package archenoah.web.setup.form;


import java.applet.Applet;
import java.applet.AudioClip;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TabSheet.Tab;

public class Constr_Setup extends CustomComponent  {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	public Button btn_next;
	@AutoGenerated
	public Button btn_back;
	@AutoGenerated
	public Button btn_close;
	@AutoGenerated
	public TabSheet tab;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	


	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


	public AudioClip sound;
	
	
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	
	
	
	//Forms
	
	public AGB agb;
	public Setup_Datenbank_Application Setup_DB;
	public Setup_Allgemeine_Einstellungen Setup_Allgemeine_Einstellungen;
	public Setup_AdminKonto Setup_Adminkonto;
	public Setup_Abschliessen Setup_Abschluss;
	public Willkommen w;
	// Tabs
	public final Tab Tab_Willkommen;
	public final Tab Tab_AGB;	
	public final Tab Tab_Setup_Database;
	public final Tab Tab_Setup_Allgemeine_Einstellungen;
	public final Tab Tab_Setup_Admin_Konto_Einstellungen;
	public final Tab Tab_Setup_LDAP_Einstellungen;
	public final Tab Tab_Setup_Abschluss;
	
	public HorizontalLayout HLb ;
	public HorizontalLayout HLc ;
	public HorizontalLayout HLd ;
	//public final Tab Tab_Setup_Schedelur;	
	
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Constr_Setup() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

	
		
		// TODO add user code here
	
		
		
		// Aufbau der Setup tabs
		
		
		
		
		// Willkommen
		
		HorizontalLayout HL = new HorizontalLayout();
		
		HL.setSizeFull();
	 w = new Willkommen();
		HL.addComponent(w);
		HL.setComponentAlignment(w, Alignment.TOP_CENTER);
		
		
		Tab_Willkommen = tab.addTab(HL, "Willkommen");
		Tab_Willkommen.setClosable(false);
		
		btn_back.setEnabled(false);
		
		// AGB 
		
		agb = new AGB();
		
		HorizontalLayout HLa = new HorizontalLayout();
		
		HLa.setSizeFull();
		
		HLa.addComponent(agb);
		HLa.setComponentAlignment(agb, Alignment.TOP_CENTER);
		
		
		Tab_AGB = tab.addTab(HLa, "AGB");
		Tab_AGB.setClosable(false);
		Tab_AGB.setEnabled(false);
		
		
		
		// Installer Database
		
		Setup_DB = new Setup_Datenbank_Application();
		
		
		HLb = new HorizontalLayout();
		
		HLb.setSizeFull();
		
		HLb.addComponent(Setup_DB);
		HLb.setComponentAlignment(Setup_DB, Alignment.TOP_CENTER);
		
		
		Tab_Setup_Database = tab.addTab(HLb, "Setup Datenbank");
		Tab_Setup_Database.setClosable(false);
		Tab_Setup_Database.setEnabled(false);
		
		
		
		// Allgemeine Einstellungen
		
		Setup_Allgemeine_Einstellungen = new Setup_Allgemeine_Einstellungen();
		
		
		HLc = new HorizontalLayout();
		
		HLc.setSizeFull();
		
		HLc.addComponent(Setup_Allgemeine_Einstellungen);
		HLc.setComponentAlignment(Setup_Allgemeine_Einstellungen, Alignment.TOP_CENTER);
		
		
		Tab_Setup_Allgemeine_Einstellungen = tab.addTab(HLc, "Allgemeine Einstellungen");
		Tab_Setup_Allgemeine_Einstellungen.setClosable(false);
		Tab_Setup_Allgemeine_Einstellungen.setEnabled(false);
		
		
		
		
		
		
		
		
		
		
		
		// Admin Konto Einstellungen
		
		Setup_Adminkonto = new Setup_AdminKonto();
		
		
		HLc = new HorizontalLayout();
		
		HLc.setSizeFull();
		
		HLc.addComponent(Setup_Adminkonto);
		HLc.setComponentAlignment(Setup_Adminkonto, Alignment.TOP_CENTER);
		
		
		Tab_Setup_Admin_Konto_Einstellungen = tab.addTab(HLc, "Adminkonto Einrichtung");
		Tab_Setup_Admin_Konto_Einstellungen.setClosable(false);
		Tab_Setup_Admin_Konto_Einstellungen.setEnabled(false);
		
		
		
		//LDAP Einstellungen
		HLc = new HorizontalLayout();
		HLc.setSizeFull();
		
		
		Tab_Setup_LDAP_Einstellungen = tab.addTab(HLc, "LDAP Einstellung");
		Tab_Setup_LDAP_Einstellungen.setClosable(false);
		Tab_Setup_LDAP_Einstellungen.setEnabled(false);
		
		//Abschluss
		Setup_Abschluss = new Setup_Abschliessen();
		Setup_Abschluss.progBar.setVisible(false);
		HLc = new HorizontalLayout();
		HLc.setSizeFull();
		
		HLc.addComponent(Setup_Abschluss);
		HLc.setComponentAlignment(Setup_Abschluss, Alignment.TOP_CENTER);
				
				
		Tab_Setup_Abschluss = tab.addTab(HLc, "Abschluss der Installation");
		Tab_Setup_Abschluss.setClosable(false);
		Tab_Setup_Abschluss.setEnabled(false);
	
		btn_next.setEnabled(false);
		
		
		
	
	}

	private void musik_ini()
	{
		 // Installer Musik
		 
		 
		
		URL Pfad_URL = getClass ().getProtectionDomain().getCodeSource().getLocation ();
		
		String P_temp =Pfad_URL.toString();
		
		String Pad =P_temp.substring (6, P_temp.length() - 23);
		
		
		String pfad = Pad.replace("%20", " ");
		pfad = pfad +"sound/1.wav";
		
		
		
		File f = new File(pfad );
		sound = null;
		try {
			
			sound = Applet.newAudioClip( f.toURL() );
			
		
		
		} catch (MalformedURLException e) {
			// TODO Automatisch generierter Erfassungsblock
			e.printStackTrace();
		}
		
		 
		 
		
		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("1024px");
		mainLayout.setHeight("600px");
		
		
		// top-level component properties
		setWidth("1024px");
		setHeight("600px");
		
		// tab
		tab = new TabSheet();
		tab.setImmediate(false);
		tab.setWidth("982px");
		tab.setHeight("440px");
		mainLayout.addComponent(tab, "top:20.0px;left:20.0px;");
		
		// btn_close
		btn_close = new Button();
		btn_close.setCaption("Abbrechen");
		btn_close.setImmediate(true);
		btn_close.setWidth("180px");
		btn_close.setHeight("-1px");
		mainLayout.addComponent(btn_close, "top:480.0px;left:103.0px;");
		
		// btn_back
		btn_back = new Button();
		btn_back.setCaption("Zurück");
		btn_back.setImmediate(true);
		btn_back.setWidth("180px");
		btn_back.setHeight("-1px");
		mainLayout.addComponent(btn_back, "top:480.0px;left:391.0px;");
		
		// btn_next
		btn_next = new Button();
		btn_next.setCaption("Weiter");
		btn_next.setImmediate(true);
		btn_next.setWidth("180px");
		btn_next.setHeight("-1px");
		mainLayout.addComponent(btn_next, "top:480.0px;left:650.0px;");
		
		return mainLayout;
	}
	
	
	
	

}
