package archenoah.web.setup.form;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class Popup_Neuer_Benutzer_Erstellen extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	public Button btn_Benutzer_Erstellen;
	@AutoGenerated
	public PasswordField txt_new_passwort_2;
	@AutoGenerated
	public PasswordField txt_new_passwort_1;
	@AutoGenerated
	public TextField txt_new_user;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_2;
	@AutoGenerated
	public TextField txt_admin_user;
	@AutoGenerated
	public PasswordField txt_admin_pass;
	@AutoGenerated
	private Label label_1;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Popup_Neuer_Benutzer_Erstellen() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("240px");
		mainLayout.setHeight("420px");

		
		// top-level component properties
		setWidth("240px");
		setHeight("420px");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("<h3>Neuen Benutzer Erstellen</h3>");
		label_1.setContentMode(label_1.CONTENT_XHTML);
		mainLayout.addComponent(label_1, "top:20.0px;left:33.0px;");
		
		// panel_1
		panel_1 = buildPanel_1();
		mainLayout.addComponent(panel_1, "top:66.0px;left:20.0px;");
		
		// txt_new_user
		txt_new_user = new TextField();
		txt_new_user.setCaption("Neuer Benutzername");
		txt_new_user.setImmediate(false);
		txt_new_user.setWidth("-1px");
		txt_new_user.setHeight("-1px");
		txt_new_user.setTabIndex(14);
		txt_new_user.setInputPrompt("Neuer Benutzer");
	
		mainLayout.addComponent(txt_new_user, "top:251.0px;left:53.0px;");
		
		// txt_new_passwort_1
		txt_new_passwort_1 = new PasswordField();
		txt_new_passwort_1.setCaption("Passwort ");
		txt_new_passwort_1.setImmediate(false);
		txt_new_passwort_1.setWidth("-1px");
		txt_new_passwort_1.setHeight("-1px");
		txt_new_passwort_1.setTabIndex(15);
		txt_new_passwort_1.setInputPrompt("*********");
		mainLayout.addComponent(txt_new_passwort_1, "top:295.0px;left:53.0px;");
		
		// txt_new_passwort_2
		txt_new_passwort_2 = new PasswordField();
		txt_new_passwort_2.setCaption("Passwort  Wiederholung");
		txt_new_passwort_2.setImmediate(false);
		txt_new_passwort_2.setWidth("-1px");
		txt_new_passwort_2.setHeight("-1px");
		txt_new_passwort_2.setTabIndex(16);
		txt_new_passwort_2.setInputPrompt("*********");
		mainLayout.addComponent(txt_new_passwort_2, "top:341.0px;left:53.0px;");
		
		// btn_Benutzer_Erstellen
		btn_Benutzer_Erstellen = new Button();
		btn_Benutzer_Erstellen.setCaption("Benutzer Erstellen");
		btn_Benutzer_Erstellen.setImmediate(true);
		btn_Benutzer_Erstellen.setWidth("174px");
		btn_Benutzer_Erstellen.setHeight("-1px");
		btn_Benutzer_Erstellen.setTabIndex(17);
		mainLayout.addComponent(btn_Benutzer_Erstellen,
				"top:380.0px;left:34.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setCaption("Root Zugangsdaten");
		panel_1.setImmediate(false);
		panel_1.setWidth("200px");
		panel_1.setHeight("160px");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		panel_1.setContent(verticalLayout_1);
		
		return panel_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("100.0%");
		verticalLayout_1.setMargin(false);
		
		// absoluteLayout_2
		absoluteLayout_2 = buildAbsoluteLayout_2();
		verticalLayout_1.addComponent(absoluteLayout_2);
		
		return verticalLayout_1;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_2() {
		// common part: create layout
		absoluteLayout_2 = new AbsoluteLayout();
		absoluteLayout_2.setImmediate(false);
		absoluteLayout_2.setWidth("196px");
		absoluteLayout_2.setHeight("139px");

		
		// txt_admin_pass
		txt_admin_pass = new PasswordField();
		txt_admin_pass.setCaption("Root Passwort");
		txt_admin_pass.setImmediate(false);
		txt_admin_pass.setWidth("-1px");
		txt_admin_pass.setHeight("-1px");
		txt_admin_pass.setTabIndex(13);
		txt_admin_pass.setInputPrompt("***********");
		absoluteLayout_2
				.addComponent(txt_admin_pass, "top:77.0px;left:33.0px;");
		
		// txt_admin_user
		txt_admin_user = new TextField();
		txt_admin_user.setCaption("Root Username");
		txt_admin_user.setImmediate(false);
		txt_admin_user.setWidth("-1px");
		txt_admin_user.setHeight("-1px");
		txt_admin_user.setTabIndex(12);
		txt_admin_user.setInputPrompt("dba");

		absoluteLayout_2
				.addComponent(txt_admin_user, "top:27.0px;left:32.0px;");
		
		return absoluteLayout_2;
	}

}
