package archenoah.web.setup.form;

import java.util.HashMap;
import java.util.Map;



import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class Setup_Allgemeine_Einstellungen extends CustomComponent {

	@AutoGenerated
	public AbsoluteLayout mainLayout;
	@AutoGenerated
	public Panel panel_3;
	@AutoGenerated
	public VerticalLayout verticalLayout_2;
	@AutoGenerated
	public TextField txt_smtp_server_port;
	@AutoGenerated
	public PasswordField psw_smtppasswort;
	@AutoGenerated
	public TextField txt_smtp_server_username;
	@AutoGenerated
	public TextField txt_smtp_server_adresse;
	@AutoGenerated
	public Panel panel_4;
	@AutoGenerated
	public VerticalLayout verticalLayout_3;
	@AutoGenerated
	public TextField txt_max_faild_login_ip;
	@AutoGenerated
	public TextField txt_max_faild_login_acc;
	@AutoGenerated
	public TextField txt_server_email;
	@AutoGenerated
	public TextField txt_serveradresse;
	@AutoGenerated
	public Button btn_save;
	@AutoGenerated
	public Label label_1;
	
	public Map<Object, String> ValidateMap;
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Setup_Allgemeine_Einstellungen() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		txt_smtp_server_port.setValue("25");
		txt_max_faild_login_acc.setValue("5");
		txt_max_faild_login_ip.setValue("10");
		txt_smtp_server_adresse.focus();
		
		Validate();
		// TODO add user code here
	}
	
	
	
	private void Validate()
	{
	
		Set_Validate_Map();
	}
	private void Set_Validate_Map()
	{
		ValidateMap = new HashMap<>();
		ValidateMap.put(txt_smtp_server_adresse,"txt_smtp_server_adresse");
		ValidateMap.put(txt_smtp_server_username,"txt_smtp_server_username");
		ValidateMap.put(txt_smtp_server_port,"txt_smtp_server_port");
		ValidateMap.put(txt_serveradresse,"txt_serveradresse");
		ValidateMap.put(txt_server_email,"txt_server_email");
		ValidateMap.put(txt_max_faild_login_acc,"txt_max_faild_login_acc");
		ValidateMap.put(txt_max_faild_login_ip,"txt_max_faild_login_ip");
		ValidateMap.put(psw_smtppasswort,"psw_smtppasswort");	
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("840px");
		mainLayout.setHeight("360px");
	
		
		// top-level component properties
		setWidth("840px");
		setHeight("360px");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("<h3>Setup Allgemeine Einstellungen</h3>");
		label_1.setContentMode(label_1.CONTENT_XHTML);
		mainLayout.addComponent(label_1, "top:0.0px;left:300.0px;");
		
		// btn_save
		btn_save = new Button();
		btn_save.setCaption("Daten Übernehmen");
		btn_save.setImmediate(true);
		btn_save.setWidth("200px");
		btn_save.setHeight("-1px");
		btn_save.setTabIndex(6);
		mainLayout.addComponent(btn_save, "top:300.0px;left:300.0px;");
		
		// panel_4
		panel_4 = buildPanel_4();
		mainLayout.addComponent(panel_4, "top:60.0px;left:420.0px;");
		
		// panel_3
		panel_3 = buildPanel_3();
		mainLayout.addComponent(panel_3, "top:60.0px;left:180.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_4() {
		// common part: create layout
		panel_4 = new Panel();
		panel_4.setCaption("Serverdaten");
		panel_4.setImmediate(false);
		panel_4.setWidth("220px");
		panel_4.setHeight("220px");
		
		// verticalLayout_3
		verticalLayout_3 = buildVerticalLayout_3();
		panel_4.setContent(verticalLayout_3);
		
		return panel_4;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_3() {
		// common part: create layout
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("100.0%");
		verticalLayout_3.setHeight("100.0%");
		verticalLayout_3.setMargin(false);
		
		// txt_serveradresse
		txt_serveradresse = new TextField();
		txt_serveradresse.setCaption("Server Adresse");
		txt_serveradresse.setImmediate(false);
		txt_serveradresse.setWidth("-1px");
		txt_serveradresse.setHeight("-1px");
		txt_serveradresse.setTabIndex(4);
		txt_serveradresse.setInputPrompt("isconet.de");
	
		verticalLayout_3.addComponent(txt_serveradresse);
		verticalLayout_3.setComponentAlignment(txt_serveradresse,
				new Alignment(48));
		
		// txt_server_email
		txt_server_email = new TextField();
		txt_server_email.setCaption("Server Email Adresse");
		txt_server_email.setImmediate(false);
		txt_server_email.setWidth("-1px");
		txt_server_email.setHeight("-1px");
		txt_server_email.setTabIndex(5);
		txt_server_email.setInputPrompt("beispiel@isconet.de");
	
		verticalLayout_3.addComponent(txt_server_email);
		verticalLayout_3.setComponentAlignment(txt_server_email, new Alignment(
				20));
		
		// txt_max_faild_login_acc
		txt_max_faild_login_acc = new TextField();
		txt_max_faild_login_acc.setCaption("Max Login Faild(Account Sperren)");
		txt_max_faild_login_acc.setImmediate(false);
		txt_max_faild_login_acc.setWidth("-1px");
		txt_max_faild_login_acc.setHeight("-1px");
		txt_max_faild_login_acc.setTabIndex(400);
		txt_max_faild_login_acc.setInputPrompt("5");

		verticalLayout_3.addComponent(txt_max_faild_login_acc);
		verticalLayout_3.setComponentAlignment(txt_max_faild_login_acc,
				new Alignment(20));
		
		// txt_max_faild_login_ip
		txt_max_faild_login_ip = new TextField();
		txt_max_faild_login_ip.setCaption("Max Login Faild(IP Sperren)");
		txt_max_faild_login_ip.setImmediate(false);
		txt_max_faild_login_ip.setWidth("-1px");
		txt_max_faild_login_ip.setHeight("-1px");
		txt_max_faild_login_ip.setTabIndex(200);
		txt_max_faild_login_ip.setInputPrompt("10");
		
		verticalLayout_3.addComponent(txt_max_faild_login_ip);
		verticalLayout_3.setComponentAlignment(txt_max_faild_login_ip,
				new Alignment(20));
		
		return verticalLayout_3;
	}

	@AutoGenerated
	private Panel buildPanel_3() {
		// common part: create layout
		panel_3 = new Panel();
		panel_3.setCaption("SMTP Daten");
		panel_3.setImmediate(false);
		panel_3.setWidth("220px");
		panel_3.setHeight("220px");
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		panel_3.setContent(verticalLayout_2);
		
		return panel_3;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(false);
		
		// txt_smtp_server_adresse
		txt_smtp_server_adresse = new TextField();
		txt_smtp_server_adresse.setCaption("SMTP Server Adresse");
		txt_smtp_server_adresse.setImmediate(false);
		txt_smtp_server_adresse.setWidth("-1px");
		txt_smtp_server_adresse.setHeight("-1px");
		txt_smtp_server_adresse.setTabIndex(1);
		txt_smtp_server_adresse.setInputPrompt("smtp.strato.de");
	
		verticalLayout_2.addComponent(txt_smtp_server_adresse);
		verticalLayout_2.setComponentAlignment(txt_smtp_server_adresse,
				new Alignment(48));
		
		// txt_smtp_server_username
		txt_smtp_server_username = new TextField();
		txt_smtp_server_username.setCaption("SMTP Username");
		txt_smtp_server_username.setImmediate(false);
		txt_smtp_server_username.setWidth("-1px");
		txt_smtp_server_username.setHeight("-1px");
		txt_smtp_server_username.setTabIndex(2);
		txt_smtp_server_username.setInputPrompt("Musteruser");

		verticalLayout_2.addComponent(txt_smtp_server_username);
		verticalLayout_2.setComponentAlignment(txt_smtp_server_username,
				new Alignment(20));
		
		// psw_smtppasswort
		psw_smtppasswort = new PasswordField();
		psw_smtppasswort.setCaption("SMTP Passwort");
		psw_smtppasswort.setImmediate(false);
		psw_smtppasswort.setWidth("-1px");
		psw_smtppasswort.setHeight("-1px");
		psw_smtppasswort.setTabIndex(3);
		psw_smtppasswort.setInputPrompt("0000000000");
		verticalLayout_2.addComponent(psw_smtppasswort);
		verticalLayout_2.setComponentAlignment(psw_smtppasswort, new Alignment(
				20));
		
		// txt_smtp_server_port
		txt_smtp_server_port = new TextField();
		txt_smtp_server_port.setCaption("SMTP Port");
		txt_smtp_server_port.setImmediate(false);
		txt_smtp_server_port.setWidth("-1px");
		txt_smtp_server_port.setHeight("-1px");
		txt_smtp_server_port.setTabIndex(100);
		txt_smtp_server_port.setInputPrompt("25");
	
		verticalLayout_2.addComponent(txt_smtp_server_port);
		verticalLayout_2.setComponentAlignment(txt_smtp_server_port,
				new Alignment(20));
		
		return verticalLayout_2;
	}

}
