package archenoah.web.normal.main.Menuepunkte.Individuelle.Stammdaten.Krankenschwesternverwaltung.forms;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import archenoah.config.CMS_Config_Std;
import archenoah.lib.custom.MyUtils;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.vaadin.Components.Combo.combo;
import archenoah.lib.vaadin.Components.Combo.nativecombo;
import archenoah.lib.vaadin.Components.Validators.ContextHelper;
import archenoah.lib.vaadin.Components.Validators.RegexValidator;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Tab_Menue_Item;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Window_Button;
import archenoah.lib.vaadin.Forms_Builder.Form_Bind;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.lib.vaadin.MenuBerechtigung.Rechteholen;
import archenoah.lib.vaadin.resources.Icons;
import archenoah.lib.vaadin.valchecker.val_checker4;
import archenoah.web.normal.UserInfo.UserData;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Stammdaten.Benutzerverwaltung.data_view_benutzerverwaltung;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Stammdaten.Krankenschwesternverwaltung.components.NurseFirmComponent;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Stammdaten.Krankenschwesternverwaltung.components.UserEmploymentComponent;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Stammdaten.Ärztverwaltung.Form.Validatoren.Custom_Validator_tel;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Item;
import com.vaadin.data.validator.EmailValidator;
import com.vaadin.event.FieldEvents.FocusEvent;
import com.vaadin.event.FieldEvents.FocusListener;
import com.vaadin.server.ExternalResource;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

public class form_nurse_insert_edit extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private VerticalLayout mainLayout;
    @AutoGenerated
    private Button btn_save;
    @AutoGenerated
    private TabSheet tabs;
    @AutoGenerated
    private UserEmploymentComponent employments;
    @AutoGenerated
    private NurseFirmComponent firms;
    @AutoGenerated
    private HorizontalLayout layoutData;
    @AutoGenerated
    private VerticalLayout verticalLayout_5;
    @AutoGenerated
    private VerticalLayout verticalLayout_8;
    @AutoGenerated
    private Button btn_email;
    @AutoGenerated
    private Button btn_g_maps;
    @AutoGenerated
    private Panel pan_anschrift;
    @AutoGenerated
    private VerticalLayout verticalLayout_7;
    @AutoGenerated
    private NativeSelect ns_countrycode;
    @AutoGenerated
    private TextField txt_ort;
    @AutoGenerated
    private TextField txt_plz;
    @AutoGenerated
    private TextField txt_Strasse;
    @AutoGenerated
    private VerticalLayout verticalLayout_4;
    @AutoGenerated
    private Panel pan_erreichbarkeit;
    @AutoGenerated
    private VerticalLayout verticalLayout_6;
    @AutoGenerated
    private TextField txt_handy;
    @AutoGenerated
    private TextField txt_tel;
    @AutoGenerated
    private TextField txt_email;
    @AutoGenerated
    private Panel pan_acc_id;
    @AutoGenerated
    private VerticalLayout verticalLayout_2;
    @AutoGenerated
    private TextField txt_user_id;
    @AutoGenerated
    private Panel pan_grund;
    @AutoGenerated
    private VerticalLayout verticalLayout_3;
    @AutoGenerated
    private TextField txt_vorname;
    @AutoGenerated
    private TextField txt_name;
    @AutoGenerated
    private NativeSelect ns_anrede;
    @AutoGenerated
    private TextField txt_titel;
    @AutoGenerated
    private HorizontalLayout horizontalLayout_2;
    @AutoGenerated
    private Panel pann_acczuw;
    @AutoGenerated
    private HorizontalLayout horizontalLayout_3;
    @AutoGenerated
    private Button btn_zuweisung;
    @AutoGenerated
    private ComboBox cb_benutzer;
    @AutoGenerated
    private Button btn_benutzerverwaltung;
    
    
    
    

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */

    /**************** --> Allgemein <--- ********************/
    org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(this.getClass());
    
    // Allgemein
    private String Exportname;
    // Datenbank
    private Map<Object, String> DBMap;
    private Map<Object, String> DBMap_SD;
    private Map<Object, String> ValidateMap;
    private DBClass db;

    private Form_Bind fb;
    private String Form_ID = "";
    // Berrechtigung
    private int ACC_ID;
    private int Lesen;
    private int Schreiben;
    private int Erstellen;
    private int Edit;
    private int Löschen;

    private MenuItem Temp_Menü = null;

    private Button Temp_Btn = null;
    private String Type = "nurse";
    private final HashMap<String, HashMap<String, String>> caseMap = new HashMap<String, HashMap<String, String>>();
    /******************************************************/
    /**************** --> Tabsheetvars <--- *****************/
    private TabSheet tab = null;

    /******************************************************/
    /**************** --> Windowvars <--- *******************/
    private Window win = null;
    /******************************************************/
    /******************* --> Custom <--- ********************/
    /******************************************************/

    boolean showEmployments = false;
    
    /************ ----->Einstellungen<-- ********************/
//    private final String LNG_FRM_ID = "11";
    private final String BER_MEN_ID = "";
    private final String Windows_Height = "620px";
    private final String Windows_Width = "680px";
    private I18nManager i18n;

    /******************************************************/

    public form_nurse_insert_edit(MenuItem Arg_Menü, String Arg_Form_ID) {
	Temp_Menü = Arg_Menü;
	Form_ID = Arg_Form_ID;

    }

    public form_nurse_insert_edit(Button Arg_btn, String Arg_Form_ID) {

	Temp_Btn = Arg_btn;
	Form_ID = Arg_Form_ID;

    }

    public form_nurse_insert_edit(MenuItem Arg_Menü, String Arg_Form_ID, String type) {
	Temp_Menü = Arg_Menü;
	Form_ID = Arg_Form_ID;
	Type = type;

    }

    public form_nurse_insert_edit(Button Arg_btn, String Arg_Form_ID, String type) {

	Temp_Btn = Arg_btn;
	Form_ID = Arg_Form_ID;
	Type = type;

    }

    /***************************** ---> Feste Funtionen<--- **************************************/

    /********* INIT-Window ************/
    public void Init_Class_Window() {
	if (Windows_Height.equals("") == true || Windows_Width.equals("") == true) {
	    System.out.println("Form Einstellung Fehlt: !!!");
	    return;
	}

	Standard_Init();

	if (Temp_Menü != null) {
	    String Recourcename = Temp_Menü.getIcon().toString();
	    Recourcename = Recourcename.substring(0, Recourcename.length() - 12) + "white-16.png";

	    Exportname = Temp_Menü.getText();
	    Build_Window_Button bwb = new Build_Window_Button(Temp_Menü.getText(), mainLayout, Windows_Height, Windows_Width,
		    new ThemeResource(Recourcename));
	    win = bwb.ReturnWindow();
	}
	if (Temp_Btn != null) {
	    Exportname = Temp_Btn.getCaption();
	    Build_Window_Button bwb = new Build_Window_Button(Temp_Btn.getCaption(), mainLayout, Windows_Height, Windows_Width,
		    Temp_Btn.getIcon());
	    win = bwb.ReturnWindow();
	}

    }

    /********* INIT-Tray ************/
    public void Init_Class_Tab(TabSheet Arg_tab) {

	Standard_Init();
	tab = Arg_tab;
	if (Temp_Menü != null) {
	    Exportname = Temp_Menü.getText();
	    Build_Tab_Menue_Item bt = new Build_Tab_Menue_Item(Arg_tab, Temp_Menü.getText(), mainLayout, Temp_Menü.getIcon());
	}
	if (Temp_Btn != null) {
	    Exportname = Temp_Btn.getCaption();
	    Build_Tab_Menue_Item bt = new Build_Tab_Menue_Item(Arg_tab, Temp_Btn.getCaption(), mainLayout, Temp_Btn.getIcon());
	}

    }
    
    public Window getWindow() {
        return win;
    }
    
    /********* Init-Standard ************/
    private void Standard_Init() {

	generateCaseMap();

	buildMainLayout();
	i18n = new I18nManager(this);

	Set_DB_Map();
	Set_DB_Map_STD();

	Set_Validierer();
	Set_Validate_Map();

	/********** Custom Fill Function *******************/
	Popup_Combo_Nurse();
	Anrede_holen();
	fillCountrycode();

	/***************************************************/
	txt_user_id.setReadOnly(true);
	
	// migrated from database
	btn_g_maps.setIcon(Icons.Other.maps);
	btn_zuweisung.setIcon(Icons.White.add_16);
	btn_email.setIcon(Icons.White.mail_16);
	btn_save.setIcon(Icons.White.save_16);

	ns_anrede.setRequired(true);
	txt_name.setRequired(true);
	txt_vorname.setRequired(true);
	txt_email.setRequired(true);
	txt_user_id.setRequired(true);

	new ContextHelper(txt_plz, "<h3>00000 oder 0000<br></h3>");
	new RegexValidator(txt_plz, "\\d{5}|\\d{4}", "00000 oder 0000", null, false);
	// migration end
	
	UserData ud = UserData.get();
	showEmployments = ud.hasGroup(1)
        || ud.getCS().isCS()
        || ud.getHR().isHR();
	
	
	employments.setVisible(showEmployments);
	tabs.getTab(employments).setVisible(showEmployments);
	
	
	if (Form_ID != "") {
	    txt_user_id.setReadOnly(false);
	    Forms_Fill();
	    txt_user_id.setReadOnly(true);

	    cb_benutzer.setEnabled(false);
	    btn_zuweisung.setEnabled(false);
	    
	    try {
	        firms.setParentId(Integer.parseInt(Form_ID));
        } catch (Exception e) {
            Integer hash = new Date().hashCode();
            log.error("error parsing formId for firms component! Form_ID: {}, saved with temp parent of: {}", Form_ID, hash);
            firms.setParentId(hash);
        }
	    
	    
	} else {
	    toggleFields(false);
	}

	event();

	// win.addAction(new ClickShortcut(btn_save, KeyCode.ENTER));
	i18n.refresh();

    }

    /*********************************/

    private void toggleFields(boolean enabled) {
	txt_titel.setEnabled(enabled);
	ns_anrede.setEnabled(enabled);
	txt_name.setEnabled(enabled);
	txt_vorname.setEnabled(enabled);
	txt_user_id.setEnabled(enabled);
	txt_email.setEnabled(enabled);
	txt_tel.setEnabled(enabled);
	txt_handy.setEnabled(enabled);
	ns_countrycode.setEnabled(enabled);
	txt_plz.setEnabled(enabled);
	txt_Strasse.setEnabled(enabled);
	txt_ort.setEnabled(enabled);
	btn_g_maps.setEnabled(enabled);
	btn_email.setEnabled(enabled);
	btn_save.setEnabled(enabled);
    }

    /*************************** Events *******************************/

    private void event() {

	btn_save.addClickListener(new ClickListener() {

	    @Override
	    public void buttonClick(ClickEvent event) {
		// TODO Automatisch generierter Methodenstub

		if (Validate_Test() == false) {
		    I18nManager.global(I18nGlobalNotifiers.fields_empty);
		    return;
		}

		if (Form_ID.equals("")) {
		    Integer fid = Forms_Insert();
		    Form_ID = Integer.toString(fid);
		    
		    firms.save(fid);
		    
		    if(showEmployments && txt_user_id.getValue() != null && !"".equals(txt_user_id.getValue())) {
		        employments.save(Integer.parseInt(txt_user_id.getValue()));
		    }
		    

		} else {
		    
		    firms.save();
		    if(showEmployments) {
		        employments.save();
		    }
		    Forms_Update();
		}

		UI.getCurrent().getUI().removeWindow(win);

	    }

	});

	btn_email.addClickListener(new ClickListener() {

	    @Override
	    public void buttonClick(ClickEvent event) {
		// TODO Automatisch generierter Methodenstub
		Neue_Email();
	    }
	});

	btn_g_maps.addClickListener(new ClickListener() {

	    @Override
	    public void buttonClick(ClickEvent event) {
		// TODO Automatisch generierter Methodenstub
		Adresse_in_Goolemaps_Anzeigen();
	    }
	});

	btn_benutzerverwaltung.addClickListener(new ClickListener() {

	    @Override
	    public void buttonClick(ClickEvent event) {
		// TODO Automatisch generierter Methodenstub

		data_view_benutzerverwaltung vb = new data_view_benutzerverwaltung(event.getButton());
		vb.Set_ID("12");

		vb.Init_Class_Window();

	    }
	});

	cb_benutzer.addFocusListener(new FocusListener() {

	    @Override
	    public void focus(FocusEvent event) {
		// TODO Automatisch generierter Methodenstub
		Popup_Combo_Nurse();
	    }
	});

	btn_zuweisung.addClickListener(new ClickListener() {

	    @Override
	    public void buttonClick(ClickEvent event) {
		// TODO Automatisch generierter Methodenstub

		if (cb_benutzer.getValue() == null) {

		    return;
		}

		if (Prüfung_ID_Nurse((int) cb_benutzer.getValue()) == true) {
		    I18nManager.global(I18nGlobalNotifiers.entry_exists);
		    return;
		}

		Fill_Form((int) cb_benutzer.getValue());
		toggleFields(true);

	    }
	});

    }

    /******************************************************************/
    //    db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_arzt_stammdaten_anrede", "INNER JOIN", "cms_auth_stammdaten_user",
    //		"ASAN_ID", "AUL_ANREDE_ID");
    //	db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_stammdaten_user", "INNER JOIN",
    //		"cust_krankenschwester_stammdaten_ks", "AUL_ID", "KSK_U_ID");
    //	// db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cms_auth_stammdaten_user");
    //	/******************************************************************************/
    //	/******************************** Filter ****************************************/
    //	db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_krankenschwester_stammdaten_ks", "KSK_ID", "=", Form_ID, "");
    private void generateCaseMap() {
	HashMap<String, String> nurse = new HashMap<String, String>();
	nurse.put("table", "cust_krankenschwester_stammdaten_ks");
	nurse.put("userId", "KSK_U_ID");
	nurse.put("formId", "KSK_ID");

	HashMap<String, String> arzt = new HashMap<String, String>();
	arzt.put("table", "cust_arzt_stammdaten_arzt");
	arzt.put("userId", "ASA_U_ID");
	arzt.put("formId", "ASA_ID");

	caseMap.put("nurse", nurse);
	caseMap.put("arzt", arzt);
    }

    private void Fill_Form(final int ID) {

	db = new DBClass();
	db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
	db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cms_auth_stammdaten_user");
	db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cms_auth_stammdaten_user", "AUL_ID", "=", ID + "", "");

	Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();

	if (con.size() > 0) {

	    for (Object ItemIda : con.getItemIds()) {

		txt_user_id.setReadOnly(false);
		txt_user_id.setValue(ID + "");
		txt_user_id.setReadOnly(true);
		ns_anrede.setValue((int) con.getItem(ItemIda).getItemProperty("AUL_ANREDE_ID").getValue());
		txt_name.setValue((String) con.getItem(ItemIda).getItemProperty("AUL_NAME").getValue());
		txt_vorname.setValue((String) con.getItem(ItemIda).getItemProperty("AUL_VORNAME").getValue());
		txt_email.setValue((String) con.getItem(ItemIda).getItemProperty("AUL_EMAIL").getValue());
		txt_tel.setValue((String) con.getItem(ItemIda).getItemProperty("AUL_TEL").getValue());
	    }

	}

    }

    private boolean Prüfung_ID_Nurse(final int ID) {
	CMS_Config_Std std = CMS_Config_Std.getInstance();
	DBClass db = new DBClass();
	db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_krankenschwester_stammdaten_ks");
	db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
	db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_krankenschwester_stammdaten_ks", "KSK_U_ID", "=", "" + ID, "");

	Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();

	if (con.size() > 0) {
	    return true;
	} else {
	    return false;
	}

    }

    /************************* ---> cb Fülen <----- *************************/
    private void Anrede_holen() {
	CMS_Config_Std std = CMS_Config_Std.getInstance();

	DBClass db = new DBClass();
	db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
	db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cms_auth_stammdaten_anrede");

	nativecombo nc = new nativecombo(db.DB_Data_Get.DB_SEND_AND_GET(), ns_anrede, "ASA_ID", "ASA_NAME");

	db.DB_Data_Get.connclose();

    }

    private void fillCountrycode() {
	CMS_Config_Std std = CMS_Config_Std.getInstance();

	DBClass db = new DBClass();
	db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
	db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_countrycodes");
	db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_countrycodes", "CC_LNG", "=", "1", "");

	nativecombo nc = new nativecombo(db.DB_Data_Get.DB_SEND_AND_GET(), ns_countrycode, "CC_CODE", "CC_TEXT");

	db.DB_Data_Get.connclose();
    }

    private void Popup_Combo_Nurse() {
	CMS_Config_Std std = CMS_Config_Std.getInstance();

	DBClass db = new DBClass();
	db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("AUL_ID");
	db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(ASAN_NAME,' ',AUL_NAME,' ',AUL_VORNAME)", "Arztname");
	db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_liste_gu", "INNER JOIN", "cms_auth_stammdaten_user", "AL_U_ID",
		"AUL_ID");
	db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_arzt_stammdaten_anrede", "INNER JOIN", "cms_auth_stammdaten_user",
		"ASAN_ID", "AUL_ANREDE_ID");

	db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cms_auth_liste_gu", "AL_G_ID", "=", "12", "");
	// db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cms_auth_stammdaten_user", "AUL_AKTIV", "=", "1", "");

	try {
	    combo nc = new combo(db.DB_Data_Get.DB_SEND_AND_GET_Container(), cb_benutzer, "AUL_ID", "Arztname");
	} catch (Exception e) {

	}

	cb_benutzer.setFilteringMode(cb_benutzer.FILTERINGMODE_CONTAINS);

    }

    /************************ --> Berrechtigung <-- **************************/

    public void Set_Berrechtigung_Database() {
	if (BER_MEN_ID == "") {
	    System.out.println("Form Einstellung Fehlt: !!!");
	    return;
	}

	ACC_ID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
	Rechteholen r = new Rechteholen(ACC_ID + "");
	String[][] Asan = r.Datenholen();

	for (int i = 0; i < Asan.length; i++) {
	    if (Asan[i][0].equals(BER_MEN_ID) == true) {

		Lesen = Integer.valueOf(Asan[i][3]);

		Schreiben = Integer.valueOf(Asan[i][4]);
		Erstellen = Integer.valueOf(Asan[i][6]);
		Löschen = Integer.valueOf(Asan[i][5]);
	    }
	}
    }

    public void Set_Berrechtigung_Custom(int Arg_Lesen, int Arg_Erstellen, int Arg_Bearbeiten, int Arg_Loeschen) {
	Lesen = Arg_Lesen;
	Schreiben = Arg_Erstellen;
	Erstellen = Arg_Erstellen;
	Edit = Arg_Bearbeiten;
	Löschen = Arg_Loeschen;
	if (Erstellen == 0 | Edit == 0) {
	    btn_save.setEnabled(false);
	    btn_benutzerverwaltung.setEnabled(false);
	    btn_zuweisung.setEnabled(false);
	    cb_benutzer.setEnabled(false);
	}
    }

    /**********************************************************************/

    /************************** Einstellen **************************************/

    /******************** Database *****************/
    private void Set_DB_Map() {
	DBMap = new HashMap<>();

	// DBMap.put(ns_anrede,"cms_auth_stammdaten_user:AUL_USERNAME");
	// DBMap.put(txt_name,"cms_auth_stammdaten_user:AUL_USERNAME");
	// DBMap.put(txt_vorname,"cms_auth_stammdaten_user:AUL_USERNAME");
	// DBMap.put(txt_email,"cms_auth_stammdaten_user:AUL_USERNAME");
	// DBMap.put(txt_tel,"cms_auth_stammdaten_user:AUL_USERNAME");

	DBMap.put(txt_titel, "cust_krankenschwester_stammdaten_ks:KSK_TITEL");
	DBMap.put(txt_user_id, "cust_krankenschwester_stammdaten_ks:KSK_U_ID");
	DBMap.put(txt_handy, "cust_krankenschwester_stammdaten_ks:KSK_HANDY");

	DBMap.put(ns_countrycode, "cust_krankenschwester_stammdaten_ks:KSK_COUNTRYCODE");
	DBMap.put(txt_plz, "cust_krankenschwester_stammdaten_ks:KSK_PLZ");
	DBMap.put(txt_Strasse, "cust_krankenschwester_stammdaten_ks:KSK_STRASSE");
	DBMap.put(txt_ort, "cust_krankenschwester_stammdaten_ks:KSK_ORT");
	// DBMap.put(txt_username,"cms_auth_stammdaten_user:AUL_USERNAME");

    }

    private void Set_DB_Map_STD() {
	DBMap_SD = new HashMap<>();

	DBMap_SD.put(ns_anrede, "cms_auth_stammdaten_user:AUL_ANREDE_ID");
	DBMap_SD.put(txt_name, "cms_auth_stammdaten_user:AUL_NAME");
	DBMap_SD.put(txt_vorname, "cms_auth_stammdaten_user:AUL_VORNAME");
	DBMap_SD.put(txt_email, "cms_auth_stammdaten_user:AUL_EMAIL");
	DBMap_SD.put(txt_tel, "cms_auth_stammdaten_user:AUL_TEL");

	// DBMap.put(txt_username,"cms_auth_stammdaten_user:AUL_USERNAME");

    }

    private void Forms_Fill() {

	db = new DBClass();
	db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();

	/******************************** Table ****************************************/
	db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_arzt_stammdaten_anrede", "INNER JOIN", "cms_auth_stammdaten_user",
		"ASAN_ID", "AUL_ANREDE_ID");
	db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_stammdaten_user", "INNER JOIN", caseMap.get(Type).get("table"),
		"AUL_ID", caseMap.get(Type).get("userId"));
	/******************************************************************************/
	/******************************** Filter ****************************************/
	db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein(caseMap.get(Type).get("table"), caseMap.get(Type).get("formId"), "=", Form_ID, "");
	/******************************************************************************/

	//db.DB_Data_Get.DB_DEBUG_SQL_STRING();

	Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();
	fb = new Form_Bind();
	
	
	Item item = MyUtils.getFirstItemFromContainer(con);
	
	if(showEmployments && MyUtils.getValueFromItem(item, "KSK_U_ID", String.class) != null) {
	    employments.setParentId(Integer.parseInt(MyUtils.getValueFromItem(item, "KSK_U_ID", String.class)));         
	}
	
	for (Object ItemIda : con.getItemIds()) {
	    fb.Get_and_Fill(con, DBMap);

	    ns_anrede.setValue((int) con.getItem(ItemIda).getItemProperty("AUL_ANREDE_ID").getValue());
	    txt_name.setValue((String) con.getItem(ItemIda).getItemProperty("AUL_NAME").getValue());
	    txt_vorname.setValue((String) con.getItem(ItemIda).getItemProperty("AUL_VORNAME").getValue());
	    txt_email.setValue((String) con.getItem(ItemIda).getItemProperty("AUL_EMAIL").getValue());
	    txt_tel.setValue((String) con.getItem(ItemIda).getItemProperty("AUL_TEL").getValue());
	}
    }

    private int Forms_Insert() {
	db = new DBClass();
	fb = new Form_Bind();
	fb.Insert(db, DBMap);
	/******************************** Table ****************************************/
	db.DB_Data_Insert.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_krankenschwester_stammdaten_ks");
	/******************************************************************************/

	return db.DB_Data_Insert.DB_Insert();
    }

    private void Forms_Update() {
	db = new DBClass();
	fb = new Form_Bind();
	fb.Update(db, DBMap);

	/******************************** Table ****************************************/
	db.DB_Data_Update.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_krankenschwester_stammdaten_ks");
	/******************************************************************************/
	/******************************** Filter ****************************************/
	db.DB_Data_Update.DB_Filter.DB_WHERE_Allgemein("cust_krankenschwester_stammdaten_ks", "KSK_ID", "=", Form_ID, "");
	/******************************************************************************/
	db.DB_Data_Update.DB_Update();
	Forms_Update_stammdaten();
    }

    private void Forms_Update_stammdaten() {
	db = new DBClass();
	fb = new Form_Bind();
	fb.Update(db, DBMap_SD);

	/******************************** Table ****************************************/
	db.DB_Data_Update.DB_Tabellen.DB_set_Tabelle_Einzeln("cms_auth_stammdaten_user");
	/******************************************************************************/
	/******************************** Filter ****************************************/
	db.DB_Data_Update.DB_Filter.DB_WHERE_Allgemein("cms_auth_stammdaten_user", "AUL_ID", "=", txt_user_id.getValue(), "");
	/******************************************************************************/
	db.DB_Data_Update.DB_Update();
    }

    /***********************************************/


    /*********************** -->Validierung<-- ********************/
    private void Set_Validate_Map() {
	ValidateMap = new HashMap<>();
	// ValidateMap.put(txt_username,"");
	ValidateMap.put(txt_titel, "txt_titel");
	ValidateMap.put(ns_anrede, "ns_anrede");
	ValidateMap.put(txt_name, "txt_name");
	ValidateMap.put(txt_vorname, "txt_vorname");
	ValidateMap.put(txt_user_id, "txt_user_id");
	ValidateMap.put(txt_email, "txt_email");
	ValidateMap.put(txt_tel, "txt_tel");
	ValidateMap.put(txt_handy, "txt_handy");
	ValidateMap.put(txt_plz, "txt_plz");
	ValidateMap.put(txt_Strasse, "txt_Strasse");
	ValidateMap.put(txt_ort, "txt_ort");

    }

    private void Set_Validierer() {

	txt_email.addValidator(new EmailValidator("Die Eingabe entspricht keiner Emailadresse !"));
	// System.out.println(txt_email.getErrorMessage());
	txt_tel.addValidator(new Custom_Validator_tel());
//	txt_plz.addValidator(new Custom_Validator_plz());
	// psw_pass_1.addValidator(new Custom_Benutzerform_psw_ändern(psw_pass_1, psw_pass_2));

    }

    private boolean Validate_Test() {
	val_checker4 val = new val_checker4(ValidateMap);
	if (val.Is_Valid() == false) {
	    return false;
	} else {
	    return true;
	}

    }

    // ****************-> Spez <------****/
    private void Neue_Email() {

	if (txt_email.getValue().toString() != "") {
	    String Script = "document.location.href=\"MailTo:" + txt_email.getValue().toString() + "\"";
	    UI.getCurrent().getPage().getJavaScript().execute(Script);
	    return;
	} else {

	    I18nManager.global(I18nGlobalNotifiers.missing_mail);

	    return;
	}
    }

    private void Adresse_in_Goolemaps_Anzeigen() {
	if (txt_plz.getValue().toString() != "" && txt_Strasse.getValue().toString() != "" && txt_ort.getValue().toString() != "") {
	    String str = txt_Strasse.getValue().toString();
	    // "Brandenburgerstr.+34"

	    UI.getCurrent()
		    .getUI()
		    .getPage()
		    .open(new ExternalResource("http://maps.google.de/maps?q=" + str + ",+" + txt_plz.getValue().toString() + "+"
			    + txt_ort.getValue().toString() + ",+" +ns_countrycode.getItemCaption(ns_countrycode.getValue()) ), // URL
		    "_blank", false);

	} else {

	    I18nManager.global(I18nGlobalNotifiers.missing_address);

	    return;
	}
    }

    @AutoGenerated
    private VerticalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);
        mainLayout.setSpacing(true);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // horizontalLayout_2
        horizontalLayout_2 = buildHorizontalLayout_2();
        mainLayout.addComponent(horizontalLayout_2);
        mainLayout.setExpandRatio(horizontalLayout_2, 1.0f);
        mainLayout.setComponentAlignment(horizontalLayout_2, new Alignment(20));
        
        // tabs
        tabs = buildTabs();
        mainLayout.addComponent(tabs);
        mainLayout.setExpandRatio(tabs, 8.0f);
        mainLayout.setComponentAlignment(tabs, new Alignment(20));
        
        // btn_save
        btn_save = new Button();
        btn_save.setCaption("Speichern");
        btn_save.setImmediate(true);
        btn_save.setWidth("250px");
        btn_save.setHeight("-1px");
        mainLayout.addComponent(btn_save);
        mainLayout.setExpandRatio(btn_save, 1.0f);
        mainLayout.setComponentAlignment(btn_save, new Alignment(48));
        
        return mainLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_2() {
        // common part: create layout
        horizontalLayout_2 = new HorizontalLayout();
        horizontalLayout_2.setImmediate(false);
        horizontalLayout_2.setWidth("100.0%");
        horizontalLayout_2.setHeight("100.0%");
        horizontalLayout_2.setMargin(false);
        
        // pann_acczuw
        pann_acczuw = buildPann_acczuw();
        horizontalLayout_2.addComponent(pann_acczuw);
        horizontalLayout_2.setComponentAlignment(pann_acczuw, new Alignment(48));
        
        return horizontalLayout_2;
    }

    @AutoGenerated
    private Panel buildPann_acczuw() {
        // common part: create layout
        pann_acczuw = new Panel();
        pann_acczuw.setCaption("Account Zuweisung");
        pann_acczuw.setImmediate(false);
        pann_acczuw.setWidth("96.0%");
        pann_acczuw.setHeight("100.0%");
        
        // horizontalLayout_3
        horizontalLayout_3 = buildHorizontalLayout_3();
        pann_acczuw.setContent(horizontalLayout_3);
        
        return pann_acczuw;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_3() {
        // common part: create layout
        horizontalLayout_3 = new HorizontalLayout();
        horizontalLayout_3.setImmediate(false);
        horizontalLayout_3.setWidth("100.0%");
        horizontalLayout_3.setHeight("100.0%");
        horizontalLayout_3.setMargin(false);
        
        // btn_benutzerverwaltung
        btn_benutzerverwaltung = new Button();
        btn_benutzerverwaltung.setCaption("Benutzerverwaltung");
        btn_benutzerverwaltung.setImmediate(true);
        btn_benutzerverwaltung.setWidth("-1px");
        btn_benutzerverwaltung.setHeight("-1px");
        horizontalLayout_3.addComponent(btn_benutzerverwaltung);
        horizontalLayout_3.setComponentAlignment(btn_benutzerverwaltung, new Alignment(48));
        
        // cb_benutzer
        cb_benutzer = new ComboBox();
        cb_benutzer.setImmediate(false);
        cb_benutzer.setWidth("220px");
        cb_benutzer.setHeight("-1px");
        horizontalLayout_3.addComponent(cb_benutzer);
        horizontalLayout_3.setComponentAlignment(cb_benutzer, new Alignment(48));
        
        // btn_zuweisung
        btn_zuweisung = new Button();
        btn_zuweisung.setCaption("Benutzer zuweisen");
        btn_zuweisung.setImmediate(true);
        btn_zuweisung.setWidth("-1px");
        btn_zuweisung.setHeight("-1px");
        horizontalLayout_3.addComponent(btn_zuweisung);
        horizontalLayout_3.setComponentAlignment(btn_zuweisung, new Alignment(48));
        
        return horizontalLayout_3;
    }

    @AutoGenerated
    private TabSheet buildTabs() {
        // common part: create layout
        tabs = new TabSheet();
        tabs.setImmediate(true);
        tabs.setWidth("96.0%");
        tabs.setHeight("100.0%");
        
        // layoutData
        layoutData = buildLayoutData();
        tabs.addTab(layoutData, "Daten", null);
        
        // firms
        firms = new NurseFirmComponent();
        firms.setImmediate(false);
        firms.setWidth("100.0%");
        firms.setHeight("100.0%");
        tabs.addTab(firms, "Firmen", null);
        
        // userEmploymentComponent_1
        employments = new UserEmploymentComponent();
        employments.setImmediate(false);
        employments.setWidth("100.0%");
        employments.setHeight("100.0%");
        tabs.addTab(employments, "user_employment", null);
        
        return tabs;
    }

    @AutoGenerated
    private HorizontalLayout buildLayoutData() {
        // common part: create layout
        layoutData = new HorizontalLayout();
        layoutData.setImmediate(false);
        layoutData.setWidth("100.0%");
        layoutData.setHeight("100.0%");
        layoutData.setMargin(false);
        
        // pan_grund
        pan_grund = buildPan_grund();
        layoutData.addComponent(pan_grund);
        layoutData.setComponentAlignment(pan_grund, new Alignment(20));
        
        // verticalLayout_4
        verticalLayout_4 = buildVerticalLayout_4();
        layoutData.addComponent(verticalLayout_4);
        layoutData.setComponentAlignment(verticalLayout_4, new Alignment(20));
        
        // verticalLayout_5
        verticalLayout_5 = buildVerticalLayout_5();
        layoutData.addComponent(verticalLayout_5);
        layoutData.setComponentAlignment(verticalLayout_5, new Alignment(20));
        
        return layoutData;
    }

    @AutoGenerated
    private Panel buildPan_grund() {
        // common part: create layout
        pan_grund = new Panel();
        pan_grund.setCaption("Grunddaten");
        pan_grund.setImmediate(false);
        pan_grund.setWidth("90.0%");
        pan_grund.setHeight("250px");
        
        // verticalLayout_3
        verticalLayout_3 = buildVerticalLayout_3();
        pan_grund.setContent(verticalLayout_3);
        
        return pan_grund;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_3() {
        // common part: create layout
        verticalLayout_3 = new VerticalLayout();
        verticalLayout_3.setImmediate(false);
        verticalLayout_3.setWidth("100.0%");
        verticalLayout_3.setHeight("100.0%");
        verticalLayout_3.setMargin(false);
        
        // txt_titel
        txt_titel = new TextField();
        txt_titel.setCaption("Titel");
        txt_titel.setImmediate(false);
        txt_titel.setWidth("-1px");
        txt_titel.setHeight("-1px");
        verticalLayout_3.addComponent(txt_titel);
        verticalLayout_3.setComponentAlignment(txt_titel, new Alignment(48));
        
        // ns_anrede
        ns_anrede = new NativeSelect();
        ns_anrede.setCaption("Anrede");
        ns_anrede.setImmediate(false);
        ns_anrede.setWidth("160px");
        ns_anrede.setHeight("-1px");
        verticalLayout_3.addComponent(ns_anrede);
        verticalLayout_3.setComponentAlignment(ns_anrede, new Alignment(48));
        
        // txt_name
        txt_name = new TextField();
        txt_name.setCaption("Name");
        txt_name.setImmediate(false);
        txt_name.setWidth("-1px");
        txt_name.setHeight("-1px");
        verticalLayout_3.addComponent(txt_name);
        verticalLayout_3.setComponentAlignment(txt_name, new Alignment(48));
        
        // txt_vorname
        txt_vorname = new TextField();
        txt_vorname.setCaption("Vorname");
        txt_vorname.setImmediate(false);
        txt_vorname.setWidth("-1px");
        txt_vorname.setHeight("-1px");
        verticalLayout_3.addComponent(txt_vorname);
        verticalLayout_3.setComponentAlignment(txt_vorname, new Alignment(48));
        
        return verticalLayout_3;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_4() {
        // common part: create layout
        verticalLayout_4 = new VerticalLayout();
        verticalLayout_4.setImmediate(false);
        verticalLayout_4.setWidth("100.0%");
        verticalLayout_4.setHeight("100.0%");
        verticalLayout_4.setMargin(false);
        
        // pan_acc_id
        pan_acc_id = buildPan_acc_id();
        verticalLayout_4.addComponent(pan_acc_id);
        verticalLayout_4.setComponentAlignment(pan_acc_id, new Alignment(20));
        
        // pan_erreichbarkeit
        pan_erreichbarkeit = buildPan_erreichbarkeit();
        verticalLayout_4.addComponent(pan_erreichbarkeit);
        verticalLayout_4.setComponentAlignment(pan_erreichbarkeit, new Alignment(20));
        
        return verticalLayout_4;
    }

    @AutoGenerated
    private Panel buildPan_acc_id() {
        // common part: create layout
        pan_acc_id = new Panel();
        pan_acc_id.setCaption("Indendifikations Nummern");
        pan_acc_id.setImmediate(false);
        pan_acc_id.setWidth("80.0%");
        pan_acc_id.setHeight("150px");
        
        // verticalLayout_2
        verticalLayout_2 = buildVerticalLayout_2();
        pan_acc_id.setContent(verticalLayout_2);
        
        return pan_acc_id;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_2() {
        // common part: create layout
        verticalLayout_2 = new VerticalLayout();
        verticalLayout_2.setImmediate(false);
        verticalLayout_2.setWidth("100.0%");
        verticalLayout_2.setHeight("100.0%");
        verticalLayout_2.setMargin(false);
        
        // txt_user_id
        txt_user_id = new TextField();
        txt_user_id.setCaption("Account Zuweisungs ID");
        txt_user_id.setImmediate(false);
        txt_user_id.setWidth("80.0%");
        txt_user_id.setHeight("-1px");
        verticalLayout_2.addComponent(txt_user_id);
        verticalLayout_2.setComponentAlignment(txt_user_id, new Alignment(48));
        
        return verticalLayout_2;
    }

    @AutoGenerated
    private Panel buildPan_erreichbarkeit() {
        // common part: create layout
        pan_erreichbarkeit = new Panel();
        pan_erreichbarkeit.setCaption("Erreichbarkeit");
        pan_erreichbarkeit.setImmediate(false);
        pan_erreichbarkeit.setWidth("80.0%");
        pan_erreichbarkeit.setHeight("200px");
        
        // verticalLayout_6
        verticalLayout_6 = buildVerticalLayout_6();
        pan_erreichbarkeit.setContent(verticalLayout_6);
        
        return pan_erreichbarkeit;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_6() {
        // common part: create layout
        verticalLayout_6 = new VerticalLayout();
        verticalLayout_6.setImmediate(false);
        verticalLayout_6.setWidth("100.0%");
        verticalLayout_6.setHeight("100.0%");
        verticalLayout_6.setMargin(false);
        
        // txt_email
        txt_email = new TextField();
        txt_email.setCaption("Email");
        txt_email.setImmediate(false);
        txt_email.setWidth("-1px");
        txt_email.setHeight("-1px");
        verticalLayout_6.addComponent(txt_email);
        verticalLayout_6.setComponentAlignment(txt_email, new Alignment(48));
        
        // txt_tel
        txt_tel = new TextField();
        txt_tel.setCaption("Telefon");
        txt_tel.setImmediate(false);
        txt_tel.setWidth("-1px");
        txt_tel.setHeight("-1px");
        verticalLayout_6.addComponent(txt_tel);
        verticalLayout_6.setComponentAlignment(txt_tel, new Alignment(48));
        
        // txt_handy
        txt_handy = new TextField();
        txt_handy.setCaption("Handy");
        txt_handy.setImmediate(false);
        txt_handy.setWidth("-1px");
        txt_handy.setHeight("-1px");
        verticalLayout_6.addComponent(txt_handy);
        verticalLayout_6.setComponentAlignment(txt_handy, new Alignment(48));
        
        return verticalLayout_6;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_5() {
        // common part: create layout
        verticalLayout_5 = new VerticalLayout();
        verticalLayout_5.setImmediate(false);
        verticalLayout_5.setWidth("100.0%");
        verticalLayout_5.setHeight("100.0%");
        verticalLayout_5.setMargin(false);
        
        // pan_anschrift
        pan_anschrift = buildPan_anschrift();
        verticalLayout_5.addComponent(pan_anschrift);
        verticalLayout_5.setExpandRatio(pan_anschrift, 2.0f);
        verticalLayout_5.setComponentAlignment(pan_anschrift, new Alignment(20));
        
        // verticalLayout_8
        verticalLayout_8 = buildVerticalLayout_8();
        verticalLayout_5.addComponent(verticalLayout_8);
        verticalLayout_5.setExpandRatio(verticalLayout_8, 1.0f);
        
        return verticalLayout_5;
    }

    @AutoGenerated
    private Panel buildPan_anschrift() {
        // common part: create layout
        pan_anschrift = new Panel();
        pan_anschrift.setCaption("Anschrift");
        pan_anschrift.setImmediate(false);
        pan_anschrift.setWidth("80.0%");
        pan_anschrift.setHeight("200px");
        
        // verticalLayout_7
        verticalLayout_7 = buildVerticalLayout_7();
        pan_anschrift.setContent(verticalLayout_7);
        
        return pan_anschrift;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_7() {
        // common part: create layout
        verticalLayout_7 = new VerticalLayout();
        verticalLayout_7.setImmediate(false);
        verticalLayout_7.setWidth("100.0%");
        verticalLayout_7.setHeight("100.0%");
        verticalLayout_7.setMargin(false);
        
        // txt_Strasse
        txt_Strasse = new TextField();
        txt_Strasse.setCaption("Strasse");
        txt_Strasse.setImmediate(false);
        txt_Strasse.setWidth("-1px");
        txt_Strasse.setHeight("-1px");
        verticalLayout_7.addComponent(txt_Strasse);
        verticalLayout_7.setComponentAlignment(txt_Strasse, new Alignment(48));
        
        // txt_plz
        txt_plz = new TextField();
        txt_plz.setCaption("PLZ");
        txt_plz.setImmediate(false);
        txt_plz.setWidth("-1px");
        txt_plz.setHeight("-1px");
        verticalLayout_7.addComponent(txt_plz);
        verticalLayout_7.setComponentAlignment(txt_plz, new Alignment(48));
        
        // txt_ort
        txt_ort = new TextField();
        txt_ort.setCaption("Ort");
        txt_ort.setImmediate(false);
        txt_ort.setWidth("-1px");
        txt_ort.setHeight("-1px");
        verticalLayout_7.addComponent(txt_ort);
        verticalLayout_7.setComponentAlignment(txt_ort, new Alignment(48));
        
        // ns_countrycode
        ns_countrycode = new NativeSelect();
        ns_countrycode.setCaption("Land");
        ns_countrycode.setImmediate(false);
        ns_countrycode.setWidth("152px");
        ns_countrycode.setHeight("-1px");
        verticalLayout_7.addComponent(ns_countrycode);
        verticalLayout_7.setComponentAlignment(ns_countrycode, new Alignment(48));
        
        return verticalLayout_7;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_8() {
        // common part: create layout
        verticalLayout_8 = new VerticalLayout();
        verticalLayout_8.setImmediate(false);
        verticalLayout_8.setWidth("100.0%");
        verticalLayout_8.setHeight("100.0%");
        verticalLayout_8.setMargin(false);
        
        // btn_g_maps
        btn_g_maps = new Button();
        btn_g_maps.setCaption("Googel Maps");
        btn_g_maps.setImmediate(true);
        btn_g_maps.setWidth("-1px");
        btn_g_maps.setHeight("-1px");
        verticalLayout_8.addComponent(btn_g_maps);
        verticalLayout_8.setComponentAlignment(btn_g_maps, new Alignment(48));
        
        // btn_email
        btn_email = new Button();
        btn_email.setCaption("Email Senden");
        btn_email.setImmediate(true);
        btn_email.setWidth("-1px");
        btn_email.setHeight("-1px");
        verticalLayout_8.addComponent(btn_email);
        verticalLayout_8.setComponentAlignment(btn_email, new Alignment(48));
        
        return verticalLayout_8;
    }

}
