package archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.PackageCreator.form;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;

import archenoah.config.CMS_Config_Std;
import archenoah.lib.custom.ComponentIterator;
import archenoah.lib.custom.MyUtils;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.tool.comunication.dbclass.DBClass.CustomQuery;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Window_Button;
import archenoah.lib.vaadin.Forms_Builder.Form_Bind;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.lib.vaadin.MenuBerechtigung.Rechteholen;
import archenoah.lib.vaadin.valchecker.val_checker4;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.OpenTickets.form.OpenTicketsInsertEdit;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.PackageCreator.classes.PackageUtils;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.PackageCreator.classes.PackageUtils.RANGE;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.PackageCreator.classes.TicketContentsMover;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.PackageCreator.classes.TicketContentsMover.Action;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.PackageCreator.classes.TicketDbActions;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.PackageCreator.classes.TicketEvent;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.PackageCreator.classes.TicketEvent.TicketType;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.StandaloneSettings.form.StandaloneSettingsInsertEdit;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.ui.AbstractField;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.Window.CloseEvent;
import com.vaadin.ui.Window.CloseListener;

@SuppressWarnings({"serial", "rawtypes", "unchecked"})
public class PackageCreatorInsertEdit extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private VerticalLayout mainLayout;

    @AutoGenerated
    private HorizontalLayout buttons;

    @AutoGenerated
    private Button btn_save;

    @AutoGenerated
    private Button btn_rrule;

    @AutoGenerated
    private Button btn_cancel;

    @AutoGenerated
    private VerticalLayout main;

    @AutoGenerated
    private Panel panel_1;

    @AutoGenerated
    private VerticalLayout verticalLayout_4;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_1;

    @AutoGenerated
    private Table tblQuantities;

    @AutoGenerated
    private Table tblContents;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_2;

    @AutoGenerated
    private PopupDateField dateTicketEnd;

    @AutoGenerated
    private PopupDateField dateTicketStart;

    @AutoGenerated
    private PopupDateField dateShipping;

    

    

    

    

    

    

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */

    /**************** --> Allgemein <--- ********************/
    // Allgemein
    private CMS_Config_Std std;
    private String exportCaption;
    private org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(this.getClass());
    
    // Datenbank
    private Map<Object, String> componentMap;
    private Map<Object, String> dbMap;
    private Map<Object, String> validateMap;
    private Form_Bind fb;
    private TicketEvent ticketEvent;
    private Date ticketShippingDate;
    
    // Berrechtigung
    private int ACC_ID;
	private Integer permRead;
	private Integer permUpdate;
	private Integer permCreate;
	private Integer permDelete;

    private MenuItem tmpMenu = null;

    /******************************************************/
    /**************** --> Tabsheetvars <--- *****************/
    private TabSheet tab = null;
    /******************************************************/
    /**************** --> Windowvars <--- *******************/
    private Window win = null;
    /******************************************************/
    /******************* --> Custom <--- ********************/
    /******************************************************/
    
    private final Object[] tableColsAll = new Object[] {"nurse", "PP_PRODUCT", "patient", "project_date", "rx", "quantity_sum"};
    //use custom Cols when needed
    private Object[] tableColsContents = new Object[] {"patient", "project_date", "PP_PRODUCT", "rx", "quantity_sum"};
    private Object[] tableColsQuantiy = new Object[] {"PP_PRODUCT", "quantity_sum"};
    
    
    /************ ----->Einstellungen<-- ********************/
//    private final String formIdLng = "107";
    private final String formIdPerm = "107";
    private final String Windows_Height = "500px";
    private final String Windows_Width = "800px";
    
    private final String dataIdCol = "XX_ID";
    private final String dataTableName = "cust_XX";
    
    private Boolean wasSaved = false;
    private OpenTicketsInsertEdit openTicketWindow = null;

    private TicketContentsMover mover;

    private TicketDbActions dba;

    private I18nManager i18n;
    
    /******************************************************/


    public PackageCreatorInsertEdit(TicketEvent ticketEvent) {
        
        this.ticketEvent = ticketEvent;
    }

    /********* INIT-Window ************/
    public void init() {
        if (Windows_Height.equals("") == true || Windows_Width.equals("") == true) {
            System.out.println("Form Einstellung Fehlt: !!!");
            return;
        }

        Standard_Init();

        String fid = (String) ticketEvent.getItem().getItemProperty("nurse").getValue();
        fid = fid==null ? "" : fid;

        Build_Window_Button bwb = new Build_Window_Button(fid, mainLayout, Windows_Height, Windows_Width, null);
        win = bwb.ReturnWindow();

    }

    
    public Window getWindow(){
    	return win;
    }
    
    public TabSheet getTabSheet(){
    	return tab;
    }
    
    /********* Init-Standard ************/
    private void Standard_Init() {
        buildMainLayout();
        i18n = new I18nManager(this);
        
        std = CMS_Config_Std.getInstance();
        fb = new Form_Bind();
        ACC_ID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        
        registerComponents();

        setCustomValidators();
        fillValidateMap();

        /***************/
        setMenuPermissions();
        
        
        if (ticketEvent != null) {

            fillContent();
            
        } else {
            
            System.err.println("no event specified");
        	
        }

        
        configureComponents();
        i18n.refresh();
        
    }
    
    public Boolean wasSaved(){
        return wasSaved;
    }
    
    public OpenTicketsInsertEdit getOpenTicketWindow() {
        return openTicketWindow;
    }

    public void setOpenTicketWindow(OpenTicketsInsertEdit openTicketWindow) {
        this.openTicketWindow = openTicketWindow;
    }

    private void setSaved(Boolean saved){
        wasSaved = saved;
    }
    
 // register components for lng and validation tools
    private void registerComponents(){
    	componentMap = new HashMap<Object, String>();
    	new ComponentIterator(main).createMap(componentMap);
    }
    
    
    private void configureComponents(){
    	
    	for (Entry<Object, String> entry : componentMap.entrySet()) {
    		AbstractField field = (AbstractField) entry.getKey();
    		
			field.setImmediate(true);
			
			if(field instanceof ComboBox){
				((ComboBox)field).setFilteringMode(FilteringMode.CONTAINS);
			}

		}
    	
    	btn_rrule.setVisible(false);
    	if(ticketEvent != null && ticketEvent.getType() == TicketType.STANDALONE) {
    	    btn_rrule.setVisible(true);
    	}
    	

    	dateTicketStart.setEnabled(false);
        dateTicketStart.setStyleName("nogrey");
        dateTicketEnd.setEnabled(false);
        dateTicketEnd.setStyleName("nogrey");
    	
    	componentListeners();
    	
    	
    }
    
    /*************************** Events *******************************/

    private void componentListeners() {
        
        dateShipping.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                ticketShippingDate = dateShipping.getValue();
                
            }
        });
        
        btn_cancel.addClickListener(new ClickListener() {
            
            @Override
            public void buttonClick(ClickEvent event) {
                
                win.close();
                
            }
        });
        
        btn_rrule.addClickListener(new ClickListener() {
            
            @Override
            public void buttonClick(ClickEvent event) {
                
                log.info("item: {}", MyUtils.formatItem(ticketEvent.getItem()));
                final StandaloneSettingsInsertEdit se = new StandaloneSettingsInsertEdit(btn_rrule, Integer.toString(MyUtils.getValueFromItem(ticketEvent.getItem(), "OMS_ID", Integer.class)));
                se.setPermissionsFromDatabase();
                se.init();
                se.getWindow().addCloseListener(new CloseListener() {
                    
                    @Override
                    public void windowClose(CloseEvent e) {
                        
                        wasSaved = se.wasSaved();
                        if(wasSaved) {
                            win.close(); //cascade close listener to refresh calendar
                        }
                        
                    }
                });
                
            }
        });
        
        btn_save.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {

                if (validate() == false || tblContents.size() == 0) {
                    I18nManager.global(I18nGlobalNotifiers.fields_empty);
                    return;
                }
                
                
                
                log.info("available: {}", dba.getAvailableTickets());
                
                if(dba.getAvailableTickets() != null) {
                    
                    log.info("show messagebox");
                    
                    mover.showMessageBox(mover . new CloseAction() {
                        
                        @Override
                        public void onClose(Action action, Integer tid) {
                            
                            afterTicketCreation(btn_save, tid);
                            
                        }
                    });
                    
                }else {
                    
                    Action action = null;
                    
                    switch (ticketEvent.getType()) {

                    case PLANNED:
                        action = Action.new_nurse;
                        break;

                    case STANDALONE:
                        action = Action.new_patient;
                        break;

                    default:
                        action = Action.new_generic;
                        break;

                    } 
                    log.info("creating default ticket with action {}", action);
                    
                    afterTicketCreation(btn_save, mover.processAction(action));
                }
                
                
                

                
            }

        });

       
    }
    
    private void afterTicketCreation(Button btn, Integer tid) {
        
        log.info("afterTicketCreation tid: {}", tid);
        
        if (tid != null) {

            setSaved(true);

            OpenTicketsInsertEdit tie = new OpenTicketsInsertEdit(btn, tid.toString());
            tie.setPermissions(permCreate, permRead, permUpdate, permDelete);
            tie.init();

            setOpenTicketWindow(tie);

            win.close();

        } else {
I18nManager.global(I18nGlobalNotifiers.fields_empty);
            win.close();
        }
        
    }
    
    /******************************************************************/
    
    /************************ --> Berrechtigung <-- **************************/

    @SuppressWarnings("unused")
    public void setPermissionsFromDatabase() {
        if (formIdPerm == "") {
            System.out.println("Form Einstellung Fehlt: Berechtigung");
            return;
        }

        
        Rechteholen r = new Rechteholen(ACC_ID + "");
        String[][] perms = r.Datenholen();

        for (int i = 0; i < perms.length; i++) {
            if (perms[i][0].equals(formIdPerm) == true) {

                permRead = Integer.valueOf(perms[i][3]);
                permUpdate = Integer.valueOf(perms[i][4]);
                permCreate = Integer.valueOf(perms[i][6]);
                permDelete = Integer.valueOf(perms[i][5]);
                
            }
        }
    }

    public void setPermissions(int create, int read, int update, int delete) {

        permCreate = create;
        permRead = read;
        permUpdate = update;
        permDelete = delete;

    }

    private void setMenuPermissions() {
        Boolean c = (permCreate == 1);
        Boolean r = (permRead == 1);
        Boolean u = (permUpdate == 1);
        Boolean d = (permDelete == 1);

        btn_save.setEnabled((c||u));

    }
    
    /***********************************************/
    
    private void fillContent(){
        
        // basic fields
        dateShipping.setValue(getTicketShippingDate());
        PackageUtils.limitDatePicker(dateShipping, getTicketShippingDate(), RANGE.WEEK);
        
        dateTicketStart.setValue(PackageUtils.getTicketStartDate(ticketEvent));
        dateTicketStart.setReadOnly(true);
        dateTicketEnd.setValue(PackageUtils.getTicketEndDate(ticketEvent));
        dateTicketEnd.setReadOnly(true);
        
        // contents
        
        mover = new TicketContentsMover(true);
        dba = mover.getDbActions();
        
        if(ticketEvent.getType() == TicketType.PLANNED) {
            
            dba.setTicketData(dateTicketStart.getValue(), dateTicketEnd.getValue(), dateShipping.getValue(), ticketEvent.getNurseUserId(), null, ticketEvent.getCountryKey());
            log.info("ticketEvent.getContents() {}", ticketEvent.getContents());
            dba.setVirtualIds(ticketEvent.getContents(), "project", "project_data_id");
            
            tblContents.setContainerDataSource(dbGetContents());
            tblQuantities.setContainerDataSource(dbGetQuantities());
    	
        }else if(ticketEvent.getType() == TicketType.STANDALONE) {
            
            Container con = createStandaloneContents();
            
            dba.setTicketData(dateTicketStart.getValue(), dateTicketEnd.getValue(), dateShipping.getValue(), null, ticketEvent.getPatientId(), ticketEvent.getCountryKey());
            dba.setStandaloneContents(con);
            
            tblContents.setContainerDataSource(con);
            tblQuantities.setContainerDataSource(con);
            
            
            
        }
        
        
    	setTableColums();
    	setTableContentsHeaders();
    	setTableQuantityHeaders();
    	
    	// buttons

        Boolean saveEnabled = (permCreate == 1 || permUpdate == 1);
    	
    	btn_save.setEnabled(tblContents.size() > 0 ? saveEnabled : false);
    }
    
    private void setTableColums(){
        tblContents.setVisibleColumns(tableColsContents);
        tblQuantities.setVisibleColumns(tableColsQuantiy);
        
        tblContents.setColumnExpandRatio("nurse", 1);
        tblContents.setColumnExpandRatio("patient", 1);
        tblQuantities.setColumnExpandRatio("PSLV_NAME", 1);
    }
    
    private void setTableContentsHeaders() {

        for (Object column : tableColsAll) {
            String col = (String) column;
            tblContents.setColumnHeader(col, i18n.get(col));
        }
        
    }
    
    private void setTableQuantityHeaders() {

        for (Object column : tableColsAll) {
            String col = (String) column;
            tblQuantities.setColumnHeader(col, i18n.get(col));
        }
        
    }
    
    /******************** Database *****************/
    
    private String formatDate(Date date){
        SimpleDateFormat fmt = new SimpleDateFormat("YYYY-MM-dd");
        return fmt.format(date);
    }
    
    private Date getTicketShippingDate(){
        if(ticketShippingDate == null){
            ticketShippingDate = ticketEvent.getStart();
        }
        return ticketShippingDate;
    }
    private String getTicketShippingDateString(){
        return formatDate(getTicketShippingDate());
    }
    
//    private Date getTicketStartDate(){
//        return ticketEvent.getTicketStart().toDate();
//    }
//    private String getTicketStartDateString(){
//        return ticketEvent.getTicketStart().toString("YYYY-MM-dd");
//    }
//    
//    private Date getTicketEndDate(){
//        return ticketEvent.getTicketEnd().toDate();
//    }
//    private String getTicketEndDateString(){
//        return ticketEvent.getTicketEnd().toString("YYYY-MM-dd");
//    }
    
    private Container createStandaloneContents() {
        
        if(ticketEvent.getPatientId() == null) {
            return null;
        }
        
        //"patient", "project_date", "PP_PRODUCT", "rx", "quantity_sum"
        CustomQuery q = new DBClass().CustomQuery;
        q.setSqlString("select "
            + "\n " + "    cust_ordermanager_standalone.*"
             + "\n " + "    , CONCAT(PSA_NAME, ' ', PSL_VORNAME, ' ', PSL_NAME) AS patient"
             + "\n " + "    , NULL as project_date"
             + "\n " + "    , PP_PRODUCT"
             + "\n " + "    , PP_ID_PROJECT"
             + "\n " + "    , rx.balance as rx"
             + "\n " + "    , OMS_QUANTITY as quantity_sum"
             + "\n " + "    "
             + "\n " + "from cust_ordermanager_standalone"
             + "\n " + "LEFT JOIN cust_prescriptions_products ON OMS_ID_PRODUCT = PP_ID"
             + "\n " + "LEFT JOIN cust_patient_stammdaten_liste ON OMS_ID_PATIENT = PSL_ID"
             + "\n " + "LEFT JOIN cust_patient_stammdaten_anrede ON PSL_ANREDE = PSA_ID"
             + "\n " + "left join view_balance_rx as rx on OMS_ID_PATIENT = rx.PB_ID_PATIENT and OMS_ID_PRODUCT = rx.PB_ID_PRODUCT"
             + "\n " + "where OMS_ID_PATIENT = " + ticketEvent.getPatientId());
//        q.db.debugNextQuery(true);

        return q.query();
    }
    
    private Container dbGetContents(){
        return dbQueryContents(false);
    }
    
    private Container dbGetQuantities(){
        return dbQueryContents(true);
    }
    
    private Container dbQueryContents(Boolean group){
        
        DBClass db = new DBClass();
        
        String groupingString = group ? "GROUP BY product" : "GROUP BY project_data_id, product";
        String havingString = "HAVING (status IS NULL OR status_count < max_count)";
        
        
        db.CustomQuery.setSqlString("SELECT view_packagemanager_union_complete.*"
                + "\n" 
                + "\n" + ", CAST(SUM(IF(status IS NULL, project_quantity, 0)) AS UNSIGNED) as quantity_sum"
                + "\n" + ", COUNT(status) as status_count"
                + "\n" + ", COUNT(project_data_id) as max_count"
                + "\n" + ", PP_PRODUCT"
                + "\n" + ", rx.balance as rx"
                + "\n"
                + "\n" + " FROM view_packagemanager_union_complete"
                + "\n" + " LEFT JOIN cust_prescriptions_products on project = PP_ID_PROJECT and product = PP_ID"
                + "\n" + " LEFT JOIN view_balance_rx as rx on patient_id = rx.PB_ID_PATIENT and rx.PB_ID_PRODUCT = PP_ID"
                + "\n" + dba.getCondition()
                + "\n" + " " + groupingString
                + "\n" + " " + havingString
                + "");
        
//        db.debugNextQuery(true);

        return db.CustomQuery.query(); //MyUtils.convertIndex(db.CustomQuery.query(), "project_data_id");
        
    }


    /*********************** -->Validierung<-- ********************/
    private void fillValidateMap() {
        validateMap = new HashMap<>();
        validateMap.putAll(componentMap);
        
//        ValidateMap.put(component, "component"); // should not be needed

    }

    private void setCustomValidators() {

        // psw_pass_1.addValidator(new Custom_Benutzerform_psw_ändern(psw_pass_1, psw_pass_2));

        /******* manual actions *******/

    }

    private boolean validate() {
        val_checker4 val = new val_checker4(validateMap);
        if (val.Is_Valid() == false) {
            return false;
        } else {
            return true;
        }

    }

    @AutoGenerated
    private VerticalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setStyleName("cust_margin_half_full_none_full");
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(true);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // main
        main = buildMain();
        mainLayout.addComponent(main);
        mainLayout.setExpandRatio(main, 9.0f);
        mainLayout.setComponentAlignment(main, new Alignment(48));
        
        // buttons
        buttons = buildButtons();
        mainLayout.addComponent(buttons);
        mainLayout.setExpandRatio(buttons, 1.0f);
        mainLayout.setComponentAlignment(buttons, new Alignment(48));
        
        return mainLayout;
    }

    @AutoGenerated
    private VerticalLayout buildMain() {
        // common part: create layout
        main = new VerticalLayout();
        main.setImmediate(false);
        main.setWidth("100.0%");
        main.setHeight("100.0%");
        main.setMargin(false);
        main.setSpacing(true);
        
        // panel_1
        panel_1 = buildPanel_1();
        main.addComponent(panel_1);
        main.setComponentAlignment(panel_1, new Alignment(48));
        
        return main;
    }

    @AutoGenerated
    private Panel buildPanel_1() {
        // common part: create layout
        panel_1 = new Panel();
        panel_1.setImmediate(false);
        panel_1.setWidth("100.0%");
        panel_1.setHeight("100.0%");
        
        // verticalLayout_4
        verticalLayout_4 = buildVerticalLayout_4();
        panel_1.setContent(verticalLayout_4);
        
        return panel_1;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_4() {
        // common part: create layout
        verticalLayout_4 = new VerticalLayout();
        verticalLayout_4.setStyleName("cust_margin_half_full_none_full");
        verticalLayout_4.setImmediate(false);
        verticalLayout_4.setWidth("100.0%");
        verticalLayout_4.setHeight("100.0%");
        verticalLayout_4.setMargin(true);
        
        // horizontalLayout_2
        horizontalLayout_2 = buildHorizontalLayout_2();
        verticalLayout_4.addComponent(horizontalLayout_2);
        
        // horizontalLayout_1
        horizontalLayout_1 = buildHorizontalLayout_1();
        verticalLayout_4.addComponent(horizontalLayout_1);
        verticalLayout_4.setExpandRatio(horizontalLayout_1, 1.0f);
        
        return verticalLayout_4;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_2() {
        // common part: create layout
        horizontalLayout_2 = new HorizontalLayout();
        horizontalLayout_2.setImmediate(false);
        horizontalLayout_2.setWidth("100.0%");
        horizontalLayout_2.setHeight("60px");
        horizontalLayout_2.setMargin(false);
        
        // dateShipping
        dateShipping = new PopupDateField();
        dateShipping.setCaption("Lieferdatum");
        dateShipping.setImmediate(false);
        dateShipping.setWidth("-1px");
        dateShipping.setHeight("-1px");
        horizontalLayout_2.addComponent(dateShipping);
        horizontalLayout_2.setComponentAlignment(dateShipping, new Alignment(48));
        
        // dateTicketStart
        dateTicketStart = new PopupDateField();
        dateTicketStart.setCaption("Ticketzeitraum Start");
        dateTicketStart.setImmediate(false);
        dateTicketStart.setWidth("-1px");
        dateTicketStart.setHeight("-1px");
        horizontalLayout_2.addComponent(dateTicketStart);
        horizontalLayout_2.setComponentAlignment(dateTicketStart, new Alignment(48));
        
        // dateTicketEnd
        dateTicketEnd = new PopupDateField();
        dateTicketEnd.setCaption("Ticketzeitraum Ende");
        dateTicketEnd.setImmediate(false);
        dateTicketEnd.setWidth("-1px");
        dateTicketEnd.setHeight("-1px");
        horizontalLayout_2.addComponent(dateTicketEnd);
        horizontalLayout_2.setComponentAlignment(dateTicketEnd, new Alignment(48));
        
        return horizontalLayout_2;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_1() {
        // common part: create layout
        horizontalLayout_1 = new HorizontalLayout();
        horizontalLayout_1.setImmediate(false);
        horizontalLayout_1.setWidth("100.0%");
        horizontalLayout_1.setHeight("100.0%");
        horizontalLayout_1.setMargin(false);
        horizontalLayout_1.setSpacing(true);
        
        // tblContents
        tblContents = new Table();
        tblContents.setCaption("Geplante Inhalte");
        tblContents.setImmediate(false);
        tblContents.setWidth("100.0%");
        tblContents.setHeight("100.0%");
        horizontalLayout_1.addComponent(tblContents);
        horizontalLayout_1.setExpandRatio(tblContents, 3.0f);
        
        // tblQuantities
        tblQuantities = new Table();
        tblQuantities.setCaption("Mengenübersicht");
        tblQuantities.setImmediate(false);
        tblQuantities.setWidth("100.0%");
        tblQuantities.setHeight("100.0%");
        horizontalLayout_1.addComponent(tblQuantities);
        horizontalLayout_1.setExpandRatio(tblQuantities, 0.9f);
        
        return horizontalLayout_1;
    }

    @AutoGenerated
    private HorizontalLayout buildButtons() {
        // common part: create layout
        buttons = new HorizontalLayout();
        buttons.setImmediate(false);
        buttons.setWidth("100.0%");
        buttons.setHeight("100.0%");
        buttons.setMargin(false);
        
        // btn_cancel
        btn_cancel = new Button();
        btn_cancel.setCaption("Zurück");
        btn_cancel.setImmediate(true);
        btn_cancel.setWidth("-1px");
        btn_cancel.setHeight("-1px");
        buttons.addComponent(btn_cancel);
        buttons.setComponentAlignment(btn_cancel, new Alignment(48));
        
        // btn_rrule
        btn_rrule = new Button();
        btn_rrule.setCaption("Zyklus anpassen");
        btn_rrule.setImmediate(false);
        btn_rrule.setWidth("-1px");
        btn_rrule.setHeight("-1px");
        buttons.addComponent(btn_rrule);
        buttons.setComponentAlignment(btn_rrule, new Alignment(48));
        
        // btn_save
        btn_save = new Button();
        btn_save.setCaption("Planlieferung bestätigen und ggf. anpassen");
        btn_save.setImmediate(true);
        btn_save.setWidth("-1px");
        btn_save.setHeight("-1px");
        buttons.addComponent(btn_save);
        buttons.setComponentAlignment(btn_save, new Alignment(48));
        
        return buttons;
    }

}
