package archenoah.web.normal.main.Menuepunkte.Unsichtbar.Login;

import java.util.HashMap;
import java.util.Map;

import archenoah.lib.tool.encryption.sha1.Crypt_SHA1;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.lib.vaadin.Logger.Logger;
import archenoah.lib.vaadin.valchecker.val_checker;
import archenoah.web.normal.main.Menuepunkte.Unsichtbar.Init_Menüpunkt_Entwicklung;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.ShortcutAction.KeyCode;
import com.vaadin.server.ThemeResource;
import com.vaadin.server.WebBrowser;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.Button.ClickShortcut;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

@Deprecated
public class frm_login_Entwicklung extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private GridLayout gridLayout_1;
	@AutoGenerated
	private Button btn_login;
	@AutoGenerated
	private PasswordField psw_passwort;
	@AutoGenerated
	private TextField txt_username;
	@AutoGenerated
	private Embedded Login_Logo;
	private Window Login;
	
	
	private static int WARNING_PERIOD_MINS = 3;
	private WebBrowser webBrowser;
	private boolean Touch;
	private String Session;
	private int U_ID;
	
	private String Username = "";
	
	private String checkHash = "1bfded223a229dbabc29b8fbdb8c4dc27ca00b7642f437acc20cd2e6c95db7e31513f86658862a23411ca73280aa64b68b13e2028bbba48047fa85c582c29ba2";

	private Logger log ;


	
	
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	
	
	public Map<Object, String> Val_Map;
    private I18nManager i18n;
	
	public frm_login_Entwicklung() {
		buildMainLayout();
		i18n = new I18nManager(this);
		//setCompositionRoot(mainLayout);
		Login_Logo.setSource(new ThemeResource("image-res/images/Login.png"));
		Login_Logo.setHeight("100px");
		Login_Logo.setWidth("100px");
		
	
		
		Aufbau_Window();

		Event_Forms();
		VAL_Map_Fill();
		

		
		
		
	}

	
	private void Aufbau_Window()
	{
		Login = new Window("Login");
		Login.setModal(true);
		Login.setResizable(false);
		Login.setContent(mainLayout);
		Login.center();
		Login.setDraggable(false);
		Login.setStyleName("login");
		Login.setClosable(true);
		Login.setHeight("450px");
		Login.setWidth("350px");	
		UI.getCurrent().addWindow(Login);
		Login.addAction(new ClickShortcut(btn_login, KeyCode.ENTER));
		txt_username.focus();
		
	}


	
	private void VAL_Map_Fill()
	{
		Val_Map = new HashMap<>(); 
		Val_Map.put(txt_username,"txt_username");
		Val_Map.put(psw_passwort,"psw_passwort");
	}
	
	
	private void Event_Forms()
	{

		
		
		btn_login.addClickListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Automatisch generierter Methodenstub
				
				val_checker val = new val_checker(Val_Map);
				
				if(val.Is_Valid() == false)
				{
					
					I18nManager.global(I18nGlobalNotifiers.fields_empty);
					
					return;
				}
				
			
				
//				php ph = new php("http://php.isconet-applications.de/Lizenzverwaltung_Vaadin/Entwicklerbereich.php");
//				ph.data("Username", "UTF-8", (String)txt_username.getValue(), "UTF-8");
//				ph.data("Passwort", "UTF-8", (String)psw_passwort.getValue(), "UTF-8");
//				String Result = ph.Send();
				
//				if(Result.equals("ï»¿true") == true)
				
				String user = txt_username.getValue();
				String pass = psw_passwort.getValue();
				Crypt_SHA1 sha = new Crypt_SHA1();
				String hash = "";
				try {
					hash = Crypt_SHA1.SHA512(user+pass);
				} catch (Exception e) {

					e.printStackTrace();
				}
				
				if(hash.equals(checkHash) == true){
					Init_Menüpunkt_Entwicklung a = new Init_Menüpunkt_Entwicklung(); 
			
					
					UI.getCurrent().getUI().removeWindow(Login);
			
					
					
				}else
				{
					
					

					
					
					
					return;
					
					
					
					
				}
				
				
				
			}
		});
		
		
		
	}


@AutoGenerated
private VerticalLayout buildMainLayout() {
	// common part: create layout
	mainLayout = new VerticalLayout();
	mainLayout.setImmediate(false);
	mainLayout.setWidth("100%");
	mainLayout.setHeight("100%");
	mainLayout.setMargin(false);
	
	// top-level component properties
	setWidth("100.0%");
	setHeight("100.0%");
	
	// Login_Logo
	Login_Logo = new Embedded();
	Login_Logo.setImmediate(false);
	Login_Logo.setWidth("150px");
	Login_Logo.setHeight("150px");
	Login_Logo.setSource(new ThemeResource("img/component/embedded_icon.png"));
	Login_Logo.setType(1);
	Login_Logo.setMimeType("image/png");
	mainLayout.addComponent(Login_Logo);
	mainLayout.setExpandRatio(Login_Logo, 2.0f);
	mainLayout.setComponentAlignment(Login_Logo, new Alignment(48));
	
	// txt_username
	txt_username = new TextField();
	txt_username.setCaption("Benutzername");
	txt_username.setImmediate(false);
	txt_username.setWidth("170px");
	txt_username.setHeight("-1px");
	txt_username.setTabIndex(1);
	mainLayout.addComponent(txt_username);
	mainLayout.setExpandRatio(txt_username, 1.0f);
	mainLayout.setComponentAlignment(txt_username, new Alignment(48));
	
	// psw_passwort
	psw_passwort = new PasswordField();
	psw_passwort.setCaption("Passwort");
	psw_passwort.setImmediate(false);
	psw_passwort.setWidth("170px");
	psw_passwort.setHeight("-1px");
	psw_passwort.setTabIndex(2);
	mainLayout.addComponent(psw_passwort);
	mainLayout.setExpandRatio(psw_passwort, 1.0f);
	mainLayout.setComponentAlignment(psw_passwort, new Alignment(20));
	
	// gridLayout_1
	gridLayout_1 = buildGridLayout_1();
	mainLayout.addComponent(gridLayout_1);
	mainLayout.setExpandRatio(gridLayout_1, 1.0f);
	
	return mainLayout;
}


@AutoGenerated
private GridLayout buildGridLayout_1() {
	// common part: create layout
	gridLayout_1 = new GridLayout();
	gridLayout_1.setImmediate(false);
	gridLayout_1.setWidth("100.0%");
	gridLayout_1.setHeight("-1px");
	gridLayout_1.setMargin(false);
	gridLayout_1.setColumns(3);
	
	// btn_login
	btn_login = new Button();
	btn_login.setCaption("Login");
	btn_login.setImmediate(true);
	btn_login.setWidth("100.0%");
	btn_login.setHeight("-1px");
	btn_login.setTabIndex(5);
	gridLayout_1.addComponent(btn_login, 1, 0);
	gridLayout_1.setComponentAlignment(btn_login, new Alignment(20));
	
	return gridLayout_1;
}

//*********************************************/

}
