package archenoah.web.normal.main.Menuepunkte.Standard.Info.Statistiken;

import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Window_Button;

import com.vaadin.addon.charts.Chart;
import com.vaadin.addon.charts.model.ChartType;
import com.vaadin.addon.charts.model.Configuration;
import com.vaadin.addon.charts.model.Cursor;
import com.vaadin.addon.charts.model.DataSeries;
import com.vaadin.addon.charts.model.DataSeriesItem;
import com.vaadin.addon.charts.model.Labels;
import com.vaadin.addon.charts.model.PlotOptionsPie;
import com.vaadin.addon.charts.model.style.SolidColor;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

public class auswertung_os extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button button_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	
	
	private Component Chart;
	private Window win;
	public auswertung_os() {
		Gen_Chart();
		buildMainLayout();
		Gen_Window();

		// TODO add user code here
	}

	private void Gen_Window()
	{
		Build_Window_Button bwb = new Build_Window_Button("Chart Verwendeten Betriebsysteme",mainLayout,"500px","500px",null);
	}
	
		
	
	private void Gen_Chart()
	{
		 Chart chart = new Chart(ChartType.PIE);

	        Configuration conf = chart.getConfiguration();

	        conf.setTitle("Statistik der Verwendeten Betriebsysteme");

	        PlotOptionsPie plotOptions = new PlotOptionsPie();
	        plotOptions.setCursor(Cursor.POINTER);
	        Labels dataLabels = new Labels();
	        dataLabels.setEnabled(true);
	        dataLabels.setColor(new SolidColor(0, 0, 0));
	        dataLabels.setConnectorColor(new SolidColor(0, 0, 0));
	        dataLabels
	                .setFormatter("''+ this.point.name +': '+ this.percentage +' %'");
	        plotOptions.setDataLabels(dataLabels);
	        conf.setPlotOptions(plotOptions);

	        DataSeries series = new DataSeries();
	        series.add(new DataSeriesItem("Firefox", 45.0));
	        series.add(new DataSeriesItem("IE", 26.8));
	        DataSeriesItem chrome = new DataSeriesItem("Chrome", 12.8);
	        chrome.setSliced(true);
	        chrome.setSelected(true);
	        series.add(chrome);
	        series.add(new DataSeriesItem("Safari", 8.5));
	        series.add(new DataSeriesItem("Opera", 6.2));
	        series.add(new DataSeriesItem("Others", 0.7));
	        conf.setSeries(series);

	        chart.drawChart(conf);

	        Chart =  chart;

	}
	
	
	
	
	
	
	
	
	
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		
		Chart.setWidth("100%");
		Chart.setHeight("250px");
		// button_1
	
		mainLayout.addComponent(Chart);
		mainLayout.setComponentAlignment(Chart, new Alignment(48));
		
		return mainLayout;
	}

}
