package archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektzuweisung.Form;

import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Map.Entry;

import org.joda.time.LocalDate;

import archenoah.lib.custom.MyUtils;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.vaadin.Components.Combo.combo;
import archenoah.lib.vaadin.Components.Metadata.MetadataPanel;
import archenoah.lib.vaadin.Components.Metadata.RecurrenceDateInformation;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Tab_Menue_Item;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Window_Button;
import archenoah.lib.vaadin.Forms_Builder.Form_Bind;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.lib.vaadin.MenuBerechtigung.Rechteholen;
import archenoah.lib.vaadin.recurrence.DateGenerator;
import archenoah.lib.vaadin.resources.Icons;
import archenoah.lib.vaadin.valchecker.val_checker4;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektzuweisung.Form.Metadata.MetadataForsteoMain;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektzuweisung.Form.Metadata.MetadataPoPMain;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektzuweisung.Form.Metadata.MetadataReplagalMain;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektzuweisung.Form.Metadata.MetadataSAMain;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektzuweisung.Form.Metadata.MetadataVprivMain;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektzuweisung.Form.classes.MailEditor;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Stammdaten.Krankenschwesternverwaltung.forms.form_nurse_insert_edit;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Stammdaten.Patientenverwaltung.Form.data_view_behandelnderarzt;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Stammdaten.Patientenverwaltung.Form.form_patient_insert_edit;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.event.FieldEvents.BlurEvent;
import com.vaadin.event.FieldEvents.BlurListener;
import com.vaadin.event.FieldEvents.FocusEvent;
import com.vaadin.event.FieldEvents.FocusListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

public class form_projektzuweisung_insert_edit extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private HorizontalLayout mainLayout;

    @AutoGenerated
    private VerticalLayout lo_metadata;

    @AutoGenerated
    private VerticalLayout lo_zuweisung;

    @AutoGenerated
    private Button btn_save;

    @AutoGenerated
    private Panel pan_arzt;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_4;

    @AutoGenerated
    private Button btn_info_arzt;

    @AutoGenerated
    private ComboBox cb_arzt;

    @AutoGenerated
    private Panel pan_nurse;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_3;

    @AutoGenerated
    private Button btn_ganalyse;

    @AutoGenerated
    private Button btn_info_nurse;

    @AutoGenerated
    private ComboBox cb_nurse;

    @AutoGenerated
    private Panel pan_pat;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_2;

    @AutoGenerated
    private Button btn_Arzt_Zuw;

    @AutoGenerated
    private Button btn_info_Pat;

    @AutoGenerated
    private ComboBox cb_patient;

    @AutoGenerated
    private HorizontalLayout lo_proj;

    @AutoGenerated
    private Panel pan_aktionen;

    @AutoGenerated
    private VerticalLayout verticalLayout_4;

    @AutoGenerated
    private CheckBox cbx_blanko;

    @AutoGenerated
    private CheckBox cb_email;

    @AutoGenerated
    private CheckBox cbx_aktiv;

    @AutoGenerated
    private Panel pan_proj;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_1;

    @AutoGenerated
    private ComboBox cbx_projekte;

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */

    /**************** --> Allgemein <--- ********************/
    
    org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(this.getClass());
    
    // Allgemein
    private String Exportname;
    // Datenbank
    private Map<Object, String> DBMap;
    private HashMap<String, HashMap> DBMapBlanko;
    private Map<Object, String> ValidateMap;
    private DBClass db;
    private Form_Bind fb;
    private String Form_ID = "";
    // Berrechtigung
    private int ACC_ID;
    private int Lesen;
    private int Schreiben;
    private int Erstellen;
    private int Edit;
    private int Löschen;

    private MenuItem Temp_Menü = null;

    private Button Temp_Btn = null;
    /******************************************************/
    /**************** --> Tabsheetvars <--- *****************/
    private TabSheet tab = null;

    /******************************************************/
    /**************** --> Windowvars <--- *******************/
    private Window win = null;
    /******************************************************/
    /******************* --> Custom <--- ********************/
    /******************************************************/

    MetadataPanel metadataPanel = null;
    private boolean Status_Fill = false;

    private HashMap<String, String> prefilledInitVars;

    /************ ----->Einstellungen<-- ********************/
//    private final String LNG_FRM_ID = "21";
    private final String BER_MEN_ID = "";
    private final String Windows_Height = "700px";
    private final String Windows_Width = "500px";

    private I18nManager i18n;

    private boolean forceInsert;

    /******************************************************/

    public form_projektzuweisung_insert_edit(MenuItem Arg_Menü, String Arg_Form_ID) {
        Temp_Menü = Arg_Menü;
        Form_ID = Arg_Form_ID;

        // TODO add user code here
    }

    public form_projektzuweisung_insert_edit(Button Arg_btn, String Arg_Form_ID) {

        Temp_Btn = Arg_btn;
        Form_ID = Arg_Form_ID;

        // TODO add user code here
    }

    /***************************** ---> Feste Funtionen<--- **************************************/

    /********* INIT-Window ************/
    public void Init_Class_Window() {
        if (Windows_Height.equals("") == true || Windows_Width.equals("") == true) {
            System.out.println("Form Einstellung Fehlt: !!!");
            return;
        }

        Standard_Init();

        if (Temp_Menü != null) {
            String Recourcename = Temp_Menü.getIcon().toString();
            Recourcename = Recourcename.substring(0, Recourcename.length() - 12) + "white-16.png";

            Exportname = Temp_Menü.getText();
            Build_Window_Button bwb = new Build_Window_Button(Temp_Menü.getText(), mainLayout, Windows_Height, Windows_Width,
                    new ThemeResource(Recourcename));
            win = bwb.ReturnWindow();

        }
        if (Temp_Btn != null) {
            Exportname = Temp_Btn.getCaption();
            Build_Window_Button bwb = new Build_Window_Button(Temp_Btn.getCaption(), mainLayout, Windows_Height, Windows_Width,
                    Temp_Btn.getIcon());
            win = bwb.ReturnWindow();
        }
        setWidth();
    }

    /********* INIT-Tray ************/
    public void Init_Class_Tab(TabSheet Arg_tab) {

        Standard_Init();
        tab = Arg_tab;
        if (Temp_Menü != null) {
            Exportname = Temp_Menü.getText();
            Build_Tab_Menue_Item bt = new Build_Tab_Menue_Item(Arg_tab, Temp_Menü.getText(), mainLayout, Temp_Menü.getIcon());
        }
        if (Temp_Btn != null) {
            Exportname = Temp_Btn.getCaption();
            Build_Tab_Menue_Item bt = new Build_Tab_Menue_Item(Arg_tab, Temp_Btn.getCaption(), mainLayout, Temp_Btn.getIcon());
        }

    }

    public Window getWindow(){
        return win;
    }
    
    public void setForceInsert(boolean force) {
        this.forceInsert = force;
        cb_nurse.setReadOnly(!forceInsert);
        if(metadataPanel != null) {
            metadataPanel.setDuplicateOrigVhId(getFormId());
        }
    }
    
    /********* Init-Standard ************/
    private void Standard_Init() {
        buildMainLayout();
        i18n = new I18nManager(this);

        Set_DB_Map();

        Set_Validierer();
        Set_Validate_Map();

        /********** Custom Fill Function *******************/
        native_Projekte();
        //native_Status();
        Combo_Popup_Patient();
        Combo_Popup_Nurse();

        /******** Prefill *******/

        prefillFillFields();

        /***************************************************/

        cbx_projekte.setImmediate(true);
        cbx_projekte.setFilteringMode(FilteringMode.CONTAINS);
        cb_patient.setImmediate(true);
        cbx_blanko.setEnabled(false);

        if (Form_ID != "") {

            Forms_Fill();
            Status_Fill = true;
            cbx_projekte.setReadOnly(true);
            cb_patient.setReadOnly(true);
            cb_nurse.setReadOnly(true);

            btn_info_arzt.setData("arzt");
            btn_info_nurse.setData("nurse");

            setBlankoAvailable();
            setMetadataPanel();
        }
        
        // migrated from database
        btn_info_Pat.setIcon(Icons.White.info_16);
        btn_save.setIcon(Icons.White.save_16);
        btn_info_arzt.setIcon(Icons.White.info_16);
        btn_info_nurse.setIcon(Icons.White.info_16);

        btn_info_Pat.setStyleName("button-image-only");
        btn_info_arzt.setStyleName("button-image-only");
        btn_info_nurse.setStyleName("button-image-only");

        cbx_projekte.setRequired(true);
//        cb_patient.setRequired(true);
//        cb_nurse.setRequired(true);
        // migration end
        
        cb_email.setEnabled(true);
        
        event();
        // win.addAction(new ClickShortcut(btn_save, KeyCode.ENTER));
    }

    /*********************************/
    
    private Integer getFormId() {
        if(!"".equals(Form_ID) && Form_ID != null) {
            return Integer.parseInt(Form_ID);
        }
        return null;
    }
    
    private void initMetadataPanel(MetadataPanel meta, Integer projectId){
        metadataPanel = meta;
        metadataPanel.setMainId(Form_ID);
        metadataPanel.setProjectId(projectId.toString());
        
        if (cb_patient.getValue() != null) {
            metadataPanel.setPatientId(Integer.toString((Integer) cb_patient.getValue()));
        }
        if (cb_nurse.getValue() != null) {
            metadataPanel.setNurseId(Integer.toString((Integer) cb_nurse.getValue()));
        }
        lo_metadata.addComponent(metadataPanel.getPanel());
        lo_metadata.setVisible(true);
    }
    
    private void setMetadataPanel() {
        
        String pcode = "";
        
        try {
            pcode = (String) cbx_projekte.getContainerDataSource().getContainerProperty(cbx_projekte.getValue(), "PSLV_CODE").getValue();
        } catch (Exception e) {}
        
        Integer project = (Integer) cbx_projekte.getValue();
        
        lo_metadata.removeAllComponents();
        metadataPanel = null;
        lo_metadata.setVisible(false);

        if (project == null) {
            project = 0;
        }
        switch (pcode) {
        case "FOR":
            
            initMetadataPanel(new MetadataForsteoMain(), project);
            
            break;
        case "REP":

            initMetadataPanel(new MetadataReplagalMain(), project);

            break;
        case "VPRIV":

            initMetadataPanel(new MetadataVprivMain(), project);

            break;

        case "POP":

            initMetadataPanel(new MetadataPoPMain(), project);

            break;
            
        case "SA":

            initMetadataPanel(new MetadataSAMain(), project);

            break;
            
        default:
           
            break;
        }
        if (win != null) {
            setWidth();
        }
        
        if(metadataPanel != null) {
            cb_nurse.setRequired(!cb_nurse.isReadOnly() && metadataPanel.isNurseRequired());
            cb_patient.setRequired(!cb_patient.isReadOnly() && metadataPanel.isPatientRequired());
            if(forceInsert) {
                metadataPanel.setDuplicateOrigVhId(getFormId());
            }
        }
        
    }

    private void setWidth() {
        win.setWidth(Windows_Width);
        if (metadataPanel != null) {

            Float winWidth = win.getWidth();
            Unit winWidthUnit = win.getWidthUnits();

            Float panWidth = lo_metadata.getWidth();
            Unit panWidthUnit = lo_metadata.getWidthUnits();

            Float width = winWidth + panWidth;

            win.setWidth(width, winWidthUnit);
        }
        win.center();
    }

    /*************************** Events *******************************/

    private void event() {

        cbx_projekte.addValueChangeListener(new ValueChangeListener() {

            @Override
            public void valueChange(ValueChangeEvent event) {
                setBlankoAvailable();
                cb_nurse.removeAllItems();
                Combo_Popup_Nurse();
                setMetadataPanel();
            }
        });

        btn_save.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {
                // TODO Automatisch generierter Methodenstub

                if (Validate_Test() == false) {
                    I18nManager.global(I18nGlobalNotifiers.fields_empty);
                    return;
                }

                if (Status_Fill == false) {
                    if (Get_Verk_Vorhanden() == true) {
                        I18nManager.global(I18nGlobalNotifiers.entry_exists);
                        return;

                    }
                }

                if (Form_ID.equals("") == true || forceInsert) {
                    
                    if(metadataPanel != null && !metadataPanel.validate()){
                        return;
                    }
                    
                    if(forceInsert && metadataPanel != null) {
                        metadataPanel.deleteUnaccepted();
                    }
                    
                    Forms_Insert();
                    
                    if(metadataPanel != null){
                        metadataPanel.setMainId(Form_ID);
                        if(cb_patient.getValue() != null) {
                            metadataPanel.setPatientId(Integer.toString((Integer)cb_patient.getValue()));
                        }
                        if(cb_nurse.getValue() != null) {
                            metadataPanel.setNurseId(Integer.toString((Integer)cb_nurse.getValue()));
                        }
                        metadataPanel.save();
                    }
                    
                    if (cbx_blanko.isEnabled() && cbx_blanko.getValue()) {
                        setDBMapBlanko();
                        if (!checkBlankoExists()) {
                            Forms_Insert_Blanko();
                        } else {
                            I18nManager.global(I18nGlobalNotifiers.entry_exists);
                            return;
                        }
                    }
                    
                } else {
                    
                    if(metadataPanel != null){
                        Boolean metaSaved = metadataPanel.save();
                        if(!metaSaved){
                            return;
                        }
                    }
                    
                    if (cbx_blanko.isEnabled() && cbx_blanko.getValue()) {
                        setDBMapBlanko();
                        if (!checkBlankoExists()) {
                            Forms_Insert_Blanko();
                        } else {
                            I18nManager.global(I18nGlobalNotifiers.entry_exists);
                            return;
                        }
                    }
                    Forms_Update();
                }

                

                if (cb_email.getValue() == true) {
                    
                    MailEditor mail = new MailEditor();
                    mail.setProjecttId((Integer) cbx_projekte.getValue());
                    mail.setNurseId((Integer) cb_nurse.getValue());
                    mail.setPatientId((Integer) cb_patient.getValue());
                    
                    HashMap<String, Object> metaValues = metadataPanel.getFieldValues();
                    if (metaValues.containsKey("cust_protokoll_forsteo_meta_static:PFORMS_ID_ADM")) {
                        mail.setExternalId((Integer) metaValues.get("cust_protokoll_forsteo_meta_static:PFORMS_ID_ADM"));
                    }
                    
                    // try to open mail window, but leave insert_edit open if it fails
                    if(mail.show() == null) {
                        return;
                    }
                    

                }
                
                UI.getCurrent().getUI().removeWindow(win);

            }

        });

        cb_arzt.addFocusListener(new FocusListener() {

            @Override
            public void focus(FocusEvent event) {
                // TODO Automatisch generierter Methodenstub
                Combo_Popup_Arzt();
            }
        });
        cb_nurse.addFocusListener(new FocusListener() {

            @Override
            public void focus(FocusEvent event) {
                // TODO Automatisch generierter Methodenstub
                Combo_Popup_Nurse();
            }
        });
        
        cb_nurse.addValueChangeListener(new ValueChangeListener() {

            @Override
            public void valueChange(ValueChangeEvent event) {
                if (metadataPanel != null) {
                    metadataPanel.setNurseId(cb_nurse.getValue() != null ? Integer.toString((Integer) cb_nurse.getValue()) : null);
                    //metadataPanel.update(); // not needed as of now
                }
            }
        });
        
        cb_patient.addFocusListener(new FocusListener() {

            @Override
            public void focus(FocusEvent event) {
                // TODO Automatisch generierter Methodenstub
                Combo_Popup_Patient();
            }
        });

        cb_patient.addValueChangeListener(new ValueChangeListener() {

            @Override
            public void valueChange(ValueChangeEvent event) {
                if (metadataPanel != null) {
                    metadataPanel.setPatientId(Integer.toString((Integer) cb_patient.getValue()));
                    metadataPanel.update();
                }
            }
        });

        btn_info_Pat.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {
                // TODO Automatisch generierter Methodenstub
                if (cb_patient.getValue() == null) {
                    I18nManager.global(I18nGlobalNotifiers.no_entry_selected);

                    return;
                }

                form_patient_insert_edit pie = new form_patient_insert_edit(event.getButton(), "" + cb_patient.getValue());
                pie.Init_Class_Window();
                pie.Set_Berrechtigung_Custom(1, 0, 0, 0);
            }
        });

        btn_info_nurse.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {
                // TODO Automatisch generierter Methodenstub
                if (cb_nurse.getValue() == null) {
                    I18nManager.global(I18nGlobalNotifiers.no_entry_selected);

                    return;
                }

                form_nurse_insert_edit pie = new form_nurse_insert_edit(event.getButton(), "" + cb_nurse.getValue());
                pie.Init_Class_Window();
                pie.Set_Berrechtigung_Custom(1, 0, 0, 0);
            }
        });
        btn_info_arzt.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {
                // TODO Automatisch generierter Methodenstub
                if (cb_arzt.getValue() == null) {
                    I18nManager.global(I18nGlobalNotifiers.no_entry_selected);

                    return;
                }

                form_nurse_insert_edit pie = new form_nurse_insert_edit(event.getButton(), "" + cb_arzt.getValue(), "arzt");
                pie.Init_Class_Window();
                pie.Set_Berrechtigung_Custom(1, 0, 0, 0);
            }
        });

        btn_Arzt_Zuw.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {
                // TODO Automatisch generierter Methodenstub
                if (cb_patient.getValue() == null) {
                    I18nManager.global(I18nGlobalNotifiers.no_entry_selected);

                    return;
                }

                data_view_behandelnderarzt vb = new data_view_behandelnderarzt(event.getButton());
                vb.Set_Patienten_ID(cb_patient.getValue() + "");
                vb.Set_Berrechtigung_Custom(1, 1, 1, 1);
                vb.Init_Class_Window();
                vb.Set_Form_for_Ber();
            }
        });

        cb_patient.addBlurListener(new BlurListener() {

            @Override
            public void blur(BlurEvent event) {
                // TODO Automatisch generierter Methodenstub

                int temp = Get_Arzt_ID_Vorhanden();

                if (temp != 0) {
                    Combo_Popup_Arzt();
                    cb_arzt.setValue(temp);

                } else {
                    cb_arzt.removeAllItems();
                }

            }
        });

        btn_ganalyse.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {
                // TODO Automatisch generierter Methodenstub
                if (cb_patient.getValue() == null) {
                    I18nManager.global(I18nGlobalNotifiers.no_entry_selected);

                    return;
                }

                
                form_zuweisung_analyse prox = new form_zuweisung_analyse(event.getButton());
                prox.Init_Class_Window();
                prox.setNurseCombo(cb_nurse);
                prox.fill((Integer)cbx_projekte.getValue(), (Integer)cb_patient.getValue());


            }
        });

    }

    /******************************************************************/

    /*** --> Get int DB <-- ***/

    private int Get_Arzt_ID_Vorhanden() {

        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_verk_haupt");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_haupt", "VH_PATIENT_ID", "=", cb_patient.getValue() + "", "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_haupt", "VH_PROJEKT_ID", "=", cbx_projekte.getValue() + "", "");
        
        db.debugNextQuery(false);
        
        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();

        int A_ID = 0;

        if (con.size() > 0 && con.getContainerProperty(con.getContainerPropertyIds().iterator().next(), "VH_ARZT_ID") != null) {

            A_ID = (int) con.getContainerProperty(con.getContainerPropertyIds().iterator().next(), "VH_ARZT_ID").getValue();

            return A_ID;
        } else {
            return 0;
        }

    }

    private boolean Get_Verk_Vorhanden() {

        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_verk_haupt");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_haupt", "VH_PATIENT_ID", "=", cb_patient.getValue() + "", "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_haupt", "VH_PROJEKT_ID", "=", cbx_projekte.getValue() + "", "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_haupt", "VH_NURSE_ID", "=", cb_nurse.getValue() + "", "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_haupt", "VH_AKTIV", "=", "1", "");
        // db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_haupt", "VH_STATUS_ID", "=", ns_zuw_status.getValue()+"", "");
        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();

        if (con.size() > 0) {
            return true;
        } else {
            return false;
        }

    }
    
    private Boolean skipBlankoCheck() {
        
        Boolean skipCheck = false;
        
        DBClass db = new DBClass();
        
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("count(*)", "count");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_projekte_blankos");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_projekte_blankos", "PB_P_ID", "=", ((Integer) cbx_projekte.getValue()).toString(), "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_projekte_blankos", "PB_RRULE_TYPE", "IS NOT", "NULL", "");
        
//        db.debugNextQuery(true);
        
        Container con = db.DB_Data_Get.DB_SEND_AND_GET();
        
        Long count = MyUtils.getValueFromItem(MyUtils.getFirstItemFromContainer(con), "count", Long.class);
        
        if(count != null && count >= 2) {
            skipCheck = true;
        }
        
        return skipCheck;
        
    }
    
    private boolean checkBlankoExists() {

        db = new DBClass();
        
        if(skipBlankoCheck()){
            return false;
        }
        
        if (DBMapBlanko.size() == 0) {
            return true;
        }
        
        Iterator it = DBMapBlanko.entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry pairs = (Map.Entry) it.next();
            String table = (String) pairs.getKey();
            HashMap tableData = (HashMap) pairs.getValue();

            /******************************************************************************/
            db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
            db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln(table);
            // db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein((String) pairs.getKey(), "VH_PATIENT_ID", "=", cb_patient.getValue()+"", "");
            /******************************************************************************/
            DBClass lp;
            lp = new DBClass();
            lp.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
            lp.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_projekte_blankos");
            lp.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_projekte_blankos", "PB_T", "=", "'" + table + "'", "AND");
            lp.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_projekte_blankos", "PB_F", "IS NOT ", "NULL", "");

            Container lpcon = lp.DB_Data_Get.DB_SEND_AND_GET_Container();
            Integer lpsize = lpcon.size();

            for (Object lpid : lpcon.getItemIds()) {
                String fieldname = (String) lpcon.getContainerProperty(lpid, "PB_F").getValue();
                
                Object instance = null;
                String method = "AND";
                
                if ((int) lpid == lpsize) {
                    method = "";
                }
                try {
                    instance = getClass().getDeclaredField(fieldname).get(this);

                    Method m = instance.getClass().getMethod("getValue");
                    Object objValue = m.invoke(instance);

                    String value = (String) tableData.get(instance);
                    String[] cols = value.split(":");

                    db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein(table, cols[1], "=", objValue + "", method);

                } catch (Exception e) {
                    System.out.println(e.toString());
                }
            }
            
            db.debugNextQuery(false);
            
            Container result = db.DB_Data_Get.DB_SEND_AND_GET_Container();
            db.DB_Data_Get.DB_Filter.DB_Data_Leeren();

            if (result.size() > 0) {
                return true;
            }

        }

        return false;
    }

    private void setBlankoAvailable() {
        HashMap m = getDBMapBlanko();
        if (m.size() > 0) {
            cbx_blanko.setEnabled(true);
        } else {
            cbx_blanko.setEnabled(false);
        }
    }

    /************************ --> Berrechtigung <-- **************************/

    public void Set_Berrechtigung_Database() {
        if (BER_MEN_ID == "") {
            System.out.println("Form Einstellung Fehlt: !!!");
            return;
        }

        ACC_ID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        Rechteholen r = new Rechteholen(ACC_ID + "");
        String[][] Asan = r.Datenholen();

        for (int i = 0; i < Asan.length; i++) {
            if (Asan[i][0].equals(BER_MEN_ID) == true) {

                Lesen = Integer.valueOf(Asan[i][3]);

                Schreiben = Integer.valueOf(Asan[i][4]);
                Erstellen = Integer.valueOf(Asan[i][6]);
                Löschen = Integer.valueOf(Asan[i][5]);
            }
        }
    }

    public void Set_Berrechtigung_Custom(int Arg_Lesen, int Arg_Erstellen, int Arg_Bearbeiten, int Arg_Loeschen) {
        Lesen = Arg_Lesen;
        Schreiben = Arg_Erstellen;
        Erstellen = Arg_Erstellen;
        Edit = Arg_Bearbeiten;
        Löschen = Arg_Loeschen;

        if (Erstellen == 0 | Edit == 0) {
            btn_save.setEnabled(false);
            btn_Arzt_Zuw.setEnabled(false);
            btn_ganalyse.setEnabled(false);
        }

    }

    /**********************************************************************/

    public void setPrefilledInit(String projekt, String patient) {
        prefilledInitVars = new HashMap<String, String>();
        prefilledInitVars.put("projekt", projekt);
        prefilledInitVars.put("patient", patient);
    }

    /************************** Einstellen **************************************/

    /******************** Database *****************/
    private void Set_DB_Map() {
        DBMap = new HashMap<>();
        // DBMap.put(txt_username,"cms_auth_stammdaten_user:AUL_USERNAME");
        DBMap.put(cbx_projekte, "cust_verk_haupt:VH_PROJEKT_ID");
        //DBMap.put(ns_zuw_status, "cust_verk_haupt:VH_STATUS_ID");
        DBMap.put(cb_arzt, "cust_verk_haupt:VH_ARZT_ID");
        DBMap.put(cb_nurse, "cust_verk_haupt:VH_NURSE_ID");
        DBMap.put(cb_patient, "cust_verk_haupt:VH_PATIENT_ID");
        DBMap.put(cbx_aktiv, "cust_verk_haupt:VH_AKTIV");

    }
    
    private HashMap getRruleFields(String table){
        HashMap<Integer, String> map = new HashMap<Integer, String>();
        
        Integer project = (Integer) cbx_projekte.getValue();
        String pid = (project != null) ? Integer.toString(project) : "";
        
        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();

        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_projekte_blankos");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_projekte_blankos", "PB_P_ID", "=", "'" + pid + "'", "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_projekte_blankos", "PB_T", "=", "'" + table + "'", "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_projekte_blankos", "PB_RRULE_TYPE", "IS NOT", "NULL", "");
        
//        db.debugNextQuery(true);
        
        Container fields = db.DB_Data_Get.DB_SEND_AND_GET_Container();
        
        for (Object fieldId : fields.getItemIds()) {
            map.put((Integer) fields.getItem(fieldId).getItemProperty("PB_RRULE_TYPE").getValue(), (String) fields.getItem(fieldId).getItemProperty("PB_C").getValue()); 
        }
        
        
        return map;
    }
    
    private HashMap getDBMapBlanko() {
        // HashMap<> DBMapBlanko = new HashMap();
        HashMap<String, HashMap> DBMapBlankoR;
        DBMapBlankoR = new HashMap();
        Integer project = (Integer) cbx_projekte.getValue();
        String pid = (project != null) ? Integer.toString(project) : "";

        db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();

        /******************************** Table ****************************************/
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_projekte_blankos");
        /******************************************************************************/
        /******************************** Filter ****************************************/
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_projekte_blankos", "PB_P_ID", "=", "'" + pid + "'", "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_projekte_blankos", "PB_RRULE_TYPE", "IS", "NULL", "");
        /******************************************************************************/
        
//        db.debugNextQuery(true);
        
        Container fields = db.DB_Data_Get.DB_SEND_AND_GET_Container();
        // System.out.println("csize " + fields.size());
        if (fields.size() > 0) {
            for (Object Field : fields.getItemIds()) {
                // System.out.println(fields.getContainerProperty(Field,"PB_F").getValue());
                String fieldname = (String) fields.getContainerProperty(Field, "PB_F").getValue();
                String key = (String) fields.getContainerProperty(Field, "PB_T").getValue();
                Object instance = null;
                String value = "";
                if (fieldname != "") {
                    try {
                        instance = getClass().getDeclaredField(fieldname).get(this);
                        value += fields.getContainerProperty(Field, "PB_T").getValue();
                        value += ":";
                        value += fields.getContainerProperty(Field, "PB_C").getValue();
                        // System.out.println(instance);
                        // DBMapBlankoR.put(instance, value);

                    } catch (Exception e) {
                        System.out.println("excp A");
                        // e.printStackTrace();
                    }
                    if (DBMapBlankoR.containsKey(key)) {
                        // System.out.println("adding to " + key);
                        HashMap partMap = DBMapBlankoR.get(key);
                        partMap.put(instance, value);
                    } else {
                        // System.out.println("new map for " + key);
                        HashMap partMap = new HashMap();
                        partMap.put(instance, value);
                        DBMapBlankoR.put(key, partMap);
                    }
                }

            }

        }
        return DBMapBlankoR;

    }

    private void setDBMapBlanko() {
        DBMapBlanko = getDBMapBlanko();
    }

    private void Forms_Fill() {
        db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();

        /******************************** Table ****************************************/
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_verk_haupt");
        /******************************************************************************/
        /******************************** Filter ****************************************/
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_haupt", "VH_ID", "=", Form_ID, "");
        /******************************************************************************/

        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();
        fb = new Form_Bind();

        for (Object ItemIda : con.getItemIds()) {
            fb.Get_and_Fill(con, DBMap);

            Combo_Popup_Arzt();
            
            if(con.getContainerProperty(ItemIda, "VH_ARZT_ID").getValue() != null){
            	cb_arzt.setValue((int) con.getContainerProperty(ItemIda, "VH_ARZT_ID").getValue());
            }
            
        }
    }

    private void Forms_Insert() {
        db = new DBClass();
        fb = new Form_Bind();
        fb.Insert(db, DBMap);
        /******************************** Table ****************************************/
        db.DB_Data_Insert.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_verk_haupt");
        /******************************************************************************/

        Form_ID = Integer.toString(db.DB_Data_Insert.DB_Insert());

    }
    
    private void generateBlankos(Date date, Integer delegationId) {
        generateBlankos(date, delegationId, null);
    }
    
    @SuppressWarnings("unchecked")
    private void generateBlankos(Date date, Integer delegationId, HashMap<Object, Object> additionalValues) {

        DBClass db = new DBClass();
        
        HashMap<String, HashMap> hm = new HashMap<String, HashMap>(DBMapBlanko);
        
        Iterator it = hm.entrySet().iterator();
        
        while (it.hasNext()) {
            Map.Entry pairs = (Map.Entry) it.next();

            fb = new Form_Bind();
            fb.Insert(db, (HashMap) pairs.getValue());
            
            
            /******************************** Table ****************************************/
            db.DB_Data_Insert.DB_Tabellen.DB_set_Tabelle_Einzeln((String) pairs.getKey());
            /******************************************************************************/
            
            if(date != null && delegationId != null){
                HashMap<Integer, String> rruleMap = getRruleFields((String) pairs.getKey());
                if(rruleMap.size() > 0){
                    
                    java.sql.Date sqlDate = new java.sql.Date(date.getTime());
                    
                    db.DB_Data_Insert.DB_Daten.DB_Data((String) pairs.getKey(), rruleMap.get(2), Integer.toString(delegationId));
                    db.DB_Data_Insert.DB_Daten.DB_Data((String) pairs.getKey(), rruleMap.get(1), sqlDate.toString());
                    db.DB_Data_Insert.DB_Daten.DB_Data((String) pairs.getKey(), rruleMap.get(3), sqlDate.toString());
                }
                
                if(additionalValues != null) {
                    for (Entry<Object, Object> entry : additionalValues.entrySet()) {
                        
                        String value = entry.getValue() != null ? entry.getValue().toString() : null;
                        db.DB_Data_Insert.DB_Daten.DB_Data(pairs.getKey().toString(), entry.getKey().toString(), value);
                        
                    }
                }
                
            }
            
            
//          db.debugNextQuery(true);
          
          db.DB_Data_Insert.DB_Insert();
          db.DB_Data_Leeren();
            
            it.remove(); // avoids a ConcurrentModificationException
        }
        
       
    }
    
    private void generateBlankos(){
        generateBlankos(null, null);
    }
    
    private Date dbGetLatestDate2(){
        if((Integer) cbx_projekte.getValue() != 2){
            return null;
        }
        
        
        DBClass dbb = new DBClass();
        
        dbb.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
        
        dbb.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_protokoll_replagal_daten", "INNER JOIN", "cust_protokoll_replagal_meta_dynamic", "PRD_DELEGATION_ID", "PREPMD_ID");
//        dbb.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_protokoll_replagal_meta_dynamic", "INNER JOIN", "cust_verk_haupt", "PREPMD_VH_ID", "VH_ID");
        
        dbb.DB_Data_Get.DB_Ordnen.DB_Ordnen("PRD_DATE", "DESC");
        dbb.DB_Data_Get.DB_Limit.DB_LIMIT("1");
        
        dbb.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_protokoll_replagal_meta_dynamic", "PREPMD_VH_ID", "=", Form_ID, "");
        
//        dbb.debugNextQuery(true);
        
        Item item = dbb.DB_Data_Get.DB_SEND_AND_GET_FIRST_ITEM();
        
        return (item == null) ? null : (Date) item.getItemProperty("PRD_DATE").getValue();
        
        
    }
    
    private void Forms_Insert_Blanko() {
        
        ArrayList<LocalDate> dateList = new ArrayList<LocalDate>();
        
        // multi Recurrence Blankos
        if(metadataPanel.hasMultiRecurrence()) {
            
            // dyn id, datelist
            HashMap<Integer, RecurrenceDateInformation> rlist = metadataPanel.getRecurrenceDates(true);
            
            if(rlist != null) {
                
                for (Entry<Integer, RecurrenceDateInformation> entry : rlist.entrySet()) {
                    
                    ArrayList<LocalDate> multiList = entry.getValue().getDateList();
                    HashMap<Object, Object> adv = entry.getValue().getAdditionalValues();
                    Integer rid = entry.getKey();
                    
                    if(multiList.size() > 0){
                        for (LocalDate localDate : multiList) {
                            generateBlankos(localDate.toDate(), rid, adv);
//                                System.out.println("generating " + localDate.toDate() + " " + metadataPanel.getRecurrenceMetaId());
                        }
                    }
                }
            
            }
            
            return; // stop the default fallback
            
        }
        
        // single Recurrence Blankos
        if(metadataPanel.hasRecurrence()){
            
            metadataPanel.setRecurrenceSettings(Form_ID);
            
            DateGenerator dg = new DateGenerator(metadataPanel.getRecurrenceString(),
                    metadataPanel.getRecurrenceStart(),
                    metadataPanel.getRecurrenceRepetitions());
           
            Date latest = metadataPanel.getRecurrenceLatestDate();
            
//            log.info("string: {}", metadataPanel.getRecurrenceString());
//            log.info("start: {}", metadataPanel.getRecurrenceStart());
//            log.info("reps: {}", metadataPanel.getRecurrenceRepetitions());
//            log.info("latest: {}", metadataPanel.getRecurrenceLatestDate());
            
            if(latest != null){
                dg.setContinuationDate(latest);
            }
            
           dateList = dg.generateDateList();
           
        }
        
        //TASK needs restructuring
        if(dateList.size() > 0){
            for (LocalDate localDate : dateList) {
                generateBlankos(localDate.toDate(), metadataPanel.getRecurrenceMetaId());
//                System.out.println("generating " + localDate.toDate() + " " + metadataPanel.getRecurrenceMetaId());
            }
        }else{
            generateBlankos();
        }

    }
    
    private void Forms_Update() {
        db = new DBClass();
        fb = new Form_Bind();
        fb.Update(db, DBMap);

        /******************************** Table ****************************************/
        db.DB_Data_Update.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_verk_haupt");
        /******************************************************************************/
        /******************************** Filter ****************************************/
        db.DB_Data_Update.DB_Filter.DB_WHERE_Allgemein("cust_verk_haupt", "VH_ID", "=", Form_ID, "");
        /******************************************************************************/
        db.DB_Data_Update.DB_Update();
    }

    /****************** Füllen der Combos *********************/
    private void native_Projekte() {
        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("PSLV_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("PSLV_NAME");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("PSLV_CODE");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_projekte_stammdaten_liste");
        
        IndexedContainer con = MyUtils.convertIndex(db.DB_Data_Get.DB_SEND_AND_GET_Container(), "PSLV_ID");
        
        if(con.size() > 0) {
            cbx_projekte.setItemCaptionPropertyId("PSLV_NAME");
            cbx_projekte.setContainerDataSource(con);
        }else {
            cbx_projekte.removeAllItems();
        }


    }

    //    private void native_Status() {
    //	CMS_Config_Std std = CMS_Config_Std.getInstance();
    //	DBClass db = new DBClass(std.Standard_Server_URL, std.Standard_Server_Username, std.Standard_Server_Passwort,
    //		std.Standard_Server_Database, std.Standard_Server_Port);
    //	db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("VKS_ID");
    //	db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("VKS_NAME");
    //	db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_verk_haupt_status");
    //
    //	try {
    //	    nativecombo nc = new nativecombo(db.DB_Data_Get.DB_SEND_AND_GET(), ns_zuw_status, "VKS_ID", "VKS_NAME");
    //	} catch (Exception e) {
    //	    ns_zuw_status.removeAllItems();
    //	}
    //
    //	db.DB_Data_Get.connclose();
    //    }

    private void Combo_Popup_Patient() {

        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("PSL_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(PSL_TITEL,' ',PSA_NAME,' ',PSL_NAME,' ',PSL_VORNAME)",
                "Patientenname");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_patient_stammdaten_liste", "INNER JOIN",
                "cust_patient_stammdaten_anrede", "PSL_ANREDE", "PSA_ID");

        try {
            combo nc = new combo(db.DB_Data_Get.DB_SEND_AND_GET(), cb_patient, "PSL_ID", "Patientenname");
        } catch (Exception e) {
            cb_patient.removeAllItems();
        }

        db.DB_Data_Get.connclose();

        cb_patient.setFilteringMode(FilteringMode.CONTAINS);
    }

    private void Combo_Popup_Nurse() {

        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("KSK_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(KSK_TITEL,' ',KSA_NAME,' ',AUL_VORNAME,' ',AUL_NAME)",
                "Krankenschwesternname");

        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("AL_G_ID");

        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_stammdaten_user", "INNER JOIN",
                "cust_krankenschwester_stammdaten_anrede", "AUL_ANREDE_ID", "KSA_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_stammdaten_user", "LEFT JOIN", "cms_auth_liste_gu", "AUL_ID",
                "AL_U_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_liste_gu", "LEFT JOIN", "cust_projekte_stammdaten_liste",
                "AL_G_ID", "PSLV_GROUP");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_krankenschwester_stammdaten_ks", "INNER JOIN",
                "cms_auth_stammdaten_user", "KSK_U_ID", "AUL_ID");

        // System.out.println(ns_projekte.getValue());

        if (cbx_projekte.getValue() != null) {
            db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_projekte_stammdaten_liste", "PSLV_ID", "=",
                    cbx_projekte.getValue().toString(), "");
        }

        // db.DB_Data_Get.DB_DEBUG_SQL_STRING();

        try {
            combo nc = new combo(db.DB_Data_Get.DB_SEND_AND_GET(), cb_nurse, "KSK_ID", "Krankenschwesternname");
        } catch (Exception e) {
            cb_nurse.removeAllItems();
            return;
        }

        db.DB_Data_Get.connclose();

        cb_nurse.setFilteringMode(FilteringMode.CONTAINS);
    }

    private void Combo_Popup_Arzt() {
        // frm_Popup.cb_arzt.removeAllItems();
        try {
            int fora = (int) cb_patient.getValue();
        } catch (Exception e1) {
            cb_arzt.removeAllItems();

            // TODO Automatisch generierter Erfassungsblock
            return;
        }

        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("ASA_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(ASA_TITEL,' ',ASAN_NAME,' ',AUL_NAME,' ',AUL_VORNAME)",
                "Arztname");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_stammdaten_user", "INNER JOIN", "cust_arzt_stammdaten_anrede",
                "AUL_ANREDE_ID", "ASAN_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_arzt_stammdaten_arzt", "INNER JOIN", "cms_auth_stammdaten_user",
                "ASA_U_ID", "AUL_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_arzt_stammdaten_arzt", "INNER JOIN", "cust_verk_arzt_patient",
                "ASA_ID", "VAP_A_ID");

        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_arzt_patient", "VAP_P_ID", "=", cb_patient.getValue().toString(), "");

        try {
            combo nc = new combo(db.DB_Data_Get.DB_SEND_AND_GET(), cb_arzt, "ASA_ID", "Arztname");
        } catch (Exception e) {
            cb_arzt.removeAllItems();
        }

        db.DB_Data_Get.connclose();

        cb_arzt.setFilteringMode(cb_arzt.FILTERINGMODE_CONTAINS);
    }

    /*********************************************************/

    private void prefillFillFields() {
        if (prefilledInitVars != null && prefilledInitVars.size() > 0) {

            try {
                cbx_projekte.select(Integer.valueOf(prefilledInitVars.get("projekt")));
                cb_patient.select(Integer.valueOf(prefilledInitVars.get("patient")));
                if (prefilledInitVars.get("arzt") != null) {
                    cb_arzt.select(Integer.valueOf(prefilledInitVars.get("arzt")));
                    cb_arzt.setReadOnly(true);
                }
                cbx_projekte.setReadOnly(true);
                cb_patient.setReadOnly(true);
            } catch (Exception e) {
                System.out.println("Prefill konnte nicht durchgeführt werden");
                System.out.println(e.toString());
            }

        }
    }

    /***********************************************/

    /*********************** -->Validierung<-- ********************/
    private void Set_Validate_Map() {
        ValidateMap = new HashMap<>();
        // ValidateMap.put(txt_username,"");
        ValidateMap.put(cbx_projekte, "cbx_projekte");
        //ValidateMap.put(ns_zuw_status, "ns_zuw_status");
        ValidateMap.put(cb_patient, "cb_patient");
        ValidateMap.put(cb_nurse, "cb_nurse");

    }

    private void Set_Validierer() {

        // psw_pass_1.addValidator(new Custom_Benutzerform_psw_ändern(psw_pass_1, psw_pass_2));

    }

    private boolean Validate_Test() {
        val_checker4 val = new val_checker4(ValidateMap);
        if (val.Is_Valid() == false) {
            return false;
        } else {
            return true;
        }

    }

    @AutoGenerated
    private HorizontalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new HorizontalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(true);
        mainLayout.setSpacing(true);

        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");

        // lo_zuweisung
        lo_zuweisung = buildLo_zuweisung();
        mainLayout.addComponent(lo_zuweisung);
        mainLayout.setExpandRatio(lo_zuweisung, 1.0f);

        // lo_metadata
        lo_metadata = new VerticalLayout();
        lo_metadata.setImmediate(false);
        lo_metadata.setWidth("290px");
        lo_metadata.setHeight("100.0%");
        lo_metadata.setMargin(false);
        lo_metadata.setVisible(false);
        mainLayout.addComponent(lo_metadata);

        return mainLayout;
    }

    @AutoGenerated
    private VerticalLayout buildLo_zuweisung() {
        // common part: create layout
        lo_zuweisung = new VerticalLayout();
        lo_zuweisung.setImmediate(false);
        lo_zuweisung.setWidth("100.0%");
        lo_zuweisung.setHeight("100.0%");
        lo_zuweisung.setMargin(false);

        // lo_proj
        lo_proj = buildLo_proj();
        lo_zuweisung.addComponent(lo_proj);
        lo_zuweisung.setExpandRatio(lo_proj, 1.0f);
        lo_zuweisung.setComponentAlignment(lo_proj, new Alignment(48));

        // pan_pat
        pan_pat = buildPan_pat();
        lo_zuweisung.addComponent(pan_pat);
        lo_zuweisung.setExpandRatio(pan_pat, 1.0f);
        lo_zuweisung.setComponentAlignment(pan_pat, new Alignment(48));

        // pan_nurse
        pan_nurse = buildPan_nurse();
        lo_zuweisung.addComponent(pan_nurse);
        lo_zuweisung.setExpandRatio(pan_nurse, 1.0f);
        lo_zuweisung.setComponentAlignment(pan_nurse, new Alignment(48));

        // pan_arzt
        pan_arzt = buildPan_arzt();
        lo_zuweisung.addComponent(pan_arzt);
        lo_zuweisung.setExpandRatio(pan_arzt, 1.0f);
        lo_zuweisung.setComponentAlignment(pan_arzt, new Alignment(48));

        // btn_save
        btn_save = new Button();
        btn_save.setImmediate(true);
        btn_save.setCaption("Speichern");
        btn_save.setWidth("-1px");
        btn_save.setHeight("-1px");
        lo_zuweisung.addComponent(btn_save);
        lo_zuweisung.setComponentAlignment(btn_save, new Alignment(48));

        return lo_zuweisung;
    }

    @AutoGenerated
    private HorizontalLayout buildLo_proj() {
        // common part: create layout
        lo_proj = new HorizontalLayout();
        lo_proj.setImmediate(false);
        lo_proj.setWidth("100.0%");
        lo_proj.setHeight("-1px");
        lo_proj.setMargin(false);
        lo_proj.setSpacing(true);

        // pan_proj
        pan_proj = buildPan_proj();
        lo_proj.addComponent(pan_proj);
        lo_proj.setExpandRatio(pan_proj, 2.0f);

        // pan_aktionen
        pan_aktionen = buildPan_aktionen();
        lo_proj.addComponent(pan_aktionen);
        lo_proj.setExpandRatio(pan_aktionen, 1.0f);

        return lo_proj;
    }

    @AutoGenerated
    private Panel buildPan_proj() {
        // common part: create layout
        pan_proj = new Panel();
        pan_proj.setCaption("Projekt auswahl");
        pan_proj.setImmediate(false);
        pan_proj.setWidth("100.0%");
        pan_proj.setHeight("80px");

        // horizontalLayout_1
        horizontalLayout_1 = buildHorizontalLayout_1();
        pan_proj.setContent(horizontalLayout_1);

        return pan_proj;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_1() {
        // common part: create layout
        horizontalLayout_1 = new HorizontalLayout();
        horizontalLayout_1.setImmediate(false);
        horizontalLayout_1.setWidth("100.0%");
        horizontalLayout_1.setHeight("100.0%");
        horizontalLayout_1.setMargin(true);

        // ns_projekte
        cbx_projekte = new ComboBox();
        cbx_projekte.setImmediate(false);
        cbx_projekte.setWidth("90.0%");
        cbx_projekte.setHeight("-1px");
        horizontalLayout_1.addComponent(cbx_projekte);
        horizontalLayout_1.setComponentAlignment(cbx_projekte, new Alignment(48));

        return horizontalLayout_1;
    }

    @AutoGenerated
    private Panel buildPan_aktionen() {
        // common part: create layout
        pan_aktionen = new Panel();
        pan_aktionen.setCaption("Aktionen");
        pan_aktionen.setImmediate(false);
        pan_aktionen.setWidth("100.0%");
        pan_aktionen.setHeight("80px");

        // verticalLayout_4
        verticalLayout_4 = buildVerticalLayout_4();
        pan_aktionen.setContent(verticalLayout_4);

        return pan_aktionen;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_4() {
        // common part: create layout
        verticalLayout_4 = new VerticalLayout();
        verticalLayout_4.setImmediate(false);
        verticalLayout_4.setWidth("100.0%");
        verticalLayout_4.setHeight("100.0%");
        verticalLayout_4.setMargin(false);

        // cbx_aktiv
        cbx_aktiv = new CheckBox();
        cbx_aktiv.setCaption("Zuweisung aktiv");
        cbx_aktiv.setImmediate(false);
        cbx_aktiv.setWidth("-1px");
        cbx_aktiv.setHeight("-1px");
        verticalLayout_4.addComponent(cbx_aktiv);

        // cb_email
        cb_email = new CheckBox();
        cb_email.setCaption("Email Senden");
        cb_email.setImmediate(false);
        cb_email.setWidth("-1px");
        cb_email.setHeight("-1px");
        verticalLayout_4.addComponent(cb_email);

        // cbx_blanko
        cbx_blanko = new CheckBox();
        cbx_blanko.setCaption("Blankoprotokoll erstellen");
        cbx_blanko.setImmediate(false);
        cbx_blanko.setWidth("-1px");
        cbx_blanko.setHeight("-1px");
        verticalLayout_4.addComponent(cbx_blanko);

        return verticalLayout_4;
    }

    @AutoGenerated
    private Panel buildPan_pat() {
        // common part: create layout
        pan_pat = new Panel();
        pan_pat.setCaption("Patient auswahl");
        pan_pat.setImmediate(false);
        pan_pat.setWidth("100.0%");
        pan_pat.setHeight("80px");

        // horizontalLayout_2
        horizontalLayout_2 = buildHorizontalLayout_2();
        pan_pat.setContent(horizontalLayout_2);

        return pan_pat;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_2() {
        // common part: create layout
        horizontalLayout_2 = new HorizontalLayout();
        horizontalLayout_2.setImmediate(false);
        horizontalLayout_2.setWidth("100.0%");
        horizontalLayout_2.setHeight("100.0%");
        horizontalLayout_2.setMargin(true);

        // cb_patient
        cb_patient = new ComboBox();
        cb_patient.setImmediate(false);
        cb_patient.setWidth("100.0%");
        cb_patient.setHeight("-1px");
        horizontalLayout_2.addComponent(cb_patient);
        horizontalLayout_2.setExpandRatio(cb_patient, 3.0f);
        horizontalLayout_2.setComponentAlignment(cb_patient, new Alignment(48));

        // btn_info_Pat
        btn_info_Pat = new Button();
        btn_info_Pat.setImmediate(true);
        btn_info_Pat.setWidth("-1px");
        btn_info_Pat.setHeight("-1px");
        horizontalLayout_2.addComponent(btn_info_Pat);
        horizontalLayout_2.setExpandRatio(btn_info_Pat, 1.0f);
        horizontalLayout_2.setComponentAlignment(btn_info_Pat, new Alignment(48));

        // btn_Arzt_Zuw
        btn_Arzt_Zuw = new Button();
        btn_Arzt_Zuw.setCaption("Arzt Zuweisen");
        btn_Arzt_Zuw.setImmediate(true);
        btn_Arzt_Zuw.setWidth("-1px");
        btn_Arzt_Zuw.setHeight("-1px");
        horizontalLayout_2.addComponent(btn_Arzt_Zuw);
        horizontalLayout_2.setExpandRatio(btn_Arzt_Zuw, 2.0f);
        horizontalLayout_2.setComponentAlignment(btn_Arzt_Zuw, new Alignment(48));

        return horizontalLayout_2;
    }

    @AutoGenerated
    private Panel buildPan_nurse() {
        // common part: create layout
        pan_nurse = new Panel();
        pan_nurse.setCaption("Auswahl Krankenschwester");
        pan_nurse.setImmediate(false);
        pan_nurse.setWidth("100.0%");
        pan_nurse.setHeight("80px");

        // horizontalLayout_3
        horizontalLayout_3 = buildHorizontalLayout_3();
        pan_nurse.setContent(horizontalLayout_3);

        return pan_nurse;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_3() {
        // common part: create layout
        horizontalLayout_3 = new HorizontalLayout();
        horizontalLayout_3.setImmediate(false);
        horizontalLayout_3.setWidth("100.0%");
        horizontalLayout_3.setHeight("100.0%");
        horizontalLayout_3.setMargin(true);

        // cb_nurse
        cb_nurse = new ComboBox();
        cb_nurse.setImmediate(false);
        cb_nurse.setWidth("100.0%");
        cb_nurse.setHeight("-1px");
        horizontalLayout_3.addComponent(cb_nurse);
        horizontalLayout_3.setExpandRatio(cb_nurse, 3.0f);
        horizontalLayout_3.setComponentAlignment(cb_nurse, new Alignment(48));

        // btn_info_nurse
        btn_info_nurse = new Button();
        btn_info_nurse.setImmediate(true);
        btn_info_nurse.setWidth("-1px");
        btn_info_nurse.setHeight("-1px");
        horizontalLayout_3.addComponent(btn_info_nurse);
        horizontalLayout_3.setExpandRatio(btn_info_nurse, 1.0f);
        horizontalLayout_3.setComponentAlignment(btn_info_nurse, new Alignment(48));

        // btn_ganalyse
        btn_ganalyse = new Button();
        btn_ganalyse.setCaption("Analyse Tool");
        btn_ganalyse.setImmediate(true);
        btn_ganalyse.setWidth("-1px");
        btn_ganalyse.setHeight("-1px");
        horizontalLayout_3.addComponent(btn_ganalyse);
        horizontalLayout_3.setExpandRatio(btn_ganalyse, 2.0f);
        horizontalLayout_3.setComponentAlignment(btn_ganalyse, new Alignment(48));

        return horizontalLayout_3;
    }

    @AutoGenerated
    private Panel buildPan_arzt() {
        // common part: create layout
        pan_arzt = new Panel();
        pan_arzt.setCaption("Arzt Auswahl");
        pan_arzt.setImmediate(false);
        pan_arzt.setWidth("100.0%");
        pan_arzt.setHeight("80px");

        // horizontalLayout_4
        horizontalLayout_4 = buildHorizontalLayout_4();
        pan_arzt.setContent(horizontalLayout_4);

        return pan_arzt;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_4() {
        // common part: create layout
        horizontalLayout_4 = new HorizontalLayout();
        horizontalLayout_4.setImmediate(false);
        horizontalLayout_4.setWidth("100.0%");
        horizontalLayout_4.setHeight("100.0%");
        horizontalLayout_4.setMargin(true);

        // cb_arzt
        cb_arzt = new ComboBox();
        cb_arzt.setImmediate(false);
        cb_arzt.setWidth("100.0%");
        cb_arzt.setHeight("-1px");
        horizontalLayout_4.addComponent(cb_arzt);
        horizontalLayout_4.setExpandRatio(cb_arzt, 2.0f);
        horizontalLayout_4.setComponentAlignment(cb_arzt, new Alignment(48));

        // btn_info_arzt
        btn_info_arzt = new Button();
        btn_info_arzt.setImmediate(true);
        btn_info_arzt.setWidth("-1px");
        btn_info_arzt.setHeight("-1px");
        horizontalLayout_4.addComponent(btn_info_arzt);
        horizontalLayout_4.setExpandRatio(btn_info_arzt, 1.0f);
        horizontalLayout_4.setComponentAlignment(btn_info_arzt, new Alignment(48));

        return horizontalLayout_4;
    }

}
