package archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektzuweisung.Form;

import java.text.DateFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

import org.joda.time.LocalDate;
import org.tepi.filtertable.FilterTable;

import archenoah.config.CMS_Config_Std;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.tool.java_plugin.QuickConverter.QuickCollectionArrayConverter;
import archenoah.lib.vaadin.Components.CustomComponentExt;
import archenoah.lib.vaadin.Components.Steppers.IntStepper;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Tab_Menue_Item;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Window_Button;
import archenoah.lib.vaadin.CustomConverterFactorys.StringLocalDateConverter;
import archenoah.lib.vaadin.Forms_Builder.Form_Bind;
import archenoah.lib.vaadin.Language.i18n.I18nCB;
import archenoah.lib.vaadin.Language.i18n.I18nManager;

import com.google.ical.compat.jodatime.LocalDateIterator;
import com.google.ical.compat.jodatime.LocalDateIteratorFactory;
import com.google.ical.values.DateValue;
import com.google.ical.values.DateValueImpl;
import com.google.ical.values.Frequency;
import com.google.ical.values.RRule;
import com.google.ical.values.Weekday;
import com.google.ical.values.WeekdayNum;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.data.util.ObjectProperty;
import com.vaadin.data.util.PropertysetItem;
import com.vaadin.event.FieldEvents.TextChangeEvent;
import com.vaadin.event.FieldEvents.TextChangeListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbstractField;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TwinColSelect;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
//A Joda time class that represents a day regardless of timezone

//A compatibility layer for joda-time

public class form_projektzuweisung_rrule extends CustomComponentExt {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private VerticalLayout mainLayout;

    @AutoGenerated
    private Button btn_close;

    @AutoGenerated
    private Panel panel_1;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_2;

    @AutoGenerated
    private VerticalLayout verticalLayout_3;

    @AutoGenerated
    private TextArea txta_rrule;

    @AutoGenerated
    private CheckBox cb_cust_rrule;

    @AutoGenerated
    private FilterTable tbl_preview;

    @AutoGenerated
    private Panel pan_pat;

    @AutoGenerated
    private VerticalLayout lo_pat;

    @AutoGenerated
    private HorizontalLayout lo_by;

    @AutoGenerated
    private TwinColSelect col_bymonth;

    @AutoGenerated
    private TwinColSelect col_byweekno;

    @AutoGenerated
    private TwinColSelect col_bymonthday;

    @AutoGenerated
    private HorizontalLayout lo_byday;

    @AutoGenerated
    private VerticalLayout lo_byday_7;

    @AutoGenerated
    private IntStepper byday_su_int;

    @AutoGenerated
    private CheckBox byday_su;

    @AutoGenerated
    private VerticalLayout lo_byday_6;

    @AutoGenerated
    private IntStepper byday_sa_int;

    @AutoGenerated
    private CheckBox byday_sa;

    @AutoGenerated
    private VerticalLayout lo_byday_5;

    @AutoGenerated
    private IntStepper byday_fr_int;

    @AutoGenerated
    private CheckBox byday_fr;

    @AutoGenerated
    private VerticalLayout lo_byday_4;

    @AutoGenerated
    private IntStepper byday_th_int;

    @AutoGenerated
    private CheckBox byday_th;

    @AutoGenerated
    private VerticalLayout lo_byday_3;

    @AutoGenerated
    private IntStepper byday_we_int;

    @AutoGenerated
    private CheckBox byday_we;

    @AutoGenerated
    private VerticalLayout lo_byday_2;

    @AutoGenerated
    private IntStepper byday_tu_int;

    @AutoGenerated
    private CheckBox byday_tu;

    @AutoGenerated
    private VerticalLayout lo_byday_1;

    @AutoGenerated
    private IntStepper byday_mo_int;

    @AutoGenerated
    private CheckBox byday_mo;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_1;

    @AutoGenerated
    private IntStepper int_interval;

    @AutoGenerated
    private ComboBox pat_freq;

    @AutoGenerated
    private Panel pan_term;

    @AutoGenerated
    private HorizontalLayout lo_term;

    @AutoGenerated
    private HorizontalLayout lo_term_end_count;

    @AutoGenerated
    private HorizontalLayout lo_term_end_until;

    @AutoGenerated
    private PopupDateField date_term_end_until;

    @AutoGenerated
    private CheckBox cb_term_end_until;

    @AutoGenerated
    private Label lbl_term_end_count;

    @AutoGenerated
    private IntStepper int_term_end_count;

    @AutoGenerated
    private CheckBox cb_term_end_count;

    @AutoGenerated
    private PopupDateField date_start;

    

    

    

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */

    /**************** --> Allgemein <--- ********************/
    // Allgemein
    private CMS_Config_Std std;
    private String Exportname;

    private Form_Bind fb;
    private String Form_ID = "";

    // Datenbank
    private Map<Object, String> DBMap;
    private Map<Object, String> ValidateMap;
    private DBClass db;

    private MenuItem Temp_Menü = null;
    private Button Temp_Btn = null;
    private TabSheet tab = null;
    private Window win = null;

    private final boolean Status_Fill = false;

    private HashMap<String, String> prefilledInitVars;

    /************ ----->Einstellungen<-- ********************/
    private final String LNG_FRM_ID = "1001";
    private final String BER_MEN_ID = "";
    private final String Windows_Height = "600px";
    private final String Windows_Width = "560px";

    /******************************************************/

    IndexedContainer conForm = null;
    IndexedContainer conTable = null;
    Item formSet = null;
    RRule rrule = null;
    FieldGroup binderForm = null;

    Boolean setValueStopper = false;
    Boolean clearingForm = false;
    HashMap<Weekday, CheckBox> dayCb = null;
    HashMap<Weekday, IntStepper> dayInt = null;

    private I18nManager i18n;

    private final static class caption extends I18nCB {
        static final I18nCB DAILY = set();
        static final I18nCB WEEKLY = set();
        static final I18nCB MONTHLY = set();
        static final I18nCB YEARLY = set();
        
    }
    
    /******************************************************/

    public form_projektzuweisung_rrule() {

    }

    public form_projektzuweisung_rrule(MenuItem Arg_Menü, String Arg_Form_ID) {
	Temp_Menü = Arg_Menü;
	Form_ID = Arg_Form_ID;

	// TODO add user code here
    }

    public form_projektzuweisung_rrule(Button Arg_btn, String Arg_Form_ID) {

	Temp_Btn = Arg_btn;
        Form_ID = Arg_Form_ID;

        // TODO add user code here
    }

    /***************************** ---> Feste Funtionen<--- **************************************/

    /********* INIT-Window ************/
    public void Init_Class_Window() {
        if (Windows_Height.equals("") == true || Windows_Width.equals("") == true) {
            System.out.println("Form Einstellung Fehlt: !!!");
            return;
        }

        Standard_Init();

        if (Temp_Menü != null) {
            String Recourcename = Temp_Menü.getIcon().toString();
            Recourcename = Recourcename.substring(0, Recourcename.length() - 12) + "white-16.png";

            Exportname = Temp_Menü.getText();
            Build_Window_Button bwb = new Build_Window_Button(Temp_Menü.getText(), mainLayout, Windows_Height, Windows_Width,
                    new ThemeResource(Recourcename));
            win = bwb.ReturnWindow();

        }
        if (Temp_Btn != null) {
            Exportname = Temp_Btn.getCaption();
            Build_Window_Button bwb = new Build_Window_Button(Temp_Btn.getCaption(), mainLayout, Windows_Height, Windows_Width,
                    Temp_Btn.getIcon());
            win = bwb.ReturnWindow();
        }

    }

    /********* INIT-Tray ************/
    public void Init_Class_Tab(TabSheet Arg_tab) {

        Standard_Init();
        tab = Arg_tab;
        if (Temp_Menü != null) {
            Exportname = Temp_Menü.getText();
            Build_Tab_Menue_Item bt = new Build_Tab_Menue_Item(Arg_tab, Temp_Menü.getText(), mainLayout, Temp_Menü.getIcon());
        }
        if (Temp_Btn != null) {
            Exportname = Temp_Btn.getCaption();
            Build_Tab_Menue_Item bt = new Build_Tab_Menue_Item(Arg_tab, Temp_Btn.getCaption(), mainLayout, Temp_Btn.getIcon());
        }

    }

    /********* Init-Standard ************/
    private void Standard_Init() {
        buildMainLayout();
        i18n = new I18nManager(this);

        setDbMap();
        /**********/

        fillFields();
        configFields();
        setContainerTable();
        setContainerForm();
        setEvents();

        if (Form_ID != "" && Form_ID != "0") {
            dbGet();
            setEnabled(false);
        }else {
            date_start.setValue(null); // ObjectProperties can't be initialized to null
        }
        i18n.refresh();
    }

    /* public function */
    public void showWindow() {
        if (win != null && !win.isAttached()) {
            UI.getCurrent().getUI().addWindow(win);
        }else {
            win.setVisible(true);
        }
    }
    
    @Override
    public void setEnabled(boolean enabled) {
        pan_term.setEnabled(enabled);
        pan_pat.setEnabled(enabled);
        panel_1.setEnabled(enabled);
        pan_term.setStyleName(enabled ? "" : "nogrey");
        pan_pat.setStyleName(enabled ? "" : "nogrey");
        panel_1.setStyleName(enabled ? "" : "nogrey");
    }
    
    public Boolean isValid() {
//        Boolean valid = true;
//        try {
//            String rruleLocal = txta_rrule.getValue().replaceAll("[^\\S\\r\\n]", "");
//            if (rruleLocal.length() < 20) {
//                valid = false;
//            }
//            LocalDate start = new LocalDate(date_start.getValue().getYear() + 1900, date_start.getValue().getMonth() + 1, date_start
//                    .getValue().getDate());
//            LocalDateIteratorFactory.createLocalDateIterable(rruleLocal, start, true);
//        } catch (ParseException e) {
//            valid = false;
//        }
//        return valid;
        
        generateDates();
        return (conTable.size() > 0);
        
    }
    
    public Boolean hasDateStart() {
        return date_start.getValue() != null;
    }
    
    public void setDate(Date date){
//        System.out.println("setting date_start to " + date);
        date_start.setValue(date);
        
        if(cb_term_end_until.getValue()){
            LocalDate lDate = new LocalDate(date);
            lDate = lDate.plusYears(100);
            date_term_end_until.setValue(lDate.toDate());
        }
    }
    
    public String save() {
        Integer id = null;
        String re = "";
        if (Form_ID != "") {
            dbUpdate();
            re = Form_ID;
        } else {
            id = dbInsert();
            re = Integer.toString(id);
        }
        return re;
    }

    /* ************************** */
    private void fillFields() {
        cb_term_end_count.setValue(false);
        int_term_end_count.setMinValue(1);
        int_term_end_count.setValue(0);

        cb_term_end_until.setValue(true);
        LocalDate lDate = new LocalDate();
        lDate = lDate.plusYears(100);
        date_term_end_until.setValue(lDate.toDate());
        // TASK: needs localization
        date_term_end_until.setDateFormat("dd.MM.yyyy");

        pat_freq.addItem(Frequency.DAILY);
        pat_freq.setItemCaption(Frequency.DAILY, i18n.get(caption.DAILY));
        pat_freq.addItem(Frequency.WEEKLY);
        pat_freq.setItemCaption(Frequency.WEEKLY, i18n.get(caption.WEEKLY));
        pat_freq.addItem(Frequency.MONTHLY);
        pat_freq.setItemCaption(Frequency.MONTHLY, i18n.get(caption.MONTHLY));
        pat_freq.addItem(Frequency.YEARLY);
        pat_freq.setItemCaption(Frequency.YEARLY, i18n.get(caption.YEARLY));

        dayCb = new HashMap<Weekday, CheckBox>();
        dayInt = new HashMap<Weekday, IntStepper>();

        dayCb.put(Weekday.MO, byday_mo);
        dayInt.put(Weekday.MO, byday_mo_int);
        dayCb.put(Weekday.TU, byday_tu);
        dayInt.put(Weekday.TU, byday_tu_int);
        dayCb.put(Weekday.WE, byday_we);
        dayInt.put(Weekday.WE, byday_we_int);
        dayCb.put(Weekday.TH, byday_th);
        dayInt.put(Weekday.TH, byday_th_int);
        dayCb.put(Weekday.FR, byday_fr);
        dayInt.put(Weekday.FR, byday_fr_int);
        dayCb.put(Weekday.SA, byday_sa);
        dayInt.put(Weekday.SA, byday_sa_int);
        dayCb.put(Weekday.SU, byday_su);
        dayInt.put(Weekday.SU, byday_su_int);

        for (int i = 1; i <= 31; i++) {
            col_bymonthday.addItem(i);
        }
        for (int i = -1; i >= -31; i--) {
            col_bymonthday.addItem(i);
        }
        for (int i = 1; i <= 53; i++) {
            col_byweekno.addItem(i);
        }
        for (int i = -1; i >= -53; i--) {
            col_byweekno.addItem(i);
        }
        for (int i = 1; i <= 12; i++) {
            col_bymonth.addItem(i);
        }
    }

    private void configFields() {
        ArrayList<IntStepper> steppers = new ArrayList<IntStepper>();
        steppers.add(byday_mo_int);
        steppers.add(byday_tu_int);
        steppers.add(byday_we_int);
        steppers.add(byday_th_int);
        steppers.add(byday_fr_int);
        steppers.add(byday_sa_int);
        steppers.add(byday_su_int);

        for (IntStepper intStepper : steppers) {
            intStepper.setMinValue(-4);
            intStepper.setMaxValue(4);
            intStepper.setInvalidValuesAllowed(false);
            intStepper.setValue(0);
        }

        int_interval.setMinValue(0);
        int_interval.setValue(0);

        ArrayList<AbstractField> al = new ArrayList<AbstractField>();
        al.add(cb_term_end_count);
        al.add(int_term_end_count);

        al.add(cb_term_end_until);
        al.add(date_term_end_until);

        al.add(pat_freq);
        al.add(int_interval);

        al.add(byday_mo);
        al.add(byday_mo_int);
        al.add(byday_tu);
        al.add(byday_tu_int);
        al.add(byday_we);
        al.add(byday_we_int);
        al.add(byday_th);
        al.add(byday_th_int);
        al.add(byday_fr);
        al.add(byday_fr_int);
        al.add(byday_sa);
        al.add(byday_sa_int);
        al.add(byday_su);
        al.add(byday_su_int);

        al.add(col_bymonthday);
        al.add(col_byweekno);
        al.add(col_bymonth);

        ValueChangeListener vcl = new ValueChangeListener() {

            @Override
            public void valueChange(com.vaadin.data.Property.ValueChangeEvent event) {

                if (clearingForm == false) {
                    generateRrule();
                }

            }
        };

        for (AbstractField abstractField : al) {
            abstractField.setImmediate(true);
            abstractField.addValueChangeListener(vcl);
        }

    }

    //    `RRL_ID` INT(11) NOT NULL AUTO_INCREMENT,
    //	`RRL_START` DATE NULL DEFAULT NULL,
    //	`RRL_RRULE` VARCHAR(255) NULL DEFAULT '' COLLATE 'utf8_bin',
    //	`RRL_COUNT` INT(11) NULL DEFAULT '0',
    //	`RRL_END` DATE NULL DEFAULT NULL,
    //	`RRL_CUSTOM` TINYINT(1) NOT NULL DEFAULT '0',

    //    FREQ =  "DAILY" / "WEEKLY" / "MONTHLY" / "YEARLY"
    //
    //	    ( ";" "UNTIL" "=" An UTC value ) /
    //	    ( ";" "COUNT" "=" 1*DIGIT ) /
    //
    //	    ( ";" "INTERVAL" "=" 1*DIGIT )          /
    //
    //	    ( ";" "BYDAY" "=" "SU" / "MO" / "TU" / "WE" / "TH" / "FR" / "SA" )          /
    //	     ( ";" "BYMONTHDAY" "=" [-] 1 to 31 )    /
    //	     ( ";" "BYWEEKNO" "=" [-] 1 to 53 )
    //	     ( ";" "BYMONTH" "=" 1 to 12 ) 

    private void setContainerTable() {
        conTable = new IndexedContainer();
        conTable.addContainerProperty("date", LocalDate.class, new LocalDate(0, 1, 1));

        StringLocalDateConverter converter = new StringLocalDateConverter();
        converter.setFormat(DateFormat.FULL);

        tbl_preview.setContainerDataSource(conTable);
        tbl_preview.setConverter("date", converter);

    }

    private void setContainerForm() {
        formSet = new PropertysetItem();
        //item.addItemProperty("RRL_ID", new ObjectProperty<Integer>(null));
        formSet.addItemProperty("RRL_START", new ObjectProperty<Date>(new Date()));
        formSet.addItemProperty("RRL_RRULE", new ObjectProperty<String>(""));
        //item.addItemProperty("RRL_COUNT", new ObjectProperty<Integer>(0));
        //item.addItemProperty("RRL_UNTIL", new ObjectProperty<Date>(null));
        formSet.addItemProperty("RRL_CUSTOM", new ObjectProperty<Boolean>(false));

        binderForm = new FieldGroup(formSet);

        binderForm.bind(date_start, "RRL_START");
        binderForm.bind(txta_rrule, "RRL_RRULE");
        binderForm.bind(cb_cust_rrule, "RRL_CUSTOM");

        binderForm.setBuffered(false);
        txta_rrule.setEnabled(false);
    }

    private void setDbMap() {
        DBMap = new HashMap<>();
        DBMap.put(date_start, "cust_protokoll_rrules:RRL_START");
        DBMap.put(txta_rrule, "cust_protokoll_rrules:RRL_RRULE");
        DBMap.put(cb_cust_rrule, "cust_protokoll_rrules:RRL_CUSTOM");
    }

    private void setEvents() {
        
        date_start.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
//                System.out.println("value changed to " + event.getProperty().getValue());
                
                generateDates();
                
            }
        });
        
        cb_term_end_count.addValueChangeListener(new ValueChangeListener() {

            @Override
            public void valueChange(ValueChangeEvent event) {

                Boolean thisValue = cb_term_end_count.getValue();

                if (thisValue == true) {
                    int_term_end_count.setMinValue(1);
                    if (int_term_end_count.getValue() == 0) {
                        int_term_end_count.setValue(1);
                    }
                } else {
                    int_term_end_count.setMinValue(0);
                    int_term_end_count.setValue(0);
                }

                if (setValueStopper == true) {
                    return;
                }

                setValueStopper = true;
                cb_term_end_until.setValue(!thisValue);
                setValueStopper = false;

            }
        });

        cb_term_end_until.addValueChangeListener(new ValueChangeListener() {

            @Override
            public void valueChange(ValueChangeEvent event) {

                Boolean thisValue = cb_term_end_until.getValue();

                if (setValueStopper == true) {
                    return;
                }

                setValueStopper = true;
                cb_term_end_count.setValue(!thisValue);
                setValueStopper = false;

            }
        });

        cb_cust_rrule.addValueChangeListener(new ValueChangeListener() {

            @Override
            public void valueChange(ValueChangeEvent event) {

                Boolean customEnabled = (Boolean) event.getProperty().getValue();
                String tmpRrule = txta_rrule.getValue();

                lo_term_end_count.setEnabled(!customEnabled);
                lo_term_end_until.setEnabled(!customEnabled);
                pan_pat.setEnabled(!customEnabled);

                if (customEnabled == true) {
                    clearForm();
                    binderForm.getField("RRL_RRULE").getPropertyDataSource().setValue(tmpRrule);
                    generateDates();
                } else {
                    fillForm(tmpRrule);
                }

                txta_rrule.setEnabled(customEnabled);
            }

        });

        txta_rrule.addValueChangeListener(new ValueChangeListener() {

            @Override
            public void valueChange(ValueChangeEvent event) {

            }
        });

        txta_rrule.addTextChangeListener(new TextChangeListener() {

            @Override
            public void textChange(TextChangeEvent event) {

                if (cb_cust_rrule.getValue() == true) {
                    generateDates(event.getText());
                } else {

                }

            }
        });

        btn_close.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {

                win.close();

            }
        });
    }

    private void generateRrule() {

        txta_rrule.setValue("");
        conTable.removeAllItems();

        if (date_start.getValue() == null) {
            return;
        }

        if (pat_freq.getValue() == null) {
            return;
        }

        if (cb_term_end_until.getValue() == true && date_term_end_until.getValue() == null) {
            return;
        }

        String ical = "RRULE:FREQ=MONTHLY" + ";BYDAY=FR" // every Friday
                + ";BYMONTHDAY=13" // that occurs on the 13th of the month
                + ";COUNT=13"; // stop after 13 occurences

        rrule = new RRule();

        rrule.setFreq((Frequency) pat_freq.getValue());
        rrule.setInterval(int_interval.getValue());

        if (cb_term_end_count.getValue() == true) {
            rrule.setCount(int_term_end_count.getValue());
        }

        if (cb_term_end_until.getValue() == true) {
            Date date = date_term_end_until.getValue();
            LocalDate lDate = new LocalDate(date);
            DateValue dateValue = new DateValueImpl(lDate.getYear(), lDate.getMonthOfYear(), lDate.getDayOfMonth());
            rrule.setUntil(dateValue);
        }

        ArrayList<WeekdayNum> byDay = new ArrayList<WeekdayNum>();

        for (Entry<Weekday, CheckBox> entry : dayCb.entrySet()) {
            if (entry.getValue().getValue() == true) {
                byDay.add(new WeekdayNum(dayInt.get(entry.getKey()).getValue(), entry.getKey()));
            }
        }

        rrule.setByDay(byDay);

        //BYMONTHDAY
        Collection<Integer> byMonthDay = (Collection<Integer>) col_bymonthday.getValue();
        rrule.setByMonthDay(QuickCollectionArrayConverter.toIntArray(byMonthDay));

        //BYWEEKNO
        Collection<Integer> byWeekNo = (Collection<Integer>) col_byweekno.getValue();
        rrule.setByWeekNo(QuickCollectionArrayConverter.toIntArray(byWeekNo));

        //BYWEEKNO
        Collection<Integer> byMonth = (Collection<Integer>) col_bymonth.getValue();
        rrule.setByMonth(QuickCollectionArrayConverter.toIntArray(byMonth));

        binderForm.getField("RRL_RRULE").getPropertyDataSource().setValue(rrule.toIcal());
        generateDates();
    }

    private void generateDates(final String rruleLocal) {
        conTable.removeAllItems();

        if (date_start.getValue() == null) {
            return;
        }

        if (txta_rrule.getValue().equals("") == true) {
            return;
        }

        // use runnable and ExecutorService to avoid hangs
        // if EXRULE matches RRULE and no dates are generated by the iterator 
        final Runnable stuffToDo = new Thread() {

            Integer max = 100;
            Integer current = 0;

            @Override
            public void run() {

                LocalDateIterator iter;
                try {
                    iter = LocalDateIteratorFactory.createLocalDateIterable(rruleLocal.replaceAll("[^\\S\\r\\n]", ""),
                        new LocalDate(date_start.getValue().getTime()), true).iterator();

                    while (iter.hasNext()) {
                        LocalDate date = iter.next();

                        if (++current <= max) {
                            conTable.getItem(conTable.addItem()).getItemProperty("date").setValue(date);
                        } else {
                            break;
                        }

                    }

                } catch (ParseException e) {
                    conTable.removeAllItems();
                }

            }
        };

        final ExecutorService executor = Executors.newSingleThreadExecutor();
        final Future future = executor.submit(stuffToDo);
        executor.shutdown();

        try {
            future.get(250, TimeUnit.MILLISECONDS);
        } catch (InterruptedException ie) {
        } catch (ExecutionException ee) {
        } catch (TimeoutException te) {
        }

        if (!executor.isTerminated())
            executor.shutdownNow();

    }

    private void generateDates() {
        String rruleLocal = txta_rrule.getValue();
        generateDates(rruleLocal);
    }

    private void clearForm() {
        clearingForm = true;

        cb_term_end_count.setValue(false);
        int_term_end_count.setValue(0);
        cb_term_end_until.setValue(false);
        date_term_end_until.setValue(null);

        pat_freq.setValue(null);
        int_interval.setValue(0);

        for (Entry<Weekday, CheckBox> entry : dayCb.entrySet()) {
            dayCb.get(entry.getKey()).setValue(false);
            dayInt.get(entry.getKey()).setValue(0);
        }

        col_bymonthday.setValue(null);
        col_byweekno.setValue(null);
        col_bymonth.setValue(null);

        txta_rrule.setValue("");
        generateDates();

        clearingForm = false;
    }

    private void fillForm(String tmpString) {
        clearForm();
        RRule tmpRrule = null;

        if (formSet.getItemProperty("RRL_START").getValue() == null) {
            formSet.getItemProperty("RRL_START").setValue(new Date());
        }

        //formSet.getItemProperty("RRL_RRULE").setValue(tmpRule);

        //	binderForm.bind(date_start, "RRL_START");
        //	binderForm.bind(txta_rrule, "RRL_RRULE");
        //	binderForm.bind(cb_cust_rrule, "RRL_CUSTOM");

        try {
            tmpRrule = new RRule(tmpString);
        } catch (ParseException e) {
            clearForm();
            return;
        }

        if (tmpRrule.getCount() != 0) {
            cb_term_end_count.setValue(true);
            int_term_end_count.setValue(tmpRrule.getCount());
        }

        if (tmpRrule.getUntil() != null) {
            cb_term_end_until.setValue(true);
            DateValue untilDateValue = tmpRrule.getUntil();
            LocalDate untilLocalDate = new LocalDate(untilDateValue.year(), untilDateValue.month(), untilDateValue.day());
            date_term_end_until.setValue(untilLocalDate.toDate());
        }

        pat_freq.setValue(tmpRrule.getFreq());
        int_interval.setValue(tmpRrule.getInterval());

        List<WeekdayNum> byDay = tmpRrule.getByDay();

        for (WeekdayNum weekdayNum : byDay) {
            dayCb.get(weekdayNum.wday).setValue(true);
            dayInt.get(weekdayNum.wday).setValue(weekdayNum.num);
        }

        col_bymonthday.setValue(QuickCollectionArrayConverter.toHashSet(tmpRrule.getByMonthDay()));
        col_byweekno.setValue(QuickCollectionArrayConverter.toHashSet(tmpRrule.getByWeekNo()));
        col_bymonth.setValue(QuickCollectionArrayConverter.toHashSet(tmpRrule.getByMonth()));

    }

    private void dbGet() {
        db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();

        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_protokoll_rrules");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_protokoll_rrules", "RRL_ID", "=", Form_ID, "");

        //db.DB_Data_Get.DB_DEBUG_SQL_STRING();

        Item item = db.DB_Data_Get.DB_SEND_AND_GET_FIRST_ITEM();

        if (item == null) {
            return;
        }

        formSet = item;
        //binderForm.setItemDataSource(item);
//        System.out.println(item);
        fillForm((String) item.getItemProperty("RRL_RRULE").getValue());
        setDate((Date) item.getItemProperty("RRL_START").getValue());
    }

    private int dbInsert() {
        Integer id = null;
        DBClass dba = new DBClass();
        fb = new Form_Bind();

        fb.Insert(dba, DBMap);

        dba.DB_Data_Insert.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_protokoll_rrules");

        id = dba.DB_Data_Insert.DB_Insert();

        return id;
    }

    private void dbUpdate() {
        db = new DBClass();
        fb = new Form_Bind();
        fb.Update(db, DBMap);

        /******************************** Table ****************************************/
        db.DB_Data_Update.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_protokoll_rrules");
        /******************************************************************************/
        /******************************** Filter ****************************************/
        db.DB_Data_Update.DB_Filter.DB_WHERE_Allgemein("cust_protokoll_rrules", "RRL_ID", "=", Form_ID, "");
        /******************************************************************************/
        db.DB_Data_Update.DB_Update();

    }

    @AutoGenerated
    private VerticalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);

        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");

        // pan_term
        pan_term = buildPan_term();
        mainLayout.addComponent(pan_term);
        mainLayout.setExpandRatio(pan_term, 1.2f);
        mainLayout.setComponentAlignment(pan_term, new Alignment(48));

        // pan_pat
        pan_pat = buildPan_pat();
        mainLayout.addComponent(pan_pat);
        mainLayout.setExpandRatio(pan_pat, 3.0f);
        mainLayout.setComponentAlignment(pan_pat, new Alignment(48));

        // panel_1
        panel_1 = buildPanel_1();
        mainLayout.addComponent(panel_1);
        mainLayout.setExpandRatio(panel_1, 2.2f);
        mainLayout.setComponentAlignment(panel_1, new Alignment(24));

        // btn_close
        btn_close = new Button();
        btn_close.setCaption("Schließen");
        btn_close.setImmediate(true);
        btn_close.setWidth("-1px");
        btn_close.setHeight("-1px");
        mainLayout.addComponent(btn_close);
        mainLayout.setExpandRatio(btn_close, 0.5f);
        mainLayout.setComponentAlignment(btn_close, new Alignment(48));

        return mainLayout;
    }

    @AutoGenerated
    private Panel buildPan_term() {
        // common part: create layout
        pan_term = new Panel();
        pan_term.setCaption("Terminierung");
        pan_term.setImmediate(false);
        pan_term.setWidth("500px");
        pan_term.setHeight("-1px");

        // lo_term
        lo_term = buildLo_term();
        pan_term.setContent(lo_term);

        return pan_term;
    }

    @AutoGenerated
    private HorizontalLayout buildLo_term() {
        // common part: create layout
        lo_term = new HorizontalLayout();
        lo_term.setImmediate(false);
        lo_term.setWidth("100.0%");
        lo_term.setHeight("100.0%");
        lo_term.setMargin(true);

        // date_start
        date_start = new PopupDateField();
        date_start.setCaption("Startdatum");
        date_start.setImmediate(false);
        date_start.setWidth("100px");
        date_start.setHeight("-1px");
        lo_term.addComponent(date_start);
        lo_term.setExpandRatio(date_start, 1.0f);
        lo_term.setComponentAlignment(date_start, new Alignment(48));

        // lo_term_end_count
        lo_term_end_count = buildLo_term_end_count();
        lo_term.addComponent(lo_term_end_count);
        lo_term.setExpandRatio(lo_term_end_count, 3.0f);
        lo_term.setComponentAlignment(lo_term_end_count, new Alignment(24));

        return lo_term;
    }

    @AutoGenerated
    private HorizontalLayout buildLo_term_end_count() {
        // common part: create layout
        lo_term_end_count = new HorizontalLayout();
        lo_term_end_count.setImmediate(false);
        lo_term_end_count.setWidth("-1px");
        lo_term_end_count.setHeight("-1px");
        lo_term_end_count.setMargin(false);
        lo_term_end_count.setSpacing(true);

        // cb_term_end_count
        cb_term_end_count = new CheckBox();
        cb_term_end_count.setCaption("Nach");
        cb_term_end_count.setImmediate(false);
        cb_term_end_count.setWidth("-1px");
        cb_term_end_count.setHeight("-1px");
        lo_term_end_count.addComponent(cb_term_end_count);

        // int_term_end_count
        int_term_end_count = new IntStepper();
        int_term_end_count.setImmediate(false);
        int_term_end_count.setWidth("40px");
        int_term_end_count.setHeight("-1px");
        lo_term_end_count.addComponent(int_term_end_count);

        // lbl_term_end_count
        lbl_term_end_count = new Label();
        lbl_term_end_count.setImmediate(false);
        lbl_term_end_count.setWidth("-1px");
        lbl_term_end_count.setHeight("-1px");
        lbl_term_end_count.setValue("Wiederholungen");
        lo_term_end_count.addComponent(lbl_term_end_count);

        // lo_term_end_until
        lo_term_end_until = buildLo_term_end_until();
        lo_term_end_count.addComponent(lo_term_end_until);

        return lo_term_end_count;
    }

    @AutoGenerated
    private HorizontalLayout buildLo_term_end_until() {
        // common part: create layout
        lo_term_end_until = new HorizontalLayout();
        lo_term_end_until.setImmediate(false);
        lo_term_end_until.setWidth("-1px");
        lo_term_end_until.setHeight("-1px");
        lo_term_end_until.setMargin(false);
        lo_term_end_until.setSpacing(true);

        // cb_term_end_until
        cb_term_end_until = new CheckBox();
        cb_term_end_until.setCaption("Bis");
        cb_term_end_until.setImmediate(false);
        cb_term_end_until.setWidth("-1px");
        cb_term_end_until.setHeight("-1px");
        lo_term_end_until.addComponent(cb_term_end_until);

        // date_term_end_until
        date_term_end_until = new PopupDateField();
        date_term_end_until.setImmediate(false);
        date_term_end_until.setWidth("80px");
        date_term_end_until.setHeight("-1px");
        lo_term_end_until.addComponent(date_term_end_until);

        return lo_term_end_until;
    }

    @AutoGenerated
    private Panel buildPan_pat() {
        // common part: create layout
        pan_pat = new Panel();
        pan_pat.setCaption("Wiederholungsmuster");
        pan_pat.setImmediate(false);
        pan_pat.setWidth("500px");
        pan_pat.setHeight("-1px");

        // lo_pat
        lo_pat = buildLo_pat();
        pan_pat.setContent(lo_pat);

        return pan_pat;
    }

    @AutoGenerated
    private VerticalLayout buildLo_pat() {
        // common part: create layout
        lo_pat = new VerticalLayout();
        lo_pat.setImmediate(false);
        lo_pat.setWidth("100.0%");
        lo_pat.setHeight("100.0%");
        lo_pat.setMargin(false);
        lo_pat.setSpacing(true);

        // horizontalLayout_1
        horizontalLayout_1 = buildHorizontalLayout_1();
        lo_pat.addComponent(horizontalLayout_1);
        lo_pat.setComponentAlignment(horizontalLayout_1, new Alignment(48));

        // lo_byday
        lo_byday = buildLo_byday();
        lo_pat.addComponent(lo_byday);

        // lo_by
        lo_by = buildLo_by();
        lo_pat.addComponent(lo_by);
        lo_pat.setComponentAlignment(lo_by, new Alignment(48));

        return lo_pat;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_1() {
        // common part: create layout
        horizontalLayout_1 = new HorizontalLayout();
        horizontalLayout_1.setImmediate(false);
        horizontalLayout_1.setWidth("100.0%");
        horizontalLayout_1.setHeight("-1px");
        horizontalLayout_1.setMargin(false);

        // pat_freq
        pat_freq = new ComboBox();
        pat_freq.setCaption("Frequenz");
        pat_freq.setImmediate(false);
        pat_freq.setWidth("-1px");
        pat_freq.setHeight("-1px");
        horizontalLayout_1.addComponent(pat_freq);
        horizontalLayout_1.setComponentAlignment(pat_freq, new Alignment(48));

        // int_interval
        int_interval = new IntStepper();
        int_interval.setCaption("Interval");
        int_interval.setImmediate(false);
        int_interval.setWidth("-1px");
        int_interval.setHeight("-1px");
        horizontalLayout_1.addComponent(int_interval);
        horizontalLayout_1.setComponentAlignment(int_interval, new Alignment(48));

        return horizontalLayout_1;
    }

    @AutoGenerated
    private HorizontalLayout buildLo_byday() {
        // common part: create layout
        lo_byday = new HorizontalLayout();
        lo_byday.setCaption("Wochentage");
        lo_byday.setImmediate(false);
        lo_byday.setWidth("-1px");
        lo_byday.setHeight("-1px");
        lo_byday.setMargin(false);

        // lo_byday_1
        lo_byday_1 = buildLo_byday_1();
        lo_byday.addComponent(lo_byday_1);

        // lo_byday_2
        lo_byday_2 = buildLo_byday_2();
        lo_byday.addComponent(lo_byday_2);

        // lo_byday_3
        lo_byday_3 = buildLo_byday_3();
        lo_byday.addComponent(lo_byday_3);

        // lo_byday_4
        lo_byday_4 = buildLo_byday_4();
        lo_byday.addComponent(lo_byday_4);

        // lo_byday_5
        lo_byday_5 = buildLo_byday_5();
        lo_byday.addComponent(lo_byday_5);

        // lo_byday_6
        lo_byday_6 = buildLo_byday_6();
        lo_byday.addComponent(lo_byday_6);

        // lo_byday_7
        lo_byday_7 = buildLo_byday_7();
        lo_byday.addComponent(lo_byday_7);

        return lo_byday;
    }

    @AutoGenerated
    private VerticalLayout buildLo_byday_1() {
        // common part: create layout
        lo_byday_1 = new VerticalLayout();
        lo_byday_1.setImmediate(false);
        lo_byday_1.setWidth("-1px");
        lo_byday_1.setHeight("-1px");
        lo_byday_1.setMargin(false);

        // byday_mo
        byday_mo = new CheckBox();
        byday_mo.setCaption("Mo");
        byday_mo.setImmediate(false);
        byday_mo.setWidth("-1px");
        byday_mo.setHeight("-1px");
        lo_byday_1.addComponent(byday_mo);

        // byday_mo_int
        byday_mo_int = new IntStepper();
        byday_mo_int.setImmediate(false);
        byday_mo_int.setWidth("70px");
        byday_mo_int.setHeight("-1px");
        lo_byday_1.addComponent(byday_mo_int);

        return lo_byday_1;
    }

    @AutoGenerated
    private VerticalLayout buildLo_byday_2() {
        // common part: create layout
        lo_byday_2 = new VerticalLayout();
        lo_byday_2.setImmediate(false);
        lo_byday_2.setWidth("-1px");
        lo_byday_2.setHeight("-1px");
        lo_byday_2.setMargin(false);

        // byday_tu
        byday_tu = new CheckBox();
        byday_tu.setCaption("Di");
        byday_tu.setImmediate(false);
        byday_tu.setWidth("-1px");
        byday_tu.setHeight("-1px");
        lo_byday_2.addComponent(byday_tu);

        // byday_tu_int
        byday_tu_int = new IntStepper();
        byday_tu_int.setImmediate(false);
        byday_tu_int.setWidth("70px");
        byday_tu_int.setHeight("-1px");
        lo_byday_2.addComponent(byday_tu_int);

        return lo_byday_2;
    }

    @AutoGenerated
    private VerticalLayout buildLo_byday_3() {
        // common part: create layout
        lo_byday_3 = new VerticalLayout();
        lo_byday_3.setImmediate(false);
        lo_byday_3.setWidth("-1px");
        lo_byday_3.setHeight("-1px");
        lo_byday_3.setMargin(false);

        // byday_we
        byday_we = new CheckBox();
        byday_we.setCaption("Mi");
        byday_we.setImmediate(false);
        byday_we.setWidth("-1px");
        byday_we.setHeight("-1px");
        lo_byday_3.addComponent(byday_we);

        // byday_we_int
        byday_we_int = new IntStepper();
        byday_we_int.setImmediate(false);
        byday_we_int.setWidth("70px");
        byday_we_int.setHeight("-1px");
        lo_byday_3.addComponent(byday_we_int);

        return lo_byday_3;
    }

    @AutoGenerated
    private VerticalLayout buildLo_byday_4() {
        // common part: create layout
        lo_byday_4 = new VerticalLayout();
        lo_byday_4.setImmediate(false);
        lo_byday_4.setWidth("-1px");
        lo_byday_4.setHeight("-1px");
        lo_byday_4.setMargin(false);

        // byday_th
        byday_th = new CheckBox();
        byday_th.setCaption("Do");
        byday_th.setImmediate(false);
        byday_th.setWidth("-1px");
        byday_th.setHeight("-1px");
        lo_byday_4.addComponent(byday_th);

        // byday_th_int
        byday_th_int = new IntStepper();
        byday_th_int.setImmediate(false);
        byday_th_int.setWidth("70px");
        byday_th_int.setHeight("-1px");
        lo_byday_4.addComponent(byday_th_int);

        return lo_byday_4;
    }

    @AutoGenerated
    private VerticalLayout buildLo_byday_5() {
        // common part: create layout
        lo_byday_5 = new VerticalLayout();
        lo_byday_5.setImmediate(false);
        lo_byday_5.setWidth("-1px");
        lo_byday_5.setHeight("-1px");
        lo_byday_5.setMargin(false);

        // byday_fr
        byday_fr = new CheckBox();
        byday_fr.setCaption("Fr");
        byday_fr.setImmediate(false);
        byday_fr.setWidth("-1px");
        byday_fr.setHeight("-1px");
        lo_byday_5.addComponent(byday_fr);

        // byday_fr_int
        byday_fr_int = new IntStepper();
        byday_fr_int.setImmediate(false);
        byday_fr_int.setWidth("70px");
        byday_fr_int.setHeight("-1px");
        lo_byday_5.addComponent(byday_fr_int);

        return lo_byday_5;
    }

    @AutoGenerated
    private VerticalLayout buildLo_byday_6() {
        // common part: create layout
        lo_byday_6 = new VerticalLayout();
        lo_byday_6.setImmediate(false);
        lo_byday_6.setWidth("-1px");
        lo_byday_6.setHeight("-1px");
        lo_byday_6.setMargin(false);

        // byday_sa
        byday_sa = new CheckBox();
        byday_sa.setCaption("Sa");
        byday_sa.setImmediate(false);
        byday_sa.setWidth("-1px");
        byday_sa.setHeight("-1px");
        lo_byday_6.addComponent(byday_sa);

        // byday_sa_int
        byday_sa_int = new IntStepper();
        byday_sa_int.setImmediate(false);
        byday_sa_int.setWidth("70px");
        byday_sa_int.setHeight("-1px");
        lo_byday_6.addComponent(byday_sa_int);

        return lo_byday_6;
    }

    @AutoGenerated
    private VerticalLayout buildLo_byday_7() {
        // common part: create layout
        lo_byday_7 = new VerticalLayout();
        lo_byday_7.setImmediate(false);
        lo_byday_7.setWidth("-1px");
        lo_byday_7.setHeight("-1px");
        lo_byday_7.setMargin(false);

        // byday_su
        byday_su = new CheckBox();
        byday_su.setCaption("So");
        byday_su.setImmediate(false);
        byday_su.setWidth("-1px");
        byday_su.setHeight("-1px");
        lo_byday_7.addComponent(byday_su);

        // byday_su_int
        byday_su_int = new IntStepper();
        byday_su_int.setImmediate(false);
        byday_su_int.setWidth("70px");
        byday_su_int.setHeight("-1px");
        lo_byday_7.addComponent(byday_su_int);

        return lo_byday_7;
    }

    @AutoGenerated
    private HorizontalLayout buildLo_by() {
        // common part: create layout
        lo_by = new HorizontalLayout();
        lo_by.setImmediate(false);
        lo_by.setWidth("100.0%");
        lo_by.setHeight("100px");
        lo_by.setMargin(false);
        lo_by.setSpacing(true);

        // col_bymonthday
        col_bymonthday = new TwinColSelect();
        col_bymonthday.setCaption("Monatstage");
        col_bymonthday.setImmediate(false);
        col_bymonthday.setWidth("100.0%");
        col_bymonthday.setHeight("100.0%");
        lo_by.addComponent(col_bymonthday);
        lo_by.setExpandRatio(col_bymonthday, 1.0f);
        lo_by.setComponentAlignment(col_bymonthday, new Alignment(48));

        // col_byweekno
        col_byweekno = new TwinColSelect();
        col_byweekno.setCaption("Jahreswochen");
        col_byweekno.setImmediate(false);
        col_byweekno.setWidth("100.0%");
        col_byweekno.setHeight("100.0%");
        lo_by.addComponent(col_byweekno);
        lo_by.setExpandRatio(col_byweekno, 1.0f);
        lo_by.setComponentAlignment(col_byweekno, new Alignment(48));

        // col_bymonth
        col_bymonth = new TwinColSelect();
        col_bymonth.setCaption("Monate");
        col_bymonth.setImmediate(false);
        col_bymonth.setWidth("100.0%");
        col_bymonth.setHeight("100.0%");
        lo_by.addComponent(col_bymonth);
        lo_by.setExpandRatio(col_bymonth, 1.0f);
        lo_by.setComponentAlignment(col_bymonth, new Alignment(48));

        return lo_by;
    }

    @AutoGenerated
    private Panel buildPanel_1() {
        // common part: create layout
        panel_1 = new Panel();
        panel_1.setCaption("Terminvorschau");
        panel_1.setImmediate(false);
        panel_1.setWidth("500px");
        panel_1.setHeight("90.0%");

        // horizontalLayout_2
        horizontalLayout_2 = buildHorizontalLayout_2();
        panel_1.setContent(horizontalLayout_2);

        return panel_1;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_2() {
        // common part: create layout
        horizontalLayout_2 = new HorizontalLayout();
        horizontalLayout_2.setImmediate(false);
        horizontalLayout_2.setWidth("100.0%");
        horizontalLayout_2.setHeight("100.0%");
        horizontalLayout_2.setMargin(false);
        horizontalLayout_2.setSpacing(true);

        // tbl_preview
        tbl_preview = new FilterTable();
        tbl_preview.setImmediate(false);
        tbl_preview.setWidth("100.0%");
        tbl_preview.setHeight("100.0%");
        horizontalLayout_2.addComponent(tbl_preview);

        // verticalLayout_3
        verticalLayout_3 = buildVerticalLayout_3();
        horizontalLayout_2.addComponent(verticalLayout_3);

        return horizontalLayout_2;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_3() {
        // common part: create layout
        verticalLayout_3 = new VerticalLayout();
        verticalLayout_3.setImmediate(false);
        verticalLayout_3.setWidth("100.0%");
        verticalLayout_3.setHeight("100.0%");
        verticalLayout_3.setMargin(false);
        verticalLayout_3.setSpacing(true);

        // cb_cust_rrule
        cb_cust_rrule = new CheckBox();
        cb_cust_rrule.setCaption("Benutzerdefiniert");
        cb_cust_rrule.setImmediate(false);
        cb_cust_rrule.setWidth("-1px");
        cb_cust_rrule.setHeight("-1px");
        verticalLayout_3.addComponent(cb_cust_rrule);
        verticalLayout_3.setComponentAlignment(cb_cust_rrule, new Alignment(24));

        // txta_rrule
        txta_rrule = new TextArea();
        txta_rrule.setImmediate(false);
        txta_rrule.setWidth("100.0%");
        txta_rrule.setHeight("100.0%");
        verticalLayout_3.addComponent(txta_rrule);
        verticalLayout_3.setExpandRatio(txta_rrule, 1.0f);

        return verticalLayout_3;
    }

}
