package archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.forsteo.Form;

import java.util.HashMap;
import java.util.Map;

import archenoah.config.CMS_Config_Std;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.vaadin.Components.Combo.combo;
import archenoah.lib.vaadin.Components.Steppers.IntStepper;
import archenoah.lib.vaadin.Components.Validators.RegexValidator;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Tab_Menue_Item;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Window_Button;
import archenoah.lib.vaadin.Forms_Builder.Form_Bind;
import archenoah.lib.vaadin.Language.i18n.I18nCB;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.lib.vaadin.MenuBerechtigung.Rechteholen;
import archenoah.lib.vaadin.resources.Icons;
import archenoah.lib.vaadin.valchecker.val_checker4;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.classes.ProjectNurseCombos;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.forsteo.Form.classes.I18nFORStatusConverter;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.forsteo.classes.LngCareProgramConverter;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektzuweisung.Form.ProjektzuweisungDataView;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.tools.form_Berrechnen_Strecke;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Stammdaten.Krankenschwesternverwaltung.forms.form_nurse_insert_edit;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Stammdaten.Patientenverwaltung.Form.form_patient_insert_edit;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Stammdaten.Ärztverwaltung.Form.form_arzt_insert_edit;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Container.Filter;
import com.vaadin.data.Item;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.event.FieldEvents.BlurEvent;
import com.vaadin.event.FieldEvents.BlurListener;
import com.vaadin.event.FieldEvents.FocusEvent;
import com.vaadin.event.FieldEvents.FocusListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.shared.ui.datefield.Resolution;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.AbstractField;
import com.vaadin.ui.AbstractSelect;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.Window.CloseEvent;
import com.vaadin.ui.Window.CloseListener;

public class form_forsteo_insert_edit extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private AbsoluteLayout lilly_container;

	@AutoGenerated
	private Label lbl_lilly_arzt;

	@AutoGenerated
	private Label lbl_lilly_osteo;

	@AutoGenerated
	private Label lbl_lilly_kontra;

	@AutoGenerated
	private Label lbl_lilly_nicht;

	@AutoGenerated
	private Label lbl_lilly_ns;

	@AutoGenerated
	private Label lbl_lilly_andere;

	@AutoGenerated
	private Label lbl_lilly_pflege;

	@AutoGenerated
	private Label lbl_lilly_skept;

	@AutoGenerated
	private Label lbl_lilly_vllt;

	@AutoGenerated
	private Label lbl_lilly_ja;

	@AutoGenerated
	private Button btn_save;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_4;

	@AutoGenerated
	private TextArea txta_bemerkungen;

	@AutoGenerated
	private TextArea txta_beobachtungen;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;

	@AutoGenerated
	private TabSheet pan_BesD;

	@AutoGenerated
	private GridLayout grid_ue_report;

	@AutoGenerated
	private TextField casenumber;

	@AutoGenerated
	private ComboBox ueReportExist;

	@AutoGenerated
	private GridLayout grid_schul_inh;

	@AutoGenerated
	private CheckBox cb_10;

	@AutoGenerated
	private ComboBox cb_lilly;

	@AutoGenerated
	private CheckBox cb_9;

	@AutoGenerated
	private CheckBox cb_16;

	@AutoGenerated
	private CheckBox cb_17;

	@AutoGenerated
	private CheckBox cb_5;

	@AutoGenerated
	private CheckBox cb_6;

	@AutoGenerated
	private CheckBox cb_3;

	@AutoGenerated
	private CheckBox cb_8;

	@AutoGenerated
	private CheckBox cb_7;

	@AutoGenerated
	private GridLayout grid_pat_details;

	@AutoGenerated
	private ComboBox ueProductUsed;

	@AutoGenerated
	private CheckBox cb_nurse_concerns;

	@AutoGenerated
	private CheckBox cb_no_anomalies;

	@AutoGenerated
	private CheckBox cb_14;

	@AutoGenerated
	private CheckBox cb_15;

	@AutoGenerated
	private CheckBox cb_1;

	@AutoGenerated
	private Panel pan_abrechnungsdaten;

	@AutoGenerated
	private VerticalLayout verticalLayout_5;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_6;

	@AutoGenerated
	private Button btn_km_ber;

	@AutoGenerated
	private CheckBox cb_admin;

	@AutoGenerated
	private GridLayout gl_double;

	@AutoGenerated
	private VerticalLayout vl_cs;

	@AutoGenerated
	private TextField txt_Abrechnungs_Km;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_5;

	@AutoGenerated
	private NativeSelect ns_Abrechnung_Minuten;

	@AutoGenerated
	private NativeSelect ns_Abrechnung_Stunden;

	@AutoGenerated
	private VerticalLayout vl_nurse;

	@AutoGenerated
	private IntStepper int_anrufe;

	@AutoGenerated
	private TextField txt_Gesamte_Km;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_10;

	@AutoGenerated
	private NativeSelect ns_min;

	@AutoGenerated
	private NativeSelect ns_Stunden;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;

	@AutoGenerated
	private Panel pan_stammdaten;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_7;

	@AutoGenerated
	private VerticalLayout verticalLayout_7;

	@AutoGenerated
	private CheckBox cb_cancelled;

	@AutoGenerated
	private CheckBox cb_leadNurseOk;

	@AutoGenerated
	private ComboBox ns_status;

	@AutoGenerated
	private VerticalLayout verticalLayout_3;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_12;

	@AutoGenerated
	private CheckBox cb_arztConfirmed;

	@AutoGenerated
	private ComboBox cbx_arzt;

	@AutoGenerated
	private VerticalLayout verticalLayout_8;

	@AutoGenerated
	private Button btn_arzt_info;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_9;

	@AutoGenerated
	private ComboBox cb_nurse;

	@AutoGenerated
	private VerticalLayout verticalLayout_9;

	@AutoGenerated
	private Button btn_zuweisung;

	@AutoGenerated
	private VerticalLayout verticalLayout_6;

	@AutoGenerated
	private Button btn_nurse_info;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_8;

	@AutoGenerated
	private ComboBox cb_pat;

	@AutoGenerated
	private VerticalLayout verticalLayout_4;

	@AutoGenerated
	private Button btn_pat_info;

	@AutoGenerated
	private VerticalLayout verticalLayout_10;

	@AutoGenerated
	private Panel pan_dat;

	@AutoGenerated
	private VerticalLayout verticalLayout_2;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_11;

	@AutoGenerated
	private TextField txt_bis;

	@AutoGenerated
	private TextField txt_von;

	@AutoGenerated
	private PopupDateField pop_date;

	@AutoGenerated
	private PopupDateField pop_term;

	

	

	

	

	

	

	

	

	

	

	

	

	

    

    

    

    

    

    

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */

    /**************** --> Allgemein <--- ********************/
	private static org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(form_forsteo_insert_edit.class);
    // Sprache
    // Allgemein
    private String Exportname;
    // Datenbank
    private Map<Object, String> DBMap;
    private Map<Object, String> ValidateMap;
    private DBClass db;
    private Form_Bind fb;
    private String Form_ID = "";
    // Berrechtigung
    private int ACC_ID;
    private int Lesen;
    private int Schreiben;
    private int Erstellen;
    private int Edit;
    private int Löschen;

    private MenuItem Temp_Menü = null;

    private Button Temp_Btn = null;
    /******************************************************/
    /**************** --> Tabsheetvars <--- *****************/
    private TabSheet tab = null;

    /******************************************************/
    /**************** --> Windowvars <--- *******************/
    private Window win = null;
    private boolean nurse = false;
    private boolean leadNurse = false;
    /******************************************************/
    /******************* --> Custom <--- ********************/
    /******************************************************/

    /************ ----->Einstellungen<-- ********************/
//    private final String LNG_FRM_ID = "24";
    private final String BER_MEN_ID = "37"; // from dataview
    private final String Windows_Height = "700px";
    private final String Windows_Width = "1000px";
    /******************************************************/

    private I18nManager i18n;

	private Item dataSetItem;
    
    private final static class caption extends I18nCB {
		static final I18nCB yes = set();
		static final I18nCB no = set();
		static final I18nCB unknown = set();
		
	}

    public form_forsteo_insert_edit(MenuItem Arg_Menü, String Arg_Form_ID) {
        Temp_Menü = Arg_Menü;
        Form_ID = Arg_Form_ID;

        // TODO add user code here
    }

    public form_forsteo_insert_edit(Button Arg_btn, String Arg_Form_ID) {

        Temp_Btn = Arg_btn;
        Form_ID = Arg_Form_ID;

        // TODO add user code here
    }

    /***************************** ---> Feste Funtionen<--- **************************************/

    /********* INIT-Window ************/
    public void Init_Class_Window() {
        if (Windows_Height.equals("") == true || Windows_Width.equals("") == true) {
            System.out.println("Form Einstellung Fehlt: !!!");
            return;
        }

        Standard_Init();

        String fid = Form_ID;
        if (fid != "") {
            fid = " - #" + fid;
        }

        if (Temp_Menü != null) {
            String Recourcename = Temp_Menü.getIcon().toString();
            Recourcename = Recourcename.substring(0, Recourcename.length() - 12) + "white-16.png";

            Exportname = Temp_Menü.getText();
            Build_Window_Button bwb = new Build_Window_Button(Temp_Menü.getText() + fid, mainLayout, Windows_Height, Windows_Width,
                    new ThemeResource(Recourcename));
            win = bwb.ReturnWindow();
        }
        if (Temp_Btn != null) {
            Exportname = Temp_Btn.getCaption();
            Build_Window_Button bwb = new Build_Window_Button(Temp_Btn.getCaption() + fid, mainLayout, Windows_Height, Windows_Width,
                    Temp_Btn.getIcon());
            win = bwb.ReturnWindow();
        }
        
    }
    
    public Window getWindow(){
    	return win;
    }
    
    /********* INIT-Tray ************/
    public void Init_Class_Tab(TabSheet Arg_tab) {

        Standard_Init();
        tab = Arg_tab;
        if (Temp_Menü != null) {
            Exportname = Temp_Menü.getText();
            Build_Tab_Menue_Item bt = new Build_Tab_Menue_Item(Arg_tab, Temp_Menü.getText(), mainLayout, Temp_Menü.getIcon());
        }
        if (Temp_Btn != null) {
            Exportname = Temp_Btn.getCaption();
            Build_Tab_Menue_Item bt = new Build_Tab_Menue_Item(Arg_tab, Temp_Btn.getCaption(), mainLayout, Temp_Btn.getIcon());
        }

    }

    /********* Init-Standard ************/
    private void Standard_Init() {
        buildMainLayout();
        i18n = new I18nManager(this);
        
        fb = new Form_Bind();

        Set_DB_Map();

        Set_Validierer();
        Set_Validate_Map();
        Prüfung_Ist_Grp_Krankenschwestern();

        /********** Custom Fill Function *******************/
        Popup_nativeselect_minuten();
        Popup_nativeselect_Stunden();
        Popup_nativeselect_Anzahl();
        
        cb_leadNurseOk.setEnabled(false);

        fillCareProgram();
        fillStatus();
        
        fillUeReport();
        
        if (nurse == true && leadNurse == false) {
            //Fill_ns_P_Status_Nurse();
            // ^ führt zu NPE bei status 3 + 4
            cb_nurse.setValue(Get_ID_Nurse());
            cb_nurse.setReadOnly(true);
            txt_Abrechnungs_Km.setReadOnly(true);
            ns_Abrechnung_Stunden.setReadOnly(true);
            ns_Abrechnung_Minuten.setReadOnly(true);

            vl_cs.setVisible(false);
            cb_leadNurseOk.setVisible(false);

            btn_zuweisung.setVisible(false);
            Fill_cb_P_Patient_nurse();

        } else {
            //Fill_ns_P_Status();
            // ^ siehe oben
//            txt_Gesamte_Km.setReadOnly(true);
//            ns_min.setReadOnly(true);
//            ns_Stunden.setReadOnly(true);
            
            Fill_cb_P_Patient();
        }
        
        if(leadNurse == true){
            cb_leadNurseOk.setEnabled(true);
        }
        
        Combo_Popup_Nurse();
        fillArzt();
        Set_Status_Select_OnChange();

        /***************************************************/

        if (Form_ID != "") {

            Forms_Fill();
            fillArzt();
            
            if (nurse == true && !leadNurse) {
                
                int status = (int) ns_status.getValue();
                
                if (status == 1) {
                    filterStatus();
                    ns_status.setValue(status);
                }
                
                //storniert box deaktivieren
                cb_cancelled.setEnabled(false);
                
                
                // Falls freigebeben oder später Nurse nicht mehr speichern lassen
                if (status >= 2) {
                    Set_Berrechtigung_Custom(1, 0, 0, 0);
                }
               
            }

        } else {
            cb_admin.setValue(true);
        }
        filterUeReport();
        Combo_Popup_Nurse(); // erneut aufrufen um entsprechend zu filtern
        fillArzt(); // ditto
        event();
        /********************** Components Setup *******************************/
        
        // migrated from database
        btn_km_ber.setIcon(Icons.White.berechnen_16);
        btn_arzt_info.setIcon(Icons.White.info_16);
        btn_nurse_info.setIcon(Icons.White.info_16);
        btn_save.setIcon(Icons.White.save_16);
        btn_pat_info.setIcon(Icons.White.info_16);

        btn_km_ber.setStyleName("button-image-only");
        btn_arzt_info.setStyleName("button-image-only");
        btn_nurse_info.setStyleName("button-image-only");
        cb_nurse.setStyleName("input-align");
        cb_pat.setStyleName("input-align");
        btn_pat_info.setStyleName("button-image-only");
        ns_status.setStyleName("input-align");

        cb_nurse.setRequired(true);
        cb_pat.setRequired(true);
        ns_status.setRequired(true);


        new RegexValidator(txt_Gesamte_Km, "^\\d*$", null, null, false);
        new RegexValidator(txt_Abrechnungs_Km, "^\\d*$", null, null, false);
        new RegexValidator(txt_bis, "(([01]?[0-9]|2[0-3]):?[0-5][0-9])?", null, null, false);
        new RegexValidator(txt_von, "(([01]?[0-9]|2[0-3]):?[0-5][0-9])?", null, null, false);
        // migration end
        
        pop_date.setResolution(Resolution.DAY);
        pop_term.setResolution(Resolution.DAY);
        cb_pat.setImmediate(true);
        btn_zuweisung.setEnabled(cb_pat.getValue() != null ? true : false);
        cbx_arzt.setFilteringMode(FilteringMode.CONTAINS);

        cb_nurse.setNullSelectionAllowed(false);
        cb_lilly.setNullSelectionAllowed(false);
        /*********************************************************************/
        
        toggleRequiredFields();
        
        // win.addAction(new ClickShortcut(btn_save, KeyCode.ENTER));
        // hide admin
        cb_admin.setVisible(false);
        cb_1.setVisible(false); //pat ist mobil
        
        i18n.refresh();
    }

    private void toggleRequiredFields() {
        boolean status = (ns_status.getValue() != null && (Integer) ns_status.getValue() >= 2);
        ueReportExist.setRequired(status);
        ueProductUsed.setRequired(status);
    }
    
    /*********************************/

    /*************************** Events *******************************/

    private void openPat(){
        if (cb_pat.getValue() == null) {
            I18nManager.global(I18nGlobalNotifiers.no_entry_selected);

            return;
        }

        form_patient_insert_edit pie = new form_patient_insert_edit(btn_pat_info, "" + cb_pat.getValue());
        if (nurse == true) {
            pie.Set_Berrechtigung_Custom(1, 1, 1, 1);
        } else {
            pie.Set_Berrechtigung_Custom(1, 1, 1, 1);
        }
        Window patWindow = pie.Init_Class_Window();
        patWindow.addCloseListener(new CloseListener() {
            
            @Override
            public void windowClose(CloseEvent e) {
                
                refreshOnPatientWindowClose();
                
            }
        });
    }
    
    @SuppressWarnings("serial")
    private void event() {
        

        
        cb_pat.addValueChangeListener(new Property.ValueChangeListener() {

            @Override
            public void valueChange(ValueChangeEvent event) {
                btn_zuweisung.setEnabled(cb_pat.getValue() != null ? true : false);
                Combo_Popup_Nurse();
                selectArzt();
            }
        });

        ns_status.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                toggleRequiredFields();
                
            }
        });
        
        btn_save.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {
                // TODO Automatisch generierter Methodenstub

                if (Validate_Test() == false) {
                    I18nManager.global(I18nGlobalNotifiers.fields_empty);
                    return;
                }

                if (Form_ID.equals("") == true) {
                    Forms_Insert();

                } else {
                    Forms_Update();
                }

                UI.getCurrent().getUI().removeWindow(win);
            }

        });

        btn_km_ber.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {
                // TODO Automatisch generierter Methodenstub

                form_Berrechnen_Strecke fbs = new form_Berrechnen_Strecke(event.getButton());

                if (nurse == true) {
                    fbs.fieldDistance = txt_Gesamte_Km;
                    fbs.fieldMin = ns_min;
                    fbs.fieldHours = ns_Stunden;
                } else {
                    fbs.fieldDistance = txt_Abrechnungs_Km;
                    fbs.fieldMin = ns_Abrechnung_Minuten;
                    fbs.fieldHours = ns_Abrechnung_Stunden;
                }

                if (cb_nurse.getValue() != null) {
                    fbs.Init_Class_Window((Integer) cb_nurse.getValue());
                } else {
                    fbs.Init_Class_Window();
                }

                if (cb_pat.getValue() != null) {
                    fbs.Set_nach((int) cb_pat.getValue());
                }

            }
        });
        
        btn_pat_info.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {
                openPat();
            }
        });
        
        btn_nurse_info.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {
                // TODO Automatisch generierter Methodenstub
                if (cb_nurse.getValue() == null) {
                    I18nManager.global(I18nGlobalNotifiers.no_entry_selected);

                    return;
                }

                form_nurse_insert_edit pie = new form_nurse_insert_edit(event.getButton(), "" + cb_nurse.getValue());
                pie.Init_Class_Window();
                pie.Set_Berrechtigung_Custom(1, 0, 0, 0);
            }
        });

        btn_arzt_info.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {
                // TODO Automatisch generierter Methodenstub
                if (cbx_arzt.getValue() == null) {
                    I18nManager.global(I18nGlobalNotifiers.no_entry_selected);

                    return;
                }

                form_arzt_insert_edit pie = new form_arzt_insert_edit(event.getButton(), "" + cbx_arzt.getValue());
                pie.Init_Class_Window();
                pie.Set_Berrechtigung_Custom(1, 1, 1, 0);

            }
        });

        btn_zuweisung.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {
            	ProjektzuweisungDataView pz = new ProjektzuweisungDataView(event.getButton());
                pz.setFilteredInit("1", Integer.toString((int) cb_pat.getValue()));
                
                pz.setPermissionsFromDatabase();
                pz.init();
                Window popupDV = pz.getWindow();
                
                popupDV.addCloseListener(new CloseListener() {

                    @Override
                    public void windowClose(CloseEvent e) {
                        Combo_Popup_Nurse();
                    }
                });
            }
        });

        cbx_arzt.addFocusListener(new FocusListener() {

            @Override
            public void focus(FocusEvent event) {

                fillArzt();

            }
        });

    }

    /******************************************************************/
    
    private void refreshOnPatientWindowClose(){
        
        Object patientId = cb_pat.getValue(); 
        
        if (nurse == true) {
            Fill_cb_P_Patient_nurse();
        } else {
            Fill_cb_P_Patient();
        }
        
        cb_pat.setValue(patientId);

    }
    
    private void selectArzt() {
        fillArzt();
        try {
            cbx_arzt.select(Integer.parseInt(Get_A_ID()));
        } catch (Exception e) {
            cbx_arzt.removeAllItems();
        }

    }


    /************************ --> Berrechtigung <-- **************************/

    public void Set_Berrechtigung_Database() {
        if (BER_MEN_ID == "") {
            System.out.println("Form Einstellung Fehlt: !!!");
            return;
        }

        ACC_ID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        Rechteholen r = new Rechteholen(ACC_ID + "");
        String[][] Asan = r.Datenholen();

        for (int i = 0; i < Asan.length; i++) {
            if (Asan[i][0].equals(BER_MEN_ID) == true) {

                Lesen = Integer.valueOf(Asan[i][3]);

                Schreiben = Integer.valueOf(Asan[i][4]);
                Erstellen = Integer.valueOf(Asan[i][6]);
                Löschen = Integer.valueOf(Asan[i][5]);
            }
        }
    }

    public void Set_Berrechtigung_Custom(int Arg_Lesen, int Arg_Erstellen, int Arg_Bearbeiten, int Arg_Loeschen) {
        Lesen = Arg_Lesen;
        Schreiben = Arg_Erstellen;
        Erstellen = Arg_Erstellen;
        Edit = Arg_Bearbeiten;
        Löschen = Arg_Loeschen;

        if (Erstellen == 0 | Edit == 0) {
            btn_save.setEnabled(false);

        }
    }
    
    public void setLeadNurseModeEnabled(Boolean enabled){
        leadNurse = enabled;
    }
    
    /**********************************************************************/

    /************************** Einstellen **************************************/

    /******************** Database *****************/
    private void Set_DB_Map() {
        DBMap = new HashMap<>();
        DBMap.put(pop_date, "cust_schulung_liste_forsteopen:SLF_DATE");
        DBMap.put(pop_term, "cust_schulung_liste_forsteopen:SLF_TERM");

        DBMap.put(txt_von, "cust_schulung_liste_forsteopen:SLF_VON");
        DBMap.put(txt_bis, "cust_schulung_liste_forsteopen:SLF_BIS");

        DBMap.put(cb_pat, "cust_schulung_liste_forsteopen:SLF_P_ID");
        DBMap.put(cbx_arzt, "cust_schulung_liste_forsteopen:SLF_ARZT_ID");
        DBMap.put(cb_arztConfirmed, "cust_schulung_liste_forsteopen:SLF_ARZT_CONFIRMED");

        DBMap.put(cb_nurse, "cust_schulung_liste_forsteopen:SLF_K_ID");
        DBMap.put(ns_status, "cust_schulung_liste_forsteopen:SLF_STATUS");
        DBMap.put(cb_leadNurseOk, "cust_schulung_liste_forsteopen:SLF_LEAD_NURSE_OK");

        DBMap.put(ns_Stunden, "cust_schulung_liste_forsteopen:SLF_FAHRTZEIT_STD_N");
        DBMap.put(ns_min, "cust_schulung_liste_forsteopen:SLF_FAHRTZEIT_MIN_N");
        DBMap.put(int_anrufe, "cust_schulung_liste_forsteopen:SLF_ANRUFE");
        DBMap.put(ns_Abrechnung_Minuten, "cust_schulung_liste_forsteopen:SLF_FAHRTZEIT_MIN");
        DBMap.put(ns_Abrechnung_Stunden, "cust_schulung_liste_forsteopen:SLF_FAHRTZEIT_STD");
        DBMap.put(txt_Abrechnungs_Km, "cust_schulung_liste_forsteopen:SLF_GES_KM");
        DBMap.put(txt_Gesamte_Km, "cust_schulung_liste_forsteopen:SLF_GES_KM_N");
        DBMap.put(cb_admin, "cust_schulung_liste_forsteopen:SLF_ADMINPAUSCHALE");

//        DBMap.put(cb_1, "cust_schulung_liste_forsteopen:SLF_VERM_1");
//        DBMap.put(cb_2, "cust_schulung_liste_forsteopen:SLF_VERM_2");
        DBMap.put(cb_3, "cust_schulung_liste_forsteopen:SLF_VERM_3");
        // DBMap.put(cb_4,"cust_schulung_liste_forsteopen:SLF_VERM_4");
        DBMap.put(cb_lilly, "cust_schulung_liste_forsteopen:SLF_VERM_4");
        DBMap.put(cb_5, "cust_schulung_liste_forsteopen:SLF_VERM_5");
        DBMap.put(cb_6, "cust_schulung_liste_forsteopen:SLF_VERM_6");
        DBMap.put(cb_7, "cust_schulung_liste_forsteopen:SLF_VERM_7");
        DBMap.put(cb_8, "cust_schulung_liste_forsteopen:SLF_VERM_8");
        DBMap.put(cb_9, "cust_schulung_liste_forsteopen:SLF_VERM_9");
        DBMap.put(cb_10, "cust_schulung_liste_forsteopen:SLF_VERM_10");

//        DBMap.put(cb_11, "cust_schulung_liste_forsteopen:SLF_VERM_11");
//        DBMap.put(cb_12, "cust_schulung_liste_forsteopen:SLF_VERM_12");
//        DBMap.put(cb_13, "cust_schulung_liste_forsteopen:SLF_VERM_13");
        DBMap.put(cb_14, "cust_schulung_liste_forsteopen:SLF_VERM_14");
        DBMap.put(cb_15, "cust_schulung_liste_forsteopen:SLF_VERM_15");
        DBMap.put(cb_16, "cust_schulung_liste_forsteopen:SLF_VERM_16");
        DBMap.put(cb_17, "cust_schulung_liste_forsteopen:SLF_VERM_17");
//        DBMap.put(cb_18, "cust_schulung_liste_forsteopen:SLF_VERM_18");
//        DBMap.put(cb_19, "cust_schulung_liste_forsteopen:SLF_VERM_19");
//        DBMap.put(cb_20, "cust_schulung_liste_forsteopen:SLF_VERM_20");
//        DBMap.put(cb_21, "cust_schulung_liste_forsteopen:SLF_VERM_21");
//        DBMap.put(cb_22, "cust_schulung_liste_forsteopen:SLF_VERM_22");
//        DBMap.put(cb_23, "cust_schulung_liste_forsteopen:SLF_VERM_23");
//        DBMap.put(cb_24, "cust_schulung_liste_forsteopen:SLF_VERM_24");
//        DBMap.put(cb_25, "cust_schulung_liste_forsteopen:SLF_VERM_25");

        DBMap.put(txta_bemerkungen, "cust_schulung_liste_forsteopen:SLF_BESONDERHEIT");
        DBMap.put(txta_beobachtungen, "cust_schulung_liste_forsteopen:SLF_BEOBACHTUNGEN");

        DBMap.put(cb_cancelled, "cust_schulung_liste_forsteopen:SLF_CANCELLED");
        
        // DBMap.put(txt_username,"cms_auth_stammdaten_user:AUL_USERNAME");
        
        DBMap.put(cb_no_anomalies, "cust_schulung_liste_forsteopen:SLF_NO_ANOMALIES");
        DBMap.put(cb_nurse_concerns, "cust_schulung_liste_forsteopen:SLF_NURSE_CONCERNS");
        
        DBMap.put(ueProductUsed, "cust_schulung_liste_forsteopen:SLF_PRODUCT_USED");
        DBMap.put(ueReportExist, "cust_schulung_liste_forsteopen:SLF_UE_REPORT_EXIST");
        DBMap.put(casenumber, "cust_schulung_liste_forsteopen:SLF_CASENUMBER");

    }

    private void Forms_Fill() {
        db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();

        /******************************** Table ****************************************/
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_schulung_liste_forsteopen");
        /******************************************************************************/
        /******************************** Filter ****************************************/
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_schulung_liste_forsteopen", "SLF_ID", "=", Form_ID, "");
        /******************************************************************************/

        // db.DB_Data_Get.Set_Type("SLF_VON_UHRZEIT", Date.class);
        // db.DB_Data_Get.Set_Type("SLF_BIS_UHRZEIT", Date.class);

//        db.DB_Data_Get.Set_Type("SLF_UE_REPORT_EXIST", Integer.class);
        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();
        fb = new Form_Bind();

        if(con.size() > 0){
        	
        	fb.Get_and_Fill(con, DBMap);
        	
        	dataSetItem = con.getItem(con.getItemIds().iterator().next());
        }
    }

    private void Forms_Insert() {
        DBClass dba = new DBClass();
        fb = new Form_Bind();

        fb.Insert(dba, DBMap);
        // System.out.println(Get_A_ID());
        // dba.DB_Data_Insert.DB_Daten.DB_Data("cust_schulung_liste_forsteopen",
        // "SLF_ARZT_ID", Get_A_ID());

        /******************************** Table ****************************************/
        dba.DB_Data_Insert.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_schulung_liste_forsteopen");
        /******************************************************************************/
        // dba.DB_Data_Insert.DB_DEBUG_SQL_STRING();
        dba.DB_Data_Insert.DB_Insert();
    }

    private void Forms_Update() {
        db = new DBClass();
        fb = new Form_Bind();
        fb.Update(db, DBMap);

        /******************************** Table ****************************************/
        db.DB_Data_Update.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_schulung_liste_forsteopen");
        /******************************************************************************/
        /******************************** Filter ****************************************/
        db.DB_Data_Update.DB_Filter.DB_WHERE_Allgemein("cust_schulung_liste_forsteopen", "SLF_ID", "=", Form_ID, "");
        /******************************************************************************/
        db.DB_Data_Update.DB_Update();

    }

    private String Get_A_ID() {
        String P_ID = cb_pat.getValue().toString();
        db = new DBClass();
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_verk_arzt_patient");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_arzt_patient", "VAP_P_ID", "=", P_ID, "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_arzt_patient", "VAP_B_ID", "=", "2", "");

        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();

        int A_ID = 0;
        A_ID = (int) con.getItem(con.getItemIds().iterator().next()).getItemProperty("VAP_A_ID").getValue();

        return A_ID + "";

    }

    /***********************************************/

    private void Popup_nativeselect_Stunden() {
        int i = 13;

        for (int a = 0; a < i; a++) {
            ns_Stunden.addItem(a);
            ns_Abrechnung_Stunden.addItem(a);
        }

    }

    private void Popup_nativeselect_minuten() {
        int i = 60;

        for (int a = 0; a < i; a++) {
            ns_min.addItem(a);
            ns_Abrechnung_Minuten.addItem(a);
        }

    }

    private void Combo_Popup_Nurse() {
        Object nv = null;

        CMS_Config_Std std = CMS_Config_Std.getInstance();

        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("KSK_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(KSK_TITEL,' ',KSA_NAME,' ',AUL_NAME,' ',AUL_VORNAME)",
                "Krankenschwesternname");

        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_stammdaten_user", "INNER JOIN",
                "cust_krankenschwester_stammdaten_anrede", "AUL_ANREDE_ID", "KSA_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_krankenschwester_stammdaten_ks", "INNER JOIN",
                "cms_auth_stammdaten_user", "KSK_U_ID", "AUL_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_verk_haupt", "INNER JOIN", "cust_krankenschwester_stammdaten_ks",
                "VH_NURSE_ID", "KSK_ID");

        if (cb_pat.getValue() != null) {
            nv = cb_nurse.getValue();
            db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_haupt", "VH_PATIENT_ID", "=", Integer.toString((int) cb_pat.getValue()),
                    "");
            if (!nurse) {
                cb_nurse.removeAllItems(); // Property Readonly Exception
            }
        }
        // db.DB_Data_Get.DB_DEBUG_SQL_STRING();
        try {
            combo nc = new combo(db.DB_Data_Get.DB_SEND_AND_GET(), cb_nurse, "KSK_ID", "Krankenschwesternname");

            if (cb_pat.getValue() != null && nv != null) {
                
                //fix for deleted nurses
                if(!cb_nurse.containsId(nv)){
                    new combo(new ProjectNurseCombos(1).getNurseComboSingle(Integer.parseInt(nv.toString())), cb_nurse, "KSK_ID", "Krankenschwesternname");
                    cb_nurse.setEnabled(false);
                    cb_nurse.setStyleName("nogrey");
                }
                
                cb_nurse.select(nv);
            }

        } catch (Exception e) {
            cb_nurse.removeAllItems();
            return;
        }

        db.DB_Data_Get.connclose();

        cb_nurse.setFilteringMode(cb_nurse.FILTERINGMODE_CONTAINS);
    }

    private void fillArzt() {

        Object av = null;

        CMS_Config_Std std = CMS_Config_Std.getInstance();
        DBClass db = new DBClass();

        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("ASA_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(ASA_TITEL,' ',ASAN_NAME,' ',AUL_NAME,' ',AUL_VORNAME)",
                "Arztname");

        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_stammdaten_user", "INNER JOIN", "cust_arzt_stammdaten_anrede",
                "AUL_ANREDE_ID", "ASAN_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_arzt_stammdaten_arzt", "INNER JOIN", "cms_auth_stammdaten_user",
                "ASA_U_ID", "AUL_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_verk_arzt_patient", "INNER JOIN", "cust_arzt_stammdaten_arzt",
                "VAP_A_ID", "ASA_ID");

        if (cb_pat.getValue() != null) {

            av = cbx_arzt.getValue();
            db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_arzt_patient", "VAP_P_ID", "=",
                    Integer.toString((int) cb_pat.getValue()), "AND");
        }

        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_arzt_patient", "VAP_B_ID", "=", "1", "");

        //db.DB_Data_Get.DB_DEBUG_SQL_STRING();

        try {
            cbx_arzt.removeAllItems();
            combo nc = new combo(db.DB_Data_Get.DB_SEND_AND_GET(), cbx_arzt, "ASA_ID", "Arztname");

            if (cb_pat.getValue() != null && av != null) {
                cbx_arzt.select(av);
            }

        } catch (Exception e) {
            cbx_arzt.removeAllItems();
            return;
        }
    }

    private void Popup_nativeselect_Anzahl() {
//        int i = 21;
//
//        for (int a = 0; a < i; a++) {
//            ns_anrufe.addItem(a);
//        }
        int_anrufe.setMinValue(0);
    }


    private void fillCareProgram(){
    	
    	new LngCareProgramConverter().attachDatasource(cb_lilly);
    	
//        Container con = careConverter.getContainer();
//        
//        for (Object cid : con.getItemIds()) {
//        	
//        	Integer value = (Integer) con.getContainerProperty(cid, "SLFCP_ID").getValue();
//        	String text = (String) con.getContainerProperty(cid, "SLFCP_TOKEN").getValue();
//
//        	cb_lilly.addItem(value);
//        	cb_lilly.setItemCaption(value, careConverter.getLngText(text));
//    		
//		}
    	
    }
    
    
    private void fillUeReport(){
    	
    	fillUeSelection(ueProductUsed);
    	fillUeSelection(ueReportExist);
//    	System.out.println(ueReportExist.getContainerDataSource());
//    	log.warn("Container: {}", ueReportExist.getContainerDataSource());

    }
    
    private void fillUeSelection(AbstractSelect select){

    	select.addItem(-1);
    	select.addItem(0);
    	select.addItem(1);

    	select.setItemCaption(-1, i18n.get(caption.unknown));
    	select.setItemCaption(0, i18n.get(caption.no));
    	select.setItemCaption(1, i18n.get(caption.yes));
    	
    }

    private void filterUeReport(){
    	IndexedContainer con = (IndexedContainer) ueReportExist.getContainerDataSource();
    	con.addContainerFilter(new Filter() {
			
			@Override
			public boolean passesFilter(Object itemId, Item item) throws UnsupportedOperationException {
				
				int id = (int) itemId;
				
				if (id == -1 && (
						dataSetItem == null
					    || dataSetItem.getItemProperty("SLF_UE_REPORT_EXIST").getValue() == null
						|| (int) dataSetItem.getItemProperty("SLF_UE_REPORT_EXIST").getValue() != -1
						)) {

					return false;	
				}else{
					return true;
				}
				
			}
			
			@Override
			public boolean appliesToProperty(Object propertyId) {
				return false;
			}
		});
    }
    
    /*********************** -->Validierung<-- ********************/
    private void Set_Validate_Map() {
        ValidateMap = new HashMap<>();
        ValidateMap.put(pop_date, "pop_date");
        ValidateMap.put(cb_pat, "cb_pat");
        ValidateMap.put(cb_nurse, "cb_nurse");
        ValidateMap.put(ns_status, "ns_status");
        ValidateMap.put(ns_Stunden, "ns_Stunden");
        ValidateMap.put(ns_min, "ns_min");
        ValidateMap.put(int_anrufe, "int_anrufe");
        ValidateMap.put(txt_Gesamte_Km, "txt_Gesamte_Km");

        ValidateMap.put(txt_von, "txt_von");
        ValidateMap.put(txt_bis, "txt_bis");
        
        ValidateMap.put(cb_lilly, "cb_lilly");
        
        ValidateMap.put(ueProductUsed, "ueProductUsed");
        ValidateMap.put(ueReportExist, "ueReportExist");
        ValidateMap.put(casenumber, "casenumber");

        // ValidateMap.put(txt_username,"");

    }

    private void Set_Validierer() {

        // psw_pass_1.addValidator(new
        // Custom_Benutzerform_psw_ändern(psw_pass_1, psw_pass_2));

        /**************/
        /* Manuelles prüfen */

        BlurListener blur = new BlurListener() {
            @Override
            public void blur(BlurEvent event) {
                String hr = "0";
                String min = "0";
                if (((AbstractField<String>) event.getComponent()).isValid()
                        && ((AbstractField<String>) event.getComponent()).getValue() != null
                        && ((AbstractField<String>) event.getComponent()).getValue().length() > 0) {

                    AbstractField<String> field = (AbstractField<String>) event.getComponent();
                    String value = field.getValue();
                    Integer lid = value.lastIndexOf(":"); // -1 (0958) oder 1
                    // (9:58) oder 2
                    // (09:58)

                    if (lid == -1) {

                        Integer splitat = Math.max(0, value.length() - 2);

                        hr = value.substring(0, splitat);
                        min = value.substring(splitat);

                        field.setValue(hr + ":" + min);
                    } else {

                        String[] time = value.split(":");
                        hr = time[0];
                        min = time[1];

                    }

                }
            }
        };

        txt_von.setImmediate(true);
        txt_von.addBlurListener(blur);

        txt_bis.setImmediate(true);
        txt_bis.addBlurListener(blur);

    }

    private boolean Validate_Test() {
        val_checker4 val = new val_checker4(ValidateMap);
        if (val.Is_Valid() == false) {
            return false;
        } else {
            return true;
        }

    }

    /***************************** -> Fill ns und cb <- ****************************************/
    private void fillStatus() {
        
        new I18nFORStatusConverter().attachDatasource(ns_status);
        ns_status.setNullSelectionAllowed(false);

    }
    
    private void filterStatus() {
        
        IndexedContainer con = (IndexedContainer) ns_status.getContainerDataSource();
        con.addContainerFilter(new Filter() {

            @Override
            public boolean passesFilter(Object itemId, Item item) throws UnsupportedOperationException {
                return (Integer) itemId <= 2;
            }

            @Override
            public boolean appliesToProperty(Object propertyId) {
                return false;
            }
        });
    }
    
//    private void Fill_ns_P_Status_Nurse() {
//        CMS_Config_Std std = CMS_Config_Std.getInstance();
//        DBClass db = new DBClass();
//        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("SS_PROZESS");
//        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("SS_NAME");
//        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_schulung_status");
//        
//        
//        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_schulung_status", "SS_PROJEKT", "=", "1", "AND");
//        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_schulung_status", "SS_PROZESS", "<=", "2", "");
//        
//
//        try {
//            nativecombo nc = new nativecombo(db.DB_Data_Get.DB_SEND_AND_GET(), ns_status, "SS_PROZESS", "SS_NAME");
//        } catch (Exception e) {
//            ns_status.removeAllItems();
//        }
//
//        db.DB_Data_Get.connclose();
//    }
//
//    private void Fill_ns_P_Status() {
//        CMS_Config_Std std = CMS_Config_Std.getInstance();
//        DBClass db = new DBClass();
//        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("SS_PROZESS");
//        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("SS_NAME");
//        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_schulung_status");
//        
//        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_schulung_status", "SS_PROJEKT", "=", "1", "");
//
//        try {
//            nativecombo nc = new nativecombo(db.DB_Data_Get.DB_SEND_AND_GET(), ns_status, "SS_PROZESS", "SS_NAME");
//        } catch (Exception e) {
//            ns_status.removeAllItems();
//        }
//
//        db.DB_Data_Get.connclose();
//    }

    private void Fill_cb_P_Patient_nurse() {
        CMS_Config_Std std = CMS_Config_Std.getInstance();

        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("PSL_ID");
        // db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(PSL_TITEL,' ',PSA_NAME,' ',PSL_NAME,' ',PSL_VORNAME)","Patientenname");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln(
                "CONCAT(PSL_TITEL,' ',PSA_NAME,' ',PSL_NAME,' ',PSL_VORNAME, ' (',PSL_PLZ, ' ', PSL_ORT,')')", "Patientenname");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_patient_stammdaten_liste", "INNER JOIN",
                "cust_patient_stammdaten_anrede", "PSL_ANREDE", "PSA_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_patient_stammdaten_liste", "INNER JOIN", "cust_verk_haupt", "PSL_ID",
                "VH_PATIENT_ID");

        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_haupt", "VH_NURSE_ID", "=", Integer.toString(Get_ID_Nurse()), "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_haupt", "VH_PROJEKT_ID", "=", "1", "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_haupt", "VH_AKTIV", "=", "1", "");

        try {
            combo nc = new combo(db.DB_Data_Get.DB_SEND_AND_GET(), cb_pat, "PSL_ID", "Patientenname");
        } catch (Exception e) {
            cb_pat.removeAllItems();
        }

        db.DB_Data_Get.connclose();

        cb_pat.setFilteringMode(cb_pat.FILTERINGMODE_CONTAINS);
    }

    private void Fill_cb_P_Patient() {
        CMS_Config_Std std = CMS_Config_Std.getInstance();

        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("PSL_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln(
                "CONCAT(PSL_TITEL,' ',PSA_NAME,' ',PSL_NAME,' ',PSL_VORNAME, ' (',PSL_PLZ, ' ', PSL_ORT,')')", "Patientenname");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_patient_stammdaten_liste", "INNER JOIN",
                "cust_patient_stammdaten_anrede", "PSL_ANREDE", "PSA_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_patient_stammdaten_liste", "INNER JOIN", "cust_verk_haupt", "PSL_ID",
                "VH_PATIENT_ID");

        // db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_haupt",
        // "VH_NURSE_ID", "=", Integer.toString(Get_ID_Nurse()), "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_haupt", "VH_PROJEKT_ID", "=", "1", "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_haupt", "VH_AKTIV", "=", "1", "");

        try {
            combo nc = new combo(db.DB_Data_Get.DB_SEND_AND_GET(), cb_pat, "PSL_ID", "Patientenname");
        } catch (Exception e) {
            cb_pat.removeAllItems();
        }

        db.DB_Data_Get.connclose();

        cb_pat.setFilteringMode(cb_pat.FILTERINGMODE_CONTAINS);
    }

//    private void Fill_cb_lilly() {
//
//        List<Label> labels = new ArrayList<Label>();
//
//        labels.add(lbl_lilly_ja);
//        labels.add(lbl_lilly_vllt);
//        labels.add(lbl_lilly_skept);
//        labels.add(lbl_lilly_pflege);
//        labels.add(lbl_lilly_andere);
//        labels.add(lbl_lilly_ns);
//        labels.add(lbl_lilly_nicht);
//        labels.add(lbl_lilly_kontra);
//        labels.add(lbl_lilly_osteo);
//        labels.add(lbl_lilly_arzt);
//
//        for (Label l : labels) {
//        	
//        	System.out.println(l.getValue());
//        	System.out.println(l.getCaption());
//        	
//            cb_lilly.addItem(l.getValue());
//            cb_lilly.setItemCaption(l.getValue(), l.getCaption());
//        }
//
//    }

    @SuppressWarnings("serial")
    private void Set_Status_Select_OnChange() {
        ns_status.addValueChangeListener(new Property.ValueChangeListener() {
            @Override
            public void valueChange(ValueChangeEvent event) {
                boolean required = false;
                if (ns_status.getValue() != null && (int) ns_status.getValue() != 1) {
                    required = true;
                }

                ns_Stunden.setRequired(required);
                ns_min.setRequired(required);
                txt_Gesamte_Km.setRequired(required);

                pop_date.setRequired(required);
                txt_von.setRequired(required);
                txt_bis.setRequired(required);
                
                cb_lilly.setRequired(required);

                cb_arztConfirmed.setRequired(required);

            }
        });
    }

    private void Prüfung_Ist_Grp_Krankenschwestern() {
        int UID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        CMS_Config_Std std = CMS_Config_Std.getInstance();
        DBClass db = new DBClass();

        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cms_auth_liste_gu");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cms_auth_liste_gu", "AL_U_ID", "=", "'" + UID + "'", "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cms_auth_liste_gu", "AL_G_ID", "=", "'12'", "");

        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();

        if (con.size() > 0) {
            nurse = true;
        } else {
            nurse = false;
        }

    }
    
    private int Get_ID_Nurse() {

        int UID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        CMS_Config_Std std = CMS_Config_Std.getInstance();
        DBClass db = new DBClass();

        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("KSK_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("KSK_U_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_krankenschwester_stammdaten_ks");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_krankenschwester_stammdaten_ks", "KSK_U_ID", "=", "'" + UID + "'", "");

        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();

        int ksk = (int) con.getContainerProperty(1, "KSK_ID").getValue();

        return ksk;
    }

    @AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		mainLayout.addComponent(horizontalLayout_2);
		mainLayout.setExpandRatio(horizontalLayout_2, 2.3f);
		mainLayout.setComponentAlignment(horizontalLayout_2, new Alignment(48));
		
		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		mainLayout.addComponent(horizontalLayout_3);
		mainLayout.setExpandRatio(horizontalLayout_3, 3.0f);
		mainLayout.setComponentAlignment(horizontalLayout_3, new Alignment(48));
		
		// horizontalLayout_4
		horizontalLayout_4 = buildHorizontalLayout_4();
		mainLayout.addComponent(horizontalLayout_4);
		mainLayout.setExpandRatio(horizontalLayout_4, 1.7f);
		mainLayout.setComponentAlignment(horizontalLayout_4, new Alignment(48));
		
		// btn_save
		btn_save = new Button();
		btn_save.setCaption("Speichern");
		btn_save.setImmediate(true);
		btn_save.setWidth("-1px");
		btn_save.setHeight("-1px");
		mainLayout.addComponent(btn_save);
		mainLayout.setComponentAlignment(btn_save, new Alignment(48));
		
		// lilly_container
		lilly_container = buildLilly_container();
		mainLayout.addComponent(lilly_container);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("100.0%");
		horizontalLayout_2.setHeight("100.0%");
		horizontalLayout_2.setMargin(false);
		
		// verticalLayout_10
		verticalLayout_10 = buildVerticalLayout_10();
		horizontalLayout_2.addComponent(verticalLayout_10);
		horizontalLayout_2.setExpandRatio(verticalLayout_10, 1.0f);
		
		// pan_stammdaten
		pan_stammdaten = buildPan_stammdaten();
		horizontalLayout_2.addComponent(pan_stammdaten);
		horizontalLayout_2.setExpandRatio(pan_stammdaten, 4.0f);
		horizontalLayout_2.setComponentAlignment(pan_stammdaten, new Alignment(20));
		
		return horizontalLayout_2;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_10() {
		// common part: create layout
		verticalLayout_10 = new VerticalLayout();
		verticalLayout_10.setImmediate(false);
		verticalLayout_10.setWidth("90.0%");
		verticalLayout_10.setHeight("90.0%");
		verticalLayout_10.setMargin(false);
		
		// pan_dat
		pan_dat = buildPan_dat();
		verticalLayout_10.addComponent(pan_dat);
		verticalLayout_10.setExpandRatio(pan_dat, 1.0f);
		
		return verticalLayout_10;
	}

	@AutoGenerated
	private Panel buildPan_dat() {
		// common part: create layout
		pan_dat = new Panel();
		pan_dat.setCaption("Datierung");
		pan_dat.setImmediate(false);
		pan_dat.setWidth("100.0%");
		pan_dat.setHeight("100.0%");
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		pan_dat.setContent(verticalLayout_2);
		
		return pan_dat;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(false);
		
		// pop_term
		pop_term = new PopupDateField();
		pop_term.setCaption("Geplantes Datum");
		pop_term.setImmediate(false);
		pop_term.setWidth("80.0%");
		pop_term.setHeight("-1px");
		verticalLayout_2.addComponent(pop_term);
		verticalLayout_2.setComponentAlignment(pop_term, new Alignment(48));
		
		// pop_date
		pop_date = new PopupDateField();
		pop_date.setCaption("Datum");
		pop_date.setImmediate(false);
		pop_date.setWidth("80.0%");
		pop_date.setHeight("-1px");
		verticalLayout_2.addComponent(pop_date);
		verticalLayout_2.setComponentAlignment(pop_date, new Alignment(48));
		
		// horizontalLayout_11
		horizontalLayout_11 = buildHorizontalLayout_11();
		verticalLayout_2.addComponent(horizontalLayout_11);
		verticalLayout_2.setComponentAlignment(horizontalLayout_11, new Alignment(48));
		
		return verticalLayout_2;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_11() {
		// common part: create layout
		horizontalLayout_11 = new HorizontalLayout();
		horizontalLayout_11.setImmediate(false);
		horizontalLayout_11.setWidth("-1px");
		horizontalLayout_11.setHeight("-1px");
		horizontalLayout_11.setMargin(false);
		horizontalLayout_11.setSpacing(true);
		
		// txt_von
		txt_von = new TextField();
		txt_von.setCaption("Von");
		txt_von.setImmediate(false);
		txt_von.setWidth("64px");
		txt_von.setHeight("-1px");
		horizontalLayout_11.addComponent(txt_von);
		
		// txt_bis
		txt_bis = new TextField();
		txt_bis.setCaption("Bis");
		txt_bis.setImmediate(false);
		txt_bis.setWidth("64px");
		txt_bis.setHeight("-1px");
		horizontalLayout_11.addComponent(txt_bis);
		
		return horizontalLayout_11;
	}

	@AutoGenerated
	private Panel buildPan_stammdaten() {
		// common part: create layout
		pan_stammdaten = new Panel();
		pan_stammdaten.setCaption("Stammdatenauswahl");
		pan_stammdaten.setImmediate(false);
		pan_stammdaten.setWidth("100.0%");
		pan_stammdaten.setHeight("90.0%");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		pan_stammdaten.setContent(horizontalLayout_1);
		
		return pan_stammdaten;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("100.0%");
		horizontalLayout_1.setMargin(false);
		
		// verticalLayout_3
		verticalLayout_3 = buildVerticalLayout_3();
		horizontalLayout_1.addComponent(verticalLayout_3);
		horizontalLayout_1.setExpandRatio(verticalLayout_3, 3.0f);
		horizontalLayout_1.setComponentAlignment(verticalLayout_3, new Alignment(48));
		
		// horizontalLayout_7
		horizontalLayout_7 = buildHorizontalLayout_7();
		horizontalLayout_1.addComponent(horizontalLayout_7);
		horizontalLayout_1.setExpandRatio(horizontalLayout_7, 1.0f);
		horizontalLayout_1.setComponentAlignment(horizontalLayout_7, new Alignment(34));
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_3() {
		// common part: create layout
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("100.0%");
		verticalLayout_3.setHeight("100.0%");
		verticalLayout_3.setMargin(false);
		
		// horizontalLayout_8
		horizontalLayout_8 = buildHorizontalLayout_8();
		verticalLayout_3.addComponent(horizontalLayout_8);
		verticalLayout_3.setExpandRatio(horizontalLayout_8, 1.2f);
		verticalLayout_3.setComponentAlignment(horizontalLayout_8, new Alignment(33));
		
		// horizontalLayout_9
		horizontalLayout_9 = buildHorizontalLayout_9();
		verticalLayout_3.addComponent(horizontalLayout_9);
		verticalLayout_3.setExpandRatio(horizontalLayout_9, 1.0f);
		verticalLayout_3.setComponentAlignment(horizontalLayout_9, new Alignment(33));
		
		// horizontalLayout_12
		horizontalLayout_12 = buildHorizontalLayout_12();
		verticalLayout_3.addComponent(horizontalLayout_12);
		verticalLayout_3.setExpandRatio(horizontalLayout_12, 1.2f);
		
		return verticalLayout_3;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_8() {
		// common part: create layout
		horizontalLayout_8 = new HorizontalLayout();
		horizontalLayout_8.setImmediate(false);
		horizontalLayout_8.setWidth("100.0%");
		horizontalLayout_8.setHeight("-1px");
		horizontalLayout_8.setMargin(false);
		horizontalLayout_8.setSpacing(true);
		
		// verticalLayout_4
		verticalLayout_4 = buildVerticalLayout_4();
		horizontalLayout_8.addComponent(verticalLayout_4);
		horizontalLayout_8.setComponentAlignment(verticalLayout_4, new Alignment(9));
		
		// cb_pat
		cb_pat = new ComboBox();
		cb_pat.setStyleName("input-align");
		cb_pat.setCaption("Patientauswahl");
		cb_pat.setImmediate(false);
		cb_pat.setWidth("-1px");
		cb_pat.setHeight("-1px");
		horizontalLayout_8.addComponent(cb_pat);
		horizontalLayout_8.setExpandRatio(cb_pat, 1.0f);
		horizontalLayout_8.setComponentAlignment(cb_pat, new Alignment(9));
		
		return horizontalLayout_8;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_4() {
		// common part: create layout
		verticalLayout_4 = new VerticalLayout();
		verticalLayout_4.setImmediate(false);
		verticalLayout_4.setWidth("50px");
		verticalLayout_4.setHeight("-1px");
		verticalLayout_4.setMargin(false);
		
		// btn_pat_info
		btn_pat_info = new Button();
		btn_pat_info.setCaption("");
		btn_pat_info.setImmediate(true);
		btn_pat_info.setWidth("-1px");
		btn_pat_info.setHeight("-1px");
		verticalLayout_4.addComponent(btn_pat_info);
		verticalLayout_4.setComponentAlignment(btn_pat_info, new Alignment(20));
		
		return verticalLayout_4;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_9() {
		// common part: create layout
		horizontalLayout_9 = new HorizontalLayout();
		horizontalLayout_9.setImmediate(false);
		horizontalLayout_9.setWidth("-1px");
		horizontalLayout_9.setHeight("-1px");
		horizontalLayout_9.setMargin(false);
		horizontalLayout_9.setSpacing(true);
		
		// verticalLayout_6
		verticalLayout_6 = buildVerticalLayout_6();
		horizontalLayout_9.addComponent(verticalLayout_6);
		horizontalLayout_9.setComponentAlignment(verticalLayout_6, new Alignment(9));
		
		// verticalLayout_9
		verticalLayout_9 = buildVerticalLayout_9();
		horizontalLayout_9.addComponent(verticalLayout_9);
		horizontalLayout_9.setComponentAlignment(verticalLayout_9, new Alignment(9));
		
		// cb_nurse
		cb_nurse = new ComboBox();
		cb_nurse.setStyleName("input-align");
		cb_nurse.setCaption("Krankenschwester");
		cb_nurse.setImmediate(false);
		cb_nurse.setWidth("-1px");
		cb_nurse.setHeight("-1px");
		horizontalLayout_9.addComponent(cb_nurse);
		
		return horizontalLayout_9;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_6() {
		// common part: create layout
		verticalLayout_6 = new VerticalLayout();
		verticalLayout_6.setImmediate(false);
		verticalLayout_6.setWidth("50px");
		verticalLayout_6.setHeight("-1px");
		verticalLayout_6.setMargin(false);
		
		// btn_nurse_info
		btn_nurse_info = new Button();
		btn_nurse_info.setCaption("");
		btn_nurse_info.setImmediate(true);
		btn_nurse_info.setWidth("-1px");
		btn_nurse_info.setHeight("-1px");
		verticalLayout_6.addComponent(btn_nurse_info);
		verticalLayout_6.setComponentAlignment(btn_nurse_info, new Alignment(20));
		
		return verticalLayout_6;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_9() {
		// common part: create layout
		verticalLayout_9 = new VerticalLayout();
		verticalLayout_9.setImmediate(false);
		verticalLayout_9.setWidth("-1px");
		verticalLayout_9.setHeight("-1px");
		verticalLayout_9.setMargin(false);
		
		// btn_zuweisung
		btn_zuweisung = new Button();
		btn_zuweisung.setCaption("Zuweisung");
		btn_zuweisung.setImmediate(true);
		btn_zuweisung.setWidth("-1px");
		btn_zuweisung.setHeight("-1px");
		verticalLayout_9.addComponent(btn_zuweisung);
		
		return verticalLayout_9;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_12() {
		// common part: create layout
		horizontalLayout_12 = new HorizontalLayout();
		horizontalLayout_12.setImmediate(false);
		horizontalLayout_12.setWidth("-1px");
		horizontalLayout_12.setHeight("-1px");
		horizontalLayout_12.setMargin(false);
		horizontalLayout_12.setSpacing(true);
		
		// verticalLayout_8
		verticalLayout_8 = buildVerticalLayout_8();
		horizontalLayout_12.addComponent(verticalLayout_8);
		horizontalLayout_12.setComponentAlignment(verticalLayout_8, new Alignment(9));
		
		// cbx_arzt
		cbx_arzt = new ComboBox();
		cbx_arzt.setCaption("Delegierender Arzt");
		cbx_arzt.setImmediate(false);
		cbx_arzt.setWidth("-1px");
		cbx_arzt.setHeight("-1px");
		horizontalLayout_12.addComponent(cbx_arzt);
		horizontalLayout_12.setExpandRatio(cbx_arzt, 1.0f);
		
		// cb_arztConfirmed
		cb_arztConfirmed = new CheckBox();
		cb_arztConfirmed.setCaption("Bestätigt");
		cb_arztConfirmed.setImmediate(false);
		cb_arztConfirmed.setWidth("-1px");
		cb_arztConfirmed.setHeight("54.0%");
		horizontalLayout_12.addComponent(cb_arztConfirmed);
		horizontalLayout_12.setComponentAlignment(cb_arztConfirmed, new Alignment(9));
		
		return horizontalLayout_12;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_8() {
		// common part: create layout
		verticalLayout_8 = new VerticalLayout();
		verticalLayout_8.setImmediate(false);
		verticalLayout_8.setWidth("50px");
		verticalLayout_8.setHeight("-1px");
		verticalLayout_8.setMargin(false);
		
		// btn_arzt_info
		btn_arzt_info = new Button();
		btn_arzt_info.setCaption("");
		btn_arzt_info.setImmediate(true);
		btn_arzt_info.setWidth("-1px");
		btn_arzt_info.setHeight("-1px");
		verticalLayout_8.addComponent(btn_arzt_info);
		verticalLayout_8.setComponentAlignment(btn_arzt_info, new Alignment(20));
		
		return verticalLayout_8;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_7() {
		// common part: create layout
		horizontalLayout_7 = new HorizontalLayout();
		horizontalLayout_7.setImmediate(false);
		horizontalLayout_7.setWidth("180px");
		horizontalLayout_7.setHeight("100.0%");
		horizontalLayout_7.setMargin(false);
		
		// verticalLayout_7
		verticalLayout_7 = buildVerticalLayout_7();
		horizontalLayout_7.addComponent(verticalLayout_7);
		horizontalLayout_7.setExpandRatio(verticalLayout_7, 3.0f);
		horizontalLayout_7.setComponentAlignment(verticalLayout_7, new Alignment(34));
		
		return horizontalLayout_7;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_7() {
		// common part: create layout
		verticalLayout_7 = new VerticalLayout();
		verticalLayout_7.setImmediate(false);
		verticalLayout_7.setWidth("100.0%");
		verticalLayout_7.setHeight("50.0%");
		verticalLayout_7.setMargin(false);
		
		// ns_status
		ns_status = new ComboBox();
		ns_status.setStyleName("input-align");
		ns_status.setCaption("Protokollstatus");
		ns_status.setImmediate(true);
		ns_status.setWidth("130px");
		ns_status.setHeight("-1px");
		verticalLayout_7.addComponent(ns_status);
		verticalLayout_7.setComponentAlignment(ns_status, new Alignment(48));
		
		// cb_leadNurseOk
		cb_leadNurseOk = new CheckBox();
		cb_leadNurseOk.setCaption("LN Daten überprüft");
		cb_leadNurseOk.setImmediate(false);
		cb_leadNurseOk.setWidth("-1px");
		cb_leadNurseOk.setHeight("-1px");
		verticalLayout_7.addComponent(cb_leadNurseOk);
		verticalLayout_7.setComponentAlignment(cb_leadNurseOk, new Alignment(48));
		
		// cb_cancelled
		cb_cancelled = new CheckBox();
		cb_cancelled.setCaption("Storniert");
		cb_cancelled.setImmediate(false);
		cb_cancelled.setWidth("-1px");
		cb_cancelled.setHeight("-1px");
		verticalLayout_7.addComponent(cb_cancelled);
		verticalLayout_7.setComponentAlignment(cb_cancelled, new Alignment(48));
		
		return verticalLayout_7;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("100.0%");
		horizontalLayout_3.setHeight("100.0%");
		horizontalLayout_3.setMargin(false);
		
		// pan_abrechnungsdaten
		pan_abrechnungsdaten = buildPan_abrechnungsdaten();
		horizontalLayout_3.addComponent(pan_abrechnungsdaten);
		horizontalLayout_3.setExpandRatio(pan_abrechnungsdaten, 1.6f);
		horizontalLayout_3.setComponentAlignment(pan_abrechnungsdaten, new Alignment(48));
		
		// pan_BesD
		pan_BesD = buildPan_BesD();
		horizontalLayout_3.addComponent(pan_BesD);
		horizontalLayout_3.setExpandRatio(pan_BesD, 4.0f);
		
		return horizontalLayout_3;
	}

	@AutoGenerated
	private Panel buildPan_abrechnungsdaten() {
		// common part: create layout
		pan_abrechnungsdaten = new Panel();
		pan_abrechnungsdaten.setCaption("Abrechnungsdaten");
		pan_abrechnungsdaten.setImmediate(false);
		pan_abrechnungsdaten.setWidth("100.0%");
		pan_abrechnungsdaten.setHeight("100.0%");
		
		// verticalLayout_5
		verticalLayout_5 = buildVerticalLayout_5();
		pan_abrechnungsdaten.setContent(verticalLayout_5);
		
		return pan_abrechnungsdaten;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_5() {
		// common part: create layout
		verticalLayout_5 = new VerticalLayout();
		verticalLayout_5.setImmediate(false);
		verticalLayout_5.setWidth("100.0%");
		verticalLayout_5.setHeight("100.0%");
		verticalLayout_5.setMargin(true);
		
		// gl_double
		gl_double = buildGl_double();
		verticalLayout_5.addComponent(gl_double);
		verticalLayout_5.setExpandRatio(gl_double, 2.0f);
		verticalLayout_5.setComponentAlignment(gl_double, new Alignment(20));
		
		// horizontalLayout_6
		horizontalLayout_6 = buildHorizontalLayout_6();
		verticalLayout_5.addComponent(horizontalLayout_6);
		verticalLayout_5.setExpandRatio(horizontalLayout_6, 0.2f);
		verticalLayout_5.setComponentAlignment(horizontalLayout_6, new Alignment(24));
		
		return verticalLayout_5;
	}

	@AutoGenerated
	private GridLayout buildGl_double() {
		// common part: create layout
		gl_double = new GridLayout();
		gl_double.setImmediate(false);
		gl_double.setWidth("100.0%");
		gl_double.setHeight("100.0%");
		gl_double.setMargin(false);
		gl_double.setColumns(2);
		
		// vl_nurse
		vl_nurse = buildVl_nurse();
		gl_double.addComponent(vl_nurse, 0, 0);
		
		// vl_cs
		vl_cs = buildVl_cs();
		gl_double.addComponent(vl_cs, 1, 0);
		
		return gl_double;
	}

	@AutoGenerated
	private VerticalLayout buildVl_nurse() {
		// common part: create layout
		vl_nurse = new VerticalLayout();
		vl_nurse.setCaption("Erfasst");
		vl_nurse.setImmediate(false);
		vl_nurse.setWidth("-1px");
		vl_nurse.setHeight("-1px");
		vl_nurse.setMargin(false);
		vl_nurse.setSpacing(true);
		
		// horizontalLayout_10
		horizontalLayout_10 = buildHorizontalLayout_10();
		vl_nurse.addComponent(horizontalLayout_10);
		
		// txt_Gesamte_Km
		txt_Gesamte_Km = new TextField();
		txt_Gesamte_Km.setCaption("Gesamte km");
		txt_Gesamte_Km.setImmediate(false);
		txt_Gesamte_Km.setWidth("100px");
		txt_Gesamte_Km.setHeight("-1px");
		vl_nurse.addComponent(txt_Gesamte_Km);
		
		// int_anrufe
		int_anrufe = new IntStepper();
		int_anrufe.setCaption("Anrufe");
		int_anrufe.setImmediate(false);
		int_anrufe.setWidth("45px");
		int_anrufe.setHeight("-1px");
		vl_nurse.addComponent(int_anrufe);
		
		return vl_nurse;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_10() {
		// common part: create layout
		horizontalLayout_10 = new HorizontalLayout();
		horizontalLayout_10.setImmediate(false);
		horizontalLayout_10.setWidth("-1px");
		horizontalLayout_10.setHeight("-1px");
		horizontalLayout_10.setMargin(false);
		horizontalLayout_10.setSpacing(true);
		
		// ns_Stunden
		ns_Stunden = new NativeSelect();
		ns_Stunden.setCaption("Stunden");
		ns_Stunden.setImmediate(false);
		ns_Stunden.setWidth("-1px");
		ns_Stunden.setHeight("-1px");
		horizontalLayout_10.addComponent(ns_Stunden);
		
		// ns_min
		ns_min = new NativeSelect();
		ns_min.setCaption("Minuten");
		ns_min.setImmediate(false);
		ns_min.setWidth("-1px");
		ns_min.setHeight("-1px");
		horizontalLayout_10.addComponent(ns_min);
		
		return horizontalLayout_10;
	}

	@AutoGenerated
	private VerticalLayout buildVl_cs() {
		// common part: create layout
		vl_cs = new VerticalLayout();
		vl_cs.setCaption("Abgerechnet");
		vl_cs.setImmediate(false);
		vl_cs.setWidth("-1px");
		vl_cs.setHeight("-1px");
		vl_cs.setMargin(false);
		vl_cs.setSpacing(true);
		
		// horizontalLayout_5
		horizontalLayout_5 = buildHorizontalLayout_5();
		vl_cs.addComponent(horizontalLayout_5);
		
		// txt_Abrechnungs_Km
		txt_Abrechnungs_Km = new TextField();
		txt_Abrechnungs_Km.setCaption("Abgerechnete km");
		txt_Abrechnungs_Km.setImmediate(false);
		txt_Abrechnungs_Km.setWidth("100px");
		txt_Abrechnungs_Km.setHeight("-1px");
		vl_cs.addComponent(txt_Abrechnungs_Km);
		
		return vl_cs;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_5() {
		// common part: create layout
		horizontalLayout_5 = new HorizontalLayout();
		horizontalLayout_5.setImmediate(false);
		horizontalLayout_5.setWidth("-1px");
		horizontalLayout_5.setHeight("-1px");
		horizontalLayout_5.setMargin(false);
		horizontalLayout_5.setSpacing(true);
		
		// ns_Abrechnung_Stunden
		ns_Abrechnung_Stunden = new NativeSelect();
		ns_Abrechnung_Stunden.setCaption("Stunden");
		ns_Abrechnung_Stunden.setImmediate(false);
		ns_Abrechnung_Stunden.setWidth("-1px");
		ns_Abrechnung_Stunden.setHeight("-1px");
		horizontalLayout_5.addComponent(ns_Abrechnung_Stunden);
		
		// ns_Abrechnung_Minuten
		ns_Abrechnung_Minuten = new NativeSelect();
		ns_Abrechnung_Minuten.setCaption("Minuten");
		ns_Abrechnung_Minuten.setImmediate(false);
		ns_Abrechnung_Minuten.setWidth("-1px");
		ns_Abrechnung_Minuten.setHeight("-1px");
		horizontalLayout_5.addComponent(ns_Abrechnung_Minuten);
		
		return horizontalLayout_5;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_6() {
		// common part: create layout
		horizontalLayout_6 = new HorizontalLayout();
		horizontalLayout_6.setImmediate(false);
		horizontalLayout_6.setWidth("100.0%");
		horizontalLayout_6.setHeight("100.0%");
		horizontalLayout_6.setMargin(false);
		
		// cb_admin
		cb_admin = new CheckBox();
		cb_admin.setCaption("Admin Pauschale");
		cb_admin.setImmediate(false);
		cb_admin.setWidth("-1px");
		cb_admin.setHeight("-1px");
		horizontalLayout_6.addComponent(cb_admin);
		horizontalLayout_6.setComponentAlignment(cb_admin, new Alignment(48));
		
		// btn_km_ber
		btn_km_ber = new Button();
		btn_km_ber.setCaption("");
		btn_km_ber.setImmediate(true);
		btn_km_ber.setWidth("-1px");
		btn_km_ber.setHeight("-1px");
		horizontalLayout_6.addComponent(btn_km_ber);
		horizontalLayout_6.setComponentAlignment(btn_km_ber, new Alignment(48));
		
		return horizontalLayout_6;
	}

	@AutoGenerated
	private TabSheet buildPan_BesD() {
		// common part: create layout
		pan_BesD = new TabSheet();
		pan_BesD.setCaption("Besuchsdetails");
		pan_BesD.setImmediate(true);
		pan_BesD.setWidth("100.0%");
		pan_BesD.setHeight("100.0%");
		
		// grid_pat_details
		grid_pat_details = buildGrid_pat_details();
		pan_BesD.addTab(grid_pat_details, "Patientendetails", null);
		
		// grid_schul_inh
		grid_schul_inh = buildGrid_schul_inh();
		pan_BesD.addTab(grid_schul_inh, "Vermittelte Schulungsinhalte", null);
		
		// grid_ue_report
		grid_ue_report = buildGrid_ue_report();
		pan_BesD.addTab(grid_ue_report, "UE Meldung", null);
		
		return pan_BesD;
	}

	@AutoGenerated
	private GridLayout buildGrid_pat_details() {
		// common part: create layout
		grid_pat_details = new GridLayout();
		grid_pat_details.setCaption("Patientendetails");
		grid_pat_details.setImmediate(false);
		grid_pat_details.setWidth("100.0%");
		grid_pat_details.setHeight("-1px");
		grid_pat_details.setMargin(true);
		grid_pat_details.setSpacing(true);
		grid_pat_details.setColumns(2);
		grid_pat_details.setRows(4);
		
		// cb_1
		cb_1 = new CheckBox();
		cb_1.setCaption("cb_1");
		cb_1.setImmediate(false);
		cb_1.setWidth("-1px");
		cb_1.setHeight("-1px");
		grid_pat_details.addComponent(cb_1, 0, 0);
		
		// cb_15
		cb_15 = new CheckBox();
		cb_15.setCaption("cb_15");
		cb_15.setImmediate(false);
		cb_15.setWidth("-1px");
		cb_15.setHeight("-1px");
		grid_pat_details.addComponent(cb_15, 1, 0);
		
		// cb_14
		cb_14 = new CheckBox();
		cb_14.setCaption("cb_14");
		cb_14.setImmediate(false);
		cb_14.setWidth("-1px");
		cb_14.setHeight("-1px");
		grid_pat_details.addComponent(cb_14, 0, 1);
		
		// cb_no_anomalies
		cb_no_anomalies = new CheckBox();
		cb_no_anomalies.setCaption("Penschulung verlief ohne Besonderheiten");
		cb_no_anomalies.setImmediate(false);
		cb_no_anomalies.setWidth("-1px");
		cb_no_anomalies.setHeight("-1px");
		grid_pat_details.addComponent(cb_no_anomalies, 0, 2);
		
		// cb_nurse_concerns
		cb_nurse_concerns = new CheckBox();
		cb_nurse_concerns.setCaption("Nurse hat Bedenken bei der Umsetzung");
		cb_nurse_concerns.setImmediate(false);
		cb_nurse_concerns.setWidth("-1px");
		cb_nurse_concerns.setHeight("-1px");
		grid_pat_details.addComponent(cb_nurse_concerns, 1, 2);
		
		// ueProductUsed
		ueProductUsed = new ComboBox();
		ueProductUsed.setCaption("Wurde das Präparat bereits verwendet?");
		ueProductUsed.setImmediate(false);
		ueProductUsed.setWidth("-1px");
		ueProductUsed.setHeight("24px");
		grid_pat_details.addComponent(ueProductUsed, 0, 3);
		grid_pat_details.setComponentAlignment(ueProductUsed, new Alignment(33));
		
		return grid_pat_details;
	}

	@AutoGenerated
	private GridLayout buildGrid_schul_inh() {
		// common part: create layout
		grid_schul_inh = new GridLayout();
		grid_schul_inh.setStyleName("Vermittelte Schulungsinhalte");
		grid_schul_inh.setImmediate(false);
		grid_schul_inh.setWidth("100.0%");
		grid_schul_inh.setHeight("-1px");
		grid_schul_inh.setMargin(true);
		grid_schul_inh.setSpacing(true);
		grid_schul_inh.setColumns(2);
		grid_schul_inh.setRows(6);
		
		// cb_7
		cb_7 = new CheckBox();
		cb_7.setCaption("cb_7");
		cb_7.setImmediate(false);
		cb_7.setWidth("-1px");
		cb_7.setHeight("-1px");
		grid_schul_inh.addComponent(cb_7, 0, 0);
		
		// cb_8
		cb_8 = new CheckBox();
		cb_8.setCaption("cb_8");
		cb_8.setImmediate(false);
		cb_8.setWidth("-1px");
		cb_8.setHeight("-1px");
		grid_schul_inh.addComponent(cb_8, 0, 1);
		
		// cb_3
		cb_3 = new CheckBox();
		cb_3.setCaption("cb_3");
		cb_3.setImmediate(false);
		cb_3.setWidth("-1px");
		cb_3.setHeight("-1px");
		grid_schul_inh.addComponent(cb_3, 1, 1);
		
		// cb_6
		cb_6 = new CheckBox();
		cb_6.setCaption("cb_6");
		cb_6.setImmediate(false);
		cb_6.setWidth("-1px");
		cb_6.setHeight("-1px");
		grid_schul_inh.addComponent(cb_6, 0, 2);
		
		// cb_5
		cb_5 = new CheckBox();
		cb_5.setCaption("cb_5");
		cb_5.setImmediate(false);
		cb_5.setWidth("-1px");
		cb_5.setHeight("-1px");
		grid_schul_inh.addComponent(cb_5, 1, 2);
		
		// cb_17
		cb_17 = new CheckBox();
		cb_17.setCaption("cb_17");
		cb_17.setImmediate(false);
		cb_17.setWidth("-1px");
		cb_17.setHeight("-1px");
		grid_schul_inh.addComponent(cb_17, 0, 3);
		
		// cb_16
		cb_16 = new CheckBox();
		cb_16.setCaption("cb_16");
		cb_16.setImmediate(false);
		cb_16.setWidth("-1px");
		cb_16.setHeight("-1px");
		grid_schul_inh.addComponent(cb_16, 1, 3);
		
		// cb_9
		cb_9 = new CheckBox();
		cb_9.setCaption("cb_9");
		cb_9.setImmediate(false);
		cb_9.setWidth("-1px");
		cb_9.setHeight("-1px");
		grid_schul_inh.addComponent(cb_9, 0, 4);
		
		// cb_lilly
		cb_lilly = new ComboBox();
		cb_lilly.setCaption("Teilnahme am Betreuungsmodell");
		cb_lilly.setImmediate(false);
		cb_lilly.setWidth("250px");
		cb_lilly.setHeight("-1px");
		grid_schul_inh.addComponent(cb_lilly, 1, 4);
		
		// cb_10
		cb_10 = new CheckBox();
		cb_10.setCaption("cb_10");
		cb_10.setImmediate(false);
		cb_10.setWidth("-1px");
		cb_10.setHeight("-1px");
		grid_schul_inh.addComponent(cb_10, 0, 5);
		
		return grid_schul_inh;
	}

	@AutoGenerated
	private GridLayout buildGrid_ue_report() {
		// common part: create layout
		grid_ue_report = new GridLayout();
		grid_ue_report.setImmediate(false);
		grid_ue_report.setWidth("100.0%");
		grid_ue_report.setHeight("100.0%");
		grid_ue_report.setMargin(true);
		grid_ue_report.setRows(4);
		
		// ueReportExist
		ueReportExist = new ComboBox();
		ueReportExist.setCaption("Gab es hierzu eine UE-Meldung oder eine sonstige Sicherheitsmitteilung?");
		ueReportExist.setImmediate(false);
		ueReportExist.setWidth("-1px");
		ueReportExist.setHeight("-1px");
		grid_ue_report.addComponent(ueReportExist, 0, 1);
		
		// casenumber
		casenumber = new TextField();
		casenumber.setCaption("Fallnummer");
		casenumber.setImmediate(false);
		casenumber.setWidth("200px");
		casenumber.setHeight("-1px");
		casenumber.setMaxLength(30);
		grid_ue_report.addComponent(casenumber, 0, 3);
		grid_ue_report.setComponentAlignment(casenumber, new Alignment(33));
		
		return grid_ue_report;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_4() {
		// common part: create layout
		horizontalLayout_4 = new HorizontalLayout();
		horizontalLayout_4.setImmediate(false);
		horizontalLayout_4.setWidth("100.0%");
		horizontalLayout_4.setHeight("100.0%");
		horizontalLayout_4.setMargin(false);
		
		// txta_beobachtungen
		txta_beobachtungen = new TextArea();
		txta_beobachtungen.setCaption("Beobachtungen");
		txta_beobachtungen.setImmediate(false);
		txta_beobachtungen.setWidth("80.0%");
		txta_beobachtungen.setHeight("80.0%");
		horizontalLayout_4.addComponent(txta_beobachtungen);
		horizontalLayout_4.setComponentAlignment(txta_beobachtungen, new Alignment(48));
		
		// txta_bemerkungen
		txta_bemerkungen = new TextArea();
		txta_bemerkungen.setCaption("Bemerkungen");
		txta_bemerkungen.setImmediate(false);
		txta_bemerkungen.setWidth("80.0%");
		txta_bemerkungen.setHeight("80.0%");
		horizontalLayout_4.addComponent(txta_bemerkungen);
		horizontalLayout_4.setComponentAlignment(txta_bemerkungen, new Alignment(48));
		
		return horizontalLayout_4;
	}

	@AutoGenerated
	private AbsoluteLayout buildLilly_container() {
		// common part: create layout
		lilly_container = new AbsoluteLayout();
		lilly_container.setEnabled(false);
		lilly_container.setImmediate(false);
		lilly_container.setVisible(false);
		lilly_container.setWidth("-1px");
		lilly_container.setHeight("-1px");
		
		// lbl_lilly_ja
		lbl_lilly_ja = new Label();
		lbl_lilly_ja.setCaption("Patient nimmt teil");
		lbl_lilly_ja.setEnabled(false);
		lbl_lilly_ja.setImmediate(false);
		lbl_lilly_ja.setVisible(false);
		lbl_lilly_ja.setWidth("-1px");
		lbl_lilly_ja.setHeight("-1px");
		lbl_lilly_ja.setValue("1");
		lilly_container.addComponent(lbl_lilly_ja, "top:0.0px;left:0.0px;");
		
		// lbl_lilly_vllt
		lbl_lilly_vllt = new Label();
		lbl_lilly_vllt.setCaption("Patient möchte sich die Teilnahme noch überlegen");
		lbl_lilly_vllt.setEnabled(false);
		lbl_lilly_vllt.setImmediate(false);
		lbl_lilly_vllt.setVisible(false);
		lbl_lilly_vllt.setWidth("-1px");
		lbl_lilly_vllt.setHeight("-1px");
		lbl_lilly_vllt.setValue("2");
		lilly_container.addComponent(lbl_lilly_vllt, "top:0.0px;left:0.0px;");
		
		// lbl_lilly_skept
		lbl_lilly_skept = new Label();
		lbl_lilly_skept.setCaption("Patient ist sehr ängstlich und skeptisch");
		lbl_lilly_skept.setEnabled(false);
		lbl_lilly_skept.setImmediate(false);
		lbl_lilly_skept.setVisible(false);
		lbl_lilly_skept.setWidth("-1px");
		lbl_lilly_skept.setHeight("-1px");
		lbl_lilly_skept.setValue("3");
		lilly_container.addComponent(lbl_lilly_skept, "top:0.0px;left:0.0px;");
		
		// lbl_lilly_pflege
		lbl_lilly_pflege = new Label();
		lbl_lilly_pflege.setCaption("Patient wird vom Pflegedienst versorgt");
		lbl_lilly_pflege.setEnabled(false);
		lbl_lilly_pflege.setImmediate(false);
		lbl_lilly_pflege.setVisible(false);
		lbl_lilly_pflege.setWidth("-1px");
		lbl_lilly_pflege.setHeight("-1px");
		lbl_lilly_pflege.setValue("4");
		lilly_container.addComponent(lbl_lilly_pflege, "top:0.0px;left:0.0px;");
		
		// lbl_lilly_andere
		lbl_lilly_andere = new Label();
		lbl_lilly_andere.setCaption("Patient informiert sich anderweitig");
		lbl_lilly_andere.setEnabled(false);
		lbl_lilly_andere.setImmediate(false);
		lbl_lilly_andere.setVisible(false);
		lbl_lilly_andere.setWidth("-1px");
		lbl_lilly_andere.setHeight("-1px");
		lbl_lilly_andere.setValue("5");
		lilly_container.addComponent(lbl_lilly_andere, "top:0.0px;left:0.0px;");
		
		// lbl_lilly_ns
		lbl_lilly_ns = new Label();
		lbl_lilly_ns.setCaption("Nachschulung");
		lbl_lilly_ns.setEnabled(false);
		lbl_lilly_ns.setImmediate(false);
		lbl_lilly_ns.setVisible(false);
		lbl_lilly_ns.setWidth("-1px");
		lbl_lilly_ns.setHeight("-1px");
		lbl_lilly_ns.setValue("6");
		lilly_container.addComponent(lbl_lilly_ns, "top:0.0px;left:0.0px;");
		
		// lbl_lilly_nicht
		lbl_lilly_nicht = new Label();
		lbl_lilly_nicht.setCaption("Schulung konnte nicht durchgeführt werden");
		lbl_lilly_nicht.setEnabled(false);
		lbl_lilly_nicht.setImmediate(false);
		lbl_lilly_nicht.setVisible(false);
		lbl_lilly_nicht.setWidth("-1px");
		lbl_lilly_nicht.setHeight("-1px");
		lbl_lilly_nicht.setValue("7");
		lilly_container.addComponent(lbl_lilly_nicht, "top:0.0px;left:0.0px;");
		
		// lbl_lilly_kontra
		lbl_lilly_kontra = new Label();
		lbl_lilly_kontra.setCaption("Patient hat Kontraindikation - bestrahlter Tumor");
		lbl_lilly_kontra.setEnabled(false);
		lbl_lilly_kontra.setImmediate(false);
		lbl_lilly_kontra.setVisible(false);
		lbl_lilly_kontra.setWidth("-1px");
		lbl_lilly_kontra.setHeight("-1px");
		lbl_lilly_kontra.setValue("8");
		lilly_container.addComponent(lbl_lilly_kontra, "top:0.0px;left:0.0px;");
		
		// lbl_lilly_osteo
		lbl_lilly_osteo = new Label();
		lbl_lilly_osteo.setCaption("Patient hat keine Osteoporose");
		lbl_lilly_osteo.setEnabled(false);
		lbl_lilly_osteo.setImmediate(false);
		lbl_lilly_osteo.setVisible(false);
		lbl_lilly_osteo.setWidth("-1px");
		lbl_lilly_osteo.setHeight("-1px");
		lbl_lilly_osteo.setValue("9");
		lilly_container.addComponent(lbl_lilly_osteo, "top:0.0px;left:0.0px;");
		
		// lbl_lilly_arzt
		lbl_lilly_arzt = new Label();
		lbl_lilly_arzt.setCaption("Ärzteschulung");
		lbl_lilly_arzt.setEnabled(false);
		lbl_lilly_arzt.setImmediate(false);
		lbl_lilly_arzt.setVisible(false);
		lbl_lilly_arzt.setWidth("-1px");
		lbl_lilly_arzt.setHeight("-1px");
		lbl_lilly_arzt.setValue("10");
		lilly_container.addComponent(lbl_lilly_arzt, "top:0.0px;left:0.0px;");
		
		return lilly_container;
	}

}
