package archenoah.web.setup.form;

import java.util.HashMap;
import java.util.Map;




import archenoah.lib.vaadin.Components.Validators.Isconet_Validators_1;
import archenoah.lib.vaadin.valchecker.val_checker4;
import archenoah.web.setup.validator.Val_Setup_Datenbank;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Upload;

public class Setup_Datenbank_Application extends CustomComponent {

	@AutoGenerated
	public AbsoluteLayout mainLayout;
	@AutoGenerated
	public Label label_1;
	@AutoGenerated
	public Button btn_new_user;
	@AutoGenerated
	public CheckBox sw_import;
	@AutoGenerated
	public CheckBox cb_import_abg;
	@AutoGenerated
	public Button btn_upload;
	@AutoGenerated
	public Upload txt_upload;
	@AutoGenerated
	public Button btn_DB_new;
	@AutoGenerated
	public Button btn_Install_check;
	@AutoGenerated
	public TextField txt_Port;
	@AutoGenerated
	public TextField txt_Database;
	@AutoGenerated
	public TextField txt_User;
	@AutoGenerated
	public TextField txt_Server_Adresse;
	@AutoGenerated
	public PasswordField txt_pass;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	public Map<Object, String> ValidateMap;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Setup_Datenbank_Application() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here

		
		

		
		btn_upload.setEnabled(false);
		cb_import_abg.setReadOnly(false);
		cb_import_abg.setEnabled(false);
		cb_import_abg.setReadOnly(true);
		
		txt_upload.setEnabled(false);
		
		Validate();
		
		
		//
		
		
		txt_Port.setValue("3306");
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("580px");
		mainLayout.setHeight("360px");
	
		
		// top-level component properties
		setWidth("580px");
		setHeight("360px");
		
		// txt_pass
		txt_pass = new PasswordField();
		txt_pass.setCaption("Passwort");
		txt_pass.setImmediate(false);
		txt_pass.setWidth("160px");
		txt_pass.setHeight("-1px");
		txt_pass.setTabIndex(5);
		txt_pass.setInputPrompt("Musterpassswort");
		mainLayout.addComponent(txt_pass, "top:181.0px;left:200.0px;");
		
		// txt_Server_Adresse
		txt_Server_Adresse = new TextField();
		txt_Server_Adresse.setCaption("Server Adresse");
		txt_Server_Adresse.setImmediate(false);
		txt_Server_Adresse.setWidth("160px");
		txt_Server_Adresse.setHeight("-1px");
		txt_Server_Adresse.setTabIndex(1);
		txt_Server_Adresse.setInputPrompt("Serveradresse.de");
	
		mainLayout.addComponent(txt_Server_Adresse, "top:20.0px;left:200.0px;");
		
		// txt_User
		txt_User = new TextField();
		txt_User.setCaption("Benutzername");
		txt_User.setImmediate(false);
		txt_User.setWidth("160px");
		txt_User.setHeight("-1px");
		txt_User.setTabIndex(4);
		txt_User.setInputPrompt("Musteruser");

		mainLayout.addComponent(txt_User, "top:140.0px;left:200.0px;");
		
		// txt_Database
		txt_Database = new TextField();
		txt_Database.setCaption("Datenbankname");
		txt_Database.setImmediate(false);
		txt_Database.setWidth("160px");
		txt_Database.setHeight("-1px");
		txt_Database.setTabIndex(3);
		txt_Database.setInputPrompt("Muster Datenbankname");

		mainLayout.addComponent(txt_Database, "top:100.0px;left:200.0px;");
		
		// txt_Port
		txt_Port = new TextField();
		txt_Port.setCaption("Port");
		txt_Port.setImmediate(false);
		txt_Port.setWidth("160px");
		txt_Port.setHeight("-1px");
		txt_Port.setTabIndex(2);
		txt_Port.setInputPrompt("3306");

		mainLayout.addComponent(txt_Port, "top:60.0px;left:200.0px;");
		
		// btn_Install_check
		btn_Install_check = new Button();
		btn_Install_check.setCaption("Daten Übernehmen");
		btn_Install_check.setImmediate(true);
		btn_Install_check.setWidth("224px");
		btn_Install_check.setHeight("26px");
		mainLayout.addComponent(btn_Install_check, "top:320.0px;left:180.0px;");
		
		// btn_DB_new
		btn_DB_new = new Button();
		btn_DB_new.setCaption("Neue Datenbank Erstellen");
		btn_DB_new.setImmediate(true);
		btn_DB_new.setWidth("180px");
		btn_DB_new.setHeight("26px");
		mainLayout.addComponent(btn_DB_new, "top:100.0px;left:380.0px;");
		
		// txt_upload
		txt_upload = new Upload();
		txt_upload.setImmediate(false);
		txt_upload.setWidth("281px");
		txt_upload.setHeight("-1px");
		mainLayout.addComponent(txt_upload, "top:281.0px;left:15.0px;");
		
		// btn_upload
		btn_upload = new Button();
		btn_upload.setCaption("Upload");
		btn_upload.setImmediate(true);
		btn_upload.setWidth("80px");
		btn_upload.setHeight("-1px");
		mainLayout.addComponent(btn_upload, "top:283.0px;left:439.0px;");
		
		// cb_import_abg
		cb_import_abg = new CheckBox();
		cb_import_abg.setCaption("Import bereit");
		cb_import_abg.setImmediate(false);
		cb_import_abg.setWidth("96px");
		cb_import_abg.setHeight("18px");
		mainLayout.addComponent(cb_import_abg, "top:285.0px;left:312.0px;");
		
		// sw_import
		sw_import = new CheckBox();
		sw_import.setImmediate(false);
		sw_import.setWidth("-1px");
		sw_import.setHeight("-1px");
		mainLayout.addComponent(sw_import, "top:218.0px;left:237.0px;");
		
		// btn_new_user
		btn_new_user = new Button();
		btn_new_user.setCaption("Neuen Benutzer Erstellen");
		btn_new_user.setImmediate(true);
		btn_new_user.setWidth("180px");
		btn_new_user.setHeight("26px");
		mainLayout.addComponent(btn_new_user, "top:138.0px;left:380.0px;");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("<h3>Daten Importieren</h3>");
		label_1.setContentMode(label_1.CONTENT_XHTML);
		mainLayout.addComponent(label_1, "top:242.0px;left:220.0px;");
		
		return mainLayout;
	}
	
	private void Validate()
	{ 	
	Set_Validate_Map(); 
	Isconet_Validators_1 isv = new Isconet_Validators_1( "1", ValidateMap);
	 } 

	
	 private void Set_Validate_Map() 
	{ 
	ValidateMap = new HashMap<>(); 
	ValidateMap.put(txt_Server_Adresse,"Keine_Validierung:Ja");
	ValidateMap.put(txt_Port,"Port:Ja");
	ValidateMap.put(txt_Database,"Keine_Validierung:Ja");
	ValidateMap.put(txt_User,"Keine_Validierung:Ja");
	ValidateMap.put(txt_pass,"Keine_Validierung:Ja");

	if(sw_import.getValue() == true)
	{
		ValidateMap.put(cb_import_abg,"Keine_Validierung:Ja");
	}
	
	
	}

	 public boolean Validate_Pruefung()
	 {
		 
		 val_checker4 val = new val_checker4(ValidateMap);
		 
		 if(val.Is_Valid() == true)
		 {
			 return true;
		 }else
		 {
			 return false;
		 }
		 
	 }

}
