package archenoah.web.normal.main.Menuepunkte.Standard.Info.Releaseinfo.Form;

import archenoah.config.CMS_Config_Std;
import archenoah.lib.tool.comunication.dbclass.DBClass;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

public class frm_release_info extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_4;
	@AutoGenerated
	private RichTextArea rta_release_info;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	
	private MenuItem selectedItem;
	
	private Window Realease_info;
	
	public frm_release_info(MenuItem Arg_selectedItem) {
		buildMainLayout();
		
		selectedItem = Arg_selectedItem;
		Aufbau_Window();
	
		Fill_Form();
		rta_release_info.setReadOnly(true);

		// TODO add user code here
	}

	
	
	private void Fill_Form()
	{
		CMS_Config_Std std = CMS_Config_Std.getInstance();
		DBClass db = new DBClass();
		db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cms_einstelungen_archenoah");
		db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CEA_RELEASE_INFO");
		db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cms_einstelungen_archenoah", "CEA_ID", "=", "1", "");
		Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();
		
		for (Object ItemIda : con.getItemIds()) {
        //UserId = (int) result.getItem(ItemIda).getItemProperty(this.Spalte_ID).getValue;
			
			
			rta_release_info.setValue( (String) con.getItem(ItemIda).getItemProperty("CEA_RELEASE_INFO").getValue());
          // 
		}
		
	}
	
	
	//************Window******************/
		private void Aufbau_Window()
		{
			Realease_info = new Window(selectedItem.getText());
			Realease_info.setIcon(selectedItem.getIcon());
			Realease_info.setModal(true);
			Realease_info.setResizable(false);
			Realease_info.setContent(mainLayout);
			Realease_info.center();
			Realease_info.setDraggable(false);
			Realease_info.setClosable(true);
			Realease_info.setHeight("500px");
			Realease_info.setWidth("500px");	
			UI.getCurrent().getUI().addWindow(Realease_info);
			
		
		}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_4
		horizontalLayout_4 = buildHorizontalLayout_4();
		mainLayout.addComponent(horizontalLayout_4);
		mainLayout.setComponentAlignment(horizontalLayout_4, new Alignment(48));
		
		return mainLayout;
	}



	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_4() {
		// common part: create layout
		horizontalLayout_4 = new HorizontalLayout();
		horizontalLayout_4.setImmediate(false);
		horizontalLayout_4.setWidth("100.0%");
		horizontalLayout_4.setHeight("100.0%");
		horizontalLayout_4.setMargin(false);
		
		// rta_release_info
		rta_release_info = new RichTextArea();
		rta_release_info.setImmediate(false);
		rta_release_info.setWidth("90.0%");
		rta_release_info.setHeight("90.0%");
		horizontalLayout_4.addComponent(rta_release_info);
		horizontalLayout_4.setComponentAlignment(rta_release_info,
				new Alignment(48));
		
		return horizontalLayout_4;
	}

}
