package archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.servicetasking.form;

import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.joda.time.LocalDate;
import org.joda.time.LocalDateTime;
import org.tepi.filtertable.FilterTable;

import archenoah.lib.custom.ComponentIterator;
import archenoah.lib.custom.MyUtils;
import archenoah.lib.custom.TableFilterGenerator;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.tool.comunication.dbclass.DBClass.CustomQuery;
import archenoah.lib.vaadin.Components.ClickMenuBar.ClickCommand;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Tab_Menue_Item;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Window_Button;
import archenoah.lib.vaadin.Components.table.DataviewGenerator;
import archenoah.lib.vaadin.Components.table.FilteringTableUpdater;
import archenoah.lib.vaadin.Components.table.RowGenerators.HtmlLabelColumnGenerator;
import archenoah.lib.vaadin.CustomConverterFactorys.StringSqlTimestampConverter;
import archenoah.lib.vaadin.Language.i18n.I18nCB;
import archenoah.lib.vaadin.Language.i18n.I18nConverter;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalMessages;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.lib.vaadin.MenuBerechtigung.Rechteholen;
import archenoah.lib.vaadin.resources.Icons;
import archenoah.web.normal.UserInfo.UserData;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.classes.PatientHistoryToggle;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.classes.PatientHistoryToggle.ToggleListener;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.servicetasking.classes.I18nSTStatusConverter;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.servicetasking.classes.ServiceTaskingNew;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.servicetasking.classes.ServiceTaskingNew.SaveListener;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.tools.ProjectParams;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.tools.ProjectParams.Params;

import com.google.common.base.Joiner;
import com.google.common.collect.Iterables;
import com.google.gwt.thirdparty.guava.common.base.Strings;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Container.ItemSetChangeEvent;
import com.vaadin.data.Container.ItemSetChangeListener;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.event.UIEvents.PollEvent;
import com.vaadin.event.UIEvents.PollListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.shared.ui.datefield.Resolution;
import com.vaadin.ui.AbstractComponent;
import com.vaadin.ui.AbstractField;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.Command;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TwinColSelect;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.Window.CloseEvent;
import com.vaadin.ui.Window.CloseListener;

import de.steinwedel.messagebox.ButtonId;
import de.steinwedel.messagebox.MessageBoxListener;


@SuppressWarnings({"serial", "rawtypes", "unchecked"})
public class ServiceTaskingDataView extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private HorizontalLayout mainLayout;

    @AutoGenerated
    private VerticalLayout mainContainer;

    @AutoGenerated
    private FilterTable tbl_data;

    @AutoGenerated
    private HorizontalLayout globalFilterContainer;

    @AutoGenerated
    private HorizontalLayout filterStatusLayout;

    @AutoGenerated
    private TwinColSelect filterStatus;

    @AutoGenerated
    private CheckBox filterStatusEnabled;

    @AutoGenerated
    private HorizontalLayout filterProjectLayout;

    @AutoGenerated
    private TwinColSelect filterProject;

    @AutoGenerated
    private CheckBox filterProjectEnabled;

    @AutoGenerated
    private HorizontalLayout filterMonthLayout;

    @AutoGenerated
    private PopupDateField filterMonth;

    @AutoGenerated
    private CheckBox filterMonthEnabled;

    @AutoGenerated
    private VerticalLayout menuSpacer;

    @AutoGenerated
    private MenuBar men_frm;

    

    

    

    

	

	

	

	

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */

    /**************** --> Allgemein <--- ********************/
    // Datenbank
    private Map<Object, String> componentMap;
    private FilteringTableUpdater tableUpdater = null;

    // Berrechtigung
    private int ACC_ID;

    private int permRead;
    private int permCreate;
    private int permUpdate;
    private int permDelete;

    private MenuItem tmpMenu = null;

    private Button tmpButton = null;
    /******************************************************/
    /**************** --> Tabsheetvars <--- *****************/
    private TabSheet tab = null;

    /******************************************************/
    /**************** --> Windowvars <--- *******************/
    private Window win = null;
    /******************************************************/

    private DetachListener onDetach = null;

    /******************* -> Menüpunkte <- ********************/
    private MenuBar.MenuItem btn_create;
    private MenuBar.MenuItem btn_update;
    private MenuBar.MenuItem btn_read;
    private MenuBar.MenuItem btn_delete;
    private MenuBar.MenuItem btn_filter;
    private MenuBar.MenuItem btn_RegionalManager;
    private MenuBar.MenuItem btn_ProjectManager;
    
    private PatientHistoryToggle patientHistory;
    private Integer patientId; 
    private boolean deferTableUpdates;
    
    /*******************************************************/
    /******************* --> Custom <--- ********************/
    /******************************************************/

    private Boolean firstFilter = true;
    private PollListener pollListener = null;
    
    enum Status {}
    
    private Boolean regionalManagerView = false;
    private Boolean projectManagerView = false;
    private ProjectParams projectParams = new ProjectParams();
    private String multiString = null;
    /************ ----->Einstellungen<-- ********************/
//    private final String formIdLng = "601";
    private final String formIdPerm = "601";
    private final String winHeight = "600px";
    private final String winWidth = "900px";


    /******************************************************/

    private final String tableIdCol = "ST_ID";
    
    //TASK cols
    private final Object[] tableColsAll = new Object[] {"ST_ID", "project", "rx", "patient", "PSL_COUNTYCODE", "nurse", "ST_ID_TYPE", "ST_DATE", "ST_CAPTION", "status"};
    //use custom Cols when needed
    private Object[] tableColsDefault = tableColsAll;
    //use custom Cols when needed
    private final Object[] tableColsFilter = tableColsDefault;
    private Object[] tableColsActive = tableColsDefault;
    
    private I18nManager i18n;

    private I18nSTStatusConverter statusConverter;
    
    private final static class caption extends I18nCB {
        static final I18nCB regionalManagerOktrue = set();
        static final I18nCB regionalManagerOkfalse = set();
        static final I18nCB regionalManager = set();
        static final I18nCB projectManager = set();
        static final I18nCB regionalManagerEnable = set();
        static final I18nCB regionalManagerDisable = set();
    }
    
    /******************************************************/

    public ServiceTaskingDataView(MenuItem Arg_Menü) {
        tmpMenu = Arg_Menü;
    }

    public ServiceTaskingDataView(Button Arg_btn) {
        tmpButton = Arg_btn;
    }

    /***************************** ---> Feste Funtionen<--- **************************************/

    /********* INIT-Window ************/
    public void init() {
        
        Standard_Init();

        if (tmpMenu != null) {
            String Recourcename = tmpMenu.getIcon().toString();
            Recourcename = Recourcename.substring(0, Recourcename.length() - 12) + "white-16.png";

            Build_Window_Button bwb = new Build_Window_Button(tmpMenu.getText(), mainLayout, winHeight, winWidth,
                    new ThemeResource(Recourcename));
            win = bwb.ReturnWindow();
        }
        if (tmpButton != null) {
            Build_Window_Button bwb = new Build_Window_Button(tmpButton.getCaption(), mainLayout, winHeight, winWidth,
                    tmpButton.getIcon());
            win = bwb.ReturnWindow();
        }

        win.addDetachListener(onDetach);

    }
    
    public Window getWindow(){
    	return win;
    }
    
    public TabSheet getTabSheet(){
    	return tab;
    }
    
    public void init(TabSheet Arg_tab) {

        Standard_Init();
        tab = Arg_tab;
        if (tmpMenu != null) {
            new Build_Tab_Menue_Item(Arg_tab, tmpMenu.getText(), mainLayout, tmpMenu.getIcon());
        }
        if (tmpButton != null) {
            new Build_Tab_Menue_Item(Arg_tab, tmpButton.getCaption(), mainLayout, tmpButton.getIcon());
        }

        tab.getSelectedTab().addDetachListener(onDetach);
    }

    /********* Init-Standard ************/
    private void Standard_Init() {
        buildMainLayout();
        i18n = new I18nManager(this);
        
        registerComponents();
        
        generateMenu();

        setMenuPermissions();

        updateTable();
        tbl_data.setSortContainerPropertyId(tableIdCol);
        tbl_data.setSortAscending(true);
        tbl_data.sort();
        statusConverter = new I18nSTStatusConverter();
        configureTable();
        configureComponents();

        setGlobalFilterMonth();
        
        updateTable();
        
        setupListenersAndDetachEvent();
        
        i18n.refresh();
    }
    
    // register components for lng and validation tools
    private void registerComponents(){
    	componentMap = new HashMap<Object, String>();
    	new ComponentIterator(mainContainer).createMap(componentMap);
    }

    
    private void setupListenersAndDetachEvent() {
        pollListener = new PollListener() {

            @Override
            public void poll(PollEvent event) {
                if(tab.isRendered(mainLayout)  && filterMonthEnabled.getValue()){
                    updateTable();
                }
            }
        };

        UI.getCurrent().getUI().addPollListener(pollListener);

        onDetach = new DetachListener() {

            @Override
            public void detach(DetachEvent event) {
                UI.getCurrent().getUI().removePollListener(pollListener);
            }
        };
    }
    
    @SuppressWarnings("unused")
    public void setPermissionsFromDatabase() {
        if (formIdPerm == "") {
            System.out.println("Form Einstellung Fehlt: Berechtigung");
            return;
        }

        Rechteholen r = new Rechteholen(UserData.get().getUserId() + "");
        String[][] perms = r.Datenholen();

        for (int i = 0; i < perms.length; i++) {
            if (perms[i][0].equals(formIdPerm) == true) {

                permRead = Integer.valueOf(perms[i][3]);
                permUpdate = Integer.valueOf(perms[i][4]);
                permCreate = Integer.valueOf(perms[i][6]);
                permDelete = Integer.valueOf(perms[i][5]);
                
            }
        }
    }

    public void setPermissions(int create, int read, int update, int delete) {

        permCreate = create;
        permRead = read;
        permUpdate = update;
        permDelete = delete;

    }

    private void setMenuPermissions() {
        Boolean c = (permCreate == 1);
        Boolean r = (permRead == 1);
        Boolean u = (permUpdate == 1);
        Boolean d = (permDelete == 1);

        btn_create.setEnabled(c);
        btn_create.setVisible(c);

        btn_read.setEnabled(r);
        btn_read.setVisible(r);

        btn_update.setEnabled(u);
        btn_update.setVisible(u);

        btn_delete.setEnabled(d);
        btn_delete.setVisible(d);
    }

    /************ -><- ******************/

    /***************** Comands *********************/
    
    CloseListener closeListener = new CloseListener() {
		
		@Override
		public void windowClose(CloseEvent e) {
			updateTable(true);
		}
	};
    
	private String getSelectedValue(){
		return Integer.toString(getSelectedId());
	}
	
    private Integer getSelectedId(){
        Integer id = null;
        try {
            id = (Integer) tbl_data.getContainerProperty(((Collection)tbl_data.getValue()).toArray()[0], tableIdCol).getValue();
        } catch (Exception e) {
        }
        return id;
    }
    
    private Item getSelectedItem() {
        Item item = null;
        try {
            item = tbl_data.getItem(((Collection)tbl_data.getValue()).toArray()[0]);
        } catch (Exception e) {
        }
        return item;
    }
    
    private Collection<Integer> getSelectedIds(){
        Collection<Integer> vals = (Collection<Integer>) tbl_data.getValue();
        
        ArrayList<Integer> ids = new ArrayList<Integer>();
        
        for (Integer row : vals) {
            ids.add((Integer) tbl_data.getContainerProperty(row, tableIdCol).getValue());
        }
        
        return ids;
    }
	
    //TASK Commands are here
    public Command cmd_btn_add = new ClickCommand() {
        
        final ClickCommand cc = this;
        
        @Override
        public void menuClicked(MenuItem selectedItem) {
            
            ServiceTaskingNew creator = new ServiceTaskingNew();
            creator.addSaveListener(new SaveListener() {
                
                @Override
                public void onSave(Integer pid) {

                    if (pid == null) {
                        return;
                    }

                    ServiceTaskingInsertEdit pie = new ServiceTaskingInsertEdit(btn_update, Integer.toString(pid));
                    pie.setPermissions(permCreate, permRead, permUpdate, permDelete);
                    pie.init();
                    pie.setResetEnabled(true);
                    pie.getWindow().addCloseListener(closeListener);
                    pie.getWindow().setClosable(false);

                    cc.setWindow(pie.getWindow());
                    cc.setParent(men_frm);

                }
            });
 
            
        }
    };
    
    public Command cmd_btn_read = new ClickCommand() {
        @Override
        public void menuClicked(MenuItem selectedItem) {

            if(tbl_data.getValue() == null){
                I18nManager.global(I18nGlobalNotifiers.no_entry_selected);
                return;
            }
            
            ServiceTaskingInsertEdit pie = new ServiceTaskingInsertEdit(selectedItem, getSelectedValue());
        	pie.setPermissions(0, permRead, 0, 0);
        	pie.init();
        	this.setWindow(pie.getWindow());
            this.setParent(men_frm);

        }
    };
    
    public Command cmd_btn_edit = new ClickCommand() {
        @Override
        public void menuClicked(MenuItem selectedItem) {
            
            if(tbl_data.getValue() == null){
                I18nManager.global(I18nGlobalNotifiers.no_entry_selected);
                return;
            }
            
            ServiceTaskingInsertEdit pie = new ServiceTaskingInsertEdit(selectedItem, getSelectedValue());
            if(!regionalManagerView && projectManagerView) {
                pie.setPermissions(0, 1, 0, 0);
            }else {
                pie.setPermissions(permCreate, permRead, permUpdate, permDelete);
            }
        	pie.setRegionalManagerEnabled(regionalManagerView);
        	pie.init();
        	pie.getWindow().addCloseListener(closeListener);
        	this.setWindow(pie.getWindow());
            this.setParent(men_frm);
        }
    };

    public Command cmd_btn_del = new Command() {
        @Override
        public void menuSelected(MenuItem selectedItem) {
            
            if(tbl_data.getValue() == null){
                I18nManager.global(I18nGlobalNotifiers.no_entry_selected);
                return;
            }
            
            deleteData(getSelectedIds());

        }
    };

    public Command cmd_btn_filter = new Command() {
        @Override
        public void menuSelected(MenuItem selectedItem) {

            if (firstFilter) {
                tbl_data.setFilterBarVisible(true);
                tbl_data.setFilterBarVisible(false);
                firstFilter = false;
            }
            tbl_data.setFilterBarVisible(!tbl_data.isFilterBarVisible());
            
            if(!tbl_data.isFilterBarVisible()){
                tbl_data.clearFilters();
            }
            
            tableColsActive = tbl_data.isFilterBarVisible() ? tableColsFilter : tableColsDefault;
            if(tableColsActive.length > 0){
            	tbl_data.setVisibleColumns(tableColsActive);
            }

        }
    };
    
    public Command cmd_btn_regionalManagerView = new Command() {
        @Override
        public void menuSelected(MenuItem selectedItem) {

            regionalManagerView = !regionalManagerView;
            updateTable();
            toggleRlCaption();
        }
        
    };
    
    public Command cmd_btn_projectManagerView = new Command() {
        @Override
        public void menuSelected(MenuItem selectedItem) {

            projectManagerView = !projectManagerView;
            updateTable();
            toggleRlCaption();
        }
        
    };
    
    private void toggleRlCaption() {
        btn_RegionalManager.setText(i18n.get(caption.regionalManager) + " "
            + i18n.get((regionalManagerView ? caption.regionalManagerDisable : caption.regionalManagerEnable)));
        btn_ProjectManager.setText(i18n.get(caption.projectManager) + " "
            + i18n.get((projectManagerView ? caption.regionalManagerDisable : caption.regionalManagerEnable)));
    }
    
    /******************************************/

    public void setGlobalFilterMonth(Date date){
        LocalDate ld = new LocalDate(date);
        filterMonthEnabled.setValue(true);
        filterMonth.setValue(new LocalDate(ld.getYear(), ld.getMonthOfYear(), 1).toDate());
    }
    
    public void setGlobalFilterMonth(){
        setGlobalFilterMonth(new Date());
    }
    

    /*********** Gen Menüs *************/
    private void generateMenu() {

        btn_create = men_frm.addItem("FRM_ADD", Icons.White.add_16, cmd_btn_add);
        btn_update = men_frm.addItem("FRM_EDIT", Icons.White.edit_16, cmd_btn_edit);
        btn_read = men_frm.addItem("FRM_READ", Icons.White.perm_lesen_16, cmd_btn_read);
        btn_delete = men_frm.addItem("FRM_DEL", Icons.White.delete_16, cmd_btn_del);
        
        btn_filter = men_frm.addItem("FRM_FILTER", Icons.White.filter_16, cmd_btn_filter);
        
        btn_RegionalManager = men_frm.addItem("FRM_REGIONAL_MANAGER", Icons.White.krankenschwester_16, cmd_btn_regionalManagerView);
        btn_ProjectManager = men_frm.addItem("FRM_PROJECT_MANAGER", Icons.White.krankenschwester_16, cmd_btn_projectManagerView);
        
    }
    
    private void configureComponents(){
       
    	for (Entry<Object, String> entry : componentMap.entrySet()) {
    		AbstractComponent field = (AbstractComponent) entry.getKey();
    		
			field.setImmediate(true);
			
			
			if(field instanceof ComboBox){
				((ComboBox)field).setFilteringMode(FilteringMode.CONTAINS);
			}
			
		}
        
    	btn_RegionalManager.setVisible(UserData.get().getRegionalManager().isRegionalManager());
    	btn_ProjectManager.setVisible(MyUtils.getUserData().getProjectManager().forProjectCode("SA"));
    	toggleRlCaption();
    	
    	 filterMonthEnabled.setValue(false);
         filterMonthEnabled.setImmediate(true);
         filterMonth.setResolution(Resolution.MONTH);
         filterMonth.setDateFormat("MMM yyyy");
         filterMonth.setEnabled(false);
         
         filterMonthEnabled.addValueChangeListener(new ValueChangeListener() {
             
             @Override
             public void valueChange(ValueChangeEvent event) {
                 
                 Boolean enabled = (Boolean)event.getProperty().getValue();
                 filterMonth.setEnabled(enabled);
                 if(enabled && filterMonth.getValue() == null){
                     LocalDate ld = new LocalDate();
                     filterMonth.setValue(new LocalDate(ld.getYear(), ld.getMonthOfYear(), 1).toDate());
                 }else if(!enabled){
                     filterMonth.setValue(null);
                 }
                 
             }
         });
         
         filterMonth.setImmediate(true);
         filterMonth.addValueChangeListener(new ValueChangeListener() {
             
             @Override
             public void valueChange(ValueChangeEvent event) {
                 
                 updateTable(true);
                 
             }
         });
         
         // PROJECTPICKER
         filterProjectEnabled.setValue(true);
         filterProjectEnabled.setImmediate(true);
         filterProject.setContainerDataSource(dbGetProjectValues());
         filterProject.setItemCaptionPropertyId("PSLV_NAME");
         
         filterProject.setValue(filterProject.getItemIds());
         
         filterProjectEnabled.addValueChangeListener(new ValueChangeListener() {
             
             @Override
             public void valueChange(ValueChangeEvent event) {
                 
                 Boolean enabled = (Boolean)event.getProperty().getValue();
                 filterProject.setEnabled(enabled);
                 if(enabled){
                     filterProject.setValue(filterProject.getItemIds());
                 }
                 updateTable(true);
                 
             }
         });
         
         filterProject.setImmediate(true);
         filterProject.addValueChangeListener(new ValueChangeListener() {
             
             @Override
             public void valueChange(ValueChangeEvent event) {
                 
                 Collection val = (Collection) filterProject.getValue();
                 filterProjectEnabled.setValue(val.size() != 0);
                 updateTable(true);
                 
             }
         });
         
         // STATUSPICKER
         filterStatusEnabled.setValue(true);
         filterStatusEnabled.setImmediate(true);
         statusConverter.attachDatasource(filterStatus);
        
         preselectStatusFilter();
         
         filterStatusEnabled.addValueChangeListener(new ValueChangeListener() {
             
             @Override
             public void valueChange(ValueChangeEvent event) {
                 
                 Boolean enabled = (Boolean)event.getProperty().getValue();
                 filterStatus.setEnabled(enabled);
                 if(enabled){
                     preselectStatusFilter();
                 }
                 updateTable(true);
                 
             }
         });
         
         filterStatus.setImmediate(true);
         filterStatus.addValueChangeListener(new ValueChangeListener() {
             
             @Override
             public void valueChange(ValueChangeEvent event) {
                 
                 Collection val = (Collection) filterStatus.getValue();
                 filterStatusEnabled.setValue(val.size() != 0);
                 updateTable(true);
                 
             }
         });
        
         patientHistory = new PatientHistoryToggle("ST_ID_PATIENT", "patient", men_frm, tbl_data);
         patientHistory.setToggleListener(new ToggleListener() {
            
            @Override
            public void onToggle(Integer pid) {
                patientId = pid;
                
                deferTableUpdates(true);
                boolean enableFilters = (pid == null);
                filterMonthEnabled.setValue(enableFilters);
                filterProjectEnabled.setValue(enableFilters);
                filterStatusEnabled.setValue(enableFilters);
                deferTableUpdates(false);

                updateTable(true);
                toggleMenuItems();
            }
        });
        toggleMenuItems();
    }
    
    private void deferTableUpdates(boolean defer) {
        this.deferTableUpdates = defer;
    }
    
    private void preselectStatusFilter(){
        // Preselect a few items
        HashSet<Integer> preselected = new HashSet<Integer>();
        Collections.addAll(preselected, 1, 2, 3, 4);
        filterStatus.setValue(preselected);
    }
    
    private ArrayList<AbstractField> getActiveGlobalFilters(){
        ArrayList<AbstractField> al = new ArrayList<AbstractField>();
        
        if(filterMonth.getValue() != null){
            al.add(filterMonth);
        }
        
        if(filterProjectEnabled.getValue() && ((Collection) filterProject.getValue()).size() > 0){
            al.add(filterProject);
        }
        
        if(filterStatusEnabled.getValue() && ((Collection) filterStatus.getValue()).size() > 0){
            al.add(filterStatus);
        }
        
        return al;
    }
    
    private Boolean hasGlobalFilters(ArrayList a){
        
        return (a.size() > 0);
        
    }
    
    private Boolean hasGlobalFilters(){
        
        return hasGlobalFilters(getActiveGlobalFilters());
        
    }
    
    /*************************** Config TBL ********************/

    private void configureTable() {
        tbl_data.setSelectable(true);
        tbl_data.setFilterOnDemand(false);
        tbl_data.setMultiSelect(true);
        tbl_data.setImmediate(true);
        tbl_data.setColumnCollapsingAllowed(false);
        tbl_data.setFooterVisible(true);
        tbl_data.setPageLength(1);
        try {
        	if(tableColsDefault.length > 0){
        		tbl_data.setVisibleColumns(tableColsDefault);
        	}
		} catch (Exception e) {

		}
        
        if(tbl_data.size() > 0){
            
            StringSqlTimestampConverter date = new StringSqlTimestampConverter();
            date.setDateFormat(DateFormat.SHORT);
            
            StringSqlTimestampConverter time = new StringSqlTimestampConverter();
            time.setDateFormat(DateFormat.SHORT);
            time.setTimeFormat(DateFormat.SHORT);
            
            tbl_data.setConverter("ST_CREATED", time);
            tbl_data.setConverter("ST_UPDATED", time);
            tbl_data.setConverter("ST_DATE", date);
            
            I18nConverter typeConverter = new I18nConverter("cust_protokoll_servicetasking_master_types", "STXT_ID", "STXT_KEY");
            tbl_data.setConverter("ST_ID_TYPE", typeConverter);
            
            tbl_data.addGeneratedColumn("rx", new HtmlLabelColumnGenerator("rx", "rx_raw"));
            
        }
        
        DataviewGenerator gen = new DataviewGenerator();
        gen.addConverter("status", statusConverter);
        gen.attach(tbl_data);
        
        tableUpdater = new FilteringTableUpdater(tbl_data);
        
        tbl_data.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                toggleMenuItems();
                
            }
        });
        toggleMenuItems();

        tbl_data.addItemSetChangeListener(new ItemSetChangeListener() {
            @Override
            public void containerItemSetChange(ItemSetChangeEvent event) {
                tbl_data.setValue(null);
            }
        });
        
        for (Object col : tableColsAll) {
        	
        	try {
        		tbl_data.setColumnExpandRatio(col, 1);
			} catch (Exception e) {
				
			}
        		
		}
        
        tbl_data.setColumnExpandRatio("ST_ID", 0);
        tbl_data.setColumnExpandRatio("patient", 2);
        tbl_data.setColumnExpandRatio("nurse", 2);
        tbl_data.setColumnExpandRatio("ST_CAPTION", 4);
        
        tbl_data.setFilterGenerator(new TableFilterGenerator(tbl_data));
        
    }

    private void toggleMenuItems(){
        
        Collection values = (Collection) tbl_data.getValue();
        
        Boolean crud = (!values.isEmpty() && values.size() == 1);
        Boolean multi = !values.isEmpty();
        boolean hasPatient = patientId != null;
        
//        btn_create.setEnabled(crud && !hasPatient);
        btn_update.setEnabled(crud && !hasPatient);
        btn_read.setEnabled(crud);
        btn_delete.setEnabled((crud || multi) && !hasPatient);
        
        if(patientHistory != null) {
            patientHistory.setEnabled(crud || hasPatient);
        }
        
//        btn_pdf.setEnabled(multi);
        
//        btn_locate.setEnabled(crud);
    }

    /*************************** Database ********************/
    
    /********************************/
    
    
    private void updateTable(){
        updateTable(false);
    }
    
    private void updateTable(Boolean ignoreFilter) {
        
        if(deferTableUpdates) {
            return;
        }
        
        if (ignoreFilter || !tbl_data.isFilterBarVisible()) {
            dbGetContainer();
            try{
            	if(tableColsDefault.length > 0){
            		tbl_data.setVisibleColumns(tableColsActive);
            	}
            }catch(Exception e){
                
            }
        }
        
        tbl_data.setColumnFooter(Iterables.getLast(Arrays.asList(tbl_data.getVisibleColumns())), "Σ " + tbl_data.size());
        
    }
    
    private void deleteData(final Collection<Integer> ids){
        
        I18nManager.global(I18nGlobalMessages.confirm_delete, new MessageBoxListener() {
            
            @Override
            public void buttonClicked(ButtonId arg0) {
                if(ButtonId.YES == arg0) {
                    dbDeleteData(ids);
                }
            }
        });
    }
    
    private Container dbGetProjectValues() {
        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("PSLV_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("PSLV_NAME");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_projekte_stammdaten_liste");
        
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_projekte_stammdaten_liste", "PSLV_CODE", "=", "'SA'", "");
        
        Container con = MyUtils.convertIndex(db.DB_Data_Get.DB_SEND_AND_GET_Container(), "PSLV_ID");
        db.DB_Data_Get.connclose();
        
        return con;

    }
    
    //TASK dbget
	private void dbGetContainer() {

	    CustomQuery q = new DBClass().CustomQuery;
        String sql = "select"
             + "\n " + "        cust_protokoll_servicetasking.*"
             + "\n " + "        , CONCAT(n.AUL_VORNAME, ' ', n.AUL_NAME) as nurse"
             + "\n " + "        , CONCAT(PSA_NAME, ' ', PSL_VORNAME, ' ', PSL_NAME) as patient"
             + "\n " + "        , PSL_COUNTYCODE"
             + "\n " + "        , PSLV_NAME as project"
             + "\n " + "        , ST_STATUS as `status`"
             + "\n " + "        , VH_PROJEKT_ID"
             + "\n " + "        , VH_ID"
             + "\n " + "        , GROUP_CONCAT(CONCAT(PP_PRODUCT, ': ', balance) SEPARATOR '<br />') as rx_raw"
             + "\n " + "from"
             + "\n " + "    cust_protokoll_servicetasking"
             + "\n " + "    left join cust_verk_haupt on ST_VH_ID = VH_ID"
             + "\n " + "    left join cust_projekte_stammdaten_liste on VH_PROJEKT_ID = PSLV_ID"
             + "\n " + "    "
             + "\n " + "    left join cust_patient_stammdaten_liste on ST_ID_PATIENT = PSL_ID"
             + "\n " + "    left join cust_patient_stammdaten_anrede on PSL_ANREDE = PSA_ID"
             + "\n " + "    "
             + "\n " + "    left join cust_schulung_status on ST_STATUS = SS_PROZESS and SS_CODE = 'SA'"
             + "\n " + "    "
             + "\n " + "    left join cust_krankenschwester_stammdaten_ks on ST_ID_NURSE = KSK_ID"
             + "\n " + "    left join cms_auth_stammdaten_user as n on KSK_U_ID = AUL_ID"
             + "\n " + "    left join cust_prescriptions_products on VH_PROJEKT_ID = PP_ID_PROJECT"
             + "\n " + "    left join view_balance_rx on PP_ID = PB_ID_PRODUCT and ST_ID_PATIENT = PB_ID_PATIENT";
        
        // Filter
        
        String glue = "";
        
        String where = "";
        
        // by nurse id
        if (UserData.get().getNurse().isNurse() && patientId == null) {
            
            if(UserData.get().getPharmacy().isPharmacy()) {
                glue = " OR ";
            }else if(hasGlobalFilters()){
                glue = " AND ";
            }
            
            if(regionalManagerView) {
                // do nothing
            }else if(projectManagerView){
                // filter by allowed pids
                String ids = Joiner.on(",").join(MyUtils.getUserData().getProjectManager().getProjectIdsForCode("SA"));
                where += "VH_PROJEKT_ID IN (" + ids + ")" + glue;
            }else {
                // filter by nurse
                if(multiString == null) { //only generate once after init
                    Set<Integer> multiSet = projectParams.getProjectsFor(Params.multi_nurse).keySet();
                    if(multiSet != null && multiSet.size() > 0) {
                        multiString = " OR VH_PROJEKT_ID IN (" + Joiner.on(",").join(multiSet) + ")";
                    }
                }
                where += "\n " + "(ST_ID_NURSE = " + UserData.get().getNurse().getNurseId() + multiString + ")" + glue;
            }
            

        }
        
        //show pharmacy tasks
        if(UserData.get().getPharmacy().isPharmacy() && patientId == null) {
            if(hasGlobalFilters()){
                glue = " AND ";
            }
            where += "\n " + "ST_ID_TYPE = (select STXT_ID from cust_protokoll_servicetasking_master_types where STXT_KEY = 'servicetype_pharmacy') " + glue;
        }
        
        //patientHistory if set
        if(patientId != null) {
            if(hasGlobalFilters()){
                glue = " AND ";
            }
            where += "\n " + "ST_ID_PATIENT = " + patientId + glue;
        }
        
        ArrayList<AbstractField> filterList = getActiveGlobalFilters(); 
        
        if(filterMonth.getValue() != null){
            
            java.sql.Timestamp sqlDateFrom = new java.sql.Timestamp(filterMonth.getValue().getTime());
            java.sql.Timestamp sqlDateUntil = new java.sql.Timestamp(new LocalDateTime(filterMonth.getValue()).plusMonths(1).minusMillis(1).toDate().getTime());
            
            filterList.remove(filterMonth);
            glue = hasGlobalFilters(filterList) ? " AND " : "";
            
            where += "\n " + "((ST_DATE between " + "'" + sqlDateFrom.toString() + "' and '" + sqlDateUntil.toString() + "') OR "
                + "(ST_DATE IS NULL AND ST_CREATED between " + "'" + sqlDateFrom.toString() + "' and '" + sqlDateUntil.toString() + "')) " + glue;
        }
        
        if(filterProjectEnabled.getValue() && ((Collection) filterProject.getValue()).size() > 0){
            
            filterList.remove(filterProject);
            glue = hasGlobalFilters(filterList) ? " AND " : "";
            
            Collection<Integer> coll = ((Collection<Integer>) filterProject.getValue());
            
            where += "\n " + "VH_PROJEKT_ID in ("+ Joiner.on(",").join(coll) + ")" + glue;
        }
        
        if(filterStatusEnabled.getValue() && ((Collection) filterStatus.getValue()).size() > 0){
            
            filterList.remove(filterStatus);
            glue = hasGlobalFilters(filterList) ? " AND " : "";
            
            Collection<Integer> coll = ((Collection<Integer>) filterStatus.getValue());
            
            where += "\n " + "ST_STATUS in ("+ Joiner.on(",").join(coll) + ") OR ST_STATUS IS NULL" + glue;
        }
        
        
        
        if(!where.equals("")) {
            sql += "\n where " + where;
        }
        
        sql += "\n group by ST_ID";
        
        q.setSqlString(sql);
//        q.db.debugNextQuery(true);
        
        try {
        	Container container = q.query();
            
        	if (tableUpdater != null) {
                tableUpdater.updateTable(container);
            } else {
                tbl_data.setContainerDataSource(container);
            }
        	
		} catch (Exception e) {
			System.out.println("exception!");
			UI.getCurrent().getUI().removePollListener(pollListener);
		}
        
    }
    
    private String generateCollectionString(Collection<Integer> ids){
        String in = "";
        String comma = "";
        
        for (Integer integer : ids) {
            in += comma + integer;
            if(Strings.isNullOrEmpty(comma)){
                comma = ", ";
            }
        }
        
        return in;
    }
    
    private void dbDeleteData(Collection<Integer> ids){
    
        DBClass db = new DBClass();
        db.DB_Data_Delete.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_protokoll_servicetasking");
        db.DB_Data_Delete.DB_Filter.DB_WHERE_In("cust_protokoll_servicetasking", tableIdCol, Joiner.on(",").join(ids), "");
        db.DB_Data_Delete.DB_Delete();
    
        I18nManager.global(I18nGlobalNotifiers.entry_deleted);
        
        updateTable(true);

        
    }
    
    private Integer dbCreate() {
        
        if(tbl_data.getValue() == null) {
            return null;
        }
        
        Item item = getSelectedItem();
        
        ArrayList<Integer> generatedKeys = new ArrayList<Integer>();
        
        Integer vhId = MyUtils.getValueFromItem(item, "ST_VH_ID", Integer.class);
        Integer nurseId = MyUtils.getValueFromItem(item, "ST_ID_NURSE", Integer.class);
        Integer patientId = MyUtils.getValueFromItem(item, "ST_ID_PATIENT", Integer.class);

        
        CustomQuery q = new DBClass().CustomQuery;
        String sql = "INSERT INTO `cust_protokoll_servicetasking` (ST_VH_ID, ST_ID_NURSE, ST_ID_PATIENT) VALUES"
             + "\n " + "("
             + MyUtils.formatSqlValue(vhId) + ", "
             + MyUtils.formatSqlValue(nurseId) + ", "
             + MyUtils.formatSqlValue(patientId)
                 + ");";
        q.setSqlString(sql);
//        q.db.debugNextQuery(true);
        
        q.update(false, generatedKeys);
        
        return generatedKeys.iterator().next();
    }
    
    @AutoGenerated
    private HorizontalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new HorizontalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // mainContainer
        mainContainer = buildMainContainer();
        mainLayout.addComponent(mainContainer);
        mainLayout.setExpandRatio(mainContainer, 1.0f);
        mainLayout.setComponentAlignment(mainContainer, new Alignment(20));
        
        return mainLayout;
    }

    @AutoGenerated
    private VerticalLayout buildMainContainer() {
        // common part: create layout
        mainContainer = new VerticalLayout();
        mainContainer.setImmediate(false);
        mainContainer.setWidth("100.0%");
        mainContainer.setHeight("100.0%");
        mainContainer.setMargin(true);
        
        // menuSpacer
        menuSpacer = buildMenuSpacer();
        mainContainer.addComponent(menuSpacer);
        
        // globalFilterContainer
        globalFilterContainer = buildGlobalFilterContainer();
        mainContainer.addComponent(globalFilterContainer);
        mainContainer.setComponentAlignment(globalFilterContainer, new Alignment(48));
        
        // tbl_data
        tbl_data = new FilterTable();
        tbl_data.setImmediate(true);
        tbl_data.setWidth("100.0%");
        tbl_data.setHeight("100.0%");
        mainContainer.addComponent(tbl_data);
        mainContainer.setExpandRatio(tbl_data, 1.0f);
        mainContainer.setComponentAlignment(tbl_data, new Alignment(20));
        
        return mainContainer;
    }

    @AutoGenerated
    private VerticalLayout buildMenuSpacer() {
        // common part: create layout
        menuSpacer = new VerticalLayout();
        menuSpacer.setImmediate(false);
        menuSpacer.setWidth("100.0%");
        menuSpacer.setHeight("40px");
        menuSpacer.setMargin(false);
        
        // men_frm
        men_frm = new MenuBar();
        men_frm.setImmediate(false);
        men_frm.setWidth("100.0%");
        men_frm.setHeight("-1px");
        menuSpacer.addComponent(men_frm);
        menuSpacer.setComponentAlignment(men_frm, new Alignment(20));
        
        return menuSpacer;
    }

    @AutoGenerated
    private HorizontalLayout buildGlobalFilterContainer() {
        // common part: create layout
        globalFilterContainer = new HorizontalLayout();
        globalFilterContainer.setImmediate(false);
        globalFilterContainer.setWidth("100.0%");
        globalFilterContainer.setHeight("80px");
        globalFilterContainer.setMargin(false);
        
        // filterMonthLayout
        filterMonthLayout = buildFilterMonthLayout();
        globalFilterContainer.addComponent(filterMonthLayout);
        globalFilterContainer.setComponentAlignment(filterMonthLayout, new Alignment(48));
        
        // filterProjectLayout
        filterProjectLayout = buildFilterProjectLayout();
        globalFilterContainer.addComponent(filterProjectLayout);
        globalFilterContainer.setComponentAlignment(filterProjectLayout, new Alignment(48));
        
        // filterStatusLayout
        filterStatusLayout = buildFilterStatusLayout();
        globalFilterContainer.addComponent(filterStatusLayout);
        globalFilterContainer.setComponentAlignment(filterStatusLayout, new Alignment(48));
        
        return globalFilterContainer;
    }

    @AutoGenerated
    private HorizontalLayout buildFilterMonthLayout() {
        // common part: create layout
        filterMonthLayout = new HorizontalLayout();
        filterMonthLayout.setImmediate(false);
        filterMonthLayout.setWidth("-1px");
        filterMonthLayout.setHeight("-1px");
        filterMonthLayout.setMargin(false);
        filterMonthLayout.setSpacing(true);
        
        // filterMonthEnabled
        filterMonthEnabled = new CheckBox();
        filterMonthEnabled.setCaption("Monatsfilter");
        filterMonthEnabled.setImmediate(false);
        filterMonthEnabled.setWidth("-1px");
        filterMonthEnabled.setHeight("-1px");
        filterMonthLayout.addComponent(filterMonthEnabled);
        filterMonthLayout.setComponentAlignment(filterMonthEnabled, new Alignment(34));
        
        // filterMonth
        filterMonth = new PopupDateField();
        filterMonth.setImmediate(false);
        filterMonth.setWidth("100px");
        filterMonth.setHeight("-1px");
        filterMonthLayout.addComponent(filterMonth);
        filterMonthLayout.setComponentAlignment(filterMonth, new Alignment(33));
        
        return filterMonthLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildFilterProjectLayout() {
        // common part: create layout
        filterProjectLayout = new HorizontalLayout();
        filterProjectLayout.setImmediate(false);
        filterProjectLayout.setWidth("-1px");
        filterProjectLayout.setHeight("-1px");
        filterProjectLayout.setMargin(false);
        filterProjectLayout.setSpacing(true);
        
        // filterProjectEnabled
        filterProjectEnabled = new CheckBox();
        filterProjectEnabled.setCaption("Projektfilter");
        filterProjectEnabled.setImmediate(false);
        filterProjectEnabled.setWidth("-1px");
        filterProjectEnabled.setHeight("-1px");
        filterProjectLayout.addComponent(filterProjectEnabled);
        filterProjectLayout.setComponentAlignment(filterProjectEnabled, new Alignment(34));
        
        // filterProject
        filterProject = new TwinColSelect();
        filterProject.setImmediate(false);
        filterProject.setWidth("-1px");
        filterProject.setHeight("70px");
        filterProjectLayout.addComponent(filterProject);
        filterProjectLayout.setComponentAlignment(filterProject, new Alignment(33));
        
        return filterProjectLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildFilterStatusLayout() {
        // common part: create layout
        filterStatusLayout = new HorizontalLayout();
        filterStatusLayout.setImmediate(false);
        filterStatusLayout.setWidth("-1px");
        filterStatusLayout.setHeight("-1px");
        filterStatusLayout.setMargin(false);
        filterStatusLayout.setSpacing(true);
        
        // filterStatusEnabled
        filterStatusEnabled = new CheckBox();
        filterStatusEnabled.setCaption("Statusfilter");
        filterStatusEnabled.setImmediate(false);
        filterStatusEnabled.setWidth("-1px");
        filterStatusEnabled.setHeight("-1px");
        filterStatusLayout.addComponent(filterStatusEnabled);
        filterStatusLayout.setComponentAlignment(filterStatusEnabled, new Alignment(34));
        
        // filterStatus
        filterStatus = new TwinColSelect();
        filterStatus.setImmediate(false);
        filterStatus.setWidth("-1px");
        filterStatus.setHeight("70px");
        filterStatusLayout.addComponent(filterStatus);
        filterStatusLayout.setComponentAlignment(filterStatus, new Alignment(33));
        
        return filterStatusLayout;
    }
}
