package archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.TicketPreferences.form;

import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;

import archenoah.config.CMS_Config_Std;
import archenoah.lib.custom.ComponentIterator;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.vaadin.Components.Combo.combo;
import archenoah.lib.vaadin.Forms_Builder.Form_Bind;
import archenoah.lib.vaadin.Language.i18n.I18nCB;
import archenoah.lib.vaadin.Language.i18n.I18nConverter;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.OpenTickets.classes.TITYPE;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.ui.AbstractComponent;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;


public class LocationPanel extends CustomComponent{

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	
    @AutoGenerated
    private VerticalLayout mainLayout;
    @AutoGenerated
    private Panel locationContenPanel;
    @AutoGenerated
    private VerticalLayout locationContenPanelLayout;
    @AutoGenerated
    private VerticalLayout locationFieldsLayout;
    @AutoGenerated
    private ComboBox locationType;
    @AutoGenerated
    private TextField locationCity;
    @AutoGenerated
    private TextField locationPlz;
    @AutoGenerated
    private TextField locationStreet;
    @AutoGenerated
    private TextField locationExtended;
    @AutoGenerated
    private TextField locationName;
    @AutoGenerated
    private HorizontalLayout quickSelectLayout;
    @AutoGenerated
    private ComboBox quickSelectPresets;
    @AutoGenerated
    private CheckBox quickSelectEnabled;
    
    
	
    /* **************************** */
    
    private org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(this.getClass());
    
    Map<Object, String> locationMap;
    Map<Object, String> locationDbMap;
    
    CMS_Config_Std std;
    
    private TITYPE entryType;
    private Integer userId;
    private Integer patientId;
    
    private Integer tempId;
    
    private Boolean quickSelectVclEnabled = true;
    private I18nManager i18n;
    
    private final static class caption extends I18nCB {
        static final I18nCB quickselect_new = set();
        static final I18nCB quickselect_tip = set();
    }
    
 	/* **************************** */
    
	public LocationPanel() {
		std = CMS_Config_Std.getInstance();
		
		setCompositionRoot(buildMainLayout());
		i18n = new I18nManager(this);
		
		registerComponents();
		
		fillLocationMap();
		
		configureComponents();
		
		
		fillLocationType();
		
		setFieldsEnabled(false);
		
	}
	
	 // register components for lng and validation tools
    private void registerComponents(){
    	
    	locationMap = new HashMap<Object, String>();
    	new ComponentIterator(locationContenPanelLayout).createMap(locationMap);
    	
    }

    
	/* **************************** */
	
    /**
     * 
     * @return value id if custom, null otherwise
     */
    public Integer getValue() {

        return saveLocation();
    }
    
    /**
     * 
     * @param value id if custom, null otherwise
     */
    public void setValue(Integer value) {
        
        quickSelectEnabled.setValue((value != null));
        quickSelectPresets.setValue(value);
        
        if(!quickSelectPresets.containsId(value)) {
            handleSetValue(value);
        }
 
    }
    
    //TASK implement generic setting
    
    public TITYPE getEntryType() {
        return entryType;
    }

    public void setEntryType(TITYPE entryType) {
        this.entryType = entryType;
        if(entryType == TITYPE.NURSE) {
            patientId = null;
        }
        if(entryType == TITYPE.PATIENT) {
            userId = null;
        }
    }

    public Integer getUser() {
        return userId;
    }
    
    public void setUser(Integer userId) {
        this.userId = userId;
    }
    
    public Integer getPatient() {
        return userId;
    }
    
    public void setPatient(Integer patientId) {
        this.patientId = patientId;
    }

	public void clearFields(){
		clearLocationFields();
	}
	
	public Integer saveLocation(){
	    
        if(!quickSelectEnabled.getValue()) {
            return null; // don't create entries for user defaults
        }
        
        if(quickSelectPresets.getValue() != null) {
            return (Integer) quickSelectPresets.getValue();
        }
	    
        if(tempId == null) { // fixes saves without reinit (like tenary ops)
            tempId = dbSaveLocation();
            fillLocationQuickSelect();
            quickSelectPresets.setValue(tempId);
        }
        return tempId;

		
	}
	
	public void setPanelEnabled(Boolean enabled) {
	    locationContenPanelLayout.setEnabled(enabled);
	    locationContenPanelLayout.setStyleName(enabled ? "" : "nogrey");
	}
	
	private void setFieldsEnabled(Boolean enabled){
		locationFieldsLayout.setEnabled(enabled);
		locationFieldsLayout.setStyleName(enabled ? "" : "nogrey");
	}
	
	/* **************************** */
	
	/* **************************** */
	

	/* **************************** */
	
    private void configureComponents(){
	
		for (Entry<Object, String> entry : locationMap.entrySet()) {
			AbstractComponent field = (AbstractComponent) entry.getKey();
			
			field.setImmediate(true);
			field.setWidth("100%");
			
			
			if(field instanceof ComboBox){
				((ComboBox)field).setFilteringMode(FilteringMode.CONTAINS);
			}
			
		}
		
		locationFieldsLayout.setStyleName("nogrey");
		locationFieldsLayout.setEnabled(false);
    	
    	locationType.setNullSelectionAllowed(false);
    	
    	quickSelectPresets.setFilteringMode(FilteringMode.CONTAINS);
        quickSelectPresets.setNullSelectionItemId(0);
        quickSelectPresets.setItemCaption(0, i18n.get(caption.quickselect_new));
        
        quickSelectPresets.setItemCaption(-1, i18n.get(caption.quickselect_tip));
        
        quickSelectPresets.setEnabled(quickSelectEnabled.getValue());
    	
    	
        quickSelectEnabled.setImmediate(true);
        quickSelectEnabled.addValueChangeListener(new ValueChangeListener() {

            @Override
            public void valueChange(ValueChangeEvent event) {

                Boolean useLoc = quickSelectEnabled.getValue();
                
                if(useLoc) {
                    fillLocationQuickSelect();
                }
                
                quickSelectPresets.setEnabled(useLoc);
                quickSelectPresets.setValue(-1); //TASK fix please select option
                setFieldsEnabled(false);

                clearFields();

                if (!useLoc ) {
                    if(userId != null) {
                        fillLocationFieldsUser(userId);
                    }else if(patientId != null) {
                        fillLocationFieldsPatient(patientId);
                    }

                }

            }
        });
        
    	
        quickSelectPresets.setImmediate(true);
        quickSelectPresets.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                if(!quickSelectVclEnabled) {
                    return;
                }
                
                Integer id = (Integer) event.getProperty().getValue();
                
                if(!handleSetValue(id)) {
                    quickSelectPresets.setValue(null);
                }
                setFieldsEnabled((id == null));
                
                
            }
        });
	}
	
    private Boolean handleSetValue(Integer value) {
        
        if(entryType == TITYPE.NURSE && userId == null) {
            log.error("no userId specified!");
            return false; 
        }
        
        if(entryType == TITYPE.PATIENT && patientId == null) {
            log.error("no patientId specified!");
            return false; 
        }
        
        Boolean success = false;
        
        clearFields();
        
        if (value == null) {
            
            if(!quickSelectEnabled.getValue()) { // fill from User
                log.debug("filling from defaults (user/patient) {}, {}", userId, entryType);
                return fillDefault();
                
            }else { // just clear the fields, this was triggered from presets
                setFieldsEnabled(true);
                return true;
            }
            
            
        }else if (value == -1) {
            setFieldsEnabled(false);
            return true;
        } else { // try filling from user presets
            
            log.debug("filling {} from value {} and user {}", entryType, value, userId);
            
            success = fillLocationFieldsCustom(value);
            
            if(!success) { // try filling from global list ...
                log.info("location id {} for user {} not found, falling back global presets", value, userId);
                success = fillLocationFieldsCustom(value, true); 
                
                quickSelectVclEnabled = false;
                fillLocationQuickSelect(value);
                quickSelectPresets.setValue(value);
                quickSelectVclEnabled = true;

            }
            
            if(!success) { // fall back to user/patient defaults
                log.info("no global preset with id {} found, falling back to {}: {} default", value, entryType, userId);
                return fillDefault();
            }


        }
        
        return success;
        
    }
    
    private Boolean fillDefault() {
        
        log.debug("fillDefault {}", entryType);
        
        switch (entryType) {
        case NURSE:
            return fillLocationFieldsUser(userId);
        case PATIENT:
            return fillLocationFieldsPatient(patientId);
        default:
            log.warn("tried to fill generic type from defaults");
            return false;
        }
    }
    
    private void fillLocationMap(){
    	String t = "cust_shipping_locations:";
    	
    	locationDbMap = new HashMap<>();
    	locationDbMap.put(locationName, t + "SL_NAME");
    	locationDbMap.put(locationExtended, t + "SL_EXTENDED");
    	locationDbMap.put(locationStreet, t + "SL_STREET");
    	locationDbMap.put(locationPlz, t + "SL_PLZ");
    	locationDbMap.put(locationCity, t + "SL_CITY");
    	locationDbMap.put(locationType, t + "SL_ID_TYPE");
    }
    
    private void fillLocationType(){
    	
    	I18nConverter typeConverter = new I18nConverter("cust_shipping_types", "ST_ID", "ST_TYPE");
    	typeConverter.attachDatasource(locationType);
    	
//    	Container con = typeConverter.getContainer();
//    	
//    	for (Object cid : con.getItemIds()) {
//    		
//    		Item item = con.getItem(cid);
//    		
//    		Integer id = (Integer) item.getItemProperty("ST_ID").getValue();
////    		String caption = LC.getCaption((String) item.getItemProperty("ST_TYPE").getValue());
////    		String caption = typeConverter.convertToPresentation((String) item.getItemProperty("ST_TYPE").getValue(), String.class, getLocale());
//    		String caption = typeConverter.getLngText((String) item.getItemProperty("ST_TYPE").getValue());
//    		
//			locationType.addItem(id);
//			locationType.setItemCaption(id, caption);
//		}
    	
    }
    
    private Boolean  fillLocationFieldsUser(Integer userId){
    	
        if(userId == null) {
            System.out.println("userId is null?");
            return false;
        }
        
    	clearLocationFields();
    	
    	String t = "T:";
    	
    	Map<Object, String> map = new HashMap<>();
    	map.put(locationName, t + "name");
    	map.put(locationStreet, t + "KSK_STRASSE");
    	map.put(locationPlz, t + "KSK_PLZ");
    	map.put(locationCity, t + "KSK_ORT");
    	map.put(locationType, t + "locationType");
    	

    	
    	DBClass db = new DBClass();
    	db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("*");
    	
		db.DB_Data_Get.DB_Tabellen.DB_CustomSQL( 
			" ( SELECT * ,"
			+ "CONCAT(ASA_NAME, ' ', AUL_VORNAME, ' ', AUL_NAME) as name,"
			+ "2 as locationType"
				
			+ " FROM cust_krankenschwester_stammdaten_ks"
			+ " INNER JOIN cms_auth_stammdaten_user on cust_krankenschwester_stammdaten_ks.KSK_U_ID = cms_auth_stammdaten_user.AUL_ID"
			+ " INNER JOIN cms_auth_stammdaten_anrede ON cms_auth_stammdaten_user.AUL_ANREDE_ID = cms_auth_stammdaten_anrede.ASA_ID) as T");
		
    	
		db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("T", "AUL_ID", "=", userId.toString(), "");
    	
//    	db.debugNextQuery(true);
		
    	Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();
    	
    	return fillLocationFields(con, map);
    	
    }
    
    private Boolean fillLocationFieldsPatient(Integer patientId) {
        if(patientId == null) {
            log.error("patientId is null?");
            return false;
        }
        
        clearLocationFields();

        String t = "T:";
        
        Map<Object, String> map = new HashMap<>();
        map.put(locationName, t + "name");
        map.put(locationStreet, t + "PSL_STRASSE");
        map.put(locationPlz, t + "PSL_PLZ");
        map.put(locationCity, t + "PSL_ORT");
        map.put(locationType, t + "locationType");
        
        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("*");
        
        db.DB_Data_Get.DB_Tabellen.DB_CustomSQL( 
            "(SELECT "
         + "\n " + "    CONCAT(PSA_NAME, ' ', PSL_VORNAME, ' ', PSL_NAME) as name"
         + "\n " + "    , PSL_ID, PSL_STRASSE, PSL_PLZ, PSL_ORT"
         + "\n " + "    , 3 as locationType"
         + "\n " + "FROM cust_patient_stammdaten_liste"
         + "\n " + "LEFT JOIN cust_patient_stammdaten_anrede on PSL_ANREDE = PSA_ID) as T");
        
        
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("T", "PSL_ID", "=", patientId.toString(), "");
        
//        db.debugNextQuery(true);
        
        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();
        
        return fillLocationFields(con, map);
        
    }
    
    private Boolean fillLocationFieldsCustom(Integer locationId){
        return fillLocationFieldsCustom(locationId, false);
    }
    
    private Boolean fillLocationFieldsCustom(Integer locationId, Boolean global){
		
		clearLocationFields();
		
		String t = "cust_shipping_locations:";
		
		Map<Object, String> map = new HashMap<>();
		map.put(locationName, t + "SL_NAME");
		map.put(locationExtended, t + "SL_EXTENDED");
		map.put(locationStreet, t + "SL_STREET");
		map.put(locationPlz, t + "SL_PLZ");
		map.put(locationCity, t + "SL_CITY");
		map.put(locationType, t + "SL_ID_TYPE");
		
		DBClass db = new DBClass();
		db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
		db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_shipping_locations");
		
        if(userId != null && !global) {
            db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_shipping_locations", "SL_ID_USER", "=", userId.toString(), "AND"); 
        }
        if(patientId != null && !global) {
            db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_shipping_locations", "SL_ID_PATIENT", "=", patientId.toString(), "AND"); 
        }
		db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_shipping_locations", "SL_ID", "=", locationId.toString(), "");
		
//		db.debugNextQuery(true);
		
		Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();
	
		return fillLocationFields(con, map);
		
	}
    
    private Boolean fillLocationFields(Container con, Map<Object, String> map){
    	
    	Form_Bind bind = new Form_Bind();
    	
        if(con.size() > 0){
        	bind.Get_and_Fill(con, map);
        	return true;
        }else{
        	return false;
        }
    }
    
    private void clearLocationFields(){
    	
    	for (Entry<Object, String> entry : locationMap.entrySet()) {
			
    		Object field = entry.getKey();
    		
    		if(field instanceof TextField){
    			((TextField) field).setValue("");
    		}
    		
    		if(field instanceof ComboBox){
    			((ComboBox) field).setValue(null);
    		}
    		
		}
        
    	
    }
 
    
    private Integer dbSaveLocation(){
        
        if(locationType.getValue() == null) {
            locationType.setValue(0);
        }
        
    	DBClass db = new DBClass();
    	
    	 Form_Bind fb = new Form_Bind();
         fb.Insert(db, locationDbMap);
         db.DB_Data_Insert.DB_Daten.DB_Data("cust_shipping_locations", "SL_TYPE", (entryType != null) ? entryType.name() : null);
         db.DB_Data_Insert.DB_Daten.DB_Data("cust_shipping_locations", "SL_ID_USER", (userId != null) ? userId.toString() : null);
         db.DB_Data_Insert.DB_Daten.DB_Data("cust_shipping_locations", "SL_ID_PATIENT", (patientId != null) ? patientId.toString() : null);
         /******************************** Table ****************************************/
         db.DB_Data_Insert.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_shipping_locations");
         /******************************************************************************/
         
         return db.DB_Data_Insert.DB_Insert();
    	
    }
    
    private void fillLocationQuickSelect() {
        fillLocationQuickSelect(null);
    }
    
    private void fillLocationQuickSelect(Integer includeGlobalId){
        
        DBClass db = new DBClass();
        
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("SL_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(SL_NAME, ' (', SL_STREET, ' ', SL_PLZ, ' ', SL_CITY, ')')", "location");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_shipping_locations");
        
        if(includeGlobalId != null) {
            db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_shipping_locations", "SL_ID", "=", includeGlobalId.toString(), " OR ");
        }
        
        if(entryType == TITYPE.NURSE && userId != null) {
           db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_shipping_locations", "SL_ID_USER", "=", userId.toString(), ""); 
        }
        if(entryType == TITYPE.PATIENT && patientId != null) {
            db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_shipping_locations", "SL_ID_PATIENT", "=", patientId.toString(), ""); 
        }
        if(entryType == TITYPE.GENERIC) {
            db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_shipping_locations", "SL_TYPE", "=", "'"+TITYPE.GENERIC.name()+"'", "");
        }
        
        try {
            quickSelectPresets.removeAllItems();
            quickSelectPresets.addItem(-1);
            quickSelectPresets.addItem(0);
            new combo(db.DB_Data_Get.DB_SEND_AND_GET(), quickSelectPresets, "SL_ID", "location");
        } catch (Exception e) {
            quickSelectPresets.removeAllItems();
            return;
        }
        
    }
	
	
	@AutoGenerated
    private VerticalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setStyleName("cust_margin_none");
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(true);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // locationContenPanel
        locationContenPanel = buildLocationContenPanel();
        mainLayout.addComponent(locationContenPanel);
        mainLayout.setExpandRatio(locationContenPanel, 12.0f);
        mainLayout.setComponentAlignment(locationContenPanel, new Alignment(24));
        
        return mainLayout;
    }

    @AutoGenerated
    private Panel buildLocationContenPanel() {
        // common part: create layout
        locationContenPanel = new Panel();
        locationContenPanel.setCaption("Adresse");
        locationContenPanel.setImmediate(false);
        locationContenPanel.setWidth("100.0%");
        locationContenPanel.setHeight("100.0%");
        
        // locationContenPanelLayout
        locationContenPanelLayout = buildLocationContenPanelLayout();
        locationContenPanel.setContent(locationContenPanelLayout);
        
        return locationContenPanel;
    }

    @AutoGenerated
    private VerticalLayout buildLocationContenPanelLayout() {
        // common part: create layout
        locationContenPanelLayout = new VerticalLayout();
        locationContenPanelLayout.setImmediate(false);
        locationContenPanelLayout.setWidth("100.0%");
        locationContenPanelLayout.setHeight("100.0%");
        locationContenPanelLayout.setMargin(true);
        locationContenPanelLayout.setSpacing(true);
        
        // quickSelectLayout
        quickSelectLayout = buildQuickSelectLayout();
        locationContenPanelLayout.addComponent(quickSelectLayout);
        locationContenPanelLayout.setExpandRatio(quickSelectLayout, 1.0f);
        
        // locationFieldsLayout
        locationFieldsLayout = buildLocationFieldsLayout();
        locationContenPanelLayout.addComponent(locationFieldsLayout);
        locationContenPanelLayout.setExpandRatio(locationFieldsLayout, 7.0f);
        
        return locationContenPanelLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildQuickSelectLayout() {
        // common part: create layout
        quickSelectLayout = new HorizontalLayout();
        quickSelectLayout.setCaption("Abweichende Adresse");
        quickSelectLayout.setImmediate(false);
        quickSelectLayout.setWidth("100.0%");
        quickSelectLayout.setHeight("-1px");
        quickSelectLayout.setMargin(false);
        quickSelectLayout.setSpacing(true);
        
        // quickSelectEnabled
        quickSelectEnabled = new CheckBox();
        quickSelectEnabled.setImmediate(false);
        quickSelectEnabled.setWidth("-1px");
        quickSelectEnabled.setHeight("-1px");
        quickSelectLayout.addComponent(quickSelectEnabled);
        quickSelectLayout.setComponentAlignment(quickSelectEnabled, new Alignment(48));
        
        // quickSelectPresets
        quickSelectPresets = new ComboBox();
        quickSelectPresets.setImmediate(false);
        quickSelectPresets.setWidth("100.0%");
        quickSelectPresets.setHeight("-1px");
        quickSelectLayout.addComponent(quickSelectPresets);
        quickSelectLayout.setExpandRatio(quickSelectPresets, 1.0f);
        quickSelectLayout.setComponentAlignment(quickSelectPresets, new Alignment(48));
        
        return quickSelectLayout;
    }

    @AutoGenerated
    private VerticalLayout buildLocationFieldsLayout() {
        // common part: create layout
        locationFieldsLayout = new VerticalLayout();
        locationFieldsLayout.setImmediate(false);
        locationFieldsLayout.setWidth("100.0%");
        locationFieldsLayout.setHeight("100.0%");
        locationFieldsLayout.setMargin(false);
        locationFieldsLayout.setSpacing(true);
        
        // locationName
        locationName = new TextField();
        locationName.setCaption("Name");
        locationName.setImmediate(false);
        locationName.setWidth("100.0%");
        locationName.setHeight("-1px");
        locationFieldsLayout.addComponent(locationName);
        
        // locationExtended
        locationExtended = new TextField();
        locationExtended.setCaption("Adresszusatz");
        locationExtended.setImmediate(false);
        locationExtended.setWidth("100.0%");
        locationExtended.setHeight("-1px");
        locationFieldsLayout.addComponent(locationExtended);
        
        // locationStreet
        locationStreet = new TextField();
        locationStreet.setCaption("Straße und Nummer");
        locationStreet.setImmediate(false);
        locationStreet.setWidth("100.0%");
        locationStreet.setHeight("-1px");
        locationFieldsLayout.addComponent(locationStreet);
        
        // locationPlz
        locationPlz = new TextField();
        locationPlz.setCaption("Postleitzahl");
        locationPlz.setImmediate(false);
        locationPlz.setWidth("100.0%");
        locationPlz.setHeight("-1px");
        locationFieldsLayout.addComponent(locationPlz);
        
        // locationCity
        locationCity = new TextField();
        locationCity.setCaption("Ort");
        locationCity.setImmediate(false);
        locationCity.setWidth("100.0%");
        locationCity.setHeight("-1px");
        locationFieldsLayout.addComponent(locationCity);
        
        // locationType
        locationType = new ComboBox();
        locationType.setCaption("Typ");
        locationType.setImmediate(false);
        locationType.setWidth("100.0%");
        locationType.setHeight("-1px");
        locationFieldsLayout.addComponent(locationType);
        
        return locationFieldsLayout;
    }
	
}

