package archenoah.web.normal.main.Menuepunkte.Individuelle.TaskSystem.TaskGroups.fom;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;

import archenoah.lib.custom.ComponentIterator;
import archenoah.lib.custom.MultiValueMapping;
import archenoah.lib.custom.MyUtils;
import archenoah.lib.custom.OnEnterKeyHandler;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.vaadin.Components.Combo.combo;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Tab_Menue_Item;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Window_Button;
import archenoah.lib.vaadin.Forms_Builder.Form_Bind;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.lib.vaadin.MenuBerechtigung.Rechteholen;
import archenoah.lib.vaadin.valchecker.val_checker4;

import com.google.common.base.Joiner;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.event.FieldEvents.TextChangeEvent;
import com.vaadin.event.FieldEvents.TextChangeListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.ui.AbstractField;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextField;
import com.vaadin.ui.TwinColSelect;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

@SuppressWarnings({"serial", "rawtypes", "unchecked"})
public class TaskGroupsInsertEdit extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private VerticalLayout mainLayout;

    @AutoGenerated
    private HorizontalLayout buttons;

    @AutoGenerated
    private Button btn_save;

    @AutoGenerated
    private VerticalLayout main;

    @AutoGenerated
    private Panel panel_1;

    @AutoGenerated
    private VerticalLayout verticalLayout_4;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_1;

    @AutoGenerated
    private VerticalLayout layoutLeft;

    @AutoGenerated
    private TwinColSelect groupMembers;

    @AutoGenerated
    private TextField filterUser;

    @AutoGenerated
    private TextField groupMail;

    @AutoGenerated
    private ComboBox groupLead;

    @AutoGenerated
    private TextField groupName;

    

    

    

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */

    /**************** --> Allgemein <--- ********************/
    // Allgemein
    private String exportCaption;
    
    // Datenbank
    private Map<Object, String> componentMap;
    private Map<Object, String> dbMap;
    private Map<Object, String> validateMap;
    private Form_Bind fb;
    private String dataSetId = "";

    
    // Berrechtigung
    private int ACC_ID;
	private Integer permRead;
	private Integer permUpdate;
	private Integer permCreate;
	private Integer permDelete;

    private MenuItem tmpMenu = null;
    private Button tmpButton = null;
    /******************************************************/
    /**************** --> Tabsheetvars <--- *****************/
    private TabSheet tab = null;
    /******************************************************/
    /**************** --> Windowvars <--- *******************/
    private Window win = null;
    /******************************************************/
    /******************* --> Custom <--- ********************/
    /******************************************************/
    
    IndexedContainer userContainer;
    MultiValueMapping memberMapping;
    
    /************ ----->Einstellungen<-- ********************/
//    private final String formIdLng = "306";
    private final String formIdPerm = "306";
    private final String Windows_Height = "600px";
    private final String Windows_Width = "500px";
    
    private final String dataIdCol = "TMG_ID";
    private final String dataTableName = "cust_taskmanager_groups";
    
    /******************************************************/

    public TaskGroupsInsertEdit(MenuItem Arg_Menü, String Arg_Form_ID) {
        tmpMenu = Arg_Menü;
        dataSetId = Arg_Form_ID;
    }

    public TaskGroupsInsertEdit(Button Arg_btn, String Arg_Form_ID) {
        tmpButton = Arg_btn;
        dataSetId = Arg_Form_ID;
    }

    /********* INIT-Window ************/
    public void init() {
        if (Windows_Height.equals("") == true || Windows_Width.equals("") == true) {
            System.out.println("Form Einstellung Fehlt: !!!");
            return;
        }

        Standard_Init();

        String fid = dataSetId;
        if (fid != "") {
            fid = " - #" + fid;
        }

        if (tmpMenu != null) {
        	
            String Recourcename = null;
            ThemeResource resource = null;
            if(tmpMenu.getIcon() != null){
            	Recourcename = tmpMenu.getIcon().toString();
            	Recourcename = Recourcename.substring(0, Recourcename.length() - 12) + "white-16.png";
            	resource = new ThemeResource(Recourcename);
            }

            exportCaption = tmpMenu.getText();
            Build_Window_Button bwb = new Build_Window_Button(tmpMenu.getText() + fid, mainLayout, Windows_Height, Windows_Width, resource);
            win = bwb.ReturnWindow();
        }
        if (tmpButton != null) {
            exportCaption = tmpButton.getCaption();
            Build_Window_Button bwb = new Build_Window_Button(tmpButton.getCaption() + fid, mainLayout, Windows_Height, Windows_Width, tmpButton.getIcon());
            win = bwb.ReturnWindow();
        }

    }

    /********* INIT-Tray ************/
    public void init(TabSheet Arg_tab) {

        Standard_Init();
        tab = Arg_tab;
        if (tmpMenu != null) {
            exportCaption = tmpMenu.getText();
            new Build_Tab_Menue_Item(Arg_tab, tmpMenu.getText(), mainLayout, tmpMenu.getIcon());
        }
        if (tmpButton != null) {
            exportCaption = tmpButton.getCaption();
            new Build_Tab_Menue_Item(Arg_tab, tmpButton.getCaption(), mainLayout, tmpButton.getIcon());
        }

    }
    
    public Window getWindow(){
    	return win;
    }
    
    public TabSheet getTabSheet(){
    	return tab;
    }
    
    /********* Init-Standard ************/
    private void Standard_Init() {
        buildMainLayout();
        new I18nManager(this);
        
        ACC_ID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        
        registerComponents();
        
        fillFields();
        fillDbMap();

        setCustomValidators();
        fillValidateMap();

        /***************/

        if (dataSetId != "") {
        	
            dbFillForm();
            dbFillMembers();
            
            
        } else {
            
        	//TASK "create init"
        	
        }

        setMenuPermissions();
        configureComponents();
        
        setEventListeners();
        
    }
    
 // register components for lng and validation tools
    private void registerComponents(){
    	componentMap = new HashMap<Object, String>();
    	new ComponentIterator(main).createMap(componentMap);
    }
    
    
    private void configureComponents(){
        
    	groupMembers.setItemCaptionPropertyId("user");
    	memberMapping = new MultiValueMapping(groupMembers);
                
    	for (Entry<Object, String> entry : componentMap.entrySet()) {
    		AbstractField field = (AbstractField) entry.getKey();
    		
			field.setImmediate(true);
			
			if(field instanceof ComboBox){
				((ComboBox)field).setFilteringMode(FilteringMode.CONTAINS);
			}
			

		}
    	
    	
    	
    	componentListeners();
    	
    }
    
    private void componentListeners(){

    	
        OnEnterKeyHandler onEnterHandler = new OnEnterKeyHandler() {
            @Override
            public void onEnterKeyPressed() {
                filterMembers(filterUser.getValue());
            }
        };
        onEnterHandler.installOn(filterUser);
    	
    	filterUser.addTextChangeListener(new TextChangeListener() {
            
            @Override
            public void textChange(TextChangeEvent event) {
               
                filterMembers(event.getText());

            }
        });
    	
    }
    
    private void filterMembers(String value) {
        
        userContainer.removeAllContainerFilters();
        userContainer.addContainerFilter( groupMembers.getItemCaptionPropertyId(), value, true, false);
    
    }
    
    /*************************** Events *******************************/

    private void setEventListeners() {

        btn_save.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {
                
                
                if (validate() == false) {
                    I18nManager.global(I18nGlobalNotifiers.fields_empty);
                    return;
                }
                
                if (dataSetId.equals("") == true) {
                	
                    dataSetId = Integer.toString(dbInsert());
                    dbSaveMembers();
                    
                } else {
                	
                    dbUpdate();
                    dbSaveMembers();
                    
                }


                //TASK check if save successful
                UI.getCurrent().getUI().removeWindow(win);
            }

        });

       
    }

    /******************************************************************/
    
    /************************ --> Berrechtigung <-- **************************/

    @SuppressWarnings("unused")
    public void setPermissionsFromDatabase() {
        if (formIdPerm == "") {
            System.out.println("Form Einstellung Fehlt: Berechtigung");
            return;
        }

        
        Rechteholen r = new Rechteholen(ACC_ID + "");
        String[][] perms = r.Datenholen();

        for (int i = 0; i < perms.length; i++) {
            if (perms[i][0].equals(formIdPerm) == true) {

                permRead = Integer.valueOf(perms[i][3]);
                permUpdate = Integer.valueOf(perms[i][4]);
                permCreate = Integer.valueOf(perms[i][6]);
                permDelete = Integer.valueOf(perms[i][5]);
                
            }
        }
    }

    public void setPermissions(int create, int read, int update, int delete) {

        permCreate = create;
        permRead = read;
        permUpdate = update;
        permDelete = delete;

    }

    private void setMenuPermissions() {
        Boolean c = (permCreate == 1);
        Boolean r = (permRead == 1);
        Boolean u = (permUpdate == 1);
        Boolean d = (permDelete == 1);

        btn_save.setEnabled((c||u));

    }
    
    /***********************************************/
    
    private void fillFields(){
    	fillFields(false);
    }
    
    private void fillFields(Boolean keepProject){
    	
        userContainer = dbGetUsers();
        new combo(userContainer, groupLead, "AUL_ID", "user");
        
        groupMembers.setContainerDataSource(userContainer);
        
    }
    
    
    
    /******************** Database *****************/
    private void fillDbMap() {
        dbMap = new HashMap<>();

        dbMap.put(groupName, dataTableName  + ":" + "TMG_NAME");
        dbMap.put(groupLead, dataTableName  + ":" + "TMG_ID_USER_LEAD");
        dbMap.put(groupMail, dataTableName  + ":" + "TMG_MAIL");

    }

    private IndexedContainer dbGetUsers() {
        
        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("AUL_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(AUL_NAME, ', ', AUL_VORNAME)", "user");
        
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cms_auth_stammdaten_user");
        
        db.DB_Data_Get.DB_Ordnen.DB_Ordnen("AUL_NAME", "ASC");
        
        return MyUtils.convertIndex(db.DB_Data_Get.DB_SEND_AND_GET_Container(), "AUL_ID");
        
    }
    
    private void dbFillForm() {
        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();

        /******************************** Table ****************************************/
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln(dataTableName);
        /******************************************************************************/
        /******************************** Filter ****************************************/
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein(dataTableName, dataIdCol, "=", dataSetId, "");
        /******************************************************************************/

        // db.DB_Data_Get.Set_Type("SLF_VON_UHRZEIT", Date.class);
        // db.DB_Data_Get.Set_Type("SLF_BIS_UHRZEIT", Date.class);

        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();
        fb = new Form_Bind();
        
        if(con.size() > 0){
        	fb.Get_and_Fill(con, dbMap);
        }
        
    }
    
    private void dbFillMembers() {
        
        DBClass db = new DBClass();
        
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_taskmanager_group_members");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_taskmanager_group_members", "TMGM_ID_GROUP", "=", dataSetId, "");
        
        IndexedContainer con = MyUtils.convertIndex(db.DB_Data_Get.DB_SEND_AND_GET_Container(), "TMGM_ID_USER");
        
        groupMembers.setValue(con.getItemIds());
        
    }
    
    private int dbInsert() {
        DBClass db = new DBClass();
        fb = new Form_Bind();
        fb.Insert(db, dbMap);
        /******************************** Table ****************************************/
        db.DB_Data_Insert.DB_Tabellen.DB_set_Tabelle_Einzeln(dataTableName);
        /******************************************************************************/
        // dba.DB_Data_Insert.DB_DEBUG_SQL_STRING();
        return db.DB_Data_Insert.DB_Insert();
    }

    private void dbUpdate() {
        DBClass db = new DBClass();
        fb = new Form_Bind();
        fb.Update(db, dbMap);

        /******************************** Table ****************************************/
        db.DB_Data_Update.DB_Tabellen.DB_set_Tabelle_Einzeln(dataTableName);
        /******************************************************************************/
        /******************************** Filter ****************************************/
        db.DB_Data_Update.DB_Filter.DB_WHERE_Allgemein(dataTableName, dataIdCol, "=", dataSetId, "");
        /******************************************************************************/
        db.DB_Data_Update.DB_Update();

    }

    private void dbSaveMembers() {

        DBClass db = new DBClass();
        
        if(memberMapping.getAddValues().size() > 0) {
            
            StringBuilder insert = new StringBuilder();
            insert.append("INSERT INTO cust_taskmanager_group_members"
                    + "\n " + "(TMGM_ID_GROUP,TMGM_ID_USER)"
                    + "\n " + "VALUES");
            
            ArrayList<String> values = new ArrayList<String>();      
            for (Object value : memberMapping.getAddValues()) {
                values.add("\n " + "(" + dataSetId + ", " + value +")");
            }
            insert.append(Joiner.on(",").join(values));
            insert.append(";");
            db.CustomQuery.setSqlString(insert.toString());
            db.CustomQuery.update();
            
        }
        
        if(memberMapping.getRemoveValues().size() > 0) {
            
            String delete = "DELETE FROM cust_taskmanager_group_members"
                + "\n " + "WHERE TMGM_ID_GROUP = " + dataSetId + " AND"
                        + " TMGM_ID_USER in (" + Joiner.on(",").join(memberMapping.getRemoveValues()) + ")";
            db.CustomQuery.setSqlString(delete.toString());
            db.CustomQuery.update();
            
        }
        
    }

    /*********************** -->Validierung<-- ********************/
    private void fillValidateMap() {
        validateMap = new HashMap<>();
        validateMap.putAll(componentMap);
        
//        ValidateMap.put(component, "component"); // should not be needed

    }

    private void setCustomValidators() {

        // psw_pass_1.addValidator(new Custom_Benutzerform_psw_ändern(psw_pass_1, psw_pass_2));

        /******* manual actions *******/

    }

    private boolean validate() {
        val_checker4 val = new val_checker4(validateMap);
        if (val.Is_Valid() == false) {
            return false;
        } else {
            return true;
        }

    }

    @AutoGenerated
    private VerticalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setStyleName("cust_margin_half_full_none_full");
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(true);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // main
        main = buildMain();
        mainLayout.addComponent(main);
        mainLayout.setExpandRatio(main, 9.0f);
        mainLayout.setComponentAlignment(main, new Alignment(48));
        
        // buttons
        buttons = buildButtons();
        mainLayout.addComponent(buttons);
        mainLayout.setExpandRatio(buttons, 1.0f);
        mainLayout.setComponentAlignment(buttons, new Alignment(48));
        
        return mainLayout;
    }

    @AutoGenerated
    private VerticalLayout buildMain() {
        // common part: create layout
        main = new VerticalLayout();
        main.setImmediate(false);
        main.setWidth("100.0%");
        main.setHeight("100.0%");
        main.setMargin(false);
        main.setSpacing(true);
        
        // panel_1
        panel_1 = buildPanel_1();
        main.addComponent(panel_1);
        main.setComponentAlignment(panel_1, new Alignment(48));
        
        return main;
    }

    @AutoGenerated
    private Panel buildPanel_1() {
        // common part: create layout
        panel_1 = new Panel();
        panel_1.setCaption("Gruppeneinstellungen");
        panel_1.setImmediate(false);
        panel_1.setWidth("100.0%");
        panel_1.setHeight("100.0%");
        
        // verticalLayout_4
        verticalLayout_4 = buildVerticalLayout_4();
        panel_1.setContent(verticalLayout_4);
        
        return panel_1;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_4() {
        // common part: create layout
        verticalLayout_4 = new VerticalLayout();
        verticalLayout_4.setImmediate(false);
        verticalLayout_4.setWidth("100.0%");
        verticalLayout_4.setHeight("100.0%");
        verticalLayout_4.setMargin(false);
        
        // horizontalLayout_1
        horizontalLayout_1 = buildHorizontalLayout_1();
        verticalLayout_4.addComponent(horizontalLayout_1);
        
        return verticalLayout_4;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_1() {
        // common part: create layout
        horizontalLayout_1 = new HorizontalLayout();
        horizontalLayout_1.setImmediate(false);
        horizontalLayout_1.setWidth("100.0%");
        horizontalLayout_1.setHeight("100.0%");
        horizontalLayout_1.setMargin(false);
        horizontalLayout_1.setSpacing(true);
        
        // layoutLeft
        layoutLeft = buildLayoutLeft();
        horizontalLayout_1.addComponent(layoutLeft);
        
        return horizontalLayout_1;
    }

    @AutoGenerated
    private VerticalLayout buildLayoutLeft() {
        // common part: create layout
        layoutLeft = new VerticalLayout();
        layoutLeft.setImmediate(false);
        layoutLeft.setWidth("100.0%");
        layoutLeft.setHeight("100.0%");
        layoutLeft.setMargin(false);
        layoutLeft.setSpacing(true);
        
        // groupName
        groupName = new TextField();
        groupName.setCaption("Gruppen-Name");
        groupName.setImmediate(false);
        groupName.setWidth("50.0%");
        groupName.setHeight("-1px");
        layoutLeft.addComponent(groupName);
        layoutLeft.setComponentAlignment(groupName, new Alignment(48));
        
        // groupLead
        groupLead = new ComboBox();
        groupLead.setCaption("Gruppenleitung");
        groupLead.setImmediate(false);
        groupLead.setWidth("50.0%");
        groupLead.setHeight("-1px");
        layoutLeft.addComponent(groupLead);
        layoutLeft.setComponentAlignment(groupLead, new Alignment(48));
        
        // groupMail
        groupMail = new TextField();
        groupMail.setCaption("Mailverteiler");
        groupMail.setImmediate(false);
        groupMail.setWidth("50.0%");
        groupMail.setHeight("-1px");
        layoutLeft.addComponent(groupMail);
        layoutLeft.setComponentAlignment(groupMail, new Alignment(48));
        
        // filterUser
        filterUser = new TextField();
        filterUser.setCaption("Benutzer filtern");
        filterUser.setImmediate(false);
        filterUser.setWidth("50.0%");
        filterUser.setHeight("-1px");
        layoutLeft.addComponent(filterUser);
        layoutLeft.setComponentAlignment(filterUser, new Alignment(48));
        
        // groupMembers
        groupMembers = new TwinColSelect();
        groupMembers.setCaption("Gruppenmitglieder");
        groupMembers.setImmediate(false);
        groupMembers.setWidth("100.0%");
        groupMembers.setHeight("100.0%");
        layoutLeft.addComponent(groupMembers);
        layoutLeft.setExpandRatio(groupMembers, 10.0f);
        layoutLeft.setComponentAlignment(groupMembers, new Alignment(48));
        
        return layoutLeft;
    }

    @AutoGenerated
    private HorizontalLayout buildButtons() {
        // common part: create layout
        buttons = new HorizontalLayout();
        buttons.setImmediate(false);
        buttons.setWidth("100.0%");
        buttons.setHeight("100.0%");
        buttons.setMargin(false);
        
        // btn_save
        btn_save = new Button();
        btn_save.setCaption("Speichern");
        btn_save.setImmediate(true);
        btn_save.setWidth("-1px");
        btn_save.setHeight("-1px");
        buttons.addComponent(btn_save);
        buttons.setComponentAlignment(btn_save, new Alignment(48));
        
        return buttons;
    }

}
