package archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.OpenTickets.form;

import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;

import org.apache.commons.lang3.tuple.Pair;
import org.joda.time.LocalDate;
import org.joda.time.LocalDateTime;

import archenoah.config.CMS_Config_Std;
import archenoah.lib.custom.ComponentIterator;
import archenoah.lib.custom.MyUtils;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.tool.comunication.dbclass.DBClass.CustomQuery;
import archenoah.lib.vaadin.Components.Combo.combo;
import archenoah.lib.vaadin.Components.Fields.DateFieldDisplay;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Tab_Menue_Item;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Window_Button;
import archenoah.lib.vaadin.Forms_Builder.Form_Bind;
import archenoah.lib.vaadin.Language.i18n.I18nCB;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.lib.vaadin.MenuBerechtigung.Rechteholen;
import archenoah.lib.vaadin.valchecker.val_checker4;
import archenoah.web.normal.UserInfo.UserData;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.InventoryManager.classes.InventoryBalance;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.OpenTickets.classes.DbGetTicketContents;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.OpenTickets.classes.SetQueryStatusLng;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.OpenTickets.classes.TITYPE;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.OpenTickets.classes.TicketActionsPermissionSet;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.OpenTickets.classes.TicketActionsPermissionSet.ACTION;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.OpenTickets.classes.TicketContentsPanel;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.OpenTickets.classes.TicketContentsPdf;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.OpenTickets.classes.TicketDelete;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.TicketPreferences.form.LocationPanel;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Prescriptions.PrescriptionManager.classes.PrescriptionBalance;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Prescriptions.PrescriptionManager.classes.StockPatientBalance;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.Validator.InvalidValueException;
import com.vaadin.server.Resource;
import com.vaadin.server.ThemeResource;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.ui.AbstractComponent;
import com.vaadin.ui.AbstractField;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

import de.steinwedel.messagebox.ButtonId;
import de.steinwedel.messagebox.Icon;
import de.steinwedel.messagebox.MessageBox;
import de.steinwedel.messagebox.MessageBoxListener;

@SuppressWarnings({"serial", "rawtypes", "unchecked"})
public class OpenTicketsInsertEdit extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private VerticalLayout mainLayout;

    @AutoGenerated
    private HorizontalLayout buttons;

    @AutoGenerated
    private Button receivedTicket;

    @AutoGenerated
    private Button orderTicket;

    @AutoGenerated
    private Button btn_save;

    @AutoGenerated
    private Button downloadExport;

    @AutoGenerated
    private Button deleteTicket;

    @AutoGenerated
    private HorizontalLayout topLayout;

    @AutoGenerated
    private TabSheet tabSheet_1;

    @AutoGenerated
    private VerticalLayout verticalLayout_3;

    @AutoGenerated
    private TextArea statusReceivedComment;

    @AutoGenerated
    private TextArea statusSentComment;

    @AutoGenerated
    private TextArea statusPreparingComment;

    @AutoGenerated
    private TextArea statusPlacedComment;

    @AutoGenerated
    private TicketContentsPanel ticketContentsPanel;

    @AutoGenerated
    private VerticalLayout verticalLayout_2;

    @AutoGenerated
    private VerticalLayout StatusLayout;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_5;

    @AutoGenerated
    private TextField statusReceivedUser;

    @AutoGenerated
    private DateFieldDisplay statusReceivedDate;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_4;

    @AutoGenerated
    private TextField statusSentUser;

    @AutoGenerated
    private DateFieldDisplay statusSentDate;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_3;

    @AutoGenerated
    private TextField statusPreparingUser;

    @AutoGenerated
    private DateFieldDisplay statusPreparingDate;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_2;

    @AutoGenerated
    private TextField statusPlacedUser;

    @AutoGenerated
    private DateFieldDisplay statusPlacedDate;

    @AutoGenerated
    private Label commentNotification;

    @AutoGenerated
    private HorizontalLayout generalLayout;

    @AutoGenerated
    private LocationPanel locationPanelModule;

    @AutoGenerated
    private Panel ticketGeneralPanel;

    @AutoGenerated
    private VerticalLayout ticketGeneralLayout;

    @AutoGenerated
    private ComboBox status;

    @AutoGenerated
    private ComboBox shippingCompany;

    @AutoGenerated
    private HorizontalLayout intendedLayout;

    @AutoGenerated
    private PopupDateField date_delivery;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_1;

    @AutoGenerated
    private DateFieldDisplay ticket_until;

    @AutoGenerated
    private DateFieldDisplay ticket_from;

    @AutoGenerated
    private VerticalLayout layoutTypeTargets;

    @AutoGenerated
    private ComboBox patient;

    @AutoGenerated
    private ComboBox nurse;

    @AutoGenerated
    private HorizontalLayout layoutType;

    @AutoGenerated
    private ComboBox countryCode;

    @AutoGenerated
    private ComboBox typeSelector;

    @AutoGenerated
    private DateFieldDisplay date_updated;

    

    

    

    

    

    

    

    

    

//    @AutoGenerated
//    private TextField nurse;

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */

    /**************** --> Allgemein <--- ********************/
    // Allgemein
    private CMS_Config_Std std;

    
    // Datenbank
    private Map<Object, String> componentMap;
    private Map<Object, String> dbMap;
    private Map<Object, String> dbMapReadonly;
    private Map<Object, String> validateMap;
    private Form_Bind fb;
    private String dataSetId = "";
    
    // Berrechtigung
    private int ACC_ID;
	private Integer permRead;
	private Integer permUpdate;
	private Integer permCreate;
	private Integer permDelete;

    private MenuItem tmpMenu = null;
    private Button tmpButton = null;
    /******************************************************/
    /**************** --> Tabsheetvars <--- *****************/
    private TabSheet tab = null;
    /******************************************************/
    /**************** --> Windowvars <--- *******************/
    private Window win = null;
    /******************************************************/
    /******************* --> Custom <--- ********************/
    /******************************************************/
    
    private Integer previousStatus;
    private Boolean balanceModified;
    private Boolean wasSaved = false;
    private Boolean wasDeleted = false;
    
    private Item dataItem;
    
    /************ ----->Einstellungen<-- ********************/
//    private final String formIdLng = "1051";
    private final String formIdPerm = "105"; //from OpenTicketsDataView
    private final String Windows_Height = "700px";
    private final String Windows_Width = "930px";
    
    private final String dataIdCol = "OMT_ID";
    private final String dataTableName = "cust_ordermanager_tickets";
    
    private org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(this.getClass());
    
    HashMap<Pair<Integer, String>, TicketActionsPermissionSet> ticketActionsPermissions;

    private String userGroupString;

    private boolean READONLY = false;

    private TITYPE ticketType;

    private boolean pauseLocation;

    private I18nManager i18n;
    
    @SuppressWarnings("unused")
    private final static class caption extends I18nCB {
        static final I18nCB NURSE = set();
        static final I18nCB PATIENT = set();
        static final I18nCB GENERIC = set();
    }
    
    /******************************************************/

    public OpenTicketsInsertEdit(MenuItem Arg_Menü, String Arg_Form_ID) {
        tmpMenu = Arg_Menü;
        dataSetId = Arg_Form_ID;
    }

    public OpenTicketsInsertEdit(Button Arg_btn, String Arg_Form_ID) {
        tmpButton = Arg_btn;
        dataSetId = Arg_Form_ID;
    }

    public OpenTicketsInsertEdit(String Arg_Form_ID) {
        dataSetId = Arg_Form_ID;
    }
    
    /********* INIT-Window ************/
    public void init() {
        if (Windows_Height.equals("") == true || Windows_Width.equals("") == true) {
            System.out.println("Form Einstellung Fehlt: !!!");
            return;
        }

        Standard_Init();

        String fid = dataSetId;
        if (fid != "") {
            fid = (tmpButton != null ? " - " : "") + "#" + fid;
        }

        if (tmpMenu != null) {
        	
            String Recourcename = null;
            ThemeResource resource = null;
            if(tmpMenu.getIcon() != null){
            	Recourcename = tmpMenu.getIcon().toString();
            	Recourcename = Recourcename.substring(0, Recourcename.length() - 12) + "white-16.png";
            	resource = new ThemeResource(Recourcename);
            }


            Build_Window_Button bwb = new Build_Window_Button(tmpMenu.getText() + fid, mainLayout, Windows_Height, Windows_Width, resource);
            win = bwb.ReturnWindow();
            win.setStyleName("scrollfix");
        }else{
            String title = tmpButton != null ? tmpButton.getCaption() : "";
            Resource icon = tmpButton != null ? tmpButton.getIcon() : null;
            Build_Window_Button bwb = new Build_Window_Button(title + fid, mainLayout, Windows_Height, Windows_Width, icon);
            win = bwb.ReturnWindow();
            win.setStyleName("scrollfix");
        }

    }

    /********* INIT-Tray ************/
    public void init(TabSheet Arg_tab) {

        Standard_Init();
        tab = Arg_tab;
        if (tmpMenu != null) {

            new Build_Tab_Menue_Item(Arg_tab, tmpMenu.getText(), mainLayout, tmpMenu.getIcon());
        }
        if (tmpButton != null) {

            new Build_Tab_Menue_Item(Arg_tab, tmpButton.getCaption(), mainLayout, tmpButton.getIcon());
        }

    }
    
    public Window getWindow(){
    	return win;
    }
    
    public TabSheet getTabSheet(){
    	return tab;
    }
    
    /********* Init-Standard ************/
    private void Standard_Init() {
        buildMainLayout();
        i18n = new I18nManager(this);
        
        std = CMS_Config_Std.getInstance();
        fb = new Form_Bind();
        
        userGroupString = getGroupString();
        
        registerComponents();
        
        fillFields();
        fillDbMap();

        setCustomValidators();
        fillValidateMap();

        
        setMenuPermissions();
        configureComponents();
        
        initWorkflowPermission();
        
        /***************/

        if (dataSetId != "") {
        	
            dbFillForm();
            toggleTypeDropdowns((String) typeSelector.getValue());
            //PackageUtils.limitDatePicker(date_delivery, date_delivery.getValue(), RANGE.WEEK);
            
            DbGetTicketContents tc = new DbGetTicketContents();
            tc.setTicketId(Integer.parseInt(dataSetId));
            
            LocalDate end = tc.getEarliestEntry();
            date_delivery.setRangeEnd(end.toDate());
            if(UserData.get().getNurse().isNurse()) {
                LocalDate start = MyUtils.getWeekMonday(date_delivery.getValue(), 0);
                if(start.isBefore(end)) {
                    date_delivery.setRangeStart(start.toDate());
                }
            }
            
            ticketContentsPanel.getTicketContents(Integer.parseInt(dataSetId));
            ticketContentsPanel.setEditable((previousStatus <= 15));
            
        } else {
            
        	//TASK "create init"
            System.out.println("create init");
        	
        }

//        System.out.println(previousStatus);
//        if(previousStatus != null){
//        	dbGetStatusValues(previousStatus);
//        	status.setValue(previousStatus);
//        }
        
        setEventListeners();
        
        limitStatusValues();
        
        setWorkflowPermissions();
        
        setEnabledFields();
    }
    
    public void setType(TITYPE type) {
        this.ticketType = type;
    }
    
    public TITYPE getType() {
        return this.ticketType;
    }
    
    public Boolean wasSaved() {
        return wasSaved;
    }

    public void setSaved(Boolean saved) {
        this.wasSaved = saved;
    }

    
    public Boolean wasDeleted() {
        return wasDeleted;
    }
    
    public Integer getTicketId() {
        
        Integer id = null;
        
        try {
            id = Integer.parseInt(dataSetId);
        } catch (Exception e) {}
        
        return id;
    }
    // register components for lng and validation tools
    private void registerComponents(){
    	componentMap = new HashMap<Object, String>();
    	new ComponentIterator(ticketGeneralLayout).createMap(componentMap);
//    	iterateR(mainLayout.iterator(), componentMap);
    }
    
    private void configureComponents(){
	    
        mainLayout.setSizeFull();
    	
        
        
    	//general
    	status.setNullSelectionAllowed(false);
    	status.setStyleName("");
    	status.setItemCaptionPropertyId("STATUS");
    	
    	date_updated.setEnabled(false);
    	date_updated.setDateFormat(DateFormat.LONG);
    	date_updated.setTimeFormat(DateFormat.SHORT);
    	
//    	nurse.setEnabled(false);
    	countryCode.setEnabled(false);
    	
    	ticket_from.setEnabled(false);
    	ticket_from.setDateFormat(DateFormat.SHORT);
    	
    	ticket_until.setEnabled(false);
    	ticket_until.setDateFormat(DateFormat.SHORT);

    	shippingCompany.setStyleName("");
    	shippingCompany.setNullSelectionAllowed(false);
    	
    	//status fields
    	configureStatusFields(statusPlacedUser, statusPlacedDate);
    	configureStatusFields(statusPreparingUser, statusPreparingDate);
    	configureStatusFields(statusSentUser, statusSentDate);
    	configureStatusFields(statusReceivedUser, statusReceivedDate);
    	
//      nurse.setVisible(false);
        nurse.setVisible(false);
        nurse.setImmediate(true);
        nurse.setItemCaptionPropertyId("nurse");
        patient.setImmediate(true);
        patient.setVisible(false);
        patient.setItemCaptionPropertyId("patient");
    	
        typeSelector.setImmediate(true);
        typeSelector.setNullSelectionAllowed(false);
        
        statusPlacedComment.setNullRepresentation("");
        statusPlacedComment.setNullSettingAllowed(true);
        statusPreparingComment.setNullRepresentation("");
        statusPreparingComment.setNullSettingAllowed(true);
        statusSentComment.setNullRepresentation("");
        statusSentComment.setNullSettingAllowed(true);
        statusReceivedComment.setNullRepresentation("");
        statusReceivedComment.setNullSettingAllowed(true);
        
        commentNotification.setVisible(false);
        
    	componentListeners();
    	
    	
        for (Entry<Object, String> entry : componentMap.entrySet()) {
            AbstractComponent component = (AbstractComponent) entry.getKey();
            
            component.setImmediate(true);
            if(!component.isEnabled()){
                component.setStyleName("nogrey");
            }
            
            if(component instanceof ComboBox){
                ((ComboBox)component).setFilteringMode(FilteringMode.CONTAINS);
            }
            
        }
    }
    
    private void configureStatusFields(TextField user, DateFieldDisplay date) {
        user.setEnabled(false);
        user.setStyleName("nogrey");
        
        date.setEnabled(false);
        date.setStyleName("nogrey");
        date.setDateFormat(DateFormat.LONG);
        date.setTimeFormat(DateFormat.SHORT);
    }
    
    private void componentListeners(){
    	
    	status.addValueChangeListener(new ValueChangeListener() {
			
			@Override
			public void valueChange(ValueChangeEvent event) {
				
				setEnabledFields();
				
			}
		});
    	
        TicketContentsPdf export = new TicketContentsPdf();

        if(export.setTicketId(Integer.parseInt(dataSetId))) {
            export.attach(downloadExport);
        }else {
            downloadExport.addClickListener(new ClickListener() {
                
                @Override
                public void buttonClick(ClickEvent event) {
                    
                    I18nManager.global(I18nGlobalNotifiers.missing_data);
                    
                }
            });
        }

    	
    	deleteTicket.addClickListener(new ClickListener() {
            
            @Override
            public void buttonClick(ClickEvent event) {
                
                if((Integer) status.getValue() >= 20) {
                    return;
                }
                
                MessageBoxListener mbl = new MessageBoxListener() {
                    
                    @Override
                    public void buttonClicked(ButtonId btn) {
                        
                        if(btn == ButtonId.YES){
                            if(TicketDelete.delete(Integer.parseInt(dataSetId))){
                                wasSaved = true;
                                wasDeleted = true;
                                win.close();
                            }
                        }
                        
                    }
                };
                
                MessageBox mb = MessageBox.showHTML(Icon.WARN, "Ticket #"+dataSetId+" zurücksetzen?", "Warnung: alle manuellen Anpassungen werden zurückgesetzt!", mbl, ButtonId.YES, ButtonId.ABORT); 
                
                
            }
        });

    	orderTicket.addClickListener(new ClickListener() {
            
            @Override
            public void buttonClick(ClickEvent event) {
                
                if(date_delivery.getValue() != null) {
                    LocalDate limitDate = MyUtils.minusWeekDays(new LocalDate(date_delivery.getValue().getTime()), 3);
                    
                    if(new LocalDate().isAfter(limitDate) && "nurse".equals(userGroupString)) {
                        
                        MessageBox.showHTML(Icon.ERROR, "Bestellfrist verstrichen"
                            , "Dieses Paket hätte bis zum " + DateFormat.getDateInstance(DateFormat.SHORT).format(limitDate.toDate()) + " bestellt werden müssen. <br />"
                                + "Bitte kontaktieren Sie die Apotheke!", ButtonId.OK);
                        return;
                    }
                    
                    
                }
                
                
                
                MessageBox.showHTML(Icon.WARN, "Paket verbindlich bestellen?"
                        , "Achtung: Dies ist eine verbindliche Bestellung bei der Apotheke!",
                        new MessageBoxListener() {

                            @Override
                            public void buttonClicked(ButtonId buttonId) {
                                
                                if(buttonId == ButtonId.YES) {
                                    status.setValue(10);
                                    btn_save.click();
                                }
                                
                            }
                    
                        }
                        , ButtonId.NO, ButtonId.YES);
                
            }
        });

    	
    	receivedTicket.addClickListener(new ClickListener() {
            
            @Override
            public void buttonClick(ClickEvent event) {
                
                status.setValue(30);
                btn_save.click();
                
            }
        });
    	
    	typeSelector.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                if(pauseLocation) { return; }
                toggleTypeDropdowns((String) event.getProperty().getValue());
                
            }
        });
    	
    	nurse.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                if(pauseLocation) { return; }
                
                if(locationPanelModule.getUser() != (Integer) nurse.getValue()) {
                    locationPanelModule.setUser((Integer) nurse.getValue());
                    locationPanelModule.setValue(null);
                }
                
            }
        });
    	
    	patient.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                if(pauseLocation) { return; }
                
                if(locationPanelModule.getPatient() != (Integer) patient.getValue()) {
                    locationPanelModule.setPatient((Integer) patient.getValue());
                    locationPanelModule.setValue(null);
                }
                
                ticketContentsPanel.setPatientDefault((Integer) patient.getValue());
            }
        });
    }
    
    private void toggleTypeDropdowns(String type) {
        
        nurse.setVisible(MyUtils.equalsWithNulls(type, TITYPE.NURSE.name()));
        patient.setVisible(MyUtils.equalsWithNulls(type, TITYPE.PATIENT.name()));
        
        locationPanelModule.setEntryType(TITYPE.get(type));
        if(nurse.isVisible()) {
            locationPanelModule.setUser((Integer) nurse.getValue());
            ticketContentsPanel.setPatientDefault(null);
            ticketContentsPanel.setNurseUserID((Integer) nurse.getValue());
        }
        if(patient.isVisible()) {
            locationPanelModule.setPatient((Integer) patient.getValue());
            ticketContentsPanel.setPatientDefault((Integer) patient.getValue());
            ticketContentsPanel.setNurseUserID(null);
        }
        locationPanelModule.setValue(locationPanelModule.getValue());
    }
    
    private void setEnabledFields(){
    	
//    	if(previousStatus != null) {
//    	    deleteTicket.setEnabled((previousStatus <= 15));
//    	    
//    	}
    	
        // comment permissions
        
    	Integer currentStatus = (Integer) status.getValue();
    	
        Boolean placedEnabled = currentStatus <= 10;
        Boolean preparingEnabled = currentStatus == 15 && !userGroupString.equals("nurse");
        Boolean sentEnabled = currentStatus == 20 && !userGroupString.equals("nurse");
        Boolean receivedEnabled = currentStatus == 30;
        
        toggleFieldEnabled(statusPlacedComment, !READONLY && placedEnabled);
        toggleFieldEnabled(statusPreparingComment, !READONLY && preparingEnabled);
        toggleFieldEnabled(statusSentComment, !READONLY && sentEnabled);
        toggleFieldEnabled(statusReceivedComment, !READONLY && receivedEnabled);
        
        commentNotification.setVisible(
            statusPlacedComment.getValue() != null
            || statusPreparingComment.getValue() != null
            || statusSentComment.getValue() != null
            || statusReceivedComment.getValue() != null
            );
    }
    
    private void setDateValue(PopupDateField df){
    	if(df.getValue() == null){
    		df.setValue(new Date());
    	}
    }
    
    
    /*************************** Events *******************************/

    private void setEventListeners() {

        btn_save.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {

                if (validate() == false) {
                    I18nManager.global(I18nGlobalNotifiers.fields_empty);
                    return;
                }
                
                if (!checkIntegrity()) {
                    I18nManager.global(I18nGlobalNotifiers.review_data);
                    return;
                }
                
                Boolean success = false;
                
                finalizeType();
                
                if (dataSetId.equals("") == true) {
                	
//                    dataSetId = Integer.toString(dbInsert());
                	System.out.println("no insert implementation");
                    
                } else {
                	
                	//updateBalance(); //TASK ??
                	
                    if(ticketContentsPanel.saveTicketContents()){
                        updateBalance();
                        dbUpdate();
                        success = true;
                    }
                    
                    

                }

                if(success){
                    setSaved(true);
                    UI.getCurrent().getUI().removeWindow(win);
                }
                
            }

        });

       
    }

    /******************************************************************/
    
    private void updateBalance(){
        
    	Integer currentStatus = (Integer) status.getValue();
    	
    	if(!balanceModified && currentStatus > 15 && previousStatus <= 15){

    	    setBalanceValues();
            
    	}
    	

        if(balanceModified && currentStatus <= 15 && previousStatus > 15){

            restoreBalanceValues();
            
        }    	
    	
    	
    }

    /** 
     * 
     * @return
     * @return (patient, product) : value
     */
    private HashMap<Pair<Integer, Integer>, Integer> getBalanceValues(){
        // project_date, PP_PRODUCT, project_quantity_static, OMTC_QTY, patient_all, OMTC_ID_DATA, OMTC_ID, OMTC_UPDATED, OMTC_ID_PATIENT, PP_ID
        Container values = ticketContentsPanel.getCurrentValues();
        
        //HashMap<Integer, Integer> map = new HashMap<Integer, Integer>();
        HashMap<Pair<Integer,Integer>, Integer> map = new HashMap<Pair<Integer,Integer>, Integer>();
        
        for (Object iid : values.getItemIds()) {
            Item item = values.getItem(iid);
            Integer patient = (Integer) item.getItemProperty("OMTC_ID_PATIENT").getValue();
            Integer product = (Integer) item.getItemProperty("PP_ID").getValue();
            
            Integer qty = 0;
            
            if(item.getItemProperty("OMTC_QTY").getValue() != null) {
                qty = Integer.parseInt(item.getItemProperty("OMTC_QTY").getValue().toString());
            }
            
            Pair key = Pair.of(patient, product);
            
            Integer sum = 0;
            
            if(map.containsKey(key)) {
                sum = map.get(key);
            }
            
            map.put(key, sum + qty);
            
        }
        
        
        return map;
    }
    
    private void setBalanceValues() {
        balanceModified = true;
        updateBalanceValues(false);
    }
    
    private void restoreBalanceValues() {
        balanceModified = false;
        updateBalanceValues(true);
    }
    
    private void updateBalanceValues(Boolean restore) {
        
        StockPatientBalance stock = new StockPatientBalance();
        PrescriptionBalance prescription = new PrescriptionBalance();
        InventoryBalance inventory = new InventoryBalance();
        UserData userData = MyUtils.getUserData();
        
        Integer stockPrefix = restore ? -1 : 1;
        Integer prescriptionPrefix = restore ? 1 : -1;
        
        HashMap<Pair<Integer, Integer>, Integer> map = getBalanceValues();
        
        for (Pair<Integer, Integer> pair : map.keySet()) {
            
             stock.setPatientId(pair.getKey());
             stock.editBalance(pair.getValue(), stockPrefix * map.get(pair), StockPatientBalance.LOGISTICS);
            
             prescription.setPatientId(pair.getKey());
             prescription.editBalance(pair.getValue(), prescriptionPrefix * map.get(pair), PrescriptionBalance.LOGISTICS, null, dataSetId);
             
             inventory.setUserId(userData.getUserId());
             inventory.setCountryCode((String) countryCode.getValue());
             inventory.editBalance(pair.getValue(), prescriptionPrefix * map.get(pair), InventoryBalance.ACTION_TICKET, null, dataSetId);
        }
        
        
    }
    
    /************************ --> Berrechtigung <-- **************************/

    @SuppressWarnings("unused")
    public void setPermissionsFromDatabase() {
        if (formIdPerm == "") {
            System.out.println("Form Einstellung Fehlt: Berechtigung");
            return;
        }

        
        ACC_ID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        Rechteholen r = new Rechteholen(ACC_ID + "");
        String[][] perms = r.Datenholen();

        for (int i = 0; i < perms.length; i++) {
            if (perms[i][0].equals(formIdPerm) == true) {

                permRead = Integer.valueOf(perms[i][3]);
                permUpdate = Integer.valueOf(perms[i][4]);
                permCreate = Integer.valueOf(perms[i][6]);
                permDelete = Integer.valueOf(perms[i][5]);
                
            }
        }
    }

    public void setPermissions(int create, int read, int update, int delete) {

        permCreate = create;
        permRead = read;
        permUpdate = update;
        permDelete = delete;

    }

    private void setMenuPermissions() {
        Boolean c = (permCreate == 1);
        Boolean r = (permRead == 1);
        Boolean u = (permUpdate == 1);
        Boolean d = (permDelete == 1);

        btn_save.setEnabled((c||u));
        ticketContentsPanel.setEditable((c||u));
        
        deleteTicket.setEnabled(d);
        
        if(r && !(c || u || d)) { //readonly mode
            
            READONLY = true;
            
        }
    }
    
    private void initWorkflowPermission() {
        
        ticketActionsPermissions = new HashMap<Pair<Integer, String>, TicketActionsPermissionSet>();
        HashMap<Pair<Integer, String>, TicketActionsPermissionSet> map = ticketActionsPermissions;
        
        map.put(Pair.of(5, "nurse"), new TicketActionsPermissionSet());
        map.put(Pair.of(10, "nurse"), new TicketActionsPermissionSet());
        map.put(Pair.of(15, "nurse"), new TicketActionsPermissionSet());
        map.put(Pair.of(20, "nurse"), new TicketActionsPermissionSet());
        map.put(Pair.of(30, "nurse"), new TicketActionsPermissionSet());
        
        map.put(Pair.of(5, "apo"), new TicketActionsPermissionSet());
        map.put(Pair.of(10, "apo"), new TicketActionsPermissionSet());
        map.put(Pair.of(15, "apo"), new TicketActionsPermissionSet());
        map.put(Pair.of(20, "apo"), new TicketActionsPermissionSet());
        map.put(Pair.of(30, "apo"), new TicketActionsPermissionSet());
     
        // NURSE
        
        map.get(Pair.of(5, "nurse")).setPermission(ACTION.CONTENTS_UPDATE, true);
        map.get(Pair.of(5, "nurse")).setPermission(ACTION.CONTENTS_CREATE, true);
        map.get(Pair.of(5, "nurse")).setPermission(ACTION.CONTENTS_MOVE, true);
        map.get(Pair.of(5, "nurse")).setPermission(ACTION.DETAILS, true);
        map.get(Pair.of(5, "nurse")).setPermission(ACTION.TYPE, false);
        map.get(Pair.of(5, "nurse")).setPermission(ACTION.STATUS, false);
        map.get(Pair.of(5, "nurse")).setPermission(ACTION.ADDRESS, true);
        
        map.get(Pair.of(10, "nurse")).setPermission(ACTION.CONTENTS_UPDATE, false);
        map.get(Pair.of(10, "nurse")).setPermission(ACTION.CONTENTS_CREATE, false);
        map.get(Pair.of(10, "nurse")).setPermission(ACTION.CONTENTS_MOVE, false);
        map.get(Pair.of(10, "nurse")).setPermission(ACTION.DETAILS, false);
        map.get(Pair.of(10, "nurse")).setPermission(ACTION.TYPE, false);
        map.get(Pair.of(10, "nurse")).setPermission(ACTION.STATUS, false);
        map.get(Pair.of(10, "nurse")).setPermission(ACTION.ADDRESS, false);
        
        map.get(Pair.of(15, "nurse")).setPermission(ACTION.CONTENTS_UPDATE, false);
        map.get(Pair.of(15, "nurse")).setPermission(ACTION.CONTENTS_CREATE, false);
        map.get(Pair.of(15, "nurse")).setPermission(ACTION.CONTENTS_MOVE, false);
        map.get(Pair.of(15, "nurse")).setPermission(ACTION.DETAILS, false);
        map.get(Pair.of(15, "nurse")).setPermission(ACTION.TYPE, false);
        map.get(Pair.of(15, "nurse")).setPermission(ACTION.STATUS, false);
        map.get(Pair.of(15, "nurse")).setPermission(ACTION.ADDRESS, false);
        
        map.get(Pair.of(20, "nurse")).setPermission(ACTION.CONTENTS_UPDATE, false);
        map.get(Pair.of(20, "nurse")).setPermission(ACTION.CONTENTS_CREATE, false);
        map.get(Pair.of(20, "nurse")).setPermission(ACTION.CONTENTS_MOVE, false);
        map.get(Pair.of(20, "nurse")).setPermission(ACTION.DETAILS, false);
        map.get(Pair.of(20, "nurse")).setPermission(ACTION.TYPE, false);
        map.get(Pair.of(20, "nurse")).setPermission(ACTION.STATUS, false);
        map.get(Pair.of(20, "nurse")).setPermission(ACTION.ADDRESS, false);
        
        map.get(Pair.of(30, "nurse")).setPermission(ACTION.CONTENTS_UPDATE, false);
        map.get(Pair.of(30, "nurse")).setPermission(ACTION.CONTENTS_CREATE, false);
        map.get(Pair.of(30, "nurse")).setPermission(ACTION.CONTENTS_MOVE, false);
        map.get(Pair.of(30, "nurse")).setPermission(ACTION.DETAILS, false);
        map.get(Pair.of(30, "nurse")).setPermission(ACTION.TYPE, false);
        map.get(Pair.of(30, "nurse")).setPermission(ACTION.STATUS, false);
        map.get(Pair.of(30, "nurse")).setPermission(ACTION.ADDRESS, false);
        
        // APO
        
        map.get(Pair.of(5, "apo")).setPermission(ACTION.CONTENTS_UPDATE, false);
        map.get(Pair.of(5, "apo")).setPermission(ACTION.CONTENTS_CREATE, false);
        map.get(Pair.of(5, "apo")).setPermission(ACTION.CONTENTS_MOVE, false);
        map.get(Pair.of(5, "apo")).setPermission(ACTION.DETAILS, false);
        map.get(Pair.of(5, "apo")).setPermission(ACTION.TYPE, false);
        map.get(Pair.of(5, "apo")).setPermission(ACTION.STATUS, false);
        map.get(Pair.of(5, "apo")).setPermission(ACTION.ADDRESS, false);
        
        map.get(Pair.of(10, "apo")).setPermission(ACTION.CONTENTS_UPDATE, true);
        map.get(Pair.of(10, "apo")).setPermission(ACTION.CONTENTS_CREATE, true);
        map.get(Pair.of(10, "apo")).setPermission(ACTION.CONTENTS_MOVE, true);
        map.get(Pair.of(10, "apo")).setPermission(ACTION.DETAILS, true);
        map.get(Pair.of(10, "apo")).setPermission(ACTION.TYPE, true);
        map.get(Pair.of(10, "apo")).setPermission(ACTION.STATUS, true);
        map.get(Pair.of(10, "apo")).setPermission(ACTION.ADDRESS, true);
                             
        map.get(Pair.of(15, "apo")).setPermission(ACTION.CONTENTS_UPDATE, true);
        map.get(Pair.of(15, "apo")).setPermission(ACTION.CONTENTS_CREATE, true);
        map.get(Pair.of(15, "apo")).setPermission(ACTION.CONTENTS_MOVE, true);
        map.get(Pair.of(15, "apo")).setPermission(ACTION.DETAILS, true);
        map.get(Pair.of(15, "apo")).setPermission(ACTION.TYPE, false);
        map.get(Pair.of(15, "apo")).setPermission(ACTION.STATUS, true);
        map.get(Pair.of(15, "apo")).setPermission(ACTION.ADDRESS, true);
                             
        map.get(Pair.of(20, "apo")).setPermission(ACTION.CONTENTS_UPDATE, false);
        map.get(Pair.of(20, "apo")).setPermission(ACTION.CONTENTS_CREATE, false);
        map.get(Pair.of(20, "apo")).setPermission(ACTION.CONTENTS_MOVE, false);
        map.get(Pair.of(20, "apo")).setPermission(ACTION.DETAILS, false);
        map.get(Pair.of(20, "apo")).setPermission(ACTION.TYPE, false);
        map.get(Pair.of(20, "apo")).setPermission(ACTION.STATUS, true);
        map.get(Pair.of(20, "apo")).setPermission(ACTION.ADDRESS, false);
                             
        map.get(Pair.of(30, "apo")).setPermission(ACTION.CONTENTS_UPDATE, false);
        map.get(Pair.of(30, "apo")).setPermission(ACTION.CONTENTS_CREATE, false);
        map.get(Pair.of(30, "apo")).setPermission(ACTION.CONTENTS_MOVE, false);
        map.get(Pair.of(30, "apo")).setPermission(ACTION.DETAILS, false);
        map.get(Pair.of(30, "apo")).setPermission(ACTION.TYPE, false);
        map.get(Pair.of(30, "apo")).setPermission(ACTION.STATUS, true);
        map.get(Pair.of(30, "apo")).setPermission(ACTION.ADDRESS, false);
    }
    
    private TicketActionsPermissionSet getWorkflowPermission(Integer status) {

        TicketActionsPermissionSet set = ticketActionsPermissions.get(Pair.of(status, userGroupString));
        
        if(set == null) { // fallback to default all true
            set = new TicketActionsPermissionSet(true);
        }
        
        return set;
        
    }
    
    private void setWorkflowPermissions() {
        
        TicketActionsPermissionSet set = getWorkflowPermission(previousStatus);
        
        // orderButton
        orderTicket.setVisible(!READONLY && previousStatus == 5);
        receivedTicket.setVisible(!READONLY && previousStatus == 20);
        
        ticketContentsPanel.setEditable(!READONLY && set.getPermission(ACTION.CONTENTS_UPDATE));
        ticketContentsPanel.setAddable(!READONLY && set.getPermission(ACTION.CONTENTS_CREATE));
        ticketContentsPanel.setMoveable(!READONLY && set.getPermission(ACTION.CONTENTS_MOVE));

        toggleFieldEnabled(status, !READONLY && set.getPermission(ACTION.STATUS));
        toggleFieldEnabled(date_delivery, !READONLY && set.getPermission(ACTION.DETAILS));
        toggleFieldEnabled(shippingCompany, !READONLY && set.getPermission(ACTION.DETAILS));
        
        
        toggleFieldEnabled(countryCode, !READONLY && set.getPermission(ACTION.TYPE));
        toggleFieldEnabled(typeSelector, !READONLY && set.getPermission(ACTION.TYPE));
        toggleFieldEnabled(nurse, !READONLY && set.getPermission(ACTION.TYPE));
        toggleFieldEnabled(patient, !READONLY && set.getPermission(ACTION.TYPE));
        
        deleteTicket.setEnabled(!READONLY && set.getPermission(ACTION.CONTENTS_CREATE));
        
        locationPanelModule.setPanelEnabled(!READONLY && set.getPermission(ACTION.ADDRESS));
        
        downloadExport.setVisible(!userGroupString.equals("nurse"));
        
        // temp fix for date limit
        if(!userGroupString.equals("nurse")) {
            date_delivery.setRangeEnd(null);
        }
        
        try {
            date_delivery.validate();
        } catch (InvalidValueException e) {
            date_delivery.setRangeEnd(null);
            toggleFieldEnabled(date_delivery, false);
        }
        
    }
    
    private void toggleFieldEnabled(AbstractField field, Boolean enabled) {
        field.setEnabled(enabled);
        field.setStyleName(enabled ? "" : "nogrey");
    }
    
    private String getGroupString() {
        
        Integer uid = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        
        String groupString = "";
        
        DBClass db = new DBClass();
        
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("AL_G_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cms_auth_liste_gu");
        db.DB_Data_Get.DB_Filter.DB_WHERE_In("cms_auth_liste_gu", "AL_G_ID", "12,21", "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cms_auth_liste_gu", "AL_U_ID", "=", uid.toString(), "");
        
        Container con = db.DB_Data_Get.DB_SEND_AND_GET();
        ArrayList<Integer> list = new ArrayList<Integer>();
        for (Object iid : con.getItemIds()) {
            if(con.getContainerProperty(iid, "AL_G_ID") != null) {
                list.add((Integer) con.getContainerProperty(iid, "AL_G_ID").getValue());
            }
        }
        
        if(list.contains(21)) {
            groupString = "apo";
        }else if(list.contains(12)){
            groupString = "nurse";
        }
        
//        groupString = "nurse"; // DEBUG!
//        groupString = "apo"; // DEBUG!
        
        return groupString;

    }
    
    /***********************************************/
    
    private void fillFields(){
    	
    	dbGetStatusValues();
    	
    	dbGetCountries();
    	
    	fillShippingCompaniesSelect();
    	
    	fillTypes();
    	dbGetNurses();
    	dbGetPatients();
    }
    
    private void limitStatusValues() {
        
        if(!userGroupString.equals("nurse")) {
            return;
        }
        
        Container con = status.getContainerDataSource();
        
        ArrayList<Integer> list = new ArrayList<Integer>();
        
        for (Object sid : con.getItemIds()) {
            list.add((Integer) sid);
        }
        
        Integer currentIndex = list.indexOf(status.getValue());
        
        ArrayList<Integer> remove = new ArrayList<Integer>();
        
        for (Integer sid : list) {
            if(list.indexOf(sid) < currentIndex) {
                remove.add(sid);
            }
        }
        
        for (Integer rid : remove) {
            
            con.removeItem(rid);
            
        }
        
    }
    
    private void fillShippingCompaniesSelect(){
    	
    	DBClass db = new DBClass();
    	
    	db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("SC_ID");
    	db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("SC_NAME");
    	db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_shipping_companies");
    	
        try {
        	shippingCompany.removeAllItems();
            new combo(db.DB_Data_Get.DB_SEND_AND_GET(), shippingCompany, "SC_ID", "SC_NAME");
        } catch (Exception e) {
        	shippingCompany.removeAllItems();
            return;
        }
    	
    }
    
    private void fillTypes() {
        for (TITYPE type : TITYPE.values()) {
            typeSelector.addItem(type.name());
            typeSelector.setItemCaption(type.name(), i18n.get(type.name()));
        }
    }
    
    /******************** Database *****************/
    private void fillDbMap() {
    	dbMap = new HashMap<>();
        dbMapReadonly = new HashMap<>();
//        dbMap.put(component, "table:COLUMN");
        
        String table = "cust_ordermanager_tickets:";
        
        dbMapReadonly.put(statusPlacedUser, table + "creator");
        dbMapReadonly.put(statusPlacedDate, table + "OMT_STATUS_ORDER_DATE");
        dbMapReadonly.put(statusPreparingUser, table + "preperator");
        dbMapReadonly.put(statusPreparingDate, table + "OMT_STATUS_PREPARING_DATE");
        dbMapReadonly.put(statusSentUser, table + "sender");
        dbMapReadonly.put(statusSentDate, table + "OMT_STATUS_SENT_DATE");
        dbMapReadonly.put(statusReceivedUser, table + "recipient");
        dbMapReadonly.put(statusReceivedDate, table + "OMT_STATUS_RECEIVED_DATE");
        
        dbMapReadonly.put(date_updated, table + "OMT_UPDATED");
        
//        dbMapReadonly.put(nurse, table + "nurse");
        dbMapReadonly.put(ticket_from, table + "OMT_DATE_FROM");
        dbMapReadonly.put(ticket_until, table + "OMT_DATE_UNTIL");
        
        dbMap.put(date_delivery, table + "OMT_DELIVERY_DATE");
        
        dbMap.put(shippingCompany, table + "OMT_ID_SHIPPING_COMPANY");
        
        dbMap.put(status, table + "OMT_ID_STATUS");
        
        dbMap.put(countryCode, table + "OMT_KEY_COUNTRY");
        
        dbMap.put(statusPlacedComment, table + "OMT_STATUS_ORDER_COMMENT");
        dbMap.put(statusPreparingComment, table + "OMT_STATUS_PREPARING_COMMENT");
        dbMap.put(statusSentComment, table + "OMT_STATUS_SENT_COMMENT");
        dbMap.put(statusReceivedComment, table + "OMT_STATUS_RECEIVED_COMMENT");
        
        dbMap.put(typeSelector, table + "OMT_TYPE");
        dbMap.put(nurse, table + "OMT_ID_USER");
        dbMap.put(patient, table + "OMT_ID_PATIENT");

    }
    
    private void dbGetNurses() {
        CustomQuery q = new DBClass().CustomQuery;
        q.setSqlString("SELECT AUL_ID, CONCAT(AUL_VORNAME, ' ', AUL_NAME) AS nurse"
             + "\n " + "FROM cms_auth_stammdaten_user"
             + "\n " + "INNER JOIN cust_krankenschwester_stammdaten_ks on AUL_ID = KSK_U_ID"
             + "\n " + "WHERE AUL_USERNAME != '' AND AUL_ID != 1"
             + "\n " + "ORDER BY AUL_NAME ASC");
//        q.db.debugNextQuery(true);
        
        nurse.setContainerDataSource(MyUtils.convertIndex(q.query(), "AUL_ID"));
    }
    
    private void dbGetPatients() {
        CustomQuery q = new DBClass().CustomQuery;
        q.setSqlString("select PSL_ID, CONCAT(PSA_NAME, ' ', PSL_VORNAME, ' ', PSL_NAME) as patient"
             + "\n " + "from cust_patient_stammdaten_liste"
             + "\n " + "left join cust_patient_stammdaten_anrede on PSL_ANREDE = PSA_ID");
//        q.db.debugNextQuery(true);
        
        patient.setContainerDataSource(MyUtils.convertIndex(q.query(), "PSL_ID"));
    }
    
    private void dbGetStatusValues() {
    	
        DBClass db = new DBClass();
        
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("OMMS_ID");
        
    	SetQueryStatusLng qsl = new SetQueryStatusLng();
    	qsl.setStatus(db);
        
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_ordermanager_master_status");
        
//        db.debugNextQuery(false);
        
        Container con = MyUtils.convertIndex(db.DB_Data_Get.DB_SEND_AND_GET_Container(), "OMMS_ID");
        status.setContainerDataSource(con);

    }
    
    private Container dbGetContainer() {
        DBClass db = new DBClass();
        
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln(dataTableName + ".*");
//        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(cms_auth_stammdaten_user.AUL_VORNAME, ' ', cms_auth_stammdaten_user.AUL_NAME)", "'nurse'");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(c.AUL_VORNAME, ' ', c.AUL_NAME)", "'creator'");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(prep.AUL_VORNAME, ' ', prep.AUL_NAME)", "'preperator'");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(send.AUL_VORNAME, ' ', send.AUL_NAME)", "'sender'");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(rec.AUL_VORNAME, ' ', rec.AUL_NAME)", "'recipient'");
//        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("PSLV_NAME");
        /******************************** Table ****************************************/
//        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_ordermanager_tickets", "LEFT JOIN", "cust_ordermanager_orders", "OMT_ID_ORDER", "OMO_ID");
      
        //nurse
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_ordermanager_tickets", "LEFT JOIN", "cms_auth_stammdaten_user", "OMT_ID_USER", "AUL_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_stammdaten_user", "RIGHT JOIN", "cust_krankenschwester_stammdaten_anrede", "AUL_ANREDE_ID", "KSA_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_krankenschwester_stammdaten_ks", "RIGHT JOIN", "cms_auth_stammdaten_user", "KSK_U_ID", "AUL_ID");
        
        //status users
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung_Graph("LEFT JOIN", "cms_auth_stammdaten_user AS c", "c", "cust_ordermanager_tickets", "AUL_ID", "OMT_STATUS_ORDER_ID_USER");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung_Graph("LEFT JOIN", "cms_auth_stammdaten_user AS prep", "prep", "cust_ordermanager_tickets", "AUL_ID", "OMT_STATUS_PREPARING_ID_USER");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung_Graph("LEFT JOIN", "cms_auth_stammdaten_user AS send", "send", "cust_ordermanager_tickets", "AUL_ID", "OMT_STATUS_SENT_ID_USER");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung_Graph("LEFT JOIN", "cms_auth_stammdaten_user AS rec", "rec", "cust_ordermanager_tickets", "AUL_ID", "OMT_STATUS_RECEIVED_ID_USER");

        //project
        //db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_ordermanager_orders", "INNER JOIN", "cust_projekte_stammdaten_liste", "OMO_ID_PROJECT", "PSLV_ID");
        
        
        /******************************************************************************/
        /******************************** Filter ****************************************/
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein(dataTableName, dataIdCol, "=", dataSetId, "");
        /******************************************************************************/

        db.DB_Data_Get.Set_Type("OMT_STATUS_SENT_DATE", java.sql.Timestamp.class);
        db.DB_Data_Get.Set_Type("OMT_STATUS_RECEIVED_DATE", java.sql.Timestamp.class);
        
        db.DB_Data_Get.Set_Type("OMT_STATUS_ORDER_DATE", java.sql.Timestamp.class);
        db.DB_Data_Get.Set_Type("OMT_UPDATED", java.sql.Timestamp.class);
        db.DB_Data_Get.Set_Type("OMT_DELIVERY_DATE", java.sql.Date.class);
        
//        db.debugNextQuery(true);
        
        return db.DB_Data_Get.DB_SEND_AND_GET_Container();
    }
    
    private void dbFillForm() {
    	
        Container con = dbGetContainer();
        
        fb = new Form_Bind();
        
        if(con.size() > 0){
        	
            pauseLocation = true;
            
            dataItem = MyUtils.getFirstItemFromContainer(con);
//            Object cid = con.getItemIds().iterator().next();
            
            ticketContentsPanel.setTicketRange(
                MyUtils.getValueFromItem(dataItem, "OMT_DATE_FROM", Date.class),
                MyUtils.getValueFromItem(dataItem, "OMT_DATE_UNTIL", Date.class));
            ticketContentsPanel.setTicketDeliveryDate(
                MyUtils.getValueFromItem(dataItem, "OMT_DELIVERY_DATE", Date.class));
            
            
            
            previousStatus = MyUtils.getValueFromItem(dataItem, "OMT_ID_STATUS", Integer.class); // (Integer) con.getContainerProperty(cid, "OMT_ID_STATUS").getValue();
            balanceModified = MyUtils.getValueFromItem(dataItem, "OMT_BALANCE_MODIFIED", Boolean.class); //  (Boolean) con.getContainerProperty(cid, "OMT_BALANCE_MODIFIED").getValue();
            Integer location = MyUtils.getValueFromItem(dataItem, "OMT_ID_LOCATION", Integer.class); // (Integer) con.getContainerProperty(cid, "OMT_ID_LOCATION").getValue();
            
            try {
                log.info("fillForm ttype {}", TITYPE.get(MyUtils.getValueFromItem(dataItem, "OMT_TYPE", String.class)));
                locationPanelModule.setEntryType(TITYPE.get(MyUtils.getValueFromItem(dataItem, "OMT_TYPE", String.class)));
                
                Integer user = MyUtils.getValueFromItem(dataItem, "OMT_ID_USER", Integer.class); 
                if(user != null) {
                    locationPanelModule.setUser(user);
                }
                
                Integer patient = MyUtils.getValueFromItem(dataItem, "OMT_ID_PATIENT", Integer.class);
                if(patient != null) {
                    locationPanelModule.setPatient(patient);
                }
                
                locationPanelModule.setValue(location);
            } catch (Exception e) {
                System.out.println("user id was null");
            }
            
        	fb.Get_and_Fill(con, dbMap);
        	fb.Get_and_Fill(con, dbMapReadonly);
        	
        	pauseLocation = false;
        }
        
    }

//    private int dbInsert() {
//        DBClass db = new DBClass(std.Standard_Server_URL, std.Standard_Server_Username, std.Standard_Server_Passwort, std.Standard_Server_Database,
//                std.Standard_Server_Port);
//        fb = new Form_Bind();
//        fb.Insert(db, dbMap);
//        /******************************** Table ****************************************/
//        db.DB_Data_Insert.DB_Tabellen.DB_set_Tabelle_Einzeln(dataTableName);
//        /******************************************************************************/
//        // dba.DB_Data_Insert.DB_DEBUG_SQL_STRING();
//        return db.DB_Data_Insert.DB_Insert();
//    }
    
    private Boolean checkIntegrity() {
        return MyUtils.checkItemIntegrity(dataItem, MyUtils.getFirstItemFromContainer(dbGetContainer()));
    }
    
    private void fillStatusFields(DBClass db) {
        
        // no breaks in switch to fall through for lower status values!
        
        Integer id = (Integer) status.getValue();
        
        log.info("id {}", id);
        
        String user = UI.getCurrent().getSession().getSession().getAttribute("Userid").toString();
        String date = MyUtils.formatSqlDate(new LocalDateTime());
        
        switch (id) {
        case 5:
            db.DB_Data_Update.DB_Daten.DB_Data(dataTableName, "OMT_STATUS_ORDER_ID_USER", null);
            db.DB_Data_Update.DB_Daten.DB_Data(dataTableName, "OMT_STATUS_ORDER_DATE", null);
            
        case 10:
            db.DB_Data_Update.DB_Daten.DB_Data(dataTableName, "OMT_STATUS_PREPARING_ID_USER", null);
            db.DB_Data_Update.DB_Daten.DB_Data(dataTableName, "OMT_STATUS_PREPARING_DATE", null);

        case 15:
            db.DB_Data_Update.DB_Daten.DB_Data(dataTableName, "OMT_STATUS_SENT_ID_USER", null);
            db.DB_Data_Update.DB_Daten.DB_Data(dataTableName, "OMT_STATUS_SENT_DATE", null);
            
        case 20:
            db.DB_Data_Update.DB_Daten.DB_Data(dataTableName, "OMT_STATUS_RECEIVED_ID_USER", null);
            db.DB_Data_Update.DB_Daten.DB_Data(dataTableName, "OMT_STATUS_RECEIVED_DATE", null);

        default:
            break;
        }
        
        
        switch (id) {
        case 30:
            if(statusReceivedUser.getValue() == null) {
                db.DB_Data_Update.DB_Daten.DB_Data(dataTableName, "OMT_STATUS_RECEIVED_ID_USER", user);
            }
            if(statusReceivedDate.getValue() == null) {
                db.DB_Data_Update.DB_Daten.DB_Data(dataTableName, "OMT_STATUS_RECEIVED_DATE", date);
            } 
        case 20:
            if(statusSentUser.getValue() == null) {
                db.DB_Data_Update.DB_Daten.DB_Data(dataTableName, "OMT_STATUS_SENT_ID_USER", user);
            }
            if(statusSentDate.getValue() == null) {
                db.DB_Data_Update.DB_Daten.DB_Data(dataTableName, "OMT_STATUS_SENT_DATE", date);
            }            
        case 15:
            if(statusPreparingUser.getValue() == null) {
                db.DB_Data_Update.DB_Daten.DB_Data(dataTableName, "OMT_STATUS_PREPARING_ID_USER", user);
            }
            if(statusPreparingDate.getValue() == null) {
                db.DB_Data_Update.DB_Daten.DB_Data(dataTableName, "OMT_STATUS_PREPARING_DATE", date);
            }
        case 10:
            if(statusPlacedUser.getValue() == null) {
                db.DB_Data_Update.DB_Daten.DB_Data(dataTableName, "OMT_STATUS_ORDER_ID_USER", user);
            }
            if(statusPlacedDate.getValue() == null) {
                db.DB_Data_Update.DB_Daten.DB_Data(dataTableName, "OMT_STATUS_ORDER_DATE", date);
            }
        default:
            break;
        }
    }
    
    private void finalizeType() {
        if(!nurse.isVisible()) {
            nurse.setValue(null);
        }
        if(!patient.isVisible()){
            patient.setValue(null);
        }
    }
    
    private void dbUpdate() {
    	
        DBClass db = new DBClass();
        
        fb = new Form_Bind();
        fb.Update(db, dbMap);
        
        fillStatusFields(db);
        
        db.DB_Data_Update.DB_Daten.DB_Data(dataTableName, "OMT_BALANCE_MODIFIED", balanceModified ? "1" : "0");
        db.DB_Data_Update.DB_Daten.DB_Data(dataTableName, "OMT_ID_LOCATION", locationPanelModule.getValue() != null ? locationPanelModule.getValue().toString() : null);
        
        
        /******************************** Table ****************************************/
        db.DB_Data_Update.DB_Tabellen.DB_set_Tabelle_Einzeln(dataTableName);
        /******************************************************************************/
        /******************************** Filter ****************************************/
        db.DB_Data_Update.DB_Filter.DB_WHERE_Allgemein(dataTableName, dataIdCol, "=", dataSetId, "");
        /******************************************************************************/
        db.debugNextQuery(false);
        db.DB_Data_Update.DB_Update();

    }
    
    private void dbGetCountries() {
        
        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("*");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_countrycodes");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_countrycodes", "CC_LNG", "=", "1", "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_In("cust_countrycodes", "CC_CODE", "'DE', 'AT'", "");
        
        Container con = MyUtils.convertIndex(db.DB_Data_Get.DB_SEND_AND_GET(), "CC_CODE");
        countryCode.setContainerDataSource(con);
        
    }


    /*********************** -->Validierung<-- ********************/
    private void fillValidateMap() {
        validateMap = new HashMap<>();
        validateMap.putAll(componentMap);
        
//        ValidateMap.put(component, "component"); // should not be needed

    }

    private void setCustomValidators() {

        // psw_pass_1.addValidator(new Custom_Benutzerform_psw_ändern(psw_pass_1, psw_pass_2));

        /******* manual actions *******/

    }

    private boolean validate() {
        val_checker4 val = new val_checker4(validateMap);
        if (val.Is_Valid() == false) {
            return false;
        } else {
            return true;
        }

    }

    @AutoGenerated
    private VerticalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setStyleName("cust_margin_half_full_none_full");
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(true);
        mainLayout.setSpacing(true);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // topLayout
        topLayout = buildTopLayout();
        mainLayout.addComponent(topLayout);
        mainLayout.setExpandRatio(topLayout, 1.0f);
        
        // buttons
        buttons = buildButtons();
        mainLayout.addComponent(buttons);
        
        return mainLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildTopLayout() {
        // common part: create layout
        topLayout = new HorizontalLayout();
        topLayout.setStyleName("cust_margin_half_full_none_full");
        topLayout.setImmediate(false);
        topLayout.setWidth("100.0%");
        topLayout.setHeight("100.0%");
        topLayout.setMargin(false);
        topLayout.setSpacing(true);
        
        // verticalLayout_2
        verticalLayout_2 = buildVerticalLayout_2();
        topLayout.addComponent(verticalLayout_2);
        
        // tabSheet_1
        tabSheet_1 = buildTabSheet_1();
        topLayout.addComponent(tabSheet_1);
        topLayout.setExpandRatio(tabSheet_1, 1.0f);
        
        return topLayout;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_2() {
        // common part: create layout
        verticalLayout_2 = new VerticalLayout();
        verticalLayout_2.setImmediate(false);
        verticalLayout_2.setWidth("400px");
        verticalLayout_2.setHeight("100.0%");
        verticalLayout_2.setMargin(false);
        verticalLayout_2.setSpacing(true);
        
        // generalLayout
        generalLayout = buildGeneralLayout();
        verticalLayout_2.addComponent(generalLayout);
        verticalLayout_2.setExpandRatio(generalLayout, 7.0f);
        
        // StatusLayout
        StatusLayout = buildStatusLayout();
        verticalLayout_2.addComponent(StatusLayout);
        
        return verticalLayout_2;
    }

    @AutoGenerated
    private HorizontalLayout buildGeneralLayout() {
        // common part: create layout
        generalLayout = new HorizontalLayout();
        generalLayout.setImmediate(false);
        generalLayout.setWidth("100.0%");
        generalLayout.setHeight("100.0%");
        generalLayout.setMargin(false);
        
        // ticketGeneralPanel
        ticketGeneralPanel = buildTicketGeneralPanel();
        generalLayout.addComponent(ticketGeneralPanel);
        generalLayout.setExpandRatio(ticketGeneralPanel, 1.0f);
        
        // locationPanelModule
        locationPanelModule = new LocationPanel();
        locationPanelModule.setStyleName("cust_margin_none");
        locationPanelModule.setImmediate(false);
        locationPanelModule.setWidth("100.0%");
        locationPanelModule.setHeight("100.0%");
        generalLayout.addComponent(locationPanelModule);
        generalLayout.setExpandRatio(locationPanelModule, 1.0f);
        
        return generalLayout;
    }

    @AutoGenerated
    private Panel buildTicketGeneralPanel() {
        // common part: create layout
        ticketGeneralPanel = new Panel();
        ticketGeneralPanel.setCaption("Allgemein");
        ticketGeneralPanel.setImmediate(false);
        ticketGeneralPanel.setWidth("100.0%");
        ticketGeneralPanel.setHeight("100.0%");
        
        // ticketGeneralLayout
        ticketGeneralLayout = buildTicketGeneralLayout();
        ticketGeneralPanel.setContent(ticketGeneralLayout);
        
        return ticketGeneralPanel;
    }

    @AutoGenerated
    private VerticalLayout buildTicketGeneralLayout() {
        // common part: create layout
        ticketGeneralLayout = new VerticalLayout();
        ticketGeneralLayout.setStyleName("cust_margin_half_full_none_full");
        ticketGeneralLayout.setImmediate(false);
        ticketGeneralLayout.setWidth("100.0%");
        ticketGeneralLayout.setHeight("100.0%");
        ticketGeneralLayout.setMargin(true);
        
        // date_updated
        date_updated = new DateFieldDisplay();
        date_updated.setCaption("Geändert");
        date_updated.setImmediate(false);
        date_updated.setWidth("100.0%");
        date_updated.setHeight("-1px");
        ticketGeneralLayout.addComponent(date_updated);
        
        // layoutType
        layoutType = buildLayoutType();
        ticketGeneralLayout.addComponent(layoutType);
        
        // layoutTypeTargets
        layoutTypeTargets = buildLayoutTypeTargets();
        ticketGeneralLayout.addComponent(layoutTypeTargets);
        
        // horizontalLayout_1
        horizontalLayout_1 = buildHorizontalLayout_1();
        ticketGeneralLayout.addComponent(horizontalLayout_1);
        
        // intendedLayout
        intendedLayout = buildIntendedLayout();
        ticketGeneralLayout.addComponent(intendedLayout);
        
        // shippingCompany
        shippingCompany = new ComboBox();
        shippingCompany.setCaption("Spedition");
        shippingCompany.setImmediate(false);
        shippingCompany.setWidth("100.0%");
        shippingCompany.setHeight("-1px");
        ticketGeneralLayout.addComponent(shippingCompany);
        
        // status
        status = new ComboBox();
        status.setCaption("Status");
        status.setImmediate(false);
        status.setWidth("100.0%");
        status.setHeight("-1px");
        ticketGeneralLayout.addComponent(status);
        
        return ticketGeneralLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildLayoutType() {
        // common part: create layout
        layoutType = new HorizontalLayout();
        layoutType.setImmediate(false);
        layoutType.setWidth("100.0%");
        layoutType.setHeight("-1px");
        layoutType.setMargin(false);
        
        // typeSelector
        typeSelector = new ComboBox();
        typeSelector.setCaption("Typ");
        typeSelector.setImmediate(false);
        typeSelector.setWidth("80px");
        typeSelector.setHeight("-1px");
        layoutType.addComponent(typeSelector);
        layoutType.setComponentAlignment(typeSelector, new Alignment(33));
        
        // countryCode
        countryCode = new ComboBox();
        countryCode.setCaption("Apotheke");
        countryCode.setImmediate(false);
        countryCode.setWidth("100.0%");
        countryCode.setHeight("-1px");
        layoutType.addComponent(countryCode);
        
        return layoutType;
    }

    @AutoGenerated
    private VerticalLayout buildLayoutTypeTargets() {
        // common part: create layout
        layoutTypeTargets = new VerticalLayout();
        layoutTypeTargets.setImmediate(false);
        layoutTypeTargets.setWidth("100.0%");
        layoutTypeTargets.setHeight("100.0%");
        layoutTypeTargets.setMargin(false);
        
        // nurse
        nurse = new ComboBox();
        nurse.setCaption("Nurse");
        nurse.setImmediate(false);
        nurse.setWidth("100.0%");
        nurse.setHeight("-1px");
        layoutTypeTargets.addComponent(nurse);
        
        // patient
        patient = new ComboBox();
        patient.setCaption("Patient");
        patient.setImmediate(false);
        patient.setWidth("100.0%");
        patient.setHeight("-1px");
        layoutTypeTargets.addComponent(patient);
        
        return layoutTypeTargets;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_1() {
        // common part: create layout
        horizontalLayout_1 = new HorizontalLayout();
        horizontalLayout_1.setImmediate(false);
        horizontalLayout_1.setWidth("100.0%");
        horizontalLayout_1.setHeight("-1px");
        horizontalLayout_1.setMargin(false);
        horizontalLayout_1.setSpacing(true);
        
        // ticket_from
        ticket_from = new DateFieldDisplay();
        ticket_from.setCaption("Ticket Start");
        ticket_from.setImmediate(false);
        ticket_from.setWidth("100.0%");
        ticket_from.setHeight("-1px");
        horizontalLayout_1.addComponent(ticket_from);
        
        // ticket_until
        ticket_until = new DateFieldDisplay();
        ticket_until.setCaption("Ticket Ende");
        ticket_until.setImmediate(false);
        ticket_until.setWidth("100.0%");
        ticket_until.setHeight("-1px");
        horizontalLayout_1.addComponent(ticket_until);
        
        return horizontalLayout_1;
    }

    @AutoGenerated
    private HorizontalLayout buildIntendedLayout() {
        // common part: create layout
        intendedLayout = new HorizontalLayout();
        intendedLayout.setImmediate(false);
        intendedLayout.setWidth("100.0%");
        intendedLayout.setHeight("-1px");
        intendedLayout.setMargin(false);
        intendedLayout.setSpacing(true);
        
        // date_delivery
        date_delivery = new PopupDateField();
        date_delivery.setCaption("Planlieferung");
        date_delivery.setImmediate(false);
        date_delivery.setWidth("100.0%");
        date_delivery.setHeight("-1px");
        intendedLayout.addComponent(date_delivery);
        
        return intendedLayout;
    }

    @AutoGenerated
    private VerticalLayout buildStatusLayout() {
        // common part: create layout
        StatusLayout = new VerticalLayout();
        StatusLayout.setImmediate(false);
        StatusLayout.setWidth("100.0%");
        StatusLayout.setHeight("-1px");
        StatusLayout.setMargin(false);
        StatusLayout.setSpacing(true);
        
        // commentNotification
        commentNotification = new Label();
        commentNotification.setStyleName("highlight-red");
        commentNotification.setImmediate(false);
        commentNotification.setWidth("-1px");
        commentNotification.setHeight("-1px");
        commentNotification.setValue("commentNotification");
        StatusLayout.addComponent(commentNotification);
        StatusLayout.setComponentAlignment(commentNotification, new Alignment(6));
        
        // horizontalLayout_2
        horizontalLayout_2 = buildHorizontalLayout_2();
        StatusLayout.addComponent(horizontalLayout_2);
        
        // horizontalLayout_3
        horizontalLayout_3 = buildHorizontalLayout_3();
        StatusLayout.addComponent(horizontalLayout_3);
        
        // horizontalLayout_4
        horizontalLayout_4 = buildHorizontalLayout_4();
        StatusLayout.addComponent(horizontalLayout_4);
        
        // horizontalLayout_5
        horizontalLayout_5 = buildHorizontalLayout_5();
        StatusLayout.addComponent(horizontalLayout_5);
        
        return StatusLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_2() {
        // common part: create layout
        horizontalLayout_2 = new HorizontalLayout();
        horizontalLayout_2.setCaption("Bestellt");
        horizontalLayout_2.setImmediate(false);
        horizontalLayout_2.setWidth("100.0%");
        horizontalLayout_2.setHeight("-1px");
        horizontalLayout_2.setMargin(false);
        horizontalLayout_2.setSpacing(true);
        
        // statusPlacedDate
        statusPlacedDate = new DateFieldDisplay();
        statusPlacedDate.setImmediate(false);
        statusPlacedDate.setWidth("100.0%");
        statusPlacedDate.setHeight("-1px");
        horizontalLayout_2.addComponent(statusPlacedDate);
        
        // statusPlacedUser
        statusPlacedUser = new TextField();
        statusPlacedUser.setImmediate(false);
        statusPlacedUser.setWidth("100.0%");
        statusPlacedUser.setHeight("-1px");
        horizontalLayout_2.addComponent(statusPlacedUser);
        
        return horizontalLayout_2;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_3() {
        // common part: create layout
        horizontalLayout_3 = new HorizontalLayout();
        horizontalLayout_3.setCaption("Vorbereitung");
        horizontalLayout_3.setImmediate(false);
        horizontalLayout_3.setWidth("100.0%");
        horizontalLayout_3.setHeight("-1px");
        horizontalLayout_3.setMargin(false);
        horizontalLayout_3.setSpacing(true);
        
        // statusPreparingDate
        statusPreparingDate = new DateFieldDisplay();
        statusPreparingDate.setImmediate(false);
        statusPreparingDate.setWidth("100.0%");
        statusPreparingDate.setHeight("-1px");
        horizontalLayout_3.addComponent(statusPreparingDate);
        
        // statusPreparingUser
        statusPreparingUser = new TextField();
        statusPreparingUser.setImmediate(false);
        statusPreparingUser.setWidth("100.0%");
        statusPreparingUser.setHeight("-1px");
        horizontalLayout_3.addComponent(statusPreparingUser);
        
        return horizontalLayout_3;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_4() {
        // common part: create layout
        horizontalLayout_4 = new HorizontalLayout();
        horizontalLayout_4.setCaption("Versendet");
        horizontalLayout_4.setImmediate(false);
        horizontalLayout_4.setWidth("100.0%");
        horizontalLayout_4.setHeight("-1px");
        horizontalLayout_4.setMargin(false);
        horizontalLayout_4.setSpacing(true);
        
        // statusSentDate
        statusSentDate = new DateFieldDisplay();
        statusSentDate.setImmediate(false);
        statusSentDate.setWidth("100.0%");
        statusSentDate.setHeight("-1px");
        horizontalLayout_4.addComponent(statusSentDate);
        
        // statusSentUser
        statusSentUser = new TextField();
        statusSentUser.setImmediate(false);
        statusSentUser.setWidth("100.0%");
        statusSentUser.setHeight("-1px");
        horizontalLayout_4.addComponent(statusSentUser);
        
        return horizontalLayout_4;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_5() {
        // common part: create layout
        horizontalLayout_5 = new HorizontalLayout();
        horizontalLayout_5.setCaption("Empfangen");
        horizontalLayout_5.setImmediate(false);
        horizontalLayout_5.setWidth("100.0%");
        horizontalLayout_5.setHeight("-1px");
        horizontalLayout_5.setMargin(false);
        horizontalLayout_5.setSpacing(true);
        
        // statusReceivedDate
        statusReceivedDate = new DateFieldDisplay();
        statusReceivedDate.setImmediate(false);
        statusReceivedDate.setWidth("100.0%");
        statusReceivedDate.setHeight("-1px");
        horizontalLayout_5.addComponent(statusReceivedDate);
        
        // statusReceivedUser
        statusReceivedUser = new TextField();
        statusReceivedUser.setImmediate(false);
        statusReceivedUser.setWidth("100.0%");
        statusReceivedUser.setHeight("-1px");
        horizontalLayout_5.addComponent(statusReceivedUser);
        
        return horizontalLayout_5;
    }

    @AutoGenerated
    private TabSheet buildTabSheet_1() {
        // common part: create layout
        tabSheet_1 = new TabSheet();
        tabSheet_1.setImmediate(true);
        tabSheet_1.setWidth("100.0%");
        tabSheet_1.setHeight("100.0%");
        
        // ticketContentsPanel
        ticketContentsPanel = new TicketContentsPanel();
        ticketContentsPanel.setImmediate(false);
        ticketContentsPanel.setWidth("100.0%");
        ticketContentsPanel.setHeight("100.0%");
        tabSheet_1.addTab(ticketContentsPanel, "Inhalt", null);
        
        // verticalLayout_3
        verticalLayout_3 = buildVerticalLayout_3();
        tabSheet_1.addTab(verticalLayout_3, "Kommentare", null);
        
        return tabSheet_1;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_3() {
        // common part: create layout
        verticalLayout_3 = new VerticalLayout();
        verticalLayout_3.setImmediate(false);
        verticalLayout_3.setWidth("100.0%");
        verticalLayout_3.setHeight("100.0%");
        verticalLayout_3.setMargin(true);
        verticalLayout_3.setSpacing(true);
        
        // statusPlacedComment
        statusPlacedComment = new TextArea();
        statusPlacedComment.setStyleName("cust_textarea_no_margin");
        statusPlacedComment.setCaption("Bestellt");
        statusPlacedComment.setImmediate(false);
        statusPlacedComment.setWidth("100.0%");
        statusPlacedComment.setHeight("90.0%");
        verticalLayout_3.addComponent(statusPlacedComment);
        
        // statusPreparingComment
        statusPreparingComment = new TextArea();
        statusPreparingComment.setStyleName("cust_textarea_no_margin");
        statusPreparingComment.setCaption("Vorbereitung");
        statusPreparingComment.setImmediate(false);
        statusPreparingComment.setWidth("100.0%");
        statusPreparingComment.setHeight("90.0%");
        verticalLayout_3.addComponent(statusPreparingComment);
        
        // statusSentComment
        statusSentComment = new TextArea();
        statusSentComment.setStyleName("cust_textarea_no_margin");
        statusSentComment.setCaption("Versand");
        statusSentComment.setImmediate(false);
        statusSentComment.setWidth("100.0%");
        statusSentComment.setHeight("90.0%");
        verticalLayout_3.addComponent(statusSentComment);
        
        // statusReceivedComment
        statusReceivedComment = new TextArea();
        statusReceivedComment.setStyleName("cust_textarea_no_margin");
        statusReceivedComment.setCaption("Empfang");
        statusReceivedComment.setImmediate(false);
        statusReceivedComment.setWidth("100.0%");
        statusReceivedComment.setHeight("90.0%");
        verticalLayout_3.addComponent(statusReceivedComment);
        
        return verticalLayout_3;
    }

    @AutoGenerated
    private HorizontalLayout buildButtons() {
        // common part: create layout
        buttons = new HorizontalLayout();
        buttons.setImmediate(false);
        buttons.setWidth("100.0%");
        buttons.setHeight("-1px");
        buttons.setMargin(true);
        
        // deleteTicket
        deleteTicket = new Button();
        deleteTicket.setCaption("Zurücksetzen");
        deleteTicket.setImmediate(true);
        deleteTicket.setWidth("-1px");
        deleteTicket.setHeight("-1px");
        buttons.addComponent(deleteTicket);
        buttons.setComponentAlignment(deleteTicket, new Alignment(48));
        
        // downloadExport
        downloadExport = new Button();
        downloadExport.setCaption("Packschein");
        downloadExport.setImmediate(true);
        downloadExport.setWidth("-1px");
        downloadExport.setHeight("-1px");
        buttons.addComponent(downloadExport);
        buttons.setComponentAlignment(downloadExport, new Alignment(48));
        
        // btn_save
        btn_save = new Button();
        btn_save.setCaption("Speichern");
        btn_save.setImmediate(true);
        btn_save.setWidth("-1px");
        btn_save.setHeight("-1px");
        buttons.addComponent(btn_save);
        buttons.setComponentAlignment(btn_save, new Alignment(48));
        
        // orderTicket
        orderTicket = new Button();
        orderTicket.setCaption("Bestellen");
        orderTicket.setImmediate(true);
        orderTicket.setWidth("-1px");
        orderTicket.setHeight("-1px");
        buttons.addComponent(orderTicket);
        buttons.setComponentAlignment(orderTicket, new Alignment(48));
        
        // receivedTicket
        receivedTicket = new Button();
        receivedTicket.setCaption("Empfangen");
        receivedTicket.setImmediate(true);
        receivedTicket.setWidth("-1px");
        receivedTicket.setHeight("-1px");
        buttons.addComponent(receivedTicket);
        buttons.setComponentAlignment(receivedTicket, new Alignment(48));
        
        return buttons;
    }

}
