package archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.OpenTickets.form;

import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;

import org.joda.time.LocalDate;
import org.tepi.filtertable.FilterTable;

import archenoah.config.CMS_Config_Std;
import archenoah.lib.custom.ComponentIterator;
import archenoah.lib.custom.MyUtils;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.tool.comunication.dbclass.DBClass.CustomQuery;
import archenoah.lib.vaadin.Components.ClickMenuBar.ClickCommand;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Tab_Menue_Item;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Window_Button;
import archenoah.lib.vaadin.Components.table.FilteringTableUpdater;
import archenoah.lib.vaadin.CustomConverterFactorys.StringSqlTimestampConverter;
import archenoah.lib.vaadin.Language.i18n.I18nCB;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalMessages;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.lib.vaadin.MenuBerechtigung.Rechteholen;
import archenoah.lib.vaadin.resources.Icons;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.OpenTickets.classes.DbGetTicketContents;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.OpenTickets.classes.SetQueryStatusLng;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.PackageCreator.classes.TicketDbActions;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.classes.UserAttributesCountry;

import com.google.common.base.Joiner;
import com.google.gwt.thirdparty.guava.common.base.Strings;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.shared.ui.datefield.Resolution;
import com.vaadin.ui.AbstractComponent;
import com.vaadin.ui.AbstractField;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.Command;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TwinColSelect;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.Window.CloseEvent;
import com.vaadin.ui.Window.CloseListener;

import de.steinwedel.messagebox.ButtonId;
import de.steinwedel.messagebox.MessageBoxListener;


@SuppressWarnings({"serial", "rawtypes", "unchecked"})
public class OpenTicketsDataView extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private HorizontalLayout mainLayout;

    @AutoGenerated
    private VerticalLayout mainContainer;

    @AutoGenerated
    private FilterTable tbl_data;

    @AutoGenerated
    private HorizontalLayout globalFilterContainer;

    @AutoGenerated
    private HorizontalLayout filterStatusContainer;

    @AutoGenerated
    private TwinColSelect filterStatus;

    @AutoGenerated
    private CheckBox filterStatusEnabled;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_2;

    @AutoGenerated
    private Button filterPatientReset;

    @AutoGenerated
    private ComboBox filterPatient;

    @AutoGenerated
    private HorizontalLayout filterMonthContainer;

    @AutoGenerated
    private PopupDateField filterMonth;

    @AutoGenerated
    private CheckBox filterMonthEnabled;

    @AutoGenerated
    private VerticalLayout menuSpacer;

    @AutoGenerated
    private MenuBar men_frm;

    

    

    

	

	

	

	

	

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */

    /**************** --> Allgemein <--- ********************/
	private org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(this.getClass());

    // Datenbank
    private Map<Object, String> componentMap;
    private FilteringTableUpdater tableUpdater = null;

    // Berrechtigung
    private int ACC_ID;

    private int permRead;
    private int permCreate;
    private int permUpdate;
    private int permDelete;

    private MenuItem tmpMenu = null;

    private Button tmpButton = null;
    /******************************************************/
    /**************** --> Tabsheetvars <--- *****************/
    private TabSheet tab = null;

    /******************************************************/
    /**************** --> Windowvars <--- *******************/
    private Window win = null;
    /******************************************************/

//    private DetachListener onDetach = null;

    /******************* -> Menüpunkte <- ********************/
    private MenuBar.MenuItem btn_create;
    private MenuBar.MenuItem btn_update;
    private MenuBar.MenuItem btn_read;
//    private MenuBar.MenuItem btn_delete;
    private MenuBar.MenuItem btn_filter;
    private MenuBar.MenuItem btn_export;
    private MenuBar.MenuItem btn_refresh;

    
    /*******************************************************/
    /******************* --> Custom <--- ********************/
    /******************************************************/

    private Boolean firstFilter = true;
//    private PollListener pollListener = null;
    
    private Integer nurseUserId = 0;
    
    enum Status {}
    enum Project {}
    enum Location {}
    
    private Integer oldTableSize = 0;
    
    DbGetTicketContents dbGetTicketContents;
    
    /************ ----->Einstellungen<-- ********************/
//    private final String formIdLng = "105";
    private final String formIdPerm = "105";
    private final String winHeight = "600px";
    private final String winWidth = "900px";


    /******************************************************/

    private final String tableIdCol = "OMT_ID";
    
    //TASK cols
    private final Object[] tableColsAll = new Object[] { "OMT_ID", "OMT_UPDATED", "OMT_STATUS_ORDER_DATE", "OMT_DELIVERY_DATE", "OMT_KEY_COUNTRY", "nurse", "OMT_DATE_FROM", "OMT_DATE_UNTIL", "custom_location", "STATUS", "OMT_STATUS_SENT_DATE", "OMT_STATUS_RECEIVED_DATE" };
    //use custom Cols when needed
    private Object[] tableColsDefault = tableColsAll;
    //use custom Cols when needed
    private final Object[] tableColsFilter = tableColsDefault;
    private Object[] tableColsActive = tableColsDefault;

    private ArrayList<String> countryKeyList;

    private I18nManager i18n;
    
    private final static class caption extends I18nCB {
        static final I18nCB order_placed = set();
        static final I18nCB nurse_sent = set();
        static final I18nCB nurse_received = set();
        static final I18nCB status_unknown = set();
        
        static final I18nCB location_custom = set();
        static final I18nCB location_default = set();
    }
    /******************************************************/

    public OpenTicketsDataView(MenuItem Arg_Menü) {
        tmpMenu = Arg_Menü;
    }

    public OpenTicketsDataView(Button Arg_btn) {
        tmpButton = Arg_btn;
    }

    /***************************** ---> Feste Funtionen<--- **************************************/

    /********* INIT-Window ************/
    public void init() {

        Standard_Init();

        if (tmpMenu != null) {
            String Recourcename = tmpMenu.getIcon().toString();
            Recourcename = Recourcename.substring(0, Recourcename.length() - 12) + "white-16.png";

            Build_Window_Button bwb = new Build_Window_Button(tmpMenu.getText(), mainLayout, winHeight, winWidth,
                    new ThemeResource(Recourcename));
            win = bwb.ReturnWindow();
        }
        if (tmpButton != null) {
            Build_Window_Button bwb = new Build_Window_Button(tmpButton.getCaption(), mainLayout, winHeight, winWidth,
                    tmpButton.getIcon());
            win = bwb.ReturnWindow();
        }

//        win.addDetachListener(onDetach);

    }
    
    public Window getWindow(){
    	return win;
    }
    
    public TabSheet getTabSheet(){
    	return tab;
    }
    
    public void init(TabSheet Arg_tab) {

        Standard_Init();
        tab = Arg_tab;
        if (tmpMenu != null) {
            new Build_Tab_Menue_Item(Arg_tab, tmpMenu.getText(), mainLayout, tmpMenu.getIcon());
        }
        if (tmpButton != null) {
            new Build_Tab_Menue_Item(Arg_tab, tmpButton.getCaption(), mainLayout, tmpButton.getIcon());
        }

//        tab.getSelectedTab().addDetachListener(onDetach);
    }

    /********* Init-Standard ************/
    private void Standard_Init() {
        buildMainLayout();
        i18n = new I18nManager(this);
        
        registerComponents();
        
        generateMenu();
        
        setNurseUserId();
        setCountryKey();
        
        setMenuPermissions();
        
        updateTable();
        tbl_data.setSortContainerPropertyId(tableIdCol);
        tbl_data.setSortAscending(true);
        tbl_data.sort();
//        configureTable();
        configureComponents();
//        setTableHeaders();
        
        setGlobalFilterMonth();
        
        updateTable();
        
//        setupListenersAndDetachEvent();
        
        dbGetTicketContents = new DbGetTicketContents();
        i18n.refresh();
        
    }
    
    // register components for lng and validation tools
    private void registerComponents(){
    	componentMap = new HashMap<Object, String>();
        new ComponentIterator(mainContainer).createMap(componentMap);
    }
    
//    private void setupListenersAndDetachEvent() {
//        pollListener = new PollListener() {
//
//            @Override
//            public void poll(PollEvent event) {
//    if(tab.isRendered(mainLayout)){
//        updateTable();
//    }
//            }
//        };
//
//        UI.getCurrent().getUI().addPollListener(pollListener);
//
//        onDetach = new DetachListener() {
//
//            @Override
//            public void detach(DetachEvent event) {
//                UI.getCurrent().getUI().removePollListener(pollListener);
//            }
//        };
//    }
    
    @SuppressWarnings("unused")
    public void setPermissionsFromDatabase() {
        if (formIdPerm == "") {
            System.out.println("Form Einstellung Fehlt: Berechtigung");
            return;
        }

        ACC_ID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        Rechteholen r = new Rechteholen(ACC_ID + "");
        String[][] perms = r.Datenholen();

        for (int i = 0; i < perms.length; i++) {
            if (perms[i][0].equals(formIdPerm) == true) {

                permRead = Integer.valueOf(perms[i][3]);
                permUpdate = Integer.valueOf(perms[i][4]);
                permCreate = Integer.valueOf(perms[i][6]);
                permDelete = Integer.valueOf(perms[i][5]);
                
            }
        }
    }

    public void setPermissions(int create, int read, int update, int delete) {

        permCreate = create;
        permRead = read;
        permUpdate = update;
        permDelete = delete;

    }

    private void setMenuPermissions() {
        Boolean c = (permCreate == 1);
        Boolean r = (permRead == 1);
        Boolean u = (permUpdate == 1);
        Boolean d = (permDelete == 1);

        btn_create.setEnabled(c);
        btn_create.setVisible(c);

        btn_read.setEnabled(r);
        btn_read.setVisible(r);

        btn_update.setEnabled(u);
        btn_update.setVisible(u);

//        btn_delete.setEnabled(d);
//        btn_delete.setVisible(d);
    }

    /************ -><- ******************/

    /***************** Comands *********************/
    
    CloseListener closeListener = new CloseListener() {
		
		@Override
		public void windowClose(CloseEvent e) {
			updateTable(true);
		}
	};
    
	private String getSelectedValue(){
		return Integer.toString((Integer) tbl_data.getContainerProperty(tbl_data.getValue(), tableIdCol).getValue());
	}
	
	
    //TASK Commands are here
    public ClickCommand cmd_btn_add = new ClickCommand() {
        
        @Override
        public void menuClicked(MenuItem selectedItem) {
            
            //TASK needs reworking!! create tid on save instead!
            //rework mover to be useful here
            
            TicketDbActions dba = new TicketDbActions();
            dba.setTicketData(new Date(), new Date(), null, null, null, countryKeyList != null ? countryKeyList.get(0) : null);
            
            Integer tid = dba.ticketCreateBlank();
            
        	OpenTicketsInsertEdit pie = new OpenTicketsInsertEdit(selectedItem, tid.toString());
        	pie.setPermissions(permCreate, permRead, permUpdate, permDelete);
        	pie.init();
        	pie.getWindow().addCloseListener(closeListener);
        	this.setWindow(pie.getWindow());
        	this.setParent(men_frm);
        	
        	pie.getWindow().setClosable(false);
        	
        }

    };
    
    public ClickCommand cmd_btn_read = new ClickCommand() {
        
        
        @Override
        public void menuClicked(MenuItem selectedItem) {
            
            if(tbl_data.getValue() == null){
                I18nManager.global(I18nGlobalNotifiers.no_entry_selected);
                return;
            }
            
            OpenTicketsInsertEdit pie = new OpenTicketsInsertEdit(selectedItem, getSelectedValue());
        	pie.setPermissions(0, permRead, 0, 0);
        	pie.init();
        	this.setWindow(pie.getWindow());
        	this.setParent(men_frm);

        }
        
    };
    
    public ClickCommand cmd_btn_edit = new ClickCommand() {
        
        @Override
        public void menuClicked(MenuItem selectedItem) {
            
            if(tbl_data.getValue() == null){
                I18nManager.global(I18nGlobalNotifiers.no_entry_selected);
                return;
            }
            
            OpenTicketsInsertEdit pie = new OpenTicketsInsertEdit(selectedItem, getSelectedValue());
        	pie.setPermissions(permCreate, permRead, permUpdate, permDelete);
        	pie.init();
        	pie.getWindow().addCloseListener(closeListener);
        	this.setWindow(pie.getWindow());
        	this.setParent(men_frm);
            
        }
        
    };

    public Command cmd_btn_del = new Command() {
        @Override
        public void menuSelected(MenuItem selectedItem) {
            
            if(tbl_data.getValue() == null){
                I18nManager.global(I18nGlobalNotifiers.no_entry_selected);
                return;
            }
            
            deleteData(getSelectedValue());

        }
    };

    public Command cmd_btn_filter = new Command() {
        @Override
        public void menuSelected(MenuItem selectedItem) {

            if (firstFilter) {
                tbl_data.setFilterBarVisible(true);
                tbl_data.setFilterBarVisible(false);
                firstFilter = false;
            }
            tbl_data.setFilterBarVisible(!tbl_data.isFilterBarVisible());
            
            if(!tbl_data.isFilterBarVisible()){
                tbl_data.clearFilters();
            }
            
            tableColsActive = tbl_data.isFilterBarVisible() ? tableColsFilter : tableColsDefault;
            if(tableColsActive.length > 0){
            	tbl_data.setVisibleColumns(tableColsActive);
            }

        }
    };

    
    public Command cmd_btn_refresh = new Command() {
        @Override
        public void menuSelected(MenuItem selectedItem) {
            
            updateTable(true);

        }
    };
    

    /******************************************/

    
    public void setGlobalFilterMonth(Date date){
        LocalDate ld = new LocalDate(date);
        filterMonthEnabled.setValue(true);
        filterMonth.setValue(new LocalDate(ld.getYear(), ld.getMonthOfYear(), 1).toDate());
    }
    
    public void setGlobalFilterMonth(){
        setGlobalFilterMonth(new Date());
    }

    /*********** Gen Menüs *************/
    private void generateMenu() {

        btn_create = men_frm.addItem("FRM_ADD", Icons.White.add_16, cmd_btn_add);
        btn_update = men_frm.addItem("FRM_EDIT", Icons.White.edit_16, cmd_btn_edit);
        btn_read = men_frm.addItem("FRM_READ", Icons.White.perm_lesen_16, cmd_btn_read);
//        btn_delete = men_frm.addItem("FRM_DEL", Icons.White.delete_16, cmd_btn_del);
        
        btn_filter = men_frm.addItem("FRM_FILTER", Icons.White.filter_16, cmd_btn_filter);
        btn_refresh = men_frm.addItem("FRM_REFRESH", Icons.White.refresh_16, cmd_btn_refresh);
        
    }
    
    private void setNurseUserId(){
        nurseUserId = getNurseUID();
    }
    
    private void configureComponents(){
       
    	for (Entry<Object, String> entry : componentMap.entrySet()) {
    		AbstractComponent field = (AbstractComponent) entry.getKey();
    		
			field.setImmediate(true);
			
			
			if(field instanceof ComboBox){
				((ComboBox)field).setFilteringMode(FilteringMode.CONTAINS);
			}
			
		}
    	
        // MONTHPICKER
        filterMonthEnabled.setValue(false);
        filterMonthEnabled.setImmediate(true);
        filterMonth.setResolution(Resolution.MONTH);
        filterMonth.setDateFormat("MMM yyyy");
        filterMonth.setEnabled(false);
        
        filterMonthEnabled.setImmediate(true);
        filterMonthEnabled.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                Boolean enabled = (Boolean)event.getProperty().getValue();
                filterMonth.setEnabled(enabled);
                if(enabled && filterMonth.getValue() == null){
                    LocalDate ld = new LocalDate();
                    filterMonth.setValue(new LocalDate(ld.getYear(), ld.getMonthOfYear(), 1).toDate());
                }else if(!enabled){
                	filterMonth.setValue(null);
                }
                
            }
        });
        
        filterMonth.setImmediate(true);
        filterMonth.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                updateTable(true);
                
            }
        });
        
        // PATIENT
        fillPatients();
        filterPatient.setImmediate(true);
        filterPatient.setFilteringMode(FilteringMode.CONTAINS);
        filterPatient.setItemCaptionPropertyId("patient");
        filterPatient.setInvalidAllowed(true);
//        filterPatient.addFocusListener(new FocusListener() {
//            
//            @Override
//            public void focus(FocusEvent event) {
//                
//                filterPatient.setValue(null);
//                
//            }
//        });
        filterPatient.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                updateTable(true);
                
            }
        });
        filterPatientReset.setCaption(null);
        filterPatientReset.setIcon(Icons.White.close_16);
        filterPatientReset.setStyleName("button-image-only");
        filterPatientReset.setWidth("36px");
        filterPatientReset.addClickListener(new ClickListener() {
            
            @Override
            public void buttonClick(ClickEvent event) {
                
                filterPatient.setValue(null);
                
            }
        });
        
        // STATUSPICKER
        //TASK status
        filterStatusEnabled.setValue(true);
        filterStatusEnabled.setImmediate(true);
        filterStatus.setContainerDataSource(dbGetStatusValues());
        filterStatus.setItemCaptionPropertyId("STATUS");
       
        preselectStatusFilter();
        
        filterStatusEnabled.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                Boolean enabled = (Boolean)event.getProperty().getValue();
                filterStatus.setEnabled(enabled);
                updateTable(true);
                
            }
        });
        
        filterStatus.setImmediate(true);
        filterStatus.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                updateTable(true);
                
            }
        });


    }
    
    private void preselectStatusFilter(){
        HashSet<Integer> preselected = new HashSet<Integer>();
        Collections.addAll(preselected, 1, 2, 3, 4);
        filterStatus.setValue(preselected);
    }
    
    private ArrayList<AbstractField> getActiveGlobalFilters(){
        ArrayList<AbstractField> al = new ArrayList<AbstractField>();
        
        if(filterMonth.getValue() != null){
            al.add(filterMonth);
        }
        
        if(filterPatient.getValue() != null) {
            al.add(filterPatient);
        }
        
        if(filterStatusEnabled.getValue() && ((Collection) filterStatus.getValue()).size() > 0){
            al.add(filterStatus);
        }
        
        return al;
    }
    
    private Boolean hasGlobalFilters(ArrayList a){
        
        return (a.size() > 0);
        
    }
    
    private Boolean hasGlobalFilters(){
        
        return hasGlobalFilters(getActiveGlobalFilters());
        
    }
    
    /*************************** Config TBL ********************/

    private void configureTable() {
        tbl_data.setSelectable(true);
        tbl_data.setFilterOnDemand(false);
        tbl_data.setImmediate(true);
        tbl_data.setColumnCollapsingAllowed(false);
        tbl_data.setFooterVisible(true);
        tbl_data.setPageLength(1);
        try {
        	if(tableColsDefault.length > 0){
        		tbl_data.setVisibleColumns(tableColsDefault);
        	}
		} catch (Exception e) {

		}
        
        if(tbl_data.size() > 0){
            
            StringSqlTimestampConverter date = new StringSqlTimestampConverter();
            date.setDateFormat(DateFormat.SHORT);
            
            StringSqlTimestampConverter time = new StringSqlTimestampConverter();
            time.setDateFormat(DateFormat.SHORT);
            time.setTimeFormat(DateFormat.SHORT);
            
            tbl_data.setConverter("OMT_STATUS_ORDER_DATE", time);
            tbl_data.setConverter("OMT_UPDATED", time);
            
            tbl_data.setConverter("OMT_DELIVERY_DATE", date);
            tbl_data.setConverter("OMT_DATE_FROM", date);
            tbl_data.setConverter("OMT_DATE_UNTIL", date);
            
            tbl_data.setConverter("OMT_STATUS_SENT_DATE", time);
            tbl_data.setConverter("OMT_STATUS_RECEIVED_DATE", time);
            
            
        
        }
        
        tableUpdater = new FilteringTableUpdater(tbl_data);

    }

    /*************************** Database ********************/
    
    /********************************/
    
    
    private void updateTable(){
        updateTable(false);
    }
    
    private void updateTable(Boolean ignoreFilter) {

        if (ignoreFilter || !tbl_data.isFilterBarVisible()) {
            dbGetContainer();
            try{
            	if(tableColsDefault.length > 0){
            		tbl_data.setVisibleColumns(tableColsActive);
            	}
            }catch(Exception e){
                
            }
        }
        
//        tbl_data.setColumnFooter("OMT_ID", "Σ " + tbl_data.size());
//        
//        tbl_data.setColumnFooter("OMT_INTENDED_QUANTITY", "Σ " + getQuantitySum("OMT_INTENDED_QUANTITY"));
//        tbl_data.setColumnFooter("OMT_SENT_QUANTITY", "Σ " + getQuantitySum("OMT_SENT_QUANTITY"));
//        tbl_data.setColumnFooter("OMT_RECEIVED_QUANTITY", "Σ " + getQuantitySum("OMT_RECEIVED_QUANTITY"));
        
        if(oldTableSize == 0){
        	configureTable();
            i18n.refresh();
        }
        i18n.setTableHeaders();
        oldTableSize = tbl_data.size();
        
        
    }
    
    private Integer getQuantitySum(String column){
    	
    	Container con = tbl_data.getContainerDataSource();
    	Collection<Integer> selectedValues = (Collection<Integer>) con.getItemIds();
    	
        Integer sum = 0;
        for (Object row : selectedValues) {
        	
        	if(con.getContainerProperty(row, column).getValue() != null){
        		sum  += ((Integer) con.getContainerProperty(row, column).getValue()).intValue();
        	}
            
        }
        return sum;
    }
    
    private void deleteData(final String id){
        
        I18nManager.global(I18nGlobalMessages.confirm_delete, new MessageBoxListener() {
            
            @Override
            public void buttonClicked(ButtonId arg0) {
                if(ButtonId.YES == arg0) {
                    dbDeleteData(id);
                }
            }
        });
    }
    
    private void setCountryKey() {
        
        countryKeyList = null;
        
        UserAttributesCountry uac = new UserAttributesCountry();
        uac.setCurrentUserId();
        
        HashMap<String, ArrayList<String>> map = uac.getUserAttributeMap();
        
        if(map == null || map.get("ordermanager_country") == null) {
            return;
        }
        
        countryKeyList = map.get("ordermanager_country");
        
    }
    
    private int getNurseUID() {
        int UID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        CMS_Config_Std std = CMS_Config_Std.getInstance();
        DBClass db = new DBClass();

        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cms_auth_liste_gu");
        // db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_liste_gu",
        // "INNER JOIN", "cust_krankenschwester_stammdaten_ks", "AL_U_ID",
        // "KSK_U_ID");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cms_auth_liste_gu", "AL_U_ID", "=", "'" + UID + "'", "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cms_auth_liste_gu", "AL_G_ID", "=", "'12'", "");

        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();

        if (con.size() > 0) {
            return UID;
        } else {
            return 0;
        }

    }
    
    private Container dbGetStatusValues() {
        return dbGetStatusValues(0);
    }
    
    private void fillPatients() {
        
        CustomQuery q = new DBClass().CustomQuery;
        String sql = "select"
             + "\n " + "    PSL_ID"
             + "\n " + "    , CONCAT_WS('', PSL_TITEL,' ',PSA_NAME,' ',PSL_NAME,', ',PSL_VORNAME) as patient"
             + "\n " + "from cust_patient_stammdaten_liste"
             + "\n " + "left join cust_patient_stammdaten_anrede on PSL_ANREDE = PSA_ID"
             + "\n " + "ORDER BY PSL_NAME ASC";
        q.setSqlString(sql);
        
        filterPatient.setContainerDataSource(MyUtils.convertIndex(q.query(), "PSL_ID"));
        
    }
    
    private Container dbGetStatusValues(Integer currentStatus) {
        CMS_Config_Std std = CMS_Config_Std.getInstance();
        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("OMMS_ID");
        setQueryStatusLng(db);
        
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_ordermanager_master_status");
        
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_ordermanager_master_status", "OMMS_ID", ">=", currentStatus.toString(), "");
        
        db.debugNextQuery(false);
        
        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();
        db.DB_Data_Get.connclose();
        
        return con;

    }
    
    private void setQueryStatusLng(DBClass db){
    	
    	SetQueryStatusLng qsl = new SetQueryStatusLng();
    	qsl.setStatus(db);
        
    }
    
    //TASK dbget
	private void dbGetContainer() {
        CMS_Config_Std std = CMS_Config_Std.getInstance();

        DBClass db = new DBClass();

        /************ Set Spalten *************/
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("cust_ordermanager_tickets.*");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("OMT_STATUS_ORDER_DATE");
        
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(AUL_VORNAME,' ',AUL_NAME)", "'nurse'");
//        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(SL_NAME, ' (', SL_STREET, ' ', SL_PLZ, ' ', SL_CITY, ')')", "location");
//        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("PSLV_NAME");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CASE"
                + " when OMT_ID_LOCATION IS NOT NULL then '" + i18n.get(caption.location_custom) + "'"
                + " else '" + i18n.get(caption.location_default) + "' end", "'custom_location'");
        setQueryStatusLng(db);
        /**************************************/
        /************ Set Tabelle *************/
//        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_ordermanager_tickets", "LEFT JOIN", "cust_ordermanager_orders", "OMT_ID_ORDER", "OMO_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_ordermanager_tickets", "LEFT JOIN", "cust_ordermanager_ticket_contents", "OMT_ID", "OMTC_ID_TICKET");
        
        //nurse
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_ordermanager_tickets", "RIGHT JOIN", "cms_auth_stammdaten_user", "OMT_ID_USER", "AUL_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_stammdaten_user", "RIGHT JOIN", "cust_krankenschwester_stammdaten_anrede", "AUL_ANREDE_ID", "KSA_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_krankenschwester_stammdaten_ks", "RIGHT JOIN", "cms_auth_stammdaten_user", "KSK_U_ID", "AUL_ID");
        
        //location
//        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_ordermanager_tickets", "RIGHT JOIN", "cust_shipping_locations", "OMT_ID_LOCATION", "SL_ID");
        
        
        //status
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_ordermanager_tickets", "RIGHT JOIN", "cust_ordermanager_master_status", "OMT_ID_STATUS", "OMMS_ID");
        
        //project
        //db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_ordermanager_orders", "INNER JOIN", "cust_projekte_stammdaten_liste", "OMO_ID_PROJECT", "PSLV_ID");
        
        
        /**************************************/
        /************ Set Filter *************/
        
        String glue = "";
        ArrayList<AbstractField> filterList = getActiveGlobalFilters(); 
        
        if(countryKeyList != null && countryKeyList.size() > 0) {
            glue = hasGlobalFilters(filterList) ? "AND" : "";
            db.DB_Data_Get.DB_Filter.DB_WHERE_In("cust_ordermanager_tickets", "OMT_KEY_COUNTRY", "'"+Joiner.on("','").join(countryKeyList)+"'", glue);
        }
        
        if(nurseUserId != 0){
        	glue = hasGlobalFilters(filterList) ? "AND" : "";
        	db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_ordermanager_tickets", "OMT_ID_USER", "=", nurseUserId.toString(), glue);
        }
        
        
        if(filterMonthEnabled.getValue() && filterMonth.getValue() != null){
            
            java.sql.Timestamp sqlDateFrom = new java.sql.Timestamp(new LocalDate(filterMonth.getValue()).minusDays(2).toDate().getTime());
            java.sql.Timestamp sqlDateUntil = new java.sql.Timestamp(new LocalDate(filterMonth.getValue()).plusMonths(1).plusDays(2).toDate().getTime());
            
            filterList.remove(filterMonth);
            glue = hasGlobalFilters(filterList) ? "AND" : "";
            
            db.DB_Data_Get.DB_Filter.DB_WHERE_BETWEEN("( cust_ordermanager_tickets", "OMT_DELIVERY_DATE", "'" + sqlDateFrom.toString() + "'",  "'" + sqlDateUntil.toString() + "'", " OR ");
            db.DB_Data_Get.DB_Filter.DB_WHERE_BETWEEN("cust_ordermanager_tickets", "OMT_DATE_FROM", "'" + sqlDateFrom.toString() + "'",  "'" + sqlDateUntil.toString() + "'", ") "+ glue);
        }
        
        if(filterPatient.getValue() != null){
            
            filterList.remove(filterPatient);
            glue = hasGlobalFilters(filterList) ? "AND" : "";
            
            db.DB_Data_Get.DB_Filter.DB_WHERE_In("cust_ordermanager_tickets", "OMT_ID", "(select OMTC_ID_TICKET from cust_ordermanager_ticket_contents where OMTC_ID_PATIENT = "+ filterPatient.getValue() +" group by OMTC_ID_TICKET)", glue);
            
        }
        
        if(filterStatusEnabled.getValue() && ((Collection) filterStatus.getValue()).size() > 0){
            
            filterList.remove(filterStatus);
            glue = hasGlobalFilters(filterList) ? "AND" : "";

            //TASK das muss anders einfacher gehen...
            HashSet<Integer> getIds = new HashSet<Integer>();
            for (Integer value : (Collection<Integer>)filterStatus.getValue()) {
                getIds.add((Integer) filterStatus.getContainerProperty(value, "OMMS_ID").getValue());
            }
            
            db.DB_Data_Get.DB_Filter.DB_WHERE_In("cust_ordermanager_tickets", "OMT_ID_STATUS", generateCollectionString(getIds), glue);
        }
        
        /**************************************/
        
        db.DB_Data_Get.DB_Gruppieren.DB_Gruppieren("OMT_ID");

        
        /**************************************/
        /************ Set Custom *************/
        /**************************************/

        db.DB_Data_Get.Set_Type("PSLV_NAME", Project.class);
        db.DB_Data_Get.Set_Type("STATUS", Status.class);
        db.DB_Data_Get.Set_Type("custom_location", Location.class);
        
        /* **************************/
        
//        db.debugNextQuery(true);
        
        try {
        	Container container = db.DB_Data_Get.DB_SEND_AND_GET_Container();
            
        	if (tableUpdater != null) {
                tableUpdater.updateTable(container);
            } else {
                tbl_data.setContainerDataSource(container);
            }
        	
		} catch (Exception e) {
			// TASK: handle exception
			System.out.println("exception!");
//			UI.getCurrent().getUI().removePollListener(pollListener);
		}
        
    }
    
    private String generateCollectionString(Collection<Integer> ids){
        String in = "";
        String comma = "";
        
        for (Integer integer : ids) {
            in += comma + integer;
            if(Strings.isNullOrEmpty(comma)){
                comma = ", ";
            }
        }
        
        return in;
    }
    
    private void dbDeleteData(String id){
    
        CMS_Config_Std std = CMS_Config_Std.getInstance();
    
        DBClass db = new DBClass();
        db.DB_Data_Delete.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_prescriptions_list");
        db.DB_Data_Delete.DB_Filter.DB_WHERE_Allgemein("cust_prescriptions_list", tableIdCol, "=", id, "");
        db.DB_Data_Delete.DB_Delete();
    
        I18nManager.global(I18nGlobalNotifiers.entry_deleted);
        
        updateTable(true);

        
    }
    
    @AutoGenerated
    private HorizontalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new HorizontalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // mainContainer
        mainContainer = buildMainContainer();
        mainLayout.addComponent(mainContainer);
        mainLayout.setExpandRatio(mainContainer, 1.0f);
        mainLayout.setComponentAlignment(mainContainer, new Alignment(20));
        
        return mainLayout;
    }

    @AutoGenerated
    private VerticalLayout buildMainContainer() {
        // common part: create layout
        mainContainer = new VerticalLayout();
        mainContainer.setImmediate(false);
        mainContainer.setWidth("100.0%");
        mainContainer.setHeight("100.0%");
        mainContainer.setMargin(true);
        
        // menuSpacer
        menuSpacer = buildMenuSpacer();
        mainContainer.addComponent(menuSpacer);
        
        // globalFilterContainer
        globalFilterContainer = buildGlobalFilterContainer();
        mainContainer.addComponent(globalFilterContainer);
        mainContainer.setComponentAlignment(globalFilterContainer, new Alignment(48));
        
        // tbl_data
        tbl_data = new FilterTable();
        tbl_data.setImmediate(true);
        tbl_data.setWidth("100.0%");
        tbl_data.setHeight("100.0%");
        mainContainer.addComponent(tbl_data);
        mainContainer.setExpandRatio(tbl_data, 1.0f);
        mainContainer.setComponentAlignment(tbl_data, new Alignment(20));
        
        return mainContainer;
    }

    @AutoGenerated
    private VerticalLayout buildMenuSpacer() {
        // common part: create layout
        menuSpacer = new VerticalLayout();
        menuSpacer.setImmediate(false);
        menuSpacer.setWidth("100.0%");
        menuSpacer.setHeight("40px");
        menuSpacer.setMargin(false);
        
        // men_frm
        men_frm = new MenuBar();
        men_frm.setImmediate(false);
        men_frm.setWidth("100.0%");
        men_frm.setHeight("-1px");
        menuSpacer.addComponent(men_frm);
        menuSpacer.setComponentAlignment(men_frm, new Alignment(20));
        
        return menuSpacer;
    }

    @AutoGenerated
    private HorizontalLayout buildGlobalFilterContainer() {
        // common part: create layout
        globalFilterContainer = new HorizontalLayout();
        globalFilterContainer.setImmediate(false);
        globalFilterContainer.setWidth("100.0%");
        globalFilterContainer.setHeight("80px");
        globalFilterContainer.setMargin(false);
        
        // filterMonthContainer
        filterMonthContainer = buildFilterMonthContainer();
        globalFilterContainer.addComponent(filterMonthContainer);
        globalFilterContainer.setComponentAlignment(filterMonthContainer, new Alignment(48));
        
        // horizontalLayout_2
        horizontalLayout_2 = buildHorizontalLayout_2();
        globalFilterContainer.addComponent(horizontalLayout_2);
        globalFilterContainer.setComponentAlignment(horizontalLayout_2, new Alignment(48));
        
        // filterStatusContainer
        filterStatusContainer = buildFilterStatusContainer();
        globalFilterContainer.addComponent(filterStatusContainer);
        globalFilterContainer.setComponentAlignment(filterStatusContainer, new Alignment(48));
        
        return globalFilterContainer;
    }

    @AutoGenerated
    private HorizontalLayout buildFilterMonthContainer() {
        // common part: create layout
        filterMonthContainer = new HorizontalLayout();
        filterMonthContainer.setImmediate(false);
        filterMonthContainer.setWidth("-1px");
        filterMonthContainer.setHeight("-1px");
        filterMonthContainer.setMargin(false);
        filterMonthContainer.setSpacing(true);
        
        // filterMonthEnabled
        filterMonthEnabled = new CheckBox();
        filterMonthEnabled.setCaption("Monatsfilter");
        filterMonthEnabled.setImmediate(false);
        filterMonthEnabled.setWidth("-1px");
        filterMonthEnabled.setHeight("-1px");
        filterMonthContainer.addComponent(filterMonthEnabled);
        filterMonthContainer.setComponentAlignment(filterMonthEnabled, new Alignment(48));
        
        // filterMonth
        filterMonth = new PopupDateField();
        filterMonth.setImmediate(false);
        filterMonth.setWidth("-1px");
        filterMonth.setHeight("-1px");
        filterMonthContainer.addComponent(filterMonth);
        filterMonthContainer.setComponentAlignment(filterMonth, new Alignment(48));
        
        return filterMonthContainer;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_2() {
        // common part: create layout
        horizontalLayout_2 = new HorizontalLayout();
        horizontalLayout_2.setImmediate(false);
        horizontalLayout_2.setWidth("-1px");
        horizontalLayout_2.setHeight("-1px");
        horizontalLayout_2.setMargin(false);
        horizontalLayout_2.setSpacing(true);
        
        // filterPatient
        filterPatient = new ComboBox();
        filterPatient.setCaption("Patientenfilter");
        filterPatient.setImmediate(false);
        filterPatient.setWidth("-1px");
        filterPatient.setHeight("-1px");
        horizontalLayout_2.addComponent(filterPatient);
        
        // filterPatientReset
        filterPatientReset = new Button();
        filterPatientReset.setImmediate(false);
        filterPatientReset.setWidth("-1px");
        filterPatientReset.setHeight("-1px");
        horizontalLayout_2.addComponent(filterPatientReset);
        horizontalLayout_2.setComponentAlignment(filterPatientReset, new Alignment(9));
        
        return horizontalLayout_2;
    }

    @AutoGenerated
    private HorizontalLayout buildFilterStatusContainer() {
        // common part: create layout
        filterStatusContainer = new HorizontalLayout();
        filterStatusContainer.setImmediate(false);
        filterStatusContainer.setWidth("-1px");
        filterStatusContainer.setHeight("-1px");
        filterStatusContainer.setMargin(false);
        filterStatusContainer.setSpacing(true);
        
        // filterStatusEnabled
        filterStatusEnabled = new CheckBox();
        filterStatusEnabled.setCaption("Statusfilter");
        filterStatusEnabled.setImmediate(false);
        filterStatusEnabled.setWidth("-1px");
        filterStatusEnabled.setHeight("-1px");
        filterStatusContainer.addComponent(filterStatusEnabled);
        filterStatusContainer.setComponentAlignment(filterStatusEnabled, new Alignment(48));
        
        // filterStatus
        filterStatus = new TwinColSelect();
        filterStatus.setImmediate(false);
        filterStatus.setWidth("-1px");
        filterStatus.setHeight("52px");
        filterStatusContainer.addComponent(filterStatus);
        
        return filterStatusContainer;
    }
}
