package archenoah.web.normal.main.Menuepunkte.Standard.Administration.Berrechtigungsverwaltung.forms;

import archenoah.config.CMS_Config_Std;
import archenoah.lib.custom.MyUtils;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.tool.comunication.dbclass.DBClass.CustomQuery;
import archenoah.lib.vaadin.Components.Combo.nativecombo;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Tab_Menue_Item;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Init_Menüpunkt_Individuelle;
import archenoah.web.normal.main.Menuepunkte.Standard.Init_Menüpunkt_Standard;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextField;
import com.vaadin.ui.TreeTable;
import com.vaadin.ui.VerticalLayout;

public class frm_berrechtigungsverwaltung_haupt_lists extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private HorizontalLayout mainLayout;
    @AutoGenerated
    private VerticalLayout verticalLayout_2;
    @AutoGenerated
    private TreeTable tbl_ber;
    @AutoGenerated
    private HorizontalLayout horizontalLayout_2;
    @AutoGenerated
    private HorizontalLayout horizontalLayout_8;
    @AutoGenerated
    private Panel pan_get_grp;
    @AutoGenerated
    private HorizontalLayout horizontalLayout_1;
    @AutoGenerated
    private Button btn_grp_set;
    @AutoGenerated
    private NativeSelect ns_grp;
    @AutoGenerated
    private HorizontalLayout horizontalLayout_6;
    @AutoGenerated
    private Panel panel_Show_Grp;
    @AutoGenerated
    private HorizontalLayout horizontalLayout_5;
    @AutoGenerated
    private TextField txt_ausg_grp;
    /**
     * The constructor should first build the main layout, set the composition root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual editor.
     */

    private static org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(frm_berrechtigungsverwaltung_haupt_lists.class);
    
    private MenuItem Menü;
    private Container con_men_punkte;
    private String G_ID;

    private I18nManager i18n;
    private I18nManager i18nMenus;

    public frm_berrechtigungsverwaltung_haupt_lists(MenuItem Arg_Menü) {
        buildMainLayout();
        i18n = new I18nManager(this);
        i18nMenus = new I18nManager("menus");

        Menü = Arg_Menü;

        txt_ausg_grp.setReadOnly(true);
        Tree_Grundeinstellungen();
        event();
        Native_comboholen();

        // setCompositionRoot(mainLayout);

        // TODO add user code here
        i18n.refresh();

    }

    public void Gen_Tab(TabSheet tab) {
        Build_Tab_Menue_Item bt = new Build_Tab_Menue_Item(tab, Menü.getText(), mainLayout, Menü.getIcon());

    }

    private void event() {
        btn_grp_set.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {
                // TODO Automatisch generierter Methodenstub

                if (ns_grp.getValue() == null) {
                    tbl_ber.removeAllItems();
                    txt_ausg_grp.setReadOnly(false);
                    txt_ausg_grp.setValue("");
                    txt_ausg_grp.setReadOnly(true);
                    G_ID = "";
                    I18nManager.global(I18nGlobalNotifiers.no_entry_selected);

                    return;
                }

                txt_ausg_grp.setReadOnly(false);
                G_ID = ns_grp.getValue() + "";
                txt_ausg_grp.setValue(ns_grp.getItemCaption(ns_grp.getValue()));
                txt_ausg_grp.setReadOnly(true);
                
                DB_get_Menü();
                buildTree();
                
            }
        });

    }

    // ********************--> Aufbau Treetable <--*******//

    private void Tree_Grundeinstellungen() {
        
        tbl_ber.addContainerProperty("menu", String.class, "");
        tbl_ber.addContainerProperty("create", CheckBox.class, null);
        tbl_ber.addContainerProperty("read", CheckBox.class, null);
        tbl_ber.addContainerProperty("edit", CheckBox.class, null);
        tbl_ber.addContainerProperty("delete", CheckBox.class, null);
        

        tbl_ber.setSelectable(true);
        tbl_ber.setVisibleColumns(new Object[] { "menu", "read", "edit", "create", "delete" });
        tbl_ber.setColumnExpandRatio("menu", 1);
        tbl_ber.setColumnExpandRatio("create", 0);
        tbl_ber.setColumnExpandRatio("read", 0);
        tbl_ber.setColumnExpandRatio("edit", 0);
        tbl_ber.setColumnExpandRatio("delete", 0);

    }

    private void buildTree() {
        
        tbl_ber.removeAllItems();
        
        MenuBar menu = new MenuBar();
        MenuItem item = menu.addItem("Start",null, null);
        
        new Init_Menüpunkt_Standard(item);
        new Init_Menüpunkt_Individuelle(item);
        
        buildTable(item, null);
    }
    
    
    @SuppressWarnings("unchecked")
    private void buildTable(MenuItem menuItem, Integer parent) {
        
        Item item = getItemFromKey(menuItem.getText());
        
        Integer id = MyUtils.getValueFromItem(item, "ASM_ID", Integer.class);
        
        if(id != null) {
        
            Item added = tbl_ber.addItem(id);
            added.getItemProperty("menu").setValue(i18nMenus.get(menuItem.getText()));
            
            addCheckBox(added, item, "create");
            addCheckBox(added, item, "read");
            addCheckBox(added, item, "edit");
            addCheckBox(added, item, "delete");
            
            tbl_ber.setParent(id, parent);
        
            if(!menuItem.hasChildren()) {
                tbl_ber.setChildrenAllowed(id, false);
            }
            
        }
        
        if(menuItem.hasChildren()) {
            for (MenuItem child : menuItem.getChildren()) {
                buildTable(child, id);
            }
        }
        
    }
    
    @SuppressWarnings("unchecked")
    private void addCheckBox(final Item added, final Item item, final String perm) {
        
        CheckBox cb = new CheckBox();
        Integer allowed = MyUtils.getValueFromItem(item, perm, Integer.class);
        cb.setValue(allowed != null && allowed == 1 ? true : false);
        cb.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                dbSaveChange(MyUtils.getValueFromItem(item, "ASM_ID", Integer.class), added);
                
            }
        });
        added.getItemProperty(perm).setValue(cb);
    }
    
    private Item getItemFromKey(String key) {
        
        if(key == null) {
            return null;
        }
        
        for (Object iid : con_men_punkte.getItemIds()) {
            Item item = con_men_punkte.getItem(iid);
            if(key.equals(MyUtils.getValueFromItem(item, "ASM_U_MEN", String.class))) {
                return item;
            }
        }
        
        return null;
    }

    private void DB_get_Menü() {
        
        CustomQuery q = new DBClass().CustomQuery;
        String sql = "SELECT ASM_ID, ASM_U_MEN, "
            + " ALM_LESEN as `read`,"
            + " ALM_BEARBEITEN as `edit`,"
            + " ALM_LOESCHEN as `delete`,"
            + " ALM_ERSTELLEN as `create`"
            + " from cms_auth_stammdaten_menu"
         + "\n " + "left join cms_auth_liste_menu on ALM_U_ID = ASM_ID"
         + "\n " + "WHERE ASM_BER = 1 AND ALM_G_ID = " + ns_grp.getValue();
        q.setSqlString(sql);

        con_men_punkte =  MyUtils.convertIndex(q.query(), "ASM_ID");

    }


    private void Native_comboholen() {
        CMS_Config_Std std = CMS_Config_Std.getInstance();

        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cms_auth_stammdaten_group");

        nativecombo nc = new nativecombo(db.DB_Data_Get.DB_SEND_AND_GET(), ns_grp, "AGL_ID", "AGL_NAME");
        db.DB_Data_Get.connclose();
    }
    
    private void dbSaveChange(Integer menuId, Item added) {
        
        
        boolean create = ((CheckBox) added.getItemProperty("create").getValue()).getValue();
        boolean read = ((CheckBox) added.getItemProperty("read").getValue()).getValue();
        boolean edit = ((CheckBox) added.getItemProperty("edit").getValue()).getValue();
        boolean delete = ((CheckBox) added.getItemProperty("delete").getValue()).getValue();
        
        CustomQuery q = new DBClass().CustomQuery;
        String sql = "INSERT INTO cms_auth_liste_menu (ALM_U_ID, ALM_G_ID, ALM_LESEN, ALM_BEARBEITEN, ALM_LOESCHEN, ALM_ERSTELLEN)"
             + "\n " + "VALUES ("+menuId+", " + G_ID+ ", "+read+", "+edit+", "+delete+", "+create+")"
             + "\n " + "ON DUPLICATE KEY UPDATE"
             + "\n " + "    ALM_LESEN = VALUES(ALM_LESEN),"
             + "\n " + "    ALM_BEARBEITEN = VALUES(ALM_BEARBEITEN),"
             + "\n " + "    ALM_LOESCHEN = VALUES(ALM_LOESCHEN),"
             + "\n " + "    ALM_ERSTELLEN = VALUES(ALM_ERSTELLEN)";
        q.setSqlString(sql);
        q.db.debugNextQuery(true);
        q.update();

    }
    
    @AutoGenerated
    private HorizontalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new HorizontalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);

        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");

        // verticalLayout_2
        verticalLayout_2 = buildVerticalLayout_2();
        mainLayout.addComponent(verticalLayout_2);
        mainLayout.setExpandRatio(verticalLayout_2, 5.0f);

        return mainLayout;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_2() {
        // common part: create layout
        verticalLayout_2 = new VerticalLayout();
        verticalLayout_2.setImmediate(false);
        verticalLayout_2.setWidth("100.0%");
        verticalLayout_2.setHeight("100.0%");
        verticalLayout_2.setMargin(false);

        // horizontalLayout_2
        horizontalLayout_2 = buildHorizontalLayout_2();
        verticalLayout_2.addComponent(horizontalLayout_2);
        verticalLayout_2.setExpandRatio(horizontalLayout_2, 1.0f);
        verticalLayout_2.setComponentAlignment(horizontalLayout_2, new Alignment(48));

        // tbl_ber
        tbl_ber = new TreeTable();
        tbl_ber.setImmediate(false);
        tbl_ber.setWidth("800px");
        tbl_ber.setHeight("80.0%");
        verticalLayout_2.addComponent(tbl_ber);
        verticalLayout_2.setExpandRatio(tbl_ber, 3.0f);
        verticalLayout_2.setComponentAlignment(tbl_ber, new Alignment(20));

        return verticalLayout_2;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_2() {
        // common part: create layout
        horizontalLayout_2 = new HorizontalLayout();
        horizontalLayout_2.setImmediate(false);
        horizontalLayout_2.setWidth("800px");
        horizontalLayout_2.setHeight("60.0%");
        horizontalLayout_2.setMargin(false);

        // horizontalLayout_6
        horizontalLayout_6 = buildHorizontalLayout_6();
        horizontalLayout_2.addComponent(horizontalLayout_6);
        horizontalLayout_2.setExpandRatio(horizontalLayout_6, 1.0f);
        horizontalLayout_2.setComponentAlignment(horizontalLayout_6, new Alignment(48));

        // horizontalLayout_8
        horizontalLayout_8 = buildHorizontalLayout_8();
        horizontalLayout_2.addComponent(horizontalLayout_8);
        horizontalLayout_2.setExpandRatio(horizontalLayout_8, 2.0f);
        horizontalLayout_2.setComponentAlignment(horizontalLayout_8, new Alignment(48));

        return horizontalLayout_2;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_6() {
        // common part: create layout
        horizontalLayout_6 = new HorizontalLayout();
        horizontalLayout_6.setImmediate(false);
        horizontalLayout_6.setWidth("100.0%");
        horizontalLayout_6.setHeight("80.0%");
        horizontalLayout_6.setMargin(false);

        // panel_Show_Grp
        panel_Show_Grp = buildPanel_Show_Grp();
        horizontalLayout_6.addComponent(panel_Show_Grp);
        horizontalLayout_6.setComponentAlignment(panel_Show_Grp, new Alignment(48));

        return horizontalLayout_6;
    }

    @AutoGenerated
    private Panel buildPanel_Show_Grp() {
        // common part: create layout
        panel_Show_Grp = new Panel();
        panel_Show_Grp.setCaption("Ausgewählte Gruppe");
        panel_Show_Grp.setImmediate(false);
        panel_Show_Grp.setWidth("60.0%");
        panel_Show_Grp.setHeight("80.0%");

        // horizontalLayout_5
        horizontalLayout_5 = buildHorizontalLayout_5();
        panel_Show_Grp.setContent(horizontalLayout_5);

        return panel_Show_Grp;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_5() {
        // common part: create layout
        horizontalLayout_5 = new HorizontalLayout();
        horizontalLayout_5.setImmediate(false);
        horizontalLayout_5.setWidth("100.0%");
        horizontalLayout_5.setHeight("100.0%");
        horizontalLayout_5.setMargin(false);

        // txt_ausg_grp
        txt_ausg_grp = new TextField();
        txt_ausg_grp.setImmediate(false);
        txt_ausg_grp.setWidth("80.0%");
        txt_ausg_grp.setHeight("-1px");
        horizontalLayout_5.addComponent(txt_ausg_grp);
        horizontalLayout_5.setComponentAlignment(txt_ausg_grp, new Alignment(48));

        return horizontalLayout_5;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_8() {
        // common part: create layout
        horizontalLayout_8 = new HorizontalLayout();
        horizontalLayout_8.setImmediate(false);
        horizontalLayout_8.setWidth("100.0%");
        horizontalLayout_8.setHeight("80.0%");
        horizontalLayout_8.setMargin(false);

        // pan_get_grp
        pan_get_grp = buildPan_get_grp();
        horizontalLayout_8.addComponent(pan_get_grp);
        horizontalLayout_8.setComponentAlignment(pan_get_grp, new Alignment(33));

        return horizontalLayout_8;
    }

    @AutoGenerated
    private Panel buildPan_get_grp() {
        // common part: create layout
        pan_get_grp = new Panel();
        pan_get_grp.setCaption("Gruppe Auswählen");
        pan_get_grp.setImmediate(false);
        pan_get_grp.setWidth("100.0%");
        pan_get_grp.setHeight("80.0%");

        // horizontalLayout_1
        horizontalLayout_1 = buildHorizontalLayout_1();
        pan_get_grp.setContent(horizontalLayout_1);

        return pan_get_grp;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_1() {
        // common part: create layout
        horizontalLayout_1 = new HorizontalLayout();
        horizontalLayout_1.setImmediate(false);
        horizontalLayout_1.setWidth("100.0%");
        horizontalLayout_1.setHeight("100.0%");
        horizontalLayout_1.setMargin(false);

        // ns_grp
        ns_grp = new NativeSelect();
        ns_grp.setImmediate(false);
        ns_grp.setWidth("80.0%");
        ns_grp.setHeight("-1px");
        horizontalLayout_1.addComponent(ns_grp);
        horizontalLayout_1.setExpandRatio(ns_grp, 2.0f);
        horizontalLayout_1.setComponentAlignment(ns_grp, new Alignment(48));

        // btn_grp_set
        btn_grp_set = new Button();
        btn_grp_set.setCaption("Gruppe Auswählen");
        btn_grp_set.setImmediate(true);
        btn_grp_set.setWidth("-1px");
        btn_grp_set.setHeight("-1px");
        horizontalLayout_1.addComponent(btn_grp_set);
        horizontalLayout_1.setExpandRatio(btn_grp_set, 1.5f);
        horizontalLayout_1.setComponentAlignment(btn_grp_set, new Alignment(33));

        return horizontalLayout_1;
    }

}
