package archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.combined.form;

import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;

import org.joda.time.LocalDate;
import org.joda.time.LocalDateTime;
import org.tepi.filtertable.FilterTable;

import archenoah.config.CMS_Config_Std;
import archenoah.lib.custom.ComponentIterator;
import archenoah.lib.custom.MyUtils;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.vaadin.Components.ClickMenuBar.ClickCommand;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Tab_Menue_Item;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Window_Button;
import archenoah.lib.vaadin.Components.table.DataviewGenerator;
import archenoah.lib.vaadin.Components.table.FilteringTableUpdater;
import archenoah.lib.vaadin.CustomConverterFactorys.DataviewConverter;
import archenoah.lib.vaadin.CustomConverterFactorys.IntegerToBooleanConverter;
import archenoah.lib.vaadin.CustomConverterFactorys.StringSqlTimestampConverter;
import archenoah.lib.vaadin.Language.i18n.I18nConverter;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.lib.vaadin.MenuBerechtigung.Rechteholen;
import archenoah.lib.vaadin.resources.Icons;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.OpenTickets.classes.TicketContentLocator;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.classes.ProjectData;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.combined.classes.CombinedPdfPrint;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.combined.classes.SentStatusHandler;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.combined.classes.TypeConverter;

import com.google.common.base.Joiner;
import com.vaadin.addon.tableexport.ExcelExport;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.event.UIEvents.PollEvent;
import com.vaadin.event.UIEvents.PollListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.shared.ui.datefield.Resolution;
import com.vaadin.ui.AbstractComponent;
import com.vaadin.ui.AbstractField;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.Command;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;
import com.vaadin.ui.TwinColSelect;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.Window.CloseEvent;
import com.vaadin.ui.Window.CloseListener;


@SuppressWarnings({"serial", "rawtypes", "unchecked"})
public class CombinedDataView extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private HorizontalLayout mainLayout;

    @AutoGenerated
    private VerticalLayout mainContainer;

    @AutoGenerated
    private FilterTable tbl_data;

    @AutoGenerated
    private HorizontalLayout globalFilterContainer;

    @AutoGenerated
    private VerticalLayout verticalLayout_5;

    @AutoGenerated
    private TwinColSelect filterShippingFreq;

    @AutoGenerated
    private CheckBox filterShippingFreqEnabled;

    @AutoGenerated
    private VerticalLayout verticalLayout_4;

    @AutoGenerated
    private TwinColSelect filterShippingType;

    @AutoGenerated
    private CheckBox filterShippingTypeEnabled;

    @AutoGenerated
    private VerticalLayout verticalLayout_3;

    @AutoGenerated
    private TwinColSelect filterStatus;

    @AutoGenerated
    private CheckBox filterStatusEnabled;

    @AutoGenerated
    private VerticalLayout verticalLayout_2;

    @AutoGenerated
    private TwinColSelect filterProject;

    @AutoGenerated
    private CheckBox filterProjectEnabled;

    @AutoGenerated
    private VerticalLayout verticalLayout_1;

    @AutoGenerated
    private PopupDateField filterMonth;

    @AutoGenerated
    private CheckBox filterMonthEnabled;

    @AutoGenerated
    private VerticalLayout menuSpacer;

    @AutoGenerated
    private MenuBar men_frm;

    

    

    

    

    

    

    

    

	

	

	

	

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */

    /**************** --> Allgemein <--- ********************/
    // Datenbank
    private Map<Object, String> componentMap;
    private FilteringTableUpdater tableUpdater = null;
    private CMS_Config_Std config = CMS_Config_Std.getInstance();

    // Berrechtigung
    private int ACC_ID;

    private int permRead;
    private int permCreate;
    private int permUpdate;
    private int permDelete;

    private MenuItem tmpMenu = null;

    private Button tmpButton = null;
    /******************************************************/
    /**************** --> Tabsheetvars <--- *****************/
    private TabSheet tab = null;

    /******************************************************/
    /**************** --> Windowvars <--- *******************/
    private Window win = null;
    /******************************************************/

    private DetachListener onDetach = null;

    /******************* -> Menüpunkte <- ********************/
//    private MenuBar.MenuItem btn_create;
    private MenuBar.MenuItem btn_update;
    private MenuBar.MenuItem btn_read;
//    private MenuBar.MenuItem btn_delete;
    private MenuBar.MenuItem btn_filter;
    private MenuBar.MenuItem btn_pdf;
    private MenuBar.MenuItem btn_pdf_anonymous;
    private MenuBar.MenuItem btn_pdf_named;
    
    private MenuBar.MenuItem btn_sent;
    private MenuBar.MenuItem btn_mark;
    private MenuBar.MenuItem btn_unmark;
//    private MenuBar.MenuItem btn_RegionalManager;
    private MenuBar.MenuItem btn_locate;
    private MenuBar.MenuItem btn_export;
    
    /*******************************************************/
    /******************* --> Custom <--- ********************/
    /******************************************************/

    private Boolean firstFilter = true;
    private PollListener pollListener = null;
    
    enum IF_NAME {};
    
    /************ ----->Einstellungen<-- ********************/
//    private final String formIdLng = "50";
    private final String formIdPerm = "50";
    private final String winHeight = "600px";
    private final String winWidth = "900px";


    /******************************************************/

//    private final String tableIdCol = "ID";
    private final String tableName = "view_protokoll__overview";
    
    //TASK cols
    private final Object[] tableColsAll = new Object[] { "project", "date", "id", "nurse", "patient", "patientBirthday", "arzt", "SRL_ID_USER", "nurse_user_id", "project_name", "project_code", "status", "checked", "inf_type", "nurse_name", "patient_code", "patient_name", "arzt_name", "reglead_name", "IF_NAME", "pdf_type", "pdf_freq", "DATE_SENT", "sentUser", "sent", "sendable"};
    //use custom Cols when needed
    private Object[] tableColsDefault = new Object[] { "date", "project_name", "project_code", "id", "status", "checked", "inf_type", "nurse_name", "patient_code", "patientCountry", "patient_name", "patientBirthday", "arzt_name", "reglead_name", "IF_NAME", "pdf_type", "pdf_freq", "DATE_SENT", "sentUser", "sent", "sendable"};
    //use custom Cols when needed
    private final Object[] tableColsFilter = tableColsDefault;
    private Object[] tableColsActive = tableColsDefault;

    private StringSqlTimestampConverter dateConverter;
    private StringSqlTimestampConverter timeConverter;
    private StringSqlTimestampConverter birthdayConverter;
    private TypeConverter typeConverter;
    private I18nConverter pdfTypeConverter; 
    private I18nConverter pdfFreqConverter;
    private IntegerToBooleanConverter booleanConverter;

    private SentStatusHandler sentHandler;
    
    private I18nManager i18n; 
    /******************************************************/

    public CombinedDataView(MenuItem Arg_Menü) {
        tmpMenu = Arg_Menü;
    }

    public CombinedDataView(Button Arg_btn) {
        tmpButton = Arg_btn;
    }

    /***************************** ---> Feste Funtionen<--- **************************************/

    /********* INIT-Window ************/
    public void init() {

        Standard_Init();

        if (tmpMenu != null) {
            String Recourcename = tmpMenu.getIcon().toString();
            Recourcename = Recourcename.substring(0, Recourcename.length() - 12) + "white-16.png";

            Build_Window_Button bwb = new Build_Window_Button(tmpMenu.getText(), mainLayout, winHeight, winWidth,
                    new ThemeResource(Recourcename));
            win = bwb.ReturnWindow();
        }
        if (tmpButton != null) {
            Build_Window_Button bwb = new Build_Window_Button(tmpButton.getCaption(), mainLayout, winHeight, winWidth,
                    tmpButton.getIcon());
            win = bwb.ReturnWindow();
        }

        win.addDetachListener(onDetach);

    }
    
    public Window getWindow(){
    	return win;
    }
    
    public TabSheet getTabSheet(){
    	return tab;
    }
    
    public void init(TabSheet Arg_tab) {

        Standard_Init();
        tab = Arg_tab;
        if (tmpMenu != null) {
            new Build_Tab_Menue_Item(Arg_tab, tmpMenu.getText(), mainLayout, tmpMenu.getIcon());
        }
        if (tmpButton != null) {
            new Build_Tab_Menue_Item(Arg_tab, tmpButton.getCaption(), mainLayout, tmpButton.getIcon());
        }

        tab.getSelectedTab().addDetachListener(onDetach);
    }

    /********* Init-Standard ************/
    private void Standard_Init() {
        buildMainLayout();
        i18n = new I18nManager(this);
        registerComponents();
        
        generateMenu();
        
        setMenuPermissions();

//        updateTable(); //not needed
//        tbl_data.setSortContainerPropertyId("date");
//        tbl_data.setSortAscending(true);
//        tbl_data.sort();
        configureTable();
        configureComponents();

        setGlobalFilterMonth();
        
//        updateTable(); // triggered by monthFilter defaults
        
        setupListenersAndDetachEvent();
        i18n.refresh();
        
    }
    
    // register components for lng and validation tools
    private void registerComponents(){
    	componentMap = new HashMap<Object, String>();
    	new ComponentIterator(mainContainer).createMap(componentMap);
    }

    
    private void setupListenersAndDetachEvent() {
        pollListener = new PollListener() {

            @Override
            public void poll(PollEvent event) {
//                if(tab.isRendered(mainLayout) && filterMonthEnabled.getValue()){
//                    updateTable();
//                }
            }
        };

        UI.getCurrent().getUI().addPollListener(pollListener);

        onDetach = new DetachListener() {

            @Override
            public void detach(DetachEvent event) {
                UI.getCurrent().getUI().removePollListener(pollListener);
            }
        };
    }
    
    @SuppressWarnings("unused")
    public void setPermissionsFromDatabase() {
        if (formIdPerm == "") {
            System.out.println("Form Einstellung Fehlt: Berechtigung");
            return;
        }

        ACC_ID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        Rechteholen r = new Rechteholen(ACC_ID + "");
        String[][] perms = r.Datenholen();

        for (int i = 0; i < perms.length; i++) {
            if (perms[i][0].equals(formIdPerm) == true) {

                permRead = Integer.valueOf(perms[i][3]);
                permUpdate = Integer.valueOf(perms[i][4]);
                permCreate = Integer.valueOf(perms[i][6]);
                permDelete = Integer.valueOf(perms[i][5]);
                
            }
        }
    }

    public void setPermissions(int create, int read, int update, int delete) {

        permCreate = create;
        permRead = read;
        permUpdate = update;
        permDelete = delete;

    }

    private void setMenuPermissions() {
        Boolean c = (permCreate == 1);
        Boolean r = (permRead == 1);
        Boolean u = (permUpdate == 1);
        Boolean d = (permDelete == 1);

//        btn_create.setEnabled(c);
//        btn_create.setVisible(c);

        btn_read.setEnabled(r);
        btn_read.setVisible(r);

        btn_update.setEnabled(u);
        btn_update.setVisible(u);

//        btn_delete.setEnabled(d);
//        btn_delete.setVisible(d);
        
        btn_sent.setEnabled(u);
    }

    /************ -><- ******************/
    
    public void setGlobalFilterMonth(Date date){
        LocalDate ld = new LocalDate(date);
        filterMonthEnabled.setValue(true);
        filterMonth.setValue(new LocalDate(ld.getYear(), ld.getMonthOfYear(), 1).toDate());
    }
    
    public void setGlobalFilterMonth(){
        setGlobalFilterMonth(new Date());
    }
    
    /***************** Comands *********************/
    
    CloseListener closeListener = new CloseListener() {
		
		@Override
		public void windowClose(CloseEvent e) {
			updateTable(true);
		}
	};
    
	ProjectData projectData = new ProjectData(closeListener);
    
    /******************************************/

    
    

    /*********** Gen Menüs *************/
    private void generateMenu() {

        // EDIT
        btn_update = men_frm.addItem("FRM_EDIT", Icons.White.edit_16, new ClickCommand() {

            @Override
            public void menuClicked(MenuItem selected) {

                if (tbl_data.getValue() == null) {
                    I18nManager.global(I18nGlobalNotifiers.no_entry_selected);
                    return;
                }


                this.setWindow(openData(selected, getSelectedItem()));
                this.setParent(men_frm);
            }

        });
        
        // READ
        btn_read = men_frm.addItem("FRM_READ", Icons.White.perm_lesen_16, new ClickCommand() {

            @Override
            public void menuClicked(MenuItem selected) {

                if (tbl_data.getValue() == null) {
                    I18nManager.global(I18nGlobalNotifiers.no_entry_selected);
                    return;
                }
                
                this.setWindow(openDataReadonly(selected, getSelectedItem()));
                this.setParent(men_frm);
            }

        });
        
        // FILTER
        btn_filter = men_frm.addItem("FRM_FILTER", Icons.White.filter_16, new Command() {
            @Override
            public void menuSelected(MenuItem selectedItem) {

                if (firstFilter) {
                    tbl_data.setFilterBarVisible(true);
                    tbl_data.setFilterBarVisible(false);
                    firstFilter = false;
                }
                tbl_data.setFilterBarVisible(!tbl_data.isFilterBarVisible());
                
                if(!tbl_data.isFilterBarVisible()){
                    tbl_data.clearFilters();
                }
                
                tableColsActive = tbl_data.isFilterBarVisible() ? tableColsFilter : tableColsDefault;
                if(tbl_data.getContainerDataSource().size() > 0 && tableColsActive.length > 0){
                    tbl_data.setVisibleColumns(tableColsActive);
                }

            }
        });
        
        // PDF
        btn_pdf = men_frm.addItem("FRM_PDF", Icons.White.log_16, null);
        btn_pdf_anonymous = btn_pdf.addItem("PDF_ANONYMOUS", null);
        btn_pdf_named = btn_pdf.addItem("PDF_NAMED", null);

        sentHandler = new SentStatusHandler(tbl_data, "project", "id");
        
        // MARK
        btn_sent = men_frm.addItem("FRM_SENT", Icons.White.ticket_16, null);
        btn_mark = btn_sent.addItem("SENT_MARK", Icons.Black.select_16, new Command() {
            
            @Override
            public void menuSelected(MenuItem selectedItem) {
                sentHandler.markSent();
                updateTable(true);
            }
        });
        btn_unmark = btn_sent.addItem("SENT_UNMARK", Icons.Black.perm_loeschen_16, new Command() {
            
            @Override
            public void menuSelected(MenuItem selectedItem) {
                sentHandler.unmarkSent();
                updateTable(true);
            }
        });
        
        // LOCATE
        btn_locate = men_frm.addItem("FRM_LOCATE", Icons.White.backup_16, new ClickCommand() {
            
            @Override
            public void menuClicked(MenuItem selectedItem) {
                
                Item item = getSelectedItem();
                
                TicketContentLocator locator = new TicketContentLocator(selectedItem);
                
                this.setWindow(locator.locateContent(
                        MyUtils.getValueFromItem(item, "project", Long.class).intValue(),
                        MyUtils.getValueFromItem(item, "id", Integer.class)
                        ));
                this.setParent(men_frm);
                
            }

        });
        
        //EXPORT
        btn_export = men_frm.addItem("FRM_EXPORT", Icons.White.log_16, new Command() {
            
            @Override
            public void menuSelected(MenuItem selectedItem) {

                Table tbl = new Table();
                tbl.setVisible(false);
                tbl.setContainerDataSource(tbl_data);
                tbl.setColumnCollapsingAllowed(true);

                mainLayout.addComponent(tbl);
                
                for (String col : tbl.getColumnHeaders()) {
                    tbl.setColumnCollapsed(col, true);
                }
                
                for (Object col : tableColsDefault) {
                    tbl.setColumnCollapsed(col, false);
                    tbl.setColumnHeader(col, i18n.get((String) col));
                }
                
                tbl.setConverter("pdf_type", pdfTypeConverter);
                tbl.setConverter("pdf_freq", pdfFreqConverter);
                
                for (Object iid : tbl.getItemIds()) {
                    Item item = tbl.getItem(iid);
                    item.getItemProperty("pdf_type").setValue(
                        pdfTypeConverter.convertToPresentation(item.getItemProperty("pdf_type").getValue(), String.class, getLocale()));
                    item.getItemProperty("pdf_freq").setValue(
                        pdfFreqConverter.convertToPresentation(item.getItemProperty("pdf_freq").getValue(), String.class, getLocale()));
                }
                
                ExcelExport excelExport = new ExcelExport(tbl);
                
                excelExport.excludeCollapsedColumns();
                excelExport.setReportTitle("Gesamtübersicht Export");
                excelExport.setExportFileName("Gesamtprotokolle-Export.xls");

                excelExport.export();
                mainLayout.removeComponent(tbl);
                updateTable(true); // force refresh because converters are messy

            }
        });
    }
    
    private Item getSelectedItem() {
        return tbl_data.getItem(
                ((Collection) tbl_data.getValue()).toArray()[0]
                );
    }
    
    private ArrayList<Item> getSelectedItems(){
        
        ArrayList<Item> items = new ArrayList<Item>();
        
        for (Object iid : (Collection) tbl_data.getValue()) {
            items.add(tbl_data.getItem(iid));
        }
        
        return items;
    }
    
    private void configureComponents(){
       
    	for (Entry<Object, String> entry : componentMap.entrySet()) {
    		AbstractComponent field = (AbstractComponent) entry.getKey();
    		
			field.setImmediate(true);
			
			
			if(field instanceof ComboBox){
				((ComboBox)field).setFilteringMode(FilteringMode.CONTAINS);
			}
			
		}
        
        // MONTHPICKER
        filterMonthEnabled.setValue(false);
        filterMonthEnabled.setImmediate(true);
        filterMonth.setResolution(Resolution.MONTH);
        filterMonth.setDateFormat("MMM yyyy");
        filterMonth.setEnabled(false);
        
        filterMonthEnabled.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                Boolean enabled = (Boolean)event.getProperty().getValue();
                filterMonth.setEnabled(enabled);
                if(enabled && filterMonth.getValue() == null){
                    LocalDate ld = new LocalDate();
                    filterMonth.setValue(new LocalDate(ld.getYear(), ld.getMonthOfYear(), 1).toDate());
                }else if(!enabled){
                    filterMonth.setValue(null);
                }
                
            }
        });
        
        filterMonth.setImmediate(true);
        filterMonth.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                updateTable(true);
                
            }
        });
        
        // PROJECTPICKER
        filterProjectEnabled.setValue(false);
        filterProjectEnabled.setImmediate(true);
        filterProject.setContainerDataSource(dbGetProjects());
        filterProject.setItemCaptionPropertyId("PSLV_NAME");
        
       
        preselectProjectFilter();
        
        filterProjectEnabled.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                Boolean enabled = (Boolean)event.getProperty().getValue();
                filterProject.setEnabled(enabled);
                if(!enabled) {
                    filterProject.setValue(null);
                }
                
            }
        });
        
        filterProject.setImmediate(true);
        filterProject.setEnabled(false);
        filterProject.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                Collection val = (Collection) filterProject.getValue();
                filterProjectEnabled.setValue(val.size() != 0);
                updateTable(val.size() != 0);
                
            }
        });
        
        // STATUSPICKER
        filterStatusEnabled.setValue(false);
        filterStatusEnabled.setImmediate(true);
        filterStatus.setContainerDataSource(dbGetStatus());
        filterStatus.setItemCaptionPropertyId("SS_NAME");
       
        preselectProjectFilter();
        
        filterStatusEnabled.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                Boolean enabled = (Boolean)event.getProperty().getValue();
                filterStatus.setEnabled(enabled);
                if(!enabled) {
                    filterStatus.setValue(null);
                }
                
            }
        });
        
        filterStatus.setImmediate(true);
        filterStatus.setEnabled(false);
        filterStatus.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                Collection val = (Collection) filterStatus.getValue();
                filterStatusEnabled.setValue(val.size() != 0);
                updateTable(val.size() != 0);
                
            }
        });

        // TypeFilter
        filterShippingTypeEnabled.setValue(false);
        filterShippingTypeEnabled.setImmediate(true);
        fillShippingType();
        filterShippingType.setItemCaptionPropertyId(I18nConverter.CAPTION_PROPERTY);

        filterShippingTypeEnabled.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                Boolean enabled = (Boolean)event.getProperty().getValue();
                filterShippingType.setEnabled(enabled);
                if(!enabled) {
                    filterShippingType.setValue(null);
                }
                
            }
        });
        
        filterShippingType.setImmediate(true);
        filterShippingType.setEnabled(false);
        filterShippingType.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                Collection val = (Collection) filterShippingType.getValue();
                filterShippingTypeEnabled.setValue(val.size() != 0);
                updateTable(val.size() != 0);
                
            }
        });
        
        // FreqFilter
        filterShippingFreqEnabled.setValue(false);
        filterShippingFreqEnabled.setImmediate(true);
        fillShippingFreq();
        filterShippingFreq.setItemCaptionPropertyId(I18nConverter.CAPTION_PROPERTY);

        filterShippingFreqEnabled.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                Boolean enabled = (Boolean)event.getProperty().getValue();
                filterShippingFreq.setEnabled(enabled);
                if(!enabled) {
                    filterShippingFreq.setValue(null);
                }
                
            }
        });
        
        filterShippingFreq.setImmediate(true);
        filterShippingFreq.setEnabled(false);
        filterShippingFreq.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                Collection val = (Collection) filterShippingFreq.getValue();
                filterShippingFreqEnabled.setValue(val.size() != 0);
                updateTable(val.size() != 0);
                
            }
        });
        
        CombinedPdfPrint print = new CombinedPdfPrint(tbl_data);
        print.attach(mainLayout, btn_pdf_anonymous, false);
        print.attach(mainLayout, btn_pdf_named, true);
    }
    
    private void preselectProjectFilter(){
        // Preselect a few items
        HashSet<Integer> preselected = new HashSet<Integer>();
//        Collections.addAll(preselected, 1, 2, 3, 4);
        filterProject.setValue(preselected);
    }
    
   
    private ArrayList<AbstractField> getActiveGlobalFilters(){
        ArrayList<AbstractField> al = new ArrayList<AbstractField>();
        
        if(filterMonth.getValue() != null){
            al.add(filterMonth);
        }
        
        if(filterProjectEnabled.getValue() && ((Collection) filterProject.getValue()).size() > 0){
            al.add(filterProject);
        }
        
        if(filterStatusEnabled.getValue() && ((Collection) filterStatus.getValue()).size() > 0){
            al.add(filterStatus);
        }

        if(filterShippingTypeEnabled.getValue() && ((Collection) filterShippingType.getValue()).size() > 0){
            al.add(filterShippingType);
        }
        
        if(filterShippingFreqEnabled.getValue() && ((Collection) filterShippingFreq.getValue()).size() > 0){
            al.add(filterShippingFreq);
        }
        
        return al;
    }
    
    private Boolean hasGlobalFilters(ArrayList a){
        
        return (a.size() > 0);
        
    }
    
    private Boolean hasGlobalFilters(){
        
        return hasGlobalFilters(getActiveGlobalFilters());
        
    }
    
    /*************************** Config TBL ********************/

    private void configureTable() {
        tbl_data.setSelectable(true);
        tbl_data.setFilterOnDemand(false);
        tbl_data.setMultiSelect(true);
        tbl_data.setImmediate(true);
        tbl_data.setColumnCollapsingAllowed(true);
        tbl_data.setFooterVisible(true);
        tbl_data.setPageLength(1);
        try {
        	if(tableColsDefault.length > 0){
        		tbl_data.setVisibleColumns(tableColsDefault);
        	}
		} catch (Exception e) {
//		    e.printStackTrace();
		}
        
        pdfTypeConverter = new I18nConverter("cust_protokoll_pdf_type", "PPT_KEY", "PPT_KEY");
        pdfFreqConverter = new I18nConverter("cust_protokoll_pdf_freq", "PPF_KEY", "PPF_KEY");
        
        typeConverter = new TypeConverter();
        
        tbl_data.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                toggleMenuItems();
                setCount();
                
            }
        });
        toggleMenuItems();

        for (Object col : tableColsAll) {
        	
        	try {
        		tbl_data.setColumnExpandRatio(col, 1);
			} catch (Exception e) {
				
			}
        		
		}
        try {
            tbl_data.setColumnExpandRatio("nurse_name", 2);
            tbl_data.setColumnExpandRatio("patient_name", 2);
            tbl_data.setColumnExpandRatio("arzt_name", 2);
            tbl_data.setColumnExpandRatio("reglead_name", 2);
        } catch (Exception e) {
            
        }

        //tbl_data.setColumnCollapsed("sent", true); //TASK fixme
        tableUpdater = new FilteringTableUpdater(tbl_data);
    }

    private void toggleMenuItems(){
        
        Collection values = (Collection) tbl_data.getValue();
        
        Boolean crud = (!values.isEmpty() && values.size() == 1);
        Boolean multi = !values.isEmpty();
        
//        btn_create.setEnabled(crud);
        btn_update.setEnabled(crud);
        btn_read.setEnabled(crud);
//        btn_delete.setEnabled(crud || multi);
        
        btn_pdf.setEnabled(multi);
        
        btn_locate.setEnabled(crud);
    }
    
    private Window openDataReadonly(MenuItem selected, Item item) {
        return openData(selected, item, true);
    }
    
    private Window openData(MenuItem selected, Item item) {
        return openData(selected, item, false);
    }
    
    private Window openData(MenuItem selected, Item item, Boolean readonly) {

        Integer dataId = MyUtils.getValueFromItem(item, "id", Integer.class);
        dataId = dataId != null ? dataId : 0;
        String projectCode = MyUtils.getValueFromItem(item, "project_code", String.class);
        
        return projectData.open(selected, projectCode, dataId, readonly);
    }
    
    /*************************** Database ********************/
    
    /********************************/
    
    
    private void updateTable(){
        updateTable(false);
    }
    
    private void updateTable(Boolean ignoreFilter) {

        if (ignoreFilter || !tbl_data.isFilterBarVisible()) {
            
            if(dateConverter == null) {
                
                for (Object col : tableColsDefault) {
                    tbl_data.addContainerProperty(col, Object.class, null);
                }
                
                dateConverter = new StringSqlTimestampConverter();
                dateConverter.setDateFormat(DateFormat.SHORT);
                
                timeConverter = new StringSqlTimestampConverter();
                timeConverter.setDateFormat(DateFormat.SHORT);
                timeConverter.setTimeFormat(DateFormat.SHORT);
                
                birthdayConverter = new StringSqlTimestampConverter();
                birthdayConverter.setDateFormat(DateFormat.MEDIUM);
                
                tbl_data.setConverter("date", dateConverter);
                tbl_data.setConverter("patientBirthday", birthdayConverter);
                tbl_data.setConverter("DATE_SENT", timeConverter);
             
                HashMap<String, DataviewConverter> converterMap = new HashMap<String, DataviewConverter>();
                converterMap.put("pdf_type", pdfTypeConverter);
                converterMap.put("pdf_freq", pdfFreqConverter);
                converterMap.put("checked", new IntegerToBooleanConverter());
                converterMap.put("sent", new IntegerToBooleanConverter());
                converterMap.put("sendable", new IntegerToBooleanConverter());
                
                new DataviewGenerator(converterMap).attach(tbl_data);
                
            }
            
            dbGetContainer();
            try{
            	if(tableColsDefault.length > 0){
            	    tbl_data.setVisibleColumns(tableColsActive);
            	}
            }catch(Exception e){
                
            }
        }
        
        setCount();
        
    }
    
    private void setCount() {
        
        Integer size = tbl_data.getValue() != null ? ((Collection) tbl_data.getValue()).size() : 0;
        
        tbl_data.setColumnFooter("reglead_name", "Σ " + tbl_data.size()
                + ((size > 0) ? (" (" + size + ")") : ""));
    }
    
    private int getNurseUID() {
        int UID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        DBClass db = new DBClass();

        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cms_auth_liste_gu");

        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cms_auth_liste_gu", "AL_U_ID", "=", "'" + UID + "'", "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cms_auth_liste_gu", "AL_G_ID", "=", "'12'", "");

        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();

        if (con.size() > 0) {
            return UID;
        } else {
            return 0;
        }

    }
    
    private Container dbGetStatus() {
        
        DBClass db = new DBClass();

        String sql = "select"
         + "\n " + "    SS_NAME"
         + "\n " + "from cust_schulung_status"
         + "\n " + ""
         + "\n " + "GROUP BY SS_NAME"
         + "\n " + "ORDER BY SUM(SS_PROZESS)";
        
        db.CustomQuery.setSqlString(sql);
        
        return MyUtils.convertIndex(db.CustomQuery.query(), "SS_NAME");
        
    }
    
    private Container dbGetProjects() {
        DBClass db = new DBClass();

        String sql = "select"
         + "\n " + "    PSLV_ID"
         + "\n " + "    , PSLV_NAME"
         + "\n " + "from"
         + "\n " + "    cust_projekte_stammdaten_liste";
        
        db.CustomQuery.setSqlString(sql);
        
        return MyUtils.convertIndex(db.CustomQuery.query(), "PSLV_ID");
    }
    
    private void fillShippingType() {
        I18nConverter type = new I18nConverter("cust_protokoll_pdf_type", "PPT_KEY", "PPT_KEY");
        type.attachDatasource(filterShippingType);
    }
    
    private void fillShippingFreq() {
        I18nConverter freq = new I18nConverter("cust_protokoll_pdf_freq", "PPF_KEY", "PPF_KEY");
        freq.attachDatasource(filterShippingFreq);
    }
    
    //TASK dbget
	private void dbGetContainer() {
        
        Integer NUID = getNurseUID();
        
        DBClass db = new DBClass();
        
        String st = "view_protokoll_sendable";
        String tn = tableName;

        /************ Set Spalten *************/
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln(tableName+".*");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("cust_internal_firms.*");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("DATE_SENT");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT_WS(' ', AUL_VORNAME, AUL_NAME) as sentUser");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("DATE_SENT IS NOT NULL as sent");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("sendable");
       /**************************************/
        /************ Set Tabelle *************/

        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung(tableName, "left join", "cust_internal_firms", "firm_key", "if_key"); 
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung(tableName, "right join", "cust_protokoll_sent", "project", "ID_PROJECT and id = ID_DATA");
        
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung(tableName, "right join", "view_protokoll_sendable",
            "arzt", "arzt and "+st+".firm_key = "+tn+".firm_key and "+st+".pdf_type = "+tn+".pdf_type and "+st+".pdf_freq = "+tn+".pdf_freq"
                + "  AND YEAR("+tn+".date) = "+st+".yr"
         + "\n " + "  AND IF("+tn+".pdf_freq = 'freq_monthly_6', IF(MONTH("+tn+".date) <= 6, 1, 2), 0) = "+st+".semi"
         + "\n " + "  AND IF("+tn+".pdf_freq = 'freq_monthly_3', QUARTER("+tn+".date), 0) = "+st+".qrt"
         + "\n " + "  AND IF("+tn+".pdf_freq = 'freq_monthly_1', MONTH("+tn+".date), 0) = "+st+".mth"); 
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_protokoll_sent", "right join", "cms_auth_stammdaten_user", "ID_USER", "AUL_ID"); 
        
        /**************************************/
        /************ Set Filter *************/
        String glue = "";
        
        if (NUID != 0) {
            
            if(hasGlobalFilters()){
                glue = "AND";
            }
            
            db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein(tableName, "nurse_user_id", "=", Integer.toString(NUID), glue);
        }
        
        ArrayList<AbstractField> filterList = getActiveGlobalFilters(); 
        
        if(filterList.contains(filterMonth)){
            
            java.sql.Timestamp sqlDateFrom = new java.sql.Timestamp(filterMonth.getValue().getTime());
            java.sql.Timestamp sqlDateUntil = new java.sql.Timestamp(new LocalDateTime(filterMonth.getValue()).plusMonths(1).minusMillis(1).toDate().getTime());
            
            filterList.remove(filterMonth);
            glue = hasGlobalFilters(filterList) ? "AND" : "";
            
            db.DB_Data_Get.DB_Filter.DB_WHERE_BETWEEN(tableName, "date", "'" + sqlDateFrom.toString() + "'",  "'" + sqlDateUntil.toString() + "'", glue);
        }
        
        if(filterList.contains(filterProject)){
            
            filterList.remove(filterProject);
            glue = hasGlobalFilters(filterList) ? "AND" : "";
            
            Collection<Integer> coll = ((Collection<Integer>) filterProject.getValue());
            
            
            db.DB_Data_Get.DB_Filter.DB_WHERE_In(tableName, "project", Joiner.on(",").join(coll), glue);
        }
        
        if(filterList.contains(filterStatus)) {
            
            filterList.remove(filterStatus);
            glue = hasGlobalFilters(filterList) ? "AND" : "";
            
            Collection<String> coll = MyUtils.wrapStringCollection((Collection<String>) filterStatus.getValue(), "'");
            
            db.DB_Data_Get.DB_Filter.DB_WHERE_In(tableName, "status", Joiner.on(",").join(coll), glue);
            
        }

        if(filterList.contains(filterShippingType)) {
            
            filterList.remove(filterShippingType);
            glue = hasGlobalFilters(filterList) ? "AND" : "";
            
            Collection<String> coll = MyUtils.wrapStringCollection((Collection<String>) filterShippingType.getValue(), "'");
            
            db.DB_Data_Get.DB_Filter.DB_WHERE_In(tableName, "pdf_type", Joiner.on(",").join(coll), glue);
            
        }
        
        if(filterList.contains(filterShippingFreq)) {
            
            filterList.remove(filterShippingFreq);
            glue = hasGlobalFilters(filterList) ? "AND" : "";
            
            Collection<String> coll = MyUtils.wrapStringCollection((Collection<String>) filterShippingFreq.getValue(), "'");
            
            db.DB_Data_Get.DB_Filter.DB_WHERE_In(tableName, "pdf_freq", Joiner.on(",").join(coll), glue);
            
        }
        
        /**************************************/
        
        db.DB_Data_Get.DB_Ordnen.DB_Ordnen("date", "ASC");
        db.DB_Data_Get.DB_Ordnen.DB_Ordnen("id", "ASC");
        
        /**************************************/
        /************ Set Custom *************/
        /**************************************/
//        db.DB_Data_Get.Set_Type("nurse_name", nurse_name.class);
//        db.DB_Data_Get.Set_Type("patient_name", patient_name.class);
//        db.DB_Data_Get.Set_Type("arzt_name", arzt_name.class);
//        db.DB_Data_Get.Set_Type("reglead_name", reglead_name.class);
        db.DB_Data_Get.Set_Type("IF_NAME", IF_NAME.class);
//        db.DB_Data_Get.Set_Type("pdf_type", pdf_type.class);
//        db.DB_Data_Get.Set_Type("pdf_freq", pdf_freq.class);

        
        /* **************************/
        
//        db.debugNextQuery(true);
        
        try {
        	Container container = db.DB_Data_Get.DB_SEND_AND_GET_Container();
            
        	for (Object iid : container.getItemIds()) {
                typeConverter.convertType(container.getItem(iid));
            }
        	
        	if (tableUpdater != null) {
                tableUpdater.updateTable(container);
            } else {
                tbl_data.setContainerDataSource(container);
            }
        	
		} catch (Exception e) {
			// TASK: handle exception
			System.out.println("exception!");
			UI.getCurrent().getUI().removePollListener(pollListener);
		}
        
    }
    
    
    @AutoGenerated
    private HorizontalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new HorizontalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // mainContainer
        mainContainer = buildMainContainer();
        mainLayout.addComponent(mainContainer);
        mainLayout.setExpandRatio(mainContainer, 1.0f);
        mainLayout.setComponentAlignment(mainContainer, new Alignment(20));
        
        return mainLayout;
    }

    @AutoGenerated
    private VerticalLayout buildMainContainer() {
        // common part: create layout
        mainContainer = new VerticalLayout();
        mainContainer.setImmediate(false);
        mainContainer.setWidth("100.0%");
        mainContainer.setHeight("100.0%");
        mainContainer.setMargin(true);
        
        // menuSpacer
        menuSpacer = buildMenuSpacer();
        mainContainer.addComponent(menuSpacer);
        
        // globalFilterContainer
        globalFilterContainer = buildGlobalFilterContainer();
        mainContainer.addComponent(globalFilterContainer);
        mainContainer.setComponentAlignment(globalFilterContainer, new Alignment(48));
        
        // tbl_data
        tbl_data = new FilterTable();
        tbl_data.setImmediate(true);
        tbl_data.setWidth("100.0%");
        tbl_data.setHeight("100.0%");
        mainContainer.addComponent(tbl_data);
        mainContainer.setExpandRatio(tbl_data, 1.0f);
        mainContainer.setComponentAlignment(tbl_data, new Alignment(20));
        
        return mainContainer;
    }

    @AutoGenerated
    private VerticalLayout buildMenuSpacer() {
        // common part: create layout
        menuSpacer = new VerticalLayout();
        menuSpacer.setImmediate(false);
        menuSpacer.setWidth("100.0%");
        menuSpacer.setHeight("40px");
        menuSpacer.setMargin(false);
        
        // men_frm
        men_frm = new MenuBar();
        men_frm.setImmediate(false);
        men_frm.setWidth("100.0%");
        men_frm.setHeight("-1px");
        menuSpacer.addComponent(men_frm);
        menuSpacer.setComponentAlignment(men_frm, new Alignment(20));
        
        return menuSpacer;
    }

    @AutoGenerated
    private HorizontalLayout buildGlobalFilterContainer() {
        // common part: create layout
        globalFilterContainer = new HorizontalLayout();
        globalFilterContainer.setImmediate(false);
        globalFilterContainer.setWidth("100.0%");
        globalFilterContainer.setHeight("110px");
        globalFilterContainer.setMargin(false);
        
        // verticalLayout_1
        verticalLayout_1 = buildVerticalLayout_1();
        globalFilterContainer.addComponent(verticalLayout_1);
        globalFilterContainer.setComponentAlignment(verticalLayout_1, new Alignment(20));
        
        // verticalLayout_2
        verticalLayout_2 = buildVerticalLayout_2();
        globalFilterContainer.addComponent(verticalLayout_2);
        
        // verticalLayout_3
        verticalLayout_3 = buildVerticalLayout_3();
        globalFilterContainer.addComponent(verticalLayout_3);
        
        // verticalLayout_4
        verticalLayout_4 = buildVerticalLayout_4();
        globalFilterContainer.addComponent(verticalLayout_4);
        
        // verticalLayout_5
        verticalLayout_5 = buildVerticalLayout_5();
        globalFilterContainer.addComponent(verticalLayout_5);
        
        return globalFilterContainer;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_1() {
        // common part: create layout
        verticalLayout_1 = new VerticalLayout();
        verticalLayout_1.setImmediate(false);
        verticalLayout_1.setWidth("-1px");
        verticalLayout_1.setHeight("-1px");
        verticalLayout_1.setMargin(false);
        verticalLayout_1.setSpacing(true);
        
        // filterMonthEnabled
        filterMonthEnabled = new CheckBox();
        filterMonthEnabled.setCaption("Monatsfilter");
        filterMonthEnabled.setImmediate(false);
        filterMonthEnabled.setWidth("-1px");
        filterMonthEnabled.setHeight("-1px");
        verticalLayout_1.addComponent(filterMonthEnabled);
        verticalLayout_1.setComponentAlignment(filterMonthEnabled, new Alignment(48));
        
        // filterMonth
        filterMonth = new PopupDateField();
        filterMonth.setImmediate(false);
        filterMonth.setWidth("-1px");
        filterMonth.setHeight("-1px");
        verticalLayout_1.addComponent(filterMonth);
        
        return verticalLayout_1;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_2() {
        // common part: create layout
        verticalLayout_2 = new VerticalLayout();
        verticalLayout_2.setImmediate(false);
        verticalLayout_2.setWidth("-1px");
        verticalLayout_2.setHeight("-1px");
        verticalLayout_2.setMargin(false);
        verticalLayout_2.setSpacing(true);
        
        // filterProjectEnabled
        filterProjectEnabled = new CheckBox();
        filterProjectEnabled.setCaption("Projektfilter");
        filterProjectEnabled.setImmediate(false);
        filterProjectEnabled.setWidth("-1px");
        filterProjectEnabled.setHeight("-1px");
        verticalLayout_2.addComponent(filterProjectEnabled);
        verticalLayout_2.setComponentAlignment(filterProjectEnabled, new Alignment(48));
        
        // filterProject
        filterProject = new TwinColSelect();
        filterProject.setImmediate(false);
        filterProject.setWidth("-1px");
        filterProject.setHeight("70px");
        verticalLayout_2.addComponent(filterProject);
        
        return verticalLayout_2;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_3() {
        // common part: create layout
        verticalLayout_3 = new VerticalLayout();
        verticalLayout_3.setImmediate(false);
        verticalLayout_3.setWidth("-1px");
        verticalLayout_3.setHeight("-1px");
        verticalLayout_3.setMargin(false);
        verticalLayout_3.setSpacing(true);
        
        // filterStatusEnabled
        filterStatusEnabled = new CheckBox();
        filterStatusEnabled.setCaption("Statusfilter");
        filterStatusEnabled.setImmediate(false);
        filterStatusEnabled.setWidth("-1px");
        filterStatusEnabled.setHeight("-1px");
        verticalLayout_3.addComponent(filterStatusEnabled);
        verticalLayout_3.setComponentAlignment(filterStatusEnabled, new Alignment(48));
        
        // filterStatus
        filterStatus = new TwinColSelect();
        filterStatus.setImmediate(false);
        filterStatus.setWidth("-1px");
        filterStatus.setHeight("70px");
        verticalLayout_3.addComponent(filterStatus);
        
        return verticalLayout_3;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_4() {
        // common part: create layout
        verticalLayout_4 = new VerticalLayout();
        verticalLayout_4.setImmediate(false);
        verticalLayout_4.setWidth("-1px");
        verticalLayout_4.setHeight("-1px");
        verticalLayout_4.setMargin(false);
        verticalLayout_4.setSpacing(true);
        
        // filterShippingTypeEnabled
        filterShippingTypeEnabled = new CheckBox();
        filterShippingTypeEnabled.setCaption("Versandartsfilter");
        filterShippingTypeEnabled.setImmediate(false);
        filterShippingTypeEnabled.setWidth("-1px");
        filterShippingTypeEnabled.setHeight("-1px");
        verticalLayout_4.addComponent(filterShippingTypeEnabled);
        verticalLayout_4.setComponentAlignment(filterShippingTypeEnabled, new Alignment(48));
        
        // filterShippingType
        filterShippingType = new TwinColSelect();
        filterShippingType.setImmediate(false);
        filterShippingType.setWidth("-1px");
        filterShippingType.setHeight("70px");
        verticalLayout_4.addComponent(filterShippingType);
        
        return verticalLayout_4;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_5() {
        // common part: create layout
        verticalLayout_5 = new VerticalLayout();
        verticalLayout_5.setImmediate(false);
        verticalLayout_5.setWidth("-1px");
        verticalLayout_5.setHeight("-1px");
        verticalLayout_5.setMargin(false);
        verticalLayout_5.setSpacing(true);
        
        // filterShippingFreqEnabled
        filterShippingFreqEnabled = new CheckBox();
        filterShippingFreqEnabled.setCaption("Versandintervallsfilter");
        filterShippingFreqEnabled.setImmediate(false);
        filterShippingFreqEnabled.setWidth("-1px");
        filterShippingFreqEnabled.setHeight("-1px");
        verticalLayout_5.addComponent(filterShippingFreqEnabled);
        verticalLayout_5.setComponentAlignment(filterShippingFreqEnabled, new Alignment(48));
        
        // filterShippingFreq
        filterShippingFreq = new TwinColSelect();
        filterShippingFreq.setImmediate(false);
        filterShippingFreq.setWidth("-1px");
        filterShippingFreq.setHeight("70px");
        verticalLayout_5.addComponent(filterShippingFreq);
        
        return verticalLayout_5;
    }
}
