package archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.InventoryManager.form;

import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import org.joda.time.LocalDate;
import org.tepi.filtertable.FilterTable;

import archenoah.config.CMS_Config_Std;
import archenoah.lib.custom.ComponentIterator;
import archenoah.lib.custom.MyUtils;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.vaadin.Components.ClickMenuBar.ClickCommand;
import archenoah.lib.vaadin.Components.Combo.combo;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Tab_Menue_Item;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Window_Button;
import archenoah.lib.vaadin.Components.table.FilteringTableUpdater;
import archenoah.lib.vaadin.CustomConverterFactorys.StringSqlTimestampConverter;
import archenoah.lib.vaadin.Language.i18n.I18nCB;
import archenoah.lib.vaadin.Language.i18n.I18nConverter;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalMessages;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.lib.vaadin.MenuBerechtigung.Rechteholen;
import archenoah.lib.vaadin.resources.Icons;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.classes.UserAttributesCountry;

import com.google.common.base.Joiner;
import com.google.gwt.thirdparty.guava.common.base.Strings;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.event.UIEvents.PollEvent;
import com.vaadin.event.UIEvents.PollListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.shared.ui.datefield.Resolution;
import com.vaadin.ui.AbstractField;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.InlineDateField;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.Window.CloseEvent;
import com.vaadin.ui.Window.CloseListener;

import de.steinwedel.messagebox.ButtonId;
import de.steinwedel.messagebox.MessageBoxListener;


@SuppressWarnings({"serial", "rawtypes", "unchecked"})
public class InventoryManagerDataView extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private HorizontalLayout mainLayout;

    @AutoGenerated
    private VerticalLayout mainContainer;

    @AutoGenerated
    private FilterTable tbl_data;

    @AutoGenerated
    private HorizontalLayout globalFilterContainer;

    @AutoGenerated
    private HorizontalLayout filterLayoutProduct;

    @AutoGenerated
    private ComboBox filterProduct;

    @AutoGenerated
    private HorizontalLayout filterLayoutCountry;

    @AutoGenerated
    private ComboBox filterCountry;

    @AutoGenerated
    private HorizontalLayout filterLayoutMonth;

    @AutoGenerated
    private InlineDateField filterMonth;

    @AutoGenerated
    private CheckBox filterMonthEnabled;

    @AutoGenerated
    private VerticalLayout menuSpacer;

    @AutoGenerated
    private MenuBar men_frm;

    

    

	

	

	

	

	

	

	

	

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */

    /**************** --> Allgemein <--- ********************/
    // Datenbank
    private Map<Object, String> componentMap;
    private FilteringTableUpdater tableUpdater = null;

    // Berrechtigung
    private int ACC_ID;

    private int permRead;
    private int permCreate;
    private int permUpdate;
    private int permDelete;

    private MenuItem tmpMenu = null;

    private Button tmpButton = null;
    /******************************************************/
    /**************** --> Tabsheetvars <--- *****************/
    private TabSheet tab = null;

    /******************************************************/
    /**************** --> Windowvars <--- *******************/
    private Window win = null;
    /******************************************************/

    private DetachListener onDetach = null;

    /******************* -> Menüpunkte <- ********************/
//    private MenuBar.MenuItem btn_create;
    private MenuBar.MenuItem btn_update;
//    private MenuBar.MenuItem btn_read;
//    private MenuBar.MenuItem btn_delete;
    private MenuBar.MenuItem btn_filter;

    
    /*******************************************************/
    /******************* --> Custom <--- ********************/
    /******************************************************/

    private Boolean firstFilter = true;
    private PollListener pollListener = null;
    
    enum Status {}
    
    /************ ----->Einstellungen<-- ********************/
//    private final String formIdLng = "111";
    private final String formIdPerm = "111";
    private final String winHeight = "600px";
    private final String winWidth = "900px";


    /******************************************************/

    private final String tableIdCol = "SIB_ID";
    
    //TASK cols
    private final Object[] tableColsAll = new Object[] {"SIB_ID", "SIB_CREATED", "SIB_COUNTRY", "PP_PRODUCT", "user", "SIBA_ACTION", "SIB_DELTA", "SIB_BALANCE", "SIB_DATA", "SIB_COMMENT"};
    //use custom Cols when needed
    private Object[] tableColsDefault = new Object[] {"SIB_CREATED", "SIB_COUNTRY", "PP_PRODUCT", "SIB_BALANCE"};
    private Object[] tableColsDetail = tableColsAll;
    //use custom Cols when needed
    private Object[] tableColsActive = tableColsDefault;


    private StringSqlTimestampConverter dateConverter;
    private StringSqlTimestampConverter timeConverter;
    private I18nConverter actionConverter;

    private I18nManager i18n;
    
    private final static class caption extends I18nCB {
        static final I18nCB combo_all = set();
    }
    
    /******************************************************/

    public InventoryManagerDataView(MenuItem Arg_Menü) {
        tmpMenu = Arg_Menü;
    }

    public InventoryManagerDataView(Button Arg_btn) {
        tmpButton = Arg_btn;
    }

    /***************************** ---> Feste Funtionen<--- **************************************/

    /********* INIT-Window ************/
    public void init() {

        Standard_Init();

        if (tmpMenu != null) {
            String Recourcename = tmpMenu.getIcon().toString();
            Recourcename = Recourcename.substring(0, Recourcename.length() - 12) + "white-16.png";

            Build_Window_Button bwb = new Build_Window_Button(tmpMenu.getText(), mainLayout, winHeight, winWidth,
                    new ThemeResource(Recourcename));
            win = bwb.ReturnWindow();
        }
        if (tmpButton != null) {
            Build_Window_Button bwb = new Build_Window_Button(tmpButton.getCaption(), mainLayout, winHeight, winWidth,
                    tmpButton.getIcon());
            win = bwb.ReturnWindow();
        }

        win.addDetachListener(onDetach);

    }
    
    public Window getWindow(){
    	return win;
    }
    
    public TabSheet getTabSheet(){
    	return tab;
    }
    
    public void init(TabSheet Arg_tab) {

        Standard_Init();
        tab = Arg_tab;
        if (tmpMenu != null) {
            new Build_Tab_Menue_Item(Arg_tab, tmpMenu.getText(), mainLayout, tmpMenu.getIcon());
        }
        if (tmpButton != null) {
            new Build_Tab_Menue_Item(Arg_tab, tmpButton.getCaption(), mainLayout, tmpButton.getIcon());
        }

        tab.getSelectedTab().addDetachListener(onDetach);
    }

    /********* Init-Standard ************/
    private void Standard_Init() {
        buildMainLayout();
        i18n = new I18nManager(this);
        
        registerComponents();
        
        generateMenu();
        
        setMenuPermissions();

        updateTable();
        tbl_data.setSortContainerPropertyId(tableIdCol);
        tbl_data.setSortAscending(true);
        tbl_data.sort();
        configureTable();
        configureComponents();
        
        updateTable();
        
        setupListenersAndDetachEvent();
        
        i18n.refresh();
    }
    
    // register components for lng and validation tools
    private void registerComponents(){
    	componentMap = new HashMap<Object, String>();
    	new ComponentIterator(mainContainer).createMap(componentMap);
    }
    
    private void setupListenersAndDetachEvent() {
        pollListener = new PollListener() {

            @Override
            public void poll(PollEvent event) {
                if(tab.isRendered(mainLayout)){
                    updateTable();
                }
            }
        };

        UI.getCurrent().getUI().addPollListener(pollListener);

        onDetach = new DetachListener() {

            @Override
            public void detach(DetachEvent event) {
                UI.getCurrent().getUI().removePollListener(pollListener);
            }
        };
    }
    
    @SuppressWarnings("unused")
    public void setPermissionsFromDatabase() {
        if (formIdPerm == "") {
            System.out.println("Form Einstellung Fehlt: Berechtigung");
            return;
        }

        ACC_ID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        Rechteholen r = new Rechteholen(ACC_ID + "");
        String[][] perms = r.Datenholen();

        for (int i = 0; i < perms.length; i++) {
            if (perms[i][0].equals(formIdPerm) == true) {

                permRead = Integer.valueOf(perms[i][3]);
                permUpdate = Integer.valueOf(perms[i][4]);
                permCreate = Integer.valueOf(perms[i][6]);
                permDelete = Integer.valueOf(perms[i][5]);
                
            }
        }
    }

    public void setPermissions(int create, int read, int update, int delete) {

        permCreate = create;
        permRead = read;
        permUpdate = update;
        permDelete = delete;

    }

    private void setMenuPermissions() {
        Boolean c = (permCreate == 1);
        Boolean r = (permRead == 1);
        Boolean u = (permUpdate == 1);
        Boolean d = (permDelete == 1);

//        btn_create.setEnabled(c);
//        btn_create.setVisible(c);
//
//        btn_read.setEnabled(r);
//        btn_read.setVisible(r);
//
//        btn_update.setEnabled(u);
//        btn_update.setVisible(u);
//
//        btn_delete.setEnabled(d);
//        btn_delete.setVisible(d);
    }

    /************ -><- ******************/

    /***************** Comands *********************/
    
    CloseListener closeListener = new CloseListener() {
		
		@Override
		public void windowClose(CloseEvent e) {
			updateTable(true);
		}
	};
    
	private String getSelectedValue(){
		return Integer.toString((Integer) tbl_data.getContainerProperty(tbl_data.getValue(), tableIdCol).getValue());
	}
	
//    //TASK Commands are here
//    public Command cmd_btn_add = new Command() {
//        @Override
//        public void menuSelected(MenuItem selectedItem) {
//        
//        	BalanceManagerInsertEdit pie = new BalanceManagerInsertEdit(selectedItem, "");
//        	pie.setPermissions(permCreate, permRead, permUpdate, permDelete);
//        	pie.init();
//        	pie.getWindow().addCloseListener(closeListener);
//        	
//        }
//    };
//    
//    public Command cmd_btn_read = new Command() {
//        @Override
//        public void menuSelected(MenuItem selectedItem) {
//
//            if(tbl_data.getValue() == null){
//I18nManager.global(I18nGlobalNotifiers.no_entry_selected);
//                return;
//            }
//            
//            BalanceManagerInsertEdit pie = new BalanceManagerInsertEdit(selectedItem, getSelectedValue());
//        	pie.setPermissions(0, permRead, 0, 0);
//        	pie.init();
//
//
//        }
//    };
    
    public ClickCommand cmd_btn_edit = new ClickCommand() {
        @Override
        public void menuClicked(MenuItem selectedItem) {
            
            
            InventoryManagerInsertEdit pie = new InventoryManagerInsertEdit(selectedItem, "");
        	pie.setPermissions(permCreate, permRead, permUpdate, permDelete);
        	pie.init();
        	pie.getWindow().addCloseListener(closeListener);
        	
        	if(tbl_data.getValue() != null) {
        	    pie.fillFromItem(tbl_data.getContainerDataSource().getItem(tbl_data.getValue()));
        	}
            
        	this.setParent(men_frm);
        	this.setWindow(pie.getWindow());
        }
    };
//
//    public Command cmd_btn_del = new Command() {
//        @Override
//        public void menuSelected(MenuItem selectedItem) {
//            
//            if(tbl_data.getValue() == null){
// I18nManager.global(I18nGlobalNotifiers.no_entry_selected);
//                return;
//            }
//            
//            deleteData(getSelectedValue());
//
//        }
//    };

    public ClickCommand cmd_btn_filter = new ClickCommand() {
        @Override
        public void menuClicked(MenuItem selectedItem) {

            if (firstFilter) {
                tbl_data.setFilterBarVisible(true);
                tbl_data.setFilterBarVisible(false);
                firstFilter = false;
            }
            tbl_data.setFilterBarVisible(!tbl_data.isFilterBarVisible());
            
            if(!tbl_data.isFilterBarVisible()){
                tbl_data.clearFilters();
            }

        }
    };
    
    

    /******************************************/

    
    public void setGlobalFilterMonth(Date date){
        LocalDate ld = new LocalDate(date);
        filterMonthEnabled.setValue(true);
        filterMonth.setValue(new LocalDate(ld.getYear(), ld.getMonthOfYear(), 1).toDate());
    }
    
    public void setGlobalFilterMonth(){
        setGlobalFilterMonth(new Date());
    }

    /*********** Gen Menüs *************/
    private void generateMenu() {

//        btn_create = men_frm.addItem("FRM_ADD", Icons.White.add_16, cmd_btn_add);
        btn_update = men_frm.addItem("FRM_EDIT", Icons.White.edit_16, cmd_btn_edit);
//        btn_read = men_frm.addItem("FRM_READ", Icons.White.perm_lesen_16, cmd_btn_read);
//        btn_delete = men_frm.addItem("FRM_DEL", Icons.White.delete_16, cmd_btn_del);
        
        btn_filter = men_frm.addItem("FRM_FILTER", Icons.White.filter_16, cmd_btn_filter);

    }
    
    private void configureComponents(){
       
        
        // MONTHPICKER
        filterMonthEnabled.setValue(false);
        filterMonthEnabled.setImmediate(true);
        filterMonth.setResolution(Resolution.MONTH);
        filterMonth.setDateFormat("MMM yyyy");
        filterMonth.setEnabled(false);
        
        filterMonthEnabled.setImmediate(true);
        filterMonthEnabled.setEnabled(false);
        filterMonthEnabled.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                Boolean enabled = (Boolean)event.getProperty().getValue();
                filterMonth.setEnabled(enabled);
                if(enabled && filterMonth.getValue() == null){
                    setGlobalFilterMonth();
                }else if(!enabled){
                    filterMonth.setValue(null);
                }
                
            }
        });
        
        filterMonth.setImmediate(true);
        filterMonth.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                updateTable(true);
                
            }
        });
        
		
		filterProduct.setFilteringMode(FilteringMode.CONTAINS);
		filterProduct.setImmediate(true);
		filterProduct.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                toggleMonthFilterEnabled();
                updateTable(true);
                
            }
        });
		
		filterCountry.setFilteringMode(FilteringMode.CONTAINS);
		filterCountry.setItemCaptionPropertyId("CC_TEXT");
		filterCountry.setImmediate(true);
		filterCountry.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                toggleMonthFilterEnabled();
                updateTable(true);
                
            }
        });
		
		dbGetProducts();
		dbGetCountries();
		
    	
		addComponentListeners();
    }
    
    private void toggleMonthFilterEnabled() {
        
        Boolean enabled = (filterProduct.getValue() != null) && (filterCountry.getValue() != null);
        
        filterMonthEnabled.setValue(enabled);
        filterMonthEnabled.setEnabled(enabled);
        
    }
    
    private void addComponentListeners(){
    	

    }
    
    private ArrayList<AbstractField> getActiveGlobalFilters(){
        ArrayList<AbstractField> al = new ArrayList<AbstractField>();
        
        if(filterMonthEnabled.getValue()){
        	al.add(filterMonth);
        }
        
        if(filterProduct.getValue() != null){
        	al.add(filterProduct);
        }
        
        if(filterCountry.getValue() != null){
            al.add(filterCountry);
        }
        
        return al;
    }
    
    private Boolean hasGlobalFilters(ArrayList a){
        
        return (a.size() > 0);
        
    }
    
    private Boolean hasGlobalFilters(){
        
        return hasGlobalFilters(getActiveGlobalFilters());
        
    }
    
    /*************************** Config TBL ********************/

    private void configureTable() {
        tbl_data.setSelectable(true);
        tbl_data.setFilterOnDemand(false);
        tbl_data.setImmediate(true);
        tbl_data.setColumnCollapsingAllowed(false);
        tbl_data.setFooterVisible(true);
        tbl_data.setPageLength(1);
        try {
        	if(tableColsDefault.length > 0){
        		tbl_data.setVisibleColumns(tableColsDefault);
        	}
		} catch (Exception e) {

		}
        
        setTableConverters();
        
        tableUpdater = new FilteringTableUpdater(tbl_data);
        

        for (Object col : tableColsAll) {
        	
        	try {
        		tbl_data.setColumnExpandRatio(col, 1);
			} catch (Exception e) {
				
			}
        		
		}
        
        tbl_data.setColumnExpandRatio("SIB_ID", 0f);
        tbl_data.setColumnExpandRatio("SIB_COMMENT", 5f);
    }
    
    private void setTableConverters() {
        
        if(dateConverter == null) {
            dateConverter = new StringSqlTimestampConverter();
            dateConverter.setDateFormat(DateFormat.SHORT);
        }
        
        if(timeConverter == null) {
            timeConverter = new StringSqlTimestampConverter();
            timeConverter.setDateFormat(DateFormat.SHORT);
            timeConverter.setTimeFormat(DateFormat.SHORT);
        }
        
        if(actionConverter == null) {
            actionConverter = new I18nConverter("cust_stock_inventory_balance_actions", "SIBA_ACTION");
        }
        
        
        if(tbl_data.getContainerPropertyIds().contains("SIB_CREATED")) {
            tbl_data.setConverter("SIB_CREATED", timeConverter);
        }
        
        if(tbl_data.getContainerPropertyIds().contains("SIBA_ACTION")) {
            tbl_data.setConverter("SIBA_ACTION", actionConverter);
        }
        
    }

    /*************************** Database ********************/
    
    /********************************/
    
    
    private void updateTable(){
        updateTable(false);
    }
    
    private void updateTable(Boolean ignoreFilter) {

        if (ignoreFilter || !tbl_data.isFilterBarVisible()) {
            dbGetContainer();
            try{
            	if(tableColsActive.length > 0){
            		tbl_data.setVisibleColumns(tableColsActive);
            	}
            	setTableConverters();
            }catch(Exception e){
                
            }
            
            if(tbl_data.size() > 0) {
                i18n.refresh();
            }

        }
        
//        tbl_data.setColumnFooter("Status", "Σ " + tbl_data.size());
        
    }
    
    private void deleteData(final String id){
        
        I18nManager.global(I18nGlobalMessages.confirm_delete, new MessageBoxListener() {
            
            @Override
            public void buttonClicked(ButtonId arg0) {
                if(ButtonId.YES == arg0) {
                    dbDeleteData(id);
                }
            }
        });
    }
    
    
    //TASK dbget
	private void dbGetContainer() {

        DBClass db = new DBClass();

        /************ Set Spalten *************/
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("*");

        /**************************************/
        /************ Set Filter *************/
        
        ArrayList<AbstractField> filterList = getActiveGlobalFilters(); 
        String glue = "";
        String filterString = hasGlobalFilters(filterList) ? " WHERE " : "";
        
        if(filterMonthEnabled.getValue() && filterMonth.getValue() != null){
            
            java.sql.Timestamp sqlDateFrom = new java.sql.Timestamp(new LocalDate(filterMonth.getValue()).minusDays(1).toDate().getTime());
            java.sql.Timestamp sqlDateUntil = new java.sql.Timestamp(new LocalDate(filterMonth.getValue()).plusMonths(1).plusDays(0).toDate().getTime());
            
            filterList.remove(filterMonth);
            glue = hasGlobalFilters(filterList) ? " AND " : "";
            
            filterString += "SIB_CREATED BETWEEN '"+sqlDateFrom.toString()+"' AND '"+sqlDateUntil.toString()+"'" + glue;
            
        }
        
        if(filterProduct.getValue() != null){

            filterList.remove(filterProduct);
            glue = hasGlobalFilters(filterList) ? " AND " : "";
            
            filterString += "SIB_ID_PRODUCT = " + filterProduct.getValue() + glue;
          	
        }
        
        if(filterCountry.getValue() != null){

            filterList.remove(filterCountry);
            glue = hasGlobalFilters(filterList) ? " AND " : "";
            
            filterString += "SIB_COUNTRY = '" + filterCountry.getValue()  + "'" + glue;
            
        }
        
        /**************************************/
        /************ Set Tabelle *************/
        
        String sql = "";
        
        if(filterProduct.getValue() != null && filterCountry.getValue() != null) {
            
            tableColsActive = tableColsDetail;
            
            sql = "SELECT"
             + "\n " + "    SIB_ID"
             + "\n " + "    , SIB_CREATED"
             + "\n " + "    , SIB_COUNTRY"
             + "\n " + "    , PP_ID" // used in InsertEdit
             + "\n " + "    , PP_PRODUCT"
             + "\n " + "    , CONCAT(AUL_VORNAME, ' ', AUL_NAME) as `user`"
             + "\n " + "    , SIBA_ACTION"
             + "\n " + "    , SIB_DELTA"
             + "\n " + "    , SIB_BALANCE"
             + "\n " + "    , SIB_DATA"
             + "\n " + "    , SIB_COMMENT"
             + "\n " + "FROM cust_stock_inventory_balance"
             + "\n " + "LEFT JOIN cust_prescriptions_products on PP_ID = SIB_ID_PRODUCT"
             + "\n " + "LEFT JOIN cms_auth_stammdaten_user on SIB_ID_USER = AUL_ID"
             + "\n " + "LEFT JOIN cust_stock_inventory_balance_actions on SIB_ACTION = SIBA_ID"
             + "\n " + ""
             + "\n " + filterString
             + "\n " + "ORDER BY SIB_ID ASC";
        }else {
            
            tableColsActive = tableColsDefault;
            
            sql = "SELECT"
             + "\n " + "    SIB_CREATED"
             + "\n " + "    , PP_ID" // used in InsertEdit
             + "\n " + "    , SIB_COUNTRY"
             + "\n " + "    , PP_PRODUCT"
             + "\n " + "    , SIB_BALANCE"
             + "\n " + "FROM "
             + "\n " + "    cust_stock_inventory_balance as inv"
             + "\n " + "    JOIN -- hacky double groupwise maximum to get id of latest entry"
             + "\n " + "    ("

             + "\n " + " -- get latest date for each product"
             + "\n " + "            select md.product, md.country, id.max_id from "
             + "\n " + "            ("
             + "\n " + "                SELECT"
             + "\n " + "                    m.SIB_ID_PRODUCT as product"
             + "\n " + "                    , m.SIB_COUNTRY as country"
             + "\n " + "                    , MAX(m.SIB_CREATED) AS max_date"
             + "\n " + "                FROM cust_stock_inventory_balance as m"
             + "\n " + "                GROUP BY m.SIB_COUNTRY, m.SIB_ID_PRODUCT"
             + "\n " + "            ) as md"
             + "\n " + "            "
             + "\n " + "            -- join it on highest id for each date"
             + "\n " + "            left join "
             + "\n " + "            ("
             + "\n " + "                select MAX(SIB_ID) as max_id, SIB_CREATED as created, SIB_ID_PRODUCT as product, SIB_COUNTRY as country from "
             + "\n " + "                    cust_stock_inventory_balance"
             + "\n " + "                    group by SIB_COUNTRY, SIB_ID_PRODUCT, SIB_CREATED"
             + "\n " + "            ) as id on md.max_date = id.created and md.product = id.product and md.country = id.country"
             
             + "\n " + "    ) as sub"
             + "\n " + "    ON inv.SIB_ID_PRODUCT = sub.product AND inv.SIB_ID = sub.max_id AND inv.SIB_COUNTRY = sub.country"
             + "\n " + "    LEFT JOIN cust_prescriptions_products on PP_ID = SIB_ID_PRODUCT"
             + "\n " + ""
             + "\n " + filterString
             + "\n " + "ORDER BY inv.SIB_ID";
        }
        
        db.CustomQuery.setSqlString(sql);
        
        
//        db.debugNextQuery(true);
        
        try {
        	Container container = db.CustomQuery.query();
            
        	if (tableUpdater != null) {
                tableUpdater.updateTable(container);
            } else {
                tbl_data.setContainerDataSource(container);
            }
        	
		} catch (Exception e) {
			// TASK: handle exception
			System.out.println("exception!");
			UI.getCurrent().getUI().removePollListener(pollListener);
		}
        
    }
    
    private String generateCollectionString(Collection<Integer> ids){
        String in = "";
        String comma = "";
        
        for (Integer integer : ids) {
            in += comma + integer;
            if(Strings.isNullOrEmpty(comma)){
                comma = ", ";
            }
        }
        
        return in;
    }
    
    private void dbDeleteData(String id){
    
        CMS_Config_Std std = CMS_Config_Std.getInstance();
    
        DBClass db = new DBClass();
        db.DB_Data_Delete.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_prescriptions_list");
        db.DB_Data_Delete.DB_Filter.DB_WHERE_Allgemein("cust_prescriptions_list", tableIdCol, "=", id, "");
        db.DB_Data_Delete.DB_Delete();
    
        I18nManager.global(I18nGlobalNotifiers.entry_deleted);
        
        updateTable(true);

        
    }
    
    private void dbGetProducts(){
    	
    	DBClass db = new DBClass();
    	
    	
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("*");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_prescriptions_products");
        
        try {
        	
        	filterProduct.addItem(0);
        	filterProduct.setItemCaption(0, i18n.get("combo_all"));
        	filterProduct.setNullSelectionItemId(0);
        	
            combo nc = new combo(db.DB_Data_Get.DB_SEND_AND_GET(), filterProduct, "PP_ID", "PP_PRODUCT");
        } catch (Exception e) {
        	filterProduct.removeAllItems();
        }
        
    }
    
    private void dbGetCountries() {
        
        UserAttributesCountry uac = new UserAttributesCountry();
        uac.setCurrentUserId();
        
        HashMap<String, ArrayList<String>> map = uac.getUserAttributeMap();
        
        ArrayList<String> list = null;
        
        if(map != null && map.get("ordermanager_country") != null) {
            
            list = new ArrayList<String>();
            
            for (String code : map.get("ordermanager_country")) {
                list.add("'" + code + "'");
            }
            
        }
        
        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("*");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_countrycodes");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_countrycodes", "CC_LNG", "=", "1", "AND");
        if(list != null) {
            db.DB_Data_Get.DB_Filter.DB_WHERE_In("cust_countrycodes", "CC_CODE", Joiner.on(",").join(list), "");
        }else {
            db.DB_Data_Get.DB_Filter.DB_WHERE_In("cust_countrycodes", "CC_CODE", "'DE', 'AT'", "");
        }
        
        Container con = MyUtils.convertIndex(db.DB_Data_Get.DB_SEND_AND_GET(), "CC_CODE");
        
        filterCountry.setContainerDataSource(con);
        Boolean nsa = (con != null &&  con.size() > 1);
        filterCountry.setNullSelectionAllowed(nsa);
        if(!nsa) {
            filterCountry.setValue(con.getItemIds().iterator().next());
        }

        
    }
    
    @AutoGenerated
    private HorizontalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new HorizontalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // mainContainer
        mainContainer = buildMainContainer();
        mainLayout.addComponent(mainContainer);
        mainLayout.setExpandRatio(mainContainer, 1.0f);
        mainLayout.setComponentAlignment(mainContainer, new Alignment(20));
        
        return mainLayout;
    }

    @AutoGenerated
    private VerticalLayout buildMainContainer() {
        // common part: create layout
        mainContainer = new VerticalLayout();
        mainContainer.setImmediate(false);
        mainContainer.setWidth("100.0%");
        mainContainer.setHeight("100.0%");
        mainContainer.setMargin(true);
        
        // menuSpacer
        menuSpacer = buildMenuSpacer();
        mainContainer.addComponent(menuSpacer);
        
        // globalFilterContainer
        globalFilterContainer = buildGlobalFilterContainer();
        mainContainer.addComponent(globalFilterContainer);
        mainContainer.setComponentAlignment(globalFilterContainer, new Alignment(48));
        
        // tbl_data
        tbl_data = new FilterTable();
        tbl_data.setImmediate(true);
        tbl_data.setWidth("100.0%");
        tbl_data.setHeight("100.0%");
        mainContainer.addComponent(tbl_data);
        mainContainer.setExpandRatio(tbl_data, 1.0f);
        mainContainer.setComponentAlignment(tbl_data, new Alignment(20));
        
        return mainContainer;
    }

    @AutoGenerated
    private VerticalLayout buildMenuSpacer() {
        // common part: create layout
        menuSpacer = new VerticalLayout();
        menuSpacer.setImmediate(false);
        menuSpacer.setWidth("100.0%");
        menuSpacer.setHeight("40px");
        menuSpacer.setMargin(false);
        
        // men_frm
        men_frm = new MenuBar();
        men_frm.setImmediate(false);
        men_frm.setWidth("100.0%");
        men_frm.setHeight("-1px");
        menuSpacer.addComponent(men_frm);
        menuSpacer.setComponentAlignment(men_frm, new Alignment(20));
        
        return menuSpacer;
    }

    @AutoGenerated
    private HorizontalLayout buildGlobalFilterContainer() {
        // common part: create layout
        globalFilterContainer = new HorizontalLayout();
        globalFilterContainer.setImmediate(false);
        globalFilterContainer.setWidth("100.0%");
        globalFilterContainer.setHeight("80px");
        globalFilterContainer.setMargin(false);
        
        // filterLayoutMonth
        filterLayoutMonth = buildFilterLayoutMonth();
        globalFilterContainer.addComponent(filterLayoutMonth);
        globalFilterContainer.setComponentAlignment(filterLayoutMonth, new Alignment(48));
        
        // filterLayoutCountry
        filterLayoutCountry = buildFilterLayoutCountry();
        globalFilterContainer.addComponent(filterLayoutCountry);
        globalFilterContainer.setComponentAlignment(filterLayoutCountry, new Alignment(48));
        
        // filterLayoutProduct
        filterLayoutProduct = buildFilterLayoutProduct();
        globalFilterContainer.addComponent(filterLayoutProduct);
        globalFilterContainer.setComponentAlignment(filterLayoutProduct, new Alignment(48));
        
        return globalFilterContainer;
    }

    @AutoGenerated
    private HorizontalLayout buildFilterLayoutMonth() {
        // common part: create layout
        filterLayoutMonth = new HorizontalLayout();
        filterLayoutMonth.setImmediate(false);
        filterLayoutMonth.setWidth("-1px");
        filterLayoutMonth.setHeight("-1px");
        filterLayoutMonth.setMargin(false);
        filterLayoutMonth.setSpacing(true);
        
        // filterMonthEnabled
        filterMonthEnabled = new CheckBox();
        filterMonthEnabled.setCaption("Monatsfilter");
        filterMonthEnabled.setImmediate(false);
        filterMonthEnabled.setWidth("-1px");
        filterMonthEnabled.setHeight("-1px");
        filterLayoutMonth.addComponent(filterMonthEnabled);
        filterLayoutMonth.setComponentAlignment(filterMonthEnabled, new Alignment(48));
        
        // filterMonth
        filterMonth = new InlineDateField();
        filterMonth.setImmediate(false);
        filterMonth.setWidth("-1px");
        filterMonth.setHeight("-1px");
        filterLayoutMonth.addComponent(filterMonth);
        
        return filterLayoutMonth;
    }

    @AutoGenerated
    private HorizontalLayout buildFilterLayoutCountry() {
        // common part: create layout
        filterLayoutCountry = new HorizontalLayout();
        filterLayoutCountry.setImmediate(false);
        filterLayoutCountry.setWidth("-1px");
        filterLayoutCountry.setHeight("-1px");
        filterLayoutCountry.setMargin(false);
        
        // filterCountry
        filterCountry = new ComboBox();
        filterCountry.setCaption("Apotheke");
        filterCountry.setImmediate(false);
        filterCountry.setWidth("-1px");
        filterCountry.setHeight("-1px");
        filterLayoutCountry.addComponent(filterCountry);
        
        return filterLayoutCountry;
    }

    @AutoGenerated
    private HorizontalLayout buildFilterLayoutProduct() {
        // common part: create layout
        filterLayoutProduct = new HorizontalLayout();
        filterLayoutProduct.setImmediate(false);
        filterLayoutProduct.setWidth("-1px");
        filterLayoutProduct.setHeight("-1px");
        filterLayoutProduct.setMargin(false);
        filterLayoutProduct.setSpacing(true);
        
        // filterProduct
        filterProduct = new ComboBox();
        filterProduct.setCaption("Medikament");
        filterProduct.setImmediate(false);
        filterProduct.setWidth("-1px");
        filterProduct.setHeight("-1px");
        filterLayoutProduct.addComponent(filterProduct);
        filterLayoutProduct.setComponentAlignment(filterProduct, new Alignment(48));
        
        return filterLayoutProduct;
    }
}
