package archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.servicetasking.form.submodules;

import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;

import org.tepi.filtertable.FilterTreeTable;

import archenoah.lib.custom.MyUtils;
import archenoah.lib.custom.comments.types.OrganisationComments;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.tool.comunication.dbclass.DBClass.CustomQuery;
import archenoah.lib.vaadin.Language.i18n.I18nCB;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.servicetasking.modules.ModuleComponent;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.servicetasking.modules.ModuleEntry;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.servicetasking.modules.converters.BooleanConverter;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Container.Filter;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;

public class SubmoduleAcquisition extends ModuleComponent{
	
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
    private HorizontalLayout mainLayout;


    @AutoGenerated
    private TabSheet tabSheet_1;


    @AutoGenerated
    private VerticalLayout commentsLayout;


    @AutoGenerated
    private OrganisationComments comments;


    @AutoGenerated
    private HorizontalLayout contentsLayout;


    @AutoGenerated
    private VerticalLayout dataLayout;


    @AutoGenerated
    private TextArea toDo;


    @AutoGenerated
    private ComboBox contact;


    @AutoGenerated
    private ComboBox organisation;


    @AutoGenerated
    private VerticalLayout topicLayout;


    @AutoGenerated
    private FilterTreeTable topics;


    // {section fields}
	// ****************
    
    private static org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(SubmoduleAcquisition.class);
    
	private I18nManager i18n;
	
	private HashMap<Integer, HashSet<Integer>> orgsByContact = new HashMap<>();
	private HashMap<Integer, HashSet<Integer>> contactsByOrg = new HashMap<>();
	
	private ModuleEntry checkboxes;
	private ModuleEntry data;
	
	private boolean commentFiltersInitialized = false;
	
	private final static class caption extends I18nCB {
        static final I18nCB idFilter = set();
    }
	
	// {end fields}

	// {section constructors}
	// **********************
	public SubmoduleAcquisition(){
		setCompositionRoot(buildMainLayout());
		i18n = new I18nManager(this);
		
		setupFields();
		configureListeners();
		configureComponents();
		
		fillFields();
		
        registerEntry(checkboxes);
        registerEntry(data);
        
        i18n.refresh();
        
	}
	// {end constructors}

	// {section gettersandsetters}
	// ***************************
	// {end gettersandsetters}

	// {section publicmethods}
	// ***********************
	// {end publicmethods}

	// {section privatemethods}
	// ************************

	private void configureListeners() {
	    addFieldChangeListener(new FieldValueChangeListener() {
            
            @Override
            public void onFieldValueChange(FieldValue fieldValue, Object value, Class<?> type) {
                
                switch (fieldValue) {
                case PARENT:
                    if(value != null) {
                        comments.setDataId((Integer) value);
                        addCommentFilters();
                    }
                    break;
                
                case READONLY:
                    comments.setReadOnly((Boolean) value);
                    break;

                default:
                    break;
                }
                
            }
        });
	    
	    addValueChangeListener(ParentValue.DATE, new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                dbGetOrganisationContacts();
            }
        });
	    
	    organisation.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                comments.setParentId((Integer) organisation.getValue());
                comments.setEnabled(organisation.getValue() != null);
                
            }
        });
        
        addSaveListener(new SaveListener() {
            
            @Override
            public void onSave() {
                
                comments.save();
                
            }
        });
        
        organisation.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                IndexedContainer cc =  (IndexedContainer) contact.getContainerDataSource();
                cc.removeAllContainerFilters();
                final Integer org = (Integer) event.getProperty().getValue(); 
                
                if(org == null) {
                    return;
                }

                cc.addContainerFilter(new Filter() {
                    
                    @Override
                    public boolean passesFilter(Object itemId, Item item) throws UnsupportedOperationException {
                        Integer cont = MyUtils.getValueFromItem(item, "id", Integer.class);
                        return (contactsByOrg.get(org) != null
                            && contactsByOrg.get(org).contains(cont)); 
                    }
                    
                    @Override
                    public boolean appliesToProperty(Object propertyId) {
                        return false;
                    }
                });
            }
        });
        
        contact.addValueChangeListener(new ValueChangeListener() {

            @Override
            public void valueChange(ValueChangeEvent event) {
                IndexedContainer co = (IndexedContainer) organisation.getContainerDataSource();
                co.removeAllContainerFilters();
                final Integer cont = (Integer) event.getProperty().getValue();

                if (cont == null) {
                    return;
                }

                co.addContainerFilter(new Filter() {

                    @Override
                    public boolean passesFilter(Object itemId, Item item) throws UnsupportedOperationException {
                        Integer org = MyUtils.getValueFromItem(item, "id", Integer.class);
                        return (orgsByContact.get(cont) != null
                            && orgsByContact.get(cont).contains(org));
                    }

                    @Override
                    public boolean appliesToProperty(Object propertyId) {
                        return false;
                    }
                });
            }
        });
	}
	
	private void setupFields() {
	    
	    checkboxes = new ModuleEntry("cust_protokoll_servicetasking_module_acquisition_multi", "PARENT");
        checkboxes.withMultiKey("KEY");
        
        data = new ModuleEntry("cust_protokoll_servicetasking_module_acquisition", "PARENT");
        data.withField(organisation, "PSMA_ORGANISATION_ID");
        data.withField(contact, "PSMA_CONTACT_ID");
        data.withField(toDo, "PSMA_TODO");
        
        buildTree();
        
        comments.setOrigin(SubmoduleAcquisition.class);
	}
	
	private void configureComponents(){
		
		toDo.setNullRepresentation("");
		
		organisation.setRequired(true);
		organisation.setImmediate(true);
		organisation.setItemCaptionPropertyId("organisation");

		contact.setRequired(true);
		contact.setImmediate(true);
		contact.setItemCaptionPropertyId("contact");
		
		comments.setEnabled(false);
	}
	
    private void addCommentFilters() {
        
        if(commentFiltersInitialized) {
            return;
        }
        
        CheckBox idFilter = new CheckBox(i18n.get(caption.idFilter));
        idFilter.setImmediate(true);
        idFilter.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                comments.filterDataId( (boolean) event.getProperty().getValue() ? getParentId() : null);
            }
        });
        
        comments.addTopComponent(idFilter);
        
        commentFiltersInitialized = true;
    }
	
	private void fillFields() {
	    dbFillOrganisation();
	    dbFillContact();
	}
	

	private void buildTree(){
		
		Container con = dbGetTree();

		BooleanConverter boolCon = new BooleanConverter();

        topics.addContainerProperty("topic", CheckBox.class, "");
        topics.setWidth("100%");
        topics.setHeight("100%");

        //insert TreeTable Components
        for (Object iid : con.getItemIds()) {
			
        	Item item = con.getItem(iid);
        	Integer id = MyUtils.getValueFromItem(item, "ID", Integer.class);
        	
			CheckBox cb = new CheckBox(MyUtils.getValueFromItem(item, "TOPIC", String.class));
			topics.addItem(id).getItemProperty("topic").setValue(cb);
			checkboxes.withMultiField(cb, "DATA", id, boolCon);
        	
		}
        
        //set TableTree structure
        for (Object iid : topics.getItemIds()) {	
        	topics.setParent(iid, MyUtils.getValueFromItem(con.getItem(iid), "PARENT", Integer.class));
		}
        
        //expand TreeTable -> ContainerItemsIds required
        for (Object itemId: con.getItemIds()){
            topics.setCollapsed(itemId, false);
        }
        
        i18n.includeTableProperties(topics, "topic");
        
	}
	
	
	// {end privatemethods}

	// {section database}
	// ******************
	
	private Container dbGetTree(){
		
		CustomQuery q = new DBClass().CustomQuery;
		String sql = "SELECT ID, PARENT, TOPIC FROM cust_protokoll_servicetasking_module_acquisition_topics";
		q.setSqlString(sql);
		
		return MyUtils.convertIndex(q.query(), "ID");
		
	}
	
	private void dbFillOrganisation(){
				
		CustomQuery q = new DBClass().CustomQuery;
		String sql = "SELECT OSL_ID as id, "
         + "\n " + "    CASE "
         + "\n " + "        WHEN ((OSL_PLZ IS NOT NULL and OSL_PLZ != '') or (OSL_ORT IS NOT NULL and OSL_ORT != '')) THEN"
         + "\n " + "            CONCAT_WS('', OSL_NAME , ' (', "
         + "\n " + "                IF(OSL_PLZ IS NOT NULL and OSL_PLZ != '', CONCAT(OSL_PLZ, "
         + "\n " + "                    IF(OSL_ORT IS NOT NULL and OSL_ORT != '', ' ', '')),"
         + "\n " + "                 ''), OSL_ORT, ')')"
         + "\n " + "        ELSE OSL_NAME"
         + "\n " + "    END AS organisation"
         + "\n " + "FROM cust_organisation_stammdaten_liste";
		q.setSqlString(sql);
		
		organisation.setContainerDataSource(MyUtils.convertIndex(q.query(), "id"));

	}
	
	private void dbFillContact(){
		
		CustomQuery q = new DBClass().CustomQuery;
		String sql = "  SELECT"
         + "\n " + "    arzt.ASA_ID as id,"
         + "\n " + "   CONCAT(usrAnr.ASA_NAME, ' ', "
         + "\n " + "        IF(arzt.ASA_TITEL IS NOT NULL and Arzt.ASA_TITEL != '', CONCAT(ASA_TITEL, ' '), ''),"
         + "\n " + "        usr.AUL_VORNAME, ' ', usr.AUL_NAME, ' (', "
         + "\n " + "        IF(arzt.ASA_PLZ IS NOT NULL and arzt.ASA_PLZ != '', CONCAT(arzt.ASA_PLZ, ' '), ''), arzt.ASA_ORT, ')')"
         + "\n " + "    AS contact"
         + "\n " + " FROM cust_verk_arzt_organisation vao"
         + "\n " + " LEFT JOIN cust_arzt_stammdaten_arzt arzt ON vao.VAO_ARZT_ID = arzt.ASA_ID"
         + "\n " + " LEFT JOIN cms_auth_stammdaten_user usr ON arzt.ASA_U_ID = usr.AUL_ID"
         + "\n " + " LEFT JOIN cms_auth_stammdaten_anrede usrAnr ON usr.AUL_ANREDE_ID = usrAnr.ASA_ID"
         + "\n " + " group by arzt.ASA_ID";
		
		q.setSqlString(sql);
//		q.db.debugNextQuery(true);
		
		contact.setContainerDataSource(MyUtils.convertIndex(q.query(), "id"));
	}
	
	private void dbGetOrganisationContacts() {
	    
	    Date date = getParentValue(ParentValue.DATE, Date.class);
	    
	    String where = "";
	    if(date != null) {
	        where = " WHERE VAO_DATE_UNTIL >= '" + MyUtils.formatSqlDate(date) + "' or VAO_DATE_UNTIL IS NULL";
	    }
	    
	    CustomQuery q = new DBClass().CustomQuery;
        String sql = "select * from cust_verk_arzt_organisation" + where;
        q.setSqlString(sql);
//        q.db.debugNextQuery(true);
        
        Container con = q.query();
        
        for (Object iid : con.getItemIds()) {
            Item item = con.getItem(iid);
            Integer contact = MyUtils.getValueFromItem(item, "VAO_ARZT_ID", Integer.class); 
            Integer org = MyUtils.getValueFromItem(item, "VAO_ORGANISATION_ID", Integer.class);
            
            if(orgsByContact.get(contact) == null) {
                orgsByContact.put(contact, new HashSet<Integer>(1));
            }
            if(contactsByOrg.get(org) == null) {
                contactsByOrg.put(org, new HashSet<Integer>(1));
            }
            
            orgsByContact.get(contact).add(org);
            contactsByOrg.get(org).add(contact);
        }
        
	}
	
	// {end database}

	// {section layout}
	// ****************
	
	
    @AutoGenerated
    private HorizontalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new HorizontalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);
        mainLayout.setSpacing(true);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // tabSheet_1
        tabSheet_1 = buildTabSheet_1();
        mainLayout.addComponent(tabSheet_1);
        
        return mainLayout;
    }

    @AutoGenerated
    private TabSheet buildTabSheet_1() {
        // common part: create layout
        tabSheet_1 = new TabSheet();
        tabSheet_1.setImmediate(true);
        tabSheet_1.setWidth("100.0%");
        tabSheet_1.setHeight("100.0%");
        
        // contentsLayout
        contentsLayout = buildContentsLayout();
        tabSheet_1.addTab(contentsLayout, "contents", null);
        
        // commentsLayout
        commentsLayout = buildCommentsLayout();
        tabSheet_1.addTab(commentsLayout, "comments", null);
        
        return tabSheet_1;
    }

    @AutoGenerated
    private HorizontalLayout buildContentsLayout() {
        // common part: create layout
        contentsLayout = new HorizontalLayout();
        contentsLayout.setStyleName("scrollfix");
        contentsLayout.setImmediate(false);
        contentsLayout.setWidth("98.0%");
        contentsLayout.setHeight("100.0%");
        contentsLayout.setMargin(true);
        contentsLayout.setSpacing(true);
        
        // topicLayout
        topicLayout = buildTopicLayout();
        contentsLayout.addComponent(topicLayout);
        
        // dataLayout
        dataLayout = buildDataLayout();
        contentsLayout.addComponent(dataLayout);
        contentsLayout.setComponentAlignment(dataLayout, new Alignment(48));
        
        return contentsLayout;
    }

    @AutoGenerated
    private VerticalLayout buildTopicLayout() {
        // common part: create layout
        topicLayout = new VerticalLayout();
        topicLayout.setImmediate(false);
        topicLayout.setWidth("100.0%");
        topicLayout.setHeight("100.0%");
        topicLayout.setMargin(false);
        
        // topics
        topics = new FilterTreeTable();
        topics.setImmediate(false);
        topics.setWidth("100.0%");
        topics.setHeight("100.0%");
        topicLayout.addComponent(topics);
        
        return topicLayout;
    }

    @AutoGenerated
    private VerticalLayout buildDataLayout() {
        // common part: create layout
        dataLayout = new VerticalLayout();
        dataLayout.setImmediate(false);
        dataLayout.setWidth("100.0%");
        dataLayout.setHeight("100.0%");
        dataLayout.setMargin(false);
        
        // organisation
        organisation = new ComboBox();
        organisation.setCaption("Organisation");
        organisation.setImmediate(false);
        organisation.setWidth("100.0%");
        organisation.setHeight("-1px");
        dataLayout.addComponent(organisation);
        dataLayout.setComponentAlignment(organisation, new Alignment(48));
        
        // contact
        contact = new ComboBox();
        contact.setCaption("Ansprechpartner");
        contact.setImmediate(false);
        contact.setWidth("100.0%");
        contact.setHeight("-1px");
        contact.setRequired(false);
        dataLayout.addComponent(contact);
        dataLayout.setExpandRatio(contact, 1.0f);
        dataLayout.setComponentAlignment(contact, new Alignment(48));
        
        // toDo
        toDo = new TextArea();
        toDo.setCaption("ToDo");
        toDo.setImmediate(false);
        toDo.setWidth("100.0%");
        toDo.setHeight("-1px");
        dataLayout.addComponent(toDo);
        dataLayout.setExpandRatio(toDo, 2.0f);
        dataLayout.setComponentAlignment(toDo, new Alignment(48));
        
        return dataLayout;
    }

    @AutoGenerated
    private VerticalLayout buildCommentsLayout() {
        // common part: create layout
        commentsLayout = new VerticalLayout();
        commentsLayout.setImmediate(false);
        commentsLayout.setWidth("100.0%");
        commentsLayout.setHeight("100.0%");
        commentsLayout.setMargin(true);
        
        // comments
        comments = new OrganisationComments();
        comments.setImmediate(false);
        comments.setWidth("100.0%");
        comments.setHeight("100.0%");
        commentsLayout.addComponent(comments);
        
        return commentsLayout;
    }
}
