package archenoah.scheduler.jobs;

import org.quartz.Job;
import org.quartz.JobExecutionContext;
import org.quartz.JobExecutionException;

import archenoah.lib.custom.MyUtils;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.tool.comunication.dbclass.DBClass.CustomQuery;
import archenoah.web.normal.main.Menuepunkte.Individuelle.TaskSystem.TaskManager.classes.TaskManagerMailHandler;
import archenoah.web.normal.main.Menuepunkte.Individuelle.TaskSystem.TaskManager.classes.TaskManagerMailHandler.MTYPE;

import com.vaadin.data.Container;
import com.vaadin.data.Item;

public class TaskMailerJob implements Job {

    
    // {section fields}
    // ****************
    private org.slf4j.Logger log;
    private TaskManagerMailHandler mailHandler;
    
    private Integer reminderDays = 3;  
    // {end fields}

    // {section constructors}
    // **********************
    public TaskMailerJob() {
        
        log = org.slf4j.LoggerFactory.getLogger(this.getClass());
        
        log.info("initTaskMailer");
        
        mailHandler = new TaskManagerMailHandler();
    }
    // {end constructors}

    // {section gettersandsetters}
    // ***************************
    // {end gettersandsetters}

    // {section publicmethods}
    // ***********************
    @Override
    public void execute(JobExecutionContext context) throws JobExecutionException {
        log.info("starting TaskMailerJob");

        try {
            Container con = dbGetTasks();
            
            if(con == null || con.size() == 0) {
                log.info("no relevant Tasks found");
                return;
            }
            
            log.info("found {} tasks, iterating", con.size());
            for (Object iid : con.getItemIds()) {
                handleTask(con.getItem(iid));
            }
            
        } catch (Exception e) {
            log.error("error executing TaskMailerJob: {}", e);
        }
        
        
    }
    // {end publicmethods}

    // {section privatemethods}
    // ************************
    
    private void handleTask(Item task) {
        log.info("handling task: {}", task);
        
        if(task == null) {
            log.warn("task was null");
            return;
        }
        
        MTYPE type = null;
        
        switch (MyUtils.getValueFromItem(task, "mtype", String.class)) {
        case "reminder":
            type = MTYPE.REMINDER;
            break;
        case "warning":
            type = MTYPE.WARNING;
            break;
        case "critical":
            type = MTYPE.CRITICAL;
            break;
        default:
            log.warn("no task type?");
            break;
        }
        
        if(type != null) {
            log.info("sending mails for task {} \n with type {}", task, type);
            mailHandler.setTask(task);
            mailHandler.addNotification(type);
            mailHandler.sendMails();
        }
        
    }
    
    // {end privatemethods}

    // {section database}
    // ******************
    private Container dbGetTasks() {
        
        DBClass db = new DBClass();
        CustomQuery q = db.CustomQuery;
        
        String sql = "select "
            + "\n "+ "  cust_taskmanager_tasks.*"
            + "\n "+ "   , (CASE "
            + "\n "+ "      WHEN TMT_REMINDER_DATE = DATE(NOW()) THEN 'reminder'"
            + "\n "+ "      WHEN (DATE_SUB(TMT_DUE, INTERVAL "+reminderDays+" DAY) = DATE(NOW()) and TMT_REMINDER_DATE IS NULL) THEN 'reminder'"
            + "\n "+ "      WHEN DATE_ADD(TMT_DUE, INTERVAL 1 DAY) = DATE(NOW()) THEN 'warning'"
            + "\n "+ "      WHEN DATE_ADD(TMT_DUE, INTERVAL 1 WEEK) = DATE(NOW()) THEN 'critical'"
            + "\n "+ "   END) as mtype"
            + "\n "+ "from cust_taskmanager_tasks"
            + "\n "+ "where"
            + "\n "+ "  TMT_ID_STATUS != 0 and ( # ignore closed tasks" 
            + "\n "+ "  TMT_REMINDER_DATE = DATE(NOW()) # reminder from capa"
            + "\n "+ "  or (DATE_SUB(TMT_DUE, INTERVAL "+reminderDays+" DAY) = DATE(NOW()) and TMT_REMINDER_DATE IS NULL) # reminder autogenerated"
            + "\n "+ "  or DATE_ADD(TMT_DUE, INTERVAL 1 DAY) = DATE(NOW()) # due date warning"
            + "\n "+ "  or DATE_ADD(TMT_DUE, INTERVAL 1 WEEK) = DATE(NOW()) # due date critical"
            + "\n "+ ")";
        
        q.setSqlString(sql);
//        db.debugNextQuery(true);
        
        return q.query();
        
    }
    // {end database}

    // {section layout}
    // ****************
    // {end layout}
}
