#!/bin/bash                                                                      

set -e                                                                           

printf '\npost-checkout hook\n\n'                                                

prevHEAD=$1                                                                      
newHEAD=$2                                                                       
checkoutType=$3                                                                  
branch=$(git rev-parse --abbrev-ref HEAD)

target='sql/_current/changes.sql'

export SRC_DIR=$(cd .; pwd)
                            
if [[ $checkoutType == 1 ]] && [[ $branch != "master" ]]
then

  mkdir -p sql/${branch}
  touch sql/${branch}/changes.sql
  
  rm -rf ./sql/_current
  cp -alf ${SRC_DIR}/sql/${branch}/ sql/_current
  
  # write develop changes into current and clear file for future reuse
  if [[ $branch = "release/"* ]] && [[ ! -s $target ]]; then
    
    wrap='/* *****************************\n** %s\n** ****************************/\n\n'
      
    [ -f sql/develop/changes.sql ] \
      && printf "${wrap}" 'from develop' >> $target \
      && cat sql/develop/changes.sql >> $target \
      && >| sql/develop/changes.sql
    
    if [ -d "./sql/feature" ]; then
      find ./sql/feature -maxdepth 1 -mindepth 1 -type d -exec printf "\n\n${wrap}" {} >> $target \; \
    -exec cat {}/changes.sql >> $target \; -exec rm -rf {} \;
    fi
    
    
    
  fi


fi