package archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.servicetasking.form;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;

import archenoah.global.UserAttributes;
import archenoah.lib.custom.ComponentIterator;
import archenoah.lib.custom.MyUtils;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.tool.comunication.dbclass.DBClass.CustomQuery;
import archenoah.lib.vaadin.Components.Combo.combo;
import archenoah.lib.vaadin.Components.Fields.CustomTimePicker;
import archenoah.lib.vaadin.Components.Steppers.IntStepper;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Tab_Menue_Item;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Window_Button;
import archenoah.lib.vaadin.Forms_Builder.Form_Bind;
import archenoah.lib.vaadin.Language.i18n.I18nConverter;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.lib.vaadin.MenuBerechtigung.Rechteholen;
import archenoah.lib.vaadin.resources.Icons;
import archenoah.lib.vaadin.valchecker.val_checker4;
import archenoah.web.normal.UserInfo.Nurse;
import archenoah.web.normal.UserInfo.UserData;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.OpenTickets.form.OpenTicketsInsertEdit;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.PackageCreator.classes.TicketDbActions;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.PackageCreator.classes.TicketDbActions.CreateParams;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.classes.ProjectLimits;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.classes.ProjectNurseCombos;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.classes.RegionalLeadCheck;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.classes.RegionalLeadCheck.FieldType;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.servicetasking.classes.I18nSTStatusConverter;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.servicetasking.modules.ModuleComponent;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.servicetasking.modules.ModuleComponent.ParentValue;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.servicetasking.modules.SubmoduleManager;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.tools.form_Berrechnen_Strecke;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Stammdaten.Krankenschwesternverwaltung.forms.form_nurse_insert_edit;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Stammdaten.Patientenverwaltung.Form.form_patient_insert_edit;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Container.Filter;
import com.vaadin.data.Item;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.server.ThemeResource;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.ui.AbstractComponent;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.Window.CloseEvent;
import com.vaadin.ui.Window.CloseListener;

@SuppressWarnings({"serial", "rawtypes", "unchecked"})
public class ServiceTaskingInsertEdit extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private VerticalLayout mainLayout;

    @AutoGenerated
    private HorizontalLayout buttons;

    @AutoGenerated
    private Button btn_save;

    @AutoGenerated
    private Button reset;

    @AutoGenerated
    private VerticalLayout main;

    @AutoGenerated
    private Panel panel_1;

    @AutoGenerated
    private VerticalLayout verticalLayout_4;

    @AutoGenerated
    private Panel dynamicData;

    @AutoGenerated
    private VerticalLayout verticalLayout_3;

    @AutoGenerated
    private HorizontalLayout staticDataLayout;

    @AutoGenerated
    private TabSheet staticDataTabs;

    @AutoGenerated
    private VerticalLayout captionLayout;

    @AutoGenerated
    private TextField captionField;

    @AutoGenerated
    private HorizontalLayout billingLayout;

    @AutoGenerated
    private VerticalLayout billingRightLayout;

    @AutoGenerated
    private IntStepper billingDistance;

    @AutoGenerated
    private CustomTimePicker billingTime;

    @AutoGenerated
    private VerticalLayout billingCenterLayout;

    @AutoGenerated
    private CheckBox adminEnabled;

    @AutoGenerated
    private Button calcTime;

    @AutoGenerated
    private VerticalLayout billingLeftLayout;

    @AutoGenerated
    private IntStepper nurseDistance;

    @AutoGenerated
    private CustomTimePicker nurseTime;

    @AutoGenerated
    private HorizontalLayout statusLayout;

    @AutoGenerated
    private VerticalLayout statusRightLayout;

    @AutoGenerated
    private ComboBox type;

    @AutoGenerated
    private ComboBox status;

    @AutoGenerated
    private VerticalLayout statusLeftLayout;

    @AutoGenerated
    private HorizontalLayout nurseLayout;

    @AutoGenerated
    private RegionalLeadCheck regionalManagerOk;

    @AutoGenerated
    private HorizontalLayout ticketLayout;

    @AutoGenerated
    private Button ticketEdit;

    @AutoGenerated
    private Button ticketCreate;

    @AutoGenerated
    private ComboBox nurse;

    @AutoGenerated
    private Button nurseInfo;

    @AutoGenerated
    private HorizontalLayout patientLayout;

    @AutoGenerated
    private TextField patient;

    @AutoGenerated
    private TextField patientInitials;

    @AutoGenerated
    private Button patientInfo;

    @AutoGenerated
    private VerticalLayout verticalLayout_2;

    @AutoGenerated
    private Panel datePanel;

    @AutoGenerated
    private VerticalLayout verticalLayout_5;

    @AutoGenerated
    private HorizontalLayout timeLayout;

    @AutoGenerated
    private CustomTimePicker timeEnd;

    @AutoGenerated
    private CustomTimePicker timeStart;

    @AutoGenerated
    private PopupDateField date;

    @AutoGenerated
    private PopupDateField plannedDate;

    @AutoGenerated
    private TextField project;

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */

    /**************** --> Allgemein <--- ********************/
    // Allgemein
    org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(this.getClass());
    
    // Datenbank
    private Map<Object, String> componentMap;
//    private Map<Object, String> dbMap;
    private Map<Object, String> validateMap;
    private Form_Bind fb;
    private String dataSetId = "";

    
    // Berrechtigung
	private Integer permRead;
	private Integer permUpdate;
	private Integer permCreate;
	private Integer permDelete;

    private MenuItem tmpMenu = null;
    private Button tmpButton = null;
    /******************************************************/
    /**************** --> Tabsheetvars <--- *****************/
    private TabSheet tab = null;
    /******************************************************/
    /**************** --> Windowvars <--- *******************/
    private Window win = null;
    /******************************************************/
    /******************* --> Custom <--- ********************/
    /******************************************************/
    
    
    /************ ----->Einstellungen<-- ********************/
//    private final String formIdLng = "6011";
    private final String formIdPerm = "601";
    private final String Windows_Height = "750px";
    private final String Windows_Width = "1000px";
    
    private final String dataIdCol = "ST_ID";
    private final String dataTableName = "cust_protokoll_servicetasking";

    private HashMap<Object, String> dbMap;

    private Item dataSetItem;

    private ProjectLimits limit;
    
    private boolean regionalManager = false;
    private Nurse nursePerm = UserData.get().getNurse();
    private Integer ticketId = null;

    private ModuleComponent moduleComponent;
    
    private I18nManager i18n;

    /******************************************************/

    public ServiceTaskingInsertEdit(MenuItem Arg_Menü, String Arg_Form_ID) {
        tmpMenu = Arg_Menü;
        dataSetId = Arg_Form_ID;
    }

    public ServiceTaskingInsertEdit(Button Arg_btn, String Arg_Form_ID) {
        tmpButton = Arg_btn;
        dataSetId = Arg_Form_ID;
    }

    /********* INIT-Window ************/
    public void init() {
        if (Windows_Height.equals("") == true || Windows_Width.equals("") == true) {
            System.out.println("Form Einstellung Fehlt: !!!");
            return;
        }

        Standard_Init();

        String fid = dataSetId;
        if (fid != "") {
            fid = " - #" + fid;
        }

        if (tmpMenu != null) {
        	
            String Recourcename = null;
            ThemeResource resource = null;
            if(tmpMenu.getIcon() != null){
            	Recourcename = tmpMenu.getIcon().toString();
            	Recourcename = Recourcename.substring(0, Recourcename.length() - 12) + "white-16.png";
            	resource = new ThemeResource(Recourcename);
            }

            Build_Window_Button bwb = new Build_Window_Button(tmpMenu.getText() + fid, mainLayout, Windows_Height, Windows_Width, resource);
            win = bwb.ReturnWindow();
        }
        if (tmpButton != null) {
            Build_Window_Button bwb = new Build_Window_Button(tmpButton.getCaption() + fid, mainLayout, Windows_Height, Windows_Width, tmpButton.getIcon());
            win = bwb.ReturnWindow();
        }

    }

    /********* INIT-Tray ************/
    public void init(TabSheet Arg_tab) {

        Standard_Init();
        tab = Arg_tab;
        if (tmpMenu != null) {
            new Build_Tab_Menue_Item(Arg_tab, tmpMenu.getText(), mainLayout, tmpMenu.getIcon());
        }
        if (tmpButton != null) {
            new Build_Tab_Menue_Item(Arg_tab, tmpButton.getCaption(), mainLayout, tmpButton.getIcon());
        }

    }
    
    public Window getWindow(){
    	return win;
    }
    
    public TabSheet getTabSheet(){
    	return tab;
    }
    
    /********* Init-Standard ************/
    private void Standard_Init() {
        buildMainLayout();
        i18n = new I18nManager(this);
        
        fb = new Form_Bind();
        
        registerComponents();
        
        fillFields();
        fillDbMap();

        setCustomValidators();
        fillValidateMap();
        
        if (nursePerm.isNurse() && !regionalManager) {
          nurse.setValue(UserData.get().getNurse().getNurseId());
          billingDistance.setEnabled(false);
          billingTime.setEnabled(false);

          billingRightLayout.setVisible(false);

        }
        regionalManagerOk.setEnabled(regionalManager);
        
        /***************/

        if (dataSetId != "") {
        	
            dbFillForm();
            configureModularComponents();

            filterServiceType();
            
            toggleOnStatusChange();
            if (nursePerm.isNurse()) {
                if ((int) status.getValue() >= 3 && !regionalManager) {
                    setPermissions(0, 1, 0, 0);
                }
            }
            
        } else {
            
        	//TASK "create init"
        	
        }
        
        fillNurses();
        
        setMenuPermissions();
        configureComponents();
        
        setEventListeners();
        fillLimit();
    }
    
    private void fillLimit() {
        limit = new ProjectLimits("SA", dataSetId, MyUtils.getValueFromItem(dataSetItem, "ST_ID_DELEGATION", Integer.class));
        limit.setNurseSelect(nurse);
        limit.setStatusSelect(status);
        limit.setOriginalDate(MyUtils.getValueFromItem(dataSetItem, "ST_ORIGINAL_DATE", Date.class));
        
        String type = MyUtils.getValueFromItem(dataSetItem, "STXT_KEY", String.class);
        if("servicetype_pharmacy".equals(type)) {
            limit.setOriginalDateTooltip(date);
        }else {
            limit.limitDatePicker(date);
        }
    }
    
 // register components for lng and validation tools
    private void registerComponents(){
    	componentMap = new HashMap<Object, String>();
    	new ComponentIterator(main).createMap(componentMap);
    }
    
    
    private void configureComponents(){
    	
    	for (Entry<Object, String> entry : componentMap.entrySet()) {
    	    
    	    AbstractComponent field = (AbstractComponent) entry.getKey();
    		
			field.setImmediate(true);
			
			
			if(field instanceof ComboBox){
				((ComboBox)field).setFilteringMode(FilteringMode.CONTAINS);
			}
			
		}
    	
    	date.setRequired(true);
    	
    	status.setNullSelectionAllowed(false);
    	
    	patientInitials.setEnabled(false);
    	patientInitials.setStyleName("nogrey");
    	
        patient.setEnabled(false);
        patient.setStyleName("nogrey");
        
        project.setEnabled(false);
        project.setStyleName("nogrey");
    	
        nurse.setNullSelectionAllowed(true);
        
        captionField.setNullRepresentation("");
        captionField.setMaxLength(2000);
        captionField.setEnabled(!MyUtils.getUserData().getNurse().isNurse());
        captionField.setStyleName(captionField.isEnabled() ? "" : "nogrey");
        
    	componentListeners();
    	
    	// migrated from database
    	patientInfo.setIcon(Icons.White.info_16);
    	calcTime.setIcon(Icons.White.berechnen_16);
    	nurseInfo.setIcon(Icons.White.info_16);

    	patientInfo.setStyleName("button-image-only");
    	calcTime.setStyleName("button-image-only");
    	nurseInfo.setStyleName("button-image-only");

    	// migration end
    	
    	
        plannedDate.setReadOnly(true);
        plannedDate.setVisible(false);
        UserAttributes ua = new UserAttributes(UserData.get().getUserId());
        if(ua.getUserAttributeMap() != null && ua.getUserAttributeMap().containsKey("pop_change_planned_date")) {
            plannedDate.setReadOnly(false);
            plannedDate.setVisible(true);
            verticalLayout_5.setHeight(null);
            
            plannedDate.addValueChangeListener(new ValueChangeListener() {
                @Override
                public void valueChange(ValueChangeEvent event) {
                    
                    limit.setOriginalDate(plannedDate.getValue());
                    limit.limitDatePicker(date);
                    
                    date.setValue(plannedDate.getValue());
                }
            });
            
        }

    	
    	// hide admin
        adminEnabled.setVisible(false);
        
        setResetEnabled(false);
    	
    }
    
    private void componentListeners(){
        
        patientInfo.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {
                // TODO Automatisch generierter Methodenstub
                if (patient.getValue() == null) {
                    I18nManager.global(I18nGlobalNotifiers.no_entry_selected);

                    return;
                }

                form_patient_insert_edit pie = new form_patient_insert_edit(event.getButton(), Integer.toString(MyUtils.getValueFromItem(dataSetItem, "PSL_ID", Integer.class)));
                pie.Init_Class_Window();
                pie.Set_Berrechtigung_Custom(1, 1, 1, 1);

            }
        });

        nurseInfo.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {
                // TODO Automatisch generierter Methodenstub
                if (nurse.getValue() == null) {
                    I18nManager.global(I18nGlobalNotifiers.no_entry_selected);

                    return;
                }

                form_nurse_insert_edit pie = new form_nurse_insert_edit(event.getButton(), "" + nurse.getValue());
                pie.Init_Class_Window();
                pie.Set_Berrechtigung_Custom(1, 0, 0, 0);
            }
        });
    	
        nurse.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                if(status.getValue().equals(2)) {
                    status.setValue(1);
                }
                
            }
        });
        
        calcTime.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {

                form_Berrechnen_Strecke fbs = new form_Berrechnen_Strecke(event.getButton());

                if (MyUtils.getUserData().getNurse().isNurse()) {
                    fbs.fieldDistance = nurseDistance;
                    fbs.fieldDuration = nurseTime;
                } else {
                    fbs.fieldDistance = billingDistance;
                    fbs.fieldDuration = billingTime;
                }

                if (nurse.getValue() != null) {
                    fbs.Init_Class_Window((Integer) nurse.getValue());
                } else {
                    fbs.Init_Class_Window();
                }

                if (patient.getValue() != null) {
                    fbs.Set_nach(MyUtils.getValueFromItem(dataSetItem, "PSL_ID", Integer.class));
                }

            }
        });
        
        status.addValueChangeListener(new Property.ValueChangeListener() {
            @Override
            public void valueChange(ValueChangeEvent event) {
               toggleOnStatusChange();
            }
        });
        
        ticketCreate.addClickListener(new ClickListener() {
            
            @Override
            public void buttonClick(ClickEvent event) {
                
                CreateParams params = new CreateParams();
                params.button = ticketCreate;
                
                Timestamp ts = MyUtils.getValueFromItem(dataSetItem, "ST_DATE", java.sql.Timestamp.class);
                
                if(ts != null) {
                    params.shippingDate = new Date(ts.getTime());
                    params.date = new Date(ts.getTime());
                }
                params.patientId = MyUtils.getValueFromItem(dataSetItem, "ST_ID_PATIENT", Integer.class);
                params.country = MyUtils.getValueFromItem(dataSetItem, "PSL_COUNTYCODE", String.class);
                
                TicketDbActions dba = new TicketDbActions(); 
                final OpenTicketsInsertEdit tie = dba.createAndOpenWin(params);
                toggleTicketButtons(tie.getTicketId());
                
                tie.getWindow().addCloseListener(new CloseListener() {
                    
                    @Override
                    public void windowClose(CloseEvent e) {
                        
                        if(tie.wasDeleted()) {
                            toggleTicketButtons(null);
                        }
                        
                    }
                });

                
            }
        });
        
        ticketEdit.addClickListener(new ClickListener() {
            
            @Override
            public void buttonClick(ClickEvent event) {
                
                if(ticketId == null) {
                    return;
                }
                ticketEdit.setEnabled(false);
                final OpenTicketsInsertEdit pie = new OpenTicketsInsertEdit(ticketEdit, ticketId.toString());
                pie.setPermissionsFromDatabase();
                pie.init();
                pie.getWindow().addCloseListener(new CloseListener() {
                    
                    @Override
                    public void windowClose(CloseEvent e) {
                        ticketEdit.setEnabled(true);
                        if(pie.wasDeleted()) {
                            toggleTicketButtons(null);
                        }
                    }
                });
                
            }
        });
        
        reset.addClickListener(new ClickListener() {
            
            @Override
            public void buttonClick(ClickEvent event) {
                
                dbReset();
                UI.getCurrent().getUI().removeWindow(win);
                
            }
        });
    }
    
    private void filterServiceType() {
        
        final ArrayList<Integer> types = new ArrayList<Integer>(); 
        
        CustomQuery q = new DBClass().CustomQuery;
        String sql = "select ID_TYPE from cust_protokoll_servicetasking_project_types where ID_PROJECT = "
        + MyUtils.getValueFromItem(dataSetItem, "VH_PROJEKT_ID", Integer.class) ;
        q.setSqlString(sql);
//        q.db.debugNextQuery(true);
        
        Container con = q.query();
        for (Object iid : con.getItemIds()) {
            types.add(MyUtils.getValueFromItem(con.getItem(iid), "ID_TYPE", Integer.class));
        }
        
        IndexedContainer src = (IndexedContainer) type.getContainerDataSource();
        src.addContainerFilter(new Filter() {
            
            @Override
            public boolean passesFilter(Object itemId, Item item) throws UnsupportedOperationException {
                return types.contains(itemId);
            }
            
            @Override
            public boolean appliesToProperty(Object propertyId) {
                return false;
            }
        });
    }
    
    private void configureModularComponents() {
        
        Integer id = MyUtils.getValueFromItem(dataSetItem, "VH_PROJEKT_ID", Integer.class);
        
        moduleComponent = SubmoduleManager.getInstance().getModule(id);
        if(moduleComponent == null) {
            log.warn("no module found for project {}", id);
            return;
        }
        
        moduleComponent.setPatientId(MyUtils.getValueFromItem(dataSetItem, "PSL_ID", Integer.class));
        moduleComponent.setReadOnly(btn_save.isEnabled());
        setModularListeners(moduleComponent);
        moduleComponent.load(Integer.parseInt(dataSetId));
        dynamicData.setContent(moduleComponent);
    }
    
    private void setModularListeners(ModuleComponent mod) {
        mod.registerParentValue(ParentValue.NURSE, nurse);
        mod.registerParentValue(ParentValue.DATE, date);
    }
    
    private void toggleTicketButtons(Integer ticketId) {
        
        this.ticketId = ticketId;
        dbUpdateTicket();
        
        Boolean hasTicket = ticketId != null;
        ticketCreate.setVisible(!hasTicket);
        ticketEdit.setVisible(hasTicket);
    }
    
    private void toggleOnStatusChange() {
        boolean required = false;
        if (status.getValue() != null && (int) status.getValue() > 2) {
            required = true;
        }

        nurseDistance.setRequired(required);
        nurseTime.setRequired(required);

        timeStart.setRequired(required);
        timeEnd.setRequired(required);
        
        type.setRequired(required);
    }
    
    /*************************** Events *******************************/

    private void setEventListeners() {

        btn_save.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {

                if (!validate()) {
                    I18nManager.global(I18nGlobalNotifiers.fields_empty);
                    return;
                }
                if(moduleComponent != null && !moduleComponent.validate()){
                    return;
                }
                
                if (dataSetId.equals("") == true) {
                	
                    dataSetId = Integer.toString(dbInsert());
                    
                } else {
                	
                    dbUpdate();

                }
                if(moduleComponent != null) {
                    moduleComponent.save(Integer.parseInt(dataSetId));
                }
                

                //TASK check if save successful
                UI.getCurrent().getUI().removeWindow(win);
            }

        });

       
    }

    /******************************************************************/
    
    /************************ --> Berrechtigung <-- **************************/

    @SuppressWarnings("unused")
    public void setPermissionsFromDatabase() {
        if (formIdPerm == "") {
            System.out.println("Form Einstellung Fehlt: Berechtigung");
            return;
        }

        
        Rechteholen r = new Rechteholen(UserData.get().getUserId() + "");
        String[][] perms = r.Datenholen();
        
        System.out.println(perms);
        
        for (int i = 0; i < perms.length; i++) {
            if (perms[i][0].equals(formIdPerm) == true) {

                permRead = Integer.valueOf(perms[i][3]);
                permUpdate = Integer.valueOf(perms[i][4]);
                permCreate = Integer.valueOf(perms[i][6]);
                permDelete = Integer.valueOf(perms[i][5]);
                
            }
        }
    }

    public void setPermissions(int create, int read, int update, int delete) {

        permCreate = create;
        permRead = read;
        permUpdate = update;
        permDelete = delete;

    }

    private void setMenuPermissions() {
        Boolean c = (permCreate == 1);
        Boolean r = (permRead == 1);
        Boolean u = (permUpdate == 1);
        Boolean d = (permDelete == 1);
        
        boolean nurse = UserData.get().getNurse().isNurse();
        boolean limited = nurse
            && "servicetype_pharmacy".equals(MyUtils.getValueFromItem(dataSetItem, "STXT_KEY", String.class));
        
        btn_save.setEnabled(!limited ? (c||u) : false);
        ticketCreate.setEnabled(!nurse && c);
        ticketEdit.setEnabled(!nurse && u);

    }
    
    public void setRegionalManagerEnabled(Boolean enabled){
        regionalManager = enabled;
    }
    
    public void setResetEnabled(boolean enabled) {
        reset.setEnabled(enabled);
        reset.setVisible(enabled);
    }
    
    /***********************************************/
    
    private void fillFields(){
        new I18nConverter("cust_protokoll_servicetasking_master_types", "STXT_ID", "STXT_KEY").attachDatasource(type);
        new I18nSTStatusConverter().attachDatasource(status);
    }
    
    private void fillNurses() {
        Boolean readonly = nurse.isReadOnly();
        nurse.setReadOnly(false);

        Integer nv = MyUtils.getValueFromItem(dataSetItem, "ST_ID_NURSE", Integer.class);
        nurse.removeAllItems();
        
        ProjectNurseCombos pnc = new ProjectNurseCombos(MyUtils.getValueFromItem(dataSetItem, "VH_PROJEKT_ID", Integer.class));
        pnc.setPatientId(MyUtils.getValueFromItem(dataSetItem, "PSL_ID", Integer.class));
        
        try {
            
            new combo(pnc.getNurseComboSubs(), nurse, "KSK_ID", "Krankenschwesternname");
            new combo(pnc.getNurseComboMain(), nurse, "KSK_ID", "Krankenschwesternname");
            //new combo(rnc.getNurseComboSingle(Integer.parseInt(nv.toString())), cb_nurse, "KSK_ID", "Krankenschwesternname");

            if (nv != null) {
                
                //fix for deleted nurses
                if(!nurse.containsId(nv)){
                    new combo(pnc.getNurseComboSingle(Integer.parseInt(nv.toString())), nurse, "KSK_ID", "Krankenschwesternname");
                    nurse.setEnabled(false);
                    nurse.setStyleName("nogrey");
                }
                
                nurse.select(nv);
            }

        } catch (Exception e) {
            e.printStackTrace();
            nurse.removeAllItems();
            return;
        }

        nurse.setReadOnly(readonly);
    }
    /******************** Database *****************/
    private void fillDbMap() {
        
        String table = dataTableName + ":";
        
        dbMap = new HashMap<>();
        dbMap.put(date, table + "ST_DATE");
        dbMap.put(plannedDate, table + "ST_ORIGINAL_DATE");
        dbMap.put(nurse, table + "ST_ID_NURSE");
        
//        dbMap.put(patient, table + "ST_ID_PATIENT");
        //TASK: project
        
        dbMap.put(timeStart, table + "ST_VON");
        dbMap.put(timeEnd, table + "ST_BIS");
        
        dbMap.put(billingDistance, table + "ST_KM");
        dbMap.put(nurseDistance, table + "ST_KM_NURSE");
        dbMap.put(adminEnabled, table + "ST_ADMINPAUSCHALE");
        dbMap.put(billingTime, table + "ST_FAHRTZEIT");
        dbMap.put(nurseTime, table + "ST_FAHRTZEIT_NURSE");
        dbMap.put(status, table + "ST_STATUS");
        dbMap.put(type, table + "ST_ID_TYPE");
        
        regionalManagerOk.addToDBMap(dbMap, FieldType.CHECK, table + "ST_REGIONAL_MANAGER_OK");
        regionalManagerOk.addToDBMap(dbMap, FieldType.DATE, table + "ST_REGIONAL_MANAGER_DATE");
        regionalManagerOk.addToDBMap(dbMap, FieldType.USER, table + "ST_REGIONAL_MANAGER_USER");

        
//        dbMap.put(comment, table + "ST_COMMENT");
        dbMap.put(captionField, table + "ST_CAPTION");
        

    }

    private void dbFillForm() {
       
        CustomQuery q = new DBClass().CustomQuery;
        String sql = "select"
         + "\n " + "    cust_protokoll_servicetasking.*"
         + "\n " + "    , PSL_ID"
         + "\n " + "    , CONCAT(PSL_NAME, ', ', PSL_VORNAME, ', ', PSA_NAME) as patient"
         + "\n " + "    , STMS_PAT_INITIALS as initials"
         + "\n " + "    , VH_PROJEKT_ID"
         + "\n " + "    , PSLV_NAME as project"
         + "\n " + "    , PSL_COUNTYCODE" // ticketCreator
         + "\n " + "    , OMT_ID" // ticketEdit
         + "\n " + "    , STXT_KEY"
         + "\n " + "from cust_protokoll_servicetasking"
         + "\n " + "left join cust_verk_haupt on ST_VH_ID = VH_ID"
         + "\n " + "left join cust_protokoll_servicetasking_meta_static on ST_VH_ID = STMS_VH_ID"
         + "\n " + ""
         + "\n " + "left join cust_projekte_stammdaten_liste on VH_PROJEKT_ID = PSLV_ID"
         + "\n " + "left join cust_patient_stammdaten_liste on ST_ID_PATIENT = PSL_ID"
         + "\n " + "left join cust_patient_stammdaten_anrede on PSL_ANREDE = PSA_ID"
         + "\n " + "left join cust_ordermanager_tickets on ST_ID_TICKET = OMT_ID"
         + "\n " + "left join cust_protokoll_servicetasking_master_types on ST_ID_TYPE = STXT_ID"
         + "\n " + "where ST_ID = " + dataSetId;
             
//        q.db.debugNextQuery(true);
        q.setSqlString(sql);
        
        Container con = q.query();
        
        if(con.size() > 0) {
            
            fb = new Form_Bind();
            fb.Get_and_Fill(con, dbMap);
            
            dataSetItem = MyUtils.getFirstItemFromContainer(con);
            
            if(MyUtils.getValueFromItem(dataSetItem, "PSL_ID", Integer.class) != null) {
                patientInitials.setValue(MyUtils.getValueFromItem(dataSetItem, "initials", String.class));
                patient.setValue(MyUtils.getValueFromItem(dataSetItem, "patient", String.class));
            }else {
                patientLayout.setEnabled(false);
                patientLayout.setVisible(false);
            }
            
            project.setValue(MyUtils.getValueFromItem(dataSetItem, "project", String.class));
            
            toggleTicketButtons(MyUtils.getValueFromItem(dataSetItem, "OMT_ID", Integer.class));

            regionalManagerOk.init();
        }
        
    }

    private int dbInsert() {
        DBClass db = new DBClass();
        
        fb = new Form_Bind();
        fb.Insert(db, dbMap);
        
        db.DB_Data_Insert.DB_Tabellen.DB_set_Tabelle_Einzeln(dataTableName);
        db.DB_Data_Insert.DB_Daten.DB_Data(dataTableName, "ST_ID_TICKET", ticketId != null ? ticketId.toString() : null);
        
        // dba.DB_Data_Insert.DB_DEBUG_SQL_STRING();
        return db.DB_Data_Insert.DB_Insert();
    }

    private void dbUpdate() {
        DBClass db = new DBClass();
        fb = new Form_Bind();
        fb.Update(db, dbMap);
        
        db.DB_Data_Update.DB_Tabellen.DB_set_Tabelle_Einzeln(dataTableName);
        db.DB_Data_Update.DB_Filter.DB_WHERE_Allgemein(dataTableName, dataIdCol, "=", dataSetId, "");
        db.DB_Data_Update.DB_Daten.DB_Data(dataTableName, "ST_ID_TICKET", ticketId != null ? ticketId.toString() : null);
        
        db.DB_Data_Update.DB_Update();

    }
    
    private void dbUpdateTicket() {
        DBClass db = new DBClass();
       
        db.DB_Data_Update.DB_Tabellen.DB_set_Tabelle_Einzeln(dataTableName);
        db.DB_Data_Update.DB_Filter.DB_WHERE_Allgemein(dataTableName, dataIdCol, "=", dataSetId, "");
        db.DB_Data_Update.DB_Daten.DB_Data(dataTableName, "ST_ID_TICKET", ticketId != null ? ticketId.toString() : null);
        
        db.DB_Data_Update.DB_Update();
    }
    
    private void dbReset() {
        
        if(dataSetId == "") {
            return;
        }
        
        CustomQuery q = new DBClass().CustomQuery;
        String sql = "delete from " + dataTableName + " where ST_ID = " + dataSetId;
        q.setSqlString(sql);
        
        q.update();
    }
    
    /*********************** -->Validierung<-- ********************/
    private void fillValidateMap() {
        validateMap = new HashMap<>();
        validateMap.putAll(componentMap);
        
//        ValidateMap.put(component, "component"); // should not be needed

    }

    private void setCustomValidators() {

        // psw_pass_1.addValidator(new Custom_Benutzerform_psw_ändern(psw_pass_1, psw_pass_2));

        /******* manual actions *******/

    }

    private boolean validate() {
        val_checker4 val = new val_checker4(validateMap);
        if (val.Is_Valid() == false) {
            return false;
        } else {
            return true;
        }

    }

    @AutoGenerated
    private VerticalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setStyleName("cust_margin_half_full_none_full");
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // main
        main = buildMain();
        mainLayout.addComponent(main);
        mainLayout.setExpandRatio(main, 9.0f);
        mainLayout.setComponentAlignment(main, new Alignment(48));
        
        // buttons
        buttons = buildButtons();
        mainLayout.addComponent(buttons);
        mainLayout.setComponentAlignment(buttons, new Alignment(48));
        
        return mainLayout;
    }

    @AutoGenerated
    private VerticalLayout buildMain() {
        // common part: create layout
        main = new VerticalLayout();
        main.setImmediate(false);
        main.setWidth("100.0%");
        main.setHeight("100.0%");
        main.setMargin(false);
        main.setSpacing(true);
        
        // panel_1
        panel_1 = buildPanel_1();
        main.addComponent(panel_1);
        main.setComponentAlignment(panel_1, new Alignment(48));
        
        return main;
    }

    @AutoGenerated
    private Panel buildPanel_1() {
        // common part: create layout
        panel_1 = new Panel();
        panel_1.setImmediate(false);
        panel_1.setWidth("100.0%");
        panel_1.setHeight("100.0%");
        
        // verticalLayout_4
        verticalLayout_4 = buildVerticalLayout_4();
        panel_1.setContent(verticalLayout_4);
        
        return panel_1;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_4() {
        // common part: create layout
        verticalLayout_4 = new VerticalLayout();
        verticalLayout_4.setImmediate(false);
        verticalLayout_4.setWidth("100.0%");
        verticalLayout_4.setHeight("100.0%");
        verticalLayout_4.setMargin(true);
        verticalLayout_4.setSpacing(true);
        
        // staticDataLayout
        staticDataLayout = buildStaticDataLayout();
        verticalLayout_4.addComponent(staticDataLayout);
        
        // dynamicData
        dynamicData = buildDynamicData();
        verticalLayout_4.addComponent(dynamicData);
        verticalLayout_4.setExpandRatio(dynamicData, 1.0f);
        
        return verticalLayout_4;
    }

    @AutoGenerated
    private HorizontalLayout buildStaticDataLayout() {
        // common part: create layout
        staticDataLayout = new HorizontalLayout();
        staticDataLayout.setImmediate(false);
        staticDataLayout.setWidth("100.0%");
        staticDataLayout.setHeight("-1px");
        staticDataLayout.setMargin(false);
        staticDataLayout.setSpacing(true);
        
        // verticalLayout_2
        verticalLayout_2 = buildVerticalLayout_2();
        staticDataLayout.addComponent(verticalLayout_2);
        
        // staticDataTabs
        staticDataTabs = buildStaticDataTabs();
        staticDataLayout.addComponent(staticDataTabs);
        staticDataLayout.setExpandRatio(staticDataTabs, 1.0f);
        
        return staticDataLayout;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_2() {
        // common part: create layout
        verticalLayout_2 = new VerticalLayout();
        verticalLayout_2.setImmediate(false);
        verticalLayout_2.setWidth("-1px");
        verticalLayout_2.setHeight("100.0%");
        verticalLayout_2.setMargin(false);
        verticalLayout_2.setSpacing(true);
        
        // project
        project = new TextField();
        project.setImmediate(false);
        project.setWidth("100.0%");
        project.setHeight("-1px");
        verticalLayout_2.addComponent(project);
        
        // datePanel
        datePanel = buildDatePanel();
        verticalLayout_2.addComponent(datePanel);
        verticalLayout_2.setExpandRatio(datePanel, 1.0f);
        
        return verticalLayout_2;
    }

    @AutoGenerated
    private Panel buildDatePanel() {
        // common part: create layout
        datePanel = new Panel();
        datePanel.setCaption("Datierung");
        datePanel.setImmediate(false);
        datePanel.setWidth("180px");
        datePanel.setHeight("100.0%");
        
        // verticalLayout_5
        verticalLayout_5 = buildVerticalLayout_5();
        datePanel.setContent(verticalLayout_5);
        
        return datePanel;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_5() {
        // common part: create layout
        verticalLayout_5 = new VerticalLayout();
        verticalLayout_5.setImmediate(false);
        verticalLayout_5.setWidth("100.0%");
        verticalLayout_5.setHeight("100.0%");
        verticalLayout_5.setMargin(false);
        verticalLayout_5.setSpacing(true);
        
        // planned
        plannedDate = new PopupDateField();
        plannedDate.setCaption("Plandatum");
        plannedDate.setImmediate(false);
        plannedDate.setVisible(false);
        plannedDate.setWidth("80.0%");
        plannedDate.setHeight("-1px");
        verticalLayout_5.addComponent(plannedDate);
        verticalLayout_5.setComponentAlignment(plannedDate, new Alignment(48));
        
        // date
        date = new PopupDateField();
        date.setCaption("Datum");
        date.setImmediate(false);
        date.setWidth("80.0%");
        date.setHeight("-1px");
        verticalLayout_5.addComponent(date);
        verticalLayout_5.setComponentAlignment(date, new Alignment(48));
        
        // timeLayout
        timeLayout = buildTimeLayout();
        verticalLayout_5.addComponent(timeLayout);
        verticalLayout_5.setComponentAlignment(timeLayout, new Alignment(48));
        
        return verticalLayout_5;
    }

    @AutoGenerated
    private HorizontalLayout buildTimeLayout() {
        // common part: create layout
        timeLayout = new HorizontalLayout();
        timeLayout.setImmediate(false);
        timeLayout.setWidth("80.0%");
        timeLayout.setHeight("-1px");
        timeLayout.setMargin(false);
        timeLayout.setSpacing(true);
        
        // timeStart
        timeStart = new CustomTimePicker();
        timeStart.setCaption("Von");
        timeStart.setImmediate(false);
        timeStart.setWidth("60px");
        timeStart.setHeight("-1px");
        timeLayout.addComponent(timeStart);
        
        // timeEnd
        timeEnd = new CustomTimePicker();
        timeEnd.setCaption("Bis");
        timeEnd.setImmediate(false);
        timeEnd.setWidth("60px");
        timeEnd.setHeight("-1px");
        timeLayout.addComponent(timeEnd);
        
        return timeLayout;
    }

    @AutoGenerated
    private TabSheet buildStaticDataTabs() {
        // common part: create layout
        staticDataTabs = new TabSheet();
        staticDataTabs.setImmediate(true);
        staticDataTabs.setWidth("100.0%");
        staticDataTabs.setHeight("170px");
        
        // statusLayout
        statusLayout = buildStatusLayout();
        staticDataTabs.addTab(statusLayout, "Stammdaten", null);
        
        // billingLayout
        billingLayout = buildBillingLayout();
        staticDataTabs.addTab(billingLayout, "Abrechnungsdaten", null);
        
        // captionLayout
        captionLayout = buildCaptionLayout();
        staticDataTabs.addTab(captionLayout, "Betreff", null);
        
        return staticDataTabs;
    }

    @AutoGenerated
    private HorizontalLayout buildStatusLayout() {
        // common part: create layout
        statusLayout = new HorizontalLayout();
        statusLayout.setImmediate(false);
        statusLayout.setWidth("100.0%");
        statusLayout.setHeight("100.0%");
        statusLayout.setMargin(false);
        
        // statusLeftLayout
        statusLeftLayout = buildStatusLeftLayout();
        statusLayout.addComponent(statusLeftLayout);
        statusLayout.setExpandRatio(statusLeftLayout, 1.0f);
        
        // statusRightLayout
        statusRightLayout = buildStatusRightLayout();
        statusLayout.addComponent(statusRightLayout);
        
        return statusLayout;
    }

    @AutoGenerated
    private VerticalLayout buildStatusLeftLayout() {
        // common part: create layout
        statusLeftLayout = new VerticalLayout();
        statusLeftLayout.setImmediate(false);
        statusLeftLayout.setWidth("100.0%");
        statusLeftLayout.setHeight("-1px");
        statusLeftLayout.setMargin(true);
        statusLeftLayout.setSpacing(true);
        
        // patientLayout
        patientLayout = buildPatientLayout();
        statusLeftLayout.addComponent(patientLayout);
        
        // nurseLayout
        nurseLayout = buildNurseLayout();
        statusLeftLayout.addComponent(nurseLayout);
        
        return statusLeftLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildPatientLayout() {
        // common part: create layout
        patientLayout = new HorizontalLayout();
        patientLayout.setImmediate(false);
        patientLayout.setWidth("100.0%");
        patientLayout.setHeight("-1px");
        patientLayout.setMargin(false);
        patientLayout.setSpacing(true);
        
        // patientInfo
        patientInfo = new Button();
        patientInfo.setCaption("");
        patientInfo.setImmediate(true);
        patientInfo.setWidth("-1px");
        patientInfo.setHeight("-1px");
        patientLayout.addComponent(patientInfo);
        patientLayout.setComponentAlignment(patientInfo, new Alignment(9));
        
        // patientInitials
        patientInitials = new TextField();
        patientInitials.setCaption("Kürzel");
        patientInitials.setImmediate(false);
        patientInitials.setWidth("100px");
        patientInitials.setHeight("-1px");
        patientLayout.addComponent(patientInitials);
        
        // patient
        patient = new TextField();
        patient.setCaption("Patient");
        patient.setImmediate(false);
        patient.setWidth("100.0%");
        patient.setHeight("-1px");
        patientLayout.addComponent(patient);
        patientLayout.setExpandRatio(patient, 1.0f);
        
        return patientLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildNurseLayout() {
        // common part: create layout
        nurseLayout = new HorizontalLayout();
        nurseLayout.setImmediate(false);
        nurseLayout.setWidth("100.0%");
        nurseLayout.setHeight("-1px");
        nurseLayout.setMargin(false);
        nurseLayout.setSpacing(true);
        
        // nurseInfo
        nurseInfo = new Button();
        nurseInfo.setCaption("");
        nurseInfo.setImmediate(true);
        nurseInfo.setWidth("-1px");
        nurseInfo.setHeight("-1px");
        nurseLayout.addComponent(nurseInfo);
        nurseLayout.setComponentAlignment(nurseInfo, new Alignment(9));
        
        // nurse
        nurse = new ComboBox();
        nurse.setCaption("Krankenschwester");
        nurse.setImmediate(false);
        nurse.setWidth("-1px");
        nurse.setHeight("-1px");
        nurseLayout.addComponent(nurse);
        
        // ticketLayout
        ticketLayout = buildTicketLayout();
        nurseLayout.addComponent(ticketLayout);
        nurseLayout.setComponentAlignment(ticketLayout, new Alignment(48));
        
        // regionalManagerOk
        regionalManagerOk = new RegionalLeadCheck();
        regionalManagerOk.setCaption("Regionalleiter Ok");
        regionalManagerOk.setImmediate(false);
        regionalManagerOk.setWidth("-1px");
        regionalManagerOk.setHeight("-1px");
        nurseLayout.addComponent(regionalManagerOk);
        nurseLayout.setExpandRatio(regionalManagerOk, 1.0f);
        nurseLayout.setComponentAlignment(regionalManagerOk, new Alignment(34));
        
        return nurseLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildTicketLayout() {
        // common part: create layout
        ticketLayout = new HorizontalLayout();
        ticketLayout.setImmediate(false);
        ticketLayout.setWidth("-1px");
        ticketLayout.setHeight("100.0%");
        ticketLayout.setMargin(false);
        ticketLayout.setSpacing(true);
        
        // ticketCreate
        ticketCreate = new Button();
        ticketCreate.setCaption("Paket erstellen");
        ticketCreate.setImmediate(true);
        ticketCreate.setWidth("-1px");
        ticketCreate.setHeight("-1px");
        ticketLayout.addComponent(ticketCreate);
        ticketLayout.setComponentAlignment(ticketCreate, new Alignment(24));
        
        // ticketEdit
        ticketEdit = new Button();
        ticketEdit.setCaption("Paket bearbeiten");
        ticketEdit.setImmediate(true);
        ticketEdit.setWidth("-1px");
        ticketEdit.setHeight("-1px");
        ticketLayout.addComponent(ticketEdit);
        ticketLayout.setComponentAlignment(ticketEdit, new Alignment(24));
        
        return ticketLayout;
    }

    @AutoGenerated
    private VerticalLayout buildStatusRightLayout() {
        // common part: create layout
        statusRightLayout = new VerticalLayout();
        statusRightLayout.setImmediate(false);
        statusRightLayout.setWidth("160px");
        statusRightLayout.setHeight("-1px");
        statusRightLayout.setMargin(true);
        statusRightLayout.setSpacing(true);
        
        // status
        status = new ComboBox();
        status.setCaption("Status");
        status.setImmediate(false);
        status.setWidth("100.0%");
        status.setHeight("-1px");
        statusRightLayout.addComponent(status);
        
        // type
        type = new ComboBox();
        type.setCaption("Servicetyp");
        type.setImmediate(false);
        type.setWidth("100.0%");
        type.setHeight("-1px");
        statusRightLayout.addComponent(type);
        
        return statusRightLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildBillingLayout() {
        // common part: create layout
        billingLayout = new HorizontalLayout();
        billingLayout.setImmediate(false);
        billingLayout.setWidth("100.0%");
        billingLayout.setHeight("100.0%");
        billingLayout.setMargin(false);
        
        // billingLeftLayout
        billingLeftLayout = buildBillingLeftLayout();
        billingLayout.addComponent(billingLeftLayout);
        
        // billingCenterLayout
        billingCenterLayout = buildBillingCenterLayout();
        billingLayout.addComponent(billingCenterLayout);
        
        // billingRightLayout
        billingRightLayout = buildBillingRightLayout();
        billingLayout.addComponent(billingRightLayout);
        billingLayout.setComponentAlignment(billingRightLayout, new Alignment(34));
        
        return billingLayout;
    }

    @AutoGenerated
    private VerticalLayout buildBillingLeftLayout() {
        // common part: create layout
        billingLeftLayout = new VerticalLayout();
        billingLeftLayout.setImmediate(false);
        billingLeftLayout.setWidth("100.0%");
        billingLeftLayout.setHeight("-1px");
        billingLeftLayout.setMargin(true);
        billingLeftLayout.setSpacing(true);
        
        // nurseTime
        nurseTime = new CustomTimePicker();
        nurseTime.setCaption("Nurse Fahrzeit");
        nurseTime.setImmediate(false);
        nurseTime.setWidth("-1px");
        nurseTime.setHeight("-1px");
        billingLeftLayout.addComponent(nurseTime);
        billingLeftLayout.setComponentAlignment(nurseTime, new Alignment(33));
        
        // nurseDistance
        nurseDistance = new IntStepper();
        nurseDistance.setCaption("Gesamte Km");
        nurseDistance.setImmediate(false);
        nurseDistance.setWidth("-1px");
        nurseDistance.setHeight("-1px");
        billingLeftLayout.addComponent(nurseDistance);
        billingLeftLayout.setComponentAlignment(nurseDistance, new Alignment(33));
        
        return billingLeftLayout;
    }

    @AutoGenerated
    private VerticalLayout buildBillingCenterLayout() {
        // common part: create layout
        billingCenterLayout = new VerticalLayout();
        billingCenterLayout.setImmediate(false);
        billingCenterLayout.setWidth("100.0%");
        billingCenterLayout.setHeight("100.0%");
        billingCenterLayout.setMargin(true);
        billingCenterLayout.setSpacing(true);
        
        // calcTime
        calcTime = new Button();
        calcTime.setCaption("");
        calcTime.setImmediate(true);
        calcTime.setWidth("-1px");
        calcTime.setHeight("-1px");
        billingCenterLayout.addComponent(calcTime);
        billingCenterLayout.setComponentAlignment(calcTime, new Alignment(48));
        
        // adminEnabled
        adminEnabled = new CheckBox();
        adminEnabled.setCaption("Adminpauschale");
        adminEnabled.setImmediate(false);
        adminEnabled.setWidth("-1px");
        adminEnabled.setHeight("-1px");
        billingCenterLayout.addComponent(adminEnabled);
        billingCenterLayout.setComponentAlignment(adminEnabled, new Alignment(48));
        
        return billingCenterLayout;
    }

    @AutoGenerated
    private VerticalLayout buildBillingRightLayout() {
        // common part: create layout
        billingRightLayout = new VerticalLayout();
        billingRightLayout.setImmediate(false);
        billingRightLayout.setWidth("100.0%");
        billingRightLayout.setHeight("-1px");
        billingRightLayout.setMargin(true);
        billingRightLayout.setSpacing(true);
        
        // billingTime
        billingTime = new CustomTimePicker();
        billingTime.setCaption("Abgerechnete Fahrzeit");
        billingTime.setImmediate(false);
        billingTime.setWidth("-1px");
        billingTime.setHeight("-1px");
        billingRightLayout.addComponent(billingTime);
        billingRightLayout.setComponentAlignment(billingTime, new Alignment(34));
        
        // billingDistance
        billingDistance = new IntStepper();
        billingDistance.setCaption("Abgerechnete Km");
        billingDistance.setImmediate(false);
        billingDistance.setWidth("-1px");
        billingDistance.setHeight("-1px");
        billingRightLayout.addComponent(billingDistance);
        billingRightLayout.setComponentAlignment(billingDistance, new Alignment(34));
        
        return billingRightLayout;
    }

    @AutoGenerated
    private VerticalLayout buildCaptionLayout() {
        // common part: create layout
        captionLayout = new VerticalLayout();
        captionLayout.setImmediate(false);
        captionLayout.setWidth("100.0%");
        captionLayout.setHeight("100.0%");
        captionLayout.setMargin(true);
        
        // captionField
        captionField = new TextField();
        captionField.setCaption("Betreff");
        captionField.setImmediate(false);
        captionField.setWidth("100.0%");
        captionField.setHeight("-1px");
        captionLayout.addComponent(captionField);
        
        return captionLayout;
    }

    @AutoGenerated
    private Panel buildDynamicData() {
        // common part: create layout
        dynamicData = new Panel();
        dynamicData.setImmediate(false);
        dynamicData.setWidth("100.0%");
        dynamicData.setHeight("100.0%");
        
        // verticalLayout_3
        verticalLayout_3 = new VerticalLayout();
        verticalLayout_3.setImmediate(false);
        verticalLayout_3.setWidth("100.0%");
        verticalLayout_3.setHeight("100.0%");
        verticalLayout_3.setMargin(false);
        dynamicData.setContent(verticalLayout_3);
        
        return dynamicData;
    }

    @AutoGenerated
    private HorizontalLayout buildButtons() {
        // common part: create layout
        buttons = new HorizontalLayout();
        buttons.setImmediate(false);
        buttons.setWidth("100.0%");
        buttons.setHeight("-1px");
        buttons.setMargin(true);
        
        // reset
        reset = new Button();
        reset.setCaption("Abbrechen");
        reset.setImmediate(true);
        reset.setWidth("-1px");
        reset.setHeight("-1px");
        buttons.addComponent(reset);
        buttons.setComponentAlignment(reset, new Alignment(48));
        
        // btn_save
        btn_save = new Button();
        btn_save.setCaption("Speichern");
        btn_save.setImmediate(true);
        btn_save.setWidth("-1px");
        btn_save.setHeight("-1px");
        buttons.addComponent(btn_save);
        buttons.setComponentAlignment(btn_save, new Alignment(48));
        
        return buttons;
    }

}
