package archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.expenses.form;

import java.math.BigDecimal;
import java.sql.Time;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Locale;
import java.util.Map;
import java.util.Map.Entry;

import org.joda.time.DateTimeZone;
import org.joda.time.Duration;
import org.joda.time.LocalDate;
import org.joda.time.LocalDateTime;
import org.joda.time.Period;
import org.joda.time.PeriodType;
import org.joda.time.format.PeriodFormatter;
import org.joda.time.format.PeriodFormatterBuilder;
import org.tepi.filtertable.FilterTable;

import com.google.common.base.Joiner;
import com.google.common.collect.Iterables;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.converter.Converter;
import com.vaadin.event.ItemClickEvent;
import com.vaadin.event.ItemClickEvent.ItemClickListener;
import com.vaadin.event.UIEvents.PollEvent;
import com.vaadin.event.UIEvents.PollListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.shared.ui.datefield.Resolution;
import com.vaadin.ui.AbstractComponent;
import com.vaadin.ui.AbstractField;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.CustomTable.Align;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.Command;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TwinColSelect;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.Window.CloseEvent;
import com.vaadin.ui.Window.CloseListener;

import archenoah.global.UserAttributes;
import archenoah.lib.custom.ComponentIterator;
import archenoah.lib.custom.MyUtils;
import archenoah.lib.custom.TableFilterGenerator;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.tool.comunication.dbclass.DBClass.CustomQuery;
import archenoah.lib.vaadin.Components.ClickMenuBar.ClickCommand;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Tab_Menue_Item;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Window_Button;
import archenoah.lib.vaadin.Components.table.FilteringTableUpdater;
import archenoah.lib.vaadin.CustomConverterFactorys.StringSqlTimestampConverter;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalMessages;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.lib.vaadin.MenuBerechtigung.Rechteholen;
import archenoah.lib.vaadin.resources.Icons;
import archenoah.web.normal.UserInfo.UserData;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.classes.PatientHistoryToggle;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.expenses.classes.I18nCEDStatusConverter;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.expenses.classes.SentStatusHandler;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.tools.ProjectParams;
import de.steinwedel.messagebox.ButtonId;
import de.steinwedel.messagebox.MessageBoxListener;


@SuppressWarnings({"serial", "rawtypes", "unchecked"})
public class ExpensesDataView extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private HorizontalLayout mainLayout;

    @AutoGenerated
    private VerticalLayout mainContainer;

    @AutoGenerated
    private FilterTable tbl_data;

    @AutoGenerated
    private HorizontalLayout globalFilterContainer;

    @AutoGenerated
    private HorizontalLayout filterStatusLayout;

    @AutoGenerated
    private TwinColSelect filterStatus;

    @AutoGenerated
    private CheckBox filterStatusEnabled;

    @AutoGenerated
    private HorizontalLayout filterProjectLayout;

    @AutoGenerated
    private TwinColSelect filterProject;

    @AutoGenerated
    private CheckBox filterProjectEnabled;

    @AutoGenerated
    private HorizontalLayout filterMonthLayout;

    @AutoGenerated
    private PopupDateField filterMonth;

    @AutoGenerated
    private CheckBox filterMonthEnabled;

    @AutoGenerated
    private VerticalLayout menuSpacer;

    @AutoGenerated
    private MenuBar men_frm;

    

    

    

    

	

	

	

	

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */

    /**************** --> Allgemein <--- ********************/
    private static org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(ExpensesDataView.class);
    
    // Datenbank
    private Map<Object, String> componentMap;
    private FilteringTableUpdater tableUpdater = null;

    // Berrechtigung
    private int ACC_ID;

    private int permRead;
    private int permCreate;
    private int permUpdate;
    private int permDelete;

    private MenuItem tmpMenu = null;

    private Button tmpButton = null;
    /******************************************************/
    /**************** --> Tabsheetvars <--- *****************/
    private TabSheet tab = null;

    /******************************************************/
    /**************** --> Windowvars <--- *******************/
    private Window win = null;
    /******************************************************/

    private DetachListener onDetach = null;

    /******************* -> Menüpunkte <- ********************/
    private MenuBar.MenuItem btn_create;
    private MenuBar.MenuItem btn_update;
    private MenuBar.MenuItem btn_read;
    private MenuBar.MenuItem btn_delete;
    private MenuBar.MenuItem btn_filter;
    
    private MenuBar.MenuItem btn_check;
    private MenuBar.MenuItem btn_checked;
    private MenuBar.MenuItem btn_unchecked;
    
    private PatientHistoryToggle patientHistory;
    private Integer patientId; 
    private boolean deferTableUpdates;
    
    /*******************************************************/
    /******************* --> Custom <--- ********************/
    /******************************************************/

    private Boolean firstFilter = true;
    private PollListener pollListener = null;
    
    enum Status {}
    SentStatusHandler sentHandler;
    
    private Boolean regionalManagerView = false;
    private Boolean projectManagerView = false;
    private ProjectParams projectParams = new ProjectParams();
    private String multiString = null;
    
    public Integer groupID = 0;
    
    /************ ----->Einstellungen<-- ********************/
//    private final String formIdLng = "601";
    private final String formIdPerm = "715";
    private final String winHeight = "600px";
    private final String winWidth = "900px";


    /******************************************************/

    private final String tableIdCol = "CED_ID";
    
    //TASK cols
    private final Object[] tableColsAll = new Object[] {"CED_ID", "USER", "KSK_COUNTRYCODE", "CED_DATE", "CEA_ACTIVITY", "CED_SERVICEZEIT", "CED_FAHRZEIT", "CED_KM", "CED_AMOUNT_CURRENCY", "CED_STATUS_BILLABLE", "CEC_ROLE", "PSLV_NAME", "CED_COMMENT", "NURSE_FIRM", "CED_STATUS"};
    //use custom Cols when needed
    private Object[] tableColsDefault = tableColsAll;
    //use custom Cols when needed
    private final Object[] tableColsFilter = tableColsDefault;
    private Object[] tableColsActive = tableColsDefault;
    
    private I18nManager i18n;

    private I18nCEDStatusConverter statusConverter;
    

    PeriodFormatter formatter = new PeriodFormatterBuilder().printZeroAlways().minimumPrintedDigits(2)
    										.appendHours().appendLiteral(":").appendMinutes().toFormatter();

    private boolean initialLoad = false;
    
    /******************************************************/

    public ExpensesDataView(MenuItem Arg_Menü) {
        tmpMenu = Arg_Menü;
    }

    public ExpensesDataView(Button Arg_btn) {
        tmpButton = Arg_btn;
    }

    /***************************** ---> Feste Funtionen<--- **************************************/

    /********* INIT-Window ************/
    public void init() {
        
        Standard_Init();

        if (tmpMenu != null) {
            String Recourcename = tmpMenu.getIcon().toString();
            Recourcename = Recourcename.substring(0, Recourcename.length() - 12) + "white-16.png";

            Build_Window_Button bwb = new Build_Window_Button(tmpMenu.getText(), mainLayout, winHeight, winWidth,
                    new ThemeResource(Recourcename));
            win = bwb.ReturnWindow();
        }
        if (tmpButton != null) {
            Build_Window_Button bwb = new Build_Window_Button(tmpButton.getCaption(), mainLayout, winHeight, winWidth,
                    tmpButton.getIcon());
            win = bwb.ReturnWindow();
        }

        win.addDetachListener(onDetach);

    }
    
    public Window getWindow(){
    	return win;
    }
    
    public TabSheet getTabSheet(){
    	return tab;
    }
    
    public void init(TabSheet Arg_tab) {

        Standard_Init();
        tab = Arg_tab;
        if (tmpMenu != null) {
            new Build_Tab_Menue_Item(Arg_tab, tmpMenu.getText(), mainLayout, tmpMenu.getIcon());
        }
        if (tmpButton != null) {
            new Build_Tab_Menue_Item(Arg_tab, tmpButton.getCaption(), mainLayout, tmpButton.getIcon());
        }

        tab.getSelectedTab().addDetachListener(onDetach);
    }

    /********* Init-Standard ************/
    private void Standard_Init() {
        buildMainLayout();
        i18n = new I18nManager(this);
        
        registerComponents();
        
        generateMenu();

        setMenuPermissions();

        updateTable();
        
        
//        tbl_data.setSortContainerPropertyId(tableIdCol);
//        tbl_data.setSortAscending(true);
//        tbl_data.sort();
        statusConverter = new I18nCEDStatusConverter();
        configureTable();
        configureComponents();

        setGlobalFilterMonth();
        
        initialLoad = false;
//        updateTable();
        
        setupListenersAndDetachEvent();
        
        i18n.refresh();
    }
    
    // register components for lng and validation tools
    private void registerComponents(){
    	componentMap = new HashMap<Object, String>();
    	new ComponentIterator(mainContainer).createMap(componentMap);
    }

    
    private void setupListenersAndDetachEvent() {
        pollListener = new PollListener() {

            @Override
            public void poll(PollEvent event) {
                if(tab.isRendered(mainLayout)  && filterMonthEnabled.getValue()){
                    updateTable();
                }
            }
        };

        UI.getCurrent().getUI().addPollListener(pollListener);

        onDetach = new DetachListener() {

            @Override
            public void detach(DetachEvent event) {
                UI.getCurrent().getUI().removePollListener(pollListener);
            }
        };
    }
    
    @SuppressWarnings("unused")
    public void setPermissionsFromDatabase() {
        if (formIdPerm == "") {
            System.out.println("Form Einstellung Fehlt: Berechtigung");
            return;
        }

        Rechteholen r = new Rechteholen(UserData.get().getUserId() + "");
        String[][] perms = r.Datenholen();

        for (int i = 0; i < perms.length; i++) {
            if (perms[i][0].equals(formIdPerm) == true) {

                permRead = Integer.valueOf(perms[i][3]);
                permUpdate = Integer.valueOf(perms[i][4]);
                permCreate = Integer.valueOf(perms[i][6]);
                permDelete = Integer.valueOf(perms[i][5]);
                
            }
        }
    }

    public void setPermissions(int create, int read, int update, int delete) {

        permCreate = create;
        permRead = read;
        permUpdate = update;
        permDelete = delete;

    }

    private void setMenuPermissions() {
        Boolean c = (permCreate == 1);
        Boolean r = (permRead == 1);
        Boolean u = (permUpdate == 1);
        Boolean d = (permDelete == 1);

        btn_create.setEnabled(c);
        btn_create.setVisible(c);

        btn_read.setEnabled(r);
        btn_read.setVisible(r);

        btn_update.setEnabled(u);
        btn_update.setVisible(u);

        btn_delete.setEnabled(d);
        btn_delete.setVisible(d);
        
    }

    /************ -><- ******************/

    /***************** Comands *********************/
    
    CloseListener closeListener = new CloseListener() {
		
		@Override
		public void windowClose(CloseEvent e) {
			updateTable(true);
		}
	};
    
	private String getSelectedValue(){
		
		return Integer.toString(getSelectedId());
	}
	
    private Integer getSelectedId(){
        Integer id = null;
        
        try {
        	id = (Integer) tbl_data.getContainerProperty(((Collection)tbl_data.getValue()).toArray()[0], tableIdCol).getValue();
        } catch (Exception e) {

        }
        return id;
    }
    
    private Item getSelectedItem() {
        Item item = null;
        try {
            item = tbl_data.getItem(((Collection)tbl_data.getValue()).toArray()[0]);
        } catch (Exception e) {
        }
        return item;
    }
    
    private Collection<Integer> getSelectedIds(){
        Collection<Integer> vals = (Collection<Integer>) tbl_data.getValue();
        
        ArrayList<Integer> ids = new ArrayList<Integer>();
        
        for (Integer row : vals) {
            ids.add((Integer) tbl_data.getContainerProperty(row, tableIdCol).getValue());
        }
        
        return ids;
    }
	
    //TASK Commands are here
    public Command cmd_btn_add = new ClickCommand() {

		@Override
		public void menuClicked(MenuItem selectedItem) {
			// TODO Auto-generated method stub
            ExpensesInsertEdit pie = new ExpensesInsertEdit(selectedItem, "");

            pie.setPermissions(permCreate, permRead, permUpdate, permDelete);
            
        	pie.setRegionalManagerEnabled(regionalManagerView);
        	pie.init();
        	pie.getWindow().addCloseListener(closeListener);
        	this.setWindow(pie.getWindow());
            this.setParent(men_frm);
			
			
		}

    };
    
    public Command cmd_btn_read = new ClickCommand() {
        @Override
        public void menuClicked(MenuItem selectedItem) {

            if(tbl_data.getValue() == null){
                I18nManager.global(I18nGlobalNotifiers.no_entry_selected);
                return;
            }
            
            ExpensesInsertEdit pie = new ExpensesInsertEdit(selectedItem, getSelectedValue());
        	
            pie.setPermissions(0, permRead, 0, 0);
            
            pie.init();
        	this.setWindow(pie.getWindow());
            this.setParent(men_frm);

        }
    };
    
    public Command cmd_btn_edit = new ClickCommand() {
        @Override
        public void menuClicked(MenuItem selectedItem) {
            
            if(tbl_data.getValue() == null){
                I18nManager.global(I18nGlobalNotifiers.no_entry_selected);
                return;
            }
            
            ExpensesInsertEdit pie = new ExpensesInsertEdit(selectedItem, getSelectedValue());
           
            pie.setPermissions(permCreate, permRead, permUpdate, permDelete);
            
        	pie.init();
        	pie.getWindow().addCloseListener(closeListener);
        	this.setWindow(pie.getWindow());
            this.setParent(men_frm);
        }
    };

    public Command cmd_btn_del = new Command() {
        @Override
        public void menuSelected(MenuItem selectedItem) {
            
            if(tbl_data.getValue() == null){
                I18nManager.global(I18nGlobalNotifiers.no_entry_selected);
                return;
            }
            
            deleteData(getSelectedIds());

        }
    };

    public Command cmd_btn_filter = new Command() {
        @Override
        public void menuSelected(MenuItem selectedItem) {

            if (firstFilter) {
                tbl_data.setFilterBarVisible(true);
                tbl_data.setFilterBarVisible(false);
                firstFilter = false;
            }
            tbl_data.setFilterBarVisible(!tbl_data.isFilterBarVisible());
            
            if(!tbl_data.isFilterBarVisible()){
                tbl_data.clearFilters();
            }
            
            tableColsActive = tbl_data.isFilterBarVisible() ? tableColsFilter : tableColsDefault;
            if(tableColsActive.length > 0){
            	tbl_data.setVisibleColumns(tableColsActive);
            }

        }
    };
    
    /******************************************/

    public void setGlobalFilterMonth(Date date){
        LocalDate ld = new LocalDate(date);
        filterMonthEnabled.setValue(true);
        filterMonth.setValue(new LocalDate(ld.getYear(), ld.getMonthOfYear(), 1).toDate());
    }
    
    public void setGlobalFilterMonth(){
        setGlobalFilterMonth(new Date());
    }
    
    /*************************** Gen Menues **********************************************************************************/
    /*************************************************************************************************************************/       
    private void generateMenu() {

        btn_create = men_frm.addItem("FRM_ADD", Icons.White.add_16, cmd_btn_add);
        btn_update = men_frm.addItem("FRM_EDIT", Icons.White.edit_16, cmd_btn_edit);
        btn_read = men_frm.addItem("FRM_READ", Icons.White.perm_lesen_16, cmd_btn_read);
        btn_delete = men_frm.addItem("FRM_DEL", Icons.White.delete_16, cmd_btn_del);
        
        btn_filter = men_frm.addItem("FRM_FILTER", Icons.White.filter_16, cmd_btn_filter);
        
        if (UserData.get().getExpenseChecking().isExpenseChecking() || UserData.get().hasGroup(1)) {
        	btn_check = men_frm.addItem("FRM_CHECK", Icons.White.select_16, null);
		}
        
        sentHandler = new SentStatusHandler(tbl_data, "CED_ID");   
        
        if (UserData.get().getExpenseChecking().isExpenseChecking() || UserData.get().hasGroup(1)) {
			
            btn_checked = btn_check.addItem("FRM_CHECK_APPROVED", Icons.Black.filter_add_16, new Command() {
            	
                @Override
                public void menuSelected(MenuItem selectedItem) {
                    sentHandler.checked();
                    updateTable(true);
                }
            });
      	
		}
  
    }

    /*************************** Config Components ***************************************************************************/
    /*************************************************************************************************************************/    
    
    private void configureComponents(){
       
    	for (Entry<Object, String> entry : componentMap.entrySet()) {
    		AbstractComponent field = (AbstractComponent) entry.getKey();
    		
			field.setImmediate(true);
			
			
			if(field instanceof ComboBox){
				((ComboBox)field).setFilteringMode(FilteringMode.CONTAINS);
			}
			
		}
        
    	
    	 filterMonthEnabled.setValue(false);
         filterMonthEnabled.setImmediate(true);
         filterMonth.setResolution(Resolution.MONTH);
         filterMonth.setDateFormat("MMM yyyy");
         filterMonth.setEnabled(false);
         
         filterMonthEnabled.addValueChangeListener(new ValueChangeListener() {
             
             @Override
             public void valueChange(ValueChangeEvent event) {
                 
                 Boolean enabled = (Boolean)event.getProperty().getValue();
                 filterMonth.setEnabled(enabled);
                 if(enabled && filterMonth.getValue() == null){
                     LocalDate ld = new LocalDate();
                     filterMonth.setValue(new LocalDate(ld.getYear(), ld.getMonthOfYear(), 1).toDate());
                 }else if(!enabled){
                     filterMonth.setValue(null);
                 }
                 
             }
         });
         
         filterMonth.setImmediate(true);
         filterMonth.addValueChangeListener(new ValueChangeListener() {
             
             @Override
             public void valueChange(ValueChangeEvent event) {
                 
                 updateTable(true);
                 
             }
         });
         
         // PROJECTPICKER
         filterProjectEnabled.setValue(false);
         filterProjectEnabled.setImmediate(true);
         filterProject.setContainerDataSource(dbGetProjectValues());
         filterProject.setItemCaptionPropertyId("PSLV_NAME");
         filterProject.setEnabled(false);
         
         filterProject.setValue(filterProject.getItemIds());
         
         filterProjectEnabled.addValueChangeListener(new ValueChangeListener() {
             
             @Override
             public void valueChange(ValueChangeEvent event) {
            	 
                 Boolean enabled = (Boolean)event.getProperty().getValue();
                 filterProject.setEnabled(enabled);
                 if(enabled){
                     filterProject.setValue(filterProject.getItemIds());
                 }
                 updateTable(true);
                 
             }
         });
         
         filterProject.setImmediate(true);
         filterProject.addValueChangeListener(new ValueChangeListener() {
             
             @Override
             public void valueChange(ValueChangeEvent event) {
                 
                 Collection val = (Collection) filterProject.getValue();
                 filterProjectEnabled.setValue(val.size() != 0);
                 updateTable(true);
                 
             }
         });
         
         // STATUSPICKER
         filterStatusEnabled.setValue(true);
         filterStatusEnabled.setImmediate(true);
         statusConverter.attachDatasource(filterStatus);
        
         preselectStatusFilter();
         
         filterStatusEnabled.addValueChangeListener(new ValueChangeListener() {
             
             @Override
             public void valueChange(ValueChangeEvent event) {
                 
                 Boolean enabled = (Boolean)event.getProperty().getValue();
                 filterStatus.setEnabled(enabled);
                 if(enabled){
                     preselectStatusFilter();
                 }
                 updateTable(true);
                 
             }
         });
         
         filterStatus.setImmediate(true);
         filterStatus.addValueChangeListener(new ValueChangeListener() {
             
             @Override
             public void valueChange(ValueChangeEvent event) {
                 
                 Collection val = (Collection) filterStatus.getValue();
                 filterStatusEnabled.setValue(val.size() != 0);
                 updateTable(true);
                 
             }
         });
         
         toggleMenuItems();
         
    }
    
	private boolean isBasicUser() {

		return (!UserData.get().getFinance().isFinance() && !UserData.get().getExpenseChecking().isExpenseChecking() && !UserData.get().getCS().isCS()
				&& !UserData.get().hasGroup(1));
	}
    
    private void deferTableUpdates(boolean defer) {
        this.deferTableUpdates = defer;
    }
    
    private void preselectStatusFilter(){
        // Preselect a few items
        HashSet<Integer> preselected = new HashSet<Integer>();
        Collections.addAll(preselected, 1, 2, 3, 4, 5, 6);
        filterStatus.setValue(preselected);
    }
    
    private ArrayList<AbstractField> getActiveGlobalFilters(){
        ArrayList<AbstractField> al = new ArrayList<AbstractField>();
        
        if(filterMonth.getValue() != null){
            al.add(filterMonth);
        }
        
        if(filterProjectEnabled.getValue() && ((Collection) filterProject.getValue()).size() > 0){
            al.add(filterProject);
        }
        
        if(filterStatusEnabled.getValue() && ((Collection) filterStatus.getValue()).size() > 0){
            al.add(filterStatus);
        }
        
        return al;
    }
    
    private Boolean hasGlobalFilters(ArrayList a){
        
        return (a.size() > 0);
        
    }
    
    private Boolean hasGlobalFilters(){
        
        return hasGlobalFilters(getActiveGlobalFilters());
        
    }
   
    private void deleteData(final Collection<Integer> ids){
        
        I18nManager.global(I18nGlobalMessages.confirm_delete, new MessageBoxListener() {
            
            @Override
            public void buttonClicked(ButtonId arg0) {
                if(ButtonId.YES == arg0) {
                    dbDeleteData(ids);
                }
            }
        });
    }
    
    private void dbDeleteData(Collection<Integer> ids){
        
      DBClass db = new DBClass();
      db.DB_Data_Delete.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_expenses_data");
      db.DB_Data_Delete.DB_Filter.DB_WHERE_In("cust_expenses_data", tableIdCol, Joiner.on(",").join(ids), "");
      db.DB_Data_Delete.DB_Delete();
  
      I18nManager.global(I18nGlobalNotifiers.entry_deleted);
      
      updateTable(true);
   
  }
    
    /*************************** Config TBL **********************************************************************************/
    /*************************************************************************************************************************/
    private void configureTable() {
        tbl_data.setSelectable(true);
        tbl_data.setFilterOnDemand(false);
        tbl_data.setMultiSelect(true);
        tbl_data.setImmediate(true);
        tbl_data.setColumnCollapsingAllowed(false);
        tbl_data.setFooterVisible(true);
        tbl_data.setPageLength(1);
        
        tbl_data.setColumnAlignment("CED_SERVICEZEIT", Align.CENTER);
        tbl_data.setColumnAlignment("CED_FAHRZEIT", Align.CENTER);
        tbl_data.setColumnAlignment("CED_KM", Align.CENTER);
        tbl_data.setColumnAlignment("CED_AMOUNT_CURRENCY", Align.RIGHT);
        tbl_data.setColumnAlignment("KSK_COUNTRYCODE", Align.CENTER);
        
        tbl_data.setColumnExpandRatio("CED_ID", 0.5f);
        tbl_data.setColumnExpandRatio("USER", 2);
        tbl_data.setColumnExpandRatio("KSK_COUNTRYCODE", 0.3f);
        tbl_data.setColumnExpandRatio("CED_DATE", 0.5f);
        tbl_data.setColumnExpandRatio("CEA_ACTIVITY", 2.3f);
        tbl_data.setColumnExpandRatio("CED_FAHRZEIT", 0.75f);
        tbl_data.setColumnExpandRatio("CED_SERVICEZEIT", 0.75f);
        tbl_data.setColumnExpandRatio("CED_KM", 0.75f);
        tbl_data.setColumnExpandRatio("CED_AMOUNT_CURRENCY", 0.6f);
        tbl_data.setColumnExpandRatio("CED_STATUS_BILLABLE", 1f);
        tbl_data.setColumnExpandRatio("CEC_ROLE", 1.3f);
        tbl_data.setColumnExpandRatio("PSLV_NAME", 1f);
        tbl_data.setColumnExpandRatio("CED_COMMENT", 3.5f);
        tbl_data.setColumnExpandRatio("NURSE_FIRM", 0.6f);
        tbl_data.setColumnExpandRatio("CED_STATUS", 1.4f);
        
        tbl_data.setFilterGenerator(new TableFilterGenerator(tbl_data));

        tableUpdater = new FilteringTableUpdater(tbl_data);
                
        if(tbl_data.size() > 0){
            
            StringSqlTimestampConverter date = new StringSqlTimestampConverter();
            date.setDateFormat(DateFormat.SHORT);
            

            StringSqlTimestampConverter time = new StringSqlTimestampConverter();
            time.setDateFormat(0);
            time.setTimeFormat(DateFormat.SHORT);
            
           
            tbl_data.setConverter("CED_SERVICEZEIT", new Converter<String, Time>(){

				@Override
				public Time convertToModel(String value, Class<? extends Time> targetType, Locale locale)
						throws com.vaadin.data.util.converter.Converter.ConversionException {
					// FIXME Auto-generated method stub
					return null;
				}

				@Override
				public String convertToPresentation(Time value, Class<? extends String> targetType, Locale locale)
						throws com.vaadin.data.util.converter.Converter.ConversionException {
					// FIXME Auto-generated method stub
					
					if(value == null){
						return null;
					}
					
					return formatter.print(new Period(new LocalDateTime(value).toDateTime(DateTimeZone.UTC).toDate().getTime()));
					
				}

				@Override
				public Class<Time> getModelType() {
					// FIXME Auto-generated method stub
					return Time.class;
				}

				@Override
				public Class<String> getPresentationType() {
					// FIXME Auto-generated method stub
					return String.class;
				}
            	
            });
            
            tbl_data.setConverter("CED_AMOUNT_CURRENCY", new Converter<String, BigDecimal>() {
            	DecimalFormat df = new DecimalFormat("#0.00 €");
            	
				@Override
				public BigDecimal convertToModel(String value, Class<? extends BigDecimal> targetType, Locale locale)
						throws com.vaadin.data.util.converter.Converter.ConversionException {
					return null;
				}

				@Override
				public String convertToPresentation(BigDecimal value, Class<? extends String> targetType, Locale locale)
						throws com.vaadin.data.util.converter.Converter.ConversionException {
					
					if(value != null)
						return df.format(value);
					else
						return null;
				}

				@Override
				public Class<BigDecimal> getModelType() {
					return BigDecimal.class;
				}

				@Override
				public Class<String> getPresentationType() {
					return String.class;
				}
			});
            
            Converter<String, BigDecimal> secToTimeConverter = new Converter<String, BigDecimal>() {

                @Override
                public BigDecimal convertToModel(String value, Class<? extends BigDecimal> targetType, Locale locale)
                    throws com.vaadin.data.util.converter.Converter.ConversionException {
                    return null;
                }

                @Override
                public String convertToPresentation(BigDecimal value, Class<? extends String> targetType, Locale locale)
                    throws com.vaadin.data.util.converter.Converter.ConversionException {
                    
                    Duration dur = new Duration(0);
                    dur = dur.withDurationAdded(value.longValueExact(), 1000);
                    
                    return formatter.print(dur.toPeriod());
                    
                }

                @Override
                public Class<BigDecimal> getModelType() {
                    return BigDecimal.class;
                }

                @Override
                public Class<String> getPresentationType() {
                    return String.class;
                }

            };
            
            tbl_data.setConverter("CED_DATE", date);
            tbl_data.setConverter("CED_FAHRZEIT", time);
            
        }
        
        tbl_data.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                toggleMenuItems();
                updateFooter();
                
            }
        });
       
        tbl_data.addItemClickListener(new ItemClickListener() {
			
			@Override
			public void itemClick(ItemClickEvent event) {
				// FIXME Auto-generated method stub
								
				updateFooter();
				
			}
		});
        
    }

    private void toggleMenuItems(){
        
        Collection values = (Collection) tbl_data.getValue();
        
        Boolean crud = (!values.isEmpty() && values.size() == 1 && tbl_data.size() > 0);
        Integer inProgress = MyUtils.getValueFromItem(getSelectedItem(), "CED_ID_STATUS", Integer.class);
        
//        btn_create.setEnabled(crud);
//        btn_update.setEnabled(dataIsUser || crud);
        btn_update.setEnabled(crud && (isBasicUser() ? (MyUtils.equalsWithNulls(inProgress, 1) || MyUtils.equalsWithNulls(inProgress, 5)) : true));        
        btn_read.setEnabled(crud);
        btn_delete.setEnabled(crud && MyUtils.equalsWithNulls(inProgress, 1));
        
    }
    
    /*************************** Database ************************************************************************************/
    /*************************************************************************************************************************/
    
    private void updateTable(){
        updateTable(false);
    }
    
    private void updateTable(Boolean ignoreFilter) {
        
        if(deferTableUpdates) {
            return;
        }
        
        if (ignoreFilter || !tbl_data.isFilterBarVisible()) {
            dbGetContainer();
            try{
            	if(tableColsDefault.length > 0){
            		tbl_data.setVisibleColumns(tableColsActive);
            	}
            }catch(Exception e){
                
            }
        }
        
        updateFooter();
        
    }
    
    private void updateFooter(){

    	try {
        	tbl_data.setColumnFooter("CED_SERVICEZEIT", calcTime("CED_SERVICEZEIT"));
        	tbl_data.setColumnFooter("CED_FAHRZEIT", calcTime("CED_FAHRZEIT"));
		} catch (Exception e) {
			// TODO: handle exception
			System.out.println(e.getMessage());
		}

        Integer size = tbl_data.getValue() != null ? ((Collection) tbl_data.getValue()).size() : 0;
        
    	tbl_data.setColumnFooter("CED_KM", calcKM());
    	tbl_data.setColumnFooter("CED_AMOUNT_CURRENCY", calcAmount());
    	tbl_data.setColumnFooter(Iterables.getLast(Arrays.asList(tbl_data.getVisibleColumns())), "Σ " + tbl_data.size() + ((size > 0) ? (" (" + size + ")") : ""));
    	
    }
    
	private void dbGetContainer() {

	    CustomQuery q = new DBClass().CustomQuery;

        String sql = "SELECT"
		   + "\n " + "	CED_ID"		
//		   + "\n " + "	, CED_ID_USER"
    	   + "\n " + "	, CONCAT(AUL_VORNAME, ' ', AUL_NAME) AS USER"
    	   + "\n " + "  , KSK_COUNTRYCODE"
    	   + "\n " + "	, CED_DATE"
    	   + "\n " + "	, CEA_ACTIVITY"
    	   + "\n " + "	, CED_SERVICEZEIT"
    	   + "\n " + "	, CED_FAHRZEIT"
    	   + "\n " + "	, CED_KM"
    	   + "\n " + "	, CED_AMOUNT AS CED_AMOUNT_CURRENCY"
    	   + "\n " + "	, CED_AMOUNT"
    	   + "\n " + "	, IF(CED_STATUS_BILLABLE = 1, 'Ja', IF(CED_STATUS_BILLABLE = 0, 'Nein', IF(CED_STATUS_BILLABLE = -1, 'Unbekannt', ''))) AS CED_STATUS_BILLABLE"
    	   + "\n " + "	, CEC_ROLE"
    	   + "\n " + "	, PSLV_NAME"
    	   + "\n " + "	, CED_COMMENT"
    	   + "\n " + "	, SS_NAME AS CED_STATUS"
    	   + "\n " + "  , GROUP_CONCAT(IF_NAME_ABRV) as NURSE_FIRM"
    	   + "\n " + "  , CED_STATUS AS CED_ID_STATUS"
    	   + "\n " + "FROM"
    	   + "\n " + "	cust_expenses_data"
    	   + "\n " + "LEFT JOIN cms_auth_stammdaten_user ON CED_ID_USER = AUL_ID"
    	   + "\n " + "LEFT JOIN cust_expenses_activity ON CED_ID_CEA = CEA_ID"
    	   + "\n " + "LEFT JOIN cust_expenses_coordinators ON CED_ID_CEC = CEC_ID"
    	   + "\n " + "LEFT JOIN cust_projekte_stammdaten_liste ON CED_ID_PROJECT = PSLV_ID"
    	   + "\n " + "LEFT JOIN cust_schulung_status ON SS_PROZESS = CED_STATUS AND SS_CODE = 'EXP'"
    	   + "\n " + "LEFT JOIN cust_krankenschwester_stammdaten_ks ON KSK_U_ID = AUL_ID"
    	   + "\n " + "LEFT JOIN cust_krankenschwester_stammdaten_firmen ON KSK_ID = KSF_ID_NURSE"
    	   + "\n " + "	AND CED_DATE >= KSF_DATE_FROM AND (CED_DATE <= KSF_DATE_UNTIL OR KSF_DATE_UNTIL IS NULL)"
    	   + "\n " + "LEFT JOIN cust_internal_firms ON KSF_KEY_FIRM = IF_KEY"
    	   ;  
   
//        FILTER
        String glue = hasGlobalFilters() ? " AND " : "";
        
        String where = "";
        
        //if admin skip all
        if(!UserData.get().hasGroup(1)){
           
        	// if authorized filter by country
        	if(UserData.get().getExpenseChecking().isExpenseChecking() || UserData.get().getCS().isCS() || UserData.get().getFinance().isFinance()){

        		
        		if(!UserData.get().getCS().isCS() && !UserData.get().getFinance().isFinance()){
            		UserAttributes ua = new UserAttributes(UserData.get().getUserId());
                    ua.addAttribute("expenses_country");
            		Collection<String> countryList = ua.getAttributeMap().get(UserData.get().getUserId()).get("expenses_country");
        			where += "KSK_Countrycode IN (" + Joiner.on(",").join(MyUtils.wrapStringCollection(countryList, "'")) + ")" + glue;
        		}
        		
        	}else{ // filter by userId only
        		
        		where += "\n " + "CED_ID_USER = " + UserData.get().getUserId() + glue;
        		
        	}
        	
        }

        
        ArrayList<AbstractField> filterList = getActiveGlobalFilters(); 
        
        if(filterMonth.getValue() != null){
            
            java.sql.Timestamp sqlDateFrom = new java.sql.Timestamp(filterMonth.getValue().getTime());
            java.sql.Timestamp sqlDateUntil = new java.sql.Timestamp(new LocalDateTime(filterMonth.getValue()).plusMonths(1).minusMillis(1).toDate().getTime());
            
            filterList.remove(filterMonth);
            glue = hasGlobalFilters(filterList) ? " AND " : "";
            
            where += "\n " + "((CED_DATE between " + "'" + sqlDateFrom.toString() + "' and '" + sqlDateUntil.toString() + "') OR "
                + "(CED_DATE IS NULL AND CED_CREATED between " + "'" + sqlDateFrom.toString() + "' and '" + sqlDateUntil.toString() + "')) " + glue;
        }
        
        if(filterProjectEnabled.getValue() && ((Collection) filterProject.getValue()).size() > 0){
            
            filterList.remove(filterProject);
            glue = hasGlobalFilters(filterList) ? " AND " : "";
            
            Collection<Integer> coll = ((Collection<Integer>) filterProject.getValue());
            
            where += "\n " + "PSLV_ID in ("+ Joiner.on(",").join(coll) + ")" + glue;
        }
        
        if(filterStatusEnabled.getValue() && ((Collection) filterStatus.getValue()).size() > 0){
            
            filterList.remove(filterStatus);
            glue = hasGlobalFilters(filterList) ? " AND " : "";
            
            Collection<Integer> coll = ((Collection<Integer>) filterStatus.getValue());
            
            where += "\n " + "CED_STATUS in ("+ Joiner.on(",").join(coll) + ") OR CED_STATUS IS NULL" + glue;
        }
        
        if(!where.equals("")) {
            sql += "\n where " + where;
        }
        
        sql += "\n group by CED_ID";
        
        if(initialLoad) { // hacky fix for triple loading when configuring filter listener
            sql += "\n limit 0";
        }
        
        q.setSqlString(sql);
        
//        q.db.debugNextQuery(true);
        
        try {
        	Container container = q.query();
            
        	if (tableUpdater != null) {
                tableUpdater.updateTable(container);
            } else {
                tbl_data.setContainerDataSource(container);
            }
        	
		} catch (Exception e) {
			System.out.println("exception!");
			UI.getCurrent().getUI().removePollListener(pollListener);
		}
        
    }
    
    private Container dbGetProjectValues() {
    	
    	CustomQuery q = new DBClass().CustomQuery;
    	
		String sql = "SELECT" 
				+ "\n " + "    cust_projekte_stammdaten_liste.PSLV_ID AS id," 
				+ "\n "	+ "    cust_projekte_stammdaten_liste.PSLV_NAME" 
				+ "\n " + "FROM" 
				+ "\n "	+ "    cust_projekte_stammdaten_liste" 
				+ "\n " + "WHERE" 
				+ "\n "	+ "    PSLV_CODE = 'FOR'" 
				+ "\n "	+ "    OR PSLV_CODE = 'POP'" 
				+ "\n "	+ "    OR PSLV_CODE = 'SA'" 
				+ "\n "	+ "    OR PSLV_CODE = 'INT'" 
				+ "\n "	+ "    OR PSLV_CODE = 'EXP'" 
				+ "\n "	+ "order by if(PSLV_CODE = 'INT', 0, PSLV_NAME) ASC" 
				;    	
    	
    	q.setSqlString(sql);    			
    	    	
    		
        return MyUtils.convertIndex(q.query(), "id");

    }

    private String calcAmount(){
    	BigDecimal items = new BigDecimal(0);
    	
    	for(Iterator i = tbl_data.getItemIds().iterator(); i.hasNext();){
    		
    		int iid = (Integer) i.next();
    		
    		Item item = tbl_data.getItem(iid);
    		
    		items = items.add(item.getItemProperty("CED_AMOUNT").getValue() != null ? (BigDecimal) item.getItemProperty("CED_AMOUNT").getValue() : new BigDecimal(0));
    	}
    	
    	return "Σ " + items + " €";
    }
    
    private String calcKM(){
    	
    	int km = 0;
    	
    	for(Iterator i = tbl_data.getItemIds().iterator(); i.hasNext();){
    		
    		int iid = (Integer) i.next();
    		
    		Item item = tbl_data.getItem(iid);

    		if(item.getItemProperty("CED_KM").getValue() != null)
    			km += (Integer) item.getItemProperty("CED_KM").getValue();
    	}
    	
    	return "Σ " + km + " km";
    }
    
    private String calcTime(String column) throws Exception{

    	PeriodFormatter parser = new PeriodFormatterBuilder().appendHours().appendLiteral(":").appendMinutes().appendLiteral(":").appendSeconds().toFormatter();
    	Period period = Period.ZERO;
    	
    	for(Iterator i = tbl_data.getItemIds().iterator(); i.hasNext();){
    		
    		int iid = (Integer) i.next();
    		
    		Item item = tbl_data.getItem(iid);
    		
    		period = period.plus(MyUtils.getValueFromItem(item, column, Time.class) != null ? parser.parsePeriod(((Time)item.getItemProperty(column).getValue()).toString()) : parser.parsePeriod("00:00:00"));

    	}
    	
    	PeriodFormatter printer = new PeriodFormatterBuilder().printZeroAlways().minimumPrintedDigits(2).appendHours().appendLiteral(":").appendMinutes().toFormatter();

    	return "Σ " + printer.print(period.normalizedStandard(PeriodType.time()))  + " h";
    	
    }
    
    /*************************************************************************************************************************/
    /*************************************************************************************************************************/
    
    @AutoGenerated
    private HorizontalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new HorizontalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // mainContainer
        mainContainer = buildMainContainer();
        mainLayout.addComponent(mainContainer);
        mainLayout.setExpandRatio(mainContainer, 1.0f);
        mainLayout.setComponentAlignment(mainContainer, new Alignment(20));
        
        return mainLayout;
    }

    @AutoGenerated
    private VerticalLayout buildMainContainer() {
        // common part: create layout
        mainContainer = new VerticalLayout();
        mainContainer.setImmediate(false);
        mainContainer.setWidth("100.0%");
        mainContainer.setHeight("100.0%");
        mainContainer.setMargin(true);
        
        // menuSpacer
        menuSpacer = buildMenuSpacer();
        mainContainer.addComponent(menuSpacer);
        
        // globalFilterContainer
        globalFilterContainer = buildGlobalFilterContainer();
        mainContainer.addComponent(globalFilterContainer);
        mainContainer.setComponentAlignment(globalFilterContainer, new Alignment(48));
        
        // tbl_data
        tbl_data = new FilterTable();
        tbl_data.setImmediate(true);
        tbl_data.setWidth("100.0%");
        tbl_data.setHeight("100.0%");
        mainContainer.addComponent(tbl_data);
        mainContainer.setExpandRatio(tbl_data, 1.0f);
        mainContainer.setComponentAlignment(tbl_data, new Alignment(20));
        
        return mainContainer;
    }

    @AutoGenerated
    private VerticalLayout buildMenuSpacer() {
        // common part: create layout
        menuSpacer = new VerticalLayout();
        menuSpacer.setImmediate(false);
        menuSpacer.setWidth("100.0%");
        menuSpacer.setHeight("40px");
        menuSpacer.setMargin(false);
        
        // men_frm
        men_frm = new MenuBar();
        men_frm.setImmediate(false);
        men_frm.setWidth("100.0%");
        men_frm.setHeight("-1px");
        menuSpacer.addComponent(men_frm);
        menuSpacer.setComponentAlignment(men_frm, new Alignment(20));
        
        return menuSpacer;
    }

    @AutoGenerated
    private HorizontalLayout buildGlobalFilterContainer() {
        // common part: create layout
        globalFilterContainer = new HorizontalLayout();
        globalFilterContainer.setImmediate(false);
        globalFilterContainer.setWidth("100.0%");
        globalFilterContainer.setHeight("80px");
        globalFilterContainer.setMargin(false);
        
        // filterMonthLayout
        filterMonthLayout = buildFilterMonthLayout();
        globalFilterContainer.addComponent(filterMonthLayout);
        globalFilterContainer.setComponentAlignment(filterMonthLayout, new Alignment(48));
        
        // filterProjectLayout
        filterProjectLayout = buildFilterProjectLayout();
        globalFilterContainer.addComponent(filterProjectLayout);
        globalFilterContainer.setComponentAlignment(filterProjectLayout, new Alignment(48));
        
        // filterStatusLayout
        filterStatusLayout = buildFilterStatusLayout();
        globalFilterContainer.addComponent(filterStatusLayout);
        globalFilterContainer.setComponentAlignment(filterStatusLayout, new Alignment(48));
        
        return globalFilterContainer;
    }

    @AutoGenerated
    private HorizontalLayout buildFilterMonthLayout() {
        // common part: create layout
        filterMonthLayout = new HorizontalLayout();
        filterMonthLayout.setImmediate(false);
        filterMonthLayout.setWidth("-1px");
        filterMonthLayout.setHeight("-1px");
        filterMonthLayout.setMargin(false);
        filterMonthLayout.setSpacing(true);
        
        // filterMonthEnabled
        filterMonthEnabled = new CheckBox();
        filterMonthEnabled.setCaption("Monatsfilter");
        filterMonthEnabled.setImmediate(false);
        filterMonthEnabled.setWidth("-1px");
        filterMonthEnabled.setHeight("-1px");
        filterMonthLayout.addComponent(filterMonthEnabled);
        filterMonthLayout.setComponentAlignment(filterMonthEnabled, new Alignment(34));
        
        // filterMonth
        filterMonth = new PopupDateField();
        filterMonth.setImmediate(false);
        filterMonth.setWidth("100px");
        filterMonth.setHeight("-1px");
        filterMonthLayout.addComponent(filterMonth);
        filterMonthLayout.setComponentAlignment(filterMonth, new Alignment(33));
        
        return filterMonthLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildFilterProjectLayout() {
        // common part: create layout
        filterProjectLayout = new HorizontalLayout();
        filterProjectLayout.setImmediate(false);
        filterProjectLayout.setWidth("-1px");
        filterProjectLayout.setHeight("-1px");
        filterProjectLayout.setMargin(false);
        filterProjectLayout.setSpacing(true);
        
        // filterProjectEnabled
        filterProjectEnabled = new CheckBox();
        filterProjectEnabled.setCaption("Projektfilter");
        filterProjectEnabled.setImmediate(false);
        filterProjectEnabled.setWidth("-1px");
        filterProjectEnabled.setHeight("-1px");
        filterProjectLayout.addComponent(filterProjectEnabled);
        filterProjectLayout.setComponentAlignment(filterProjectEnabled, new Alignment(34));
        
        // filterProject
        filterProject = new TwinColSelect();
        filterProject.setImmediate(false);
        filterProject.setWidth("-1px");
        filterProject.setHeight("70px");
        filterProjectLayout.addComponent(filterProject);
        filterProjectLayout.setComponentAlignment(filterProject, new Alignment(33));
        
        return filterProjectLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildFilterStatusLayout() {
        // common part: create layout
        filterStatusLayout = new HorizontalLayout();
        filterStatusLayout.setImmediate(false);
        filterStatusLayout.setWidth("-1px");
        filterStatusLayout.setHeight("-1px");
        filterStatusLayout.setMargin(false);
        filterStatusLayout.setSpacing(true);
        
        // filterStatusEnabled
        filterStatusEnabled = new CheckBox();
        filterStatusEnabled.setCaption("Statusfilter");
        filterStatusEnabled.setImmediate(false);
        filterStatusEnabled.setWidth("-1px");
        filterStatusEnabled.setHeight("-1px");
        filterStatusLayout.addComponent(filterStatusEnabled);
        filterStatusLayout.setComponentAlignment(filterStatusEnabled, new Alignment(34));
        
        // filterStatus
        filterStatus = new TwinColSelect();
        filterStatus.setImmediate(false);
        filterStatus.setWidth("-1px");
        filterStatus.setHeight("70px");
        filterStatusLayout.addComponent(filterStatus);
        filterStatusLayout.setComponentAlignment(filterStatus, new Alignment(33));
        
        return filterStatusLayout;
    }
}
