package archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.pop.form;

import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;

import org.joda.time.LocalDate;
import org.joda.time.LocalDateTime;
import org.tepi.filtertable.FilterTable;

import archenoah.config.CMS_Config_Std;
import archenoah.lib.custom.ComponentIterator;
import archenoah.lib.custom.MyUtils;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.tool.comunication.dbclass.DBClass.CustomQuery;
import archenoah.lib.vaadin.Components.ClickMenuBar.ClickCommand;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Tab_Menue_Item;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Window_Button;
import archenoah.lib.vaadin.Components.table.DataviewGenerator;
import archenoah.lib.vaadin.Components.table.FilteringTableUpdater;
import archenoah.lib.vaadin.CustomConverterFactorys.DataviewConverter;
import archenoah.lib.vaadin.CustomConverterFactorys.StringSqlTimestampConverter;
import archenoah.lib.vaadin.Language.i18n.I18nCB;
import archenoah.lib.vaadin.Language.i18n.I18nConverter;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalMessages;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.lib.vaadin.MenuBerechtigung.Rechteholen;
import archenoah.lib.vaadin.resources.Icons;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.OpenTickets.classes.TicketContentLocator;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.classes.PatientHistoryToggle;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.classes.PatientHistoryToggle.ToggleListener;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.pop.classes.I18nPoPProcessConverter;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.pop.classes.PoPPdfPrint;

import com.google.common.base.Joiner;
import com.google.gwt.thirdparty.guava.common.base.Strings;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Container.ItemSetChangeEvent;
import com.vaadin.data.Container.ItemSetChangeListener;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.event.UIEvents.PollEvent;
import com.vaadin.event.UIEvents.PollListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.shared.ui.datefield.Resolution;
import com.vaadin.ui.AbstractComponent;
import com.vaadin.ui.AbstractField;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.Command;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TwinColSelect;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.Window.CloseEvent;
import com.vaadin.ui.Window.CloseListener;

import de.steinwedel.messagebox.ButtonId;
import de.steinwedel.messagebox.MessageBoxListener;


@SuppressWarnings({"serial", "rawtypes", "unchecked"})
public class PoPDataView extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private HorizontalLayout mainLayout;

    @AutoGenerated
    private VerticalLayout mainContainer;

    @AutoGenerated
    private FilterTable tbl_data;

    @AutoGenerated
    private HorizontalLayout globalFilterContainer;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_3;

    @AutoGenerated
    private TwinColSelect filterStatus;

    @AutoGenerated
    private CheckBox filterStatusEnabled;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_2;

    @AutoGenerated
    private PopupDateField filterMonth;

    @AutoGenerated
    private CheckBox filterMonthEnabled;

    @AutoGenerated
    private VerticalLayout menuSpacer;

    @AutoGenerated
    private MenuBar men_frm;

    

	

	

	

	

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */

    /**************** --> Allgemein <--- ********************/
    I18nManager i18n;
    private static org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(PoPDataView.class);
    
    // Datenbank
    private Map<Object, String> componentMap;
    private FilteringTableUpdater tableUpdater = null;
    private CMS_Config_Std config = CMS_Config_Std.getInstance();

    // Berrechtigung
    private int ACC_ID;

    private int permRead;
    private int permCreate;
    private int permUpdate;
    private int permDelete;

    private MenuItem tmpMenu = null;

    private Button tmpButton = null;
    /******************************************************/
    /**************** --> Tabsheetvars <--- *****************/
    private TabSheet tab = null;

    /******************************************************/
    /**************** --> Windowvars <--- *******************/
    private Window win = null;
    /******************************************************/

    private DetachListener onDetach = null;

    /******************* -> Menüpunkte <- ********************/
    private MenuBar.MenuItem btn_create;
    private MenuBar.MenuItem btn_update;
    private MenuBar.MenuItem btn_read;
    private MenuBar.MenuItem btn_delete;
    private MenuBar.MenuItem btn_filter;
    private MenuBar.MenuItem btn_pdf;
    private MenuBar.MenuItem btn_RegionalManager;
    private MenuBar.MenuItem btn_ProjectManager;
    private MenuBar.MenuItem btn_locate;
    
    /*******************************************************/
    /******************* --> Custom <--- ********************/
    /******************************************************/

    private Boolean firstFilter = true;
    private PollListener pollListener = null;
    
    enum Status {}
    
    private Boolean regionalManagerView = false;
    private Boolean projectManagerView = false;
    
    private PatientHistoryToggle patientHistory;
    private Integer patientId; 
    private boolean deferTableUpdates;

    
    /************ ----->Einstellungen<-- ********************/
    private final String formIdPerm = "410";
    private final String winHeight = "600px";
    private final String winWidth = "900px";


    /******************************************************/

    private final String tableIdCol = "ID";
    private final String tableName = "cust_protokoll_pop_daten";
    
    //TASK cols
    private final Object[] tableColsAll = new Object[] { "ID", "rx", "Patient", "Land", "Arzt", "Krankenschwester", "Datum", "infType", "IF_NAME", "PP_PRODUCT", "regionalManagerOk", "Regionalleiter", "Status" };
    //use custom Cols when needed
    private Object[] tableColsDefault = tableColsAll;
    //use custom Cols when needed
    private final Object[] tableColsFilter = tableColsDefault;
    private Object[] tableColsActive = tableColsDefault;
    
    private final static class caption extends I18nCB{
        static final I18nCB regionalManagerOktrue = set();
        static final I18nCB regionalManagerOkfalse = set();

        static final I18nCB regionalManager = set();
        static final I18nCB projectManager = set();
        static final I18nCB enable = set();
        static final I18nCB disable = set();

    }
    
    /******************************************************/

    public PoPDataView(MenuItem Arg_Menü) {
        tmpMenu = Arg_Menü;
    }

    public PoPDataView(Button Arg_btn) {
        tmpButton = Arg_btn;
    }

    /***************************** ---> Feste Funtionen<--- **************************************/

    /********* INIT-Window ************/
    public void init() {

        Standard_Init();

        if (tmpMenu != null) {
            String Recourcename = tmpMenu.getIcon().toString();
            Recourcename = Recourcename.substring(0, Recourcename.length() - 12) + "white-16.png";

            Build_Window_Button bwb = new Build_Window_Button(tmpMenu.getText(), mainLayout, winHeight, winWidth,
                    new ThemeResource(Recourcename));
            win = bwb.ReturnWindow();
        }
        if (tmpButton != null) {
            Build_Window_Button bwb = new Build_Window_Button(tmpButton.getCaption(), mainLayout, winHeight, winWidth,
                    tmpButton.getIcon());
            win = bwb.ReturnWindow();
        }

        win.addDetachListener(onDetach);

    }
    
    public Window getWindow(){
    	return win;
    }
    
    public TabSheet getTabSheet(){
    	return tab;
    }
    
    public void init(TabSheet Arg_tab) {

        Standard_Init();
        tab = Arg_tab;
        if (tmpMenu != null) {
            new Build_Tab_Menue_Item(Arg_tab, tmpMenu.getText(), mainLayout, tmpMenu.getIcon());
        }
        if (tmpButton != null) {
            new Build_Tab_Menue_Item(Arg_tab, tmpButton.getCaption(), mainLayout, tmpButton.getIcon());
        }

        tab.getSelectedTab().addDetachListener(onDetach);
    }

    /********* Init-Standard ************/
    private void Standard_Init() {
        buildMainLayout();
        
        i18n = new I18nManager(this);
        
        registerComponents();
        
        generateMenu();

        setMenuPermissions();

        setGlobalFilterMonth();
        updateTable();
        tbl_data.setSortContainerPropertyId(tableIdCol);
        tbl_data.setSortAscending(true);
        tbl_data.sort();
        configureTable();
        configureComponents();

        
        
//        updateTable(); // not needed since month filter default rework
        
        setupListenersAndDetachEvent();
        
        i18n.refresh();
        
    }
    
    // register components for lng and validation tools
    private void registerComponents(){
    	componentMap = new HashMap<Object, String>();
    	new ComponentIterator(mainContainer).createMap(componentMap);
    }

    
    private void setupListenersAndDetachEvent() {
        pollListener = new PollListener() {

            @Override
            public void poll(PollEvent event) {
                if(tab.isRendered(mainLayout)  && filterMonthEnabled.getValue()){
                    updateTable();
                }
            }
        };

        UI.getCurrent().getUI().addPollListener(pollListener);

        onDetach = new DetachListener() {

            @Override
            public void detach(DetachEvent event) {
                UI.getCurrent().getUI().removePollListener(pollListener);
            }
        };
    }
    
    @SuppressWarnings("unused")
    public void setPermissionsFromDatabase() {
        if (formIdPerm == "") {
            System.out.println("Form Einstellung Fehlt: Berechtigung");
            return;
        }

        ACC_ID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        Rechteholen r = new Rechteholen(ACC_ID + "");
        String[][] perms = r.Datenholen();

        for (int i = 0; i < perms.length; i++) {
            if (perms[i][0].equals(formIdPerm) == true) {

                permRead = Integer.valueOf(perms[i][3]);
                permUpdate = Integer.valueOf(perms[i][4]);
                permCreate = Integer.valueOf(perms[i][6]);
                permDelete = Integer.valueOf(perms[i][5]);
                
            }
        }
    }

    public void setPermissions(int create, int read, int update, int delete) {

        permCreate = create;
        permRead = read;
        permUpdate = update;
        permDelete = delete;

    }

    private void setMenuPermissions() {
        Boolean c = (permCreate == 1);
        Boolean r = (permRead == 1);
        Boolean u = (permUpdate == 1);
        Boolean d = (permDelete == 1);

        btn_create.setEnabled(c);
        btn_create.setVisible(c);

        btn_read.setEnabled(r);
        btn_read.setVisible(r);

        btn_update.setEnabled(u);
        btn_update.setVisible(u);

        btn_delete.setEnabled(d);
        btn_delete.setVisible(d);
    }

    /************ -><- ******************/
    
    public void setGlobalFilterMonth(Date date){
        LocalDate ld = new LocalDate(date);
        filterMonthEnabled.setValue(true);
        filterMonth.setValue(new LocalDate(ld.getYear(), ld.getMonthOfYear(), 1).toDate());
    }
    
    public void setGlobalFilterMonth(){
        setGlobalFilterMonth(new Date());
    }
    
    /***************** Comands *********************/
    
    CloseListener closeListener = new CloseListener() {
		
		@Override
		public void windowClose(CloseEvent e) {
			updateTable(true);
		}
	};
    
    private Integer getSelectedId(){
        Integer id = null;
        try {
            id = (Integer) tbl_data.getContainerProperty(((Collection)tbl_data.getValue()).toArray()[0], tableIdCol).getValue();
        } catch (Exception e) {
        }
        return id;
    }
    
    private Collection<Integer> getSelectedIds(){
        Collection<Integer> vals = (Collection<Integer>) tbl_data.getValue();
        
        ArrayList<Integer> ids = new ArrayList<Integer>();
        
        for (Integer row : vals) {
            ids.add((Integer) tbl_data.getContainerProperty(row, tableIdCol).getValue());
        }
        
        return ids;
    }
	
    private Item getSelectedItem() {
        Item item = null;
        try {
            item = tbl_data.getItem(((Collection)tbl_data.getValue()).toArray()[0]);
        } catch (Exception e) {}
        return item;
    }

    //TASK Commands are here
    public ClickCommand cmd_btn_add = new ClickCommand() {
        
        @Override
        public void menuClicked(MenuItem selectedItem) {
            
            Integer pid = dbCreate();
            
            if(pid == null) {
                return;
            }
            
        	PoPInsertEdit pie = new PoPInsertEdit(selectedItem, Integer.toString(pid));
        	pie.setPermissions(permCreate, permRead, permUpdate, permDelete);
        	pie.init();
        	pie.getWindow().addCloseListener(closeListener);
        	pie.getWindow().setClosable(false);
        	
            this.setWindow(pie.getWindow());
            this.setParent(men_frm);
        }

    };
    
    public ClickCommand cmd_btn_read = new ClickCommand() {
        
        @Override
        public void menuClicked(MenuItem selectedItem) {

            if(tbl_data.getValue() == null){
                I18nManager.global(I18nGlobalNotifiers.no_entry_selected);
                return;
            }
            
            PoPInsertEdit pie = new PoPInsertEdit(selectedItem, getSelectedId().toString());
        	pie.setPermissions(0, permRead, 0, 0);
        	pie.init();
            this.setWindow(pie.getWindow());
            this.setParent(men_frm);
        }

    };
    
    public ClickCommand cmd_btn_edit = new ClickCommand() {
        
        @Override
        public void menuClicked(MenuItem selectedItem) {
            
            if(tbl_data.getValue() == null){
                I18nManager.global(I18nGlobalNotifiers.no_entry_selected);
                return;
            }
            
            PoPInsertEdit pie = new PoPInsertEdit(selectedItem, getSelectedId().toString());
            if(!regionalManagerView && projectManagerView) {
                pie.setPermissions(0, 1, 0, 0);
            }else {
                pie.setPermissions(permCreate, permRead, permUpdate, permDelete);
            }
        	pie.setRegionalManagerEnabled(regionalManagerView);
        	pie.init();
        	pie.getWindow().addCloseListener(closeListener);
            this.setWindow(pie.getWindow());
            this.setParent(men_frm);
        	
        }
        
    };

    public Command cmd_btn_del = new Command() {
        @Override
        public void menuSelected(MenuItem selectedItem) {
            
            if(tbl_data.getValue() == null){
                I18nManager.global(I18nGlobalNotifiers.no_entry_selected);
                return;
            }
            
            deleteData(getSelectedIds());
            tbl_data.setValue(null);
            
        }
    };

    public Command cmd_btn_filter = new Command() {
        @Override
        public void menuSelected(MenuItem selectedItem) {

            if (firstFilter) {
                tbl_data.setFilterBarVisible(true);
                tbl_data.setFilterBarVisible(false);
                firstFilter = false;
            }
            tbl_data.setFilterBarVisible(!tbl_data.isFilterBarVisible());
            
            if(!tbl_data.isFilterBarVisible()){
                tbl_data.clearFilters();
            }
            
            tableColsActive = tbl_data.isFilterBarVisible() ? tableColsFilter : tableColsDefault;
            if(tbl_data.getContainerDataSource().size() > 0 && tableColsActive.length > 0){
            	tbl_data.setVisibleColumns(tableColsActive);
            }

        }
    };
    
    public Command cmd_btn_regionalManagerView = new Command() {
        @Override
        public void menuSelected(MenuItem selectedItem) {

            regionalManagerView = !regionalManagerView;
            updateTable();
            toggleRlCaption();
            
        }
        
    };
    
    public Command cmd_btn_projectManagerView = new Command() {
        @Override
        public void menuSelected(MenuItem selectedItem) {

            projectManagerView = !projectManagerView;
            updateTable();
            toggleRlCaption();
            
        }
        
    };
    
    public ClickCommand cmd_btn_locateTicket = new ClickCommand() {
        
        @Override
        public void menuClicked(MenuItem selectedItem) {
            
            Integer project = (Integer) tbl_data.getContainerProperty(((Collection)tbl_data.getValue()).toArray()[0], "VH_PROJEKT_ID").getValue();
            
            TicketContentLocator locator = new TicketContentLocator(selectedItem);
            this.setWindow(locator.locateContent(project, getSelectedId()));
            this.setParent(men_frm);
            
        }

    };
    
    
    private void toggleRlCaption() {
        btn_RegionalManager.setText(i18n.get(caption.regionalManager)+ " "+ i18n.get((regionalManagerView ? caption.disable : caption.enable)));
        btn_ProjectManager.setText(i18n.get(caption.projectManager)+ " "+ i18n.get((regionalManagerView ? caption.disable : caption.enable)));
    }
    
    /******************************************/

    
    

    /*********** Gen Menüs *************/
    private void generateMenu() {

        btn_create = men_frm.addItem("FRM_ADD", Icons.White.add_16, cmd_btn_add);
        btn_update = men_frm.addItem("FRM_EDIT", Icons.White.edit_16, cmd_btn_edit);
        btn_read = men_frm.addItem("FRM_READ", Icons.White.perm_lesen_16, cmd_btn_read);
        btn_delete = men_frm.addItem("FRM_DEL", Icons.White.delete_16, cmd_btn_del);
        
        btn_filter = men_frm.addItem("FRM_FILTER", Icons.White.filter_16, cmd_btn_filter);
        btn_RegionalManager = men_frm.addItem("FRM_REGIONAL_MANAGER", Icons.White.krankenschwester_16, cmd_btn_regionalManagerView);
        btn_ProjectManager = men_frm.addItem("FRM_PROJECT_MANAGER", Icons.White.krankenschwester_16, cmd_btn_projectManagerView);
        
        
        btn_pdf = men_frm.addItem("FRM_PDF", Icons.White.log_16, null);
        
        btn_locate = men_frm.addItem("FRM_LOCATE", Icons.White.backup_16, cmd_btn_locateTicket);


    }
    
    private void configureComponents(){
       
    	for (Entry<Object, String> entry : componentMap.entrySet()) {
    		AbstractComponent field = (AbstractComponent) entry.getKey();
    		
			field.setImmediate(true);
			
			
			if(field instanceof ComboBox){
				((ComboBox)field).setFilteringMode(FilteringMode.CONTAINS);
			}
			
		}
    	
    	
    	btn_RegionalManager.setVisible(isRegionalManager());
    	btn_ProjectManager.setVisible(MyUtils.getUserData().getProjectManager().forProjectCode("POP"));
    	toggleRlCaption();
        
        // MONTHPICKER
//        filterMonthEnabled.setValue(filterMonthEnabled.isEnabled());
        filterMonthEnabled.setImmediate(true);
        filterMonth.setResolution(Resolution.MONTH);
        filterMonth.setDateFormat("MMM yyyy");
//        filterMonth.setEnabled(false);
        
        filterMonthEnabled.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                Boolean enabled = (Boolean)event.getProperty().getValue();
                filterMonth.setEnabled(enabled);
                if(enabled && filterMonth.getValue() == null){
                    LocalDate ld = new LocalDate();
                    filterMonth.setValue(new LocalDate(ld.getYear(), ld.getMonthOfYear(), 1).toDate());
                }else if(!enabled){
                    filterMonth.setValue(null);
                }
                
            }
        });
        
        filterMonth.setImmediate(true);
        filterMonth.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                updateTable(true);
                
            }
        });
        
        // STATUSPICKER
        filterStatusEnabled.setValue(true);
        filterStatusEnabled.setImmediate(true);
//        filterStatus.setContainerDataSource(dbGetStatusValues());
        new I18nPoPProcessConverter().attachDatasource(filterStatus);
       
        preselectStatusFilter();
        
        filterStatusEnabled.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                Boolean enabled = (Boolean)event.getProperty().getValue();
                filterStatus.setEnabled(enabled);
                if(enabled){
                    preselectStatusFilter();
                }
                updateTable(true);
                
            }
        });
        
        filterStatus.setImmediate(true);
        filterStatus.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                Collection val = (Collection) filterStatus.getValue();
                filterStatusEnabled.setValue(val.size() != 0);
                updateTable(true);
                
            }
        });
        
        patientHistory = new PatientHistoryToggle("ID_PATIENT", "Patient", men_frm, tbl_data);
        patientHistory.setToggleListener(new ToggleListener() {
            @Override
            public void onToggle(Integer pid) {
                patientId = pid;
                
                deferTableUpdates(true);
                boolean enableFilters = (pid == null);
                filterMonthEnabled.setValue(enableFilters);
                filterStatusEnabled.setValue(enableFilters);
                deferTableUpdates(false);

                updateTable(true);
                toggleMenuItems();
            }
        });
    
        toggleMenuItems();

        
        PoPPdfPrint print = new PoPPdfPrint(tbl_data);
        print.attach(mainLayout, btn_pdf);
        
    }
    
    private void deferTableUpdates(boolean defer) {
        this.deferTableUpdates = defer;
    }

    
    private void preselectStatusFilter(){
        // Preselect a few items
        HashSet<Integer> preselected = new HashSet<Integer>();
        Collections.addAll(preselected, 1, 2, 3, 4);
        filterStatus.setValue(preselected);
    }
    
    private ArrayList<AbstractField> getActiveGlobalFilters(){
        ArrayList<AbstractField> al = new ArrayList<AbstractField>();
        
        if(filterMonth.getValue() != null){
            al.add(filterMonth);
        }
        
        if(filterStatusEnabled.getValue() && ((Collection) filterStatus.getValue()).size() > 0){
            al.add(filterStatus);
        }
        
        return al;
    }
    
    private Boolean hasGlobalFilters(ArrayList a){
        
        return (a.size() > 0);
        
    }
    
    private Boolean hasGlobalFilters(){
        
        return hasGlobalFilters(getActiveGlobalFilters());
        
    }
    
    /*************************** Config TBL ********************/

    private void configureTable() {
        tbl_data.setSelectable(true);
        tbl_data.setFilterOnDemand(false);
        tbl_data.setMultiSelect(true);
        tbl_data.setImmediate(true);
        tbl_data.setColumnCollapsingAllowed(false);
        tbl_data.setFooterVisible(true);
        tbl_data.setPageLength(1);
        try {
        	if(tableColsDefault.length > 0){
        		tbl_data.setVisibleColumns(tableColsDefault);
        	}
		} catch (Exception e) {

		}
        
        if(tbl_data.size() > 0){
            
            StringSqlTimestampConverter time = new StringSqlTimestampConverter();
            time.setDateFormat(DateFormat.SHORT);
            time.setTimeFormat(DateFormat.SHORT);
            
            tbl_data.setConverter("Datum", time);
            
            I18nConverter lc = new I18nConverter("cust_protokoll_pop_typ", "STRING", "STRING");
            tbl_data.setConverter("infType", lc);
            
            I18nPoPProcessConverter pc = new I18nPoPProcessConverter();
            tbl_data.setConverter("Status", pc);
            
            HashMap<String, DataviewConverter> converterMap = new HashMap<String, DataviewConverter>();
            converterMap.put("infType", lc);
            converterMap.put("Status", pc);
            tbl_data.setFilterOnDemand(false);
            tbl_data.setFilterGenerator(new DataviewGenerator(converterMap));

        
        }
        
        tableUpdater = new FilteringTableUpdater(tbl_data);
        
        tbl_data.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                toggleMenuItems();
                
            }
        });
        toggleMenuItems();
        
        tbl_data.addItemSetChangeListener(new ItemSetChangeListener() {
            @Override
            public void containerItemSetChange(ItemSetChangeEvent event) {
                tbl_data.setValue(null);
            }
        });

        for (Object col : tableColsAll) {
        	
        	try {
        		tbl_data.setColumnExpandRatio(col, 1);
			} catch (Exception e) {
				
			}
        		
		}
        
        tbl_data.setColumnExpandRatio("ID", 0);
        tbl_data.setColumnExpandRatio("rx", 0);
    }

    private void toggleMenuItems(){
        
        Collection values = (Collection) tbl_data.getValue();
        
        Boolean crud = (!values.isEmpty() && values.size() == 1);
        Boolean multi = !values.isEmpty();
        boolean hasPatient = patientId != null;
        
        btn_create.setEnabled(crud && !hasPatient);
        btn_update.setEnabled(crud && !hasPatient);
        btn_read.setEnabled(crud);
        btn_delete.setEnabled((crud || multi) && !hasPatient);
        
        btn_pdf.setEnabled(multi);
        
        btn_locate.setEnabled(crud);
        
        if(patientHistory != null) {
            patientHistory.setEnabled(crud || hasPatient);
        }
    }
    
    /*************************** Database ********************/
    
    /********************************/
    
    
    private void updateTable(){
        updateTable(false);
    }
    
    private void updateTable(Boolean ignoreFilter) {
        
        if(deferTableUpdates) {
            return;
        }
        
        if (ignoreFilter || !tbl_data.isFilterBarVisible()) {
            dbGetContainer();
            try{
            	if(tableColsDefault.length > 0){
            		tbl_data.setVisibleColumns(tableColsActive);
            	}
            }catch(Exception e){
                
            }
        }
        
        tbl_data.setColumnFooter("Status", "Σ " + tbl_data.size());
        
    }
    
    private void deleteData(final Collection<Integer> ids){
        
        I18nManager.global(I18nGlobalMessages.confirm_delete, new MessageBoxListener() {
            
            @Override
            public void buttonClicked(ButtonId arg0) {
                if(ButtonId.YES == arg0) {
                    dbDeleteData(ids);
                }
            }
        });
    }
    
    private int getNurseUID() {
        int UID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        DBClass db = new DBClass();

        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cms_auth_liste_gu");

        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cms_auth_liste_gu", "AL_U_ID", "=", "'" + UID + "'", "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cms_auth_liste_gu", "AL_G_ID", "=", "'12'", "");

        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();

        if (con.size() > 0) {
            return UID;
        } else {
            return 0;
        }

    }
    
    private Boolean isRegionalManager() {
        int UID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        DBClass db = new DBClass();
        
//        select *"
//        + "\n " + "from"
//        + "\n " + "cust_stammdaten_regionalleiter"
//        + "\n " + "inner join cust_projekte_stammdaten_liste on SRL_ID_PROJEKT = PSLV_ID"
//        + "\n " + "where PSLV_CODE = 'POP'"
//        + "\n " + "group by SRL_ID_USER
        
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_stammdaten_regionalleiter", "INNER JOIN", "cust_projekte_stammdaten_liste", "SRL_ID_PROJEKT", "PSLV_ID");
        
        
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_stammdaten_regionalleiter", "SRL_ID_USER", "=", "'" + UID + "'", "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_projekte_stammdaten_liste", "PSLV_CODE", "=", "'POP'", "");
        
        db.DB_Data_Get.DB_Gruppieren.DB_Gruppieren("SRL_ID_USER");

        Container con = db.DB_Data_Get.DB_SEND_AND_GET();

        if (con.size() > 0) {
           return true;
        } else {
            return false;
        }

    }
    
    private Container dbGetStatusValues() {
        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("SS_PROZESS");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("SS_NAME");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_schulung_status");
        
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_schulung_status", "SS_PROJEKT", "=", "5000", "");
        
        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();
        db.DB_Data_Get.connclose();
        
        return con;

    }
    
    //TASK dbget
	private void dbGetContainer() {
        CMS_Config_Std std = CMS_Config_Std.getInstance();
        
        Integer NUID = getNurseUID();
        
        DBClass db = new DBClass();

        /************ Set Spalten *************/
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("VH_PROJEKT_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln(tableName + ".ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("GROUP_CONCAT(balance SEPARATOR ' & ')" , "rx");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(Arzt.AUL_NAME,', ',Arzt.AUL_VORNAME,', ', ASAN_NAME,' ',ASA_TITEL)", "Arzt");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(PSL_NAME,', ',PSL_VORNAME, ', ', PSA_NAME,' ',PSL_TITEL)", "Patient");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("ID_PATIENT");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("ID_NURSE"); // for copy on add
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("ID_DELEGATION"); // for copy on add
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("ARZT_ID"); // for copy on add
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("PSL_COUNTYCODE", "Land");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(Krankenschwester.AUL_VORNAME,' ',Krankenschwester.AUL_NAME)", "Krankenschwester");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln(
            "CONCAT(Regionalleiter.AUL_VORNAME,' ',Regionalleiter.AUL_NAME)", "Regionalleiter");
        //additional columns for project leads
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("ptype.STRING as infType");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("IF_NAME");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("PP_PRODUCT");

        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CASE WHEN DATE > '1900-01-01 00:00:00' THEN DATE_ADD(DATE, INTERVAL IF(VON != '', VON, '') HOUR_MINUTE) END", "'Datum'");

        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CASE when REGIONAL_MANAGER_OK = 0 then '" + i18n.get(caption.regionalManagerOkfalse)
                + "' else '" + i18n.get(caption.regionalManagerOktrue) + "' end", "'regionalManagerOk'");

//        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("SS_NAME", "'Status'");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("STATUS", "'Status'");
      
        /**************************************/
        /************ Set Tabelle *************/

        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung(tableName, "LEFT JOIN", "cust_patient_stammdaten_liste", "ID_PATIENT", "PSL_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_patient_stammdaten_liste", "RIGHT JOIN", "cust_patient_stammdaten_anrede", "PSL_ANREDE", "PSA_ID");
        
        /* Krankenschwester */
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung(tableName, "RIGHT JOIN", "cust_krankenschwester_stammdaten_ks", "ID_NURSE", "KSK_ID");

        /* Arzt */
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung(tableName, "RIGHT JOIN", "cust_arzt_stammdaten_arzt", "ARZT_ID", "ASA_ID");

        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung_Graph("LEFT JOIN", "cms_auth_stammdaten_user AS Arzt", "Arzt", "cust_arzt_stammdaten_arzt", "AUL_ID", "ASA_U_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung_Graph("LEFT JOIN", "cms_auth_stammdaten_user AS Krankenschwester", "Krankenschwester", "cust_krankenschwester_stammdaten_ks", "AUL_ID", "KSK_U_ID");

        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung_Graph("LEFT JOIN", "cust_krankenschwester_stammdaten_anrede", "cust_krankenschwester_stammdaten_anrede", "Krankenschwester", "KSA_ID", "AUL_ANREDE_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung_Graph("LEFT JOIN", "cust_arzt_stammdaten_anrede", "cust_arzt_stammdaten_anrede", "Arzt", "ASAN_ID", "AUL_ANREDE_ID");
        
        /* rx */
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung(tableName, "RIGHT JOIN", "cust_protokoll_pop_meta_dynamic", "ID_DELEGATION", "PPOPMD_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_protokoll_pop_meta_dynamic", "RIGHT JOIN", "cust_verk_haupt", "PPOPMD_VH_ID", "VH_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_verk_haupt", "RIGHT JOIN", "cust_prescriptions_products", "VH_PROJEKT_ID", "PP_ID_PROJECT");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung(tableName, "RIGHT JOIN", "view_balance_rx", "ID_PATIENT", "PB_ID_PATIENT and PB_ID_PRODUCT = PP_ID");
        
        /* type */
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung_Graph("/*t*/ LEFT JOIN", "/*a*/cust_protokoll_pop_typ as ptype", "/*b*/cust_protokoll_pop_daten", "ptype", "INFUSIONSTYP", "ID");
        
        
        /* RL */
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_protokoll_pop_meta_dynamic", "RIGHT JOIN", "cust_protokoll_pop_meta_static", "PPOPMD_VH_ID", "PPOPMS_VH_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_protokoll_pop_meta_static", "RIGHT JOIN", "cust_stammdaten_regionalleiter", "PPOPMS_ID_REG_LEAD", "SRL_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung_Graph("LEFT JOIN", "cms_auth_stammdaten_user AS Regionalleiter", "Regionalleiter",
          "cust_stammdaten_regionalleiter", "AUL_ID", "SRL_ID_USER");
        
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_protokoll_pop_meta_static", "RIGHT JOIN", "cust_internal_firms", "PPOPMS_KEY_FIRM", "IF_KEY");
        /**************************************/
        /************ Set Filter *************/
        String glue = "";
        
        if (NUID != 0 && patientId == null) {
            
            if(hasGlobalFilters()){
                glue = "AND";
            }
            
            if(regionalManagerView) {
                // do nothing
            }else if(projectManagerView){
                // filter by allowed pids
                String ids = Joiner.on(",").join(MyUtils.getUserData().getProjectManager().getProjectIdsForCode("POP"));
                db.DB_Data_Get.DB_Filter.DB_WHERE_In("cust_verk_haupt", "VH_PROJEKT_ID", ids, glue);
            }else {
                // filter by nurse
                db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_krankenschwester_stammdaten_ks", "KSK_U_ID", "=", Integer.toString(NUID), glue);
            }
            
            
        }
        
        //patientHistory if set
        if(patientId != null) {
            if(hasGlobalFilters()){
                glue = " AND ";
            }
            db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein(tableName, "ID_PATIENT", "=", Integer.toString(patientId), glue);
        }
        
        ArrayList<AbstractField> filterList = getActiveGlobalFilters(); 
        
        if(filterMonth.getValue() != null){
            
            java.sql.Timestamp sqlDateFrom = new java.sql.Timestamp(filterMonth.getValue().getTime());
            java.sql.Timestamp sqlDateUntil = new java.sql.Timestamp(new LocalDateTime(filterMonth.getValue()).plusMonths(1).minusMillis(1).toDate().getTime());
            
            filterList.remove(filterMonth);
            glue = hasGlobalFilters(filterList) ? "AND" : "";
            
            db.DB_Data_Get.DB_Filter.DB_WHERE_BETWEEN("(" + tableName, "DATE", "'" + sqlDateFrom.toString() + "'",  "'" + sqlDateUntil.toString() + "'", "OR");
            db.DB_Data_Get.DB_Filter.DB_WHERE_BETWEEN("(DATE IS NULL AND " + tableName, "CREATED", "'" + sqlDateFrom.toString() + "'",  "'" + sqlDateUntil.toString() + "'))", glue);
        }
        
        if(filterStatusEnabled.getValue() && ((Collection) filterStatus.getValue()).size() > 0){
            
            filterList.remove(filterStatus);
            glue = hasGlobalFilters(filterList) ? "AND" : "";
            
            Collection<Integer> coll = ((Collection<Integer>) filterStatus.getValue());
            
            
            db.DB_Data_Get.DB_Filter.DB_WHERE_In("("+tableName, "STATUS", Joiner.on(",").join(coll), "OR");
            db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein(tableName, "STATUS", "IS", "NULL)", glue);
        }
        
        /**************************************/
        
        db.DB_Data_Get.DB_Ordnen.DB_Ordnen("ID", "ASC");
        db.DB_Data_Get.DB_Gruppieren.DB_Gruppieren("ID");
        
        /**************************************/
        /************ Set Custom *************/
        /**************************************/

//        db.DB_Data_Get.Set_Type("PSLV_NAME", Project.class);
        
        /* **************************/
        
//        db.debugNextQuery(true);
        
        try {
        	Container container = db.DB_Data_Get.DB_SEND_AND_GET_Container();
            
        	if (tableUpdater != null) {
                tableUpdater.updateTable(container);
            } else {
                tbl_data.setContainerDataSource(container);
            }
        	
		} catch (Exception e) {
			// TASK: handle exception
			System.out.println("exception!");
			UI.getCurrent().getUI().removePollListener(pollListener);
		}
        
    }
    
    private String generateCollectionString(Collection<Integer> ids){
        String in = "";
        String comma = "";
        
        for (Integer integer : ids) {
            in += comma + integer;
            if(Strings.isNullOrEmpty(comma)){
                comma = ", ";
            }
        }
        
        return in;
    }
    
    private void dbDeleteData(Collection<Integer> ids){
        
        DBClass db = new DBClass();
        db.DB_Data_Delete.DB_Tabellen.DB_set_Tabelle_Einzeln(tableName);
        db.DB_Data_Delete.DB_Filter.DB_WHERE_In(tableName, tableIdCol, Joiner.on(",").join(ids), "");
        db.DB_Data_Delete.DB_Delete();
    
        I18nManager.global(I18nGlobalNotifiers.entry_deleted);
        
        updateTable(true);

        
    }
    
    private Integer dbCreate() {
        
        if(tbl_data.getValue() == null) {
            return null;
        }
        
        Item item = getSelectedItem();
        
        ArrayList<Integer> generatedKeys = new ArrayList<Integer>();
        
        Integer vhId = MyUtils.getValueFromItem(item, "ID_DELEGATION", Integer.class);
        Integer nurseId = MyUtils.getValueFromItem(item, "ID_NURSE", Integer.class);
        Integer patientId = MyUtils.getValueFromItem(item, "ID_PATIENT", Integer.class);
        Integer arztId = MyUtils.getValueFromItem(item, "ARZT_ID", Integer.class);

        
        CustomQuery q = new DBClass().CustomQuery;
        String sql = "INSERT INTO `cust_protokoll_pop_daten` (ID_DELEGATION, ID_NURSE, ID_PATIENT, ARZT_ID) VALUES"
             + "\n " + "("
             + MyUtils.formatSqlValue(vhId) + ", "
             + MyUtils.formatSqlValue(nurseId) + ", "
             + MyUtils.formatSqlValue(patientId) + ", "
             + MyUtils.formatSqlValue(arztId)
                 + ");";
        q.setSqlString(sql);
//        q.db.debugNextQuery(true);
        
        q.update(false, generatedKeys);
        
        return generatedKeys.iterator().next();
    }
    
    @AutoGenerated
    private HorizontalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new HorizontalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // mainContainer
        mainContainer = buildMainContainer();
        mainLayout.addComponent(mainContainer);
        mainLayout.setExpandRatio(mainContainer, 1.0f);
        mainLayout.setComponentAlignment(mainContainer, new Alignment(20));
        
        return mainLayout;
    }

    @AutoGenerated
    private VerticalLayout buildMainContainer() {
        // common part: create layout
        mainContainer = new VerticalLayout();
        mainContainer.setImmediate(false);
        mainContainer.setWidth("100.0%");
        mainContainer.setHeight("100.0%");
        mainContainer.setMargin(true);
        
        // menuSpacer
        menuSpacer = buildMenuSpacer();
        mainContainer.addComponent(menuSpacer);
        
        // globalFilterContainer
        globalFilterContainer = buildGlobalFilterContainer();
        mainContainer.addComponent(globalFilterContainer);
        mainContainer.setComponentAlignment(globalFilterContainer, new Alignment(48));
        
        // tbl_data
        tbl_data = new FilterTable();
        tbl_data.setImmediate(true);
        tbl_data.setWidth("100.0%");
        tbl_data.setHeight("100.0%");
        mainContainer.addComponent(tbl_data);
        mainContainer.setExpandRatio(tbl_data, 1.0f);
        mainContainer.setComponentAlignment(tbl_data, new Alignment(20));
        
        return mainContainer;
    }

    @AutoGenerated
    private VerticalLayout buildMenuSpacer() {
        // common part: create layout
        menuSpacer = new VerticalLayout();
        menuSpacer.setImmediate(false);
        menuSpacer.setWidth("100.0%");
        menuSpacer.setHeight("40px");
        menuSpacer.setMargin(false);
        
        // men_frm
        men_frm = new MenuBar();
        men_frm.setImmediate(false);
        men_frm.setWidth("100.0%");
        men_frm.setHeight("-1px");
        menuSpacer.addComponent(men_frm);
        menuSpacer.setComponentAlignment(men_frm, new Alignment(20));
        
        return menuSpacer;
    }

    @AutoGenerated
    private HorizontalLayout buildGlobalFilterContainer() {
        // common part: create layout
        globalFilterContainer = new HorizontalLayout();
        globalFilterContainer.setImmediate(false);
        globalFilterContainer.setWidth("100.0%");
        globalFilterContainer.setHeight("80px");
        globalFilterContainer.setMargin(false);
        
        // horizontalLayout_2
        horizontalLayout_2 = buildHorizontalLayout_2();
        globalFilterContainer.addComponent(horizontalLayout_2);
        globalFilterContainer.setComponentAlignment(horizontalLayout_2, new Alignment(48));
        
        // horizontalLayout_3
        horizontalLayout_3 = buildHorizontalLayout_3();
        globalFilterContainer.addComponent(horizontalLayout_3);
        globalFilterContainer.setComponentAlignment(horizontalLayout_3, new Alignment(48));
        
        return globalFilterContainer;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_2() {
        // common part: create layout
        horizontalLayout_2 = new HorizontalLayout();
        horizontalLayout_2.setImmediate(false);
        horizontalLayout_2.setWidth("-1px");
        horizontalLayout_2.setHeight("-1px");
        horizontalLayout_2.setMargin(false);
        horizontalLayout_2.setSpacing(true);
        
        // filterMonthEnabled
        filterMonthEnabled = new CheckBox();
        filterMonthEnabled.setCaption("Monatsfilter");
        filterMonthEnabled.setImmediate(false);
        filterMonthEnabled.setWidth("-1px");
        filterMonthEnabled.setHeight("-1px");
        horizontalLayout_2.addComponent(filterMonthEnabled);
        horizontalLayout_2.setComponentAlignment(filterMonthEnabled, new Alignment(48));
        
        // filterMonth
        filterMonth = new PopupDateField();
        filterMonth.setImmediate(false);
        filterMonth.setWidth("-1px");
        filterMonth.setHeight("-1px");
        horizontalLayout_2.addComponent(filterMonth);
        horizontalLayout_2.setComponentAlignment(filterMonth, new Alignment(48));
        
        return horizontalLayout_2;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_3() {
        // common part: create layout
        horizontalLayout_3 = new HorizontalLayout();
        horizontalLayout_3.setImmediate(false);
        horizontalLayout_3.setWidth("-1px");
        horizontalLayout_3.setHeight("-1px");
        horizontalLayout_3.setMargin(false);
        horizontalLayout_3.setSpacing(true);
        
        // filterStatusEnabled
        filterStatusEnabled = new CheckBox();
        filterStatusEnabled.setCaption("Statusfilter");
        filterStatusEnabled.setImmediate(false);
        filterStatusEnabled.setWidth("-1px");
        filterStatusEnabled.setHeight("-1px");
        horizontalLayout_3.addComponent(filterStatusEnabled);
        horizontalLayout_3.setComponentAlignment(filterStatusEnabled, new Alignment(48));
        
        // filterStatus
        filterStatus = new TwinColSelect();
        filterStatus.setImmediate(false);
        filterStatus.setWidth("-1px");
        filterStatus.setHeight("70px");
        horizontalLayout_3.addComponent(filterStatus);
        horizontalLayout_3.setComponentAlignment(filterStatus, new Alignment(48));
        
        return horizontalLayout_3;
    }
}
