package archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Prescriptions.PrescriptionManager.form;

import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map.Entry;

import org.joda.time.LocalDate;
import org.tepi.filtertable.FilterTable;

import archenoah.config.CMS_Config_Std;
import archenoah.lib.custom.MyUtils;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Tab_Menue_Item;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Window_Button;
import archenoah.lib.vaadin.Components.table.DataviewGenerator;
import archenoah.lib.vaadin.Components.table.FilteringTableUpdater;
import archenoah.lib.vaadin.CustomConverterFactorys.DataviewConverter;
import archenoah.lib.vaadin.CustomConverterFactorys.IntegerToBooleanConverter;
import archenoah.lib.vaadin.CustomConverterFactorys.StringSqlTimestampConverter;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalMessages;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.lib.vaadin.MenuBerechtigung.Rechteholen;
import archenoah.lib.vaadin.resources.Icons;
import archenoah.web.normal.UserInfo.Country;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Prescriptions.PrescriptionManager.classes.PrescriptionBalance;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Prescriptions.PrescriptionManager.classes.PrescriptionEntriesComponent;

import com.google.gwt.thirdparty.guava.common.base.Strings;
import com.vaadin.addon.tableexport.ExcelExport;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.event.UIEvents.PollEvent;
import com.vaadin.event.UIEvents.PollListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.shared.ui.datefield.Resolution;
import com.vaadin.ui.AbstractField;
import com.vaadin.ui.AbstractSelect.ItemDescriptionGenerator;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.Command;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;
import com.vaadin.ui.TwinColSelect;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.Window.CloseEvent;
import com.vaadin.ui.Window.CloseListener;

import de.steinwedel.messagebox.ButtonId;
import de.steinwedel.messagebox.MessageBoxListener;


public class PrescriptionManagerDataView extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
	private HorizontalLayout mainLayout;

	@AutoGenerated
	private VerticalLayout vl_main;

	@AutoGenerated
	private FilterTable tbl_data;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_4;

	@AutoGenerated
	private TwinColSelect filterProduct;

	@AutoGenerated
	private CheckBox filterUseProduct;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;

	@AutoGenerated
	private PopupDateField filterMonth;

	@AutoGenerated
	private CheckBox filterUseMonth;

	@AutoGenerated
	private VerticalLayout vl_menuSpacer;

	@AutoGenerated
	private MenuBar men_frm;

	

	

	

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */

    /**************** --> Allgemein <--- ********************/
	private static org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(PrescriptionManagerDataView.class);
	
	// Datenbank
    private FilteringTableUpdater tableUpdater = null;

    // Berrechtigung
    private int ACC_ID;

    private int permRead;
    private int permCreate;
    private int permUpdate;
    private int permDelete;

    private MenuItem tmpMenu = null;

    private Button tmpButton = null;
    /******************************************************/
    /**************** --> Tabsheetvars <--- *****************/
    private TabSheet tab = null;

    /******************************************************/
    /**************** --> Windowvars <--- *******************/
    private Window win = null;
    /******************************************************/

    private DetachListener onDetach = null;

    /******************* -> Menüpunkte <- ********************/
    private MenuBar.MenuItem btn_create;
    private MenuBar.MenuItem btn_update;
    private MenuBar.MenuItem btn_read;
    private MenuBar.MenuItem btn_delete;
    private MenuBar.MenuItem btn_filter;
    private MenuBar.MenuItem btn_export;

    
    /*******************************************************/
    /******************* --> Custom <--- ********************/
    /******************************************************/

    private Boolean firstFilter = true;
    private PollListener pollListener = null;
    
    enum Status {}
    enum Project {}
    
    /************ ----->Einstellungen<-- ********************/
//    private final String formIdLng = "201";
    private final String formIdPerm = "201";
    private final String winHeight = "600px";
    private final String winWidth = "900px";


    /******************************************************/

    private final String tableIdCol = "PL_ID";
    
    //TASK cols
    private final Object[] tableColsAll = new Object[] { "PL_ID", "PL_CREATED", "patient", "nurse", "user", "PL_DATE", "PL_BOOKING",
            "PL_NR", "PL_STATUS", "PL_FIRM", "PL_NO_FEE", "PL_COMMENT", "checked"};
    private final Object[] tableColsExport = new Object[] { "PL_ID", "PL_CREATED", "patient", "nurse", "user", "PL_DATE", "PL_BOOKING",
            "PL_NR", "PL_STATUS", "PL_FIRM", "PL_NO_FEE", "PL_COMMENT", "checked"};
    //use custom Cols when needed
    private Object[] tableColsDefault = new Object[] { "PL_ID", "PL_CREATED", "patient", "nurse", "user", "PL_DATE", "PL_BOOKING", "checked"};
    //use custom Cols when needed
    private final Object[] tableColsFilter = tableColsDefault;
    private Object[] tableColsActive = tableColsDefault;
    
    private StringSqlTimestampConverter dateConverter;
    private StringSqlTimestampConverter timeConverter;

    private I18nManager i18n;
    
    /******************************************************/

    public PrescriptionManagerDataView(MenuItem Arg_Menü) {
        tmpMenu = Arg_Menü;
    }

    public PrescriptionManagerDataView(Button Arg_btn) {
        tmpButton = Arg_btn;
    }

    /***************************** ---> Feste Funtionen<--- **************************************/

    /********* INIT-Window ************/
    public void init() {

        Standard_Init();

        if (tmpMenu != null) {
            String Recourcename = tmpMenu.getIcon().toString();
            Recourcename = Recourcename.substring(0, Recourcename.length() - 12) + "white-16.png";

            Build_Window_Button bwb = new Build_Window_Button(tmpMenu.getText(), mainLayout, winHeight, winWidth,
                    new ThemeResource(Recourcename));
            win = bwb.ReturnWindow();
        }
        if (tmpButton != null) {
            Build_Window_Button bwb = new Build_Window_Button(tmpButton.getCaption(), mainLayout, winHeight, winWidth,
                    tmpButton.getIcon());
            win = bwb.ReturnWindow();
        }

        win.addDetachListener(onDetach);

    }
    
    public Window getWindow(){
    	return win;
    }
    
    public TabSheet getTabSheet(){
    	return tab;
    }
    
    public void init(TabSheet Arg_tab) {

        Standard_Init();
        tab = Arg_tab;
        if (tmpMenu != null) {
            Build_Tab_Menue_Item bt = new Build_Tab_Menue_Item(Arg_tab, tmpMenu.getText(), mainLayout, tmpMenu.getIcon());
        }
        if (tmpButton != null) {
            Build_Tab_Menue_Item bt = new Build_Tab_Menue_Item(Arg_tab, tmpButton.getCaption(), mainLayout, tmpButton.getIcon());
        }

        tab.getSelectedTab().addDetachListener(onDetach);
    }

    /********* Init-Standard ************/
    private void Standard_Init() {
        buildMainLayout();
        i18n = new I18nManager(this);

        generateMenu();
        
        setMenuPermissions();

        tbl_data.setSortContainerPropertyId(tableIdCol);
        tbl_data.setSortAscending(true);
        tbl_data.sort();
        configureTable();
        configureComponents();

        setGlobalFilterMonth();
        
        setupListenersAndDetachEvent();
        i18n.refresh();
    }

    private void setupListenersAndDetachEvent() {
        pollListener = new PollListener() {

            @Override
            public void poll(PollEvent event) {
                if(tab.isRendered(mainLayout)){
                    updateTable();
                }
            }
        };

        UI.getCurrent().getUI().addPollListener(pollListener);

        onDetach = new DetachListener() {

            @Override
            public void detach(DetachEvent event) {
                UI.getCurrent().getUI().removePollListener(pollListener);
            }
        };
    }
    
    public void setGlobalFilterMonth(Date date){
        LocalDate ld = new LocalDate(date);
        filterUseMonth.setValue(true);
        filterMonth.setValue(new LocalDate(ld.getYear(), ld.getMonthOfYear(), 1).toDate());
    }
    
    public void setGlobalFilterMonth(){
        setGlobalFilterMonth(new Date());
    }
    
    @SuppressWarnings("unused")
    public void setPermissionsFromDatabase() {
        if (formIdPerm == "") {
            System.out.println("Form Einstellung Fehlt: Berechtigung");
            return;
        }

        ACC_ID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        Rechteholen r = new Rechteholen(ACC_ID + "");
        String[][] perms = r.Datenholen();

        for (int i = 0; i < perms.length; i++) {
            if (perms[i][0].equals(formIdPerm) == true) {

                permRead = Integer.valueOf(perms[i][3]);
                permUpdate = Integer.valueOf(perms[i][4]);
                permCreate = Integer.valueOf(perms[i][6]);
                permDelete = Integer.valueOf(perms[i][5]);
                
            }
        }
    }

    public void setPermissions(int create, int read, int update, int delete) {

        permCreate = create;
        permRead = read;
        permUpdate = update;
        permDelete = delete;

    }

    private void setMenuPermissions() {
        Boolean c = (permCreate == 1);
        Boolean r = (permRead == 1);
        Boolean u = (permUpdate == 1);
        Boolean d = (permDelete == 1);

        btn_create.setEnabled(c);
        btn_create.setVisible(c);

        btn_read.setEnabled(r);
        btn_read.setVisible(r);

        btn_update.setEnabled(u);
        btn_update.setVisible(u);

        btn_delete.setEnabled(d);
        btn_delete.setVisible(d);
    }

    /************ -><- ******************/

    /***************** Comands *********************/
    
    CloseListener closeListener = new CloseListener() {
		
		@Override
		public void windowClose(CloseEvent e) {
			updateTable(true);
		}
	};
    
    //TASK Commands are here
    public Command cmd_btn_add = new Command() {
        @Override
        public void menuSelected(MenuItem selectedItem) {
        
        	PrescriptionManagerInsertEdit pie = new PrescriptionManagerInsertEdit(selectedItem, "");
        	pie.setPermissions(permCreate, permRead, permUpdate, permDelete);
        	pie.init();
        	pie.getWindow().addCloseListener(closeListener);
        	
        }
    };
    
    public Command cmd_btn_read = new Command() {
        @Override
        public void menuSelected(MenuItem selectedItem) {

            if(tbl_data.getValue() == null){
                I18nManager.global(I18nGlobalNotifiers.no_entry_selected);
                return;
            }
            
            String id = Integer.toString((Integer) tbl_data.getContainerProperty(tbl_data.getValue(), tableIdCol).getValue());
            PrescriptionManagerInsertEdit pie = new PrescriptionManagerInsertEdit(selectedItem, id);
        	pie.setPermissions(0, permRead, 0, 0);
        	pie.init();

        }
    };
    
    public Command cmd_btn_edit = new Command() {
        @Override
        public void menuSelected(MenuItem selectedItem) {
            
            if(tbl_data.getValue() == null){
                I18nManager.global(I18nGlobalNotifiers.no_entry_selected);
                return;
            }
            
            String id = Integer.toString((Integer) tbl_data.getContainerProperty(tbl_data.getValue(), tableIdCol).getValue());
            PrescriptionManagerInsertEdit pie = new PrescriptionManagerInsertEdit(selectedItem, id);
        	pie.setPermissions(permCreate, permRead, permUpdate, permDelete);
        	pie.init();
        	pie.getWindow().addCloseListener(closeListener);
            
        }
    };

    public Command cmd_btn_del = new Command() {
        @Override
        public void menuSelected(MenuItem selectedItem) {
            
            if(tbl_data.getValue() == null){
                I18nManager.global(I18nGlobalNotifiers.no_entry_selected);
                return;
            }
            
            Integer id = (Integer) tbl_data.getContainerProperty(tbl_data.getValue(), tableIdCol).getValue();
            deleteData(id);

        }
    };

    public Command cmd_btn_filter = new Command() {
        @Override
        public void menuSelected(MenuItem selectedItem) {

            if (firstFilter) {
                tbl_data.setFilterBarVisible(true);
                tbl_data.setFilterBarVisible(false);
                firstFilter = false;
            }
            tbl_data.setFilterBarVisible(!tbl_data.isFilterBarVisible());
            
            if(!tbl_data.isFilterBarVisible()){
                tbl_data.clearFilters();
            }
            
            tableColsActive = tbl_data.isFilterBarVisible() ? tableColsFilter : tableColsDefault;
            if(tbl_data.size() >0 ) {
                tbl_data.setVisibleColumns(tableColsActive);
            }

        }
    };
    
    public Command cmd_btn_export = new Command() {
        @Override
        public void menuSelected(MenuItem selectedItem) {

            Table tbl = new Table();
            tbl.setVisible(false);
            tbl.setContainerDataSource(tbl_data);
            tbl.setColumnCollapsingAllowed(true);

            mainLayout.addComponent(tbl);
            
            for (String col : tbl.getColumnHeaders()) {
                tbl.setColumnCollapsed(col, true);
            }
            
            for (Object col : tableColsExport) {
                tbl.setColumnCollapsed(col, false);
                tbl.setColumnHeader(col, i18n.get((String) col));
            }
            
            ExcelExport excelExport = new ExcelExport(tbl);
            
            
            
            excelExport.excludeCollapsedColumns();
            excelExport.setReportTitle("Rezeptverwaltung Export");
            excelExport.setExportFileName("Rezeptverwaltung-Export.xls");

            excelExport.export();
            mainLayout.removeComponent(tbl);

        }
    };

    /******************************************/

    
    

    /*********** Gen Menüs *************/
    private void generateMenu() {

        btn_create = men_frm.addItem("FRM_ADD", Icons.White.add_16, cmd_btn_add);
        btn_update = men_frm.addItem("FRM_EDIT", Icons.White.edit_16, cmd_btn_edit);
        btn_read = men_frm.addItem("FRM_READ", Icons.White.perm_lesen_16, cmd_btn_read);
        btn_delete = men_frm.addItem("FRM_DEL", Icons.White.delete_16, cmd_btn_del);
        
        btn_filter = men_frm.addItem("FRM_FILTER", Icons.White.filter_16, cmd_btn_filter);
        
        btn_export = men_frm.addItem("FRM_EXPORT", Icons.White.log_16, cmd_btn_export);

    }
    
    private void configureComponents(){
       
    	 // MONTHPICKER
        filterUseMonth.setValue(false);
        filterUseMonth.setImmediate(true);
        filterMonth.setResolution(Resolution.MONTH);
        filterMonth.setDateFormat("MMM yyyy");
        filterMonth.setEnabled(false);
        
        filterUseMonth.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                Boolean enabled = (Boolean)event.getProperty().getValue();
                filterMonth.setEnabled(enabled);
                if(enabled && filterMonth.getValue() == null){
                    LocalDate ld = new LocalDate();
                    filterMonth.setValue(new LocalDate(ld.getYear(), ld.getMonthOfYear(), 1).toDate());
                }else if(!enabled){
                    filterMonth.setValue(null);
                }
                
            }
        });
        
        filterMonth.setImmediate(true);
        filterMonth.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                updateTable(true);
                
            }
        });
        
        // STATUSPICKER
        //TASK status
        filterUseProduct.setValue(false);
        filterUseProduct.setImmediate(true);
        filterProduct.setContainerDataSource(dbGetProducts());
        filterProduct.setItemCaptionPropertyId("PP_PRODUCT");

        
        filterUseProduct.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                Boolean enabled = (Boolean)event.getProperty().getValue();
                filterProduct.setEnabled(enabled);
                updateTable(true);
                
            }
        });
        
        filterProduct.setImmediate(true);
        filterProduct.setEnabled(false);
        filterProduct.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                               
                updateTable(true);
                
            }
        });
        
    }
    
    private ArrayList<AbstractField> getActiveGlobalFilters(){
        ArrayList<AbstractField> al = new ArrayList<AbstractField>();
        
        if(filterMonth.getValue() != null){
            al.add(filterMonth);
        }
        
        if(filterUseProduct.getValue() && ((Collection) filterProduct.getValue()).size() > 0){
            al.add(filterProduct);
        }
        
        return al;
    }
    
    private Boolean hasGlobalFilters(ArrayList a){
        
        return (a.size() > 0);
        
    }
    
    private Boolean hasGlobalFilters(){
        
        return hasGlobalFilters(getActiveGlobalFilters());
        
    }
    
    /*************************** Config TBL ********************/

    private void configureTable() {
        tbl_data.setSelectable(true);
        tbl_data.setFilterOnDemand(false);
        tbl_data.setImmediate(true);
        tbl_data.setColumnCollapsingAllowed(false);
        tbl_data.setFooterVisible(true);
        tbl_data.setPageLength(1);
        tbl_data.setColumnCollapsingAllowed(true);
//        try {
////        	tbl_data.setVisibleColumns(tableColsDefault);
//        	tbl_data.setColumnCollapsed("PL_FILED", true);
//        	tbl_data.setColumnCollapsed("PL_FILED_DATE", true);
//		} catch (Exception e) {
//		    e.printStackTrace();
//		}

        tbl_data.setItemDescriptionGenerator(new ItemDescriptionGenerator() {
            
            @Override
            public String generateDescription(Component source, Object itemId, Object propertyId) {
                return MyUtils.getValueFromItem(tbl_data.getItem(itemId), "description", String.class);
            }
        });
        
        tbl_data.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                toggleMenuItems();
            }
        });
        
        tableUpdater = new FilteringTableUpdater(tbl_data);

    }
    
    private void toggleMenuItems() {
        
        Item item = tbl_data.getItem(tbl_data.getValue());
        btn_update.setEnabled(MyUtils.equalsWithNulls(MyUtils.getValueFromItem(item, "checked", Integer.class), 0));
        
    }
    
    /*************************** Database ********************/
    
    /********************************/
    
    private void updateTable(){
        updateTable(false);
    }
    
    private void updateTable(Boolean ignoreFilter) {

        if (ignoreFilter || !tbl_data.isFilterBarVisible()) {
            
            
            
            if(dateConverter == null) {
                
                for (Object col : tableColsDefault) {
                    tbl_data.addContainerProperty(col, Object.class, null);
                }
                
                dateConverter = new StringSqlTimestampConverter();
                dateConverter.setDateFormat(DateFormat.SHORT);
                
                timeConverter = new StringSqlTimestampConverter();
                timeConverter.setDateFormat(DateFormat.SHORT);
                timeConverter.setTimeFormat(DateFormat.SHORT);
                
                tbl_data.setConverter("PL_CREATED", timeConverter);
                tbl_data.setConverter("PL_DATE", dateConverter);
                tbl_data.setConverter("PL_BOOKING", dateConverter);
                tbl_data.setConverter("checked", new IntegerToBooleanConverter());
             
                HashMap<String, DataviewConverter> converterMap = new HashMap<String, DataviewConverter>();
                converterMap.put("checked", new IntegerToBooleanConverter());
                
                new DataviewGenerator(converterMap).attach(tbl_data);
                
            }
            
            dbGetContainer();
            try{
                if(tableColsDefault.length > 0){
                    tbl_data.setVisibleColumns(tableColsActive);
                }
            }catch(Exception e){
                
            }
            
        }
        
        tbl_data.setColumnFooter("Status", "Σ " + tbl_data.size());
        
    }
    
    private void deleteData(final Integer id){
            
        I18nManager.global(I18nGlobalMessages.confirm_delete, new MessageBoxListener() {
            
            @Override
            public void buttonClicked(ButtonId arg0) {
                if(ButtonId.YES == arg0) {
                    Item item = tbl_data.getContainerDataSource().getItem(tbl_data.getValue());
                    
                    // only remove balance if entry was checked
                    boolean doDelete = MyUtils.getValueFromItem(item, "PL_CHECKED_DATE", Date.class) == null;
                    
                    if(!doDelete) {
                        doDelete = deleteBalance(MyUtils.getValueFromItem(item, "PL_ID_PATIENT", Integer.class),
                            MyUtils.getValueFromItem(item, "PL_ID", Integer.class));
                    }
                    
                    if(doDelete) {
                        dbDeleteData(Integer.toString(id));
                    }
                }
            }
        });
    }
    
    private boolean deleteBalance(Integer pid, Integer id) {

        
        PrescriptionEntriesComponent entries = new PrescriptionEntriesComponent();
        entries.setParentId(id);
        IndexedContainer con = entries.getContainer();
        
        PrescriptionBalance balance = new PrescriptionBalance();
        balance.setPatientId(pid);
        
        HashMap<Integer, Integer> deltas = new HashMap<Integer, Integer>();
        
        for (Object iid : con.getItemIds()) {
            
            Item insertItem = con.getItem(iid);
            
            Integer product = MyUtils.getValueFromItem(insertItem, "PLE_ID_PRODUCT", Integer.class);
            Integer quantity = MyUtils.getValueFromItem(insertItem, "PLE_QUANTITY", Integer.class);
            deltas.put(product, (-1 * quantity) + (deltas.get(product) != null ? deltas.get(product) : 0));
            
        }
        
        log.info("deltas: {}", deltas);
        for (Entry<Integer, Integer> delta : deltas.entrySet()) {
            balance.editBalance(delta.getKey(), delta.getValue(), PrescriptionBalance.PRESCRIPTION, null, id+"");
        }
        return true;
        
    }
    
    private Container dbGetProducts(){
    	CMS_Config_Std std = CMS_Config_Std.getInstance();
    	DBClass db = new DBClass();
        
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_prescriptions_products");
        
//        if(project.getValue() != null){
//        	db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_prescriptions_products", "PP_ID_PROJECT", "=", getSelectedProjectId(), "");
//        }
        
        return db.DB_Data_Get.DB_SEND_AND_GET_Container();
    }
    
    //TASK dbget
    
    private void dbGetContainer() {
        CMS_Config_Std std = CMS_Config_Std.getInstance();

        DBClass db = new DBClass();

        /************ Set Spalten *************/
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("*");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(PSL_NAME,', ',PSL_VORNAME, ', ', PSA_NAME,' ',PSL_TITEL)", "patient");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(KSK_TITEL,' ', KSA_NAME,' ',nurse.AUL_NAME,', ',nurse.AUL_VORNAME)", "nurse");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(ASA_NAME, ' ', user.AUL_NAME, ', ', user.AUL_VORNAME)", "user");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("GROUP_CONCAT(CONCAT_WS('', PP_PRODUCT, ' ', PLE_QUANTITY, CONCAT(' (', PPS_NAME, '-', PPS_SIZE , ' x ', PLE_SIZE_COUNT, ')' ) ) SEPARATOR '<br />')", "description");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("PL_CHECKED_DATE IS NOT NULL", "checked");
//        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT_WS(', ', checked_user.AUL_NAME, checked_user.AUL_VORNAME)", "checkedUser");
        /**************************************/
        /************ Set Tabelle *************/
//        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_prescriptions_list", "LEFT JOIN", "cust_prescriptions_products", "PL_ID_PRODUCT", "PP_ID");
        
        
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_prescriptions_list", "LEFT JOIN", "cust_prescriptions_list_entries", "PL_ID", "PLE_PL_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_prescriptions_list_entries", "RIGHT /*a*/ JOIN", "cust_prescriptions_products", "PLE_ID_PRODUCT", "PP_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_prescriptions_list_entries", "RIGHT /*b*/ JOIN", "cust_prescription_product_sizes", "PLE_ID_SIZE", "PPS_ID");
        
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_prescriptions_list", "INNER JOIN", "cust_patient_stammdaten_liste", "PL_ID_PATIENT", "PSL_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_patient_stammdaten_liste", "INNER JOIN", "cust_patient_stammdaten_anrede", "PSL_ANREDE", "PSA_ID");

        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_prescriptions_list", "RIGHT /*1*/ JOIN", "cust_krankenschwester_stammdaten_ks", "PL_ID_NURSE", "KSK_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung_Graph("LEFT /*2*/ JOIN", "cms_auth_stammdaten_user as nurse", "nurse", "cust_krankenschwester_stammdaten_ks", "AUL_ID", "KSK_U_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung_Graph("LEFT /*3*/ JOIN", "cust_krankenschwester_stammdaten_anrede", "cust_krankenschwester_stammdaten_anrede", "nurse", "KSA_ID", "AUL_ANREDE_ID");
       
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung_Graph("LEFT /*4*/ JOIN", "cms_auth_stammdaten_user as user", "user", "cust_prescriptions_list", "AUL_ID", "PL_ID_USER");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung_Graph("   LEFT /*5*/ JOIN", "cms_auth_stammdaten_anrede", "cms_auth_stammdaten_anrede", "user", "ASA_ID", "AUL_ANREDE_ID");

        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung_Graph("LEFT /*6*/ JOIN", "cms_auth_stammdaten_user as checked_user", "checked_user", "cust_prescriptions_list", "AUL_ID", "PL_CHECKED_ID_USER");
        
        //
//        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_prescriptions_list", "INNER JOIN", "cust_projekte_stammdaten_liste", "PL_ID_PROJECT", "PSLV_ID");
        
        /**************************************/
        /************ Set Filter *************/
            
        String glue = "";
        
        ArrayList<AbstractField> filterList = getActiveGlobalFilters(); 
        
        Country uc = MyUtils.getUserData().getCountry();
        if(uc.hasPermissions()) {
            db.DB_Data_Get.DB_Filter.DB_WHERE_In("cust_patient_stammdaten_liste", "PSL_COUNTYCODE", uc.getFilterString(), hasGlobalFilters(filterList) ? "AND" : "");
        }
        
        if(filterMonth.getValue() != null){
            
            java.sql.Timestamp sqlDateFrom = new java.sql.Timestamp(filterMonth.getValue().getTime());
            java.sql.Timestamp sqlDateUntil = new java.sql.Timestamp(new LocalDate(filterMonth.getValue()).plusMonths(1).minusDays(1).toDate().getTime());
            
            filterList.remove(filterMonth);
            glue = hasGlobalFilters(filterList) ? "AND" : "";
            
            db.DB_Data_Get.DB_Filter.DB_WHERE_BETWEEN("cust_prescriptions_list", "PL_DATE", "'" + sqlDateFrom.toString() + "'",  "'" + sqlDateUntil.toString() + "'", glue);
        }
        
        if(filterUseProduct.getValue() && ((Collection) filterProduct.getValue()).size() > 0){
            
            filterList.remove(filterProduct);
            glue = hasGlobalFilters(filterList) ? "AND" : "";

            //TASK das muss anders einfacher gehen...
            HashSet<Integer> getIds = new HashSet<Integer>();
            for (Integer value : (Collection<Integer>)filterProduct.getValue()) {
                getIds.add((Integer) filterProduct.getContainerProperty(value, "PP_ID").getValue());
            }
            
            db.DB_Data_Get.DB_Filter.DB_WHERE_In("cust_prescriptions_list_entries", "PLE_ID_PRODUCT", generateCollectionString(getIds), glue);
        }
            

        /**************************************/
        
        db.DB_Data_Get.DB_Gruppieren.DB_Gruppieren("PL_ID");
        
        /**************************************/
        /************ Set Custom *************/
        /**************************************/

//        db.DB_Data_Get.Set_Type("PSLV_NAME", Project.class);
        
        /* **************************/
        
//        db.debugNextQuery(true);
        
        try {
        	Container container = db.DB_Data_Get.DB_SEND_AND_GET_Container();
            
        	if (tableUpdater != null) {
                tableUpdater.updateTable(container);
            } else {
                tbl_data.setContainerDataSource(container);
            }
        	
		} catch (Exception e) {
			// TASK: handle exception
			e.printStackTrace();
			UI.getCurrent().getUI().removePollListener(pollListener);
		}
        
    }
    
    private String generateCollectionString(Collection<Integer> ids){
        String in = "";
        String comma = "";
        
        for (Integer integer : ids) {
            in += comma + integer;
            if(Strings.isNullOrEmpty(comma)){
                comma = ", ";
            }
        }
        
        return in;
    }
    
    private void dbDeleteData(String id){
    
        CMS_Config_Std std = CMS_Config_Std.getInstance();
    
        DBClass db = new DBClass();
        db.DB_Data_Delete.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_prescriptions_list");
        db.DB_Data_Delete.DB_Filter.DB_WHERE_Allgemein("cust_prescriptions_list", tableIdCol, "=", id, "");
        db.DB_Data_Delete.DB_Delete();
    
        I18nManager.global(I18nGlobalNotifiers.entry_deleted);
        
        updateTable(true);

        
    }
    
    @AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// vl_main
		vl_main = buildVl_main();
		mainLayout.addComponent(vl_main);
		mainLayout.setExpandRatio(vl_main, 1.0f);
		mainLayout.setComponentAlignment(vl_main, new Alignment(20));
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVl_main() {
		// common part: create layout
		vl_main = new VerticalLayout();
		vl_main.setImmediate(false);
		vl_main.setWidth("100.0%");
		vl_main.setHeight("100.0%");
		vl_main.setMargin(true);
		
		// vl_menuSpacer
		vl_menuSpacer = buildVl_menuSpacer();
		vl_main.addComponent(vl_menuSpacer);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		vl_main.addComponent(horizontalLayout_2);
		vl_main.setComponentAlignment(horizontalLayout_2, new Alignment(48));
		
		// tbl_data
		tbl_data = new FilterTable();
		tbl_data.setImmediate(true);
		tbl_data.setWidth("100.0%");
		tbl_data.setHeight("100.0%");
		vl_main.addComponent(tbl_data);
		vl_main.setExpandRatio(tbl_data, 1.0f);
		vl_main.setComponentAlignment(tbl_data, new Alignment(20));
		
		return vl_main;
	}

	@AutoGenerated
	private VerticalLayout buildVl_menuSpacer() {
		// common part: create layout
		vl_menuSpacer = new VerticalLayout();
		vl_menuSpacer.setImmediate(false);
		vl_menuSpacer.setWidth("100.0%");
		vl_menuSpacer.setHeight("40px");
		vl_menuSpacer.setMargin(false);
		
		// men_frm
		men_frm = new MenuBar();
		men_frm.setImmediate(false);
		men_frm.setWidth("100.0%");
		men_frm.setHeight("-1px");
		vl_menuSpacer.addComponent(men_frm);
		vl_menuSpacer.setComponentAlignment(men_frm, new Alignment(20));
		
		return vl_menuSpacer;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("100.0%");
		horizontalLayout_2.setHeight("80px");
		horizontalLayout_2.setMargin(false);
		
		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		horizontalLayout_2.addComponent(horizontalLayout_3);
		horizontalLayout_2.setComponentAlignment(horizontalLayout_3,
				new Alignment(48));
		
		// horizontalLayout_4
		horizontalLayout_4 = buildHorizontalLayout_4();
		horizontalLayout_2.addComponent(horizontalLayout_4);
		horizontalLayout_2.setComponentAlignment(horizontalLayout_4,
				new Alignment(48));
		
		return horizontalLayout_2;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("-1px");
		horizontalLayout_3.setHeight("-1px");
		horizontalLayout_3.setMargin(false);
		horizontalLayout_3.setSpacing(true);
		
		// filterUseMonth
		filterUseMonth = new CheckBox();
		filterUseMonth.setCaption("Monatsfilter");
		filterUseMonth.setImmediate(false);
		filterUseMonth.setWidth("-1px");
		filterUseMonth.setHeight("-1px");
		horizontalLayout_3.addComponent(filterUseMonth);
		horizontalLayout_3.setComponentAlignment(filterUseMonth, new Alignment(
				48));
		
		// filterMonth
		filterMonth = new PopupDateField();
		filterMonth.setImmediate(false);
		filterMonth.setWidth("-1px");
		filterMonth.setHeight("-1px");
		horizontalLayout_3.addComponent(filterMonth);
		horizontalLayout_3
				.setComponentAlignment(filterMonth, new Alignment(48));
		
		return horizontalLayout_3;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_4() {
		// common part: create layout
		horizontalLayout_4 = new HorizontalLayout();
		horizontalLayout_4.setImmediate(false);
		horizontalLayout_4.setWidth("-1px");
		horizontalLayout_4.setHeight("-1px");
		horizontalLayout_4.setMargin(false);
		horizontalLayout_4.setSpacing(true);
		
		// filterUseProduct
		filterUseProduct = new CheckBox();
		filterUseProduct.setCaption("Medikamentfilter");
		filterUseProduct.setImmediate(false);
		filterUseProduct.setWidth("-1px");
		filterUseProduct.setHeight("-1px");
		horizontalLayout_4.addComponent(filterUseProduct);
		horizontalLayout_4.setComponentAlignment(filterUseProduct,
				new Alignment(48));
		
		// filterProduct
		filterProduct = new TwinColSelect();
		filterProduct.setImmediate(false);
		filterProduct.setWidth("-1px");
		filterProduct.setHeight("60px");
		horizontalLayout_4.addComponent(filterProduct);
		horizontalLayout_4.setComponentAlignment(filterProduct, new Alignment(
				48));
		
		return horizontalLayout_4;
	}
}
