package archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Prescriptions.PrescriptionManager.form;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;

import org.joda.time.LocalDate;

import archenoah.config.CMS_Config_Std;
import archenoah.lib.custom.ComponentIterator;
import archenoah.lib.custom.MyUtils;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.tool.comunication.dbclass.DBClass.CustomQuery;
import archenoah.lib.vaadin.Components.Combo.combo;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Tab_Menue_Item;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Window_Button;
import archenoah.lib.vaadin.Forms_Builder.Form_Bind;
import archenoah.lib.vaadin.Language.i18n.I18nCB;
import archenoah.lib.vaadin.Language.i18n.I18nConverter;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.lib.vaadin.MenuBerechtigung.Rechteholen;
import archenoah.lib.vaadin.valchecker.val_checker4;
import archenoah.web.normal.UserInfo.Country;
import archenoah.web.normal.UserInfo.UserData;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Prescriptions.PrescriptionManager.classes.PrescriptionBalance;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Prescriptions.PrescriptionManager.classes.PrescriptionEntriesComponent;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.classes.ProjectNurseCombos;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Container.Filter;
import com.vaadin.data.Container.ItemSetChangeEvent;
import com.vaadin.data.Container.ItemSetChangeListener;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.server.ThemeResource;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.shared.ui.datefield.Resolution;
import com.vaadin.ui.AbstractField;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

public class PrescriptionManagerInsertEdit extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private VerticalLayout mainLayout;

    @AutoGenerated
    private HorizontalLayout buttons;

    @AutoGenerated
    private Button btn_save;

    @AutoGenerated
    private VerticalLayout main;

    @AutoGenerated
    private Panel prescriptionPanel;

    @AutoGenerated
    private VerticalLayout verticalLayout_3;

    @AutoGenerated
    private TabSheet tabs;

    @AutoGenerated
    private PrescriptionEntriesComponent prescriptionEntries;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_1;

    @AutoGenerated
    private VerticalLayout verticalLayout_5;

    @AutoGenerated
    private TextArea comment;

    @AutoGenerated
    private CheckBox noFees;

    @AutoGenerated
    private ComboBox status;

    @AutoGenerated
    private VerticalLayout verticalLayout_4;

    @AutoGenerated
    private ComboBox nurse;

    @AutoGenerated
    private ComboBox patient;

    @AutoGenerated
    private TextField number;

    @AutoGenerated
    private PopupDateField date;

    @AutoGenerated
    private Panel systemPanel;

    @AutoGenerated
    private VerticalLayout verticalLayout_2;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_8;

    @AutoGenerated
    private VerticalLayout verticalLayout_7;

    @AutoGenerated
    private PopupDateField booking;

    @AutoGenerated
    private TextField checked_user;

    @AutoGenerated
    private ComboBox user;

    @AutoGenerated
    private VerticalLayout verticalLayout_6;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_7;

    @AutoGenerated
    private PopupDateField updated;

    @AutoGenerated
    private PopupDateField created;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_6;

    @AutoGenerated
    private PopupDateField checked_date;

    @AutoGenerated
    private CheckBox checked;

    @AutoGenerated
    private ComboBox project;

    

    

    

    

    

    

    

    

    

//    @AutoGenerated
//    private ComboBox firm;

    

    

    

    

    

    

    

    

    

    

    

    

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */

    /**************** --> Allgemein <--- ********************/
    
    private static org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(PrescriptionManagerInsertEdit.class);
    
    // Allgemein
    private CMS_Config_Std std;
    private String exportCaption;
    
    // Datenbank
    private Map<Object, String> componentMap;
    private Map<Object, String> dbMap;
    private Map<Object, String> validateMap;
    private Form_Bind fb;
    private String dataSetId = "";

    
    // Berrechtigung
    private int ACC_ID;
	private Integer permRead;
	private Integer permUpdate;
	private Integer permCreate;
	private Integer permDelete;

    private MenuItem tmpMenu = null;
    private Button tmpButton = null;
    /******************************************************/
    /**************** --> Tabsheetvars <--- *****************/
    private TabSheet tab = null;
    /******************************************************/
    /**************** --> Windowvars <--- *******************/
    private Window win = null;
    /******************************************************/
    /******************* --> Custom <--- ********************/
    /******************************************************/
    
    private Map<Object, String> disabledMap;
    
    /************ ----->Einstellungen<-- ********************/
//    private final String formIdLng = "202";
    private final String formIdPerm = "202";
    private final String Windows_Height = "580px";
    private final String Windows_Width = "500px";
    
    private final String dataIdCol = "PL_ID";

    private I18nManager i18n;

    private Item dataSetItem;
    
    private final static class caption extends I18nCB {
        static final I18nCB firm_auto = set();
    }
    
    /******************************************************/

    public PrescriptionManagerInsertEdit(MenuItem Arg_Menü, String Arg_Form_ID) {
        tmpMenu = Arg_Menü;
        dataSetId = Arg_Form_ID;
    }

    public PrescriptionManagerInsertEdit(Button Arg_btn, String Arg_Form_ID) {
        tmpButton = Arg_btn;
        dataSetId = Arg_Form_ID;
    }

    /********* INIT-Window ************/
    public void init() {
        if (Windows_Height.equals("") == true || Windows_Width.equals("") == true) {
            System.out.println("Form Einstellung Fehlt: !!!");
            return;
        }

        Standard_Init();

        String fid = dataSetId;
        if (fid != "") {
            fid = " - #" + fid;
        }

        if (tmpMenu != null) {
        	
            String Recourcename = null;
            ThemeResource resource = null;
            if(tmpMenu.getIcon() != null){
            	Recourcename = tmpMenu.getIcon().toString();
            	Recourcename = Recourcename.substring(0, Recourcename.length() - 12) + "white-16.png";
            	resource = new ThemeResource(Recourcename);
            }

            exportCaption = tmpMenu.getText();
            Build_Window_Button bwb = new Build_Window_Button(tmpMenu.getText() + fid, mainLayout, Windows_Height, Windows_Width, resource);
            win = bwb.ReturnWindow();
        }
        if (tmpButton != null) {
            exportCaption = tmpButton.getCaption();
            Build_Window_Button bwb = new Build_Window_Button(tmpButton.getCaption() + fid, mainLayout, Windows_Height, Windows_Width, tmpButton.getIcon());
            win = bwb.ReturnWindow();
        }

    }

    /********* INIT-Tray ************/
    public void init(TabSheet Arg_tab) {

        Standard_Init();
        tab = Arg_tab;
        if (tmpMenu != null) {
            exportCaption = tmpMenu.getText();
            Build_Tab_Menue_Item bt = new Build_Tab_Menue_Item(Arg_tab, tmpMenu.getText(), mainLayout, tmpMenu.getIcon());
        }
        if (tmpButton != null) {
            exportCaption = tmpButton.getCaption();
            Build_Tab_Menue_Item bt = new Build_Tab_Menue_Item(Arg_tab, tmpButton.getCaption(), mainLayout, tmpButton.getIcon());
        }

    }
    
    public Window getWindow(){
    	return win;
    }
    
    public TabSheet getTabSheet(){
    	return tab;
    }
    
    /********* Init-Standard ************/
    private void Standard_Init() {
        buildMainLayout();
        i18n = new I18nManager(this);
        
        std = CMS_Config_Std.getInstance();
        fb = new Form_Bind();
        ACC_ID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        
        registerComponents();
        
        fillFields();
        fillDbMap();

        setCustomValidators();
        fillValidateMap();

        /***************/

        if (dataSetId != "") {
        	
            dbFillForm();
            fillNurses();
            
            prescriptionEntries.setParentId(Integer.parseInt(dataSetId));
            
            limitDatePickers(created.getValue());
            
        } else {
            
        	//TASK "create init"
        	user.setValue(ACC_ID);
            limitDatePickers(new Date());
        }

        setMenuPermissions();
        configureComponents();
        
        setEventListeners();
        
    }
    
 // register components for lng and validation tools
    private void registerComponents(){
    	componentMap = new HashMap<Object, String>();
        new ComponentIterator(main).createMap(componentMap);
    }

    
    private void configureComponents(){
    	
    	for (Entry<Object, String> entry : componentMap.entrySet()) {
    		AbstractField field = (AbstractField) entry.getKey();
    		
			field.setImmediate(true);
			
			
			if(field instanceof ComboBox){
				((ComboBox)field).setFilteringMode(FilteringMode.CONTAINS);
			}
			
			if(!(field instanceof PopupDateField)){
				field.setWidth("180px");
			}
		}
    	
    	user.setEnabled(false);
    	user.setStyleName("nogrey");
    	
    	project.setItemCaptionPropertyId("PSLV_NAME");
    	project.setEnabled(false);
    	
    	disabledMap = new HashMap<Object, String>();
    	disabledMap.putAll(componentMap);
    	disabledMap.remove(user);
    	disabledMap.remove(project);
    	disabledMap.remove(patient);
    	disabledMap.remove(created);
    	
    	number.setImmediate(true);
    	
    	checked.setEnabled(dataSetItem != null && !MyUtils.equalsWithNulls(
    	    MyUtils.getValueFromItem(dataSetItem, "PL_ID_USER", Integer.class),
    	    UserData.get().getUserId()
    	    ) && !wasChecked());
    	checked.setStyleName(checked.isEnabled() ? "" : "nogrey");
    	checked.setWidth(null);
    	checked_user.setEnabled(false);
    	checked_user.setStyleName("nogrey");
    	checked_date.setEnabled(false);
        checked_date.setStyleName("nogrey");
        checked_date.setWidth("100px");
        
        checked.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                if((boolean) event.getProperty().getValue()
                    && dataSetItem != null 
                    && !wasChecked()) {
                    
                    checked_user.setValue(UserData.get().getUserName());
                    checked_date.setReadOnly(false);
                    checked_date.setValue(new Date());
                    checked_date.setReadOnly(true);
                    
                }
                
            }
        });
    	
    	if(dataSetId.equals("")){
	    	for (Entry<Object, String> entry : disabledMap.entrySet()) {
	    		AbstractField field = (AbstractField) entry.getKey();
				field.setEnabled(false);
			}
	    	prescriptionEntries.setEnabled(false);
	    	disabledMap.remove(nurse);
	    	btn_save.setEnabled(false);
	    	created.setValue(new Date());
	    	booking.setValue(new Date());
	    	
	    	limitProject();
    	}else{
    		project.setEnabled(false);
    		project.setStyleName("nogrey");
    		
    		patient.setEnabled(false);
    		patient.setStyleName("nogrey");
    		
    		prescriptionEntries.setProject((Integer) project.getValue());
    	}
    	
    	componentListeners();
    	
    	created.setReadOnly(true);
    	created.setResolution(Resolution.MINUTE);
    	updated.setReadOnly(true);
    	updated.setResolution(Resolution.MINUTE);
        checked_date.setReadOnly(true);
        checked_date.setResolution(Resolution.MINUTE);
    	
    	date.setRequired(true);
    	patient.setRequired(true);
    	nurse.setRequired(false); // später rausnehmen
    	booking.setRequired(true);
    	
    	
//    	firm.setImmediate(true);
    	
    }
    
    // independent of currently selected project since edit mode does not allow it to change
    // and does not need to be filtered
    private void limitProject() {
        IndexedContainer con = (IndexedContainer) project.getContainerDataSource();
        con.addContainerFilter(new Filter() {
            
            @Override
            public boolean passesFilter(Object itemId, Item item) throws UnsupportedOperationException {
                return item.getItemProperty("PSLV_CODE").getValue() != null &&
                    !"".equals(item.getItemProperty("PSLV_CODE").getValue());
            }
            
            @Override
            public boolean appliesToProperty(Object propertyId) {
                return false;
            }
        });
    }
    
    private void limitDatePickers(Date target) {
        
        if(target == null) {
            return;
        }
        LocalDate local = new LocalDate(target);
        
        date.setRangeStart(local.minusDays(100).toDate());
        date.setRangeEnd(local.toDate());
        booking.setRangeStart(local.minusDays(10).toDate());
        booking.setRangeEnd(local.toDate());
    }
    
    private void componentListeners(){
    	
    	project.addValueChangeListener(new ValueChangeListener() {
			
			@Override
			public void valueChange(ValueChangeEvent event) {
				
				Boolean selected = (event.getProperty().getValue() != null);
				
//				fillFields(true);
				
				prescriptionEntries.setProject((Integer) project.getValue());
				
                nurse.setEnabled(selected);
                project.setEnabled(patient.getValue() != null);
                for (Entry<Object, String> entry : disabledMap.entrySet()) {
                    AbstractField field = (AbstractField) entry.getKey();
                    field.setEnabled(selected);
                }
				
				Container con = prescriptionEntries.getContainer();
				btn_save.setEnabled(selected && con != null && con.size() > 0);
				prescriptionEntries.setEnabled(selected);
			}
		});
    	
    	patient.addValueChangeListener(new ValueChangeListener() {
			
			@Override
			public void valueChange(ValueChangeEvent event) {
				
			    log.info("pid: {}", event.getProperty().getValue());
			    
				Boolean selected = (event.getProperty().getValue() != null);
				fillNurses();
				fillProjects();
				project.setEnabled(selected);
				
				preselectExtendedFields();
				
			}
		});
    	
    	prescriptionEntries.addItemSetChangeListener(new ItemSetChangeListener() {
            
            @Override
            public void containerItemSetChange(ItemSetChangeEvent event) {
                
                Container con = event.getContainer();
                btn_save.setEnabled(project.getValue() != null && (con != null && con.size() != 0));
                
            }
        });
    	
    }
    
    /*************************** Events *******************************/

    @SuppressWarnings("serial")
    private void setEventListeners() {

        btn_save.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {
                // TODO Automatisch generierter Methodenstub

                if (validate() == false) {
                    I18nManager.global(I18nGlobalNotifiers.fields_empty);
                    return;
                }
                
                if(hasDuplicates()) {
                    I18nManager.global(I18nGlobalNotifiers.entry_exists);
                    return;
                }
                
                PrescriptionBalance balance = new PrescriptionBalance();
            	balance.setPatientId((Integer) patient.getValue());
                
                if (dataSetId.equals("") == true) {
                    dataSetId = Integer.toString(dbInsert());
                    
                    if(!dataSetId.equals("") && !dataSetId.equals("0")){
                    	
//                    	balance.addBalance((Integer) product.getValue(), quantity.getValue(), PrescriptionBalance.PRESCRIPTION);
//                    	PrescriptionBalance.action.PRESCRIPTION
                        prescriptionEntries.setPatient((Integer) patient.getValue());
                    	prescriptionEntries.save(Integer.parseInt(dataSetId));
                    	
//                    	sendMail();
                    }
                    
                } else {
                    dbUpdate();
                    
//                    Integer delta = quantity.getValue() - previousQuantity;
//                    
//                    if(delta != 0){
//                    	balance.editBalance((Integer) product.getValue(), delta, PrescriptionBalance.PRESCRIPTION);
//                    }
                    prescriptionEntries.setPatient((Integer) patient.getValue());
                    prescriptionEntries.save();
                    
                    updateBalance();

                }
                
                

                //TASK check if save successful
                UI.getCurrent().getUI().removeWindow(win);
            }

        });

       
    }

    /******************************************************************/
    
    /************************ --> Berrechtigung <-- **************************/

    @SuppressWarnings("unused")
    public void setPermissionsFromDatabase() {
        if (formIdPerm == "") {
            System.out.println("Form Einstellung Fehlt: Berechtigung");
            return;
        }

        
        Rechteholen r = new Rechteholen(ACC_ID + "");
        String[][] perms = r.Datenholen();

        for (int i = 0; i < perms.length; i++) {
            if (perms[i][0].equals(formIdPerm) == true) {

                permRead = Integer.valueOf(perms[i][3]);
                permUpdate = Integer.valueOf(perms[i][4]);
                permCreate = Integer.valueOf(perms[i][6]);
                permDelete = Integer.valueOf(perms[i][5]);
                
            }
        }
    }

    public void setPermissions(int create, int read, int update, int delete) {

        permCreate = create;
        permRead = read;
        permUpdate = update;
        permDelete = delete;

    }

    private void setMenuPermissions() {
        Boolean c = (permCreate == 1);
        Boolean r = (permRead == 1);
        Boolean u = (permUpdate == 1);
        Boolean d = (permDelete == 1);

        btn_save.setEnabled((c||u));
        prescriptionEntries.setEnabled((c || u));

    }
    
    /***********************************************/
    
    private void fillFields(){
    	
		fillProjects();
		fillUser();

    	
    	fillFirm();
    	fillPatient();
    	fillNurses();
    	fillStatus();
    }
    
    private void fillStatus() {
        I18nConverter statusConverter = new I18nConverter("cust_prescriptions_status", "PS_KEY", "PS_KEY");
        statusConverter.attachDatasource(status);
    }
    
    private void preselectExtendedFields() {
        DBClass db = new DBClass();

        String sql = "select"
         + "\n " + "    PSL_ID"
         + "\n " + "    , PSL_NO_FEES_UNTIL >= DATE_SUB(NOW(), INTERVAL 1 DAY) as nofees"
         + "\n " + "    , PSL_PERM_GRANT_UNTIL >= DATE_SUB(NOW(), INTERVAL 1 DAY) as perm"
         + "\n " + "from cust_patient_stammdaten_liste"
         + "\n " + "where PSL_ID = " + patient.getValue();
        
        db.CustomQuery.setSqlString(sql);
//        db.debugNextQuery(true);
        Item item = MyUtils.getFirstItemFromContainer(db.CustomQuery.query());
        
        noFees.setValue(MyUtils.equalsWithNulls(MyUtils.getValueFromItem(item, "nofees", Long.class) , 1L));
        
        if(dataSetId.equals("")) {
            
            final Boolean perm = MyUtils.equalsWithNulls(MyUtils.getValueFromItem(item, "perm", Long.class), 1L);
            ((IndexedContainer) status.getContainerDataSource()).addContainerFilter(new Filter() {
                
                @Override
                public boolean passesFilter(Object itemId, Item item) throws UnsupportedOperationException {
                    
                    return itemId.equals("rx_permanent") ? perm : !perm;
                    
                }
                
                @Override
                public boolean appliesToProperty(Object propertyId) {
                    return false;
                }
            });
            
            if(perm) {
                status.setValue("rx_permanent");
            }
            
        }
        
    }
    
    private void fillFirm() {

        DBClass db = new DBClass();

        String sql = "SELECT" 
            + "\n " + "    IF_KEY" 
            + "\n " + "    , IF_NAME" 
            + "\n " + "FROM cust_internal_firms";

        db.CustomQuery.setSqlString(sql);
        Container con = db.CustomQuery.query();

//        firm.addItem(0);
//        firm.setItemCaption(0, i18n.get(caption.firm_auto));
//        firm.setNullSelectionItemId(0);
//        
//        for (Object iid : con.getItemIds()) {
//            firm.addItem(con.getContainerProperty(iid, "IF_KEY").getValue());
//            firm.setItemCaption(con.getContainerProperty(iid, "IF_KEY").getValue(),
//                (String) con.getContainerProperty(iid, "IF_NAME").getValue());
//        }
        
    }
    
    private void fillProjects(){
        
        CustomQuery q = new DBClass().CustomQuery;
        String sql = "select distinct VH_PROJEKT_ID, PSLV_NAME from "
             + "\n " + "cust_verk_haupt"
             + "\n " + "left join cust_projekte_stammdaten_liste on VH_PROJEKT_ID = PSLV_ID";
        
        if(patient.getValue() != null) {
            sql += "\n where VH_PATIENT_ID = " + patient.getValue(); 
        }
        
        q.setSqlString(sql);
        
	    project.setContainerDataSource(MyUtils.convertIndex(q.query(), "VH_PROJEKT_ID"));
    }
    
    private String getSelectedProjectId(){
        Integer value = 0;
        
    	if (project.getValue() != null) {
    	    value = (Integer) project.getValue();
    	}
    	
    	return value.toString();
    }
    
    private boolean wasChecked() {
        return dataSetItem != null && !MyUtils.equalsWithNulls(
            MyUtils.getValueFromItem(dataSetItem, "PL_CHECKED_ID_USER", Integer.class), null);
    }
    
    private void fillNurses(){
        
        Integer nurseId = (Integer) nurse.getValue();
        
        if (project.getValue() == null) {
            nurse.removeAllItems();
            
            ProjectNurseCombos rnc = new ProjectNurseCombos();
            new combo(rnc.getNurseComboAll(), nurse, "KSK_ID", "Krankenschwesternname");
            
            return;
        }
        
        ProjectNurseCombos rnc = new ProjectNurseCombos((Integer) project.getValue());
        
        
        if((permCreate == 1) || (permUpdate == 1)){
        	rnc.setPatientId((Integer) patient.getValue());
        }
        
        Container main = rnc.getNurseComboMain();
        Container subs = rnc.getNurseComboSubs();
        
        try {
        	nurse.removeAllItems();
        	if(rnc.getPatientId() != null){
        		new combo(main, nurse, "KSK_ID", "Krankenschwesternname");
                new combo(subs, nurse, "KSK_ID", "Krankenschwesternname");	
        	}else{
        		new combo(rnc.getNurseComboAll(), nurse, "KSK_ID", "Krankenschwesternname");
        	}
        } catch (Exception e) {
            nurse.removeAllItems();
            return;
        }
        
        if(nurseId != null){
        	Boolean isPresent = false;
        	
        	for (Object itemId : main.getItemIds()) {
        		if((((Integer) main.getContainerProperty(itemId, "KSK_ID").getValue()) == nurseId)){
        			isPresent = true;
        		}
			}
        	
        	for (Object itemId : subs.getItemIds()) {
        		if((((Integer) subs.getContainerProperty(itemId, "KSK_ID").getValue()) == nurseId)){
        			isPresent = true;
        		}
			}
        	
        	if(!isPresent){
        		try {
        			new combo(rnc.getNurseComboSingle(nurseId), nurse, "KSK_ID", "Krankenschwesternname");		
				} catch (Exception e) {
					System.out.println("error adding temporary nurse entry");
				}
        	}
        	nurse.setValue(nurseId);
        }
    }
    
    private void fillNursesDB() {

        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("KSK_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(KSK_TITEL,' ',KSA_NAME,' ',AUL_NAME,' ',AUL_VORNAME)",
                "Krankenschwesternname");

        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("AL_G_ID");

        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_stammdaten_user", "INNER JOIN", "cust_krankenschwester_stammdaten_anrede", "AUL_ANREDE_ID", "KSA_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_stammdaten_user", "LEFT JOIN", "cms_auth_liste_gu", "AUL_ID", "AL_U_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_krankenschwester_stammdaten_ks", "INNER JOIN", "cms_auth_stammdaten_user", "KSK_U_ID", "AUL_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_liste_gu", "LEFT JOIN", "cust_projekte_stammdaten_liste", "AL_G_ID", "PSLV_GROUP");
        
        if(project.getValue() != null){
        	db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_projekte_stammdaten_liste", "PSLV_ID", "=", getSelectedProjectId(), "");
        }
        
        db.debugNextQuery(false);
        
        try {
        	nurse.removeAllItems();
            combo nc = new combo(db.DB_Data_Get.DB_SEND_AND_GET(), nurse, "KSK_ID", "Krankenschwesternname");
        } catch (Exception e) {
            nurse.removeAllItems();
            return;
        }

        db.DB_Data_Get.connclose();

    }
    
    private void fillPatient() {

        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("PSL_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(PSL_TITEL,' ',PSA_NAME,' ',PSL_NAME,', ',PSL_VORNAME)", "Patientenname");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_patient_stammdaten_liste", "INNER JOIN", "cust_patient_stammdaten_anrede", "PSL_ANREDE", "PSA_ID");
        
        Country uc = MyUtils.getUserData().getCountry();
        if(uc.hasPermissions()) {
            //db.DB_Data_Get.DB_Filter.DB_WHERE_In("cust_patient_stammdaten_liste", "PSL_COUNTYCODE", uc.getFilterString(), (project.getValue() != null && (Integer) project.getValue() != 1000) ? "AND" : "");
            db.DB_Data_Get.DB_Filter.DB_WHERE_In("cust_patient_stammdaten_liste", "PSL_COUNTYCODE", uc.getFilterString(), "");
        }
        
//        if(project.getValue() != null && (Integer) project.getValue() != 1000){
//            db.DB_Data_Get.DB_Filter.DB_WHERE_In("cust_patient_stammdaten_liste", "PSL_ID",
//                "(select VH_PATIENT_ID from cust_verk_haupt where VH_PROJEKT_ID = "+ getSelectedProjectId() +" group by VH_PATIENT_ID)", "");
//        }
        db.DB_Data_Get.DB_Ordnen.DB_Ordnen("PSL_NAME", "ASC");
        db.DB_Data_Get.DB_Gruppieren.DB_Gruppieren("PSL_ID");
        
//        db.debugNextQuery(true);
        
        try {
        	patient.removeAllItems();
            combo nc = new combo(db.DB_Data_Get.DB_SEND_AND_GET(), patient, "PSL_ID", "Patientenname");
        } catch (Exception e) {
            patient.removeAllItems();
        }

        db.DB_Data_Get.connclose();

        patient.setFilteringMode(FilteringMode.CONTAINS);
    }
    
    private void fillUser() {

        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("AUL_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(AUL_NAME, ', ', AUL_VORNAME)", "user");
        
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_stammdaten_user", "INNER JOIN", "cms_auth_stammdaten_anrede", "AUL_ANREDE_ID", "ASA_ID");
        
        db.DB_Data_Get.DB_Gruppieren.DB_Gruppieren("AUL_ID");
        
        
//        db.debugNextQuery(true);
        
        try {
        	user.removeAllItems();
            combo nc = new combo(db.DB_Data_Get.DB_SEND_AND_GET(), user, "AUL_ID", "user");
        } catch (Exception e) {
        	user.removeAllItems();
        }

        db.DB_Data_Get.connclose();

        user.setFilteringMode(FilteringMode.CONTAINS);
    }
    
    /******************** Database *****************/
    private void fillDbMap() {
        dbMap = new HashMap<>();
//        dbMap.put(component, "table:COLUMN");
//        dbMap.put(project, "cust_prescriptions_list:PL_ID_PROJECT");
        
        String table = "cust_prescriptions_list:";
        
        dbMap.put(created, table + "PL_CREATED");
        dbMap.put(updated, table + "PL_UPDATED");
        dbMap.put(user, table + "PL_ID_USER");
        dbMap.put(date, table + "PL_DATE");
        dbMap.put(booking, table + "PL_BOOKING");
        dbMap.put(patient, table + "PL_ID_PATIENT");
        dbMap.put(nurse, table + "PL_ID_NURSE");
        dbMap.put(number, table + "PL_NR");
        
        dbMap.put(status, table + "PL_STATUS");
        dbMap.put(noFees, table + "PL_NO_FEE");
//        dbMap.put(firm, table + "PL_FIRM");
        dbMap.put(comment, table + "PL_COMMENT");
        
        dbMap.put(checked_user, table + "checked_user");
        dbMap.put(checked_date, table + "PL_CHECKED_DATE");
        


    }
    
    private Boolean hasDuplicates() {
        
        if(!dataSetId.equals("") || number.getValue() == null || "".equals(number.getValue())) {
            return false;
        }
        
        DBClass db = new DBClass();

        String sql = "SELECT COUNT(*) as count FROM"
             + "\n " + "cust_prescriptions_list"
             + "\n " + "WHERE TRIM(PL_NR) = '"+number.getValue().trim()+"'";
        
        db.CustomQuery.setSqlString(sql);
        
//        db.debugNextQuery(true);
        
        Container con = db.CustomQuery.query();
        
        Integer count = 0;
        
        if(con.size() > 0) {
            count = MyUtils.getValueFromItem(con.getItem(con.getItemIds().iterator().next()), "count", Long.class).intValue();
        }
        
        return count > 0;
    }
    
    private void dbFillForm() {
        
        CustomQuery q = new DBClass().CustomQuery;
        String sql = "select cust_prescriptions_list.*, CONCAT_WS(' ',AUL_VORNAME, AUL_NAME ) as checked_user from cust_prescriptions_list"
            + "\n left join cms_auth_stammdaten_user on PL_CHECKED_ID_USER = AUL_ID"
            + "\n " + "where PL_ID = " + dataSetId;
        q.setSqlString(sql);
        
//        DBClass db = new DBClass();
//        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
//
//        /******************************** Table ****************************************/
//        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_prescriptions_list");
//        /******************************************************************************/
//        /******************************** Filter ****************************************/
//        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_prescriptions_list", "PL_ID", "=", dataSetId, "");
//        /******************************************************************************/
//
//        // db.DB_Data_Get.Set_Type("SLF_VON_UHRZEIT", Date.class);
//        // db.DB_Data_Get.Set_Type("SLF_BIS_UHRZEIT", Date.class);

        Container con = q.query();
        fb = new Form_Bind();

        fb.Get_and_Fill(con, dbMap);
        dataSetItem = MyUtils.getFirstItemFromContainer(con);
        
        checked.setValue(wasChecked());
        
        for (Object itemId :  project.getContainerDataSource().getItemIds()) {
        	
        	if(project.getContainerProperty(itemId, "VH_PROJEKT_ID").getValue()
        			.equals(dataSetItem.getItemProperty("PL_ID_PROJECT").getValue())){
        		project.setValue(itemId);
        	}
		}


    }

    private int dbInsert() {
        DBClass db = new DBClass();
        fb = new Form_Bind();
        HashMap<Object, String> map = new HashMap<Object, String>();
        map.putAll(dbMap);
        map.remove(created);
        map.remove(updated);
        map.remove(checked_user);
        map.remove(checked_date);
        fb.Insert(db, map);
        db.DB_Data_Insert.DB_Daten.DB_Data("cust_prescriptions_list", "PL_ID_PROJECT", getSelectedProjectId());
        /******************************** Table ****************************************/
        db.DB_Data_Insert.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_prescriptions_list");
        /******************************************************************************/
        
//        db.debugNextQuery(true);
        
        return db.DB_Data_Insert.DB_Insert();
    }

    private void dbUpdate() {
        DBClass db = new DBClass();
        fb = new Form_Bind();
        HashMap<Object, String> map = new HashMap<Object, String>();
        map.putAll(dbMap);
        map.remove(created);
        map.remove(updated);
        map.remove(checked_user);
        map.remove(checked_date);
        fb.Update(db, map);
        
        if(prescriptionEntries != null && prescriptionEntries.isModified()) {
            db.DB_Data_Update.DB_Daten.DB_Data("cust_prescriptions_list", "PL_UPDATED", "CURRENT_TIMESTAMP()", false);
        }
        
        if(checked.getValue() && !wasChecked()) {
            db.DB_Data_Update.DB_Daten.DB_Data("cust_prescriptions_list", "PL_CHECKED_ID_USER", UserData.get().getUserId().toString());
            db.DB_Data_Update.DB_Daten.DB_Data("cust_prescriptions_list", "PL_CHECKED_DATE", MyUtils.formatSqlDate(new Date()));
        }
        
        db.DB_Data_Update.DB_Daten.DB_Data("cust_prescriptions_list", "PL_ID_PROJECT", getSelectedProjectId());
        /******************************** Table ****************************************/
        db.DB_Data_Update.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_prescriptions_list");
        /******************************************************************************/
        /******************************** Filter ****************************************/
        db.DB_Data_Update.DB_Filter.DB_WHERE_Allgemein("cust_prescriptions_list", dataIdCol, "=", dataSetId, "");
        /******************************************************************************/
//        db.debugNextQuery(true);
        db.DB_Data_Update.DB_Update();

    }

    private void updateBalance() {
        
        IndexedContainer con = prescriptionEntries.getContainer();
        
        if(!checked.getValue() || wasChecked() || patient.getValue() == null) {
            return;
        }

        PrescriptionBalance balance = new PrescriptionBalance();
        balance.setPatientId((Integer) patient.getValue());
        
        HashMap<Integer, Integer> deltas = new HashMap<Integer, Integer>();
        
        for (Object iid : con.getItemIds()) {
            
            Item insertItem = con.getItem(iid);
            
            Integer product = MyUtils.getValueFromItem(insertItem, "PLE_ID_PRODUCT", Integer.class);
            Integer quantity = MyUtils.getValueFromItem(insertItem, "PLE_QUANTITY", Integer.class);
            deltas.put(product, quantity + (deltas.get(product) != null ? deltas.get(product) : 0));
            
        }
        
        log.info("deltas: {}", deltas);

        for (Entry<Integer, Integer> delta : deltas.entrySet()) {
            balance.editBalance(delta.getKey(), delta.getValue(), PrescriptionBalance.PRESCRIPTION, null, dataSetId);
        }
        
    }

    /*********************** -->Validierung<-- ********************/
    private void fillValidateMap() {
        validateMap = new HashMap<>();
        validateMap.putAll(componentMap);
        
//        ValidateMap.put(component, "component"); // should not be needed

    }

    private void setCustomValidators() {

        // psw_pass_1.addValidator(new Custom_Benutzerform_psw_ändern(psw_pass_1, psw_pass_2));

        /******* manual actions *******/

    }

    private boolean validate() {
        val_checker4 val = new val_checker4(validateMap);
        return val.Is_Valid();

    }

    @AutoGenerated
    private VerticalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setStyleName("cust_margin_half_full_none_full");
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(true);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // main
        main = buildMain();
        mainLayout.addComponent(main);
        mainLayout.setExpandRatio(main, 10.0f);
        mainLayout.setComponentAlignment(main, new Alignment(48));
        
        // buttons
        buttons = buildButtons();
        mainLayout.addComponent(buttons);
        mainLayout.setExpandRatio(buttons, 1.0f);
        mainLayout.setComponentAlignment(buttons, new Alignment(48));
        
        return mainLayout;
    }

    @AutoGenerated
    private VerticalLayout buildMain() {
        // common part: create layout
        main = new VerticalLayout();
        main.setImmediate(false);
        main.setWidth("100.0%");
        main.setHeight("100.0%");
        main.setMargin(false);
        main.setSpacing(true);
        
        // systemPanel
        systemPanel = buildSystemPanel();
        main.addComponent(systemPanel);
        main.setExpandRatio(systemPanel, 4.0f);
        
        // prescriptionPanel
        prescriptionPanel = buildPrescriptionPanel();
        main.addComponent(prescriptionPanel);
        main.setExpandRatio(prescriptionPanel, 7.0f);
        
        return main;
    }

    @AutoGenerated
    private Panel buildSystemPanel() {
        // common part: create layout
        systemPanel = new Panel();
        systemPanel.setCaption("Verwaltungsdaten");
        systemPanel.setImmediate(false);
        systemPanel.setWidth("100.0%");
        systemPanel.setHeight("100.0%");
        
        // verticalLayout_2
        verticalLayout_2 = buildVerticalLayout_2();
        systemPanel.setContent(verticalLayout_2);
        
        return systemPanel;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_2() {
        // common part: create layout
        verticalLayout_2 = new VerticalLayout();
        verticalLayout_2.setImmediate(false);
        verticalLayout_2.setWidth("100.0%");
        verticalLayout_2.setHeight("100.0%");
        verticalLayout_2.setMargin(false);
        
        // horizontalLayout_8
        horizontalLayout_8 = buildHorizontalLayout_8();
        verticalLayout_2.addComponent(horizontalLayout_8);
        
        return verticalLayout_2;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_8() {
        // common part: create layout
        horizontalLayout_8 = new HorizontalLayout();
        horizontalLayout_8.setImmediate(false);
        horizontalLayout_8.setWidth("100.0%");
        horizontalLayout_8.setHeight("100.0%");
        horizontalLayout_8.setMargin(false);
        horizontalLayout_8.setSpacing(true);
        
        // verticalLayout_6
        verticalLayout_6 = buildVerticalLayout_6();
        horizontalLayout_8.addComponent(verticalLayout_6);
        
        // verticalLayout_7
        verticalLayout_7 = buildVerticalLayout_7();
        horizontalLayout_8.addComponent(verticalLayout_7);
        
        return horizontalLayout_8;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_6() {
        // common part: create layout
        verticalLayout_6 = new VerticalLayout();
        verticalLayout_6.setImmediate(false);
        verticalLayout_6.setWidth("100.0%");
        verticalLayout_6.setHeight("100.0%");
        verticalLayout_6.setMargin(false);
        
        // project
        project = new ComboBox();
        project.setCaption("Projekt");
        project.setImmediate(false);
        project.setWidth("-1px");
        project.setHeight("-1px");
        verticalLayout_6.addComponent(project);
        verticalLayout_6.setComponentAlignment(project, new Alignment(48));
        
        // horizontalLayout_6
        horizontalLayout_6 = buildHorizontalLayout_6();
        verticalLayout_6.addComponent(horizontalLayout_6);
        verticalLayout_6.setComponentAlignment(horizontalLayout_6, new Alignment(48));
        
        // horizontalLayout_7
        horizontalLayout_7 = buildHorizontalLayout_7();
        verticalLayout_6.addComponent(horizontalLayout_7);
        verticalLayout_6.setComponentAlignment(horizontalLayout_7, new Alignment(48));
        
        return verticalLayout_6;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_6() {
        // common part: create layout
        horizontalLayout_6 = new HorizontalLayout();
        horizontalLayout_6.setImmediate(false);
        horizontalLayout_6.setWidth("100.0%");
        horizontalLayout_6.setHeight("-1px");
        horizontalLayout_6.setMargin(false);
        
        // checked
        checked = new CheckBox();
        checked.setCaption("checked");
        checked.setImmediate(false);
        checked.setWidth("100px");
        checked.setHeight("-1px");
        horizontalLayout_6.addComponent(checked);
        horizontalLayout_6.setComponentAlignment(checked, new Alignment(48));
        
        // checked_date
        checked_date = new PopupDateField();
        checked_date.setCaption("checked_date");
        checked_date.setImmediate(false);
        checked_date.setWidth("100px");
        checked_date.setHeight("-1px");
        horizontalLayout_6.addComponent(checked_date);
        horizontalLayout_6.setComponentAlignment(checked_date, new Alignment(48));
        
        return horizontalLayout_6;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_7() {
        // common part: create layout
        horizontalLayout_7 = new HorizontalLayout();
        horizontalLayout_7.setImmediate(false);
        horizontalLayout_7.setWidth("100.0%");
        horizontalLayout_7.setHeight("-1px");
        horizontalLayout_7.setMargin(false);
        
        // created
        created = new PopupDateField();
        created.setCaption("Erstellungsdatum");
        created.setImmediate(false);
        created.setWidth("100px");
        created.setHeight("-1px");
        horizontalLayout_7.addComponent(created);
        horizontalLayout_7.setComponentAlignment(created, new Alignment(48));
        
        // updated
        updated = new PopupDateField();
        updated.setCaption("Änderungsdatum");
        updated.setImmediate(false);
        updated.setWidth("100px");
        updated.setHeight("-1px");
        horizontalLayout_7.addComponent(updated);
        horizontalLayout_7.setComponentAlignment(updated, new Alignment(48));
        
        return horizontalLayout_7;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_7() {
        // common part: create layout
        verticalLayout_7 = new VerticalLayout();
        verticalLayout_7.setImmediate(false);
        verticalLayout_7.setWidth("100.0%");
        verticalLayout_7.setHeight("100.0%");
        verticalLayout_7.setMargin(false);
        
        // user
        user = new ComboBox();
        user.setCaption("Bearbeiter");
        user.setImmediate(false);
        user.setWidth("-1px");
        user.setHeight("-1px");
        verticalLayout_7.addComponent(user);
        verticalLayout_7.setComponentAlignment(user, new Alignment(48));
        
        // checked_user
        checked_user = new TextField();
        checked_user.setCaption("checked_user");
        checked_user.setImmediate(false);
        checked_user.setWidth("-1px");
        checked_user.setHeight("-1px");
        verticalLayout_7.addComponent(checked_user);
        verticalLayout_7.setComponentAlignment(checked_user, new Alignment(48));
        
        // booking
        booking = new PopupDateField();
        booking.setCaption("Buchungsdatum");
        booking.setImmediate(false);
        booking.setWidth("-1px");
        booking.setHeight("-1px");
        verticalLayout_7.addComponent(booking);
        verticalLayout_7.setComponentAlignment(booking, new Alignment(48));
        
        return verticalLayout_7;
    }

    @AutoGenerated
    private Panel buildPrescriptionPanel() {
        // common part: create layout
        prescriptionPanel = new Panel();
        prescriptionPanel.setCaption("Rezeptdaten");
        prescriptionPanel.setImmediate(false);
        prescriptionPanel.setWidth("100.0%");
        prescriptionPanel.setHeight("100.0%");
        
        // verticalLayout_3
        verticalLayout_3 = buildVerticalLayout_3();
        prescriptionPanel.setContent(verticalLayout_3);
        
        return prescriptionPanel;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_3() {
        // common part: create layout
        verticalLayout_3 = new VerticalLayout();
        verticalLayout_3.setImmediate(false);
        verticalLayout_3.setWidth("100.0%");
        verticalLayout_3.setHeight("100.0%");
        verticalLayout_3.setMargin(false);
        
        // tabs
        tabs = buildTabs();
        verticalLayout_3.addComponent(tabs);
        
        return verticalLayout_3;
    }

    @AutoGenerated
    private TabSheet buildTabs() {
        // common part: create layout
        tabs = new TabSheet();
        tabs.setImmediate(true);
        tabs.setWidth("100.0%");
        tabs.setHeight("100.0%");
        
        // horizontalLayout_1
        horizontalLayout_1 = buildHorizontalLayout_1();
        tabs.addTab(horizontalLayout_1, "Allgemein", null);
        
        // prescriptionEntries
        prescriptionEntries = new PrescriptionEntriesComponent();
        prescriptionEntries.setImmediate(false);
        prescriptionEntries.setWidth("100.0%");
        prescriptionEntries.setHeight("100.0%");
        tabs.addTab(prescriptionEntries, "Medikamente", null);
        
        return tabs;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_1() {
        // common part: create layout
        horizontalLayout_1 = new HorizontalLayout();
        horizontalLayout_1.setImmediate(false);
        horizontalLayout_1.setWidth("100.0%");
        horizontalLayout_1.setHeight("98.0%");
        horizontalLayout_1.setMargin(false);
        horizontalLayout_1.setSpacing(true);
        
        // verticalLayout_4
        verticalLayout_4 = buildVerticalLayout_4();
        horizontalLayout_1.addComponent(verticalLayout_4);
        horizontalLayout_1.setExpandRatio(verticalLayout_4, 1.0f);
        
        // verticalLayout_5
        verticalLayout_5 = buildVerticalLayout_5();
        horizontalLayout_1.addComponent(verticalLayout_5);
        horizontalLayout_1.setExpandRatio(verticalLayout_5, 1.0f);
        
        return horizontalLayout_1;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_4() {
        // common part: create layout
        verticalLayout_4 = new VerticalLayout();
        verticalLayout_4.setImmediate(false);
        verticalLayout_4.setWidth("100.0%");
        verticalLayout_4.setHeight("100.0%");
        verticalLayout_4.setMargin(false);
        
        // date
        date = new PopupDateField();
        date.setCaption("Rezeptdatum");
        date.setImmediate(false);
        date.setWidth("-1px");
        date.setHeight("-1px");
        verticalLayout_4.addComponent(date);
        verticalLayout_4.setComponentAlignment(date, new Alignment(48));
        
        // number
        number = new TextField();
        number.setCaption("Rezeptnummer");
        number.setImmediate(false);
        number.setWidth("-1px");
        number.setHeight("-1px");
        verticalLayout_4.addComponent(number);
        verticalLayout_4.setComponentAlignment(number, new Alignment(48));
        
        // patient
        patient = new ComboBox();
        patient.setCaption("Patient");
        patient.setImmediate(false);
        patient.setWidth("-1px");
        patient.setHeight("-1px");
        verticalLayout_4.addComponent(patient);
        verticalLayout_4.setComponentAlignment(patient, new Alignment(48));
        
        // nurse
        nurse = new ComboBox();
        nurse.setCaption("Rezeptverantwortliche KS");
        nurse.setImmediate(false);
        nurse.setWidth("-1px");
        nurse.setHeight("-1px");
        verticalLayout_4.addComponent(nurse);
        verticalLayout_4.setComponentAlignment(nurse, new Alignment(48));
        
        return verticalLayout_4;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_5() {
        // common part: create layout
        verticalLayout_5 = new VerticalLayout();
        verticalLayout_5.setImmediate(false);
        verticalLayout_5.setWidth("100.0%");
        verticalLayout_5.setHeight("100.0%");
        verticalLayout_5.setMargin(false);
        verticalLayout_5.setSpacing(true);
        
        // status
        status = new ComboBox();
        status.setCaption("Status");
        status.setImmediate(false);
        status.setWidth("-1px");
        status.setHeight("-1px");
        verticalLayout_5.addComponent(status);
        verticalLayout_5.setComponentAlignment(status, new Alignment(48));
        
        // noFees
        noFees = new CheckBox();
        noFees.setCaption("Gebührenbefreit");
        noFees.setImmediate(false);
        noFees.setWidth("-1px");
        noFees.setHeight("-1px");
        verticalLayout_5.addComponent(noFees);
        verticalLayout_5.setComponentAlignment(noFees, new Alignment(48));
        
        // comment
        comment = new TextArea();
        comment.setStyleName("cust_textarea_no_margin");
        comment.setCaption("Bemerkungen");
        comment.setImmediate(false);
        comment.setWidth("200px");
        comment.setHeight("100.0%");
        verticalLayout_5.addComponent(comment);
        verticalLayout_5.setExpandRatio(comment, 1.0f);
        verticalLayout_5.setComponentAlignment(comment, new Alignment(48));
        
        return verticalLayout_5;
    }

    @AutoGenerated
    private HorizontalLayout buildButtons() {
        // common part: create layout
        buttons = new HorizontalLayout();
        buttons.setImmediate(false);
        buttons.setWidth("100.0%");
        buttons.setHeight("100.0%");
        buttons.setMargin(false);
        
        // btn_save
        btn_save = new Button();
        btn_save.setCaption("Speichern");
        btn_save.setImmediate(true);
        btn_save.setWidth("-1px");
        btn_save.setHeight("-1px");
        buttons.addComponent(btn_save);
        buttons.setComponentAlignment(btn_save, new Alignment(48));
        
        return buttons;
    }

}
