package archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektzuweisung.Form.Metadata;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map.Entry;
import java.util.concurrent.CopyOnWriteArrayList;

import org.apache.commons.lang3.tuple.Pair;
import org.joda.time.LocalDate;

import archenoah.config.CMS_Config_Std;
import archenoah.lib.custom.MyUtils;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.tool.comunication.dbclass.DBClass.CustomQuery;
import archenoah.lib.vaadin.Components.Combo.combo;
import archenoah.lib.vaadin.Components.Metadata.MetadataPanel;
import archenoah.lib.vaadin.Components.Metadata.RecurrenceDateInformation;
import archenoah.lib.vaadin.Components.Recurrence.PART;
import archenoah.lib.vaadin.Components.Recurrence.RruleItem;
import archenoah.lib.vaadin.Components.Steppers.IntStepper;
import archenoah.lib.vaadin.Forms_Builder.Form_Bind;
import archenoah.lib.vaadin.Language.i18n.I18nCB;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.lib.vaadin.recurrence.DateBoundaries;
import archenoah.lib.vaadin.recurrence.DateGenerator;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.servicetasking.classes.ServicePlanningCreator;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.servicetasking.classes.ServiceTaskingConfig;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.servicetasking.classes.ServiceTaskingConfig.Permission;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektzuweisung.Form.Metadata.ServiceTaskingComponents.RecurrenceManager;

import com.google.common.base.Joiner;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.ui.AbstractField;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

public class MetadataSAMain extends MetadataPanel {
//    public class MetadataSAMain extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
        private VerticalLayout mainLayout;
        @AutoGenerated
        private Panel pan_system;
        @AutoGenerated
        private VerticalLayout verticalLayout_3;
        @AutoGenerated
        private IntStepper int_maxRep;
        @AutoGenerated
        private Panel pan_verwaltung;
        @AutoGenerated
        private VerticalLayout verticalLayout_4;
        @AutoGenerated
        private ListSelect list_nurses;
        @AutoGenerated
        private HorizontalLayout horizontalLayout_3;
        @AutoGenerated
        private Button btn_removeNurse;
        @AutoGenerated
        private Button btn_addNurse;
        @AutoGenerated
        private ComboBox cbx_nurses;
        @AutoGenerated
        private ComboBox cbx_regLead;
        @AutoGenerated
        private ComboBox cbx_internalFirm;
        @AutoGenerated
        private Panel pan_dynamic;
        @AutoGenerated
        private VerticalLayout verticalLayout_5;
        @AutoGenerated
        private HorizontalLayout horizontalLayout_2;
        @AutoGenerated
        private PopupDateField planningStart;
        @AutoGenerated
        private ComboBox planningPlan;
        @AutoGenerated
        private RecurrenceManager recurrenceManager;
        @AutoGenerated
        private Panel pan_project;
        @AutoGenerated
        private VerticalLayout verticalLayout_2;
        @AutoGenerated
        private TextField txt_patInitials;
        @AutoGenerated
        private TextField txt_patCode;
    /**************** --> Allgemein <--- ********************/
        org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(this.getClass());
        
    // Berrechtigung

    private final Button Temp_Btn = null;
    /******************************************************/
    /**************** --> Tabsheetvars <--- *****************/

    /******************************************************/
    /**************** --> Windowvars <--- *******************/
    private final Window win = null;
    private Panel pan = null;
    /******************************************************/
    /******************* --> Custom <--- ********************/
    /******************************************************/
    private String staticId = null;
    private HashMap<Object, String> DBMapStatic;
    private HashMap<Object, String> DBMapDynamic;
    private HashMap<Object, String> DBMapSubs;

    private IndexedContainer conNursesSubs = null;
    private ArrayList<Object> listNursesSubsDb = null;
    
    private ArrayList<AbstractField> validateListStatic;
    private ArrayList<DBClass> tempDynamic;

    final String table_static = "cust_protokoll_servicetasking_meta_static";
    
    /************ ----->Einstellungen<-- ********************/
    private final String LNG_FRM_ID = "2104";

    private final String Windows_Height = "600px";
    private final String Windows_Width = "720px";

    /******************************************************/
    
    private String RecurrenceString = null;
    private Date RecurrenceStart = null;
    private Integer RecurrenceRepetitions = null;
    private Date RecurrenceLatestDate = null;
    private Integer RecurrenceMetaId = null;
    
    // used in force save homecare
    private Integer metaDynamicId = null;
    private Boolean metaDynamicHomecareValue = null;
    private I18nManager i18n;
    private ServiceTaskingConfig config;
    
    private final static class caption extends I18nCB {
        static final I18nCB planningNone = set();
    }
    
    //public ComboBox cb_nurse;
    public MetadataSAMain() {
        buildMainLayout();
        i18n = new I18nManager(this);
        config = new ServiceTaskingConfig();
        pan = new Panel(mainLayout);
        pan.setSizeFull();

    }

    /********* INIT-Window ************/

//    @Override
    @Override
    public Panel getPanel() {
        
        if(!hasProjectId()) {
            System.err.println("no project id assigned!");
            return pan;
        }
        
        defaultInit();
        return pan;
    }
    
//    /*************************************/
    //TASK placeholder stuff for Editor
//    private Boolean hasMainId(){
//        return true;
//    }
//    
//    private String getMainId(){
//        return null;
//    }
//    
//    private String getPatientId(){
//        return null;
//    }
//    
//    private Boolean hasProjectId(){
//        return true;
//    }
//    
//    private String getProjectId(){
//        return "";
//    }
//    /*************************************/
    
    /********* Inherited Methods ************/
    
    @Override
    public Boolean validate(){
        
        if(!validateStatic()){
            I18nManager.global(I18nGlobalNotifiers.fields_empty);
            return false;
        }
        
        return true;
        
    }
    
    @Override
    public Boolean save() {
        
        if (!hasMainId()) {
            I18nManager.global(I18nGlobalNotifiers.no_main_id);
            return false;
        }
        
        if(!validate()){
            return false;
        }
        
        
        if(staticId != null && staticId.equals("") == false){
            updateStatic();
        }else{
            saveStatic();
        }
        
        saveDynamic();
        saveNurseSubs();
        generatePlanningDates();

        return true;

    }
    

    @Override
    public void update(){
        fillFields();
    }
    
    @Override
    public HashMap<String, Object> getFieldValues(){
        
        HashMap<String, Object> map = new HashMap<String, Object>();
        
        for (Entry<Object, String> entry: DBMapStatic.entrySet()) {

            map.put(entry.getValue(), ((AbstractField) entry.getKey()).getValue());
            
        }
        
        return map;
    }
    
    
    @Override
    public Boolean hasRecurrence(){
        return false;
    }
    
    @Override
    public String getRecurrenceString() {
        // TASK Auto-generated method stub
        return RecurrenceString;
    }

    @Override
    public Date getRecurrenceStart() {
        // TASK Auto-generated method stub
        return RecurrenceStart;
    }

    @Override
    public Integer getRecurrenceRepetitions() {
        // TASK Auto-generated method stub
        return RecurrenceRepetitions;
    }

    @Override
    public Date getRecurrenceLatestDate() {
        // TASK Auto-generated method stub
        return RecurrenceLatestDate;
    }
    
    @Override
    public Integer getRecurrenceMetaId() {
        // TASK Auto-generated method stub
        return RecurrenceMetaId;
    }
    
    @Override
    public void setRecurrenceSettings(String Form_ID) {

    }
    
    @Override
    public Boolean hasMultiRecurrence() {
        return true;
    }
    
    @Override
    public HashMap<Integer, RecurrenceDateInformation> getRecurrenceDates(Boolean all) {
        
        Container con = recurrenceManager.getContainer();
        
        ArrayList<Integer> delIds = new ArrayList<Integer>();
        for (Object iid : con.getItemIds()) {
            delIds.add(MyUtils.getValueFromItem(con.getItem(iid), "STMD_ID", Integer.class));
        }
        
        HashMap<Integer, Date> latestDates = getRecurrenceLatestDates(delIds);
        
        HashMap<Integer,RecurrenceDateInformation> list = new HashMap<Integer, RecurrenceDateInformation>();
        
        for (Object iid : con.getItemIds()) {
            
            RecurrenceDateInformation info = new RecurrenceDateInformation();
            
            Item item = con.getItem(iid);
            Integer id = MyUtils.getValueFromItem(item, "STMD_ID", Integer.class);
            java.sql.Date date = MyUtils.getValueFromItem(item, "STMD_RRULE_START", java.sql.Date.class);
            String rrule = MyUtils.getValueFromItem(item, "STMD_RRULE", String.class);
            
            DateGenerator dg = new DateGenerator(rrule, new Date(date.getTime()), dbGetRecurrenceReps());
            if(latestDates.containsKey(id)){
                
                LocalDate latest = new LocalDate(latestDates.get(id));
                LocalDate today = new LocalDate();
                LocalDate lowestDate = (all || latest.isBefore(today)) ? latest : today; 
                
                dg.setContinuationDate(lowestDate.toDate());
                info.setLatestDate(latest);
            }
            
            HashMap<Object, Object> adv = new HashMap<Object, Object>();
            adv.put("ST_ID_TYPE", MyUtils.getValueFromItem(item, "STMD_TYPE", Integer.class));
            adv.put("ST_VH_ID", MyUtils.getValueFromItem(item, "STMD_VH_ID", Integer.class));
            info.setAdditionalValues(adv);
            
            
            //generate datelist and handle all/future cases
            CopyOnWriteArrayList<LocalDate> dateList = new CopyOnWriteArrayList<LocalDate>(dg.generateDateList());
            
            // remove dates before latest entry for future continuation 
            if(!all && latestDates.containsKey(id)) {
                
                LocalDate latest = new LocalDate(latestDates.get(id));
                dateList.remove(latest);
                
                for (Iterator<LocalDate> dit = dateList.iterator(); dit.hasNext();) {
                    LocalDate localDate = dit.next();
                    
                    if(localDate.isBefore(latest)) {
                        dateList.remove(localDate);
                    }
                    
                }
            }
            info.setDateList(new ArrayList<LocalDate>(dateList));
            list.put(id, info);
            
        }
        
        return list;
    }
    
    @Override
    public Boolean isNurseRequired() {
        return config.getPermission(Permission.nurse_required,
            hasProjectId() ? Integer.parseInt(getProjectId()) : null);
    }
    
    @Override
    public Boolean isPatientRequired() {
        return config.getPermission(Permission.patient_required,
            hasProjectId() ? Integer.parseInt(getProjectId()) : null);
    }
    
    @Override
    public Pair<Date, Date> getBoundaryDates(Integer delegationId, Date originalDate){
        
        RruleItem ri = dbGetRecurrenceRule(delegationId);
        
        if(ri.getItemPropertyIds().size() == 0 || originalDate == null) {
            log.warn("Item or date was null");
            return null;
        }
        
        return DateBoundaries.getBoundaries(ri.getRrule(), ri.getStart(), originalDate);
        
    }
    
    @Override
    public void deleteUnaccepted() {
        // TASK Auto-generated method stub
        
    }

    /********* Init-Standard ************/
    private void defaultInit() {
        
        setDBMaps();
        setupFields();
        fillFields();

        setValidateMaps();

        /**********************/

    }
    
    @Override
    public void setMainId(String id) {
        
        if(id != null && !id.equals("")) {
            
            if(getMainId() != null && getMainId().equals("")) { // initial save from new entry
                recurrenceManager.setParentIdOnly(Integer.parseInt(id));
            }else { // initial load from existing entry
                recurrenceManager.setParentId(Integer.parseInt(id));
            }
            
        }
        
        super.setMainId(id);
        
    }
    
    /******************* Config TBL *******************/

    private void setupFields() {

        tempDynamic = new ArrayList<DBClass>();
        
        txt_patCode.setImmediate(true);
        txt_patInitials.setImmediate(true);
        
        cbx_regLead.setFilteringMode(FilteringMode.CONTAINS);
        cbx_nurses.setFilteringMode(FilteringMode.CONTAINS);
        cbx_internalFirm.setFilteringMode(FilteringMode.CONTAINS);

        //system
        int_maxRep.setMinValue(0);
        int_maxRep.setValue(10);
        
        //internal firm
        cbx_internalFirm.setItemCaptionPropertyId("IF_NAME");
        
        //hinzufügen enabled falls Nurse ausgewählt
        btn_addNurse.setEnabled(false);
        cbx_nurses.setImmediate(true);
        cbx_nurses.addValueChangeListener(new ValueChangeListener() {

            @Override
            public void valueChange(ValueChangeEvent event) {
                Boolean enabled = false;
                if (event.getProperty().getValue() != null) {
                    enabled = true;
                }

                btn_addNurse.setEnabled(enabled);
            }
        });

        conNursesSubs = new IndexedContainer();
        conNursesSubs.addContainerProperty("nurse", String.class, "");
        list_nurses.setContainerDataSource(conNursesSubs);
        list_nurses.setItemCaptionPropertyId("nurse");
        list_nurses.setNullSelectionAllowed(false);

        //Nurse zu Liste hinzufügen
        btn_addNurse.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {
                try {
                    conNursesSubs.addItem(cbx_nurses.getValue()).getItemProperty("nurse")
                            .setValue(cbx_nurses.getItemCaption(cbx_nurses.getValue()));
                } catch (Exception e) {
                }
                cbx_nurses.setValue(null);
            }
        });

        btn_removeNurse.setEnabled(false);
        list_nurses.setImmediate(true);
        list_nurses.addValueChangeListener(new ValueChangeListener() {

            @Override
            public void valueChange(ValueChangeEvent event) {

                if (event.getProperty().getValue() != null) {
                    btn_removeNurse.setEnabled(true);
                }

            }
        });

        btn_removeNurse.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {

                conNursesSubs.removeItem(list_nurses.getValue());
                btn_removeNurse.setEnabled(false);

            }
        });
        
        planningPlan.setImmediate(true);
        planningPlan.setItemCaption(0, i18n.get(caption.planningNone));
        planningPlan.setNullSelectionItemId(0);
        
        planningPlan.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                boolean hasPlan = planningPlan.getValue() != null;
                
                planningStart.setEnabled(hasPlan);
                
                if(hasPlan && planningStart.getValue() == null) {
                    planningStart.setValue(new Date());
                }else {
                    planningStart.setValue(null);
                }
                
            }
        });
        
        planningStart.setImmediate(true);
        planningStart.setEnabled(false);
        
    }
    
    
    private void fillFields() {
        getRl();
        getFirm();
        getStatic();
        getPlanning();
        getNurses();
        fillNurseSubs();
    }


    private void editSaveNewButton(Object itemId) {
        Boolean enabled = true;

        if (itemId != null) {
            enabled = false;
        }
        
        if(!hasMainId()){
            enabled = false;
        }
    }


    /************************************************/
    
    private Boolean validateStatic(){
        
        for (AbstractField field : validateListStatic) {
            if (field.isValid() == false) {
                I18nManager.global(I18nGlobalNotifiers.fields_empty);
                return false;
            }
        }
        
        return true;
    }
    
    private Boolean saveDynamic() {
        
        if(recurrenceManager.getParentId() == null || recurrenceManager.getParentId() == 0) {
            recurrenceManager.setParentIdOnly(Integer.parseInt(getMainId()));
        }
        
        recurrenceManager.saveAndUpdate();
        
        return true;
        
    }
    
    private void generatePlanningDates() {
        
        
        if(planningPlan.getValue() == null
            || planningStart.getValue() == null
            || !hasPatientId()
            || !hasMainId()) {
            log.debug("missing one of the required values - planningPlan: {}, planningStart: {}, patientId: {}, vhId: {}",
                planningPlan.getValue(), planningStart.getValue(), getPatientId(), getMainId());
            return;
        }
        
        log.info("saving planned dates! {}, {}", planningPlan.getValue(), planningStart.getValue());
        
        ServicePlanningCreator spc = new ServicePlanningCreator();
        spc.setVhId(Integer.parseInt(getMainId()));
        spc.setPatientId(Integer.parseInt(getPatientId()));
        spc.setNurseId(Integer.parseInt(getNurseId()));
        
        spc.setParentId((Integer) planningPlan.getValue());
        spc.setStartDate(planningStart.getValue());
        
        ArrayList<Integer> list = spc.generate();
        
        log.info("new entries: {}", list);
        
    }
    
    private void saveNurseSubs() {

        ArrayList<String> currentEntries = new ArrayList<String>();
        ArrayList<String> toDelete = new ArrayList<String>();
        ArrayList<String> toInsert = new ArrayList<String>();

        for (Object id : listNursesSubsDb) {

            String nurse = id.toString();
            currentEntries.add(nurse);

            if (!conNursesSubs.containsId(id)) {
                toDelete.add(nurse);
            }

        }

        for (Object id : conNursesSubs.getItemIds()) {
            String nurse = id.toString();
            if (!currentEntries.contains(nurse)) {
                toInsert.add(nurse);
            }
        }

        //   System.out.println(toDelete.toString());
        //   System.out.println(toInsert.toString());

        CMS_Config_Std std = CMS_Config_Std.getInstance();
        DBClass db = new DBClass();

        db.DB_Data_Insert.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_verk_subs");

        for (String id : toInsert) {

            db.DB_Data_Insert.DB_Daten.DB_Data("cust_verk_subs", "CVS_PROJECT_ID", getProjectId());
            db.DB_Data_Insert.DB_Daten.DB_Data("cust_verk_subs", "CVS_PATIENT_ID", getPatientId());
            db.DB_Data_Insert.DB_Daten.DB_Data("cust_verk_subs", "CVS_NURSE_ID", id);
            db.DB_Data_Insert.DB_Insert();
            db.DB_Data_Insert.DB_Daten.DB_Data_Leeren();
        }

        db.DB_Data_Delete.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_verk_subs");
        //db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_verk_subs");

        for (String id : toDelete) {

            db.DB_Data_Delete.DB_Filter.DB_WHERE_Allgemein("cust_verk_subs", "CVS_PROJECT_ID", "=", getProjectId(), "AND");
            db.DB_Data_Delete.DB_Filter.DB_WHERE_Allgemein("cust_verk_subs", "CVS_PATIENT_ID", "=", "'" + getPatientId() + "'", "AND");
            db.DB_Data_Delete.DB_Filter.DB_WHERE_Allgemein("cust_verk_subs", "CVS_NURSE_ID", "=", "'" + id + "'", "");
            db.DB_Data_Delete.DB_Delete();
            db.DB_Data_Delete.DB_Filter.DB_Data_Leeren();
        }

    }
    
    /********** -> DB Map <- ******************/
    private void setDBMaps() {
        DBMapDynamic = new HashMap<Object, String>();

        DBMapStatic = new HashMap<Object, String>();
        DBMapStatic.put(txt_patCode, "cust_protokoll_servicetasking_meta_static:STMS_PAT_CODE");
        DBMapStatic.put(txt_patInitials, "cust_protokoll_servicetasking_meta_static:STMS_PAT_INITIALS");
        DBMapStatic.put(cbx_regLead, "cust_protokoll_servicetasking_meta_static:STMS_ID_REG_LEAD");
        DBMapStatic.put(int_maxRep, "cust_protokoll_servicetasking_meta_static:STMS_MAX_REP");
        DBMapStatic.put(cbx_internalFirm, "cust_protokoll_servicetasking_meta_static:STMS_KEY_FIRM");

        
    }

    private void setValidateMaps() {
        
        validateListStatic = new ArrayList<AbstractField>();
        validateListStatic.add(txt_patCode);
        validateListStatic.add(txt_patInitials);
        validateListStatic.add(cbx_regLead);

    }

    /********** -> Datenholen <- ******************/
    private void getStatic() {
        CMS_Config_Std std = CMS_Config_Std.getInstance();

        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_protokoll_servicetasking_meta_static");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();

        String wid = getMainId();
        if (wid == null || wid == "") {
            wid = "0";
        }

        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_protokoll_servicetasking_meta_static", "STMS_VH_ID", "=", wid, "");

        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();
        Form_Bind fb = new Form_Bind();

        if (con.size() > 0) {
            staticId = Integer.toString((Integer) con.getItem(1).getItemProperty("STMS_ID").getValue());
            fb.Get_and_Fill(con, DBMapStatic);
        }

    }
    
    private void getPlanning() {
        CustomQuery q = new DBClass().CustomQuery;
        String sql = "select STPL_ID, STPL_NAME from cust_protokoll_servicetasking_plans"
             + "\n " + "where (select count(*) from cust_protokoll_servicetasking_planning where STP_ID_PARENT = STPL_ID) > 0"
             + "\n " + "    and STPL_ID_PROJECT = " + getProjectId();
        q.setSqlString(sql);
        
        try {
            planningPlan.addItem(0);
            new combo(q.query(), planningPlan, "STPL_ID", "STPL_NAME");
        } catch (Exception e) {
            planningPlan.removeAllItems();
        }
    }
    
    private void getRl(){
        CMS_Config_Std std = CMS_Config_Std.getInstance();
        DBClass db = new DBClass();

        
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("SRL_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("AUL_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT("
                + "AUL_VORNAME, ' ', AUL_NAME,"
                + " (CASE WHEN SRL_REGION IS NULL OR SRL_REGION = '' THEN ''ELSE CONCAT(' (', SRL_REGION, ') ') END))", "Regionalleitername");

        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_stammdaten_user", "INNER JOIN", "cust_krankenschwester_stammdaten_anrede", "AUL_ANREDE_ID", "KSA_ID");

        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_stammdaten_regionalleiter", "INNER JOIN", "cms_auth_stammdaten_user", "SRL_ID_USER", "AUL_ID");
        
        
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_stammdaten_regionalleiter", "SRL_ID_PROJEKT", "=", getProjectId(), "");
        
//        db.DB_Data_Get.DB_DEBUG_SQL_STRING();
        
        try {
            combo nc = new combo(db.DB_Data_Get.DB_SEND_AND_GET_Container(), cbx_regLead, "SRL_ID", "Regionalleitername");
        } catch (Exception e) {
            cbx_regLead.removeAllItems();
        }
    }
    
    private void getFirm() {
        
        DBClass db = new DBClass();
        
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("IF_KEY");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("IF_NAME");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_internal_firms");
        
        cbx_internalFirm.setContainerDataSource(MyUtils.convertIndex(db.DB_Data_Get.DB_SEND_AND_GET_Container(), "IF_KEY"));
        
    }
    
    private void getNurses() {
        CMS_Config_Std std = CMS_Config_Std.getInstance();

        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("KSK_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(KSK_TITEL,' ',KSA_NAME,' ',AUL_NAME,' ',AUL_VORNAME)",
                "Krankenschwesternname");

        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("AL_G_ID");

        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_stammdaten_user", "INNER JOIN",
                "cust_krankenschwester_stammdaten_anrede", "AUL_ANREDE_ID", "KSA_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_stammdaten_user", "LEFT JOIN", "cms_auth_liste_gu", "AUL_ID",
                "AL_U_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_liste_gu", "LEFT JOIN", "cust_projekte_stammdaten_liste",
                "AL_G_ID", "PSLV_GROUP");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_krankenschwester_stammdaten_ks", "INNER JOIN",
                "cms_auth_stammdaten_user", "KSK_U_ID", "AUL_ID");

        // System.out.println(ns_projekte.getValue());

        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_projekte_stammdaten_liste", "PSLV_ID", "=", getProjectId(), "");

        // db.DB_Data_Get.DB_DEBUG_SQL_STRING();

        try {
            combo nc = new combo(db.DB_Data_Get.DB_SEND_AND_GET(), cbx_nurses, "KSK_ID", "Krankenschwesternname");
        } catch (Exception e) {
            cbx_nurses.removeAllItems();
            return;
        }

        db.DB_Data_Get.connclose();

    }
    
    private void fillNurseSubs() {

        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("KSK_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CVS_NURSE_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(KSK_TITEL,' ',KSA_NAME,' ',AUL_NAME,' ',AUL_VORNAME)", "Name");

        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_stammdaten_user", "INNER JOIN",
                "cust_krankenschwester_stammdaten_anrede", "AUL_ANREDE_ID", "KSA_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_krankenschwester_stammdaten_ks", "INNER JOIN",
                "cms_auth_stammdaten_user", "KSK_U_ID", "AUL_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_krankenschwester_stammdaten_ks", "INNER JOIN", "cust_verk_subs",
                "KSK_ID", "CVS_NURSE_ID");

        // System.out.println(ns_projekte.getValue());

        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_subs", "CVS_PROJECT_ID", "=", getProjectId(), "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_subs", "CVS_PATIENT_ID", "=", getPatientId(), "");
        
        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();
        
        listNursesSubsDb = new ArrayList();
        conNursesSubs.removeAllItems();
        for (Object itemId : con.getItemIds()) {
            
            Object nurseId = con.getItem(itemId).getItemProperty("CVS_NURSE_ID").getValue();
            String nurseName = (String) con.getItem(itemId).getItemProperty("Name").getValue();
            conNursesSubs.addItem(nurseId);
            conNursesSubs.getItem(nurseId).getItemProperty("nurse").setValue(nurseName);
            
            listNursesSubsDb.add(nurseId);
        }

        

        //db.DB_Data_Get.connclose();
    }

    private HashMap<Integer, Date> getRecurrenceLatestDates(Collection<Integer> delegationIds) {
        
        if(delegationIds == null || delegationIds.size() == 0) {
            return null;
        }
        
        CustomQuery q = new DBClass().CustomQuery;
        String sql = "select ST_ID_DELEGATION as delegationId, max(ST_ORIGINAL_DATE) as max"
             + "\n " + "from cust_protokoll_servicetasking"
             + "\n " + "where ST_ID_DELEGATION IN ("+Joiner.on(",").join(delegationIds)+")"
             + "\n " + "group by ST_ID_DELEGATION";
        q.setSqlString(sql);
//        q.db.debugNextQuery(true);
        Container con =  q.query();
        
        if(con == null) {
            return null;
        }
        
        HashMap<Integer, Date> map = new HashMap<Integer, Date>();
        for (Object iid : con.getItemIds()) {
            
            Item item = con.getItem(iid);
            Integer did =  MyUtils.getValueFromItem(item, "delegationId", Integer.class);
            Timestamp ts = MyUtils.getValueFromItem(con.getItem(iid), "max", java.sql.Timestamp.class);
            
            if(ts != null) {
                map.put(did, new Date(ts.getTime()));
            }

        }
        
        return map;
    }
    
    private Integer dbGetRecurrenceReps() {
        
        if(getMainId() == null) {
            return null;
        }
        
        CustomQuery q = new DBClass().CustomQuery;
        String sql = "select STMS_MAX_REP as reps"
             + "\n " + "from cust_protokoll_servicetasking_meta_static"
             + "\n " + "where STMS_VH_ID = " + getMainId();
        q.setSqlString(sql);
        return MyUtils.getValueFromItem(
            MyUtils.getFirstItemFromContainer(q.query()), "reps", Integer.class);
    }
    
    /**
     * 
     * @param delegationId
     * @return Item [STMD_ID, STMD_VH_ID, STMD_TYPE, STMD_RRULE_START, STMD_RRULE, STMD_RRULE_CUSTOM]
     */
    private RruleItem dbGetRecurrenceRule(Integer delegationId) {
        
        CustomQuery q = new DBClass().CustomQuery;
        String sql = "select * from cust_protokoll_servicetasking_meta_dynamic where STMD_ID = " + delegationId;
        q.setSqlString(sql);
        
        RruleItem ri = new RruleItem(MyUtils.getFirstItemFromContainer(q.query()));
        ri.setPropertyFor(PART.START, "STMD_RRULE_START");
        ri.setPropertyFor(PART.RRULE, "STMD_RRULE");
        ri.setPropertyFor(PART.CUSTOM, "STMD_RRULE_CUSTOM");
        
        return ri;
    }
    
    /* *********************************** */


    private Integer saveStatic() {
        CMS_Config_Std std = CMS_Config_Std.getInstance();
        DBClass db = new DBClass();
        db.DB_Data_Insert.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_protokoll_servicetasking_meta_static");

        Form_Bind fb = new Form_Bind();
        fb.Insert(db, DBMapStatic);

        db.DB_Data_Insert.DB_Daten.DB_Data("cust_protokoll_servicetasking_meta_static", "STMS_VH_ID", getMainId());

        //db.DB_Data_Insert.DB_DEBUG_SQL_STRING();
        return db.DB_Data_Insert.DB_Insert();

    }
    
    private void updateStatic() {
        CMS_Config_Std std = CMS_Config_Std.getInstance();
        DBClass db = new DBClass();
        db.DB_Data_Update.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_protokoll_servicetasking_meta_static");

        Form_Bind fb = new Form_Bind();
        fb.Update(db, DBMapStatic);
        
        db.DB_Data_Update.DB_Filter.DB_WHERE_Allgemein("cust_protokoll_servicetasking_meta_static", "STMS_ID", "=", staticId, "");

        db.DB_Data_Update.DB_Update();

    }
    
    @AutoGenerated
    private VerticalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("-1px");
        mainLayout.setMargin(false);
        mainLayout.setSpacing(true);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("-1px");
        
        // pan_project
        pan_project = buildPan_project();
        mainLayout.addComponent(pan_project);
        
        // panel_1
        pan_dynamic = buildPan_dynamic();
        mainLayout.addComponent(pan_dynamic);
        
        // pan_verwaltung
        pan_verwaltung = buildPan_verwaltung();
        mainLayout.addComponent(pan_verwaltung);
        
        // pan_system
        pan_system = buildPan_system();
        mainLayout.addComponent(pan_system);
        
        return mainLayout;
    }

    @AutoGenerated
    private Panel buildPan_project() {
        // common part: create layout
        pan_project = new Panel();
        pan_project.setCaption("Projektinformationen");
        pan_project.setImmediate(false);
        pan_project.setWidth("100.0%");
        pan_project.setHeight("120px");
        
        // verticalLayout_2
        verticalLayout_2 = buildVerticalLayout_2();
        pan_project.setContent(verticalLayout_2);
        
        return pan_project;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_2() {
        // common part: create layout
        verticalLayout_2 = new VerticalLayout();
        verticalLayout_2.setImmediate(false);
        verticalLayout_2.setWidth("100.0%");
        verticalLayout_2.setHeight("100.0%");
        verticalLayout_2.setMargin(false);
        
        // txt_patCode
        txt_patCode = new TextField();
        txt_patCode.setCaption("Patient Code-Nummer");
        txt_patCode.setImmediate(false);
        txt_patCode.setWidth("200px");
        txt_patCode.setHeight("-1px");
        verticalLayout_2.addComponent(txt_patCode);
        verticalLayout_2.setComponentAlignment(txt_patCode, new Alignment(48));
        
        // txt_patInitials
        txt_patInitials = new TextField();
        txt_patInitials.setCaption("Patient Projektinitialien");
        txt_patInitials.setImmediate(false);
        txt_patInitials.setWidth("200px");
        txt_patInitials.setHeight("-1px");
        verticalLayout_2.addComponent(txt_patInitials);
        verticalLayout_2.setComponentAlignment(txt_patInitials, new Alignment(48));
        
        return verticalLayout_2;
    }

    @AutoGenerated
    private Panel buildPan_dynamic() {
        // common part: create layout
        pan_dynamic = new Panel();
        pan_dynamic.setCaption("Delegationen");
        pan_dynamic.setImmediate(false);
        pan_dynamic.setWidth("100.0%");
        pan_dynamic.setHeight("260px");
        
        // verticalLayout_5
        verticalLayout_5 = buildVerticalLayout_5();
        pan_dynamic.setContent(verticalLayout_5);
        
        return pan_dynamic;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_5() {
        // common part: create layout
        verticalLayout_5 = new VerticalLayout();
        verticalLayout_5.setImmediate(false);
        verticalLayout_5.setWidth("100.0%");
        verticalLayout_5.setHeight("100.0%");
        verticalLayout_5.setMargin(false);
        verticalLayout_5.setSpacing(true);
        
        // recurrenceManager
        recurrenceManager = new RecurrenceManager();
        recurrenceManager.setImmediate(false);
        recurrenceManager.setWidth("100.0%");
        recurrenceManager.setHeight("100.0%");
        verticalLayout_5.addComponent(recurrenceManager);
        verticalLayout_5.setExpandRatio(recurrenceManager, 1.0f);
        
        // horizontalLayout_2
        horizontalLayout_2 = buildHorizontalLayout_2();
        verticalLayout_5.addComponent(horizontalLayout_2);
        verticalLayout_5.setExpandRatio(recurrenceManager, 1.0f);
        
        return verticalLayout_5;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_2() {
        // common part: create layout
        horizontalLayout_2 = new HorizontalLayout();
        horizontalLayout_2.setImmediate(false);
        horizontalLayout_2.setWidth("100.0%");
        horizontalLayout_2.setHeight("-1px");
        horizontalLayout_2.setMargin(false);
        horizontalLayout_2.setSpacing(true);
        
        // planningPlan
        planningPlan = new ComboBox();
        planningPlan.setCaption("Initialplanung generieren");
        planningPlan.setImmediate(false);
        planningPlan.setWidth("100.0%");
        planningPlan.setHeight("-1px");
        horizontalLayout_2.addComponent(planningPlan);
        horizontalLayout_2.setExpandRatio(planningPlan, 2.0f);
        horizontalLayout_2.setComponentAlignment(planningPlan, new Alignment(48));
        
        // planningStart
        planningStart = new PopupDateField();
        planningStart.setCaption("Startdatum");
        planningStart.setImmediate(false);
        planningStart.setWidth("100.0%");
        planningStart.setHeight("-1px");
        horizontalLayout_2.addComponent(planningStart);
        horizontalLayout_2.setExpandRatio(planningStart, 1.0f);
        horizontalLayout_2.setComponentAlignment(planningStart, new Alignment(48));
        
        return horizontalLayout_2;
    }

    @AutoGenerated
    private Panel buildPan_verwaltung() {
        // common part: create layout
        pan_verwaltung = new Panel();
        pan_verwaltung.setCaption("Verwaltungsdaten");
        pan_verwaltung.setImmediate(false);
        pan_verwaltung.setWidth("100.0%");
        pan_verwaltung.setHeight("310px");
        
        // verticalLayout_4
        verticalLayout_4 = buildVerticalLayout_4();
        pan_verwaltung.setContent(verticalLayout_4);
        
        return pan_verwaltung;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_4() {
        // common part: create layout
        verticalLayout_4 = new VerticalLayout();
        verticalLayout_4.setImmediate(false);
        verticalLayout_4.setWidth("100.0%");
        verticalLayout_4.setHeight("-1px");
        verticalLayout_4.setMargin(false);
        verticalLayout_4.setSpacing(true);
        
        // cbx_internalFirm
        cbx_internalFirm = new ComboBox();
        cbx_internalFirm.setCaption("Infusionsfirma");
        cbx_internalFirm.setImmediate(false);
        cbx_internalFirm.setWidth("200px");
        cbx_internalFirm.setHeight("-1px");
        verticalLayout_4.addComponent(cbx_internalFirm);
        verticalLayout_4.setComponentAlignment(cbx_internalFirm, new Alignment(48));
        
        // cbx_regLead
        cbx_regLead = new ComboBox();
        cbx_regLead.setCaption("Regionalleiter");
        cbx_regLead.setImmediate(false);
        cbx_regLead.setWidth("200px");
        cbx_regLead.setHeight("-1px");
        verticalLayout_4.addComponent(cbx_regLead);
        verticalLayout_4.setComponentAlignment(cbx_regLead, new Alignment(48));
        
        // cbx_nurses
        cbx_nurses = new ComboBox();
        cbx_nurses.setCaption("Vertretungsnurse");
        cbx_nurses.setImmediate(false);
        cbx_nurses.setWidth("200px");
        cbx_nurses.setHeight("-1px");
        verticalLayout_4.addComponent(cbx_nurses);
        verticalLayout_4.setComponentAlignment(cbx_nurses, new Alignment(48));
        
        // horizontalLayout_3
        horizontalLayout_3 = buildHorizontalLayout_3();
        verticalLayout_4.addComponent(horizontalLayout_3);
        verticalLayout_4.setComponentAlignment(horizontalLayout_3, new Alignment(48));
        
        // list_nurses
        list_nurses = new ListSelect();
        list_nurses.setCaption("Vertretungsnurses");
        list_nurses.setImmediate(false);
        list_nurses.setWidth("200px");
        list_nurses.setHeight("80px");
        verticalLayout_4.addComponent(list_nurses);
        verticalLayout_4.setComponentAlignment(list_nurses, new Alignment(48));
        
        return verticalLayout_4;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_3() {
        // common part: create layout
        horizontalLayout_3 = new HorizontalLayout();
        horizontalLayout_3.setImmediate(false);
        horizontalLayout_3.setWidth("-1px");
        horizontalLayout_3.setHeight("-1px");
        horizontalLayout_3.setMargin(false);
        horizontalLayout_3.setSpacing(true);
        
        // btn_addNurse
        btn_addNurse = new Button();
        btn_addNurse.setCaption("hinzufügen");
        btn_addNurse.setImmediate(true);
        btn_addNurse.setWidth("95px");
        btn_addNurse.setHeight("-1px");
        horizontalLayout_3.addComponent(btn_addNurse);
        
        // btn_removeNurse
        btn_removeNurse = new Button();
        btn_removeNurse.setCaption("entfernen");
        btn_removeNurse.setImmediate(true);
        btn_removeNurse.setWidth("95px");
        btn_removeNurse.setHeight("-1px");
        horizontalLayout_3.addComponent(btn_removeNurse);
        
        return horizontalLayout_3;
    }

    @AutoGenerated
    private Panel buildPan_system() {
        // common part: create layout
        pan_system = new Panel();
        pan_system.setCaption("Systemeinstellungen");
        pan_system.setImmediate(false);
        pan_system.setWidth("100.0%");
        pan_system.setHeight("80px");
        
        // verticalLayout_3
        verticalLayout_3 = buildVerticalLayout_3();
        pan_system.setContent(verticalLayout_3);
        
        return pan_system;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_3() {
        // common part: create layout
        verticalLayout_3 = new VerticalLayout();
        verticalLayout_3.setImmediate(false);
        verticalLayout_3.setWidth("100.0%");
        verticalLayout_3.setHeight("100.0%");
        verticalLayout_3.setMargin(false);
        
        // int_maxRep
        int_maxRep = new IntStepper();
        int_maxRep.setCaption("Anzahl Blankos");
        int_maxRep.setImmediate(false);
        int_maxRep.setWidth("-1px");
        int_maxRep.setHeight("-1px");
        verticalLayout_3.addComponent(int_maxRep);
        verticalLayout_3.setComponentAlignment(int_maxRep, new Alignment(48));
        
        return verticalLayout_3;
    }

}
