package archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Prescriptions.BalanceManager.form;

import java.math.BigDecimal;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

import org.tepi.filtertable.FilterTable;

import archenoah.config.CMS_Config_Std;
import archenoah.lib.custom.ComponentIterator;
import archenoah.lib.custom.MyUtils;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.tool.comunication.dbclass.DBClass.CustomQuery;
import archenoah.lib.vaadin.Components.ClickMenuBar.ClickCommand;
import archenoah.lib.vaadin.Components.Combo.combo;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Tab_Menue_Item;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Window_Button;
import archenoah.lib.vaadin.Components.table.DataviewGenerator;
import archenoah.lib.vaadin.Components.table.FilteringTableUpdater;
import archenoah.lib.vaadin.CustomConverterFactorys.DataviewConverter;
import archenoah.lib.vaadin.CustomConverterFactorys.StringSqlTimestampConverter;
import archenoah.lib.vaadin.Language.i18n.I18nCB;
import archenoah.lib.vaadin.Language.i18n.I18nConverter;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.lib.vaadin.MenuBerechtigung.Rechteholen;
import archenoah.lib.vaadin.resources.Icons;
import archenoah.web.normal.UserInfo.Country;
import archenoah.web.normal.UserInfo.Nurse;
import archenoah.web.normal.UserInfo.ProjectManager;
import archenoah.web.normal.UserInfo.UserData;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.OpenTickets.form.OpenTicketsInsertEdit;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Prescriptions.PrescriptionManager.form.PrescriptionManagerInsertEdit;

import com.google.common.base.Joiner;
import com.google.gwt.thirdparty.guava.common.base.Strings;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Container.ItemSetChangeEvent;
import com.vaadin.data.Container.ItemSetChangeListener;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.event.UIEvents.PollEvent;
import com.vaadin.event.UIEvents.PollListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.ui.AbstractField;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.Window.CloseEvent;
import com.vaadin.ui.Window.CloseListener;


@SuppressWarnings({"serial", "rawtypes", "unchecked"})
public class BalanceManagerDataView extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
	private HorizontalLayout mainLayout;

	@AutoGenerated
	private VerticalLayout mainContainer;

	@AutoGenerated
	private FilterTable tbl_data;

	@AutoGenerated
	private HorizontalLayout globalFilterContainer;

	@AutoGenerated
	private HorizontalLayout filterLayoutProduct;

	@AutoGenerated
	private ComboBox filterProduct;

	@AutoGenerated
	private HorizontalLayout filterLayoutPatient;

	@AutoGenerated
	private ComboBox filterPatient;

	@AutoGenerated
	private CheckBox filterAll;

	@AutoGenerated
	private VerticalLayout menuSpacer;

	@AutoGenerated
	private MenuBar men_frm;

	

	

	

	

	

	

	

	

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */

    /**************** --> Allgemein <--- ********************/
	
	private static org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(BalanceManagerDataView.class);
	
    // Datenbank
    private Map<Object, String> componentMap;
    private FilteringTableUpdater tableUpdater = null;

    // Berrechtigung
    private int ACC_ID;

    private int permRead;
    private int permCreate;
    private int permUpdate;
    private int permDelete;

    private MenuItem tmpMenu = null;

    private Button tmpButton = null;
    /******************************************************/
    /**************** --> Tabsheetvars <--- *****************/
    private TabSheet tab = null;

    /******************************************************/
    /**************** --> Windowvars <--- *******************/
    private Window win = null;
    /******************************************************/

    private DetachListener onDetach = null;

    /******************* -> Menüpunkte <- ********************/
//    private MenuBar.MenuItem btn_create;
    private MenuBar.MenuItem btn_update;
//    private MenuBar.MenuItem btn_read;
//    private MenuBar.MenuItem btn_delete;
    private MenuBar.MenuItem btn_filter;
    private MenuBar.MenuItem btn_ticket;
    private MenuBar.MenuItem btn_presc;

    
    /*******************************************************/
    /******************* --> Custom <--- ********************/
    /******************************************************/

    private Boolean firstFilter = true;
    private PollListener pollListener = null;
    
    enum Status {}
    
    /************ ----->Einstellungen<-- ********************/
//    private final String formIdLng = "203";
    private final String formIdPerm = "203";
    private final String winHeight = "600px";
    private final String winWidth = "900px";


    /******************************************************/

    private final String tableIdCol = "PSL_ID";
    
    //TASK cols
    private final Object[] tableColsAll = new Object[] { "PSL_ID", "PSL_NAME", "PSL_VORNAME", "PSL_STRASSE", "PSL_ORT", "PSL_PLZ", "PB_CREATED", "PP_PRODUCT", "balance", "PBA_ACTION", "PB_DELTA", "PB_BALANCE", "PB_COMMENT", "dataUser", "ticketId", "prescriptionId"};
    //use custom Cols when needed
    private Object[] tableColsDefault = new Object[] { "PSL_ID", "PSL_NAME", "PSL_VORNAME", "PSL_STRASSE", "PSL_ORT", "PSL_PLZ", "PB_CREATED", "PP_PRODUCT", "balance"};
    private Object[] tableColsPatient = new Object[] { "PB_CREATED", "PP_PRODUCT", "PBA_ACTION", "PB_DELTA", "PB_BALANCE", "ticketId", "prescriptionId", "dataUser", "PB_COMMENT"};
    //use custom Cols when needed
    private Object[] tableColsActive = tableColsDefault;

    private boolean firstPatient = true;
    
    private String patientIds;

    private I18nManager i18n;

    private final static class caption extends I18nCB {
        static final I18nCB combo_all = set();
    }
    
    /******************************************************/

    public BalanceManagerDataView(MenuItem Arg_Menü) {
        tmpMenu = Arg_Menü;
    }

    public BalanceManagerDataView(Button Arg_btn) {
        tmpButton = Arg_btn;
    }

    /***************************** ---> Feste Funtionen<--- **************************************/

    /********* INIT-Window ************/
    public void init() {

        Standard_Init();

        if (tmpMenu != null) {
            String Recourcename = tmpMenu.getIcon().toString();
            Recourcename = Recourcename.substring(0, Recourcename.length() - 12) + "white-16.png";

            Build_Window_Button bwb = new Build_Window_Button(tmpMenu.getText(), mainLayout, winHeight, winWidth,
                    new ThemeResource(Recourcename));
            win = bwb.ReturnWindow();
        }
        if (tmpButton != null) {
            Build_Window_Button bwb = new Build_Window_Button(tmpButton.getCaption(), mainLayout, winHeight, winWidth,
                    tmpButton.getIcon());
            win = bwb.ReturnWindow();
        }

        win.addDetachListener(onDetach);

    }
    
    public Window getWindow(){
    	return win;
    }
    
    public TabSheet getTabSheet(){
    	return tab;
    }
    
    public void init(TabSheet Arg_tab) {

        Standard_Init();
        tab = Arg_tab;
        if (tmpMenu != null) {
            new Build_Tab_Menue_Item(Arg_tab, tmpMenu.getText(), mainLayout, tmpMenu.getIcon());
        }
        if (tmpButton != null) {
            new Build_Tab_Menue_Item(Arg_tab, tmpButton.getCaption(), mainLayout, tmpButton.getIcon());
        }

        tab.getSelectedTab().addDetachListener(onDetach);
    }

    /********* Init-Standard ************/
    private void Standard_Init() {
        buildMainLayout();
        i18n = new I18nManager(this);
        
        registerComponents();
        
        generateMenu();
        
        setMenuPermissions();

        updateTable();
        tbl_data.setSortContainerPropertyId(tableIdCol);
        tbl_data.setSortAscending(true);
        tbl_data.sort();
        configureTable();
        configureComponents();

        
        updateTable();
        
        setupListenersAndDetachEvent();
        i18n.refresh();
    }
    
    // register components for lng and validation tools
    private void registerComponents(){
    	componentMap = new HashMap<Object, String>();
    	new ComponentIterator(mainContainer).createMap(componentMap);
    }
    
    private void setupListenersAndDetachEvent() {
        pollListener = new PollListener() {

            @Override
            public void poll(PollEvent event) {
                if(tab.isRendered(mainLayout)){
                    updateTable();
                }
            }
        };

        UI.getCurrent().getUI().addPollListener(pollListener);

        onDetach = new DetachListener() {

            @Override
            public void detach(DetachEvent event) {
                UI.getCurrent().getUI().removePollListener(pollListener);
            }
        };
    }
    
    @SuppressWarnings("unused")
    public void setPermissionsFromDatabase() {
        if (formIdPerm == "") {
            System.out.println("Form Einstellung Fehlt: Berechtigung");
            return;
        }

        ACC_ID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        Rechteholen r = new Rechteholen(ACC_ID + "");
        String[][] perms = r.Datenholen();

        for (int i = 0; i < perms.length; i++) {
            if (perms[i][0].equals(formIdPerm) == true) {

                permRead = Integer.valueOf(perms[i][3]);
                permUpdate = Integer.valueOf(perms[i][4]);
                permCreate = Integer.valueOf(perms[i][6]);
                permDelete = Integer.valueOf(perms[i][5]);
                
            }
        }
    }

    public void setPermissions(int create, int read, int update, int delete) {

        permCreate = create;
        permRead = read;
        permUpdate = update;
        permDelete = delete;

    }

    private void setMenuPermissions() {
        Boolean c = (permCreate == 1);
        Boolean r = (permRead == 1);
        Boolean u = (permUpdate == 1);
        Boolean d = (permDelete == 1);

//        btn_create.setEnabled(c);
//        btn_create.setVisible(c);
//
//        btn_read.setEnabled(r);
//        btn_read.setVisible(r);
//
        btn_update.setEnabled(u);
        btn_update.setVisible(u);
//
//        btn_delete.setEnabled(d);
//        btn_delete.setVisible(d);
        
        btn_ticket.setEnabled(r);
        btn_presc.setEnabled(r);
    }

    /************ -><- ******************/

    /***************** Comands *********************/
    
    CloseListener closeListener = new CloseListener() {
		
		@Override
		public void windowClose(CloseEvent e) {
			updateTable(true);
		}
	};
    
	private String getSelectedValue(){
		return Integer.toString((Integer) tbl_data.getContainerProperty(tbl_data.getValue(), tableIdCol).getValue());
	}
	
//    //TASK Commands are here
//    public Command cmd_btn_add = new Command() {
//        @Override
//        public void menuSelected(MenuItem selectedItem) {
//        
//        	BalanceManagerInsertEdit pie = new BalanceManagerInsertEdit(selectedItem, "");
//        	pie.setPermissions(permCreate, permRead, permUpdate, permDelete);
//        	pie.init();
//        	pie.getWindow().addCloseListener(closeListener);
//        	
//        }
//    };
//    
//    public Command cmd_btn_read = new Command() {
//        @Override
//        public void menuSelected(MenuItem selectedItem) {
//
//            if(tbl_data.getValue() == null){
//	        I18nManager.global(I18nGlobalNotifiers.no_entry_selected);
//                return;
//            }
//            
//            BalanceManagerInsertEdit pie = new BalanceManagerInsertEdit(selectedItem, getSelectedValue());
//        	pie.setPermissions(0, permRead, 0, 0);
//        	pie.init();
//
//
//        }
//    };
    
    public ClickCommand cmd_btn_edit = new ClickCommand() {
        @Override
        public void menuClicked(MenuItem selectedItem) {
            
            
            BalanceManagerInsertEdit pie = new BalanceManagerInsertEdit(selectedItem, "");
        	pie.setPermissions(permCreate, permRead, permUpdate, permDelete);
        	pie.init();
        	pie.getWindow().addCloseListener(closeListener);
        	
        	if(tbl_data.getValue() != null) {
        	    pie.fillFromItem(tbl_data.getContainerDataSource().getItem(tbl_data.getValue()));
        	}
            
        	this.setParent(men_frm);
        	this.setWindow(pie.getWindow());
        }
    };
//
//    public Command cmd_btn_del = new Command() {
//        @Override
//        public void menuSelected(MenuItem selectedItem) {
//            
//            if(tbl_data.getValue() == null){
// I18nManager.global(I18nGlobalNotifiers.no_entry_selected);
//                return;
//            }
//            
//            deleteData(getSelectedValue());
//
//        }
//    };

    public ClickCommand cmd_btn_filter = new ClickCommand() {
        @Override
        public void menuClicked(MenuItem selectedItem) {

            if (firstFilter) {
                tbl_data.setFilterBarVisible(true);
                tbl_data.setFilterBarVisible(false);
                firstFilter = false;
            }
            tbl_data.setFilterBarVisible(!tbl_data.isFilterBarVisible());
            
            if(!tbl_data.isFilterBarVisible()){
                tbl_data.clearFilters();
            }

        }
    };
    
    public ClickCommand cmd_btn_ticket = new ClickCommand() {
        
        @Override
        public void menuClicked(MenuItem selectedItem) {
            
            Long tid = MyUtils.getValueFromItem(tbl_data.getItem(tbl_data.getValue()), "ticketId", Long.class);
            
            log.info("ticket {}", tid);
            
            if(tid == null) {
                return;
            }
            
            OpenTicketsInsertEdit pie = new OpenTicketsInsertEdit(selectedItem, Objects.toString(tid));
            pie.setPermissions(0, permRead, 0, 0);
            pie.init();
            
            this.setParent(men_frm);
            this.setWindow(pie.getWindow());
            
        }
    };

    public ClickCommand cmd_btn_presc = new ClickCommand() {
        
        @Override
        public void menuClicked(MenuItem selectedItem) {
            
            Long pid = MyUtils.getValueFromItem(tbl_data.getItem(tbl_data.getValue()), "prescriptionId", Long.class);
            log.info("presc {}", pid);
            
            if(pid == null) {
                return;
            }
            
            PrescriptionManagerInsertEdit pie = new PrescriptionManagerInsertEdit(selectedItem, Objects.toString(pid));
            pie.setPermissions(0, permRead, 0, 0);
            pie.init();
            
            this.setParent(men_frm);
            this.setWindow(pie.getWindow());
        }
    };
    
    /******************************************/

    
    

    /*********** Gen Menüs *************/
    private void generateMenu() {

//        btn_create = men_frm.addItem("FRM_ADD", Icons.White.add_16, cmd_btn_add);
        btn_update = men_frm.addItem("FRM_EDIT", Icons.White.edit_16, cmd_btn_edit);
//        btn_read = men_frm.addItem("FRM_READ", Icons.White.perm_lesen_16, cmd_btn_read);
//        btn_delete = men_frm.addItem("FRM_DEL", Icons.White.delete_16, cmd_btn_del);
        
        btn_filter = men_frm.addItem("FRM_FILTER", Icons.White.filter_16, cmd_btn_filter);
        
        btn_ticket = men_frm.addItem("FRM_TICKET", Icons.White.backup_16, cmd_btn_ticket);
        btn_presc = men_frm.addItem("FRM_PRESC", Icons.White.log_16, cmd_btn_presc);

    }
    
    private void configureComponents(){
       
//    	for (Entry<Object, String> entry : componentMap.entrySet()) {
//    		AbstractComponent field = (AbstractComponent) entry.getKey();
//    		
//			field.setImmediate(true);
//			
//			
//			if(field instanceof ComboBox){
//				((ComboBox)field).setFilteringMode(FilteringMode.CONTAINS);
//			}
//			
//			if(!(field instanceof PopupDateField)){
//				field.setWidth("180px");
//			}
//
//		}
        
    	filterAll.setImmediate(true);
    	
    	filterPatient.setWidth("178px");
		filterPatient.setFilteringMode(FilteringMode.CONTAINS);
		filterPatient.setImmediate(true);
		dbGetPatients();
		
		filterProduct.setFilteringMode(FilteringMode.CONTAINS);
		filterProduct.setImmediate(true);
		dbGetProducts();
		
		btn_ticket.setVisible(false);
		btn_presc.setVisible(false);
    	
		addComponentListeners();
    }
    
    private void addComponentListeners(){
    	
    	ValueChangeListener vcl = new ValueChangeListener() {
			
			@Override
			public void valueChange(ValueChangeEvent event) {
				
			    tableColsActive = filterPatient.getValue() != null ? tableColsPatient :  tableColsDefault;
			    
				updateTable(true);
				if(firstPatient) {
				    i18n.refresh();
				    firstPatient = false;
				}
				
			}
		};
    	
    	filterPatient.addValueChangeListener(vcl);
    	filterProduct.addValueChangeListener(vcl);
    	filterAll.addValueChangeListener(vcl);
    	
    }
    
    private ArrayList<AbstractField> getActiveGlobalFilters(){
        ArrayList<AbstractField> al = new ArrayList<AbstractField>();
        
        if(filterPatient.getValue() != null){
        	al.add(filterPatient);
        }
        
        if(filterProduct.getValue() != null){
        	al.add(filterProduct);
        }
        
        return al;
    }
    
    private Boolean hasGlobalFilters(ArrayList a){
        
        return (a.size() > 0);
        
    }
    
    private Boolean hasGlobalFilters(){
        
        return hasGlobalFilters(getActiveGlobalFilters());
        
    }
    
    /*************************** Config TBL ********************/

    private void configureTable() {
        tbl_data.setSelectable(true);
        tbl_data.setFilterOnDemand(false);
        tbl_data.setImmediate(true);
        tbl_data.setColumnCollapsingAllowed(false);
        tbl_data.setFooterVisible(true);
        tbl_data.setPageLength(1);
        try {
        	if(tableColsDefault.length > 0){
        		tbl_data.setVisibleColumns(tableColsDefault);
        	}
		} catch (Exception e) {

		}
        
        if(tbl_data.size() > 0){
            
            StringSqlTimestampConverter date = new StringSqlTimestampConverter();
            date.setDateFormat(DateFormat.SHORT);
            
            StringSqlTimestampConverter time = new StringSqlTimestampConverter();
            time.setDateFormat(DateFormat.SHORT);
            time.setTimeFormat(DateFormat.SHORT);
            
            tbl_data.setConverter("PB_CREATED", time);
            
            I18nConverter lng = new I18nConverter("cust_prescription_balance_actions", "PBA_ACTION", "PBA_ACTION");
            tbl_data.setConverter("PBA_ACTION", lng);
            
            HashMap<String, DataviewConverter> converterMap = new HashMap<String, DataviewConverter>();
            converterMap.put("PBA_ACTION", lng);
            tbl_data.setFilterOnDemand(false);
            tbl_data.setFilterGenerator(new DataviewGenerator(converterMap));
        }
        
        tableUpdater = new FilteringTableUpdater(tbl_data);
        
        tbl_data.addItemSetChangeListener(new ItemSetChangeListener() {
            
            @Override
            public void containerItemSetChange(ItemSetChangeEvent event) {
                
                updateSums();
                
            }
        });
        tbl_data.addValueChangeListener(new ValueChangeListener() {

            @Override
            public void valueChange(ValueChangeEvent event) {

                Item item = tbl_data.getContainerDataSource().getItem(tbl_data.getValue());

                btn_ticket.setVisible(tbl_data.getValue() != null
                    && MyUtils.getValueFromItem(item, "ticketId", Long.class) != null);

                btn_presc.setVisible(tbl_data.getValue() != null
                    && MyUtils.getValueFromItem(item, "prescriptionId", Long.class) != null);

            }
        });

        for (Object col : tableColsAll) {
        	
        	try {
        		tbl_data.setColumnExpandRatio(col, 1);
			} catch (Exception e) {
				
			}
        		
		}
        
        tbl_data.setColumnExpandRatio("PSL_ID", 0f);
        tbl_data.setColumnExpandRatio("PB_COMMENT", 5f);
    }

    /*************************** Database ********************/
    
    /********************************/
    
    
    private void updateTable(){
        updateTable(false);
    }
    
    private void updateTable(Boolean ignoreFilter) {

        if (ignoreFilter || !tbl_data.isFilterBarVisible()) {
            dbGetContainer();
            try{
            	if(tableColsDefault.length > 0){
            		tbl_data.setVisibleColumns(tableColsActive);
            	}
            }catch(Exception e){
                
            }
        }
        
        i18n.setTableHeaders();
        updateSums();
        
    }
    
    private void updateSums() {
        if(filterProduct.getValue() != null && filterPatient.getValue() == null) {
            Container con = tbl_data.getContainerDataSource();
            BigDecimal sum = new BigDecimal(0);
            for (Object iid : con.getItemIds()) {
                sum = sum.add(MyUtils.getValueFromItem(tbl_data.getItem(iid), "balance", BigDecimal.class));
            }
            tbl_data.setColumnFooter("balance", "Σ " + sum);
        }else {
            tbl_data.setColumnFooter("balance", null);
        }
        
        if(filterPatient.getValue() != null) {
            Container con = tbl_data.getContainerDataSource();
            Integer sum = 0;
            for (Object iid : con.getItemIds()) {
                sum += MyUtils.getValueFromItem(tbl_data.getItem(iid), "PB_DELTA", Integer.class);
            }
            tbl_data.setColumnFooter("PB_BALANCE", "Σ " + sum);
        }else {
            tbl_data.setColumnFooter("PB_BALANCE", null);
        }
    }
    
    //TASK dbget
	private void dbGetContainer() {
       
        
        /**************************************/
        /************ Set Filter *************/
        
        Country uc = MyUtils.getUserData().getCountry();
        
        ArrayList<AbstractField> filterList = getActiveGlobalFilters(); 
        String glue = "";
        String filterString = "";
        if(uc.hasPermissions()) {
            filterString += uc.getFilterCondition("PSL_COUNTYCODE") + (hasGlobalFilters(filterList) || isLimited() ? "AND " : "");
        }
        
        if(isLimited()) {
            
            glue = hasGlobalFilters(filterList) ? " AND " : "";
            filterString += "PB_ID_PATIENT IN (" + getNursePatientIds() + ")" + glue;
        }
        
        String joinString = filterAll.getValue() ? "left join" : "inner join";
        
        if(filterPatient.getValue() != null){

          filterList.remove(filterPatient);
          glue = hasGlobalFilters(filterList) ? " AND " : "";
          
          filterString += "PB_ID_PATIENT = " + filterPatient.getValue() + glue;
        	
        }
        
        if(filterProduct.getValue() != null){

            filterList.remove(filterProduct);
            glue = hasGlobalFilters(filterList) ? "AND" : "";
            
            filterString += "PP_ID = " + filterProduct.getValue() + glue;
          	
          }

        
        /**************************************/
        /************ Set Tabelle *************/
        
        Boolean patientView = filterPatient.getValue() != null;
        
        
        String sql = "";
        
        
        if(patientView) {
            
            sql = "select "
            + "\n " + "    PB_CREATED,"
            + "\n " + "    PP_PRODUCT,"
            + "\n " + "    PBA_ACTION,"
            + "\n " + "    PB_DELTA,"
            + "\n " + "    PB_BALANCE,"
            + "\n " + "    PB_COMMENT,"
            + "\n " + "    COALESCE(tickets.OMT_ID, retro.OMT_ID) as ticketId,"
            + "\n " + "    COALESCE(rxt.PL_ID, rxr.PL_ID) as prescriptionId,"
            + "\n " + "    COALESCE(CONCAT(ticketUser.AUL_VORNAME, ' ', ticketUser.AUL_NAME),"
            + "\n " + "    CONCAT(prescriptionUser.AUL_VORNAME, ' ', prescriptionUser.AUL_NAME),"
            + "\n " + "    CONCAT(manualUser.AUL_VORNAME, ' ', manualUser.AUL_NAME)) as dataUser,"
            + "\n " + "    # used by balanceInsertEdit"
            + "\n " + "    PP_ID_PROJECT,"
            + "\n " + "    PSL_ID,"
            + "\n " + "    PP_ID"
            + "\n " + "from cust_prescriptions_balance"
            + "\n " + "left join cust_prescriptions_products on PB_ID_PRODUCT = PP_ID"
            + "\n " + "left join cust_prescription_balance_actions on PB_ACTION = PBA_ID"
            + "\n " + ""
            + "\n " + "left join cust_ordermanager_tickets as tickets on PB_ACTION = 2 and PB_ACTION_DATA = OMT_ID # join ticket directly if data available"
            + "\n " + "left join   (SELECT OMT_ID, OMT_ID_USER, OMT_STATUS_SENT_DATE, OMTC_ID_PATIENT, OMTC_ID_PRODUCT from # else try and find corresponding ticket"
            + "\n " + "   cust_ordermanager_tickets "
            + "\n " + "   left join cust_ordermanager_ticket_contents on OMT_ID = OMTC_ID_TICKET) as retro"
            + "\n " + "    on PB_CREATED = retro.OMT_STATUS_SENT_DATE"
            + "\n " + "    and PB_ID_PATIENT = retro.OMTC_ID_PATIENT"
            + "\n " + "       and PB_ID_PRODUCT = retro.OMTC_ID_PRODUCT"
            + "\n " + "    and PB_ACTION = 2"
            + "\n " + "    "
            + "\n " + "left join cust_prescriptions_list as rxt on PB_ACTION = 1 and PB_ACTION_DATA = PL_ID # join prescription directly if data available"
            + "\n " + "left join   (select PL_ID, PL_ID_USER, PL_CREATED, PL_UPDATED, PL_ID_PATIENT, PLE_ID_PRODUCT from cust_prescriptions_list_entries # else try and find corresponding prescription"
            + "\n " + "    left join cust_prescriptions_list on PLE_PL_ID = PL_ID) as rxr"
            + "\n " + "    on (PB_CREATED = rxr.PL_CREATED or PB_CREATED = rxr.PL_UPDATED)"
            + "\n " + "    and PB_ID_PATIENT = rxr.PL_ID_PATIENT"
            + "\n " + "       and PB_ID_PRODUCT = rxr.PLE_ID_PRODUCT"
            + "\n " + "    and PB_ACTION = 1"
            + "\n " + ""
            + "\n " + "left join cms_auth_stammdaten_user as ticketUser on PB_ACTION = 2 and (tickets.OMT_ID_USER = ticketUser.AUL_ID or  retro.OMT_ID_USER = ticketUser.AUL_ID )"
            + "\n " + "left join cms_auth_stammdaten_user as prescriptionUser on PB_ACTION = 1 and (prescriptionUser.AUL_ID = rxt.PL_ID_USER or prescriptionUser.AUL_ID = rxr.PL_ID_USER)"
            + "\n " + "left join cms_auth_stammdaten_user as manualUser on PB_ACTION NOT IN (1, 2) and manualUser.AUL_ID = PB_ACTION_DATA "
            + "\n " + "left join cust_patient_stammdaten_liste on PB_ID_PATIENT = PSL_ID";
            
        }else {
            
            sql = "select * "
            + "\n " + " "
            + "\n " + " from view_patient_stammdaten_liste"
            + "\n " + " inner join view_balance_rx on PB_ID_PATIENT = PSL_ID"
            + "\n " + " left join cust_prescriptions_products on PB_ID_PRODUCT = PP_ID"
            + "\n " + " left join cust_prescription_balance_actions on PB_ACTION = PBA_ID";
            
        }
        
        String groupAndOrder = patientView ? "GROUP BY PB_ID ORDER BY PB_CREATED ASC" : "GROUP BY PSL_ID, PB_ID_PRODUCT";
        sql += "\n "+ ("".equals(filterString) ? "" : " WHERE ") + filterString
            + "\n "+ groupAndOrder;
        
        CustomQuery q = new DBClass().CustomQuery;
        q.setSqlString(sql);
//        q.db.debugNextQuery(true);
        
        try {
        	Container container = q.query();
            
        	if (tableUpdater != null) {
                tableUpdater.updateTable(container);
            } else {
                tbl_data.setContainerDataSource(container);
            }
        	
		} catch (Exception e) {
			// TASK: handle exception
			System.out.println("exception!");
			UI.getCurrent().getUI().removePollListener(pollListener);
		}
        
    }
    
    private String generateCollectionString(Collection<Integer> ids){
        String in = "";
        String comma = "";
        
        for (Integer integer : ids) {
            in += comma + integer;
            if(Strings.isNullOrEmpty(comma)){
                comma = ", ";
            }
        }
        
        return in;
    }
    
    private void dbDeleteData(String id){
    
        CMS_Config_Std std = CMS_Config_Std.getInstance();
    
        DBClass db = new DBClass();
        db.DB_Data_Delete.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_prescriptions_list");
        db.DB_Data_Delete.DB_Filter.DB_WHERE_Allgemein("cust_prescriptions_list", tableIdCol, "=", id, "");
        db.DB_Data_Delete.DB_Delete();
    
        I18nManager.global(I18nGlobalNotifiers.entry_deleted);
        
        updateTable(true);

        
    }
    
    private boolean isLimited() {
        return UserData.get().getNurse().isNurse() && !UserData.get().getRegionalManager().isRegionalManager();
    }
    
    private String getNursePatientIds() {
        
        if(patientIds != null) {
            return patientIds;
        }
        
        ProjectManager pm = UserData.get().getProjectManager(); 
        Nurse nurse = UserData.get().getNurse();
        
        String pl = "";
        if(pm.isProjectManager()) {
            pl = " or VH_PROJEKT_ID IN (" + Joiner.on(",").join(pm.getProjectIds()) + ")";
        }
        
        CustomQuery q = new DBClass().CustomQuery;
        String sql = "select group_concat(pid) as pids from "
         + "\n " + "(select VH_PATIENT_ID as pid from cust_verk_haupt where VH_NURSE_ID = " + nurse.getNurseId() + pl
         + "\n " + "union distinct"
         + "\n " + "select CVS_PATIENT_ID from cust_verk_subs where CVS_NURSE_ID = " + nurse.getNurseId() + ") as p";
        q.setSqlString(sql);
        
//        q.db.debugNextQuery(true);
        
        patientIds = MyUtils.getValueFromItem(MyUtils.getFirstItemFromContainer(q.query()), "pids", String.class);
        return patientIds != null ? patientIds : "";
        
    }
    
    private void dbGetPatients(){
    	
    	DBClass db = new DBClass();
    	
    	
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("*");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln(" CONCAT_WS(' ', PSA_NAME, PSL_VORNAME, PSL_NAME, CONCAT_WS('', '(', PSL_PLZ, ' ', PSL_ORT, ')'))", "patient");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("view_patient_stammdaten_liste", "INNER JOIN", "cust_patient_stammdaten_anrede", "PSL_ANREDE", "PSA_ID");
        
        if(isLimited()) {
            db.DB_Data_Get.DB_Filter.DB_WHERE_In("view_patient_stammdaten_liste", "PSL_ID", getNursePatientIds(), "");
        }
        
//        db.debugNextQuery(true);
        
//        return db.DB_Data_Get.DB_SEND_AND_GET();
        
        try {
        	
        	filterPatient.addItem(0);
        	filterPatient.setItemCaption(0, i18n.get(caption.combo_all));
        	filterPatient.setNullSelectionItemId(0);
        	
        	
            combo nc = new combo(db.DB_Data_Get.DB_SEND_AND_GET(), filterPatient, "PSL_ID", "patient");
        } catch (Exception e) {
            filterPatient.removeAllItems();
        }
    }
    
    private void dbGetProducts(){
    	
    	DBClass db = new DBClass();
    	
    	
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("*");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_prescriptions_products");
        
        try {
        	
        	filterProduct.addItem(0);
        	filterProduct.setItemCaption(0, i18n.get(caption.combo_all));
        	filterProduct.setNullSelectionItemId(0);
        	
            combo nc = new combo(db.DB_Data_Get.DB_SEND_AND_GET(), filterProduct, "PP_ID", "PP_PRODUCT");
        } catch (Exception e) {
        	filterProduct.removeAllItems();
        }
        
    }
    
    @AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// mainContainer
		mainContainer = buildMainContainer();
		mainLayout.addComponent(mainContainer);
		mainLayout.setExpandRatio(mainContainer, 1.0f);
		mainLayout.setComponentAlignment(mainContainer, new Alignment(20));
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildMainContainer() {
		// common part: create layout
		mainContainer = new VerticalLayout();
		mainContainer.setImmediate(false);
		mainContainer.setWidth("100.0%");
		mainContainer.setHeight("100.0%");
		mainContainer.setMargin(true);
		
		// menuSpacer
		menuSpacer = buildMenuSpacer();
		mainContainer.addComponent(menuSpacer);
		
		// globalFilterContainer
		globalFilterContainer = buildGlobalFilterContainer();
		mainContainer.addComponent(globalFilterContainer);
		mainContainer.setComponentAlignment(globalFilterContainer,
				new Alignment(48));
		
		// tbl_data
		tbl_data = new FilterTable();
		tbl_data.setImmediate(true);
		tbl_data.setWidth("100.0%");
		tbl_data.setHeight("100.0%");
		mainContainer.addComponent(tbl_data);
		mainContainer.setExpandRatio(tbl_data, 1.0f);
		mainContainer.setComponentAlignment(tbl_data, new Alignment(20));
		
		return mainContainer;
	}

	@AutoGenerated
	private VerticalLayout buildMenuSpacer() {
		// common part: create layout
		menuSpacer = new VerticalLayout();
		menuSpacer.setImmediate(false);
		menuSpacer.setWidth("100.0%");
		menuSpacer.setHeight("40px");
		menuSpacer.setMargin(false);
		
		// men_frm
		men_frm = new MenuBar();
		men_frm.setImmediate(false);
		men_frm.setWidth("100.0%");
		men_frm.setHeight("-1px");
		menuSpacer.addComponent(men_frm);
		menuSpacer.setComponentAlignment(men_frm, new Alignment(20));
		
		return menuSpacer;
	}

	@AutoGenerated
	private HorizontalLayout buildGlobalFilterContainer() {
		// common part: create layout
		globalFilterContainer = new HorizontalLayout();
		globalFilterContainer.setImmediate(false);
		globalFilterContainer.setWidth("100.0%");
		globalFilterContainer.setHeight("80px");
		globalFilterContainer.setMargin(false);
		
		// filterAll
		filterAll = new CheckBox();
		filterAll.setCaption("Alle Patienten anzeigen");
		filterAll.setImmediate(false);
		filterAll.setWidth("-1px");
		filterAll.setHeight("-1px");
		globalFilterContainer.addComponent(filterAll);
		globalFilterContainer.setComponentAlignment(filterAll,
				new Alignment(48));
		
		// filterLayoutPatient
		filterLayoutPatient = buildFilterLayoutPatient();
		globalFilterContainer.addComponent(filterLayoutPatient);
		globalFilterContainer.setComponentAlignment(filterLayoutPatient,
				new Alignment(48));
		
		// filterLayoutProduct
		filterLayoutProduct = buildFilterLayoutProduct();
		globalFilterContainer.addComponent(filterLayoutProduct);
		globalFilterContainer.setComponentAlignment(filterLayoutProduct,
				new Alignment(48));
		
		return globalFilterContainer;
	}

	@AutoGenerated
	private HorizontalLayout buildFilterLayoutPatient() {
		// common part: create layout
		filterLayoutPatient = new HorizontalLayout();
		filterLayoutPatient.setImmediate(false);
		filterLayoutPatient.setWidth("-1px");
		filterLayoutPatient.setHeight("-1px");
		filterLayoutPatient.setMargin(false);
		filterLayoutPatient.setSpacing(true);
		
		// filterPatient
		filterPatient = new ComboBox();
		filterPatient.setCaption("Patient");
		filterPatient.setImmediate(false);
		filterPatient.setWidth("-1px");
		filterPatient.setHeight("-1px");
		filterLayoutPatient.addComponent(filterPatient);
		filterLayoutPatient.setComponentAlignment(filterPatient, new Alignment(
				48));
		
		return filterLayoutPatient;
	}

	@AutoGenerated
	private HorizontalLayout buildFilterLayoutProduct() {
		// common part: create layout
		filterLayoutProduct = new HorizontalLayout();
		filterLayoutProduct.setImmediate(false);
		filterLayoutProduct.setWidth("-1px");
		filterLayoutProduct.setHeight("-1px");
		filterLayoutProduct.setMargin(false);
		filterLayoutProduct.setSpacing(true);
		
		// filterProduct
		filterProduct = new ComboBox();
		filterProduct.setCaption("Medikament");
		filterProduct.setImmediate(false);
		filterProduct.setWidth("-1px");
		filterProduct.setHeight("-1px");
		filterLayoutProduct.addComponent(filterProduct);
		filterLayoutProduct.setComponentAlignment(filterProduct, new Alignment(
				48));
		
		return filterLayoutProduct;
	}
}
