package archenoah.web.normal.main.Menuepunkte.Individuelle.Stammdaten.Krankenschwesternverwaltung.components;

import java.text.DateFormat;
import java.util.Date;

import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.vaadin.Components.MultiRowData.MultiRowDataComponent;
import archenoah.lib.vaadin.Components.MultiRowData.MultiRowDataField;
import archenoah.lib.vaadin.Components.MultiRowData.MultiRowDataFieldConverter;
import archenoah.lib.vaadin.Components.MultiRowData.MultiRowDataFieldRows;
import archenoah.lib.vaadin.CustomConverterFactorys.StringSqlTimestampConverter;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.VerticalLayout;

public class NurseFirmComponent extends CustomComponent{

    private VerticalLayout mainLayout;
    
    // {section fields}
    // ****************
    MultiRowDataComponent multiRow;
    // {end fields}

    // {section constructors}
    // **********************
    public NurseFirmComponent() {
        setCompositionRoot(buildMainLayout());
        
        StringSqlTimestampConverter date = new StringSqlTimestampConverter();
        date.setDateFormat(DateFormat.SHORT);
        
        MultiRowDataFieldConverter dateFieldConverter = new MultiRowDataFieldConverter() {
            @Override
            public Object convertForTable(MultiRowDataField field) {
                return new java.sql.Date(((java.util.Date) field.getField().getValue()).getTime());
            }
        };
        
        ComboBox firm = new ComboBox();
        firm.setCaption("Firma");
        firm.setRequired(true);
        MultiRowDataField firmField = new MultiRowDataField(firm, "KSF_KEY_FIRM", String.class);
        firmField.setDataSource(dbGetFirms(), "IF_KEY", "IF_NAME");
        
        PopupDateField dateFrom = new PopupDateField();
        dateFrom.setCaption("Startdatum");
        dateFrom.setRequired(true);
        MultiRowDataField dateFromField = new MultiRowDataField(dateFrom, "KSF_DATE_FROM", java.sql.Date.class);
        dateFromField.setDefaultValue(new Date());
        dateFromField.setConverter(date);
        dateFromField.setFieldConverter(dateFieldConverter);
        
        PopupDateField dateUntil = new PopupDateField();
        dateUntil.setCaption("Enddatum");
        MultiRowDataField dateUntilField = new MultiRowDataField(dateUntil, "KSF_DATE_UNTIL", java.sql.Date.class);
        dateUntilField.setConverter(date);
        dateUntilField.setFieldConverter(dateFieldConverter);
        
        MultiRowDataFieldRows rows = new MultiRowDataFieldRows();
        rows.addFieldRow(
                firmField
                , dateFromField
                , dateUntilField
                );
        
        multiRow = new MultiRowDataComponent(
                "cust_krankenschwester_stammdaten_firmen"
                , "KSF_ID"
                , "KSF_ID_NURSE"
                , rows);
        
        mainLayout.addComponent(multiRow);
        multiRow.setSizeFull();
        
    }
    // {end constructors}

    // {section gettersandsetters}
    // ***************************
    // {end gettersandsetters}

    // {section publicmethods}
    // ***********************
    
    public void setParentId(Integer id) {
        multiRow.setParentId(id);
    }
    
    public void setParentIdOnly(Integer id) {
        multiRow.setParentIdOnly(id);
    }
    
    public void save(Integer id) {
        multiRow.save(id);
    }
    
    public void save() {
        multiRow.save();
    }
    
    public void saveAndUpdate() {
        multiRow.saveAndUpdate();
    }
    
    // {end publicmethods}

    // {section privatemethods}
    // ************************
    // {end privatemethods}

    // {section database}
    // ******************
    private Container dbGetFirms() {
        
        DBClass db = new DBClass();
        
        String sql = "SELECT"
             + "\n " + "    IF_KEY"
             + "\n " + "    , IF_NAME"
             + "\n " + "FROM cust_internal_firms";
        
        db.CustomQuery.setSqlString(sql);
        return db.CustomQuery.query();
        
    }
    // {end database}

    // {section layout}
    // ****************
    @AutoGenerated
    private VerticalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setStyleName("cust_margin_none");
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);
        mainLayout.setSpacing(true);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        return mainLayout;
    }
    // {end layout}
}
