package archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektzuweisung.Form.Metadata;

import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map.Entry;

import org.apache.commons.lang3.tuple.Pair;

import archenoah.config.CMS_Config_Std;
import archenoah.lib.custom.MyUtils;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.tool.comunication.dbclass.DBClass.CustomQuery;
import archenoah.lib.vaadin.Components.Combo.combo;
import archenoah.lib.vaadin.Components.Metadata.MetadataPanel;
import archenoah.lib.vaadin.Components.Metadata.RecurrenceDateInformation;
import archenoah.lib.vaadin.Components.Recurrence.PART;
import archenoah.lib.vaadin.Components.Recurrence.RruleItem;
import archenoah.lib.vaadin.Components.Steppers.IntStepper;
import archenoah.lib.vaadin.CustomConverterFactorys.StringSqlTimestampConverter;
import archenoah.lib.vaadin.Forms_Builder.Form_Bind;
import archenoah.lib.vaadin.Language.i18n.I18nCB;
import archenoah.lib.vaadin.Language.i18n.I18nConverter;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.lib.vaadin.recurrence.DateBoundaries;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektzuweisung.Form.form_projektzuweisung_rrule;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektzuweisung.Form.classes.MetaProductsComponent;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.data.util.sqlcontainer.SQLContainer;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.ui.AbstractField;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

import de.steinwedel.messagebox.ButtonId;
import de.steinwedel.messagebox.Icon;
import de.steinwedel.messagebox.MessageBox;
import de.steinwedel.messagebox.MessageBoxListener;

public class MetadataPoPMain extends MetadataPanel {
//    public class MetadataPoPMain extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private VerticalLayout mainLayout;
    @AutoGenerated
    private Panel pan_system;
    @AutoGenerated
    private VerticalLayout verticalLayout_3;
    @AutoGenerated
    private IntStepper int_maxRep;
    @AutoGenerated
    private Panel pan_pdfs;
    @AutoGenerated
    private VerticalLayout verticalLayout_5;
    @AutoGenerated
    private ComboBox pdfFreq;
    @AutoGenerated
    private ComboBox pdfType;
    @AutoGenerated
    private Panel pan_verwaltung;
    @AutoGenerated
    private VerticalLayout verticalLayout_4;
    @AutoGenerated
    private ListSelect list_nurses;
    @AutoGenerated
    private HorizontalLayout horizontalLayout_3;
    @AutoGenerated
    private Button btn_removeNurse;
    @AutoGenerated
    private Button btn_addNurse;
    @AutoGenerated
    private ComboBox cbx_nurses;
    @AutoGenerated
    private ComboBox cbx_regLead;
    @AutoGenerated
    private ComboBox cbx_internalFirm;
    @AutoGenerated
    private Panel pan_dynamic;
    @AutoGenerated
    private HorizontalLayout horizontalLayout_1;
    @AutoGenerated
    private VerticalLayout verticalLayout_6;
    @AutoGenerated
    private Button btn_rrule;
    @AutoGenerated
    private CheckBox cb_homecare;
    @AutoGenerated
    private Button btn_products;
    @AutoGenerated
    private TextField txt_rrule_id;
    @AutoGenerated
    private PopupDateField pop_dyn_dateActive;
    @AutoGenerated
    private PopupDateField pop_dyn_dateDelegation;
    @AutoGenerated
    private VerticalLayout verticalLayout_7;
    @AutoGenerated
    private Button btn_dyn_saveNew;
    @AutoGenerated
    private ListSelect list_dynamic;
    @AutoGenerated
    private Panel pan_project;
    @AutoGenerated
    private VerticalLayout verticalLayout_2;
    @AutoGenerated
    private TextField txt_patInitials;
    @AutoGenerated
    private TextField txt_patCode;
    /**************** --> Allgemein <--- ********************/
        
    org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(this.getClass());
    // Allgemein

    // Berrechtigung

    private final Button Temp_Btn = null;
    /******************************************************/
    /**************** --> Tabsheetvars <--- *****************/

    /******************************************************/
    /**************** --> Windowvars <--- *******************/
    private final Window win = null;
    private Panel pan = null;
    private form_projektzuweisung_rrule rrule = null;
    /******************************************************/
    /******************* --> Custom <--- ********************/
    /******************************************************/
    private String staticId = null;
    private HashMap<Object, String> DBMapStatic;
    private HashMap<Object, String> DBMapDynamic;
    private HashMap<Object, String> DBMapSubs;

    private ArrayList<AbstractField> validateListDynamic;
    private ArrayList<AbstractField> validateListStatic;
    private ArrayList<DBClass> tempDynamic;

    private final SQLContainer conMeta = null;
    private IndexedContainer conNursesSubs = null;
    private ArrayList listNursesSubsDb = null;

    final String table_static = "cust_protokoll_pop_meta_static";
    final String table_dynamic = "cust_protokoll_pop_meta_dynamic";
    
    /************ ----->Einstellungen<-- ********************/
    private final String LNG_FRM_ID = "2103";

    private final String Windows_Height = "600px";
    private final String Windows_Width = "720px";

    /******************************************************/
    
    private String RecurrenceString = null;
    private Date RecurrenceStart = null;
    private Integer RecurrenceRepetitions = null;
    private Date RecurrenceLatestDate = null;
    private Integer RecurrenceMetaId = null;
    
    // used in force save homecare
    private Integer metaDynamicId = null;
    private Boolean metaDynamicHomecareValue = null;
    
    private MetaProductsComponent products;
    private boolean saveProducts;
    private I18nManager i18n;
    
    private final static class caption extends I18nCB {
        static final I18nCB Neu = set();
    }
    
    //public ComboBox cb_nurse;
    public MetadataPoPMain() {
        buildMainLayout();
        
        i18n = new I18nManager(this);
        
        pan = new Panel(mainLayout);
        pan.setSizeFull();

    }

    /********* INIT-Window ************/

    @Override
    public Panel getPanel() {
        
        if(!hasProjectId()) {
            System.err.println("no project id assigned!");
            return pan;
        }
        
        defaultInit();
        return pan;
    }
    
//    /*************************************/
    //TASK placeholder stuff for Editor
//    private Boolean hasMainId(){
//        return true;
//    }
//    
//    private String getMainId(){
//        return null;
//    }
//    
//    private String getPatientId(){
//        return null;
//    }
//    
//    private Boolean hasProjectId(){
//        return true;
//    }
//    
//    private String getProjectId(){
//        return "";
//    }
//    /*************************************/
    
    /********* Inherited Methods ************/
    
    @Override
    public Boolean validate(){
        
        if(!validateStatic()){
            I18nManager.global(I18nGlobalNotifiers.fields_empty);
            return false;
        }
        
        if(staticId == null || staticId.equals("") == true){
            
            if(!validateDynamic()){
                I18nManager.global(I18nGlobalNotifiers.meta_dynamic_error);
                return false;
            }

        }
        
        return true;
        
    }
    
    @Override
    public Boolean save() {
        
        if (!hasMainId()) {
            I18nManager.global(I18nGlobalNotifiers.no_main_id);
            return false;
        }
        
        if(!validate()){
            return false;
        }
        
        if(!isDuplicationMode() && staticId != null && staticId.equals("") == false){
            updateStatic();
        }else if(isDuplicationMode()) {
            duplicateDynamic();
            saveStatic();
        }else{
            
            if(!validateAndSaveDynamic()){
                I18nManager.global(I18nGlobalNotifiers.meta_dynamic_error);
                return false;
            }
            
            saveStatic();
        }
        
        saveNurseSubs();
        

        return true;

    }
    

    @Override
    public void update(){
        fillFields();
    }
    
    @Override
    public HashMap<String, Object> getFieldValues(){
        
        HashMap<String, Object> map = new HashMap<String, Object>();
        
        for (Entry<Object, String> entry: DBMapStatic.entrySet()) {

            map.put(entry.getValue(), ((AbstractField) entry.getKey()).getValue());
            
        }
        
        return map;
    }
    
    
    @Override
    public Boolean hasRecurrence(){
        return true;
    }
    
    @Override
    public String getRecurrenceString() {
        // TASK Auto-generated method stub
        return RecurrenceString;
    }

    @Override
    public Date getRecurrenceStart() {
        // TASK Auto-generated method stub
        return RecurrenceStart;
    }

    @Override
    public Integer getRecurrenceRepetitions() {
        // TASK Auto-generated method stub
        return RecurrenceRepetitions;
    }

    @Override
    public Date getRecurrenceLatestDate() {
        // TASK Auto-generated method stub
        return RecurrenceLatestDate;
    }
    
    @Override
    public Integer getRecurrenceMetaId() {
        // TASK Auto-generated method stub
        return RecurrenceMetaId;
    }
    
    @Override
    public Boolean isNurseRequired() {
        return true;
    }
    
    @Override
    public Boolean hasMultiRecurrence() {
        return false;
    }
    
    @Override
    public HashMap<Integer, RecurrenceDateInformation> getRecurrenceDates(Boolean all) {
        return null;
    }
    
    @Override
    public Pair<Date, Date> getBoundaryDates(Integer delegationId, Date originalDate){
        
        RruleItem ri = dbGetRecurrenceRule(delegationId);
        
        if(ri.getItemPropertyIds().size() == 0 || originalDate == null) {
            log.warn("Item or date was null");
            return null;
        }
        
        return DateBoundaries.getBoundaries(ri.getRrule(), ri.getStart(), originalDate);
        
    }
    
    @Override
    public void deleteUnaccepted() {
        
        if(!isDuplicationMode()) {
            return;
        }
        
        CustomQuery q = new DBClass().CustomQuery;
        String sql = "delete cust_protokoll_pop_daten from cust_protokoll_pop_daten"
         + "\n " + "left join cust_protokoll_pop_meta_dynamic on ID_DELEGATION = PPOPMD_ID"
         + "\n " + "where PPOPMD_VH_ID = "+getDuplicateOrigVhId()+" and STATUS = 1";
        q.setSqlString(sql);
        q.update();
        
    }

    /********* Init-Standard ************/
    private void defaultInit() {

        setDBMaps();
        setupFields();
        fillFields();

        setValidateMaps();

        /**********************/

    }

    /******************* Config TBL *******************/

    private void setupFields() {

        tempDynamic = new ArrayList<DBClass>();
        
        txt_patCode.setImmediate(true);
        txt_patInitials.setImmediate(true);
        
        cbx_nurses.setFilteringMode(FilteringMode.CONTAINS);
        cbx_regLead.setFilteringMode(FilteringMode.CONTAINS);

        list_nurses.setItemCaptionPropertyId("Name");

        //dynamic fields	
        list_dynamic.setItemCaptionPropertyId("display");
        list_dynamic.setNullSelectionItemId("new");
        list_dynamic.setImmediate(true);
//        int_volume.setMinValue(0);
//        int_volume.setRequired(true);
        pop_dyn_dateActive.setRequired(true);
        pop_dyn_dateDelegation.setRequired(true);
        
        //system
        int_maxRep.setMinValue(0);
        int_maxRep.setValue(10);
        
        //internal firm
        cbx_internalFirm.setItemCaptionPropertyId("IF_NAME");
        
        // Delegationsinfos füllen / Speichern Button
        //btn_dyn_saveNew.setEnabled(false);
        list_dynamic.addValueChangeListener(new ValueChangeListener() {

            @Override
            public void valueChange(ValueChangeEvent event) {

                rrule = null; // set to null to clear window
                editDynamicFields(event.getProperty().getValue());
                editSaveNewButton(event.getProperty().getValue());
                
            }
        });
        
        //toggle save button for homecare
        cb_homecare.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                if(metaDynamicId != null && metaDynamicHomecareValue != null){
                    btn_dyn_saveNew.setEnabled(!MyUtils.equalsWithNulls(event.getProperty().getValue(), metaDynamicHomecareValue));
                }
                
            }
        });
        
        //hinzufügen enabled falls Nurse ausgewählt
        btn_addNurse.setEnabled(false);
        cbx_nurses.setImmediate(true);
        cbx_nurses.addValueChangeListener(new ValueChangeListener() {

            @Override
            public void valueChange(ValueChangeEvent event) {
                Boolean enabled = false;
                if (event.getProperty().getValue() != null) {
                    enabled = true;
                }

                btn_addNurse.setEnabled(enabled);
            }
        });

        conNursesSubs = new IndexedContainer();
        conNursesSubs.addContainerProperty("nurse", String.class, "");
        list_nurses.setContainerDataSource(conNursesSubs);
        list_nurses.setItemCaptionPropertyId("nurse");
        list_nurses.setNullSelectionAllowed(false);

        //Nurse zu Liste hinzufügen
        btn_addNurse.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {
                try {
                    conNursesSubs.addItem(cbx_nurses.getValue()).getItemProperty("nurse")
                            .setValue(cbx_nurses.getItemCaption(cbx_nurses.getValue()));
                } catch (Exception e) {
                }
                cbx_nurses.setValue(null);
            }
        });

        btn_removeNurse.setEnabled(false);
        list_nurses.setImmediate(true);
        list_nurses.addValueChangeListener(new ValueChangeListener() {

            @Override
            public void valueChange(ValueChangeEvent event) {

                if (event.getProperty().getValue() != null) {
                    btn_removeNurse.setEnabled(true);
                }

            }
        });

        btn_removeNurse.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {

                conNursesSubs.removeItem(list_nurses.getValue());
                btn_removeNurse.setEnabled(false);

            }
        });

        btn_products.addClickListener(new ClickListener() {
            
            @Override
            public void buttonClick(ClickEvent event) {
                
                final MessageBox box = MessageBox.showCustomized(Icon.NONE, btn_products.getCaption(), products, new MessageBoxListener() {
                    
                    @Override
                    public void buttonClicked(ButtonId btnid) {
                        
                        if(btnid == ButtonId.CANCEL) {
                            products.setParentId(metaDynamicId); //reload previous values
                        }else if (btnid == ButtonId.SAVE) {
                            log.info("saving? {}", products.getParentId());
                            if(products.getParentId() != null) {
                                products.saveAndUpdate();
                            }else {
                                saveProducts = true;
                            }
                        }
                        
                    }
                }, ButtonId.SAVE, ButtonId.CANCEL, ButtonId.CLOSE);
                box.setHeight("300px");
                box.setWidth("350px");
                
                boolean enabled = btn_dyn_saveNew.isEnabled() || MyUtils.equalsWithNulls(getMainId(), "");
                
                box.getButton(ButtonId.SAVE).setVisible(enabled);
                box.getButton(ButtonId.CANCEL).setVisible(enabled);
                box.getButton(ButtonId.CLOSE).setVisible(!enabled);
                
                products.setEnabled(enabled);
            }
        });
        
        btn_rrule.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {

                if (rrule != null) {
                    rrule.showWindow();
                } else {
                    rrule = new form_projektzuweisung_rrule(btn_rrule, txt_rrule_id.getValue());
                    rrule.Init_Class_Window();
                    if(pop_dyn_dateActive.getValue() != null && !rrule.hasDateStart()){
                        rrule.setDate(pop_dyn_dateActive.getValue());
                    }
                    
                }
            }
        });

        btn_dyn_saveNew.setEnabled(false);

        btn_dyn_saveNew.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {
                
                if(metaDynamicId == null && metaDynamicHomecareValue == null){
                    //save new
                    validateAndSaveDynamic();
                }else{
                    // update metaDynamicId
                    updateDynamic();
                    editDynamicFields(null);
                    fillDynamicList();
                }
                
            }
        });
        
        // use 21 as formid for main insert edit
        new I18nConverter("cust_protokoll_pdf_type", "PPT_KEY", "PPT_KEY").attachDatasource(pdfType);
        new I18nConverter("cust_protokoll_pdf_freq", "PPF_KEY", "PPF_KEY").attachDatasource(pdfFreq);
        
        
    }
    
    private Boolean validateAndSaveDynamic(){
        Integer saved = null;
        Boolean re = false;
        
        if (validateDynamic() == true) {
            if (rrule != null) {
                txt_rrule_id.setValue(rrule.save());
                saved = saveDynamic();
            }
        }

        if (saved != null) {
            fillDynamicList();
            if(saveProducts && products.isModified()) {
                products.save(metaDynamicId);
                saveProducts = false;
            }
        }
        
        if(saved != null){
            re = true;
        }
        
        return re;
    }
    
    private void fillFields() {
        getRl();
        getFirm();
        getNurses();
        fillNurseSubs();
        editDynamicFields(null);
        fillDynamicList();
        getStatic();
    }

    private void editDynamicFields(Object itemId) {
        Boolean enabled = true;
        Item item = null;
        if(itemId != null){
            item = list_dynamic.getContainerDataSource().getItem(itemId);
        }

        enableDynamicFields(enabled);
        
        if (item != null) {
            enabled = false;
            
            metaDynamicId = (Integer) item.getItemProperty("PPOPMD_ID").getValue();
            
            pop_dyn_dateDelegation.setValue((Date) item.getItemProperty("PPOPMD_DELEGATION").getValue());
            pop_dyn_dateActive.setValue((Date) item.getItemProperty("PPOPMD_ACTIVE").getValue());
//            int_volume.setValue((Integer) item.getItemProperty("PPOPMD_VOLUME").getValue());
            cb_homecare.setValue((Boolean) item.getItemProperty("PPOPMD_HOMECARE").getValue());
            metaDynamicHomecareValue = (Boolean) item.getItemProperty("PPOPMD_HOMECARE").getValue();
            txt_rrule_id.setValue(Integer.toString((Integer) item.getItemProperty("PPOPMD_RRULE_ID").getValue()));
        } else {
            
            metaDynamicId = null;
            
            pop_dyn_dateDelegation.setValue(null);
            pop_dyn_dateActive.setValue(null);
//            int_volume.setValue(0);
            cb_homecare.setValue(true);
            metaDynamicHomecareValue = null;
            txt_rrule_id.setValue("");
        }
        
        if(!saveProducts) {
            products = new MetaProductsComponent();
            products.setup(Integer.parseInt(getProjectId()), metaDynamicId);
        }

        
        enableDynamicFields(enabled);

    }

    private void enableDynamicFields(Boolean enabled) {
        Boolean disabled = !enabled;
        pop_dyn_dateDelegation.setReadOnly(disabled);
        pop_dyn_dateActive.setReadOnly(disabled);
//        int_volume.setReadOnly(disabled);
        btn_dyn_saveNew.setReadOnly(disabled);
    }

    private void editSaveNewButton(Object itemId) {
        Boolean enabled = true;

        if (itemId != null) {
            enabled = false;
        }
        
        if(!hasMainId()){
            enabled = false;
        }
        
        btn_dyn_saveNew.setEnabled(enabled);
    }

    /************************************************/
    
    private Boolean validateStatic(){
        
        for (AbstractField field : validateListStatic) {
            if (field.isValid() == false) {
                I18nManager.global(I18nGlobalNotifiers.fields_empty);
                return false;
            }
        }
        
        return true;
    }
    
    private Boolean validateDynamic() {

        for (AbstractField field : validateListDynamic) {
            if (field.isValid() == false) {
                I18nManager.global(I18nGlobalNotifiers.fields_empty);
                return false;
            }
        }
        
        if (products != null && products.getContainer().size() == 0) {
            I18nManager.global(I18nGlobalNotifiers.missing_products);
            return false;
        }
        
        if(rrule == null){
            I18nManager.global(I18nGlobalNotifiers.recurrence_missing);
            return false;
        }
        
        if (rrule != null) {
            if (rrule.isValid() == false) {
                I18nManager.global(I18nGlobalNotifiers.recurrence_invalid);
                return false;
            }
        }
        return true;
    }

    /********** -> DB Map <- ******************/
    private void setDBMaps() {
        DBMapDynamic = new HashMap<Object, String>();
        DBMapDynamic.put(pop_dyn_dateDelegation, "cust_protokoll_pop_meta_dynamic:PPOPMD_DELEGATION");
        DBMapDynamic.put(pop_dyn_dateActive, "cust_protokoll_pop_meta_dynamic:PPOPMD_ACTIVE");
//        DBMapDynamic.put(int_volume, "cust_protokoll_pop_meta_dynamic:PPOPMD_VOLUME");
        DBMapDynamic.put(cb_homecare, "cust_protokoll_pop_meta_dynamic:PPOPMD_HOMECARE");
        DBMapDynamic.put(txt_rrule_id, "cust_protokoll_pop_meta_dynamic:PPOPMD_RRULE_ID");

        DBMapStatic = new HashMap<Object, String>();
        DBMapStatic.put(txt_patCode, "cust_protokoll_pop_meta_static:PPOPMS_PAT_CODE");
        DBMapStatic.put(txt_patInitials, "cust_protokoll_pop_meta_static:PPOPMS_PAT_INITIALS");
        DBMapStatic.put(cbx_regLead, "cust_protokoll_pop_meta_static:PPOPMS_ID_REG_LEAD");
        DBMapStatic.put(int_maxRep, "cust_protokoll_pop_meta_static:PPOPMS_MAX_REP");
        DBMapStatic.put(cbx_internalFirm, "cust_protokoll_pop_meta_static:PPOPMS_KEY_FIRM");
        
        DBMapStatic.put(pdfType, "cust_protokoll_pop_meta_static:PPOPMS_PDF_TYPE");
        DBMapStatic.put(pdfFreq, "cust_protokoll_pop_meta_static:PPOPMS_PDF_FREQ");
        
    }

    private void setValidateMaps() {
        
        validateListStatic = new ArrayList<AbstractField>();
        validateListStatic.add(txt_patCode);
        validateListStatic.add(txt_patInitials);
        validateListStatic.add(cbx_regLead);
        
        validateListDynamic = new ArrayList<AbstractField>();
        validateListDynamic.add(pop_dyn_dateDelegation);
        validateListDynamic.add(pop_dyn_dateActive);
//        validateListDynamic.add(int_volume);
        validateListDynamic.add(cb_homecare);
        validateListDynamic.add(txt_rrule_id);

    }

    /********** -> Datenholen <- ******************/
    private void getStatic() {
        CMS_Config_Std std = CMS_Config_Std.getInstance();

        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_protokoll_pop_meta_static");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();

        String wid = getMainId();
        if (wid == null || wid == "") {
            wid = "0";
        }

        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_protokoll_pop_meta_static", "PPOPMS_VH_ID", "=", wid, "");

        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();
        Form_Bind fb = new Form_Bind();

        if (con.size() > 0) {
            staticId = Integer.toString((Integer) con.getItem(1).getItemProperty("PPOPMS_ID").getValue());
            fb.Get_and_Fill(con, DBMapStatic);
        }

    }
    
    private void getRl(){
        CMS_Config_Std std = CMS_Config_Std.getInstance();
        DBClass db = new DBClass();

        
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("SRL_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("AUL_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT("
                + "AUL_VORNAME, ' ', AUL_NAME,"
                + " (CASE WHEN SRL_REGION IS NULL OR SRL_REGION = '' THEN ''ELSE CONCAT(' (', SRL_REGION, ') ') END))", "Regionalleitername");

        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_stammdaten_user", "INNER JOIN", "cust_krankenschwester_stammdaten_anrede", "AUL_ANREDE_ID", "KSA_ID");

        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_stammdaten_regionalleiter", "INNER JOIN", "cms_auth_stammdaten_user", "SRL_ID_USER", "AUL_ID");
        
        
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_stammdaten_regionalleiter", "SRL_ID_PROJEKT", "=", getProjectId(), "");
        
//        db.DB_Data_Get.DB_DEBUG_SQL_STRING();
        
        try {
            combo nc = new combo(db.DB_Data_Get.DB_SEND_AND_GET_Container(), cbx_regLead, "SRL_ID", "Regionalleitername");
        } catch (Exception e) {
            cbx_regLead.removeAllItems();
        }
    }
    
    private void getFirm() {
        
        DBClass db = new DBClass();
        
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("IF_KEY");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("IF_NAME");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_internal_firms");
        
        cbx_internalFirm.setContainerDataSource(MyUtils.convertIndex(db.DB_Data_Get.DB_SEND_AND_GET_Container(), "IF_KEY"));
        
    }
    
    private void getNurses() {
        CMS_Config_Std std = CMS_Config_Std.getInstance();

        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("KSK_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(KSK_TITEL,' ',KSA_NAME,' ',AUL_NAME,' ',AUL_VORNAME)",
                "Krankenschwesternname");

        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("AL_G_ID");

        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_stammdaten_user", "INNER JOIN",
                "cust_krankenschwester_stammdaten_anrede", "AUL_ANREDE_ID", "KSA_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_stammdaten_user", "LEFT JOIN", "cms_auth_liste_gu", "AUL_ID",
                "AL_U_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_liste_gu", "LEFT JOIN", "cust_projekte_stammdaten_liste",
                "AL_G_ID", "PSLV_GROUP");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_krankenschwester_stammdaten_ks", "INNER JOIN",
                "cms_auth_stammdaten_user", "KSK_U_ID", "AUL_ID");

        // System.out.println(ns_projekte.getValue());

        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_projekte_stammdaten_liste", "PSLV_ID", "=", getProjectId(), "");

        // db.DB_Data_Get.DB_DEBUG_SQL_STRING();

        try {
            combo nc = new combo(db.DB_Data_Get.DB_SEND_AND_GET(), cbx_nurses, "KSK_ID", "Krankenschwesternname");
        } catch (Exception e) {
            cbx_nurses.removeAllItems();
            return;
        }

        db.DB_Data_Get.connclose();

    }

    @SuppressWarnings("unchecked")
    private void fillDynamicList() {
        CMS_Config_Std std = CMS_Config_Std.getInstance();
        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_protokoll_pop_meta_dynamic");

        String wid = getMainId();
        if (wid == null || wid == "") {
            wid = "0";
        }

        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_protokoll_pop_meta_dynamic", "PPOPMD_VH_ID", "=", wid, "");

        //db.DB_Data_Get.DB_DEBUG_SQL_STRING();

        Container scon = db.DB_Data_Get.DB_SEND_AND_GET_Container();
        scon.addContainerProperty("display", String.class, "");
        StringSqlTimestampConverter converter = new StringSqlTimestampConverter();
        converter.setFormat(DateFormat.SHORT);

        Object sconId = null;
        for (Object id : scon.getItemIds()) {
            scon.getItem(id)
                    .getItemProperty("display")
                    .setValue(
                            converter.convertToPresentation(scon.getItem(id).getItemProperty("PPOPMD_DELEGATION").getValue(), String.class,
                                    UI.getCurrent().getLocale()));
            sconId = id;
        }
        scon.addItem("new").getItemProperty("display").setValue(i18n.get(caption.Neu));
        list_dynamic.setContainerDataSource(scon);
        editSaveNewButton(null);
        list_dynamic.setValue(sconId);
    }

    private void fillNurseSubs() {
        CMS_Config_Std std = CMS_Config_Std.getInstance();

        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("KSK_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CVS_NURSE_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(KSK_TITEL,' ',KSA_NAME,' ',AUL_NAME,' ',AUL_VORNAME)", "Name");

        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_stammdaten_user", "INNER JOIN",
                "cust_krankenschwester_stammdaten_anrede", "AUL_ANREDE_ID", "KSA_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_krankenschwester_stammdaten_ks", "INNER JOIN",
                "cms_auth_stammdaten_user", "KSK_U_ID", "AUL_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_krankenschwester_stammdaten_ks", "INNER JOIN", "cust_verk_subs",
                "KSK_ID", "CVS_NURSE_ID");

        // System.out.println(ns_projekte.getValue());

        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_subs", "CVS_PROJECT_ID", "=", getProjectId(), "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_subs", "CVS_PATIENT_ID", "=", getPatientId(), "");

        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();
        
        listNursesSubsDb = new ArrayList();
        conNursesSubs.removeAllItems();
        for (Object itemId : con.getItemIds()) {
            
            Object nurseId = con.getItem(itemId).getItemProperty("CVS_NURSE_ID").getValue();
            String nurseName = (String) con.getItem(itemId).getItemProperty("Name").getValue();
            conNursesSubs.addItem(nurseId);
            conNursesSubs.getItem(nurseId).getItemProperty("nurse").setValue(nurseName);
            
            listNursesSubsDb.add(nurseId);
        }

        

        //db.DB_Data_Get.connclose();
    }
    
    private RruleItem dbGetRecurrenceRule(Integer delegationId) {
        
        CustomQuery q = new DBClass().CustomQuery;
        String sql = "select * from cust_protokoll_rrules"
            + "\n " + "where RRL_ID = (select PPOPMD_RRULE_ID from cust_protokoll_pop_meta_dynamic where PPOPMD_ID = " + delegationId + ")";
        q.setSqlString(sql);
        
        RruleItem ri = new RruleItem(MyUtils.getFirstItemFromContainer(q.query()));
        ri.setPropertyFor(PART.START, "RRL_START");
        ri.setPropertyFor(PART.RRULE, "RRL_RRULE");
        ri.setPropertyFor(PART.CUSTOM, "RRL_CUSTOM");
        
        return ri;
    }
    
    /* *********************************** */

    private Integer saveDynamic() {
        CMS_Config_Std std = CMS_Config_Std.getInstance();
        DBClass db = new DBClass();
        db.DB_Data_Insert.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_protokoll_pop_meta_dynamic");
        Form_Bind fb = new Form_Bind();
        fb.Insert(db, DBMapDynamic);

        db.DB_Data_Insert.DB_Daten.DB_Data("cust_protokoll_pop_meta_dynamic", "PPOPMD_VH_ID", getMainId());

//        db.DB_Data_Insert.DB_DEBUG_SQL_STRING();
        return db.DB_Data_Insert.DB_Insert();
        
    }
    
    private void updateDynamic(){
        //homecare only for now
        
        DBClass db = new DBClass();
        db.DB_Data_Update.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_protokoll_pop_meta_dynamic");
        db.DB_Data_Update.DB_Daten.DB_Data("cust_protokoll_pop_meta_dynamic", "PPOPMD_HOMECARE", cb_homecare.getValue() ? "1" : "0");

        db.DB_Data_Update.DB_Filter.DB_WHERE_Allgemein("cust_protokoll_pop_meta_dynamic", "PPOPMD_ID", "=", metaDynamicId.toString(), "");
        
        db.DB_Data_Update.DB_Update();
        
    }
    
    private void duplicateDynamic() {
        CustomQuery q = new DBClass().CustomQuery;
        String sql = "insert into cust_protokoll_pop_meta_dynamic (PPOPMD_VH_ID, PPOPMD_RRULE_ID, PPOPMD_CREATED, PPOPMD_LAST_UPDATE, PPOPMD_DELEGATION, PPOPMD_ACTIVE, PPOPMD_VOLUME, PPOPMD_HOMECARE)"
            + "\n " + "select "+ getMainId() +", PPOPMD_RRULE_ID, PPOPMD_CREATED, PPOPMD_LAST_UPDATE, PPOPMD_DELEGATION, PPOPMD_ACTIVE, PPOPMD_VOLUME, PPOPMD_HOMECARE from cust_protokoll_pop_meta_dynamic"
            + "\n " + "where PPOPMD_VH_ID = " + getDuplicateOrigVhId();
        q.setSqlString(sql);
        
        q.update();
    }
    
//    private void saveTempDynamic() {
//        Iterator it = tempDynamic.iterator();
//        while (it.hasNext()) {
//            DBClass dbc = (DBClass) it.next();
//            dbc.DB_Data_Insert.DB_Daten.DB_Data("cust_protokoll_pop_meta_dynamic", "PPOPMD_VH_ID", getMainId());
//            dbc.DB_Data_Insert.DB_Insert();
//
//            it.remove();// avoids a ConcurrentModificationException
//            tempDynamic.remove(dbc);
//        }
//    }
//
//    private Integer saveDynamic() {
//
//        tempDynamic.add(prepSaveDynamic());
//
//        if (getMainId() != null && getMainId().equals("") == false) {
//            saveTempDynamic();
//        }
//
//        return 1;
//    }

    private Integer saveStatic() {
        CMS_Config_Std std = CMS_Config_Std.getInstance();
        DBClass db = new DBClass();
        db.DB_Data_Insert.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_protokoll_pop_meta_static");

        Form_Bind fb = new Form_Bind();
        fb.Insert(db, DBMapStatic);

        db.DB_Data_Insert.DB_Daten.DB_Data("cust_protokoll_pop_meta_static", "PPOPMS_VH_ID", getMainId());

        //db.DB_Data_Insert.DB_DEBUG_SQL_STRING();
        return db.DB_Data_Insert.DB_Insert();

    }
    
    private void updateStatic() {
        CMS_Config_Std std = CMS_Config_Std.getInstance();
        DBClass db = new DBClass();
        db.DB_Data_Update.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_protokoll_pop_meta_static");

        Form_Bind fb = new Form_Bind();
        fb.Update(db, DBMapStatic);
        
        db.DB_Data_Update.DB_Filter.DB_WHERE_Allgemein("cust_protokoll_pop_meta_static", "PPOPMS_ID", "=", staticId, "");

        db.DB_Data_Update.DB_Update();

    }
    
    private void saveNurseSubs() {

        ArrayList<String> currentEntries = new ArrayList<String>();
        ArrayList<String> toDelete = new ArrayList<String>();
        ArrayList<String> toInsert = new ArrayList<String>();

        for (Object id : listNursesSubsDb) {

            String nurse = id.toString();
            currentEntries.add(nurse);

            if (!conNursesSubs.containsId(id)) {
                toDelete.add(nurse);
            }

        }

        for (Object id : conNursesSubs.getItemIds()) {
            String nurse = id.toString();
            if (!currentEntries.contains(nurse)) {
                toInsert.add(nurse);
            }
        }

        //	 System.out.println(toDelete.toString());
        //	 System.out.println(toInsert.toString());

        CMS_Config_Std std = CMS_Config_Std.getInstance();
        DBClass db = new DBClass();

        db.DB_Data_Insert.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_verk_subs");

        for (String id : toInsert) {

            db.DB_Data_Insert.DB_Daten.DB_Data("cust_verk_subs", "CVS_PROJECT_ID", getProjectId());
            db.DB_Data_Insert.DB_Daten.DB_Data("cust_verk_subs", "CVS_PATIENT_ID", getPatientId());
            db.DB_Data_Insert.DB_Daten.DB_Data("cust_verk_subs", "CVS_NURSE_ID", id);
            db.DB_Data_Insert.DB_Insert();
            db.DB_Data_Insert.DB_Daten.DB_Data_Leeren();
        }

        db.DB_Data_Delete.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_verk_subs");
        //db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_verk_subs");

        for (String id : toDelete) {

            db.DB_Data_Delete.DB_Filter.DB_WHERE_Allgemein("cust_verk_subs", "CVS_PROJECT_ID", "=", getProjectId(), "AND");
            db.DB_Data_Delete.DB_Filter.DB_WHERE_Allgemein("cust_verk_subs", "CVS_PATIENT_ID", "=", "'" + getPatientId() + "'", "AND");
            db.DB_Data_Delete.DB_Filter.DB_WHERE_Allgemein("cust_verk_subs", "CVS_NURSE_ID", "=", "'" + id + "'", "");
            db.DB_Data_Delete.DB_Delete();
            db.DB_Data_Delete.DB_Filter.DB_Data_Leeren();
        }

    }
    
    
    @Override
    public void setRecurrenceSettings(String Form_ID){
        DBClass db = new DBClass();
        
        
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
        
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_verk_haupt", "INNER JOIN", table_static, "VH_ID", "PPOPMS_VH_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_verk_haupt", "INNER JOIN", table_dynamic, "VH_ID", "PPOPMD_VH_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung(table_dynamic, "INNER JOIN", "cust_protokoll_rrules", "PPOPMD_RRULE_ID", "RRL_ID");
        
        db.DB_Data_Get.DB_Ordnen.DB_Ordnen("PPOPMD_ACTIVE", "DESC"); //TASK this takes the highest active date - not always right!
        db.DB_Data_Get.DB_Ordnen.DB_Ordnen("PPOPMD_CREATED", "DESC");
        db.DB_Data_Get.DB_Limit.DB_LIMIT("1");
        
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_verk_haupt", "VH_ID", "=", Form_ID, "");
        
//        db.debugNextQuery(true);
        
        Item settings = db.DB_Data_Get.DB_SEND_AND_GET_FIRST_ITEM();
        
        if(settings != null){
            RecurrenceString = (String) settings.getItemProperty("RRL_RRULE").getValue();
            RecurrenceStart = (Date) settings.getItemProperty("RRL_START").getValue();
            RecurrenceRepetitions = (Integer) settings.getItemProperty("PPOPMS_MAX_REP").getValue();
            RecurrenceMetaId = (Integer) settings.getItemProperty("PPOPMD_ID").getValue();
        }
        
        
        DBClass dbb = new DBClass();
        
        dbb.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
        
        dbb.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_protokoll_pop_daten", "INNER JOIN", table_dynamic, "ID_DELEGATION", "PPOPMD_ID");
        
        dbb.DB_Data_Get.DB_Ordnen.DB_Ordnen("ORIGINAL_DATE", "DESC");
        dbb.DB_Data_Get.DB_Limit.DB_LIMIT("1");
        
        dbb.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein(table_dynamic, "PPOPMD_VH_ID", "=", Form_ID, "");
        
//        dbb.debugNextQuery(true);
        
        Item item = dbb.DB_Data_Get.DB_SEND_AND_GET_FIRST_ITEM();
        
        RecurrenceLatestDate = (item == null) ? null : (Date) item.getItemProperty("ORIGINAL_DATE").getValue();
        
    }
    
    @AutoGenerated
    private VerticalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("-1px");
        mainLayout.setMargin(false);
        mainLayout.setSpacing(true);

        // top-level component properties
        setWidth("100.0%");
        setHeight("-1px");

        // pan_project
        pan_project = buildPan_project();
        mainLayout.addComponent(pan_project);

        // pan_dynamic
        pan_dynamic = buildPan_dynamic();
        mainLayout.addComponent(pan_dynamic);

        // pan_verwaltung
        pan_verwaltung = buildPan_verwaltung();
        mainLayout.addComponent(pan_verwaltung);

        // pan_pdfs
        pan_pdfs = buildPan_pdfs();
        mainLayout.addComponent(pan_pdfs);

        // pan_system
        pan_system = buildPan_system();
        mainLayout.addComponent(pan_system);

        return mainLayout;
    }

    @AutoGenerated
    private Panel buildPan_project() {
        // common part: create layout
        pan_project = new Panel();
        pan_project.setCaption("Projektinformationen");
        pan_project.setImmediate(false);
        pan_project.setWidth("100.0%");
        pan_project.setHeight("120px");

        // verticalLayout_2
        verticalLayout_2 = buildVerticalLayout_2();
        pan_project.setContent(verticalLayout_2);

        return pan_project;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_2() {
        // common part: create layout
        verticalLayout_2 = new VerticalLayout();
        verticalLayout_2.setImmediate(false);
        verticalLayout_2.setWidth("100.0%");
        verticalLayout_2.setHeight("100.0%");
        verticalLayout_2.setMargin(false);

        // txt_patCode
        txt_patCode = new TextField();
        txt_patCode.setCaption("Patient Code-Nummer");
        txt_patCode.setImmediate(false);
        txt_patCode.setWidth("200px");
        txt_patCode.setHeight("-1px");
        verticalLayout_2.addComponent(txt_patCode);
        verticalLayout_2.setComponentAlignment(txt_patCode, new Alignment(48));

        // txt_patInitials
        txt_patInitials = new TextField();
        txt_patInitials.setCaption("Patient Projektinitialien");
        txt_patInitials.setImmediate(false);
        txt_patInitials.setWidth("200px");
        txt_patInitials.setHeight("-1px");
        verticalLayout_2.addComponent(txt_patInitials);
        verticalLayout_2.setComponentAlignment(txt_patInitials, new Alignment(48));

        return verticalLayout_2;
    }

    @AutoGenerated
    private Panel buildPan_dynamic() {
        // common part: create layout
        pan_dynamic = new Panel();
        pan_dynamic.setCaption("Delegationen");
        pan_dynamic.setImmediate(false);
        pan_dynamic.setWidth("100.0%");
        pan_dynamic.setHeight("260px");

        // horizontalLayout_1
        horizontalLayout_1 = buildHorizontalLayout_1();
        pan_dynamic.setContent(horizontalLayout_1);

        return pan_dynamic;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_1() {
        // common part: create layout
        horizontalLayout_1 = new HorizontalLayout();
        horizontalLayout_1.setImmediate(false);
        horizontalLayout_1.setWidth("100.0%");
        horizontalLayout_1.setHeight("100.0%");
        horizontalLayout_1.setMargin(false);
        horizontalLayout_1.setSpacing(true);

        // verticalLayout_7
        verticalLayout_7 = buildVerticalLayout_7();
        horizontalLayout_1.addComponent(verticalLayout_7);
        horizontalLayout_1.setExpandRatio(verticalLayout_7, 1.0f);
        horizontalLayout_1.setComponentAlignment(verticalLayout_7, new Alignment(48));

        // verticalLayout_6
        verticalLayout_6 = buildVerticalLayout_6();
        horizontalLayout_1.addComponent(verticalLayout_6);
        horizontalLayout_1.setExpandRatio(verticalLayout_6, 1.0f);
        horizontalLayout_1.setComponentAlignment(verticalLayout_6, new Alignment(48));

        return horizontalLayout_1;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_7() {
        // common part: create layout
        verticalLayout_7 = new VerticalLayout();
        verticalLayout_7.setImmediate(false);
        verticalLayout_7.setWidth("80px");
        verticalLayout_7.setHeight("-1px");
        verticalLayout_7.setMargin(false);
        verticalLayout_7.setSpacing(true);

        // list_dynamic
        list_dynamic = new ListSelect();
        list_dynamic.setImmediate(false);
        list_dynamic.setWidth("100px");
        list_dynamic.setHeight("180px");
        verticalLayout_7.addComponent(list_dynamic);
        verticalLayout_7.setComponentAlignment(list_dynamic, new Alignment(48));

        // btn_dyn_saveNew
        btn_dyn_saveNew = new Button();
        btn_dyn_saveNew.setCaption("Speichern");
        btn_dyn_saveNew.setImmediate(true);
        btn_dyn_saveNew.setWidth("100px");
        btn_dyn_saveNew.setHeight("-1px");
        verticalLayout_7.addComponent(btn_dyn_saveNew);
        verticalLayout_7.setComponentAlignment(btn_dyn_saveNew, new Alignment(48));

        return verticalLayout_7;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_6() {
        // common part: create layout
        verticalLayout_6 = new VerticalLayout();
        verticalLayout_6.setImmediate(false);
        verticalLayout_6.setWidth("100.0%");
        verticalLayout_6.setHeight("100.0%");
        verticalLayout_6.setMargin(false);

        // pop_dyn_dateDelegation
        pop_dyn_dateDelegation = new PopupDateField();
        pop_dyn_dateDelegation.setCaption("Delegationsdatum");
        pop_dyn_dateDelegation.setImmediate(false);
        pop_dyn_dateDelegation.setWidth("-1px");
        pop_dyn_dateDelegation.setHeight("-1px");
        verticalLayout_6.addComponent(pop_dyn_dateDelegation);
        verticalLayout_6.setComponentAlignment(pop_dyn_dateDelegation, new Alignment(48));

        // pop_dyn_dateActive
        pop_dyn_dateActive = new PopupDateField();
        pop_dyn_dateActive.setCaption("Gültigkeitsdatum");
        pop_dyn_dateActive.setImmediate(false);
        pop_dyn_dateActive.setWidth("-1px");
        pop_dyn_dateActive.setHeight("-1px");
        verticalLayout_6.addComponent(pop_dyn_dateActive);
        verticalLayout_6.setComponentAlignment(pop_dyn_dateActive, new Alignment(48));

        // txt_rrule_id
        txt_rrule_id = new TextField();
        txt_rrule_id.setEnabled(false);
        txt_rrule_id.setImmediate(false);
        txt_rrule_id.setVisible(false);
        txt_rrule_id.setWidth("-1px");
        txt_rrule_id.setHeight("-1px");
        verticalLayout_6.addComponent(txt_rrule_id);

        // btn_products
        btn_products = new Button();
        btn_products.setCaption("Medikamente");
        btn_products.setImmediate(false);
        btn_products.setWidth("-1px");
        btn_products.setHeight("-1px");
        verticalLayout_6.addComponent(btn_products);
        verticalLayout_6.setComponentAlignment(btn_products, new Alignment(48));

        // cb_homecare
        cb_homecare = new CheckBox();
        cb_homecare.setCaption("Lieferpatient");
        cb_homecare.setImmediate(false);
        cb_homecare.setWidth("-1px");
        cb_homecare.setHeight("-1px");
        verticalLayout_6.addComponent(cb_homecare);
        verticalLayout_6.setComponentAlignment(cb_homecare, new Alignment(48));

        // btn_rrule
        btn_rrule = new Button();
        btn_rrule.setCaption("Wiederholung");
        btn_rrule.setImmediate(true);
        btn_rrule.setWidth("-1px");
        btn_rrule.setHeight("-1px");
        verticalLayout_6.addComponent(btn_rrule);
        verticalLayout_6.setComponentAlignment(btn_rrule, new Alignment(48));

        return verticalLayout_6;
    }

    @AutoGenerated
    private Panel buildPan_verwaltung() {
        // common part: create layout
        pan_verwaltung = new Panel();
        pan_verwaltung.setCaption("Verwaltungsdaten");
        pan_verwaltung.setImmediate(false);
        pan_verwaltung.setWidth("100.0%");
        pan_verwaltung.setHeight("310px");

        // verticalLayout_4
        verticalLayout_4 = buildVerticalLayout_4();
        pan_verwaltung.setContent(verticalLayout_4);

        return pan_verwaltung;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_4() {
        // common part: create layout
        verticalLayout_4 = new VerticalLayout();
        verticalLayout_4.setImmediate(false);
        verticalLayout_4.setWidth("100.0%");
        verticalLayout_4.setHeight("-1px");
        verticalLayout_4.setMargin(false);
        verticalLayout_4.setSpacing(true);

        // cbx_internalFirm
        cbx_internalFirm = new ComboBox();
        cbx_internalFirm.setCaption("Infusionsfirma");
        cbx_internalFirm.setImmediate(false);
        cbx_internalFirm.setWidth("200px");
        cbx_internalFirm.setHeight("-1px");
        verticalLayout_4.addComponent(cbx_internalFirm);
        verticalLayout_4.setComponentAlignment(cbx_internalFirm, new Alignment(48));

        // cbx_regLead
        cbx_regLead = new ComboBox();
        cbx_regLead.setCaption("Regionalleiter");
        cbx_regLead.setImmediate(false);
        cbx_regLead.setWidth("200px");
        cbx_regLead.setHeight("-1px");
        verticalLayout_4.addComponent(cbx_regLead);
        verticalLayout_4.setComponentAlignment(cbx_regLead, new Alignment(48));

        // cbx_nurses
        cbx_nurses = new ComboBox();
        cbx_nurses.setCaption("Vertretungsnurse");
        cbx_nurses.setImmediate(false);
        cbx_nurses.setWidth("200px");
        cbx_nurses.setHeight("-1px");
        verticalLayout_4.addComponent(cbx_nurses);
        verticalLayout_4.setComponentAlignment(cbx_nurses, new Alignment(48));

        // horizontalLayout_3
        horizontalLayout_3 = buildHorizontalLayout_3();
        verticalLayout_4.addComponent(horizontalLayout_3);
        verticalLayout_4.setComponentAlignment(horizontalLayout_3, new Alignment(48));

        // list_nurses
        list_nurses = new ListSelect();
        list_nurses.setCaption("Vertretungsnurses");
        list_nurses.setImmediate(false);
        list_nurses.setWidth("200px");
        list_nurses.setHeight("80px");
        verticalLayout_4.addComponent(list_nurses);
        verticalLayout_4.setComponentAlignment(list_nurses, new Alignment(48));

        return verticalLayout_4;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_3() {
        // common part: create layout
        horizontalLayout_3 = new HorizontalLayout();
        horizontalLayout_3.setImmediate(false);
        horizontalLayout_3.setWidth("-1px");
        horizontalLayout_3.setHeight("-1px");
        horizontalLayout_3.setMargin(false);
        horizontalLayout_3.setSpacing(true);

        // btn_addNurse
        btn_addNurse = new Button();
        btn_addNurse.setCaption("hinzufügen");
        btn_addNurse.setImmediate(true);
        btn_addNurse.setWidth("95px");
        btn_addNurse.setHeight("-1px");
        horizontalLayout_3.addComponent(btn_addNurse);

        // btn_removeNurse
        btn_removeNurse = new Button();
        btn_removeNurse.setCaption("entfernen");
        btn_removeNurse.setImmediate(true);
        btn_removeNurse.setWidth("95px");
        btn_removeNurse.setHeight("-1px");
        horizontalLayout_3.addComponent(btn_removeNurse);

        return horizontalLayout_3;
    }

    @AutoGenerated
    private Panel buildPan_pdfs() {
        // common part: create layout
        pan_pdfs = new Panel();
        pan_pdfs.setCaption("Protokollversand");
        pan_pdfs.setImmediate(false);
        pan_pdfs.setWidth("100.0%");
        pan_pdfs.setHeight("100.0%");

        // verticalLayout_5
        verticalLayout_5 = buildVerticalLayout_5();
        pan_pdfs.setContent(verticalLayout_5);

        return pan_pdfs;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_5() {
        // common part: create layout
        verticalLayout_5 = new VerticalLayout();
        verticalLayout_5.setImmediate(false);
        verticalLayout_5.setWidth("100.0%");
        verticalLayout_5.setHeight("100.0%");
        verticalLayout_5.setMargin(false);
        verticalLayout_5.setSpacing(true);

        // pdfType
        pdfType = new ComboBox();
        pdfType.setCaption("Versandart");
        pdfType.setImmediate(false);
        pdfType.setWidth("200px");
        pdfType.setHeight("-1px");
        verticalLayout_5.addComponent(pdfType);
        verticalLayout_5.setComponentAlignment(pdfType, new Alignment(48));

        // pdfFreq
        pdfFreq = new ComboBox();
        pdfFreq.setCaption("Intervall");
        pdfFreq.setImmediate(false);
        pdfFreq.setWidth("200px");
        pdfFreq.setHeight("-1px");
        verticalLayout_5.addComponent(pdfFreq);
        verticalLayout_5.setComponentAlignment(pdfFreq, new Alignment(48));

        return verticalLayout_5;
    }

    @AutoGenerated
    private Panel buildPan_system() {
        // common part: create layout
        pan_system = new Panel();
        pan_system.setCaption("Systemeinstellungen");
        pan_system.setImmediate(false);
        pan_system.setWidth("100.0%");
        pan_system.setHeight("80px");

        // verticalLayout_3
        verticalLayout_3 = buildVerticalLayout_3();
        pan_system.setContent(verticalLayout_3);

        return pan_system;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_3() {
        // common part: create layout
        verticalLayout_3 = new VerticalLayout();
        verticalLayout_3.setImmediate(false);
        verticalLayout_3.setWidth("100.0%");
        verticalLayout_3.setHeight("100.0%");
        verticalLayout_3.setMargin(false);

        // int_maxRep
        int_maxRep = new IntStepper();
        int_maxRep.setCaption("Anzahl Blankos");
        int_maxRep.setImmediate(false);
        int_maxRep.setWidth("-1px");
        int_maxRep.setHeight("-1px");
        verticalLayout_3.addComponent(int_maxRep);
        verticalLayout_3.setComponentAlignment(int_maxRep, new Alignment(48));

        return verticalLayout_3;
    }

}
