package archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.nursecockpit.Form;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Map.Entry;

import org.joda.time.Duration;
import org.joda.time.LocalDateTime;
import org.joda.time.format.PeriodFormatter;
import org.joda.time.format.PeriodFormatterBuilder;
import org.tepi.filtertable.FilterTable;

import archenoah.config.CMS_Config_Std;
import archenoah.lib.custom.ComponentIterator;
import archenoah.lib.custom.MyUtils;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Tab_Menue_Item;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Window_Button;
import archenoah.lib.vaadin.Components.table.FilteringTableUpdater;
import archenoah.lib.vaadin.Language.i18n.I18nCB;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.lib.vaadin.MenuBerechtigung.Rechteholen;
import archenoah.lib.vaadin.resources.Icons;
import archenoah.web.normal.UserInfo.Nurse;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.classes.ProjectNurseCombos;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.nursecockpit.classes.ProjectTabOpener;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Projekte.Projektuebersicht.nursecockpit.classes.WarningDataView;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Container.ItemSetChangeEvent;
import com.vaadin.data.Container.ItemSetChangeListener;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.converter.Converter;
import com.vaadin.event.ItemClickEvent;
import com.vaadin.event.ItemClickEvent.ItemClickListener;
import com.vaadin.event.UIEvents.PollEvent;
import com.vaadin.event.UIEvents.PollListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.shared.ui.datefield.Resolution;
import com.vaadin.ui.AbstractComponent;
import com.vaadin.ui.AbstractField;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.InlineDateField;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.Command;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.Window.CloseEvent;
import com.vaadin.ui.Window.CloseListener;


@SuppressWarnings({"serial", "rawtypes", "unchecked"})
public class CockpitDataView extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private HorizontalLayout mainLayout;

    @AutoGenerated
    private VerticalLayout mainContainer;

    @AutoGenerated
    private TabSheet tabs;

    @AutoGenerated
    private WarningDataView warningList;

    @AutoGenerated
    private FilterTable tbl_data;

    @AutoGenerated
    private CockpitCalendar cockpitCalendar;

    @AutoGenerated
    private HorizontalLayout globalFilterContainer;

    @AutoGenerated
    private ComboBox filterNurse;

    @AutoGenerated
    private InlineDateField filterMonth;

    @AutoGenerated
    private VerticalLayout menuSpacer;

    @AutoGenerated
    private MenuBar men_frm;

    

    

    

    

    

    

	

	

	

	

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */

    /**************** --> Allgemein <--- ********************/

    private static org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(CockpitDataView.class);
    
    // Datenbank
    private Map<Object, String> componentMap;
    private FilteringTableUpdater tableUpdater = null;

    // Berrechtigung
    private int ACC_ID;

    private int permRead;
    private int permCreate;
    private int permUpdate;
    private int permDelete;

    private MenuItem tmpMenu = null;

    private Button tmpButton = null;
    /******************************************************/
    /**************** --> Tabsheetvars <--- *****************/
    private TabSheet tab = null;

    /******************************************************/
    /**************** --> Windowvars <--- *******************/
    private Window win = null;
    /******************************************************/

    private DetachListener onDetach = null;

    /******************* -> Menüpunkte <- ********************/
    private MenuBar.MenuItem btn_create;
    private MenuBar.MenuItem btn_update;
    private MenuBar.MenuItem btn_read;
    private MenuBar.MenuItem btn_delete;
    private MenuBar.MenuItem btn_filter;
    private MenuBar.MenuItem btn_projectManager;

    
    /*******************************************************/
    /******************* --> Custom <--- ********************/
    /******************************************************/

    private Boolean firstFilter = true;
    private PollListener pollListener = null;
    
    private ProjectTabOpener tabOpener = new ProjectTabOpener();
    
    enum Status {}
    
    /************ ----->Einstellungen<-- ********************/
//    private final String formIdLng = "40";
    private final String formIdPerm = "40";
    private final String winHeight = "600px";
    private final String winWidth = "900px";


    /******************************************************/

    private final String tableIdCol = "project";
    
    //TASK cols
    private final Object[] tableColsAll = new Object[] {"PSLV_NAME", "entries", "time_service", "time_driven", "distance", "admin", "unaccepted" };
    //use custom Cols when needed
    private Object[] tableColsDefault = tableColsAll;
    //use custom Cols when needed
    private final Object[] tableColsFilter = tableColsDefault;
    private Object[] tableColsActive = tableColsDefault;
    
    private boolean firstMonthInit = true;
    private boolean firstNurseInit = true;

    private I18nManager i18n;
    
    private final static class caption extends I18nCB {
        static final I18nCB projectManager = set();
        static final I18nCB projectManagerEnable = set();
        static final I18nCB projectManagerDisable = set();
    }
    
    PeriodFormatter formatter = new PeriodFormatterBuilder()
    .minimumPrintedDigits(2)
    .printZeroAlways()
    .appendHours()
    .appendSuffix(":")
    .appendMinutes()
    .toFormatter();
    
    /******************************************************/

    public CockpitDataView(MenuItem Arg_Menü) {
        tmpMenu = Arg_Menü;
    }

    public CockpitDataView(Button Arg_btn) {
        tmpButton = Arg_btn;
    }

    /***************************** ---> Feste Funtionen<--- **************************************/

    /********* INIT-Window ************/
    public void init() {

        Standard_Init();

        if (tmpMenu != null) {
            String Recourcename = tmpMenu.getIcon().toString();
            Recourcename = Recourcename.substring(0, Recourcename.length() - 12) + "white-16.png";

            Build_Window_Button bwb = new Build_Window_Button(tmpMenu.getText(), mainLayout, winHeight, winWidth,
                    new ThemeResource(Recourcename));
            win = bwb.ReturnWindow();
        }
        if (tmpButton != null) {
            Build_Window_Button bwb = new Build_Window_Button(tmpButton.getCaption(), mainLayout, winHeight, winWidth,
                    tmpButton.getIcon());
            win = bwb.ReturnWindow();
        }

        win.addDetachListener(onDetach);

    }
    
    public Window getWindow(){
    	return win;
    }
    
    public TabSheet getTabSheet(){
    	return tab;
    }
    
    public void init(TabSheet Arg_tab) {

        Standard_Init();
        tab = Arg_tab;
        if (tmpMenu != null) {
            new Build_Tab_Menue_Item(Arg_tab, tmpMenu.getText(), mainLayout, tmpMenu.getIcon());
        }
        if (tmpButton != null) {
            new Build_Tab_Menue_Item(Arg_tab, tmpButton.getCaption(), mainLayout, tmpButton.getIcon());
        }

        tab.getSelectedTab().addDetachListener(onDetach);
    }

    /********* Init-Standard ************/
    private void Standard_Init() {
        buildMainLayout();
        
        i18n = new I18nManager(this);
        
        registerComponents();
        
        generateMenu();

        setMenuPermissions();
        
        fillNurse();
        
        updateTable();
        tbl_data.setSortContainerPropertyId(tableIdCol);
        tbl_data.setSortAscending(true);
        tbl_data.sort();
        configureTable();
        configureComponents();
        
        setupListenersAndDetachEvent();
        
        i18n.refresh();
        updateWarningCount();
    }
    
    // register components for lng and validation tools
    private void registerComponents(){
    	componentMap = new HashMap<Object, String>();
    	new ComponentIterator(mainContainer).createMap(componentMap);
    }

    
    private void setupListenersAndDetachEvent() {
        pollListener = new PollListener() {

            @Override
            public void poll(PollEvent event) {
                if(tab.isRendered(mainLayout)){
                    updateTable();
                }
            }
        };

        UI.getCurrent().getUI().addPollListener(pollListener);

        onDetach = new DetachListener() {

            @Override
            public void detach(DetachEvent event) {
                UI.getCurrent().getUI().removePollListener(pollListener);
            }
        };
    }
    
    @SuppressWarnings("unused")
    public void setPermissionsFromDatabase() {
        if (formIdPerm == "") {
            System.out.println("Form Einstellung Fehlt: Berechtigung");
            return;
        }

        ACC_ID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        Rechteholen r = new Rechteholen(ACC_ID + "");
        String[][] perms = r.Datenholen();

        for (int i = 0; i < perms.length; i++) {
            if (perms[i][0].equals(formIdPerm) == true) {

                permRead = Integer.valueOf(perms[i][3]);
                permUpdate = Integer.valueOf(perms[i][4]);
                permCreate = Integer.valueOf(perms[i][6]);
                permDelete = Integer.valueOf(perms[i][5]);
                
            }
        }
    }

    public void setPermissions(int create, int read, int update, int delete) {

        permCreate = create;
        permRead = read;
        permUpdate = update;
        permDelete = delete;

    }

    private void setMenuPermissions() {
        Boolean c = (permCreate == 1);
        Boolean r = (permRead == 1);
        Boolean u = (permUpdate == 1);
        Boolean d = (permDelete == 1);

//        btn_create.setEnabled(c);
//        btn_create.setVisible(c);
//
//        btn_read.setEnabled(r);
//        btn_read.setVisible(r);
//
//        btn_update.setEnabled(u);
//        btn_update.setVisible(u);
//
//        btn_delete.setEnabled(d);
//        btn_delete.setVisible(d);
        
    }

    /************ -><- ******************/

    /***************** Comands *********************/
    
    CloseListener closeListener = new CloseListener() {
		
		@Override
		public void windowClose(CloseEvent e) {
			updateTable(true);
		}
	};
    
    //TASK Commands are here

    public Command cmd_btn_filter = new Command() {
        @Override
        public void menuSelected(MenuItem selectedItem) {

            if (firstFilter) {
                tbl_data.setFilterBarVisible(true);
                tbl_data.setFilterBarVisible(false);
                warningList.setFilterBarVisible(true);
                warningList.setFilterBarVisible(false);
                firstFilter = false;
            }
            tbl_data.setFilterBarVisible(!tbl_data.isFilterBarVisible());
            warningList.setFilterBarVisible(!warningList.isFilterBarVisible());
            
            if(!tbl_data.isFilterBarVisible()){
                tbl_data.clearFilters();
                warningList.clearFilters();
            }
            
            tableColsActive = tbl_data.isFilterBarVisible() ? tableColsFilter : tableColsDefault;
            if(tableColsActive.length > 0 && tbl_data.size() > 0){
            	tbl_data.setVisibleColumns(tableColsActive);
            }

        }
    };
    
    public Command cmd_projectManager = new Command() {
        
        @Override
        public void menuSelected(MenuItem selectedItem) {
            
            Nurse nurse = MyUtils.getUserData().getNurse();
            
            if(cockpitCalendar.getProjectIds() != null) {
                cockpitCalendar.setProjectIds(null);
                if(nurse.isNurse()) {
                    filterNurse.setValue(nurse.getNurseId());
                }
            }else {
                cockpitCalendar.setProjectIds(MyUtils.getUserData().getProjectManager().getProjectIds());
                filterNurse.setValue(null);
            }
            togglePmCaption();
        }
    };

    

    /******************************************/

    
    

    /*********** Gen Menüs *************/
    private void generateMenu() {
        
        btn_filter = men_frm.addItem("FRM_FILTER", Icons.White.filter_16, cmd_btn_filter);
        btn_projectManager = men_frm.addItem("FRM_PROJECTMANAGER", Icons.White.krankenschwester_16, cmd_projectManager);

    }
    
    private void configureComponents(){
       
    	for (Entry<Object, String> entry : componentMap.entrySet()) {
    		AbstractComponent field = (AbstractComponent) entry.getKey();
    		
			field.setImmediate(true);
			
			
			if(field instanceof ComboBox){
				((ComboBox)field).setFilteringMode(FilteringMode.CONTAINS);
			}

		}
    	
    	// migrated from database
    	btn_filter.setIcon(Icons.White.filter_16);
    	// migration end
    	
    	btn_projectManager.setVisible(MyUtils.getUserData().getProjectManager().isProjectManager());
    	togglePmCaption();
    	
    	ValueChangeListener vcl = new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
               updateTable();
            }
        };

    	filterMonth.setResolution(Resolution.MONTH);
    	filterMonth.setImmediate(true);
    	filterMonth.addValueChangeListener(vcl);
    	filterMonth.addValueChangeListener(new ValueChangeListener() {

            @Override
            public void valueChange(ValueChangeEvent event) {
                
                cockpitCalendar.setDate(filterMonth.getValue());
                
                if(firstMonthInit) {
                    firstMonthInit = false;
                    cockpitCalendar.setWeeklyView(new Date());
                }
                
            }
        });
    	
    	
    	filterNurse.setItemCaptionPropertyId("Krankenschwesternname");
    	filterNurse.setImmediate(true);
    	filterNurse.addValueChangeListener(vcl);
    	filterNurse.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {

                cockpitCalendar.setNurse((Integer) filterNurse.getValue());

            }
        });
    	

        //infoWarnings
        
    	filterNurse.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                updateNurseWarnings();
                
            }
        });
    	
    }
    
    private void updateNurseWarnings() {
        warningList.setUser(getSelectedNurseUserId());
        updateWarningCount();
    }
    
    private void updateWarningCount() {
        tabs.getTab(warningList).setCaption(i18n.get("Warnungen") + " (" + warningList.getCount() + ")");
    }
    
    private Integer getSelectedNurseUserId() {
        Item item = filterNurse.getContainerDataSource().getItem(filterNurse.getValue());
        return MyUtils.getValueFromItem(item, "AUL_ID", Integer.class);
    }
    
    private ArrayList<AbstractField> getActiveGlobalFilters(){
        ArrayList<AbstractField> al = new ArrayList<AbstractField>();
        
        if(filterMonth.getValue() != null){
            al.add(filterMonth);
        }
        
        if(filterNurse.getValue() != null){
            al.add(filterNurse);
        }
        
        return al;
    }
    
    private Boolean hasGlobalFilters(ArrayList a){
        
        return (a.size() > 0);
        
    }
    
    private Boolean hasGlobalFilters(){
        
        return hasGlobalFilters(getActiveGlobalFilters());
        
    }
    
    private void togglePmCaption() {
        btn_projectManager.setText(i18n.get(caption.projectManager) + " " 
        + i18n.get(((cockpitCalendar.getProjectIds() != null) ? caption.projectManagerDisable : caption.projectManagerEnable)));
    }
    
    /*************************** Config TBL ********************/

    private void configureTable() {
        tbl_data.setSelectable(true);
        tbl_data.setFilterOnDemand(false);
        tbl_data.setImmediate(true);
        tbl_data.setColumnCollapsingAllowed(false);
        tbl_data.setFooterVisible(true);
        tbl_data.setPageLength(1);
        try {
        	if(tableColsDefault.length > 0){
        		tbl_data.setVisibleColumns(tableColsDefault);
        	}
		} catch (Exception e) {

		}
        
        if(tbl_data.size() > 0){
            
//            StringSqlTimestampConverter date = new StringSqlTimestampConverter();
//            date.setDateFormat(DateFormat.SHORT);
//            
//            StringSqlTimestampConverter time = new StringSqlTimestampConverter();
//            time.setDateFormat(DateFormat.SHORT);
//            time.setTimeFormat(DateFormat.SHORT);
//            
//            tbl_data.setConverter("PL_CREATED", time);
//            tbl_data.setConverter("PL_DATE", date);
        
        }
        
        tableUpdater = new FilteringTableUpdater(tbl_data);
        

        for (Object col : tableColsAll) {
        	
        	try {
        		tbl_data.setColumnExpandRatio(col, 1);
			} catch (Exception e) {
				
			}
        		
		}
        
        
        tbl_data.addItemClickListener(new ItemClickListener() {
            
            @Override
            public void itemClick(ItemClickEvent event) {
                
                if (event.isDoubleClick() && event.getItem() != null && event.getItem().getItemProperty("PSLV_CODE") != null) {
                    
                    tabOpener.openTab((String) event.getItem().getItemProperty("PSLV_CODE").getValue(), filterMonth.getValue());
                    
                }
                
            }
        });
        
        tbl_data.addItemSetChangeListener(new ItemSetChangeListener() {
            
            @Override
            public void containerItemSetChange(ItemSetChangeEvent event) {
                
                tbl_data.setColumnFooter("PSLV_NAME", "Σ " + tbl_data.size());
                tbl_data.setColumnFooter("entries", calculateEntries());
                tbl_data.setColumnFooter("time_service", calculateTime("tsr"));
                tbl_data.setColumnFooter("time_driven", calculateTime("tdr"));
                tbl_data.setColumnFooter("distance", calculateDist());
                tbl_data.setColumnFooter("admin", calculateTime("tar"));
                tbl_data.setColumnFooter("unaccepted", calculateOpen());
                
            }
        });
        
        Converter<String, BigDecimal> secToTimeConverter = new Converter<String, BigDecimal>() {

            @Override
            public BigDecimal convertToModel(String value, Class<? extends BigDecimal> targetType, Locale locale)
                throws com.vaadin.data.util.converter.Converter.ConversionException {
                return null;
            }

            @Override
            public String convertToPresentation(BigDecimal value, Class<? extends String> targetType, Locale locale)
                throws com.vaadin.data.util.converter.Converter.ConversionException {
                
                Duration dur = new Duration(0);
                dur = dur.withDurationAdded(value.longValueExact(), 1000);
                
                return formatter.print(dur.toPeriod());
                
            }

            @Override
            public Class<BigDecimal> getModelType() {
                return BigDecimal.class;
            }

            @Override
            public Class<String> getPresentationType() {
                return String.class;
            }

        };
        
        tbl_data.setConverter("time_service", secToTimeConverter);
        tbl_data.setConverter("time_driven", secToTimeConverter);
        tbl_data.setConverter("admin", secToTimeConverter);
    }
    
    
    private Long totalSum() {
        Long number = new Long(0);
        for (Object iid : tbl_data.getItemIds()) {
            number = Math.addExact(number, MyUtils.getValueFromItem(tbl_data.getItem(iid), "entries", Long.class));
        }
        return number;
    }
    
    private String calculateEntries() {
        
        return "Σ " + totalSum().toString();
        
    }
    
    private String calculateTime(Object col) {
        
        Duration dur = new Duration(0);
        
        for (Object iid : tbl_data.getItemIds()) {
            
            BigDecimal bd = MyUtils.getValueFromItem(tbl_data.getItem(iid), col, BigDecimal.class);
            if(bd != null) {
                dur = dur.withDurationAdded(bd.longValueExact(), 1000);
            }
        }
        
        return "Σ " + formatter.print(dur.toPeriod());
        
    }
    
    private String calculateDist() {
        
        Double number = new Double(0);
        for (Object iid : tbl_data.getItemIds()) {
            number = Double.sum(number, MyUtils.getValueFromItem(tbl_data.getItem(iid), "distance", Double.class));
        }
        return "Σ " + String.format("%.0f", number);

    }
    
    private String calculateAdmin() {
        
        BigDecimal number = new BigDecimal(0);
        for (Object iid : tbl_data.getItemIds()) {
            number = number.add(MyUtils.getValueFromItem(tbl_data.getItem(iid), "admin", BigDecimal.class));
        }
        return "Σ " + number.toString();

    }
    
    private String calculateOpen() {
        
        BigDecimal number = new BigDecimal(0);
        for (Object iid : tbl_data.getItemIds()) {
            number = number.add(MyUtils.getValueFromItem(tbl_data.getItem(iid), "unaccepted", BigDecimal.class));
        }
        
        Long total = totalSum();
        
        double perc = (number.longValueExact()/ (double)total );
        perc = perc * 100;
        
        return "Σ " + number.toString() + " | " + String.format("%.2f", perc) + "%";

    }
    
    /*************************** Database ********************/
    
    /********************************/
    
    
    private void updateTable(){
        updateTable(false);
    }
    
    private void updateTable(Boolean ignoreFilter) {

        if (ignoreFilter || !tbl_data.isFilterBarVisible()) {
            dbGetContainer();
            try{
            	if(tableColsDefault.length > 0){
            		tbl_data.setVisibleColumns(tableColsActive);
            	}
            }catch(Exception e){
                
            }
        }
        
//        tbl_data.setColumnFooter("Status", "Σ " + tbl_data.size());
        
    }

    
    
    //TASK dbget
	private void dbGetContainer() {
        CMS_Config_Std std = CMS_Config_Std.getInstance();

        DBClass db = new DBClass();

        /************ Set Spalten *************/
//        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("project");
//        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("nurse");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("PSLV_NAME");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("PSLV_CODE");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("COUNT(entries)", "entries");
        //db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("TIME_FORMAT(SEC_TO_TIME(SUM(IF(time_service IS NOT NULL, time_service, 0))), '%H:%i')", "time_service");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("SUM(IF(time_service IS NOT NULL, time_service, 0))", "time_service");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("SUM(time_service)", "tsr");
        //db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("TIME_FORMAT(SEC_TO_TIME(SUM(IF(time_driven IS NOT NULL, time_driven, 0))), '%H:%i')", "time_driven");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("SUM(IF(time_driven IS NOT NULL, time_driven, 0))", "time_driven");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("SUM(time_driven)", "tdr");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("SUM(IF(distance IS NOT NULL, distance, 0))", "distance");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("SUM(IF(admin IS NOT NULL, admin, 0))", "admin");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("SUM(admin)", "tar");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("SUM(IF(unaccepted = 1, 1, 0))", "unaccepted");

        /**************************************/
        /************ Set Tabelle *************/
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("view_cockpit", "INNER JOIN", "cust_projekte_stammdaten_liste", "project", "PSLV_ID");
        
        /**************************************/
        /************ Set Filter *************/
        String glue = "";
        
        ArrayList<AbstractField> filterList = getActiveGlobalFilters(); 
        
        if(filterMonth.getValue() != null){
            
            java.sql.Timestamp sqlDateFrom = new java.sql.Timestamp(filterMonth.getValue().getTime());
            java.sql.Timestamp sqlDateUntil = new java.sql.Timestamp(new LocalDateTime(filterMonth.getValue()).plusMonths(1).minusMillis(1).toDate().getTime());
            
            filterList.remove(filterMonth);
            glue = hasGlobalFilters(filterList) ? "AND" : "";
            
            db.DB_Data_Get.DB_Filter.DB_WHERE_BETWEEN("view_cockpit", "date", "'" + sqlDateFrom.toString() + "'",  "'" + sqlDateUntil.toString() + "'", glue);

        }
        
        if(filterNurse.getValue() != null){
            
            filterList.remove(filterNurse);
            glue = hasGlobalFilters(filterList) ? "AND" : "";

            
            db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("view_cockpit", "nurse", "=", filterNurse.getValue().toString(), glue);
        }
        
        /**************************************/
        
        db.DB_Data_Get.DB_Gruppieren.DB_Gruppieren("project");
        
        /**************************************/
        /************ Set Custom *************/
        /**************************************/

//        db.DB_Data_Get.Set_Type("PSLV_NAME", Project.class);
        
        /* **************************/
        
//        db.debugNextQuery(true);
        
        try {
        	Container container = db.DB_Data_Get.DB_SEND_AND_GET_Container();
            
        	if (tableUpdater != null) {
                tableUpdater.updateTable(container);
            } else {
                tbl_data.setContainerDataSource(container);
            }
        	
		} catch (Exception e) {
			// TASK: handle exception
			e.printStackTrace();
			UI.getCurrent().getUI().removePollListener(pollListener);
		}
        
    }

    private void fillNurse() {
        
        ProjectNurseCombos pnc = new ProjectNurseCombos();
        pnc.setGetAllFields(true);
        
        filterNurse.setContainerDataSource(MyUtils.convertIndex(pnc.getNurseComboAll(), "KSK_ID"));
        int NID = getNurseId();
        if (NID != 0) {
            filterNurse.select(NID);
            cockpitCalendar.setNurse(NID);
            Boolean rm = isRegionalManager();
            filterNurse.setEnabled(rm);
            filterNurse.setVisible(rm);
            updateNurseWarnings();
        }
    }
	
    private Integer getNurseId() {
        
        int UID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        
        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("KSK_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_liste_gu", "LEFT JOIN", "cust_krankenschwester_stammdaten_ks", "AL_U_ID", "KSK_U_ID");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cms_auth_liste_gu", "AL_U_ID", "=", "'" + UID + "'", "AND");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cms_auth_liste_gu", "AL_G_ID", "=", "'12'", "");
        
        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();
        
        if (con.size() > 0) {
            return (Integer) con.getItem(con.getItemIds().iterator().next()).getItemProperty("KSK_ID").getValue();
        } else {
            return 0;
        }
    }

    private Boolean isRegionalManager() {
        int UID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        DBClass db = new DBClass();
        
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_stammdaten_regionalleiter", "INNER JOIN", "cust_projekte_stammdaten_liste", "SRL_ID_PROJEKT", "PSLV_ID");
        
        
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_stammdaten_regionalleiter", "SRL_ID_USER", "=", "'" + UID + "'", "");
        
        db.DB_Data_Get.DB_Gruppieren.DB_Gruppieren("SRL_ID_USER");

        Container con = db.DB_Data_Get.DB_SEND_AND_GET();

        if (con.size() > 0) {
           return true;
        } else {
            return false;
        }

    }
    
    @AutoGenerated
    private HorizontalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new HorizontalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // mainContainer
        mainContainer = buildMainContainer();
        mainLayout.addComponent(mainContainer);
        mainLayout.setExpandRatio(mainContainer, 1.0f);
        mainLayout.setComponentAlignment(mainContainer, new Alignment(20));
        
        return mainLayout;
    }

    @AutoGenerated
    private VerticalLayout buildMainContainer() {
        // common part: create layout
        mainContainer = new VerticalLayout();
        mainContainer.setImmediate(false);
        mainContainer.setWidth("100.0%");
        mainContainer.setHeight("100.0%");
        mainContainer.setMargin(true);
        mainContainer.setSpacing(true);
        
        // menuSpacer
        menuSpacer = buildMenuSpacer();
        mainContainer.addComponent(menuSpacer);
        
        // globalFilterContainer
        globalFilterContainer = buildGlobalFilterContainer();
        mainContainer.addComponent(globalFilterContainer);
        mainContainer.setComponentAlignment(globalFilterContainer, new Alignment(48));
        
        // tabs
        tabs = buildTabs();
        mainContainer.addComponent(tabs);
        mainContainer.setExpandRatio(tabs, 1.0f);
        
        return mainContainer;
    }

    @AutoGenerated
    private VerticalLayout buildMenuSpacer() {
        // common part: create layout
        menuSpacer = new VerticalLayout();
        menuSpacer.setImmediate(false);
        menuSpacer.setWidth("100.0%");
        menuSpacer.setHeight("30px");
        menuSpacer.setMargin(false);
        
        // men_frm
        men_frm = new MenuBar();
        men_frm.setImmediate(false);
        men_frm.setWidth("100.0%");
        men_frm.setHeight("-1px");
        menuSpacer.addComponent(men_frm);
        menuSpacer.setComponentAlignment(men_frm, new Alignment(20));
        
        return menuSpacer;
    }

    @AutoGenerated
    private HorizontalLayout buildGlobalFilterContainer() {
        // common part: create layout
        globalFilterContainer = new HorizontalLayout();
        globalFilterContainer.setImmediate(false);
        globalFilterContainer.setWidth("100.0%");
        globalFilterContainer.setHeight("40px");
        globalFilterContainer.setMargin(false);
        
        // filterMonth
        filterMonth = new InlineDateField();
        filterMonth.setImmediate(false);
        filterMonth.setWidth("-1px");
        filterMonth.setHeight("-1px");
        globalFilterContainer.addComponent(filterMonth);
        globalFilterContainer.setComponentAlignment(filterMonth, new Alignment(48));
        
        // filterNurse
        filterNurse = new ComboBox();
        filterNurse.setCaption("Nurse");
        filterNurse.setImmediate(false);
        filterNurse.setWidth("-1px");
        filterNurse.setHeight("-1px");
        globalFilterContainer.addComponent(filterNurse);
        globalFilterContainer.setComponentAlignment(filterNurse, new Alignment(20));
        
        return globalFilterContainer;
    }

    @AutoGenerated
    private TabSheet buildTabs() {
        // common part: create layout
        tabs = new TabSheet();
        tabs.setImmediate(true);
        tabs.setWidth("100.0%");
        tabs.setHeight("100.0%");
        
        // cockpitCalendar
        cockpitCalendar = new CockpitCalendar();
        cockpitCalendar.setImmediate(false);
        cockpitCalendar.setWidth("100.0%");
        cockpitCalendar.setHeight("100.0%");
        tabs.addTab(cockpitCalendar, "Kalender", null);
        
        // tbl_data
        tbl_data = new FilterTable();
        tbl_data.setImmediate(true);
        tbl_data.setWidth("100.0%");
        tbl_data.setHeight("100.0%");
        tabs.addTab(tbl_data, "Übersicht", null);
        
        // warningList
        warningList = new WarningDataView();
        warningList.setImmediate(false);
        warningList.setWidth("100%");
        warningList.setHeight("100%");
        tabs.addTab(warningList, "Warnungen", null);
        
        return tabs;
    }
}
