package archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.OpenTickets.classes;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import org.tepi.filtertable.FilterTable;

import archenoah.config.CMS_Config_Std;
import archenoah.lib.custom.ComponentIterator;
import archenoah.lib.custom.CustomStyles;
import archenoah.lib.custom.CustomStyles.HIGHLIGHT;
import archenoah.lib.custom.MyUtils;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.tool.comunication.dbclass.DBClass.CustomQuery;
import archenoah.lib.vaadin.Components.Combo.combo;
import archenoah.lib.vaadin.Components.Steppers.BigDecimalStepper;
import archenoah.lib.vaadin.Components.Steppers.IntStepper;
import archenoah.lib.vaadin.Components.table.FilteringTableUpdater;
import archenoah.lib.vaadin.Forms_Builder.Form_Bind;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.OpenTickets.form.OpenTicketsInsertEdit;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.PackageCreator.classes.TicketContentsMover;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.PackageCreator.classes.TicketContentsMover.Action;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.PackageCreator.classes.TicketDbActions;

import com.google.common.base.Joiner;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.event.ItemClickEvent;
import com.vaadin.event.ShortcutAction;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.ui.AbstractComponent;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.CustomTable;
import com.vaadin.ui.CustomTable.CellStyleGenerator;
import com.vaadin.ui.DefaultFieldFactory;
import com.vaadin.ui.Field;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

import de.steinwedel.messagebox.ButtonId;
import de.steinwedel.messagebox.Icon;
import de.steinwedel.messagebox.MessageBox;
import de.steinwedel.messagebox.MessageBoxListener;

@SuppressWarnings("serial")
public class TicketContentsPanel extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	
    @AutoGenerated
    private VerticalLayout mainLayout;
    @AutoGenerated
    private VerticalLayout hiddenLayout;
    @AutoGenerated
    private ListSelect newData;
    @AutoGenerated
    private HorizontalLayout horizontalLayout_2;
    @AutoGenerated
    private IntStepper newQuantity;
    @AutoGenerated
    private IntStepper planQuantity;
    @AutoGenerated
    private ComboBox newProduct;
    @AutoGenerated
    private ComboBox newPatient;
    @AutoGenerated
    private Panel locationContenPanel;
    @AutoGenerated
    private VerticalLayout ticketContentPanelLayout;
    @AutoGenerated
    private HorizontalLayout horizontalLayout_1;
    @AutoGenerated
    private Button editNew;
    @AutoGenerated
    private Button editDelete;
    @AutoGenerated
    private Button editMove;
    @AutoGenerated
    private Button editCancel;
    @AutoGenerated
    private Button editSave;
    @AutoGenerated
    private Button editEnable;
    @AutoGenerated
    private CheckBox isGrouped;
    @AutoGenerated
    private HorizontalLayout horizontalLayout_3;
    @AutoGenerated
    private Label legendSp;
    @AutoGenerated
    private Label legendRx;
    @AutoGenerated
    private FilterTable tbl_data;
    
    
    
    
    
    
    
    
    
    
    
    
    
	
    /* **************************** */
    
    Map<Object, String> locationMap;
    Map<Object, String> dbMap;
    
    private org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(this.getClass());
    
    
//    private final String formIdLng = "1051";
    
    CMS_Config_Std std;
    
    private DbGetTicketContents dbGetTicketContents;
    
	/* **************************** */
    
    private Integer ticketId = null;
    private Date ticketStart;
    private Date ticketEnd;
    private Date deliveryDate;
    
    protected List<Field> fields = new ArrayList<Field>();
    private Boolean permEdit = false;
    private Boolean permAdd = false;
    private Boolean permMove = false;
    
    private MessageBox newEntryBox = null;
    
    private IntStepper newEntryProjectId = new IntStepper();
    
    /******************************************************/

    private final String tableIdCol = "OMTC_ID";
    private final String dataTableName = "cust_ordermanager_ticket_contents";
    
    private final Object[] tableColsAll = new Object[] {"project_date", "PP_PRODUCT", "patient_all", "rx", "sp", "project_quantity_static",  "OMTC_QTY"};
    //use custom Cols when needed
    private final Object[] tableColsDefault = tableColsAll;
    //use custom Cols when needed
    private final Object[] tableColsFilter = tableColsDefault;
    private Object[] tableColsActive = tableColsDefault;
    private Object[] tableColsGrouped = new Object[] {"PP_PRODUCT", "patient_all", "rx", "sp", "project_quantity_static",  "OMTC_QTY"};
    private FilteringTableUpdater tableUpdater;

    //editable Fields list
    private List<Object> tableFields = java.util.Arrays.asList(new Object[] {"OMTC_QTY"});
    private Integer newPatientDefault = null;
    private Integer nurseUserId = null;
    private I18nManager i18n;
    
    /******************************************************/
    
	public TicketContentsPanel() {
		
	    setCompositionRoot(buildMainLayout());
	    i18n = new I18nManager(this);
	    
		dbGetTicketContents = new DbGetTicketContents();
		
		registerComponents();
		
		fillDbMap();
		
		configureComponents();
		configureTable();
		
		fillFields();
		
		i18n.refresh();
	}
	
	 // register components for lng and validation tools
    private void registerComponents(){
    	
    	locationMap = new HashMap<Object, String>();
    	new ComponentIterator(ticketContentPanelLayout).createMap(locationMap);
    	
    }

    
	/* **************************** */
	
    public void getTicketContents(Integer ticketId){
        this.ticketId = ticketId;
        fillTable();
    }
	
    public Boolean saveTicketContents(){
        Boolean saved = saveContents();
        if(!saved){
            fillTable();
            I18nManager.global(I18nGlobalNotifiers.review_data); //review data
        }
        return saved;
    }
    
    public void setEditable(Boolean editable){
        this.permEdit = editable;
        setEditable();
    }
    public void setAddable(Boolean addable){
        this.permAdd = addable;
        setEditable();
    }
    public void setMoveable(Boolean moveable){
        this.permMove = moveable;
        setEditable();
    }
    /**
     * 
     * @return project_date, PP_PRODUCT, project_quantity_static, OMTC_QTY, patient_all, OMTC_ID_DATA, OMTC_ID, OMTC_UPDATED, OMTC_ID_PATIENT, PP_ID
     */
    public Container getCurrentValues() {
        return tbl_data.getContainerDataSource();
    }
    
    public void setPatientDefault(Integer patientId) {
        newPatientDefault = patientId;
    }
    
    public void setNurseUserID(Integer nurseUserId) {
        this.nurseUserId = nurseUserId;
    }
    
    public void setTicketRange(Date start, Date end) {
        this.ticketStart = start;
        this.ticketEnd = end;
    }
    
    public void setTicketDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }
    
//	public void setFieldsEnabled(Boolean enabled){
//		ticketContentPanelLayout.setEnabled(enabled);
//		ticketContentPanelLayout.setStyleName(enabled ? "" : "nogrey");
//	}
	
	/* **************************** */
	
	/* **************************** */
    
	/* **************************** */
	
    private void configureComponents(){
	
		for (Entry<Object, String> entry : locationMap.entrySet()) {
			AbstractComponent field = (AbstractComponent) entry.getKey();
			
			field.setImmediate(true);
			
			
			if(field instanceof ComboBox){
				((ComboBox)field).setFilteringMode(FilteringMode.CONTAINS);
			}
			
		}
		
		ticketContentPanelLayout.setStyleName("nogrey");
//    	ticketContentPanelLayout.setEnabled(false);
    	
		isGrouped.setValue(false);
		isGrouped.setImmediate(true);
		isGrouped.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                Boolean grouped = (Boolean) event.getProperty().getValue() ;
                
                if(grouped){
                    editEnable.setVisible(false);
                    editNew.setVisible(false);
                    editCancel.setVisible(false);
                    editSave.setVisible(false);
                }else{
                    configureEditable(false);
                }
                
                
                
                fillTable();                
            }
        });
    	
		editEnable.setEnabled(false);
    	editEnable.addClickListener(new ClickListener() {
            
            @Override
            public void buttonClick(ClickEvent event) {
                
                configureEditable(true);
                
            }
        });
    	
       editSave.addClickListener(new ClickListener() {
            
            @Override
            public void buttonClick(ClickEvent event) {
                
                commit();
                configureEditable(false);
                
            }
        });
       
       editCancel.addClickListener(new ClickListener() {
           
           @Override
           public void buttonClick(ClickEvent event) {
               
               discard();
               configureEditable(false);
               
           }
       });
       
       editCancel.setClickShortcut(ShortcutAction.KeyCode.ESCAPE);
       editSave.setClickShortcut(ShortcutAction.KeyCode.ENTER);
    
       configureEditable(false);
       
       editNew.addClickListener(new ClickListener() {
        
            @Override
            public void buttonClick(ClickEvent event) {
                
                newContent();
                
            }
        });

        editDelete.setVisible(false);
        editDelete.addClickListener(new ClickListener() {

            @SuppressWarnings("unchecked")
            @Override
            public void buttonClick(ClickEvent event) {

                ArrayList<Item> changeList = getChangeList(dbGetContents(), tbl_data.getContainerDataSource());

                dbDelete((Collection<Object>) tbl_data.getValue());
                fillTable();

                updateTableChanges(changeList);

            }
        });

        editMove.setVisible(false);
        editMove.addClickListener(new ClickListener() {
            
            @SuppressWarnings("unchecked")
            @Override
            public void buttonClick(ClickEvent event) {
                
                TicketContentsMover mover = new TicketContentsMover(true);
                TicketDbActions dba = mover.getDbActions();
                
                dba.setTicketData(dbGetTicketContents.getTicketItem());
                dba.setContentIds((Collection<Integer>) tbl_data.getValue());
                dba.setOriginalTicketId(ticketId);
                
                mover.showMessageBox(mover . new CloseAction() {
                    
                    @Override
                    public void onClose(Action action, Integer tid) {
                        
                        if(action == null) {
                            return;
                        }
                        
                        switch (action) {
                        case delete:
                            fillTable();
                            tbl_data.setValue(null);
                            break;
                        
                        default:
                            
                            fillTable();
                            tbl_data.setValue(null);
                            
                            log.info("tid is {}", tid);
                            
                            if(tid == null) {
                                return;
                            }
                            
                            OpenTicketsInsertEdit pie = new OpenTicketsInsertEdit(editMove, tid.toString());
                            pie.setPermissions(permAdd ? 1 : 0, 1, permEdit ? 1 : 0, permEdit ? 1 : 0);
                            pie.init();
                            
                            break;
                        }
                        
                    }
                });
                
                
                
            }
        });
        
       newPatient.setFilteringMode(FilteringMode.CONTAINS);
       newPatient.setNullSelectionAllowed(false);
       newPatient.setImmediate(true);
       newPatient.setRequired(true);
       newProduct.setItemCaptionPropertyId("PP_PRODUCT");
       newProduct.setFilteringMode(FilteringMode.CONTAINS);
       newProduct.setNullSelectionAllowed(false);
       newProduct.setEnabled(false);
       newProduct.setImmediate(true);
       newProduct.setRequired(true);
       newQuantity.setNullValueAllowed(false);
       newQuantity.setImmediate(true);
       newQuantity.setRequired(true);
       newQuantity.setMinValue(1);

       newPatient.addValueChangeListener(new ValueChangeListener() {
        
        @Override
        public void valueChange(ValueChangeEvent event) {
            
            dbGetProducts();
            newProduct.setEnabled(newProduct.getContainerDataSource().size() > 0);
            
        }
    });
       
       ValueChangeListener vcl = new ValueChangeListener() {
           
           @Override
           public void valueChange(ValueChangeEvent event) {
               
               if(newEntryBox == null){
                   return;
               }
               
               Boolean valid = (   
                       newPatient.isValid() &&
                       newProduct.isValid() &&
                       newQuantity.isValid() && 
                       newQuantity.getValue() > 0 &&
                       newData.isValid()
                       );
               
               newEntryBox.getButton(ButtonId.OK).setEnabled(valid);
               
           }
       };

       newPatient.addValueChangeListener(vcl);
       newProduct.addValueChangeListener(vcl);
       newQuantity.addValueChangeListener(vcl);
       
       ValueChangeListener dcl = new ValueChangeListener() {
        
        @Override
        public void valueChange(ValueChangeEvent event) {
                
                if(newPatient.getValue() == null
                        || newProduct.getValue() == null) {
                    return;
                }
            
                dbGetData();
                newData.setEnabled(newData.getContainerDataSource().size() > 0);
            }
            
        };
       
       newPatient.addValueChangeListener(dcl);
       newProduct.addValueChangeListener(dcl);
        
       newData.setEnabled(false);
       newData.setImmediate(true);
       newData.setNullSelectionAllowed(false);
       newData.setItemCaptionPropertyId("datef");
       
       newData.addValueChangeListener(new ValueChangeListener() {
        
            @Override
            public void valueChange(ValueChangeEvent event) {
                try {
                    planQuantity.setValue(((BigDecimal) newData.getContainerDataSource().getContainerProperty(newData.getValue(), "project_quantity_static").getValue()).intValue());
                } catch (Exception e) {
                    planQuantity.setValue(0);
                    log.info("error getting project_quantity_static for {}, e: {}", newData.getValue(), e);
                }
                
            }
           
    
        });
       
       planQuantity.setEnabled(false);
       planQuantity.setStyleName("nogrey no_stepper_control");
       
       planQuantity.addValueChangeListener(new ValueChangeListener() {
        
        @Override
        public void valueChange(ValueChangeEvent event) {
            
            Integer maxValue = null;
            
            if(MyUtils.getUserData().getNurse().isNurse() && planQuantity.getValue() != null && planQuantity.getValue() != 0) {
                maxValue = (int) (planQuantity.getValue() * 1.9);
            }
            newQuantity.setMaxValue(maxValue);
            newQuantity.setValue(planQuantity.getValue());
            
            
        }
    });
       
	}
	
    private void setEditable(){
        configureEditable(false);
    }
    
    private void configureEditable(boolean editable) {
        
        tbl_data.setSelectable(!editable);
        tbl_data.setFilterOnDemand(false);
        tbl_data.setEditable(permEdit && editable);
        editSave.setVisible(permEdit && editable);
        editCancel.setVisible(permEdit && editable);
        editEnable.setVisible(permEdit && !editable);
        editNew.setVisible(permAdd && !editable);
        if (permEdit && editable && !fields.isEmpty()) {
          fields.get(0).focus();
        }
        
        
        
      }
    
    
    private void commit() {
        for (Field field : fields) {
            
            if(field.isValid() && field.getValue() != null) {
                field.commit();
            }else {
                field.discard();
            }

        }
    }

    private void discard() {
        for (Field field : fields) {
            field.discard();
        }
    }
    
    private void fillDbMap(){
    	
    	String t = dataTableName + ":";
        
    	dbMap = new HashMap<>();
    	dbMap.put(newPatient, t + "OMTC_ID_PATIENT");
    	dbMap.put(newProduct, t + "OMTC_ID_PRODUCT");
    	dbMap.put(newQuantity, t + "OMTC_QTY");
    	dbMap.put(newData, t + "OMTC_ID_DATA");
    	//manual fields
    	dbMap.put(newEntryProjectId, t + "OMTC_ID_PROJECT");
    	

    }
    
    private void configureTable(){
        
        tbl_data.setSelectable(true);
        tbl_data.setFilterOnDemand(false);
        tbl_data.setImmediate(true);
        tbl_data.setFooterVisible(true);
        tbl_data.setMultiSelect(true);
        tbl_data.addItemClickListener(new ItemClickEvent.ItemClickListener() {
            @Override
            public void itemClick(ItemClickEvent itemClickEvent) {

              if (itemClickEvent.isDoubleClick() && !tbl_data.isEditable() && !isGrouped.getValue()) {
                  tbl_data.setValue(itemClickEvent.getItemId());
                configureEditable(permEdit);
              }
            }
          });
        
        tbl_data.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                Integer sv = getSingleValue();
                
                editEnable.setEnabled((sv != null && sv != 0));
                
                editDelete.setVisible(sv != null && permEdit && isDeletable());
                editMove.setVisible(sv != null && permMove && isMoveable());
                
            }
        });

        tbl_data.setCellStyleGenerator(new CellStyleGenerator() {

            @Override
            public String getStyle(CustomTable source, Object itemId, Object propertyId) {

                if (propertyId != null && propertyId.equals("rx")) {

                    Item item = tbl_data.getItem(itemId);

                    Integer rx = null;
                    Integer qty = null;
                    
                    
                    if(item.getItemProperty(propertyId) != null
                            && item.getItemProperty(propertyId).getValue() != null) {
                        rx = ((BigDecimal) item.getItemProperty(propertyId).getValue()).intValueExact();
                    }
                    
                    if(item.getItemProperty("OMTC_QTY") != null
                            && item.getItemProperty("OMTC_QTY").getValue() != null) {
                        qty = ((BigDecimal) item.getItemProperty("OMTC_QTY").getValue()).intValueExact();
                    }
                    
                    if (rx == null || (qty != null && (rx - qty) < 0)) {
                        return CustomStyles.get(HIGHLIGHT.RED);
                    }

                }
                return null;
            }

        });
        
        tbl_data.setTableFieldFactory(new DefaultFieldFactory() {
            @Override
            public Field<?> createField(Container container, Object itemId, Object propertyId, com.vaadin.ui.Component uiContext) {
              // If the itemId isn't the currently selected item in the table, don't generate a field
              // i.e. it's not editable
              if (!itemId.equals(getSingleValue())) {
                return null;
              }
              
              // create only fields for specified properties
              if(!tableFields.contains(propertyId)){
                  return null;
              }
              
              // Let the default factory build the field : you can and probably should do far more
              // Logic here
              //Field<?> field = super.createField(container, itemId, propertyId, uiContext);
              BigDecimalStepper field = new BigDecimalStepper();
              field.setMinValue(BigDecimal.ZERO);
              
              BigDecimal qs = MyUtils.getValueFromItem(container.getItem(itemId), "project_quantity_static", BigDecimal.class);
              if(qs != null) {
                  field.setMaxValue(qs);
              }
              
              // Make the field buffered - this lets us discard the value
              field.setBuffered(true);

              // Let's keep track of all of the attached fields
              field.addAttachListener(new AttachListener() {
                @Override
                public void attach(AttachEvent attachEvent) {
                  fields.add((Field) attachEvent.getConnector());
                }
              });
              field.addDetachListener(new DetachListener() {
                @Override
                public void detach(DetachEvent event) {
                  fields.remove(event.getConnector());
                }
              });
              
              field.setInvalidAllowed(false);
              field.setInvalidCommitted(false);
              
              
              


              return field;
            }
          });
    }
    
    private void fillTable() {

        boolean refresh = tbl_data.size() == 0;
        tbl_data.setContainerDataSource(dbGetContents());
        
        try{
            
            if(isGrouped.getValue()){
                tbl_data.setVisibleColumns(tableColsGrouped);
            }else{
                tbl_data.setVisibleColumns(tableColsActive);
            }
            
        }catch(Exception e){
             
        }
        
        tbl_data.setColumnExpandRatio("patient_all", 1);
        
        //if(refresh && tbl_data.size() > 0) {
        if(refresh ) {
            i18n.refresh();
        }
//        updateSums();
    }
    
    private void fillFields(){
        
        dbGetPatients();
        
    }
    
//    private void updateSums(){
//        tbl_data.setColumnFooter("OMTC_QTY", "Σ " + calculateSum("OMTC_QTY"));
//        tbl_data.setColumnFooter("project_quantity_static", "Σ " + calculateSum("project_quantity_static"));
////        tbl_data.setColumnFooter("patient_all", Integer.toString(tbl_data.size())); //potentially confusing
//    }
    
    private Integer calculateSum(Object propId){
        
        Container con = tbl_data.getContainerDataSource();
        Integer count = 0;
        for (Object id : con.getItemIds()) {
            try {
                count = count + Integer.parseInt(con.getItem(id).getItemProperty(propId).getValue().toString());
            } catch (Exception e) {
                continue;
            }
            
        }
        
        return count;
        
    }
    
    private Item getItemById(Container con, Object value){
        
        for(Object cid : con.getItemIds()){
            
            if(MyUtils.equalsWithNulls(con.getContainerProperty(cid, tableIdCol).getValue(), value)){
                return con.getItem(cid);
            }
            
        }
        
        return null;
        
    }
    
    private Item getItemByItem(Container con, Item item){
        return getItemById(con, item.getItemProperty(tableIdCol).getValue());
    }
    
    /**
     * 
     * @return id / 0 / null
     */
    private Integer getSingleValue() {
        Integer res = null;
        
        Collection<Integer> coll = (Collection<Integer>) tbl_data.getValue();
        
        if(coll != null) {
            if(coll.size() == 1) {
                res = coll.iterator().next();
            }else if(coll.size() > 0) {
                res = 0;
            }
            
        }
        
        return res;
    }
    
    private Boolean isDatabaseModified(Container dbc, Container cur){
        
        if(dbc.size() != cur.size()){
            System.out.println("database modification: con.size()");
            return true;
        }
        
        for(Object cid : cur.getItemIds()){
            
            if(!MyUtils.equalsWithNulls(
                    cur.getContainerProperty(cid, "OMTC_UPDATED").getValue(),
                    getItemByItem(dbc, cur.getItem(cid))
                    .getItemProperty("OMTC_UPDATED").getValue())
            ){
                System.out.println("database modification: OMTC_UPDATED");
                return true;
                
            }
            
        }
        
        
        return false;
        
    }
    
    private Boolean isDeletable(){
        
        Boolean deletable = true;
        
        Container con = tbl_data.getContainerDataSource();
        
        Collection<Integer> coll = (Collection<Integer>) tbl_data.getValue();
        
        for (Integer iid : coll) {
            Item item = con.getItem(iid);
            
            if(item == null || item.getItemProperty("OMTC_CUSTOM") == null){
                deletable = false;
                break;
            }
            
            if(!(Boolean) item.getItemProperty("OMTC_CUSTOM").getValue()) {
                deletable = false;
                break;
            }
        }
        
        return deletable;
        
    }
    
    private Boolean isMoveable(){
        
        Boolean moveable = true;
        
        Container con = tbl_data.getContainerDataSource();
        
        Collection<Integer> coll = (Collection<Integer>) tbl_data.getValue();
        
        for (Integer iid : coll) {
            Item item = con.getItem(iid);
            
            if(item == null || item.getItemProperty("OMTC_CUSTOM") == null){
                moveable = false;
                break;
            }
            
            if((Boolean) item.getItemProperty("OMTC_CUSTOM").getValue()) {
                moveable = false;
                break;
            }
        }
        
        return moveable;
        
    }
    
    private ArrayList<Item> getChangeList(Container dbc, Container cur){
        ArrayList<Item> changeList = new ArrayList<Item>();
        
        for (Object cid : cur.getItemIds()) {
            
            Item cit = cur.getItem(cid);
            Item dit = getItemByItem(dbc, cit);
            
            for (Object propId : tableFields) {
                if(!MyUtils.equalsWithNulls(cit.getItemProperty(propId).getValue(), dit.getItemProperty(propId).getValue())){
                    changeList.add(cit);
                }
            }
        }
        
        return changeList;
    }
    
    private Boolean saveContents(){
        
        Container dbc = dbGetContents();
        Container cur = tbl_data.getContainerDataSource();
        
        if(isDatabaseModified(dbc, cur)){
            return false;
        }
        
        ArrayList<Item> saveList = getChangeList(dbc, cur);
        
        if(saveList.size() == 0){
            return true;
        }
        
        Integer result = 0;
        
        DBClass db = new DBClass();
        
        for (Item item : saveList) {
            
            String sql = "UPDATE cust_ordermanager_ticket_contents ";    
            String comma = "";
            
            for (Object propId : tableFields) {
                sql += comma + "SET " + propId.toString() + "=" + item.getItemProperty(propId).getValue();
                comma = ", ";
            }
            sql += " WHERE OMTC_ID = " + item.getItemProperty(tableIdCol).getValue() + ";";

            db.CustomQuery.setSqlString(sql);
//            db.debugNextQuery(true);
            result += db.CustomQuery.update();
        }
        
        return result.equals(saveList.size());
        
    }
    
    private void newContent(){
        
//        VerticalLayout vl = new VerticalLayout();
//        vl.addComponent(newPatient);
//        vl.addComponent(newProduct);
//        vl.addComponent(newQuantity);
        
        newPatient.setValue(newPatientDefault);
        newProduct.setValue(null);
        newProduct.setEnabled(false);
        planQuantity.setValue(0);
        newQuantity.setValue(0);
        newData.setValue(null);
        newData.setNullSelectionAllowed(!MyUtils.getUserData().getNurse().isNurse());
        newData.setRequired(MyUtils.getUserData().getNurse().isNurse());
        
        newData.setContainerDataSource(null);
        
        if(newPatientDefault != null) {
            dbGetProducts();
            newProduct.setEnabled(newProduct.getContainerDataSource().size() > 0);
        }
        
        MessageBoxListener mbl = new MessageBoxListener() {
            
            @Override
            public void buttonClicked(ButtonId buttonId) {
                
                if(buttonId.equals(ButtonId.OK)){
                    
                    ArrayList<Item> changeList = getChangeList(dbGetContents(), tbl_data.getContainerDataSource());
                    
                    dbSaveNew();
                    fillTable();

                    updateTableChanges(changeList);
                    
                }
                
            }
        };
        
        
        newEntryBox = MessageBox.showCustomized(Icon.NONE, "Neu", hiddenLayout, mbl, ButtonId.OK, ButtonId.CANCEL);
        newEntryBox.getButton(ButtonId.OK).setEnabled(false);

    }

    
    @SuppressWarnings("unchecked")
    private void updateTableChanges(ArrayList<Item> changeList){
        
        Container cur = tbl_data.getContainerDataSource();
        
        for (Item newItem : changeList) {
            
            Item currentItem = getItemByItem(cur, newItem);
            
            for (Object fieldName : tableFields) {
                
                currentItem.getItemProperty(fieldName).setValue(
                        newItem.getItemProperty(fieldName).getValue());
                
            }
            
        }
        
    }
    
    private void dbGetPatients(){
        
        DBClass db = new DBClass();
        
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("PSL_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln(
                "CONCAT(PSL_TITEL,' ',PSA_NAME,' ',PSL_NAME,' ',PSL_VORNAME, ' (',PSL_PLZ, ' ', PSL_ORT,')')", "Patientenname");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_patient_stammdaten_liste", "INNER JOIN",
                "cust_patient_stammdaten_anrede", "PSL_ANREDE", "PSA_ID");
       
        
        try {
            combo nc = new combo(db.DB_Data_Get.DB_SEND_AND_GET(), newPatient, "PSL_ID", "Patientenname");
        } catch (Exception e) {
            newPatient.removeAllItems();
        }
        
    }
    
    private void dbGetProducts(){
        
        String sql = "select distinct PP_ID, PP_ID_PROJECT, PP_PRODUCT"
        + "\n " + "from cust_prescriptions_products "
        + "\n " + "left join cust_verk_haupt on PP_ID_PROJECT = VH_PROJEKT_ID"
        + "\n " + "left join cust_ordermanager_standalone on PP_ID = OMS_ID_PRODUCT";
        
        CustomQuery q = new DBClass().CustomQuery;
        
        if(newPatient.getValue() != null) {
            sql += "\n " + "where VH_PATIENT_ID = "+newPatient.getValue()+" OR OMS_ID_PATIENT = "+newPatient.getValue() + " OR PP_ID_PROJECT = 1000";
        }
        
        q.setSqlString(sql);
        newProduct.setContainerDataSource(MyUtils.convertIndex(q.query(), "PP_ID"));

        
    }
    
    private void dbGetData() {
        
        DBClass db = new DBClass();
        
        Container con = newProduct.getContainerDataSource();
        
        newEntryProjectId.setValue((Integer) con.getContainerProperty(newProduct.getValue(), "PP_ID_PROJECT").getValue());
//        System.out.println(con.getContainerProperty(newProduct.getValue(), "PSLV_NAME"));
        
        Date start = (deliveryDate != null && deliveryDate.after(ticketStart)) ? deliveryDate : ticketStart;
        if(start == null || ticketEnd == null) {
            log.error("no ticket range available! delivery:{}, start: {}, end: {}", deliveryDate, ticketStart, ticketEnd);
            return;
        }
        
        String dateRange = "";
        if(MyUtils.getUserData().getNurse().isNurse()) {
            dateRange = "and date between '" + MyUtils.formatSqlDate(start) + "' and '" + MyUtils.formatSqlDate(ticketEnd) + "'";
        }
        
        String nurseFilter = "";
        if(nurseUserId != null) {
            nurseFilter = "and nurse_user_id = " + nurseUserId;
        }
        
        String sql = "select project_data_id as pid, project_date, date, DATE_FORMAT(`date`,'%d.%m.%y') as datef, project_quantity_static"
        + "\n " + "from view_packagemanager_union_complete"
        + "\n " + "where status is NULL"
        + "\n " + "    and project = " + newEntryProjectId.getValue()
        + "\n " + "    and product = " + newProduct.getValue()
        + "\n " + "    and patient_id = " + newPatient.getValue()
        + "\n " + "    " + nurseFilter
        + "\n " + "    and accepted = 1"
        + "\n " + "    " + dateRange
        + "\n " + "    order by date ASC ";
        
        db.CustomQuery.setSqlString(sql);
        
//        db.debugNextQuery(true);
        
        IndexedContainer res = (IndexedContainer) db.CustomQuery.query();
        res.sort(new Object[] {"date"}, new boolean[] {true});
        
        newData.setContainerDataSource(MyUtils.convertIndex(res, "pid"));
        
    }
    
    
	private Container dbGetContents(){
	    
	    dbGetTicketContents.setTicketId(ticketId);
	    dbGetTicketContents.setGrouped(isGrouped.getValue());
//	    dbGetTicketContents.setDebug(true);
	    
	    return dbGetTicketContents.getContainer();
	    
	}
	
	private int dbSaveNew(){
	    
        DBClass db = new DBClass();
        
        Form_Bind fb = new Form_Bind();
        fb.Insert(db, dbMap);
        db.DB_Data_Insert.DB_Daten.DB_Data(dataTableName, "OMTC_ID_TICKET", ticketId.toString());
        db.DB_Data_Insert.DB_Daten.DB_Data(dataTableName, "OMTC_CUSTOM", "1");
        db.DB_Data_Insert.DB_Tabellen.DB_set_Tabelle_Einzeln(dataTableName);
        
        return db.DB_Data_Insert.DB_Insert();
	    
	}
	
	private void dbDelete(Collection<Object> ids){
	    
	    DBClass db = new DBClass();
	    db.DB_Data_Delete.DB_Tabellen.DB_set_Tabelle_Einzeln(dataTableName);
	    db.DB_Data_Delete.DB_Filter.DB_WHERE_In(dataTableName, tableIdCol, Joiner.on(", ").join(ids), "");
	    db.DB_Data_Delete.DB_Delete();
	    
	}
	
	@AutoGenerated
    private VerticalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setStyleName("cust_margin_none");
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(true);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // locationContenPanel
        locationContenPanel = buildLocationContenPanel();
        mainLayout.addComponent(locationContenPanel);
        mainLayout.setExpandRatio(locationContenPanel, 12.0f);
        mainLayout.setComponentAlignment(locationContenPanel, new Alignment(24));
        
        // hiddenLayout
        hiddenLayout = buildHiddenLayout();
        mainLayout.addComponent(hiddenLayout);
        
        return mainLayout;
    }

    @AutoGenerated
    private Panel buildLocationContenPanel() {
        // common part: create layout
        locationContenPanel = new Panel();
        locationContenPanel.setImmediate(false);
        locationContenPanel.setWidth("100.0%");
        locationContenPanel.setHeight("100.0%");
        
        // ticketContentPanelLayout
        ticketContentPanelLayout = buildTicketContentPanelLayout();
        locationContenPanel.setContent(ticketContentPanelLayout);
        
        return locationContenPanel;
    }

    @AutoGenerated
    private VerticalLayout buildTicketContentPanelLayout() {
        // common part: create layout
        ticketContentPanelLayout = new VerticalLayout();
        ticketContentPanelLayout.setImmediate(false);
        ticketContentPanelLayout.setWidth("100.0%");
        ticketContentPanelLayout.setHeight("100.0%");
        ticketContentPanelLayout.setMargin(false);
        ticketContentPanelLayout.setSpacing(true);
        
        // tbl_data
        tbl_data = new FilterTable();
        tbl_data.setImmediate(false);
        tbl_data.setWidth("100.0%");
        tbl_data.setHeight("100.0%");
        ticketContentPanelLayout.addComponent(tbl_data);
        ticketContentPanelLayout.setExpandRatio(tbl_data, 1.0f);
        
        // horizontalLayout_3
        horizontalLayout_3 = buildHorizontalLayout_3();
        ticketContentPanelLayout.addComponent(horizontalLayout_3);
        ticketContentPanelLayout.setComponentAlignment(horizontalLayout_3, new Alignment(6));
        
        // horizontalLayout_1
        horizontalLayout_1 = buildHorizontalLayout_1();
        ticketContentPanelLayout.addComponent(horizontalLayout_1);
        
        return ticketContentPanelLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_3() {
        // common part: create layout
        horizontalLayout_3 = new HorizontalLayout();
        horizontalLayout_3.setImmediate(false);
        horizontalLayout_3.setWidth("-1px");
        horizontalLayout_3.setHeight("-1px");
        horizontalLayout_3.setMargin(false);
        horizontalLayout_3.setSpacing(true);
        
        // legendRx
        legendRx = new Label();
        legendRx.setImmediate(false);
        legendRx.setWidth("-1px");
        legendRx.setHeight("-1px");
        legendRx.setValue("RX: aktuelles Rezeptguthaben  |  ");
        horizontalLayout_3.addComponent(legendRx);
        
        // legendSp
        legendSp = new Label();
        legendSp.setImmediate(false);
        legendSp.setWidth("-1px");
        legendSp.setHeight("-1px");
        legendSp.setValue("SP: aktueller Lagerbestand  ");
        horizontalLayout_3.addComponent(legendSp);
        
        return horizontalLayout_3;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_1() {
        // common part: create layout
        horizontalLayout_1 = new HorizontalLayout();
        horizontalLayout_1.setImmediate(false);
        horizontalLayout_1.setWidth("100.0%");
        horizontalLayout_1.setHeight("-1px");
        horizontalLayout_1.setMargin(false);
        
        // isGrouped
        isGrouped = new CheckBox();
        isGrouped.setCaption("gruppieren");
        isGrouped.setImmediate(false);
        isGrouped.setWidth("-1px");
        isGrouped.setHeight("-1px");
        horizontalLayout_1.addComponent(isGrouped);
        horizontalLayout_1.setComponentAlignment(isGrouped, new Alignment(48));
        
        // editEnable
        editEnable = new Button();
        editEnable.setCaption("Bearbeiten");
        editEnable.setImmediate(true);
        editEnable.setWidth("-1px");
        editEnable.setHeight("-1px");
        horizontalLayout_1.addComponent(editEnable);
        horizontalLayout_1.setComponentAlignment(editEnable, new Alignment(48));
        
        // editSave
        editSave = new Button();
        editSave.setCaption("Übernehmen");
        editSave.setImmediate(true);
        editSave.setWidth("-1px");
        editSave.setHeight("-1px");
        horizontalLayout_1.addComponent(editSave);
        horizontalLayout_1.setComponentAlignment(editSave, new Alignment(48));
        
        // editCancel
        editCancel = new Button();
        editCancel.setCaption("Abbrechen");
        editCancel.setImmediate(true);
        editCancel.setWidth("-1px");
        editCancel.setHeight("-1px");
        horizontalLayout_1.addComponent(editCancel);
        horizontalLayout_1.setComponentAlignment(editCancel, new Alignment(48));
        
        // editMove
        editMove = new Button();
        editMove.setCaption("Verschieben");
        editMove.setImmediate(true);
        editMove.setWidth("-1px");
        editMove.setHeight("-1px");
        horizontalLayout_1.addComponent(editMove);
        horizontalLayout_1.setComponentAlignment(editMove, new Alignment(48));
        
        // editDelete
        editDelete = new Button();
        editDelete.setCaption("Löschen");
        editDelete.setImmediate(true);
        editDelete.setWidth("-1px");
        editDelete.setHeight("-1px");
        horizontalLayout_1.addComponent(editDelete);
        horizontalLayout_1.setComponentAlignment(editDelete, new Alignment(48));
        
        // editNew
        editNew = new Button();
        editNew.setCaption("Neu");
        editNew.setImmediate(true);
        editNew.setWidth("-1px");
        editNew.setHeight("-1px");
        horizontalLayout_1.addComponent(editNew);
        horizontalLayout_1.setComponentAlignment(editNew, new Alignment(48));
        
        return horizontalLayout_1;
    }

    @AutoGenerated
    private VerticalLayout buildHiddenLayout() {
        // common part: create layout
        hiddenLayout = new VerticalLayout();
        hiddenLayout.setImmediate(true);
        hiddenLayout.setWidth("100.0%");
        hiddenLayout.setHeight("100.0%");
        hiddenLayout.setMargin(false);
        
        // newPatient
        newPatient = new ComboBox();
        newPatient.setCaption("Patient");
        newPatient.setImmediate(true);
        newPatient.setWidth("100.0%");
        newPatient.setHeight("-1px");
        newPatient.setInvalidAllowed(false);
        hiddenLayout.addComponent(newPatient);
        
        // newProduct
        newProduct = new ComboBox();
        newProduct.setCaption("Medikament");
        newProduct.setImmediate(true);
        newProduct.setWidth("100.0%");
        newProduct.setHeight("-1px");
        newProduct.setInvalidAllowed(false);
        hiddenLayout.addComponent(newProduct);
        
        // horizontalLayout_2
        horizontalLayout_2 = buildHorizontalLayout_2();
        hiddenLayout.addComponent(horizontalLayout_2);
        
        // newData
        newData = new ListSelect();
        newData.setCaption("Protokolldatum");
        newData.setImmediate(false);
        newData.setWidth("100.0%");
        newData.setHeight("100px");
        hiddenLayout.addComponent(newData);
        
        return hiddenLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_2() {
        // common part: create layout
        horizontalLayout_2 = new HorizontalLayout();
        horizontalLayout_2.setImmediate(false);
        horizontalLayout_2.setWidth("100.0%");
        horizontalLayout_2.setHeight("-1px");
        horizontalLayout_2.setMargin(false);
        horizontalLayout_2.setSpacing(true);
        
        // planQuantity
        planQuantity = new IntStepper();
        planQuantity.setCaption("Planmenge");
        planQuantity.setImmediate(false);
        planQuantity.setWidth("100.0%");
        planQuantity.setHeight("-1px");
        horizontalLayout_2.addComponent(planQuantity);
        horizontalLayout_2.setExpandRatio(planQuantity, 1.0f);
        
        // newQuantity
        newQuantity = new IntStepper();
        newQuantity.setCaption("Menge");
        newQuantity.setImmediate(true);
        newQuantity.setWidth("100.0%");
        newQuantity.setHeight("-1px");
        horizontalLayout_2.addComponent(newQuantity);
        horizontalLayout_2.setExpandRatio(newQuantity, 1.0f);
        
        return horizontalLayout_2;
    }
	
}


