package archenoah.web.normal.main.Menuepunkte.Individuelle.TaskSystem.MeetingLogging.form;

import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Map.Entry;

import archenoah.lib.custom.ComponentIterator;
import archenoah.lib.custom.ContainerTool;
import archenoah.lib.custom.MyUtils;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.vaadin.Components.Fields.CustomTimePicker;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Tab_Menue_Item;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Window_Button;
import archenoah.lib.vaadin.Forms_Builder.Form_Bind;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.lib.vaadin.MenuBerechtigung.Rechteholen;
import archenoah.lib.vaadin.valchecker.val_checker4;
import archenoah.web.normal.main.Menuepunkte.Individuelle.TaskSystem.MeetingLogging.classes.MeetingGroupContainer;
import archenoah.web.normal.main.Menuepunkte.Individuelle.TaskSystem.MeetingLogging.classes.MeetingTopicContainer;
import archenoah.web.normal.main.Menuepunkte.Individuelle.TaskSystem.TaskManager.classes.TTYPE;
import archenoah.web.normal.main.Menuepunkte.Individuelle.TaskSystem.TaskManager.classes.UserContainer;
import archenoah.web.normal.main.Menuepunkte.Individuelle.TaskSystem.TaskManager.form.TaskManagerDataView;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Container.ItemSetChangeEvent;
import com.vaadin.data.Container.ItemSetChangeListener;
import com.vaadin.data.Item;
import com.vaadin.event.ShortcutAction;
import com.vaadin.event.ShortcutListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.ui.AbstractComponent;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Layout;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TabSheet.SelectedTabChangeEvent;
import com.vaadin.ui.TabSheet.SelectedTabChangeListener;
import com.vaadin.ui.TabSheet.Tab;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;


@SuppressWarnings({"serial", "rawtypes", "unchecked"})
public class MeetingLoggingInsertEdit extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private VerticalLayout mainLayout;

    @AutoGenerated
    private HorizontalLayout buttons;

    @AutoGenerated
    private Button btn_save;

    @AutoGenerated
    private VerticalLayout main;

    @AutoGenerated
    private TabSheet tabMain;

    @AutoGenerated
    private VerticalLayout layoutTopics;

    @AutoGenerated
    private Panel panelTopics;

    @AutoGenerated
    private VerticalLayout layoutTopicsPanel;

    @AutoGenerated
    private Accordion wrapperTopics;

    @AutoGenerated
    private HorizontalLayout layoutNewTopic;

    @AutoGenerated
    private Button buttonNewTopicAdd;

    @AutoGenerated
    private TextField fieldNewTopicTitle;

    @AutoGenerated
    private HorizontalLayout layoutParticipants;

    @AutoGenerated
    private VerticalLayout layoutGuests;

    @AutoGenerated
    private TextArea fieldGuests;

    @AutoGenerated
    private VerticalLayout layoutUsers;

    @AutoGenerated
    private ListSelect listUsers;

    @AutoGenerated
    private HorizontalLayout layoutAddUser;

    @AutoGenerated
    private Button buttonRemoveUsers;

    @AutoGenerated
    private Label labelUserCount;

    @AutoGenerated
    private Button buttonAddUser;

    @AutoGenerated
    private ComboBox fieldAddUser;

    @AutoGenerated
    private Panel panelHeader;

    @AutoGenerated
    private VerticalLayout verticalLayout_4;

    @AutoGenerated
    private HorizontalLayout layoutHeader;

    @AutoGenerated
    private ComboBox fieldEditor;

    @AutoGenerated
    private ComboBox fieldTeam;

    @AutoGenerated
    private PopupDateField fieldDateNext;

    @AutoGenerated
    private HorizontalLayout layoutDate;

    @AutoGenerated
    private CustomTimePicker fieldTimeEnd;

    @AutoGenerated
    private CustomTimePicker fieldTimeStart;

    @AutoGenerated
    private PopupDateField fieldDate;

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */

    /**************** --> Allgemein <--- ********************/
    // Allgemein
    private String exportCaption;
    
    // Datenbank
    private Map<Object, String> componentMap;
    private Map<Object, String> dbMap;
    private Map<Object, String> validateMap;
    private Form_Bind fb;
    private String dataSetId = "";

    
    // Berrechtigung
    private int ACC_ID;
	private Integer permRead;
	private Integer permUpdate;
	private Integer permCreate;
	private Integer permDelete;

    private MenuItem tmpMenu = null;
    private Button tmpButton = null;
    /******************************************************/
    /**************** --> Tabsheetvars <--- *****************/
    private TabSheet tab = null;
    /******************************************************/
    /**************** --> Windowvars <--- *******************/
    private Window win = null;
    /******************************************************/
    /******************* --> Custom <--- ********************/
    /******************************************************/
    
    private UserContainer userContainer;
    private MeetingGroupContainer groupContainer;
    
    private TaskManagerDataView taskManagerDataView;
    private Layout taskManagerDataViewLayout;
    private LinkedHashMap<Integer, Integer> topicList = new LinkedHashMap<Integer, Integer>();
    
    
    /************ ----->Einstellungen<-- ********************/
//    private final String formIdLng = "304";
    private final String formIdPerm = "304";
    private final String Windows_Height = "600px";
    private final String Windows_Width = "800px";
    
    private final String dataIdCol = "TMEL_ID";
    private final String dataTableName = "cust_taskmanager_meeting_logs";

    private I18nManager i18n;
    
    /******************************************************/

    public MeetingLoggingInsertEdit(MenuItem Arg_Menü, String Arg_Form_ID) {
        tmpMenu = Arg_Menü;
        dataSetId = Arg_Form_ID;
    }

    public MeetingLoggingInsertEdit(Button Arg_btn, String Arg_Form_ID) {
        tmpButton = Arg_btn;
        dataSetId = Arg_Form_ID;
    }

    /********* INIT-Window ************/
    public void init() {
        if (Windows_Height.equals("") == true || Windows_Width.equals("") == true) {
            System.out.println("Form Einstellung Fehlt: !!!");
            return;
        }

        Standard_Init();

        String fid = dataSetId;
        if (fid != "") {
            fid = " - #" + fid;
        }

        if (tmpMenu != null) {
        	
            String Recourcename = null;
            ThemeResource resource = null;
            if(tmpMenu.getIcon() != null){
            	Recourcename = tmpMenu.getIcon().toString();
            	Recourcename = Recourcename.substring(0, Recourcename.length() - 12) + "white-16.png";
            	resource = new ThemeResource(Recourcename);
            }

            exportCaption = tmpMenu.getText();
            Build_Window_Button bwb = new Build_Window_Button(tmpMenu.getText() + fid, mainLayout, Windows_Height, Windows_Width, resource);
            win = bwb.ReturnWindow();
        }
        if (tmpButton != null) {
            exportCaption = tmpButton.getCaption();
            Build_Window_Button bwb = new Build_Window_Button(tmpButton.getCaption() + fid, mainLayout, Windows_Height, Windows_Width, tmpButton.getIcon());
            win = bwb.ReturnWindow();
        }

    }

    /********* INIT-Tray ************/
    public void init(TabSheet Arg_tab) {

        Standard_Init();
        tab = Arg_tab;
        if (tmpMenu != null) {
            exportCaption = tmpMenu.getText();
            new Build_Tab_Menue_Item(Arg_tab, tmpMenu.getText(), mainLayout, tmpMenu.getIcon());
        }
        if (tmpButton != null) {
            exportCaption = tmpButton.getCaption();
            new Build_Tab_Menue_Item(Arg_tab, tmpButton.getCaption(), mainLayout, tmpButton.getIcon());
        }

    }
    
    public Window getWindow(){
    	return win;
    }
    
    public TabSheet getTabSheet(){
    	return tab;
    }
    
    /********* Init-Standard ************/
    private void Standard_Init() {
        buildMainLayout();
        i18n = new I18nManager(this);
        
        fb = new Form_Bind();
        ACC_ID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        
        registerComponents();
        
        initTaskManager();
        
        fillFields();
        fillDbMap();

        setCustomValidators();
        fillValidateMap();

        /***************/

        if (dataSetId != "") {
        	
            dbFillForm();
            dbGetUsers();
            getTopics();
            
        } else {
            
        	//TASK "create init"
            fieldDate.setValue(new Date());
        	
        }

        setMenuPermissions();
        configureComponents();
        
        setEventListeners();
        
        i18n.ignore(labelUserCount);
        i18n.ignore(wrapperTopics);
        i18n.refresh();
    }
    
 // register components for lng and validation tools
    private void registerComponents(){
    	componentMap = new HashMap<Object, String>();
    	new ComponentIterator(main).createMap(componentMap);
    	componentMap.put(fieldAddUser, "teilnehmer_hinzufgen");
    }
    
    
    private void configureComponents(){
        
        for (Entry<Object, String> entry : componentMap.entrySet()) {
            
            if(entry.getKey() instanceof AbstractComponent){
                AbstractComponent field = (AbstractComponent) entry.getKey();
                
                field.setImmediate(true);
                
                
                if(field instanceof ComboBox){
                    ((ComboBox)field).setFilteringMode(FilteringMode.CONTAINS);
                }
            }
            
            
        }
        

//        addTopic(1, "Orange");
//        addTopic(2, "Tomato");
        
//    	for (int i = 1; i < 2; i++) {
//    	    
//    	    wrapperTopics.addTab(new MeetingTopicContainer(), "TOP " + i);
//            
//        }
    	
    	wrapperTopics.setHeight(null);
    	layoutTopicsPanel.setHeight(null);
    	
    	
//    	fieldAddUser.setItemCaptionPropertyId("user");
    	fieldAddUser.setNullSelectionAllowed(true);
//    	fieldEditor.setItemCaptionPropertyId("user");
    	fieldEditor.setNullSelectionAllowed(false);
    	
//    	fieldTeam.setItemCaptionPropertyId("TMEG_NAME");
    	fieldTeam.setNullSelectionAllowed(false);
    	
    	listUsers.setNullSelectionAllowed(false);
    	
    	componentListeners();
    	

    	
    }
    
    private void addUser(){
        if(fieldAddUser.getValue() == null){
            return;
        }
        
        addParticipantUser(fieldAddUser.getValue(), fieldAddUser.getItemCaption(fieldAddUser.getValue()));
        fieldAddUser.setValue(null);
        
    }
    
    private void componentListeners(){
        
       
    	buttonAddUser.addClickListener(new ClickListener() {
            
            @Override
            public void buttonClick(ClickEvent event) {
                
                addUser();
                
            }
        });
        
    	buttonRemoveUsers.addClickListener(new ClickListener() {
            
            @Override
            public void buttonClick(ClickEvent event) {
                
                listUsers.removeItem(listUsers.getValue());
                
            }
        });
    	
    	wrapperTopics.addSelectedTabChangeListener(new SelectedTabChangeListener() {
            
            @Override
            public void selectedTabChange(SelectedTabChangeEvent event) {
                
                MeetingTopicContainer mtc = (MeetingTopicContainer) event.getTabSheet().getSelectedTab();
                mtc.updateTaskList();
                //panelTopics.setScrollTop(0); // maybe calculate top position and scroll to it 
                
            }
        });
    	
    	tabMain.addSelectedTabChangeListener(new SelectedTabChangeListener() {
            
            @Override
            public void selectedTabChange(SelectedTabChangeEvent event) {
                
                if(MyUtils.isSelectedTab(1, event) && dataSetId.equals("")){
                    
                    saveForm();
                    
                }
                
            }
        });
    	
    	fieldAddUser.addShortcutListener(new ShortcutListener("enter", ShortcutAction.KeyCode.ENTER, null) {
            
            @Override
            public void handleAction(Object sender, Object target) {
                
                addUser();
                
            }
        });
    	
    	
    	listUsers.addItemSetChangeListener(new ItemSetChangeListener() {
            
            @Override
            public void containerItemSetChange(ItemSetChangeEvent event) {
                
                labelUserCount.setValue(Integer.toString(listUsers.size()));
                
            }
        });
    	
    	
    	buttonNewTopicAdd.addClickListener(new ClickListener() {
            
            @Override
            public void buttonClick(ClickEvent event) {
                newTopic();
            }
        });
    	
    }
    
    private void addParticipantUser(Object uid, String caption){
        
        listUsers.addItem(uid);
        listUsers.setItemCaption(uid, caption);
        
    }
    
    private void newTopic(){
        
        if(fieldNewTopicTitle.getValue() != null && !fieldNewTopicTitle.getValue().equals("")){
            
            newTopic(fieldNewTopicTitle.getValue());
            fieldNewTopicTitle.setValue(null);
            
        }
        
    }
    
    private void newTopic(String topicName){
        
        Integer logId = dataSetId.equals("") ? null : Integer.parseInt(dataSetId);
        
        MeetingTopicContainer mtc = new MeetingTopicContainer(taskManagerDataView, logId, 1, topicName);

        Tab tab = wrapperTopics.addTab(mtc, mtc.getTopTitle());
        mtc.setTab(wrapperTopics, tab);
        mtc.setSaveAction(mtc.new OnSave() {
            @Override
            public void saveAction() {
                dbTouch();
            }
        });
        
        wrapperTopics.setSelectedTab(tab);
        
        wrapperTopics.setHeight(null);
        layoutTopicsPanel.setHeight(null);
        
        
    }
    
    private void getTopics(){
        ContainerTool ct = new ContainerTool(dbGetTopics());
        ct.iterateItems(ct.new IterationInstruction() {
            
            @Override
            public void runInstruction(ContainerTool cti, Object itemId, Item item, Object[] objects) {

                MeetingTopicContainer mtc = new MeetingTopicContainer(taskManagerDataView, (Integer) item.getItemProperty("TMET_ID").getValue());
                Tab tab = wrapperTopics.addTab(mtc, mtc.getTopTitle());
                mtc.setTab(wrapperTopics, tab);
                mtc.setSaveAction(mtc.new OnSave() {
                    @Override
                    public void saveAction() {
                        dbTouch();
                    }
                });
                wrapperTopics.setHeight(null);
                layoutTopicsPanel.setHeight(null);
                
            }

        });
    }
    
    private void initTaskManager(){
        
        if(taskManagerDataView == null){
            taskManagerDataView = new TaskManagerDataView();
            taskManagerDataView.setPermissions(permCreate, permRead, permUpdate, permDelete);
            taskManagerDataView.setType(TTYPE.TASK);
            taskManagerDataView.initIntegratedMode();
        }
        
    }
    
    /*************************** Events *******************************/

    private void setEventListeners() {

        btn_save.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {

                saveForm();


                //TASK check if save successful
                UI.getCurrent().getUI().removeWindow(win);
            }

        });

       
    }

    private Integer saveForm(){
        
        if (validate() == false) {
            I18nManager.global(I18nGlobalNotifiers.fields_empty);
            return null;
        }
        
        if (dataSetId.equals("") == true) {
            
            dataSetId = Integer.toString(dbInsert());
            
        } else {
            
            dbUpdate();

        }
        
        for (Iterator iterator = wrapperTopics.iterator(); iterator.hasNext();) {
            try {
                MeetingTopicContainer mtc = (MeetingTopicContainer) iterator.next();
                mtc.setSaveAction(null); // no need to touch it during iteration
                mtc.saveTopic();    
            } catch (Exception e) {
                e.printStackTrace();
            }
            
        }
        
        dbSaveUsers();
        
        return Integer.parseInt(dataSetId);
    }
    
    /******************************************************************/
    
    /************************ --> Berrechtigung <-- **************************/

    @SuppressWarnings("unused")
    public void setPermissionsFromDatabase() {
        if (formIdPerm == "") {
            System.out.println("Form Einstellung Fehlt: Berechtigung");
            return;
        }

        
        Rechteholen r = new Rechteholen(ACC_ID + "");
        String[][] perms = r.Datenholen();

        for (int i = 0; i < perms.length; i++) {
            if (perms[i][0].equals(formIdPerm) == true) {

                permRead = Integer.valueOf(perms[i][3]);
                permUpdate = Integer.valueOf(perms[i][4]);
                permCreate = Integer.valueOf(perms[i][6]);
                permDelete = Integer.valueOf(perms[i][5]);
                
            }
        }
    }

    public void setPermissions(int create, int read, int update, int delete) {

        permCreate = create;
        permRead = read;
        permUpdate = update;
        permDelete = delete;

    }

    private void setMenuPermissions() {
        Boolean c = (permCreate == 1);
        Boolean r = (permRead == 1);
        Boolean u = (permUpdate == 1);
        Boolean d = (permDelete == 1);

        btn_save.setEnabled((c||u));

    }
    
    /***********************************************/
    
    private void fillFields(){
        
        UserContainer ucon = new UserContainer();
        ucon.fillCombo(fieldAddUser);
        ucon.fillCombo(fieldEditor);
        
        MeetingGroupContainer gcon = new MeetingGroupContainer();
        gcon.fillCombo(fieldTeam);
        
    }

    
    
    
    /******************** Database *****************/
    private void fillDbMap() {
        dbMap = new HashMap<>();
//        dbMap.put(component, "table:COLUMN");
        
        dbMap.put(fieldDate,  dataTableName + ":TMEL_DATE");
        dbMap.put(fieldTimeStart,  dataTableName + ":TMEL_TIME_START");
        dbMap.put(fieldTimeEnd,  dataTableName + ":TMEL_TIME_END");
        
        dbMap.put(fieldDateNext,  dataTableName + ":TMEL_NEXT_EVENT");
        
        dbMap.put(fieldEditor,  dataTableName + ":TMEL_ID_EDITOR");
        dbMap.put(fieldTeam,  dataTableName + ":TMEL_ID_TEAM");
        
        dbMap.put(fieldGuests,  dataTableName + ":TMEL_GUESTS");
        

    }

    private void dbFillForm() {
        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();

        /******************************** Table ****************************************/
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln(dataTableName);
        /******************************************************************************/
        /******************************** Filter ****************************************/
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein(dataTableName, dataIdCol, "=", dataSetId, "");
        /******************************************************************************/

        // db.DB_Data_Get.Set_Type("SLF_VON_UHRZEIT", Date.class);
        // db.DB_Data_Get.Set_Type("SLF_BIS_UHRZEIT", Date.class);

        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();
        fb = new Form_Bind();
        
        if(con.size() > 0){
        	fb.Get_and_Fill(con, dbMap);
        }
        
    }

    private void dbGetUsers(){
        
        String tbl = "cust_taskmanager_meeting_participants";
        
        DBClass db = new DBClass();

        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln(tbl);
        
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein(tbl, "TMEP_ID_MEETING", "=", dataSetId, "");
        
        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();
        
        if(con.size() > 0){
            
            for (Object cid : con.getItemIds()) {
                
                Integer uid = (Integer) con.getContainerProperty(cid, "TMEP_ID_USER").getValue();
                addParticipantUser(uid, fieldAddUser.getItemCaption(uid));
                
            }
            
            
        }
        
        labelUserCount.setValue(Integer.toString(listUsers.size()));
        
        
    }
    
    private void dbSaveUsers(){
        
//        TMEP_ID_MEETING
//        TMEP_ID_USER
        
        String tbl = "cust_taskmanager_meeting_participants";
        
        DBClass db = new DBClass();
        
        db.DB_Data_Delete.DB_Tabellen.DB_set_Tabelle_Einzeln(tbl);
        db.DB_Data_Delete.DB_Filter.DB_WHERE_Allgemein(tbl, "TMEP_ID_MEETING", "=", dataSetId, "");
        db.DB_Data_Delete.DB_Delete();

        db.DB_Data_Leeren();
        
        db.DB_Data_Insert.DB_Tabellen.DB_set_Tabelle_Einzeln(tbl);
        
        
        for (Object user : (Collection) listUsers.getItemIds()) {
            
            db.DB_Data_Insert.DB_Daten.DB_Data_Leeren();
            db.DB_Data_Insert.DB_Daten.DB_Data(tbl, "TMEP_ID_MEETING", dataSetId);
            db.DB_Data_Insert.DB_Daten.DB_Data(tbl, "TMEP_ID_USER", user.toString());
            db.DB_Data_Insert.DB_Insert();
        }
        
    }
    
    private int dbInsert() {
        DBClass db = new DBClass();
        fb = new Form_Bind();
        fb.Insert(db, dbMap);
        /******************************** Table ****************************************/
        db.DB_Data_Insert.DB_Tabellen.DB_set_Tabelle_Einzeln(dataTableName);
        /******************************************************************************/
        // dba.DB_Data_Insert.DB_DEBUG_SQL_STRING();
        return db.DB_Data_Insert.DB_Insert();
    }

    private void dbUpdate() {
        DBClass db = new DBClass();
        fb = new Form_Bind();
        fb.Update(db, dbMap);

        /******************************** Table ****************************************/
        db.DB_Data_Update.DB_Tabellen.DB_set_Tabelle_Einzeln(dataTableName);
        /******************************************************************************/
        /******************************** Filter ****************************************/
        db.DB_Data_Update.DB_Filter.DB_WHERE_Allgemein(dataTableName, dataIdCol, "=", dataSetId, "");
        /******************************************************************************/
        db.DB_Data_Update.DB_Update();
    }
    
    private void dbTouch() {
        DBClass db = new DBClass();
        
        db.DB_Data_Update.DB_Daten.DB_Data(dataTableName, "TMEL_UPDATED", MyUtils.formatSqlDate(new Date()));
        
        /******************************** Table ****************************************/
        db.DB_Data_Update.DB_Tabellen.DB_set_Tabelle_Einzeln(dataTableName);
        /******************************************************************************/
        /******************************** Filter ****************************************/
        db.DB_Data_Update.DB_Filter.DB_WHERE_Allgemein(dataTableName, dataIdCol, "=", dataSetId, "");
        /******************************************************************************/
        db.debugNextQuery(true);
        db.DB_Data_Update.DB_Update();

    }
    
    private Container dbGetTopics(){
        
        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_taskmanager_meeting_topics");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_taskmanager_meeting_topics", "TMET_ID_LOG", "=", dataSetId, "");
        
        return db.DB_Data_Get.DB_SEND_AND_GET_Container();
    }
    
    /*********************** -->Validierung<-- ********************/
    private void fillValidateMap() {
        validateMap = new HashMap<>();
        validateMap.putAll(componentMap);
        
//        ValidateMap.put(component, "component"); // should not be needed

    }

    private void setCustomValidators() {

        // psw_pass_1.addValidator(new Custom_Benutzerform_psw_ändern(psw_pass_1, psw_pass_2));

        /******* manual actions *******/

    }

    private boolean validate() {
        val_checker4 val = new val_checker4(validateMap);
        if (val.Is_Valid() == false) {
            return false;
        } else {
            return true;
        }

    }

    @AutoGenerated
    private VerticalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setStyleName("cust_margin_half_full_none_full");
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(true);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // main
        main = buildMain();
        mainLayout.addComponent(main);
        mainLayout.setExpandRatio(main, 9.0f);
        mainLayout.setComponentAlignment(main, new Alignment(48));
        
        // buttons
        buttons = buildButtons();
        mainLayout.addComponent(buttons);
        mainLayout.setComponentAlignment(buttons, new Alignment(48));
        
        return mainLayout;
    }

    @AutoGenerated
    private VerticalLayout buildMain() {
        // common part: create layout
        main = new VerticalLayout();
        main.setImmediate(false);
        main.setWidth("100.0%");
        main.setHeight("100.0%");
        main.setMargin(false);
        main.setSpacing(true);
        
        // panelHeader
        panelHeader = buildPanelHeader();
        main.addComponent(panelHeader);
        main.setComponentAlignment(panelHeader, new Alignment(48));
        
        // tabMain
        tabMain = buildTabMain();
        main.addComponent(tabMain);
        main.setExpandRatio(tabMain, 1.0f);
        
        return main;
    }

    @AutoGenerated
    private Panel buildPanelHeader() {
        // common part: create layout
        panelHeader = new Panel();
        panelHeader.setImmediate(false);
        panelHeader.setWidth("100.0%");
        panelHeader.setHeight("-1px");
        
        // verticalLayout_4
        verticalLayout_4 = buildVerticalLayout_4();
        panelHeader.setContent(verticalLayout_4);
        
        return panelHeader;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_4() {
        // common part: create layout
        verticalLayout_4 = new VerticalLayout();
        verticalLayout_4.setImmediate(false);
        verticalLayout_4.setWidth("100.0%");
        verticalLayout_4.setHeight("100.0%");
        verticalLayout_4.setMargin(false);
        verticalLayout_4.setSpacing(true);
        
        // layoutHeader
        layoutHeader = buildLayoutHeader();
        verticalLayout_4.addComponent(layoutHeader);
        
        return verticalLayout_4;
    }

    @AutoGenerated
    private HorizontalLayout buildLayoutHeader() {
        // common part: create layout
        layoutHeader = new HorizontalLayout();
        layoutHeader.setImmediate(false);
        layoutHeader.setWidth("100.0%");
        layoutHeader.setHeight("-1px");
        layoutHeader.setMargin(false);
        layoutHeader.setSpacing(true);
        
        // layoutDate
        layoutDate = buildLayoutDate();
        layoutHeader.addComponent(layoutDate);
        
        // fieldDateNext
        fieldDateNext = new PopupDateField();
        fieldDateNext.setCaption("nächster Termin");
        fieldDateNext.setImmediate(false);
        fieldDateNext.setWidth("100px");
        fieldDateNext.setHeight("-1px");
        layoutHeader.addComponent(fieldDateNext);
        
        // fieldTeam
        fieldTeam = new ComboBox();
        fieldTeam.setCaption("Team");
        fieldTeam.setImmediate(false);
        fieldTeam.setWidth("100.0%");
        fieldTeam.setHeight("-1px");
        layoutHeader.addComponent(fieldTeam);
        layoutHeader.setExpandRatio(fieldTeam, 1.0f);
        
        // fieldEditor
        fieldEditor = new ComboBox();
        fieldEditor.setCaption("Protokollant");
        fieldEditor.setImmediate(false);
        fieldEditor.setWidth("100.0%");
        fieldEditor.setHeight("-1px");
        layoutHeader.addComponent(fieldEditor);
        layoutHeader.setExpandRatio(fieldEditor, 1.0f);
        
        return layoutHeader;
    }

    @AutoGenerated
    private HorizontalLayout buildLayoutDate() {
        // common part: create layout
        layoutDate = new HorizontalLayout();
        layoutDate.setImmediate(false);
        layoutDate.setWidth("-1px");
        layoutDate.setHeight("-1px");
        layoutDate.setMargin(false);
        layoutDate.setSpacing(true);
        
        // fieldDate
        fieldDate = new PopupDateField();
        fieldDate.setCaption("Datum");
        fieldDate.setImmediate(false);
        fieldDate.setWidth("100px");
        fieldDate.setHeight("-1px");
        layoutDate.addComponent(fieldDate);
        layoutDate.setComponentAlignment(fieldDate, new Alignment(48));
        
        // fieldTimeStart
        fieldTimeStart = new CustomTimePicker();
        fieldTimeStart.setCaption("Von");
        fieldTimeStart.setImmediate(true);
        fieldTimeStart.setWidth("40px");
        fieldTimeStart.setHeight("-1px");
        layoutDate.addComponent(fieldTimeStart);
        layoutDate.setComponentAlignment(fieldTimeStart, new Alignment(48));
        
        // fieldTimeEnd
        fieldTimeEnd = new CustomTimePicker();
        fieldTimeEnd.setCaption("Bis");
        fieldTimeEnd.setImmediate(true);
        fieldTimeEnd.setWidth("40px");
        fieldTimeEnd.setHeight("-1px");
        layoutDate.addComponent(fieldTimeEnd);
        layoutDate.setComponentAlignment(fieldTimeEnd, new Alignment(48));
        
        return layoutDate;
    }

    @AutoGenerated
    private TabSheet buildTabMain() {
        // common part: create layout
        tabMain = new TabSheet();
        tabMain.setImmediate(true);
        tabMain.setWidth("100.0%");
        tabMain.setHeight("100.0%");
        
        // layoutParticipants
        layoutParticipants = buildLayoutParticipants();
        tabMain.addTab(layoutParticipants, "Teilnehmer", null);
        
        // layoutTopics
        layoutTopics = buildLayoutTopics();
        tabMain.addTab(layoutTopics, "Themen", null);
        
        return tabMain;
    }

    @AutoGenerated
    private HorizontalLayout buildLayoutParticipants() {
        // common part: create layout
        layoutParticipants = new HorizontalLayout();
        layoutParticipants.setImmediate(false);
        layoutParticipants.setWidth("100.0%");
        layoutParticipants.setHeight("100.0%");
        layoutParticipants.setMargin(false);
        layoutParticipants.setSpacing(true);
        
        // layoutUsers
        layoutUsers = buildLayoutUsers();
        layoutParticipants.addComponent(layoutUsers);
        layoutParticipants.setExpandRatio(layoutUsers, 2.0f);
        
        // layoutGuests
        layoutGuests = buildLayoutGuests();
        layoutParticipants.addComponent(layoutGuests);
        layoutParticipants.setExpandRatio(layoutGuests, 1.0f);
        
        return layoutParticipants;
    }

    @AutoGenerated
    private VerticalLayout buildLayoutUsers() {
        // common part: create layout
        layoutUsers = new VerticalLayout();
        layoutUsers.setCaption("Teilnehmer hinzufügen");
        layoutUsers.setImmediate(false);
        layoutUsers.setWidth("100.0%");
        layoutUsers.setHeight("100.0%");
        layoutUsers.setMargin(false);
        layoutUsers.setSpacing(true);
        
        // layoutAddUser
        layoutAddUser = buildLayoutAddUser();
        layoutUsers.addComponent(layoutAddUser);
        
        // listUsers
        listUsers = new ListSelect();
        listUsers.setImmediate(false);
        listUsers.setWidth("100.0%");
        listUsers.setHeight("100.0%");
        layoutUsers.addComponent(listUsers);
        layoutUsers.setExpandRatio(listUsers, 1.0f);
        
        return layoutUsers;
    }

    @AutoGenerated
    private HorizontalLayout buildLayoutAddUser() {
        // common part: create layout
        layoutAddUser = new HorizontalLayout();
        layoutAddUser.setImmediate(false);
        layoutAddUser.setWidth("100.0%");
        layoutAddUser.setHeight("-1px");
        layoutAddUser.setMargin(false);
        layoutAddUser.setSpacing(true);
        
        // fieldAddUser
        fieldAddUser = new ComboBox();
        fieldAddUser.setImmediate(false);
        fieldAddUser.setWidth("100.0%");
        fieldAddUser.setHeight("-1px");
        layoutAddUser.addComponent(fieldAddUser);
        layoutAddUser.setExpandRatio(fieldAddUser, 1.0f);
        
        // buttonAddUser
        buttonAddUser = new Button();
        buttonAddUser.setCaption("Hinzufügen");
        buttonAddUser.setImmediate(true);
        buttonAddUser.setWidth("100px");
        buttonAddUser.setHeight("-1px");
        layoutAddUser.addComponent(buttonAddUser);
        
        // labelUserCount
        labelUserCount = new Label();
        labelUserCount.setImmediate(false);
        labelUserCount.setWidth("-1px");
        labelUserCount.setHeight("-1px");
        labelUserCount.setValue("0");
        layoutAddUser.addComponent(labelUserCount);
        layoutAddUser.setComponentAlignment(labelUserCount, new Alignment(48));
        
        // buttonRemoveUsers
        buttonRemoveUsers = new Button();
        buttonRemoveUsers.setCaption("Ausgewählte entfernen");
        buttonRemoveUsers.setImmediate(true);
        buttonRemoveUsers.setWidth("-1px");
        buttonRemoveUsers.setHeight("-1px");
        layoutAddUser.addComponent(buttonRemoveUsers);
        
        return layoutAddUser;
    }

    @AutoGenerated
    private VerticalLayout buildLayoutGuests() {
        // common part: create layout
        layoutGuests = new VerticalLayout();
        layoutGuests.setImmediate(false);
        layoutGuests.setWidth("100.0%");
        layoutGuests.setHeight("100.0%");
        layoutGuests.setMargin(false);
        
        // fieldGuests
        fieldGuests = new TextArea();
        fieldGuests.setStyleName("cust_textarea_no_margin");
        fieldGuests.setCaption("Gäste");
        fieldGuests.setImmediate(false);
        fieldGuests.setWidth("100.0%");
        fieldGuests.setHeight("100.0%");
        layoutGuests.addComponent(fieldGuests);
        
        return layoutGuests;
    }

    @AutoGenerated
    private VerticalLayout buildLayoutTopics() {
        // common part: create layout
        layoutTopics = new VerticalLayout();
        layoutTopics.setImmediate(false);
        layoutTopics.setWidth("100.0%");
        layoutTopics.setHeight("100.0%");
        layoutTopics.setMargin(false);
        layoutTopics.setSpacing(true);
        
        // layoutNewTopic
        layoutNewTopic = buildLayoutNewTopic();
        layoutTopics.addComponent(layoutNewTopic);
        
        // panelTopics
        panelTopics = buildPanelTopics();
        layoutTopics.addComponent(panelTopics);
        layoutTopics.setExpandRatio(panelTopics, 1.0f);
        
        return layoutTopics;
    }

    @AutoGenerated
    private HorizontalLayout buildLayoutNewTopic() {
        // common part: create layout
        layoutNewTopic = new HorizontalLayout();
        layoutNewTopic.setImmediate(false);
        layoutNewTopic.setWidth("100.0%");
        layoutNewTopic.setHeight("-1px");
        layoutNewTopic.setMargin(false);
        layoutNewTopic.setSpacing(true);
        
        // fieldNewTopicTitle
        fieldNewTopicTitle = new TextField();
        fieldNewTopicTitle.setCaption("Neues Thema hinzufügen");
        fieldNewTopicTitle.setImmediate(false);
        fieldNewTopicTitle.setWidth("100.0%");
        fieldNewTopicTitle.setHeight("-1px");
        layoutNewTopic.addComponent(fieldNewTopicTitle);
        layoutNewTopic.setExpandRatio(fieldNewTopicTitle, 1.0f);
        
        // buttonNewTopicAdd
        buttonNewTopicAdd = new Button();
        buttonNewTopicAdd.setCaption("Hinzufügen");
        buttonNewTopicAdd.setImmediate(true);
        buttonNewTopicAdd.setWidth("-1px");
        buttonNewTopicAdd.setHeight("-1px");
        layoutNewTopic.addComponent(buttonNewTopicAdd);
        layoutNewTopic.setComponentAlignment(buttonNewTopicAdd, new Alignment(10));
        
        return layoutNewTopic;
    }

    @AutoGenerated
    private Panel buildPanelTopics() {
        // common part: create layout
        panelTopics = new Panel();
        panelTopics.setImmediate(false);
        panelTopics.setWidth("100.0%");
        panelTopics.setHeight("100.0%");
        
        // layoutTopicsPanel
        layoutTopicsPanel = buildLayoutTopicsPanel();
        panelTopics.setContent(layoutTopicsPanel);
        
        return panelTopics;
    }

    @AutoGenerated
    private VerticalLayout buildLayoutTopicsPanel() {
        // common part: create layout
        layoutTopicsPanel = new VerticalLayout();
        layoutTopicsPanel.setImmediate(false);
        layoutTopicsPanel.setWidth("100.0%");
        layoutTopicsPanel.setHeight("100.0%");
        layoutTopicsPanel.setMargin(false);
        
        // wrapperTopics
        wrapperTopics = new Accordion();
        wrapperTopics.setImmediate(false);
        wrapperTopics.setWidth("100.0%");
        wrapperTopics.setHeight("100.0%");
        layoutTopicsPanel.addComponent(wrapperTopics);
        layoutTopicsPanel.setExpandRatio(wrapperTopics, 1.0f);
        
        return layoutTopicsPanel;
    }

    @AutoGenerated
    private HorizontalLayout buildButtons() {
        // common part: create layout
        buttons = new HorizontalLayout();
        buttons.setImmediate(false);
        buttons.setWidth("100.0%");
        buttons.setHeight("-1px");
        buttons.setMargin(true);
        
        // btn_save
        btn_save = new Button();
        btn_save.setCaption("Speichern");
        btn_save.setImmediate(true);
        btn_save.setWidth("-1px");
        btn_save.setHeight("-1px");
        buttons.addComponent(btn_save);
        buttons.setComponentAlignment(btn_save, new Alignment(48));
        
        return buttons;
    }

}
