package archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.TicketPreferences.form;

import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Map.Entry;

import org.joda.time.LocalDate;

import archenoah.config.CMS_Config_Std;
import archenoah.lib.custom.ComponentIterator;
import archenoah.lib.tool.comunication.dbclass.DBClass;
import archenoah.lib.vaadin.Components.Combo.combo;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Tab_Menue_Item;
import archenoah.lib.vaadin.Components.Window_Tab_Generierer.Build_Window_Button;
import archenoah.lib.vaadin.Forms_Builder.Form_Bind;
import archenoah.lib.vaadin.Language.i18n.I18nCB;
import archenoah.lib.vaadin.Language.i18n.I18nGlobalNotifiers;
import archenoah.lib.vaadin.Language.i18n.I18nManager;
import archenoah.lib.vaadin.MenuBerechtigung.Rechteholen;
import archenoah.lib.vaadin.valchecker.val_checker4;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.OpenTickets.classes.TITYPE;
import archenoah.web.normal.main.Menuepunkte.Individuelle.Ordermanager.TicketPreferences.classes.LngTicketLengthConverter;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.ui.AbstractField;
import com.vaadin.ui.AbstractSelect.NewItemHandler;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

@SuppressWarnings({ "serial", "rawtypes" })
public class TicketPreferencesInsertEdit extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private VerticalLayout mainLayout;

    @AutoGenerated
    private HorizontalLayout buttons;

    @AutoGenerated
    private Button btn_save;

    @AutoGenerated
    private HorizontalLayout main;

    @AutoGenerated
    private LocationPanel locationPanelModule;

    @AutoGenerated
    private Panel preferencePanel;

    @AutoGenerated
    private VerticalLayout preferencePanelLayout;

    @AutoGenerated
    private ComboBox preferenceShippingCompany;

    @AutoGenerated
    private ComboBox preferenceInterval;

    @AutoGenerated
    private ComboBox preferenceDayOfWeek;

    @AutoGenerated
    private PopupDateField preferenceStartDate;

    @AutoGenerated
    private ComboBox preferenceUser;

    

    

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */

    /**************** --> Allgemein <--- ********************/
    
    private org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(this.getClass());
    
    // Allgemein
    private CMS_Config_Std std;
    private String exportCaption;
    
    // Datenbank
    private Map<Object, String> componentMap;
    private Map<Object, String> dbMap;
    private Map<Object, String> validateMap;
    private Form_Bind fb;
    private String dataSetId = "";

    
    // Berrechtigung
    private int ACC_ID;
	private Integer permRead;
	private Integer permUpdate;
	private Integer permCreate;
	private Integer permDelete;

    private MenuItem tmpMenu = null;
    private Button tmpButton = null;
    /******************************************************/
    /**************** --> Tabsheetvars <--- *****************/
    private TabSheet tab = null;
    /******************************************************/
    /**************** --> Windowvars <--- *******************/
    private Window win = null;
    /******************************************************/
    /******************* --> Custom <--- ********************/
    /******************************************************/
    

    
    /************ ----->Einstellungen<-- ********************/
//    private final String formIdLng = "1031";
    private final String formIdPerm = "1031";
    private final String Windows_Height = "550px";
    private final String Windows_Width = "560px";
    
    private final String dataIdCol = "OMPR_ID";

    private I18nManager i18n;
    
    private final static class caption extends I18nCB {
        static final I18nCB quickselect_new = set();
    }
    
    /******************************************************/

    public TicketPreferencesInsertEdit(MenuItem Arg_Menü, String Arg_Form_ID) {
        tmpMenu = Arg_Menü;
        dataSetId = Arg_Form_ID;
    }

    public TicketPreferencesInsertEdit(Button Arg_btn, String Arg_Form_ID) {
        tmpButton = Arg_btn;
        dataSetId = Arg_Form_ID;
    }

    /********* INIT-Window ************/
    public void init() {
        if (Windows_Height.equals("") == true || Windows_Width.equals("") == true) {
            System.out.println("Form Einstellung Fehlt: !!!");
            return;
        }

        Standard_Init();

        String fid = dataSetId;
        if (fid != "") {
            fid = " - #" + fid;
        }

        if (tmpMenu != null) {
        	
            String Recourcename = null;
            ThemeResource resource = null;
            if(tmpMenu.getIcon() != null){
            	Recourcename = tmpMenu.getIcon().toString();
            	Recourcename = Recourcename.substring(0, Recourcename.length() - 12) + "white-16.png";
            	resource = new ThemeResource(Recourcename);
            }

            exportCaption = tmpMenu.getText();
            Build_Window_Button bwb = new Build_Window_Button(tmpMenu.getText() + fid, mainLayout, Windows_Height, Windows_Width, resource);
            win = bwb.ReturnWindow();
        }
        if (tmpButton != null) {
            exportCaption = tmpButton.getCaption();
            Build_Window_Button bwb = new Build_Window_Button(tmpButton.getCaption() + fid, mainLayout, Windows_Height, Windows_Width, tmpButton.getIcon());
            win = bwb.ReturnWindow();
        }

    }

    /********* INIT-Tray ************/
    public void init(TabSheet Arg_tab) {

        Standard_Init();
        tab = Arg_tab;
        if (tmpMenu != null) {
            exportCaption = tmpMenu.getText();
            new Build_Tab_Menue_Item(Arg_tab, tmpMenu.getText(), mainLayout, tmpMenu.getIcon());
        }
        if (tmpButton != null) {
            exportCaption = tmpButton.getCaption();
            new Build_Tab_Menue_Item(Arg_tab, tmpButton.getCaption(), mainLayout, tmpButton.getIcon());
        }

    }
    
    public Window getWindow(){
    	return win;
    }
    
    public TabSheet getTabSheet(){
    	return tab;
    }
    
    /********* Init-Standard ************/
    private void Standard_Init() {
        buildMainLayout();
        i18n = new I18nManager(this);
        

        ACC_ID = (int) UI.getCurrent().getSession().getSession().getAttribute("Userid");
        
        registerComponents();

        
        fillFields();
        fillDbMap();

        setCustomValidators();
        fillValidateMap();

        /***************/

        if (dataSetId != "") {
        	
            dbFillForm();
            
//            if(useLocation.getValue()){
//            	fillLocationFieldsCustom((Integer) locationQuickSelect.getValue());
//            }else{
//            	fillLocationFieldsUser((Integer) preferenceUser.getValue());	
//            }
            
           	
            

            
        } else {
            
        	//TASK "create init"
        	
        }

        setMenuPermissions();
        configureComponents();
        
        setEventListeners();
        
    }
    
 // register components for lng and validation tools
    private void registerComponents(){
    	componentMap = new HashMap<Object, String>();
    	new ComponentIterator(main).createMap(componentMap);
    	
    	
//    	iterateR(main.iterator(), componentMap);
    	
    }
    
   
	private void configureComponents(){
    	
    	for (Entry<Object, String> entry : componentMap.entrySet()) {
    		AbstractField field = (AbstractField) entry.getKey();
    		
			field.setImmediate(true);
			
			
			if(field instanceof ComboBox){
				((ComboBox)field).setFilteringMode(FilteringMode.CONTAINS);
			}
			
			if(!(field instanceof PopupDateField)){
				field.setWidth("180px");
			}
		}
    	
    	preferenceUser.setNullSelectionAllowed(false);
    	if (dataSetId != "") {
    		preferenceUser.setEnabled(false);
    		preferenceUser.setStyleName("nogrey");
    	}else{
    		preferenceUser.setRequired(true);
    		preferenceUser.setNullSelectionAllowed(false);
    	}
    	
    	preferenceUser.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                locationPanelModule.setUser((Integer) event.getProperty().getValue());
                
            }
        });
    	
    	Boolean noDate = (preferenceStartDate.getValue() == null);
    	
    	preferenceStartDate.setEnabled(noDate);
    	if(noDate){
        	preferenceStartDate.addValueChangeListener(new ValueChangeListener() {
                
                @Override
                public void valueChange(ValueChangeEvent event) {
                    
                    setDayOfWeek();
                }
            });
    	}
    	setDayOfWeek();
    	
    	preferenceDayOfWeek.setRequired(true);
    	preferenceDayOfWeek.setEnabled(!noDate);
    	preferenceDayOfWeek.setNullSelectionAllowed(noDate);
    	if(noDate){
    	    preferenceDayOfWeek.setValue(null);
    	}
    	preferenceDayOfWeek.addValueChangeListener(new ValueChangeListener() {
            
            @Override
            public void valueChange(ValueChangeEvent event) {
                
                if(preferenceDayOfWeek.getValue() == null){
                    return;
                }
                
                LocalDate date = new LocalDate(preferenceStartDate.getValue());
                Integer dow = Integer.valueOf(date.getDayOfWeek());
                
                Integer ndow = (Integer) preferenceDayOfWeek.getValue();
                if(ndow - dow != 0){
                    preferenceStartDate.setValue(date.plusDays(ndow - dow).toDate());
                }

            }
        });
    	
    	preferenceInterval.setRequired(true);
    	preferenceInterval.setNullSelectionAllowed(false);
    	
    	
    	preferenceShippingCompany.setNewItemsAllowed(true);
    	preferenceShippingCompany.setNewItemHandler(new NewItemHandler() {

            @Override
            public void addNewItem(String newItemCaption) {
                handleNewCompany(newItemCaption);
            }
        });
    	
    	componentListeners();

    }
    
	private void setDayOfWeek(){
        LocalDate date = new LocalDate(preferenceStartDate.getValue());
        Integer dow = Integer.valueOf(date.getDayOfWeek());
        if(preferenceDayOfWeek.getValue() != dow){
            
            Boolean validId = preferenceDayOfWeek.containsId(dow);
            
            preferenceDayOfWeek.setValue(validId ? dow : null);
        }
	}
	
    private void handleNewCompany(String caption) {
        int result = dbSaveNewCompany(caption);
        if (result != 0) {
            fillShippingCompaniesSelect();
            preferenceShippingCompany.select(result);
        }
    }
	
    private void componentListeners(){
    	
    	
    	
//		preferenceUser.addValueChangeListener(listenerLocation);
    	
    	
    }
    
    /*************************** Events *******************************/

    private void setEventListeners() {

        btn_save.addClickListener(new ClickListener() {

            @Override
            public void buttonClick(ClickEvent event) {

            	Boolean success = false;
            	
                if (validate() == false) {
                    I18nManager.global(I18nGlobalNotifiers.fields_empty);
                    return;
                }

                
                if (dataSetId.equals("") == true) {
                	
                	if(checkUserPreferenceExists()){
                		I18nManager.global(I18nGlobalNotifiers.entry_exists);
                		return;
                	}
                		
//                	checkAndSaveLocationEntry();
            		dataSetId = Integer.toString(dbInsert());
            		
            		success = (!dataSetId.equals("0"));
                    
                   
                } else {
//                	checkAndSaveLocationEntry();
                    dbUpdate();
                    success = true;
                }

                if(success){
                	UI.getCurrent().getUI().removeWindow(win);
                }else{
                	//TASK notifier message
                	System.out.println("something broke");
                }
                
            }

        });
        
    }

    /******************************************************************/
    
    private Integer checkAndSaveLocationEntry(){
    	
    	Integer id = 0;
    	
    	
    	return id;
    	
    }
    
    /************************ --> Berrechtigung <-- **************************/

    @SuppressWarnings("unused")
    public void setPermissionsFromDatabase() {
        if (formIdPerm == "") {
            System.out.println("Form Einstellung Fehlt: Berechtigung");
            return;
        }

        
        Rechteholen r = new Rechteholen(ACC_ID + "");
        String[][] perms = r.Datenholen();

        for (int i = 0; i < perms.length; i++) {
            if (perms[i][0].equals(formIdPerm) == true) {

                permRead = Integer.valueOf(perms[i][3]);
                permUpdate = Integer.valueOf(perms[i][4]);
                permCreate = Integer.valueOf(perms[i][6]);
                permDelete = Integer.valueOf(perms[i][5]);
                
            }
        }
    }

    public void setPermissions(int create, int read, int update, int delete) {

        permCreate = create;
        permRead = read;
        permUpdate = update;
        permDelete = delete;

    }

    @SuppressWarnings("unused")
	private void setMenuPermissions() {
        Boolean c = (permCreate == 1);
        Boolean r = (permRead == 1);
        Boolean u = (permUpdate == 1);
        Boolean d = (permDelete == 1);

        btn_save.setEnabled((c||u));

    }
    
    /***********************************************/
    
    
    private void fillFields(){
    	
    	fillUser();
    	fillDayOfWeek();
    	fillInterval();
    	fillShippingCompaniesSelect();
    	
    }
    

    private void fillUser(){

        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("AUL_ID");
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("CONCAT(KSK_TITEL,' ',KSA_NAME,' ',AUL_NAME,' ',AUL_VORNAME)", "nurse");

        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_stammdaten_user", "INNER JOIN", "cust_krankenschwester_stammdaten_anrede", "AUL_ANREDE_ID", "KSA_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_stammdaten_user", "LEFT JOIN", "cms_auth_liste_gu", "AUL_ID", "AL_U_ID");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cms_auth_liste_gu", "RIGHT JOIN", "cust_projekte_stammdaten_liste", "AL_G_ID", "PSLV_GROUP");
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Verknüpfung("cust_krankenschwester_stammdaten_ks", "INNER JOIN", "cms_auth_stammdaten_user", "KSK_U_ID", "AUL_ID");

        // db.DB_Data_Get.DB_DEBUG_SQL_STRING();

        try {
            new combo(db.DB_Data_Get.DB_SEND_AND_GET(), preferenceUser, "AUL_ID", "nurse");
        } catch (Exception e) {
        	preferenceUser.removeAllItems();
            return;
        }
    }
    
    private void fillDayOfWeek(){
    	
        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_ordermanager_master_weekdays");
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_ordermanager_master_weekdays", "OMWW_ENABLED", "=", "1", "");
        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();
        
        SimpleDateFormat sdf = new SimpleDateFormat("EEEE");
        Calendar cal = Calendar.getInstance();
        
        if(con.size() > 0){
            
            Iterator it = con.getItemIds().iterator();
            while (it.hasNext()) {
                Item weekday = con.getItem(it.next());
                Integer day = (Integer) weekday.getItemProperty("OMMW_ID").getValue();
                
                // 0 = Samstag
                cal.set(Calendar.DAY_OF_WEEK, day+1);
                preferenceDayOfWeek.addItem(day);
                preferenceDayOfWeek.setItemCaption(day, sdf.format(cal.getTime()));
                
            }
            
        }

    }
    
    private void fillInterval(){
    	
    	new LngTicketLengthConverter().attachDatasource(preferenceInterval);
    	
    }
    


    private void fillShippingCompaniesSelect(){
    	
    	DBClass db = new DBClass();
    	
    	db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("SC_ID");
    	db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_Einzeln("SC_NAME");
    	db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_shipping_companies");
    	
        try {
        	preferenceShippingCompany.removeAllItems();
            new combo(db.DB_Data_Get.DB_SEND_AND_GET(), preferenceShippingCompany, "SC_ID", "SC_NAME");
        } catch (Exception e) {
        	preferenceShippingCompany.removeAllItems();
            return;
        }
    	
    }
    
    

    /**
     * 
     * @return true if user already has an entry
     */
    private Boolean checkUserPreferenceExists(){
    	
    	DBClass db = new DBClass();
    	db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();
    	db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_ordermanager_preferences");
    	db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_ordermanager_preferences", "OMPR_ID_USER", "=", preferenceUser.getValue().toString(), "");
    	
    	return (db.DB_Data_Get.DB_SEND_AND_GET_Container().size() > 0);
    	
    }
    
    /******************** Database *****************/
    
    
    private void fillDbMap() {
        dbMap = new HashMap<>();
//        dbMap.put(component, "table:COLUMN");
        dbMap.put(preferenceUser, "cust_ordermanager_preferences:OMPR_ID_USER");
        dbMap.put(preferenceDayOfWeek, "cust_ordermanager_preferences:OMPR_DAYOFWEEK");
        dbMap.put(preferenceInterval, "cust_ordermanager_preferences:OMPR_TICKET_LENGTH");
        
        dbMap.put(preferenceShippingCompany, "cust_ordermanager_preferences:OMPR_ID_SHIPPING_COMPANY");
        dbMap.put(preferenceStartDate, "cust_ordermanager_preferences:OMPR_DATE_START");
        


    }
    
    private void dbFillForm() {
        DBClass db = new DBClass();
        db.DB_Data_Get.DB_Spalten.Standard.DB_set_Spalten_All();

        /******************************** Table ****************************************/
        db.DB_Data_Get.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_ordermanager_preferences");
        /******************************************************************************/
        /******************************** Filter ****************************************/
        db.DB_Data_Get.DB_Filter.DB_WHERE_Allgemein("cust_ordermanager_preferences", dataIdCol, "=", dataSetId, "");
        /******************************************************************************/

        db.DB_Data_Get.Set_Type("OMPR_START", Date.class);
        // db.DB_Data_Get.Set_Type("SLF_BIS_UHRZEIT", Date.class);
        
        db.debugNextQuery(false);
        
        Container con = db.DB_Data_Get.DB_SEND_AND_GET_Container();
        fb = new Form_Bind();
        
        if(con.size() > 0){
        	fb.Get_and_Fill(con, dbMap);
        	locationPanelModule.setEntryType(TITYPE.NURSE);
        	locationPanelModule.setUser((Integer) con.getContainerProperty(con.getItemIds().iterator().next(), "OMPR_ID_USER").getValue());
        	locationPanelModule.setValue((Integer) con.getContainerProperty(con.getItemIds().iterator().next(), "OMPR_ID_LOCATION").getValue());
        }

    }

    private int dbInsert() {
        DBClass db = new DBClass();
        fb = new Form_Bind();
        fb.Insert(db, dbMap);
        
        Integer locationId = locationPanelModule.getValue();
        db.DB_Data_Insert.DB_Daten.DB_Data("cust_ordermanager_preferences", "OMPR_ID_LOCATION", locationId != null ? locationId.toString() : null);
        db.DB_Data_Insert.DB_Daten.DB_Data("cust_ordermanager_preferences", "OMPR_USE_CUSTOM_LOCATION", locationId != null ? "1" : "0");
        
        /******************************** Table ****************************************/
        db.DB_Data_Insert.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_ordermanager_preferences");
        /******************************************************************************/
        // dba.DB_Data_Insert.DB_DEBUG_SQL_STRING();
        return db.DB_Data_Insert.DB_Insert();
    }

    private void dbUpdate() {
        DBClass db = new DBClass();
        fb = new Form_Bind();
        fb.Update(db, dbMap);
        
        Integer locationId = locationPanelModule.getValue();
        db.DB_Data_Update.DB_Daten.DB_Data("cust_ordermanager_preferences", "OMPR_ID_LOCATION", locationId != null ? locationId.toString() : null);
        db.DB_Data_Update.DB_Daten.DB_Data("cust_ordermanager_preferences", "OMPR_USE_CUSTOM_LOCATION", locationId != null ? "1" : "0");
        
        /******************************** Table ****************************************/
        db.DB_Data_Update.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_ordermanager_preferences");
        /******************************************************************************/
        /******************************** Filter ****************************************/
        db.DB_Data_Update.DB_Filter.DB_WHERE_Allgemein("cust_ordermanager_preferences", dataIdCol, "=", dataSetId, "");
        /******************************************************************************/
        db.DB_Data_Update.DB_Update();

    }

    private int dbSaveNewCompany(String caption) {
        DBClass db = new DBClass();

        db.DB_Data_Insert.DB_Tabellen.DB_set_Tabelle_Einzeln("cust_shipping_companies");
        db.DB_Data_Insert.DB_Daten.DB_Data("cust_shipping_companies", "SC_NAME", caption);

        int result = db.DB_Data_Insert.DB_Insert();

        return result;
    }

    /*********************** -->Validierung<-- ********************/
    private void fillValidateMap() {
        validateMap = new HashMap<>();
        validateMap.putAll(componentMap);
        
//        ValidateMap.put(component, "component"); // should not be needed

    }

    private void setCustomValidators() {

        // psw_pass_1.addValidator(new Custom_Benutzerform_psw_ändern(psw_pass_1, psw_pass_2));

        /******* manual actions *******/

    }

    private boolean validate() {
        val_checker4 val = new val_checker4(validateMap);
        if (val.Is_Valid() == false) {
            return false;
        } else {
            return true;
        }

    }

    @AutoGenerated
    private VerticalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setStyleName("cust_margin_half_full_none_full");
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(true);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // main
        main = buildMain();
        mainLayout.addComponent(main);
        mainLayout.setExpandRatio(main, 8.0f);
        
        // buttons
        buttons = buildButtons();
        mainLayout.addComponent(buttons);
        mainLayout.setExpandRatio(buttons, 1.0f);
        mainLayout.setComponentAlignment(buttons, new Alignment(48));
        
        return mainLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildMain() {
        // common part: create layout
        main = new HorizontalLayout();
        main.setImmediate(false);
        main.setWidth("100.0%");
        main.setHeight("100.0%");
        main.setMargin(false);
        main.setSpacing(true);
        
        // preferencePanel
        preferencePanel = buildPreferencePanel();
        main.addComponent(preferencePanel);
        
        // locationPanelModule
        locationPanelModule = new LocationPanel();
        locationPanelModule.setImmediate(false);
        locationPanelModule.setWidth("100.0%");
        locationPanelModule.setHeight("100.0%");
        main.addComponent(locationPanelModule);
        
        return main;
    }

    @AutoGenerated
    private Panel buildPreferencePanel() {
        // common part: create layout
        preferencePanel = new Panel();
        preferencePanel.setCaption("Grundeinstellungen");
        preferencePanel.setImmediate(false);
        preferencePanel.setWidth("100.0%");
        preferencePanel.setHeight("280px");
        
        // preferencePanelLayout
        preferencePanelLayout = buildPreferencePanelLayout();
        preferencePanel.setContent(preferencePanelLayout);
        
        return preferencePanel;
    }

    @AutoGenerated
    private VerticalLayout buildPreferencePanelLayout() {
        // common part: create layout
        preferencePanelLayout = new VerticalLayout();
        preferencePanelLayout.setImmediate(false);
        preferencePanelLayout.setWidth("100.0%");
        preferencePanelLayout.setHeight("100.0%");
        preferencePanelLayout.setMargin(true);
        
        // preferenceUser
        preferenceUser = new ComboBox();
        preferenceUser.setCaption("Krankenschwester");
        preferenceUser.setImmediate(false);
        preferenceUser.setWidth("-1px");
        preferenceUser.setHeight("-1px");
        preferencePanelLayout.addComponent(preferenceUser);
        preferencePanelLayout.setComponentAlignment(preferenceUser, new Alignment(48));
        
        // preferenceStartDate
        preferenceStartDate = new PopupDateField();
        preferenceStartDate.setCaption("Startdatum");
        preferenceStartDate.setImmediate(false);
        preferenceStartDate.setWidth("-1px");
        preferenceStartDate.setHeight("-1px");
        preferencePanelLayout.addComponent(preferenceStartDate);
        preferencePanelLayout.setComponentAlignment(preferenceStartDate, new Alignment(48));
        
        // preferenceDayOfWeek
        preferenceDayOfWeek = new ComboBox();
        preferenceDayOfWeek.setCaption("Wunschtermin Wochentag");
        preferenceDayOfWeek.setImmediate(false);
        preferenceDayOfWeek.setWidth("-1px");
        preferenceDayOfWeek.setHeight("-1px");
        preferencePanelLayout.addComponent(preferenceDayOfWeek);
        preferencePanelLayout.setComponentAlignment(preferenceDayOfWeek, new Alignment(48));
        
        // preferenceInterval
        preferenceInterval = new ComboBox();
        preferenceInterval.setCaption("Sendungsintervall");
        preferenceInterval.setImmediate(false);
        preferenceInterval.setWidth("-1px");
        preferenceInterval.setHeight("-1px");
        preferencePanelLayout.addComponent(preferenceInterval);
        preferencePanelLayout.setComponentAlignment(preferenceInterval, new Alignment(48));
        
        // preferenceShippingCompany
        preferenceShippingCompany = new ComboBox();
        preferenceShippingCompany.setCaption("Spedition");
        preferenceShippingCompany.setImmediate(false);
        preferenceShippingCompany.setWidth("-1px");
        preferenceShippingCompany.setHeight("-1px");
        preferencePanelLayout.addComponent(preferenceShippingCompany);
        preferencePanelLayout.setComponentAlignment(preferenceShippingCompany, new Alignment(48));
        
        return preferencePanelLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildButtons() {
        // common part: create layout
        buttons = new HorizontalLayout();
        buttons.setImmediate(false);
        buttons.setWidth("100.0%");
        buttons.setHeight("100.0%");
        buttons.setMargin(false);
        
        // btn_save
        btn_save = new Button();
        btn_save.setCaption("Speichern");
        btn_save.setImmediate(true);
        btn_save.setWidth("-1px");
        btn_save.setHeight("-1px");
        buttons.addComponent(btn_save);
        buttons.setComponentAlignment(btn_save, new Alignment(48));
        
        return buttons;
    }

}
